# -*- coding: utf-8 -*-
CHAPTER = {
    "num": 7,
    "title": "Personality",
    "authors": "Elysia R. Todd and David C. Funder",
    "domain": "Nonverbal Communication | Personality",
    "scrub": (
        "Zero Acquaintance: Judging Personality from Thin Slices",
        "Inspect a series of strangers captured in silent video clips and still photographs, and make personality judgments before a single word is spoken. Track whether your snap judgments agree with self-reports and acquaintance ratings, then reflect on which nonverbal cues carried the accuracy.",
        "A wall of monitors displays silent clips of targets walking into a room, reading a weather report, and posing for stills. A scoreboard compares your judgments against self-reported Big Five profiles, highlighting the cues that made accurate impressions possible.",
        [
            "From the moment you meet another person, before he or she has uttered a single word, you begin to make inferences about his or her personality.",
            "Decades of research on personality judgments made at zero acquaintance shows that these assessments are made quickly and with a certain degree of accuracy.",
            "Behavior is not just what a person does but how he or she does it, and expressive style and patterns of nuance in behavior are major vehicles for communicating personal identity.",
            "The Big Five framework organizes the domain of personality in terms of the broad traits of Extraversion, Neuroticism, Conscientiousness, Agreeableness, and Openness to Experience.",
            "Judgments of strangers based on limited information correlate well with self-reports of personality and with ratings made by long-term acquaintances.",
            "The consistent finding that strangers can judge personality accurately suggests that there must be cues in nonverbal behavior that are indicative of personality.",
            "Relative or rank-order consistency, rather than absolute consistency, may reveal consistent behavioral patterns that can be predicted by personality traits.",
            "Allport and Vernon (1933) demonstrated decades ago how personality may be expressed via observable cues.",
            "The person-situation debate taught that it is unwise to focus on one behavior or one situation when attempting to assess correlates between traits and behavior.",
            "Even at zero acquaintance, intelligence can be accurately judged to a certain degree, so there must be some nonverbal indicators that are indicative of a person's intelligence.",
            "Aggregating behaviors across situations, assessing behaviors at more general levels of analysis, and using better standardized measures are methodological gains made in personality research.",
            "Findings of weak or no relationships between a personality variable and specific isolated nonverbal behaviors might be better illuminated by assessing broader patterns of nonverbal behavior.",
        ],
    ),
    "dialogue": (
        "Extraversion and Expressive Style",
        "Observe video-recorded triads, dyads, and solo speakers, and code nonverbal behaviors such as nodding, gesturing, posture, smiling, and speech cadence. Sort participants by their extraversion scores and see which expressive behaviors reliably distinguish extraverts from introverts.",
        "Side-by-side video panels show unacquainted triads in 15-minute conversations and a student delivering an advertisement-style talk. A live coding overlay ticks off gestures, nods, smiles, and voice traits while a correlation heatmap fills with extraversion.",
        [
            "Extraverts appear outgoing, talkative, and energetic, and they are relatively likely to enjoy time spent with people and find less reward in time spent alone.",
            "La France, Heisel, and Beatty (2004) meta-analyzed the literature on extraversion and nonverbal behavior and reported a mean correlation of .13 between extraversion and the various behaviors measured.",
            "Gifford (1994) found that people higher in extraversion exhibited more nods, more time spent gesturing, less tendency to wrap arms across the body, more left leg lean, and less leg movement.",
            "Lippa (1998) found that extraverts demonstrated clearer enunciation of their words and speech that was faster and more rhythmic in cadence.",
            "Berry and Hansen (2000) found a positive relationship between extraversion and gesturing in video-recorded interactions among unacquainted pairs of women.",
            "Funder and Sneed (1993) found that extraversion was positively related to enthusiasm, energy level, expressivity, physical animation, physical contact and proximity, and engagement in the interaction.",
            "Borkenau and Liebler (1995) found that higher self-reported extraversion was rated as friendlier, with more self-assured expressions, more smiling, higher foot lift while walking, and more arm swing.",
            "Extraversion is positively associated with speaking more and with a louder voice, and it is also related to pleasantness of voice and more upright posture.",
            "Expressivity, in its many different forms, seems to be the behavior most indicative of extraversion, and it is the aspect of nonverbal behavior most frequently researched in relation to this trait.",
            "H. R. Riggio and Riggio's (2002) meta-analysis concluded that, overall, there is a significant positive relationship between extraversion and expressivity in general.",
            "Gross and John (1995) found that their self-report measure of positive emotional expressivity was positively related to extraversion, which had the strongest personality-to-expressivity relationship of the Big Five.",
            "Behavioral correlates of extraversion such as voice volume, upright posture, and greater energy seem generally congruent with the concept of extraversion.",
        ],
    ),
    "audit": (
        "Decoding Others: Personality and Nonverbal Sensitivity",
        "Take on the role of a judge decoding silent clips, posed faces, and content-filtered audio, then compare your accuracy against personality profiles. Trace how trait anxiety, extraversion, and introversion shift decoding accuracy and perceptual biases.",
        "A quiz interface flashes 2-second PONS clips and Ekman face photos while a sidebar charts each participant's anxiety and extraversion scores. A leakage panel highlights moments when body channels betray what the face intends to show.",
        [
            "Decoding is the act of perceiving and interpreting nonverbal behavior, and research shows important individual differences in sensitivity to the nonverbal communications of others.",
            "Cunningham (1977) found that people who scored higher on neuroticism were generally more successful in decoding emotional expressions, particularly in the face over the voice and body channels.",
            "Surcinelli et al. (2006) found that participants who scored higher in nonclinical trait anxiety were more successful than their less anxious peers at detecting the emotional response of fear in faces viewed for 10 seconds.",
            "Cooper, Rowe, and Penton-Voak (2008) were unable to replicate the anxiety and emotion recognition finding when the presentation time of the stimuli was reduced to 4 seconds.",
            "Akert and Panter (1988) found that extraverts were significantly more accurate in interpreting the meaning of nonverbal communication than introverts and were more confident in their accuracy.",
            "Lieberman and Rosenthal (2001) found that introverts are less able to multitask and therefore are poorer at nonverbal decoding only when it is not the only task they are attempting to accomplish.",
            "Leakage refers to the finding that people are better able to control their facial expressions than their body's nonverbal expressions.",
            "Puccinelli and Tickle-Degnen (2004) found that people particularly capable at reading unintentional, leaking nonverbal information were more likely to make their interaction partners uncomfortable.",
            "Knyazev et al. (2008) found that people higher in trait anxiety were more likely to perceive all faces as being more hostile, whereas extraverts showed a pleasant bias in perceiving happy faces as more friendly.",
            "Matsumoto et al. (2000) found positive correlations between openness and conscientiousness and performance in decoding posed nonverbal expressions of facial affect across three of their studies.",
            "Nowicki and Duke (1994) found that children's accuracy in recognizing emotions from posed face, voice, and body-posture stimuli increased with age and was positively related to social adjustment but not to IQ.",
            "The correlates of nonverbal decoding ability do not compose a clear picture, as beneficial variables such as social adjustment and extraversion and less positive variables such as neuroticism and anxiety both show positive relationships in some findings.",
        ],
    ),
    "matrix": (
        "Encoding: Sending the Signal",
        "Encode emotions in posed and spontaneous conditions, silently acting out simple social scenarios while peers guess the scenario and valence you were assigned. Score your encoding accuracy against personality measures and compare performance-based with self-reported expressivity.",
        "A soundstage with a single chair is set for participants to act out everyday scenarios in positive, negative, or neutral manners. Observers click which scene was portrayed while encoding scores stream onto a leaderboard beside NEO and Q-sort profiles.",
        [
            "Encoding is the act of displaying emotions or communicating nonverbally, and efficacy in encoding information is an ability or skill that differs between persons and is somewhat stable.",
            "Nonverbal encoding has a weak history of research, partly because assessing encoding with performance measures requires both a participant to perform and multiple observers to rate the performance for each encoder.",
            "R. E. Riggio, Widaman, and Friedman (1985), R. E. Riggio and Friedman (1986), and Buck (1975) found that extraverts were better at accurately encoding nonverbal expression than introverts.",
            "People who scored higher on neuroticism were generally less successful in encoding posed emotional facial expressions.",
            "Cunningham (1977) found that extraversion was positively related to emotion encoding ability in both the posed and spontaneous conditions.",
            "H. R. Riggio and Riggio's (2002) meta-analysis demonstrated a relatively stable relationship between extraversion and emotional expressiveness.",
            "In the meta-analysis, self-reports of expressivity had the strongest relationship to extraversion, but posed and spontaneous performance measures of expressivity also demonstrated a reliable relationship to neuroticism.",
            "Tucker and Friedman (1993) found that nonverbally skilled, charismatic participants were higher in extraversion and expressivity when judged on natural interaction, describing a past emotional experience, and posing basic emotional expressions.",
            "It is unwise to assume that the ability to intentionally pose an expression is psychologically equivalent to how clearly the face expresses emotion in motion, because separate brain systems are involved in posing intentional and spontaneous facial expressions.",
            "In Todd and Bernieri's (2014) nonverbal acting task, encoding scores correlated positively with empathy and other social skill measures but negligibly with NEO Five-Factor Inventory and California Adult Q-Sort personality measures.",
            "It is not too difficult to imagine a person who is very expressive but frequently fails to express him- or herself accurately.",
            "There are very few studies measuring nonverbal encoding ability, and even fewer that relate that ability to measures of personality.",
        ],
    ),
    "boss": (
        "Status, Dominance, and the Wide-Open Domain",
        "Take command of a dyad interaction and manipulate assigned status roles, then trace how visual dominance, posture, and gaze shift. Extend the judgment task to sexual orientation and intelligence cues, and draft a research agenda for the personality-nonverbal link.",
        "A split-screen experiment room shows high- and low-status dyads while a gaze-tracking graph plots visual dominance ratios. A briefing table lays out face-only photos, posture codes, and a blank research plan awaiting the future directions.",
        [
            "Visual dominance is defined as the ratio of looking while speaking to looking while listening.",
            "Ellyson, Dovidio, Corson, and Vinicur (1980) found that high-status subjects demonstrated visual dominance ratios close to 1, whereas low-status subjects exhibited a much lower rate of visual dominance.",
            "Subjects who scored high on a trait measure of dominance exhibited visual behavior similar to subjects who had been assigned a high-status role.",
            "Schwartz, Tesser, and Powell (1982) found that depictions of people who were physically higher in elevation and in a standing posture were perceived as being more dominant.",
            "Research suggests that gay, lesbian, and heterosexual sexual orientations can be accurately identified even from very thin slices of behavior or appearance.",
            "Ambady, Hallahan, and Conner (1999) found that judgments of sexual orientation based on dynamic nonverbal behavior were more accurate than judgments based on still photos.",
            "Rule, Ambady, and Hallett (2009) found that women's sexual orientation was identifiable above chance levels even when the image was presented for as little as 40 milliseconds.",
            "Borkenau and Liebler (1995) found that people with higher intelligence scores were less likely to dress in a showy manner and were more likely to be rated as wearing self-assured facial expressions.",
            "Wartenburger et al. (2010) found that men scoring high in fluid intelligence used more movement and representational gestures when explaining their strategies on a geometric analogies task.",
            "Future studies of nonverbal behavior should routinely include personality measures, especially of the Big Five, and report the correlations even when the primary focus of the study is elsewhere.",
            "Using aggregation or multiple measurements is perhaps the biggest lesson learned from the person-situation debate when attempting to assess correlates between traits and behavior.",
            "Most of the studies of the connection between personality and nonverbal behavior lack any form of close replication, making it difficult to perform meta-analysis of similar methodologies or findings.",
        ],
    ),
}
