# -*- coding: utf-8 -*-
CHAPTER = {
    "num": 10,
    "title": "Facial Expressions",
    "authors": "Hyisung C. Hwang and David Matsumoto",
    "domain": "Nonverbal Communication | Facial Expressions",
    "scrub": (
        "Facial Anatomy Primer: Muscles, Nerves, and the Facial Action Coding System",
        "Dissect an interactive diagram of the facial musculature and trace the VIIth cranial nerve from the brain stem to the 20 independent facial muscles, then classify each muscle action as voluntarily or involuntarily controlled. Annotate which actions the Facial Action Coding System identifies by function rather than structure, and predict which muscle groups are required to produce the universal expressions versus those that vary across individuals.",
        "A cross-section view of the head animates the VIIth cranial nerve branching from the brain stem to each of the 20 facial muscles, with the pyramidal and extrapyramidal tracts drawn as color-coded pathways. A FACS action-unit palette lets you click each muscle action to watch the corresponding appearance change on a digital face, with badges showing which actions are voluntary, involuntary, or missing in some individuals.",
        [
            "Facial expressions are produced by muscle contractions in the face that move skin and change the shape of features, and these muscle movements are known as the morphology of the face.",
            "There are 20 anatomically independent muscles in the face, all of which are innervated by a single nerve, the VIIth cranial nerve, which originates in the brain stem.",
            "The facial muscles are striated muscles and are some of the only muscles in the body that are attached on one side to bone and on the other side to skin, making them somewhat specialized for communication.",
            "Although there are structurally 20 independent muscles in the face, they function in different ways, as the frontalis muscle that runs across the forehead can produce two independent movements.",
            "Facial measurement systems such as the Facial Action Coding System (FACS) identify more than 40 independent facial actions according to function rather than structure.",
            "There are individual differences in the presence or absence of some facial muscles, but cadaver studies have demonstrated that the muscles required to produce the universal facial expressions of emotion occur uniformly.",
            "The same facial musculature that exists in adult humans exists in newborn infants and is fully functional for most individuals at birth (Ekman & Oster, 1979).",
            "The VIIth cranial nerve and thus facial expressions are under the neural control of two distinct areas of the brain that roughly coincide with a voluntary versus involuntary distinction.",
            "The pyramidal tract drives voluntary facial actions and originates in the cortical motor strip, whereas the extrapyramidal tract drives involuntary emotional expressions and originates in the subcortical areas of the brain.",
            "The subcortical areas of the brain are those areas that humans share with their animal relatives and are concerned with body functions related to fighting, fleeing, feeding, and reproducing.",
            "The hands receive the largest degree of innervation from the cortical motor strip, the face receives the next largest degree, and within the face the lower face is more highly represented (Rinn, 1984).",
            "When emotions are elicited, spontaneously produced expressions are under the neural control of the subcortical areas of the brain, whereas attempts to control expressions are likely to emanate from the cortical motor strip.",
        ],
    ),
    "dialogue": (
        "Universal Facial Expressions of Emotion: From Darwin to the Laboratory",
        "Judge the seven universal expressions of emotion posed by actors from a dozen cultures and compare your accuracy against cross-cultural recognition norms, then trace the research lineage from Darwin through Tomkins to the New Guinea tribes and Friesen's film study. Distinguish Duchenne from non-Duchenne smiles in spontaneous Olympic footage and identify which six emotions formed the original universal set before contempt was added.",
        "A judgment lab displays portraits from the Japanese and Caucasian Facial Expressions of Emotion stimulus set with response buttons for the seven emotions and an accuracy meter benchmarked against findings from Hungary, Japan, Poland, Sumatra, the United States, and Vietnam. A timeline view reconstructs the historical studies, from Darwin's 1872 book and the New Guinea expeditions to the 2004 Athens Olympics, with video clips of medal winners and losers to classify.",
        [
            "Darwin's (1872/1998) seminal work suggested that emotions are biologically innate and that facial expressions evolved as a universal skill in all humans.",
            "Darwin suggested that humans express anger by furrowing the brow and tightening the lips with teeth displayed because these actions are part of an attack response.",
            "Darwin's inhibition hypothesis held that people are unable to perfectly simulate facial expressions in the absence of the genuine emotion and are unable to completely suppress their true expressions when feeling strong emotions, resulting in emotional leakage on the face.",
            "Darwin wrote The Expression of the Emotions in Man and Animals to refute Sir Charles Bell's claim that God designed humans with unique facial muscles to express uniquely human emotions.",
            "In the mid-1960s, Tomkins (1962, 1963) resurrected interest in the study of emotions and faces with the publication of his landmark volumes entitled Affect, Imagery, and Consciousness.",
            "Tomkins and McCarter (1964) conducted the first study demonstrating that facial expressions were reliably judged to be associated with certain emotional states.",
            "In studies with two visually isolated, preliterate tribes in the highlands of New Guinea, tribespeople could reliably recognize expressions posed by Westerners and Americans could recognize the tribespeople's expressions, ruling out learning through mass media or shared visual input.",
            "Friesen's (1972) cross-cultural study, in which 25 Americans and 25 Japanese watched neutral and highly stressful films while their faces were recorded, provided the first evidence that facial expressions of emotion were universally produced when emotions were spontaneously elicited.",
            "The original universality studies provided evidence for the cross-cultural expression and recognition of six emotions, anger, disgust, fear, happiness, sadness, and surprise, and contempt was later identified as a universally recognized expression as well.",
            "Biehl et al. (1997) demonstrated that the seven emotions were reliably identified in Hungary, Japan, Poland, Sumatra, the United States, and Vietnam using the Japanese and Caucasian Facial Expressions of Emotion (JACFEE) stimuli.",
            "At the 2004 Athens Olympic Games, winners displayed Duchenne/genuine smiles whereas losers displayed sadness, disgust, anger, and other negative emotions, providing evidence of universal expressions from spontaneous, field-based behavior.",
            "Duchenne smiles involve not only the smiling muscle (zygomatic major) but also the muscles surrounding the eyes (orbicularis oculi), and many studies have shown that only these types of smiles are correlated with experienced positive emotion.",
        ],
    ),
    "audit": (
        "Biological Sources of Universality: Blind, Twins, Infants, and Primates",
        "Evaluate the evidence for the biological innateness of facial expressions by auditing four research lines: congenitally blind individuals, twins and families, infants, and nonhuman primates. For each line, weigh the findings, such as the Paralympic judo athletes, monozygotic twins reared apart, and primate FACS comparisons, and determine whether cultural learning or a hardwired emotion-expression linkage best explains the results.",
        "A four-panel evidence board organizes studies of blind athletes, kinship concordance, neonatal expression repertoires, and primate facial musculature comparisons, each with study cards and key findings. A verdict slider moves between learned and innate as you audit each line of evidence, with a final score reporting how consistently the sources converge on biological innateness.",
        [
            "Facial expressions of emotion may be universal either because they are a biologically innate skill that all humans are born with or because they are learned in the same way around the world, and cross-cultural agreement alone cannot distinguish between these two sources.",
            "Thompson (1941) examined whether congenitally blind children differentially produce emotions on their faces compared to sighted children, finding substantial similarity between the two groups, especially for expressions such as smiling and laughter and anger.",
            "Galati et al. (2003) found that congenitally blind and sighted children expressed similar facial expressions of emotions in social interactions, although the sighted children masked their negative emotions more than the blind children did.",
            "Matsumoto and Willingham (2009) examined spontaneous facial expressions of blind judo athletes at the 2004 Athens Paralympic Games and found the same facial configurations documented in sighted athletes, with winners displaying Duchenne smiles more frequently than the defeated.",
            "Facial behaviors of blind individuals are more concordant with their kin than with strangers, providing evidence for a unique family facial expression signature (Peleg et al., 2006).",
            "Some facial expressions in response to emotionally provocative stimuli were more concordant among monozygotic twin pairs than among dizygotic twins when age and gender were controlled, supporting genetic effects on the facial expressions of certain emotions (Kendler et al., 2008).",
            "There is widespread consensus that smiling, distaste, the infant precursor of adult disgust, and crying, the universal signal of sadness and distress, occur in neonates (Oster, 2005).",
            "Discrete expressions of anger and sadness have been reported in the early part of the second year of life, and by the time of preschool children display discrete expressions of the other emotions as well.",
            "The facial expressions considered to be universal among humans also have been observed in nonhuman primates, and Redican (1982) suggested that nonhuman primates displayed a play face that was similar to the happy face of humans.",
            "A chimpanzee version of the Facial Action Coding System (ChimpFACS) was developed that allows identification of the specific facial muscle movements chimpanzees use in producing facial expressions.",
            "Burrows, Waller, Parr, and Bonar (2006) reported that the forehead musculature of chimps is less well developed than that of humans, speculating that the greater hairiness of chimps makes eyebrow movements less visible.",
            "The evidence reported in this section points to the notion that the emotions that are universally expressed and recognized are dominantly biologically innate and hardwired, and this class of emotions is known as basic emotions (Ekman, 1999).",
        ],
    ),
    "matrix": (
        "Coherence and Functions: Expression, Experience, Physiology, and the Facial Feedback Hypothesis",
        "Test the coherence of the emotion response package by linking spontaneous expressions to self-reported experience, appraisal themes, and physiological responses in studies such as Mauss et al. (2005) and Lerner et al. (2005). Then run facial feedback demonstrations that pose expressions and measure their effect on subjective experience and autonomic activity, and use visual cliff and marital interaction data to map the interpersonal functions of expressions.",
        "A coherence dashboard plots cross-lagged correlations between expression and experience, appraisals, and cardiovascular and cortisol measures across a set of studies, with the within-subject correlations highlighted. A facial feedback rig lets you hold posed configurations of the universal expressions while gauges of subjective emotion and autonomic response tick live, and a visual cliff simulator records infant crossing rates for each maternal expression.",
        [
            "Mauss, Levenson, McCarter, Wilhelm, and Gross (2005) found cross-lagged, within-individual correlations of .73 and .74 between facial behavior and experience intensity for amusing and sadness-eliciting films, and correlations corrected for disattenuation were even higher at .89 and .97.",
            "The discrete facial expressions of emotion do not coincide with the valence dimensions of pleasantness-unpleasantness but with discrete subjective experiences.",
            "Duchenne smiles are reliably related to positive subjective experiences of joy and enjoyment, whereas smiles without activity of the orbicularis oculi are not associated with positive subjective experience.",
            "Lerner et al. (2005) demonstrated that discrete facial expressions of fear, anger, and disgust were reliably linked not only to cardiovascular responses but to neuroendocrine activity as well, with fear expressions associated with elevated cardiovascular and cortisol levels.",
            "In the first study to demonstrate the link between expressions and subsequent behavior, boys who smiled while watching violent scenes engaged in more hurtful behavior and aggressive play afterward, whereas boys who showed sadness engaged in more helpful behavior and less aggressive play (Ekman, Liebert, et al., 1972).",
            "When emotions are elicited spontaneously, facial muscles respond with relatively smooth onsets and offsets, are innervated at approximately the same time, and are symmetrical on both sides of the face, with expressions of contempt occurring unilaterally as the exception.",
            "Voluntarily posed expressions activate different muscles at different times, apex at different speeds, and are more asymmetrical than spontaneous expressions (Hager & Ekman, 1985).",
            "The raising of the brows and upper eyelid in expressions of fear and surprise widens the visual field, allowing individuals to see more objects in the environment and allowing for faster eye movements during object localization (Susskind et al., 2008).",
            "According to the facial feedback hypothesis, facial expressions augment contemporaneous subjective emotional experience, and numerous studies have demonstrated this effect for both positive and negative emotions.",
            "Facial feedback effects are most powerful when the facial configurations correspond to the universal emotional expressions (Soussignan, 2002).",
            "In Sorce, Emde, Campos, and Klinnert's (1985) visual cliff study, no infant crossed the table when the mother showed fear, only 6% crossed when the mother posed anger, 33% crossed when the mother posed sadness, and approximately 75% crossed when the mother posed joy or interest.",
            "Discrete expressions of contempt, especially by the men, and disgust, especially by the women, in married couples' conversations predicted later marital dissatisfaction and even divorce (Gottman & Levenson, 1992).",
        ],
    ),
    "boss": (
        "Culture, Display Rules, Microexpressions, and the Many Other Signals of the Face",
        "Analyze how culture modulates universal expressions by studying the display rule strategies in Friesen's (1972) Japanese masking data and the Olympic athletes' sequential regulation, then use microexpression techniques to spot concealed emotions and deception in clinical interview and emotional lying footage. Classify the face's other signals, including pain, anxiety, positive emotion variants, health markers, and conversational emblems, and defend your detection conclusions against the evidence on validity.",
        "A dual-viewer shows the same stressful film footage first alone and then with an experimenter present, animating the Japanese participants' masking with smiles overlaid in real time. A microexpression lab lets you scrub through slowed interview footage to spot sub-second leakage, and a signal library catalogs facial emblems, back-channel brow movements, and health-related expression signatures with their evidence ratings.",
        [
            "Ekman and Friesen (1969) coined the term cultural display rules to account for cultural differences in facial expressions of emotion, referring to rules learned early in childhood that help individuals manage and modify their emotional expressions depending on social circumstances.",
            "In Friesen's (1972) study, Americans and Japanese produced the same expressions when viewing stressful films alone, but in the presence of an older male experimenter the Japanese masked their negative emotions with smiles while the Americans continued to express them.",
            "Individuals can manage expressions by amplifying (exaggerating) or deamplifying (minimizing) them, masking or concealing emotions by expressing something other than what they feel, neutralizing expressions by expressing nothing, qualifying feelings by expressing emotions in combination, and simulating emotions that are not felt.",
            "In Matsumoto, Willingham, and Olide's (2009) study of Olympic athletes' expressions, the average length of time from an initial, universal emotional expression to a culturally moderated modification was less than 1 second.",
            "Athletes from urban, individualistic cultures expressed their emotions more, whereas athletes from less urban, more collectivistic cultures masked their emotions more.",
            "Microexpressions are extremely quick facial expressions of emotion that are generally unobservable to the untrained person.",
            "Haggard and Isaacs (1966) were the first to empirically verify the existence of microexpressions in their studies of clinical interviews.",
            "There is growing evidence that when individuals lie, especially about their emotions, signs of the underlying, truly felt emotion appear in the face despite attempts to conceal, and failing to control one's facial expressions of emotion has been linked to lying (Hurley & Frank, 2011).",
            "There is some evidence for the existence of facial expressions of pain (LeResche, 1982; Prkachin & Craig, 1995), anxiety (Perkins et al., 2012), and sexual excitement (Fernandez-Dols, Carrera, & Crivelli, 2011).",
            "Recent studies have provided evidence that different types of positive emotional states, including embarrassment, amusement, shyness, sensory pleasure, elation, contentment, and relief, can be differentiated by specific morphological characteristics of smiling.",
            "Harker and Keltner (2001) coded women's college yearbook photos and showed that Duchenne smiling was positively correlated with multiple measures of personality, personal well-being, and marital satisfaction over the next 30 years.",
            "The brows are used as conversational signals to emphasize, punctuate, underline, or animate speech, and listeners use facial expressions as part of back-channel communication to provide feedback to the speaker.",
        ],
    ),
}
