# -*- coding: utf-8 -*-
CHAPTER = {
    "num": 21,
    "title": "Methods in Olfactory Research",
    "authors": "Robin Freyberg, Patricia Wilson, and Jeannette Haviland-Jones",
    "domain": "Nonverbal Communication | Olfactory Methods",
    "scrub": (
        "Choosing an Appropriate Olfactory Stimulus",
        "Begin as a researcher deciding which odor to use for a study of nonverbal communication. Review the three broad stimulus categories - human body odors, natural odors, and artificial odorants - then weigh where to obtain the odorant, whether to rely on odors validated in prior research, and how genetic background and active versus inactive ingredients might shape the results.",
        "A laboratory bench is shown with three labeled stimulus stations: a vial of androstadienone, a sprig of a plant odor, and a fine-fragrance bottle. A source-map panel traces each odor to its origin, listing fragrance houses such as Firmenich, International Flavors and Fragrances, and Symrise, and a checklist prompts you to consider prior published use of the odor and its ingredient composition.",
        [
            "Researchers can choose among human body odors (such as the putative pheromone androstadienone, or AND), natural odors such as plant odors, and artificial odorants such as fine fragrance, though commercially available fragrances often contain natural elements as well.",
            "Some researchers obtain odor samples directly from fragrance producers such as Firmenich, International Flavors and Fragrances, and Symrise, while natural body odors may be produced in the laboratory context itself and some artificial odors can be bought directly in stores.",
            "The chapter advises that examining what odors have been used previously by other researchers is a good first step, just as methods textbooks urge researchers to use questionnaires that have been used in prior studies before constructing a novel scale.",
            "Researchers interested in attention should consider the literature on peppermint, because previous research has repeatedly demonstrated that peppermint can have a profound impact on alertness.",
            "Emotion researchers may want to consider using human body odors, as research by Haviland-Jones and McGuire (1999) and Chen, Katdare, and Lucas (2006) showed striking mood effects when individuals were exposed to underarm pads worn during mood induction films.",
            "Usually very little information exists regarding the composition of various odorants and why exactly they maintain their particular effects on human behavior, and the effect could come from one identifiable compound or from the combination of multiple components.",
            "Perfumers refer to accords the way musicians describe chords of music, meaning a combination of individual perfume essences that creates a new unified fragrance distinct from its individual components, making it hard to identify the contributing elements.",
            "When using human body odors it can be difficult to pinpoint one specific component that affects emotion and behavior, and there may be a genetic component that can be isolated for its ultimate impact.",
            "Research has demonstrated that mothers and infants can identify each other through smell, and strangers can match samples of genetically related people, such as father and son, but not of socially related people, such as husband and wife.",
            "Research has indicated that genetic background contributes to fragrance selection, and the full extent of the genetic contribution to olfaction is still unclear and should be explored further.",
            "Odorants may be composed of both active ingredients that affect behavior and inactive ingredients that can be detected and co-occur but do not affect behavior, so researchers must be aware that what they measured or detected may not have been the active ingredient.",
        ],
    ),
    "dialogue": (
        "Determining Intensity and Choosing a Method of Delivery",
        "Take the role of a researcher who has chosen an odorant and must decide how much stimulus to present and how to expose participants to it. Decide between perithreshold and conscious detection levels, consider whether intensity matching across stimuli is needed, and weigh direct bodily delivery against indirect environmental delivery while balancing internal and external validity.",
        "A control-room scene shows two experiment setups side by side: on the left, a participant wearing a nasal cannula in a carefully controlled odor chamber, and on the right, a room with a fragrance diffuser and scented jars. A slider control lets you adjust odor intensity between perithreshold and consciously detectable levels while a validity meter shows the tradeoff between internal and external validity.",
        [
            "Some researchers choose odors that are above conscious detection, while others suggest that the actual effect of fragrance generally works best at the low or perithreshold level, which is generally below the level of conscious detection.",
            "Phillips and Cupchik (2004) reported that accuracy for recalling story details was lower when fragrance intensity was greater, suggesting that fragrance awareness may undermine specific effects.",
            "If attention is drawn to the fragrance so that it is identified, or an attempt is made by the participant to identify it, associations to the semantic aspect of its name begin to take precedence over other effects.",
            "When participants identify a perfume, correctly or incorrectly, they are more likely to search their memories for associations to the particular odorant, which may matter when the fragrance and its associations are part of the research question.",
            "When researchers study a variety of odors they often determine whether perceived intensities or strengths are similar, either by asking participants to report intensity or by measuring chemical concentrations, but it is unclear what difference intensity matching makes.",
            "Most researchers use average intensity ratings when examining differences in intensity, but those averages often do not reflect the wide range of scores surrounding the average ratings, and large individual differences exist in perceptions of intensity.",
            "Participants can be exposed to odorants directly via the body, for example a scented stick held near the nose, an odor-infused cotton ball taped between the nose and upper lip, an odorous patch on the body, a nasal cannula, or odors applied directly to the participant.",
            "Indirect exposure is typically done within the external environment, and researchers have used fragrance diffusers, fragrance pellets aired by a fan, carefully controlled odor chambers, and olfactory stimuli placed in jars near the participant.",
            "No consensus currently exists regarding the optimum method of delivery, and it is unclear whether differences in delivery method ultimately contribute to the various psychological effects reported.",
            "Some researchers use delivery systems that carefully control the exact amount of exposure and environmental factors such as humidity, while others take a more naturalistic, less controlled approach that mirrors real-world contexts.",
            "Heavily controlled environments that place participants in uncomfortable situations, such as nasal cannulae, may affect the ultimate emotions experienced or the ability to communicate.",
            "Carefully controlled odor delivery systems may remove potential confounding variables in stimulus presentation, but they may contribute to confounds in the study design itself through loss of external validity.",
        ],
    ),
    "audit": (
        "Collecting and Controlling Human Body Odor Samples",
        "Act as a study auditor reviewing a protocol for collecting human mood body odors. Inspect the donor-selection criteria, evaluate the controls imposed on diet, medication, illness, and fragranced body-care products, and verify the collection, freezing, and pooling procedures used to create the stimulus.",
        "A sterile collection checklist is displayed over a diagram of the human body highlighting the axillary (underarm) region. Step-by-step cards show a sterile gauze pad being placed in the armpit before a mood induction video, the pad being frozen to control bacterial growth, and multiple donor pads being pooled into a single sample tube labeled as a group representation.",
        [
            "The mood odor research is based on the premise that humans emit nonverbal olfactory signs that can be interpreted by others, and previous research has established that such odors can be discriminated by detectors.",
            "Human body odors are obtained by collecting axillary (underarm) secretions, and researchers have generally limited collection to adult male donors to control for possible variations in body odor due to fluctuating hormonal cycles of adult females.",
            "Typically males of approximately the same age are recruited as donors based on the assumption that hormone production is likely to be similar because hormone production changes with age.",
            "Body odor is affected by illness, medications, diet, and chemicals applied to the skin, so individuals who take medications for chronic illness or who are currently unwell would not be considered appropriate donors.",
            "To control for the effects of diet, donors are asked to refrain from eating spicy or odorous foods for several days prior to collection and for the duration of the collection.",
            "Because chemicals applied to the skin, such as fragranced lotions, shampoos, and deodorants, will be part of the collected secretions, donors must refrain from using them for several days prior to and during the collection, and researchers supply unfragranced products instead.",
            "Deodorant is supplied rather than an antiperspirant because antiperspirant builds up on the skin and can remain for several days without reapplication, whereas some researchers concerned with naturalistic mood odor production would not apply such controls.",
            "When researchers want to study human mood odors, some method of mood induction is employed, such as mood-inducing videos whose reliability is widely accepted, while on the naturalistic side Mujica-Parodi et al. (2009) used sky-diving to produce anxiety.",
            "Because more than one type of mood odor is often desired, the same donors are used in each type of collection, thus making the odors within-subject.",
            "The axillary secretions are obtained by placing a sterile gauze pad into the armpit prior to the mood induction procedure, and the collected gauze pads must be frozen to control for bacterial growth.",
            "The frozen gauze pads must be brought back to room or body temperature for odor delivery, and typically the samples of several donors are pooled to create a group of people representation like what one might be exposed to in the natural course of social activity.",
            "It is not yet known which organic compounds in axillary secretions are active for mood communication, so the effect of the other compounds present in axillary secretions is unknown as well.",
        ],
    ),
    "matrix": (
        "Measuring Odor Effects with Self-Report and Narrative Methods",
        "Take the role of a methods analyst choosing how to capture the psychological effects of odor exposure. Compare the strengths and weaknesses of questionnaires with narrative methods, identify when self-reports fail to detect subtle perithreshold effects, and decide how to score narratives for emotion words and intimacy themes.",
        "A split-screen workspace shows a questionnaire form on one side and a narrative-writing panel with the full personal-experience instructions on the other. As you toggle between methods, a results grid updates with bars comparing self-report ratings with narrative-content scores from software-based text analysis, flagged with notes about social desirability effects.",
        [
            "Questionnaire measures are still considered by many to be the gold standard for studying psychological experience, and within olfaction research self-reports are one of the most common methods for studying how odors impact emotional and social communication.",
            "Self-reports are often used because they are easy, inexpensive, and quick to implement, and within the fragrance industry they are also seen as a valid reflection of an individual's experience.",
            "Social desirability effects can make questionnaires particularly unreliable, and Brody and Hall (1993, 2000) observed that men typically report less emotion than women except in cases of anger, where the pattern is reversed, while behavioral studies often do not show such gender differences.",
            "In work examining emotional and behavioral responses to flowers, men were as likely to smile, socially approach, and initiate a conversation as women, and men's behavior actually showed even more change from baseline than women's behavior.",
            "The use of questionnaires assumes they can properly describe a participant's experience, but some experiences are too complex to be captured through specific questions defined by the researcher, and emotional expressions often travel fast and outside of conscious awareness.",
            "Self-report measures may be too imprecise for studying effects due to odor exposure because such effects are often quite subtle, and individuals exposed to perithreshold odors often did not report emotional changes.",
            "Participants exposed to perithreshold odors incorporated more emotion words in their narratives when asked to write about recent events, and adolescent girls exposed to an unfamiliar fragrance showed no direct self-report effects but indirect effects on social behavior and narrative content.",
            "The authors proposed that fragrance can serve as a biological search engine, so that when a particular odor is in the air people search for events or people that correspond to it, and these processes occur rapidly, indirectly, and usually outside of conscious awareness.",
            "Researchers need to look beyond self-reports to psychophysiology, narrative, or nonverbal behavior to detect search-engine effects because the person having the experience may not be aware of the shift in attention and may not attribute it to a fragrance.",
            "Narrative methods have been used extensively in other areas of psychological research when conscious methods such as self-reports may not be helpful, but their use within olfaction research is only starting to emerge and has already been demonstrated to be useful.",
            "Work from the authors' lab showed that although self-reports indicated no differences in pleasantness or intensity across fresh air, floral odor, and fragrance conditions, differences emerged in narrative content, with participants exposed to floral odors at perithreshold levels incorporating more words indicative of enjoyment.",
            "Research by Freyberg and Ahren (2011) found that reports of social enjoyment and words indicative of intimacy in adolescents' narratives decreased when they wore an unfamiliar fragrance compared to their favorite, but only when they also found the unfamiliar fragrance less pleasant.",
        ],
    ),
    "boss": (
        "Measuring Odor Effects: Psychophysiology, Neuroimaging, Behavioral, and Cross-Cultural Methods",
        "Take the role of the lead investigator directing a multisession study of odor effects. Integrate psychophysiological measures such as heart rate and skin conductance, evaluate neuroimaging evidence about brain responses to chemosignals, design behavioral observations of approach and helping, and judge the cross-cultural generalizability of the findings.",
        "A command-center dashboard shows four live panels: a heart-rate and skin-conductance trace overlaid with pleasantness ratings, a PET brain scan with activated regions in attention and social-cognition areas, a behavioral log recording mime-approach and flower-smile events, and a world map flagging industry reports of regional scent preferences. A final report panel compiles findings and flags remaining cross-cultural gaps.",
        [
            "Psychophysiological methods such as heart rate and skin conductance have been incorporated into olfactory research as a way of understanding how odors affect participants on a physical level.",
            "Bensafi et al. (2002) observed that heart rate was positively associated with pleasantness ratings, whereas skin conductance was positively correlated with how arousing the particular odor was perceived to be by participants.",
            "Graham, Janssen, and Sanders (2000) found a heightened sexual response by females to a male fragrance during their follicular phase but only when they engaged in a personal sexual fantasy, with no observed changes in self-report.",
            "Several studies involving the semiochemical AND reported a modulating effect whereby reported negative mood and heart rate response or galvanic skin response decreased compared to the control odor.",
            "Kiecolt-Glaser et al. (2008) observed enhanced positive mood via self-report for lemon oil compared to lavender but no changes in heart rate, blood pressure, or salivary cortisol, illustrating that psychophysiology does not always coincide with questionnaires.",
            "Measurement of cerebral blood flow as an indicator of brain activation is obtained via positron emission tomography (PET) or functional magnetic resonance imaging (fMRI), and such studies can demonstrate that an olfactory stimulus impacts not only olfactory-processing areas but other brain areas as well.",
            "Jacob et al. (2001) used PET to investigate exposure to AND and found sustained brain changes in areas associated with attention and mood as well as olfactory processing, and these effects were found without conscious exposure to AND.",
            "Lundstrom, Boyle, Zatorre, and Jones-Gotman (2008) found that different neural pathways process body odors compared to nonbody odors, and body odors from friends as opposed to strangers activated different brain areas.",
            "Herz, Eliassen, Beland, and Souza (2004) found with fMRI that a pleasant memory odor cue was significantly more likely to activate the amygdala and hippocampus than an unmarketed control fragrance, showing effects on brain areas associated with emotion and memory.",
            "Participants exposed to floral air were three times more likely to approach and touch an experimenter who dressed and acted as a mime than those exposed to fine fragrance or fresh air, and socially supportive behavior such as smiling and initiating conversations occurred when individuals were presented with flowers.",
            "Baron (1997) demonstrated that participants in a shopping mall were more likely to help a confederate in the presence of pleasant odors, and Holland, Hendriks, and Aarts (2005) found that participants exposed to a citrus-scented cleanser engaged in more cleaning behaviors, such as removing snack crumbs from their work environment.",
            "Ebihara et al. (2012) found that lavender and grapefruit odor exposure improved gait speed in older adults, which the authors suggested may ultimately result in reduced fall rates, and no published academic studies to date have examined cross-cultural or geographic differences in odor exposure.",
        ],
    ),
}
