# -*- coding: utf-8 -*-
CHAPTER = {
    "num": 5,
    "title": "The Developmental Arc of Nonverbal Communication: Capacity and Consequence for Human Social Bonds",
    "authors": "Caroline F. Keating",
    "domain": "Nonverbal Communication | Development",
    "scrub": (
        "The Developmental Niche and the Three Ontogenetic Forces",
        "Chart the three ontogenetic forces that shape nonverbal communication development - preparedness, increasing voluntary control, and differentiation - and explain how the developmental niche bends each of them. Use the Lewis, Sullivan, and Vasen (1987) face-posing study and the cross-cultural examples of Baganda, German, Nso, Hausa, and Zinacanteco infants to show how culture and custom channel expressive development, then account for why researchers still lack a comprehensive view of the nonverbal communication whole.",
        "A wall of video monitors plays children of different ages being asked to make happy, sad, and angry faces, each face rendered progressively sharper and more differentiated from age 2 to adulthood, with the lower face glowing first. Beside the monitors, a world map sprouts icons of the niche: a smoke-filled hut, a mother's breast, a sumo-style crying contest, and a mother's smiling face looming over a baby's crib.",
        [
            "Nonverbal communication development is driven by three ontogenetic forces: biological preparedness, increasing voluntary control, and differentiation.",
            "With development, responses become less diffuse, undifferentiated, and nonspecific and more distinctive, refined, organized, and directed.",
            "Though facial musculature is considerably differentiated at birth, the ability to use it to express a range of discrete emotions seems less so.",
            "Super and Harkness (1986, 2002) conceptualized the developmental niche as a set of dynamic properties and forces that create unique environments for a child that the child, in turn, impacts.",
            "The developmental niche includes the physical and social settings, customs and practices of child rearing, the psychology of caretakers, characteristics of the child (e.g., sex, temperament), and local meaning systems.",
            "In the Lewis, Sullivan, and Vasen (1987) study, 2-year-olds' posed expressions were barely distinguishable with unexpressive upper face regions, whereas adults conveyed nearly the full array of distinct emotions using both upper and lower regions of the face.",
            "Traditional Baganda newborns begin formal training soon after birth to encourage social smiling, and these charming babies smile earlier than most.",
            "German mothers frequently interact face-to-face with their babies, whereas Cameroonian Nso mothers rarely do, and at 12 weeks of age German infants smile more frequently and imitate their mother's actions more than their Nso counterparts.",
            "Cranky Hausa babies are immediately quieted at a mother's breast, and they consequently survive drought conditions better than their less expressive cohorts.",
            "Researchers tend to specialize in studying one signal channel or another and rarely examine the interplay among modalities in shaping meaning, leaving a piecemeal account of what should be a developmental whole.",
            "Children's nonverbal behavior is often used only as a convenient indicator of social status or emotionality rather than studied as a developing social communication competence or skill set in and of itself.",
        ],
    ),
    "dialogue": (
        "Dialogue with the Toddler: Touch From Contact Comfort to Social Bonds",
        "Converse with a young child through the channel of touch and trace how skin contact becomes communicative from birth onward, distinguishing raw skin contact from communication through touch. Use Harlow's contact comfort findings, kangaroo care, and the contrast between Boston and Aka infant-holding practices to show how touch builds social bonds, and interpret what blindfolded dyad studies reveal about touch's ability to carry discrete emotion messages.",
        "A nursery scene splits in two: on one side, a terry-cloth surrogate mother cradles a clinging infant monkey, and on the other, a newborn rests on a caregiver's bare chest in a cloth sling while a warm glow traces the points of contact. In a floating panel, a blindfolded student guesses the emotion behind a hand squeezing her arm, with labels like anger, fear, and sympathy flickering above her head.",
        [
            "There is touch, or skin contact, and then there is communication through touch, which is sensory information produced in response to skin contact, and the two are not the same.",
            "Sensitivity to touch is evident in the intrauterine environment, and it is exquisitely developed by birth in most mammals.",
            "Harlow (1959) showed that absent a real mother, infant monkeys experienced so-called contact comfort, or a feeling of security, when permitted to cling to inanimate, soft, terry-cloth surrogates.",
            "Kangaroo care, whereby newborns are held and carried on the chests of caregivers in a cloth pack, is associated with enhanced communication outcomes, and by 3 months both kangaroo care mothers and fathers were more sensitive to infants than traditional care parents.",
            "Touch by a trusted agent calls forth neural responses that gate away pain and rallies hormonal reinforcements that modulate cortisol levels and stress.",
            "Ferber, Feldman, and Makhoul (2008) categorized nine specific touch behaviors between U.S. mothers and infants into three basic categories: affectionate, stimulating, and instrumental.",
            "Tickling is a form of touch communication common cross-culturally, and by adolescence tickling bouts between other-sex individuals are seven times more likely than same-sex tickling bouts, though self-reported frequency declines dramatically at about 40 years of age.",
            "Daytime observations of middle-class families in Boston in the 1960s and 1970s revealed that infants were held by parents approximately 5% of the time, whereas Aka infants in Congo are held by an adult nearly all of their waking hours.",
            "In a study by Hertenstein, Holmes, McCullough, and Keltner (2009), blindfolded participants correctly identified anger, fear, sadness, disgust, love, gratitude, and sympathy from touches at rates of roughly 50% to 70%, with sympathy communicated by patting and rubbing and fear by squeezing.",
            "Other things being equal, individuals who initiate touch are typically perceived as having higher status than those they touch.",
            "National Basketball Association players who touched one another frequently during early season games improved most in terms of individual and team performance over the season.",
            "Rough touch by mothers, recorded as they fed their 3-month-olds, predicted infant behavioral problems at 2 years of age.",
        ],
    ),
    "audit": (
        "Audit the Evidence: Olfaction, the Ancient Chemosensory Channel",
        "Run a forensic audit of the chapter's claims about olfaction as a nonverbal channel: verify the evidence that chemosignals anchor early attachment, enable individual recognition among kin, friends, and roommates, guide mate selection, and transmit fear-related alarm signals. Then reconcile the paradox that humans are astonishingly good at odor detection and discrimination but astonishingly bad at odor identification and naming, and stamp each claim SUPPORTED, CHALLENGED, or UNRESOLVED.",
        "A dark laboratory fills with faint amber scent trails drifting from a newborn toward its mother and from tee-shirts toward a line of sniffing children, each trail glowing brighter where recognition occurs. On a chalkboard, two verdict columns grow - humans are astonishingly good at odor detection and astonishingly bad at odor identification - while a candle, a fear-sweat droplet, and a baby bottle float as exhibits.",
        [
            "Olfaction is a phylogenetically ancient sense, older even than touch, that comprises a range of chemosignals providing a nonverbal channel for crucial information about the identity and state of conspecifics.",
            "The mammalian olfactory sense is operational in the fetus and at birth, providing a critical chemosensory communication channel that enables individual recognition, a key component of developing attachments.",
            "Experiments with newborns reveal that they orient toward their mother's amniotic fluid and that they distinguish and prefer the odor of their mother's milk over that of a stranger's.",
            "New mothers can distinguish their individual newborn's odors from those of other infants using scents detected on their baby's breath and from traces of body odors transmitted to clothing and blankets.",
            "When 5- to 8-year-olds sniffed the tee-shirts of young children, they distinguished the odors of their younger siblings from unfamiliar children at above chance rates.",
            "The fact that family members do not smell good to one another has been proposed as an incest avoidance mechanism.",
            "Nine-year-olds can identify friends from olfactory cues, and college students can identify their roommates from olfactory cues.",
            "One study found that adults prefer the body odors of adults who share their political beliefs, and the researchers contend that such olfactory sensitivities may serve as a means by which to select a compatible mate.",
            "Individuals excrete chemosensory alarm signals through sweat glands, and the smell of fear has as powerful an effect on eliciting fearful facial expressions as does audiovisual fear cues.",
            "Women who were most accurate in identifying their roommate's body odor from tee-shirts also displayed superior performance in identifying basic facial expressions of emotion.",
            "Yeshurun and Sobel (2010) wrote that humans are astonishingly good at odor detection and discrimination but astonishingly bad at odor identification and naming, because odors do not easily sort themselves into neat, discrete, verbally accessible categories.",
        ],
    ),
    "matrix": (
        "Matrix Match: The Developing Face and Its Emotion Signals",
        "Build the developmental matrix of facial expression processing by matching each milestone - newborn mimicry, 3- to 4-month discrimination, 5- to 7-month generalization, the 7-month shift to fear, the 12-month adult-like anger sensitivity, and later-life decline - to its age band and its supporting methodology. Then map the recognition and production evidence across the life span, including the still-face paradigm, the visual cliff, sex differences, and the status signaling functions of faces.",
        "A timeline matrix stretches across the screen from birth to old age, with faces popping onto each age band: a newborn imitating a tongue protrusion, a 3-month-old staring at a happy face, a 7-month-old freezing at a fearful face, and an older adult squinting at a static photo. Along the bottom, a mother's blank, still face confronts her distressed infant in the still-face paradigm, and a baby on the visual cliff waits for a smile that never comes.",
        [
            "The still-face paradigm, in which a mother poses an expressionless face that moves not at all, is deployed by researchers to alter infant social and emotional state.",
            "Newborns are responsive to changes in facial expressions, and they mimic their configurations, and from the first few hours of life infants can imitate facial expressions such as mouth opening and tongue protrusions modeled by adults.",
            "Discrimination of posed, static facial expressions of happy, angry, fearful, sad, and surprised has been reported in 3- to 4-month-olds, with mothers' facial poses being especially provocative.",
            "Between 5 and 7 months of age, infants generalize emotional expression discrimination across dynamic and static expressions of unfamiliar individuals.",
            "Infants are able to use their mother's facial expressions as social referencing tools, and classic visual cliff studies demonstrated the effectiveness of maternal expressions in encouraging or discouraging exploration of the ambiguous appearance of a dangerous-looking drop.",
            "During the first few months of life, infants seem drawn to positive expressions, but they become tuned to fear expressions by the second half of the first year of life.",
            "Whereas ERP studies indicated that sensitivity to happy faces characterized 7-month-olds, 12-month-olds displayed a more adult-like sensitivity to angry faces.",
            "Infants, like adults, scan threatening (angry and fearful) and nonthreatening (happy, sad, neutral) facial expressions differently, revealing fewer, shorter fixations on the inner features of threatening faces.",
            "Meta-analytic results confirm that females are more sensitive to expressions of emotion than males across infancy, childhood, and adulthood.",
            "Existing laboratory research indicates a general decline in performance on typical, static emotion recognition tasks among healthy older adults, with the greatest age differences for anger, fear, and sadness.",
            "Emotion categories for happy versus sad expressions are formed by 7 months of age according to event-related potential work, and hemodynamic patterns also differ in response to happy and angry facial expressions at about this age.",
            "Facial expressions also act as social status signals, with no smile compared to slight smiles making adults appear to be the one who tells other people what to do, in the United States and in 11 countries around the world.",
        ],
    ),
    "boss": (
        "Boss Level: The Developmental Arc of Body, Status, and Social Competence",
        "Face the chapter's closing synthesis: integrate body expression development, status signaling, and the consequences of nonverbal skill into one account of the developmental arc. Walk a character from infancy through adolescence to old age, deploying pointing, gaze following, dance decoding, posture, and dominance displays at the right ages, and deliver the final judgment on how expressive and receptive capacities build, peak, and decline with old age within the niche.",
        "A time-lapse arc sweeps across the screen from a swaddled newborn through a pointing toddler, a preschooler striking a victory pose on the playground, an adolescent turning away from a parent, and an older adult in a slumped chair. Beneath the arc, a bar graph of emotion recognition performance rises through the middle years and falls into old age, while tiny stick figures mark erect postures as dominant and hunched ones as subordinate.",
        [
            "Body movement attracts attention from the earliest moments of life: newborns favor nodding, smiling faces over stationary ones, and looming bodies scare them.",
            "Using point-light stimuli, 4- and 6-month-olds showed greatest sensitivity to body-like motion, demonstrating discrimination of biological motion in the first half of the first year.",
            "Most infants respond to and deploy pointing with fingers at about 12 months of age, well before they speak, and use it as a social signal to direct others' attention.",
            "In a naturalistic study, mothers' head nods were generally confirmatory signals of approval used to encourage early attempts at language, whereas head shakes were used to discourage toddler activities.",
            "Characteristics of body gait, such as the way an adult swings an arm and the speed and length of the stride, convey varying degrees of happiness, sadness, and anger.",
            "In Boone and Cunningham's (1998) dance decoding study, 4-year-olds were above chance for sadness, 5-year-olds for happiness, sadness, and fear, and 8-year-olds and adults performed similarly and were above chance for all four emotions.",
            "Erect postures signaled successful play in a dodgeball game on the playground, whereas slumped postures signaled failure.",
            "Common body dominance signals among preschoolers include arms akimbo, chin thrusts, fist displays, pointing, and erect posture, while common affiliative or submissiveness gestures include shrugging, hunched shoulders, and open palms.",
            "Artful displays of dominance gestures are characteristic of preschool classroom leaders, who are also best at managing their body and face cues so as to appear truthful when telling a lie to an adult, and the same holds for high school and college students.",
            "In a family interaction task, avoidance signaling through facial expressions increased from pre- to late adolescence, and parents also signaled more avoidance as their teenagers aged.",
            "The general progression of nonverbal capacities is set in motion within the boundaries of evolved capacities sensitive to the niche, and expressive and receptive capacities build, peak, and decline with old age.",
            "Nonverbal signals of identity, affective state, and social status provide the basic building blocks of social bonds, and touch and olfactory systems require proximity while visual face and body cues grant increasingly mobile offspring more independence.",
        ],
    ),
}
