# -*- coding: utf-8 -*-
CHAPTER = {
    "num": 2,
    "title": "The Life and Times of Nonverbal Communication Theory and Research: Past, Present, Future",
    "domain": "Nonverbal Communication | Theory and Research",
    "scrub": (
        "Cue Scrubber: Two Traditions from Darwin to the Computer-Vision Era",
        "Drag the scrubber across Keating's timeline of the field and tag each landmark - Darwin's 1872 expression book, Tomkins, Ekman and Izard's basic emotions, Bateson and Birdwhistell's system theory, Fridlund's behavioral ecology, the status cues perspective, Brunswik and Scherer's lens models, Zebrowitz's affordances, and Patterson's parallel process model - as belonging to the emotion tradition or the communication tradition, then flag the quote or event that marks each era's turning point.",
        "A video-scrubber console spans the chapter's history: the playhead ticks from 1872 through the 1960s tipping point into today, and each stop lights up a card with the theory's name, its scholars, and a figure icon - a FACS face grid, two overlapping tradition circles, a cowbird display, or a lens diagram - while a caption bar states the milestone.",
        [
            "The chapter traces two distinguishable scholarly traditions: one emphasizing affective states underlying expression, and the second emphasizing communication as an interactive process contextualized by social relationships and social motives.",
            "Knapp (2006) considered the 1960s a tipping point in the modern incarnation of nonverbal communication research, and Knapp, Hall, and Horgan (2014) described it as a nuclear explosion of the topic.",
            "Silvan S. Tomkins persisted in studying human emotion from a Darwinian perspective despite World War II and Skinnerian psychology, and his ideas gathered steam in the late 1960s and 1970s as Paul Ekman, Cal Izard, and their colleagues synergized the field.",
            "Ekman, Sorenson, and Friesen's (1969) seminal research on cross-cultural facial expressions of emotion was published in Science, and Izard (1971) published his findings in The Face of Emotion.",
            "Irenaeus Eibl-Eibesfeldt (1972), a student of ethologist Konrad Lorenz, published his extensive work on culture and nonverbal communication in Hinde's (1972) edited volume Nonverbal Communication.",
            "van Hooff (1972) argued compellingly that the primate grin face and the human smile are homologous.",
            "Hewes (1973) argued in Current Anthropology that gesture was at the root of human language, an idea that survives in new forms today.",
            "E. O. Wilson's (1975) Sociobiology carried the central message that human and nonhuman social behavior fit patterns shaped by natural selection.",
            "Dennett's (1978) Brainstorms maintained that the behavioral displays of animals reflect social intentions akin to those inferred for humans.",
            "Today, nonverbal communication skill is believed essential to emotional intelligence and, for better or worse, to charismatic leadership.",
            "Although the central foci of the two traditions are discernibly different, they share substantial overlap: some theorists have operated within each tradition, whereas others have blended them.",
            "Signaling intentions and status was a way to avoid costly, physical confrontations and to enhance biological fitness because signaling was less risky and energetically cheap.",
        ],
    ),
    "dialogue": (
        "Dialogue with Darwin, Ekman, and Izard: The Emotion-and-Expression Tradition",
        "Hold a dialogue across a century of emotion research: question Darwin about his 1872 expressive categories and his evidence for universality, press Ekman and Izard about their basic emotions and the display rules that bend expression to culture, then confront the critiques - Russell's methods worries, Widen and Russell's disgust-as-anger children, and the orgasm-versus-pain face puzzle - and decide how tightly emotion and expression are really tied.",
        "A study-room scene faces three portrait busts - Darwin, Ekman, and Izard - that lean in as you ask questions; behind them a wall fills with posed facial photos, a FACS muscle diagram, and a cross-cultural map with pins in Papua New Guinea, while counter-argument cards from Russell and Widen slide in from the side.",
        [
            "Darwin published The Expression of the Emotions in Man and Animals in 1872 and envisioned core human expressive categories including joy, grief, fear, surprise, anger, contempt, disgust, pride, and shame.",
            "Darwin linked blushing to shame and considered it to be the most human of all expressions.",
            "Darwin took his core set of expressions to be universal, offering as evidence that they each appear early in life, are evident among blind-born people, and can be found in every culture, and he attributed their ubiquity to genetic inheritance.",
            "Darwin described an evolution of expression separate from emotion itself, arguing that expressive elements evolved sometimes as functions of the nervous system, sometimes as serviceable habits, and sometimes because display elements made counter responses unlikely.",
            "Darwin observed that the two expressive hallmarks of disgust, the wrinkling of noses and tongue protrusions, were linked to common sources for feelings of disgust.",
            "Ekman and Izard took strong, universalist positions, arguing that basic categories of emotion were common to humankind and therefore had shared expressive features.",
            "Izard (1971), who studied infants, included an emotion he designated as interest, and eventually Ekman, following Darwin's lead, added contempt to his basic six.",
            "Precise study of the facial movements accompanying different emotions led to the eventual development of the Facial Action Coding System (Ekman & Friesen, 1978), which proved to be a valuable coding tool for researchers.",
            "Researchers identified cultural habits of expression, or display rules, that modified the communication value of expressions, with these modifications often induced by social contexts.",
            "The idea that both face and body are potential sources of leaked emotion and deception clues has pop culture appeal, as evidenced by the popular Fox TV series Lie to Me, which is based on the Ekman group's research on deception.",
            "Research pioneers in lie detection began by analyzing frame-by-frame videotapes of clinical patients, and more recent success has been achieved by identifying split-second, microexpressions that presumably flag true, underlying emotion.",
            "The uniformity of cross-cultural emotion results depends to some degree on methodology, and generally the more constrained the procedures, the greater the agreement, so some question whether the most basic universalist assumptions are fully supported by the available data.",
        ],
    ),
    "audit": (
        "Audit the Communication-Process Traditions: Interaction, Ecology, and Status",
        "Run a live audit of each communication-based approach: code a therapist-client session the way Scheflen and the systems theorists did, time gestures against words the way Bavelas and Chovil did, score the behavioral ecology view against the status cues perspective, and check whether naive judges' cues match Gifford's valid head-nod signal. Issue a verdict on which approach best explains a flirting scene, a cowbird display, and a leadership photo.",
        "An observation console shows a therapist-client session being coded into kinesic and proxemic tags as it runs, a waveform ticks under a speech clip to catch gesture timing, and a three-panel evidence wall displays Rothstein's cowbird sequence, a women-in-a-bar flirting clip, and CEO facial-width photos, each waiting for an audit stamp.",
        [
            "At Stanford, anthropologists Gregory Bateson and Ray L. Birdwhistell and, later, psychiatrist Albert E. Scheflen embraced a new, holistic, systems-theory perspective on human interaction.",
            "Scheflen (1974) expressed that we could not find meaning in words any more than we could find consciousness in a nerve cell or love in a gonad.",
            "Scheflen's analyses breathed life into the study of kinesics, proxemics, and paralanguage, and, contrary to predecessors such as Birdwhistell and Hall, they incorporated what was known at the time about nonhuman primate communication.",
            "Researchers deciphered patterns of nonverbal behaviors that regulated interaction, including greeting and leave-taking, and conversation.",
            "An analysis of more than 1,700 gestures embedded in speech revealed that 70% of them were associated with words simply by timing and not by intrinsic meaning.",
            "Human courtship behavior is a lot about timing: characteristics of motion such as the speed of offset and onset of behaviors, rather than the specific behaviors themselves, predict female interest in males.",
            "From the behavioral ecology view, social motives are better predictors of facial displays in real-life interactions than are emotions, and automatic readouts of emotion would be expected to be rare and deception much more common.",
            "Rothstein (1980) determined that the appeasement elements in cowbirds' displays allowed the signalers to appraise the aggressiveness of invaders, so the cowbirds were assumed to feel neither angry nor fearful, though they acted like it.",
            "Observations of women in bars reveal that flirting combines nonverbal signals of dominance and submissiveness that signal coyness and are likely meant to invite qualified approach.",
            "The status cues perspective holds that static, age-related signals in the structure and features of the face are carriers of status information that convey dominance, which signals threat, and submissiveness, which invites approach.",
            "Keating and Bai (1986) showed that U.S. preschoolers selected male and female adult faces with broad jaws and receded hairlines as people who tell others what to do.",
            "Facial width-to-height ratios predict perceptions of competence and leadership among corporate leaders, and Fortune 500 corporate profits can be predicted from the facial widths of their chief executive officers.",
        ],
    ),
    "matrix": (
        "Matrix Match: Lens Models, Affordances, and the Social-Cognitive Engine",
        "Build a two-axis matrix sorting the remaining communication-side theories: place Brunswik's probabilistic functionalism and Scherer's modified lens model, Gibson's affordances and Zebrowitz's baby-faced overgeneralization, Rosenfeld's social-goal experiments, and Patterson's parallel process model into cells defined by perception-versus-signal and conscious-versus-automatic processing, then predict how each framework explains error in person perception.",
        "A luminous matrix grid fills the wall, with cards for lens, affordance, and parallel-process models drifting into their cells; a demonstration row shows Gifford's head-nod slippage, baby-faced adults judged weak and kind, Rosenfeld's chameleon-like participants, and a two-track animation of Patterson's controlled and automatic channels running side by side.",
        [
            "Brunswik (1955) argued that perceptual systems were adapted to their environments by expectancies established through experience in a particular ecology, and his probabilistic functionalism meant that perception operated probabilistically.",
            "Perceivers need only beat the odds some percentage of the time to come away with a winning, perceptual hand, so a certain degree of error was to be expected in social perception.",
            "Gifford (1994) found that communicators who scored high on personality measurements of warmth and agreeableness frequently nodded their heads during interactions, but naive observers actually deployed several postural cues that were unassociated with the communicators' dispositions.",
            "Theorists have applied lens models to vocal quality signals, rapport, mimicry, and deception, and because the approach can distinguish between what is expressed and what is detected, it has also been applied to emotional expression.",
            "Scherer and his colleagues applied a modified version of Brunswik's lens model to their appraisal theory of emotion, allowing the signaler's expressive behavior to be considered separately from the beholder's perception and inference.",
            "Scherer and colleagues demonstrated that expressors do not display, and perceivers do not utilize, facial action units at the level of precision or reliability that theorists such as Ekman predict, although recognition accuracy for emotions remained high.",
            "The ecological theory of social perception, developed in the 1980s, holds that facial structure conveys affordances, defined as opportunities for certain types of interactions.",
            "Baby-faced adults are perceived as having characteristics associated with babies - dependent, weak, and kind - whereas mature facial appearances make individuals look dominant, strong, and cunning.",
            "Affordance-based perceptual habits can become self-fulfilling prophecies, as targets conform to social expectations created by their physical appearances.",
            "Zebrowitz and her colleagues incorporated connectionist modeling techniques and used dynamic as well as static stimuli in support of the affordances perspective.",
            "Rosenfeld's (1965, 1966) experiments showed that participants were chameleon-like: their gestures, postures, expressions, and use of interpersonal space were transformed by the explicit, social goal operating at the time.",
            "Patterson's (1999, 2006) parallel process model attempts to expose the ways controlled and automatic processes operate in tandem in the production of nonverbal communication.",
        ],
    ),
    "boss": (
        "Boss Level: Why Nonverbal Systems Err - Overgeneralization, Sloppiness, or Design?",
        "Face the chapter's closing question: why do we make mistakes when judging the feelings, personalities, intentions, lies, and truths of conspecifics? Weigh the Gibsonian affordances answer (error is overgeneralization), the lens model answer (probabilistic sloppiness), and the behavioral ecology answer (imprecision is strategic, since being a hard read has evolutionary advantage), then issue a verdict on the future of error research armed with the tools of the computer-vision era.",
        "A boss arena is dominated by three towering positions - a baby-faced overgeneralization column, a sloppy lens column, and a hard-read deception shield - with thin-slice judgment clips of faces flashing in seconds-long loops; answering correctly charges a portal marked with high-speed cameras, virtual reality headsets, and motion-detection gear that leads to the chapter's future.",
        [
            "Only brief samples of nonverbal behavior, thin slices lasting just seconds, are needed to create impressions of one another.",
            "Thin slices lead to consensus about the likely trustworthiness and altruism of others, but the trouble is that the impressions themselves are not always to be trusted.",
            "From the Gibsonian affordances platform, error is the result of overgeneralization: perceivers perseverate in making inferences based on attunements appropriate in other contexts, such as age and anger.",
            "Lens model theorists argue that the sloppy, probabilistic shaping of encoding and decoding systems is to blame for mistakes in nonverbal judgment.",
            "Both the basic emotions and Gibsonian affordances theoretical positions have harnessed the power of cross-cultural, cross-species, developmental, and multidisciplinary approaches to make their case.",
            "Basic, prototypical emotion facial expressions generate impressive agreement and consistency in how they are perceived across cultures, but expressers around the world rarely display them in actual, social situations.",
            "From a behavioral ecology perspective, being a hard read, especially to outsiders, might lend an evolutionary advantage, both proximately and ultimately.",
            "The behavioral ecology view predicts ingroup advantages to encoding and decoding nonverbal signals, as is evident in humans and in the special, nonverbal dialects that develop among family groups in other species.",
            "Future research should investigate error patterns and imprecision in nonverbal communication to better understand its complex role in human sociability.",
            "Increasingly sophisticated technologies such as high-speed, high-definition digital recording, motion-detecting cameras, virtual reality headsets, and even Google glasses make studying nonverbal communication in its natural habitat feasible.",
            "Nonverbal communication is no longer the disdained, nameless, orphan child of psychology that Burgoon described it to be in 1980, and today it belongs to the family of important, human psychological processes.",
            "Keating's early plan as a graduate student was to photograph a range of emotions on the faces of everyday people, but her lens captured only one instance of true emotion, the stricken face of a man standing outside his burning house with his dog still inside, teaching her that studying public expression reveals much about communication but little about emotion.",
        ],
    ),
}
