# -*- coding: utf-8 -*-
CHAPTER = {
    "num": 8,
    "title": "The Physical Environment and Nonverbal Communication",
    "authors": "Miles L. Patterson",
    "domain": "Nonverbal Communication | Environment",
    "scrub": (
        "The Power of Settings: Behavior Settings and Ecological Psychology",
        "Classify a series of everyday locations, such as a math class, a football game, a funeral service, and a doctor's office, as behavior settings and inventory their physical features, event programs, actors, and social norms. Predict how the same person would behave differently across these settings, then trace the forces that make behavior homogeneous within a single setting.",
        "A diagram of a college seminar room displays its fixed elements, such as chairs, desks, a whiteboard, and a projector, alongside lists of encouraged and discouraged behaviors. A matching game pairs settings with the kinds of people they attract, revealing how settings select individuals while individuals also select settings.",
        [
            "Behavior settings are bounded geographical locations containing human and nonhuman elements that operate together in facilitating events over a limited period of time.",
            "Examples of behavior settings include a college math class, a football game, a funeral service in a church, and an office visit with a physician.",
            "Each behavior setting includes a specific physical environment that limits behavioral options, a program of relatively predictable events, and a set of social norms structuring those events.",
            "Ecological psychology assumes that settings and their related characteristics, rather than personality traits, motives, or attitudes, are major factors shaping human behavior.",
            "The same person might be an actor across various different settings, but his or her behavior would differ significantly from one setting to the next.",
            "Settings lead to behavior homogeneity by simultaneously fostering and discouraging certain types of actions based on their specific physical features.",
            "Settings not only select individuals, but individuals also select settings based on their own preferences, interests, and experiences.",
            "Sensation seekers, individuals who habitually seek intense experiences, are attracted toward unpredictable and stimulating environments such as settings with arousing music or high-risk sport activities.",
            "People in any given setting are likely to have more in common with one another than people sampled from a range of different settings, increasing the stability and predictability of nonverbal communication patterns.",
            "The ecological contamination hypothesis, introduced by Werthman and Piliavin (1967), proposes that environments can taint the perception of their occupants.",
            "Race-based responses toward others differ dramatically depending on the settings in which they take place, as the activation of negative stereotypes toward African Americans is enhanced at a graffiti-covered street corner rather than in front of a church.",
            "In a public library, mutual glances and smiles between strangers are rather uncommon because introverted, studious people holding the same goal of reading are likely to meet there, whereas in a dance club such exchanges are more likely.",
        ],
    ),
    "dialogue": (
        "Nonverbal Behavior in Public Settings: Unfocused Interactions",
        "Observe pedestrians, elevator riders, and seated strangers on park benches, and code whether they glance, smile, nod, or avert their gaze during unfocused interactions. Stage spatial invasions on solitary seated targets and record departure times and compensatory adjustments, then compare American and Japanese pedestrian microinteractions.",
        "A sidewalk simulation runs pedestrians toward a confederate while a gaze-tracking overlay draws each glance and avoidance pattern. An elevator interior logs glance behavior, and a split-screen compares the smiles, nods, and greetings of American and Japanese pedestrians.",
        [
            "In public settings, people frequently feel ambivalent about the close presence of strangers because they may want friendly contact while remaining wary of the uncertainty that strangers present.",
            "Goffman (1963) used the term civil inattention to identify a common pattern of mixed-motive behavior when strangers approach one another.",
            "As pedestrians approach one another, they initiate a brief glance outside a distance of 2.5 to 3 meters that recognizes the other person, and then look away to respect the other person's privacy as they draw closer.",
            "Studies of elevator riders supported Goffman's prediction that a single glance followed by gaze avoidance is the most common and most positively rated pattern of unfocused interaction behavior.",
            "Pedestrian passing studies found that almost half of observed pedestrians glanced at passing confederates within a range of 2.5 to 3 meters, contradicting the prediction that individuals lower their heads and avert gaze as they pass.",
            "As confederates initiated greater involvement toward approaching pedestrians, from avoiding to looking to looking and smiling, the glances, smiles, nods, and greetings from the pedestrians also increased.",
            "The violation of mutual looking and acknowledgment norms can induce feelings of social exclusion, as pedestrians looked at as though through air reported stronger feelings of disconnection than those who received a gaze or a gaze and smile.",
            "A lack of mutual nonverbal acknowledgment is likely to be more counternormative in small towns relative to large cities and may also depend on cultural contexts.",
            "Americans were much more likely to smile, nod, or greet an approaching confederate than Japanese pedestrians, with only 2% of the Japanese smiling back compared to 25% of the Americans.",
            "Japanese pedestrians, compared to Americans, may feel less obligated to reciprocate greetings to outgroup members, and avoiding passing strangers is a simple tactic to save face in ambiguous brief encounters.",
            "In spatial invasion experiments, confederates who sat at varying distances from solitary individuals precipitated more rapid departure from the setting and subtle behavioral compensation, such as leaning or turning away, when they approached more closely, sometimes as close as 15 to 30 centimeters.",
            "When options of rapid departure or behavioral compensation are limited, such as in some seating arrangements on public transport, the close presence of others can precipitate stress reflected in enhanced cortisol levels and increased negative mood.",
        ],
    ),
    "audit": (
        "The Power of Environmental Features: Lighting, Temperature, Odor, and Sound",
        "Audit a series of rooms and dial in their lighting, temperature, odor, and noise levels, then predict how each setting should shape the encounters that occur within it. Match findings about dim lighting, physical warmth, ambient scents, and background noise to their social consequences, and flag which effects remain unresolved.",
        "A room-builder interface lets you adjust brightness, warmth, scent, and noise while a prediction panel lists intimacy, aggression, helping, and trust outcomes. An evidence wall pins each study finding to the environmental variable it tested.",
        [
            "Environmental features are physical elements that can be shared by different behavioral settings, including lighting, color, temperature, noise, smell, architectural elements, objects, and personal belongings.",
            "Early studies revealed that dimmer lighting can foster an atmosphere of intimacy, and people interacting with strangers tend to compensate by keeping a greater physical distance and reducing the amount of mutual eye gaze.",
            "Dim lights are specifically utilized in bars, parties, and bedrooms to decrease social inhibition, and experimental studies provide evidence that dimmer lighting loosens social inhibition and elicits feelings of anonymity.",
            "Dim lighting enhances the likelihood of antisocial behavior such as aggression or dishonesty toward strangers, but it also fosters prosocial behavior that requires overcoming social reservations, such as mutual touch, self-disclosure, and collaboration.",
            "Individuals instructed to recall a previously committed antisocial deed judged an experimental room to be darker than those instructed to recall a prosocial deed, suggesting a bidirectional link between social disinhibition and experiences of darkness.",
            "Dim lighting conditions impoverish a perceiver's ability to encode highly detailed visual information, increasing the perception of others as random instances of social categories rather than as unique individuals.",
            "Early studies conceptualized hot temperatures above 30 degrees Celsius as a thermal stressor and found that heat reduces people's attraction to one another and fosters interpersonal aggression.",
            "Decades of social psychological research suggest that the assessment of warmth plays a pivotal role when forming impressions, as perceivers who establish whether a person is warm or cold frequently also infer whether the person is generous, sociable, and popular.",
            "Briefly holding a cup of hot rather than cold coffee tempts individuals to rate a stranger as warmer and friendlier, and touching a warm therapeutic pack increases trust toward a stranger in a nonverbal online trust game.",
            "In the presence of pleasant environmental smells, strangers are more likely to offer each other help, and pleasant scents indicative of cleanness promote reciprocity and charitable intentions.",
            "People's willingness to assist others decreases as noise intensity increases, and further evidence suggests that noise can result in cognitive overload that interferes with people's capacity to process social cues.",
            "Noise enhances aggression especially in angered individuals, although loud noise itself is not sufficient to induce interpersonal aggression in individuals not previously angered.",
        ],
    ),
    "matrix": (
        "Architectural Elements, Objects, Color, and Mobile Technology",
        "Rearrange a room's anchors, seating, objects, and color accents, and predict how each change should alter the interaction patterns occurring in the space. Assign findings about barriers, personal belongings, stereotypical objects, colored clothing, and mobile device use to their social consequences.",
        "A floor-plan editor lets you add walls, seating, and decorative objects while an occupancy heatmap shows where people linger. A wardrobe panel tests red, black, and neutral clothing against impression ratings, and a sidewalk clip shows pedestrians interacting while using mobile devices.",
        [
            "Architectural elements such as walls, columns, and partitions, collectively termed anchors, are design features that can facilitate and support but also interfere with interpersonal exchange.",
            "Seating options in public spaces are important features that allow people to stop and engage in prolonged social encounters.",
            "Blocking the visibility of a partner with a barrier prevents gaze exchange and interferes with both information transfer and turn taking.",
            "Spatial proximity toward strangers produces more discomfort in a space confined by walls, such as a vacant room, than in an unconfined space, and this effect may differ depending on a person's cultural background.",
            "Interracial encounters in a confined space enhance the accessibility of aggression-related concepts such as attack or punch, whereas similar encounters in an open field elicit heightened accessibility of withdrawal concepts such as flee and run.",
            "Occupants influence the belongings and objects in their environments by selecting objects they like to display, manipulating items in a personal manner, and unintentionally provoking changes in the objects of their environments.",
            "Perceivers rely on environmental traces such as objects and personal belongings to speculate about the social attributes of a setting's occupants, and they tend to be more accurate when judging conscientiousness than agreeableness and when judging private rather than public spaces.",
            "In a library study, females were more affected by an immediately adjacent intruder and were more likely to place their books and personal items adjacent to them, whereas males were more affected by an intruder directly opposite and placed their books and materials opposite themselves.",
            "The presence of stereotypical masculine objects such as football posters and video game boxes in a computer science classroom can signal women that they do not belong, neither in the classroom nor in the discipline.",
            "Individuals wearing black are perceived as particularly aggressive, at least in sport contexts, and women dressed in red seem to elicit heightened attraction, with male perceivers sitting closer and asking more intimate questions.",
            "Pedestrians using mobile devices smiled less than controls when a confederate initiated a look, smile, and greeting, even when the device users glanced at the confederate, suggesting that the cognitive demand of device use disrupts the automatic perception-behavior link.",
            "Mobile devices can turn into powerful means for privacy regulation in crowded environments, such as on public transport, but such devices may reduce sensitivity to nearby others and adversely affect the quality of face-to-face interactions.",
        ],
    ),
    "boss": (
        "Social Goals, Privacy, Territory, and the Ecological Systems Model",
        "Run a capstone simulation in which you set an individual's social goals, privacy needs, and setting, then watch the ecological systems model predict nonverbal outcomes across repeated iterations. Manipulate density, gaze, and territorial markers to see crowding, loneliness, and territory defense emerge, and defend your predictions to a review panel.",
        "A systems diagram with nodes for person factors, social goals, setting features, and nonverbal behavior lights up as you drag inputs between them, with outcomes feeding back into the loop. A subway car scene lets you toggle passenger density, and library tables can be dressed with personal markers to test territorial claims.",
        [
            "Social goals determine the sending and receiving of nonverbal signals and shape the dynamic relationship between the environment and nonverbal communication.",
            "The two metagoals of efficiency and appropriateness structure many interpersonal encounters across various environmental settings, and social goals can be activated without conscious awareness.",
            "The metagoal of appropriateness inclines people to abide by social norms and customs in interactions to avoid calling undue negative attention to themselves.",
            "Altman (1976) proposed that privacy is a dialectic process driven by opposing motives of being both open and closed to contact with others, ranging from low privacy at one end to high privacy at the other.",
            "According to Altman (1976), large deficits in desired high privacy are experienced as crowding, whereas large deficits in desired low privacy are experienced as loneliness.",
            "The term territory refers to a geographically limited area that is owned or controlled by an individual or group, and territoriality refers to the behaviors and cognitions related to managing and defending territories.",
            "In temporary territories, physical markers constitute a claim on the territory, and library tables with more personal markers, such as a coat or a notebook, were more resistant to intrusion from newcomers than tables with fewer personal markers.",
            "Density refers to the number of individuals per unit area as a physical state, whereas crowding refers to the negative affect or feeling resulting from high density as a psychological state.",
            "High density in social settings necessarily leads to close interpersonal distances and increased arousal, but the labeling of that arousal varies as a function of the circumstances, sometimes producing a feeling of crowding and other times a feeling of excitement and fun.",
            "Feelings of crowding can occur even in the absence of close spatial arrangements, because the psychological experience of crowding may be a product of increased nonverbal involvement, such as gaze, forward lean, or touch, from nearby others.",
            "The condition known as synomorphy describes settings in which environmental features and behavioral goals complement one another, such as close seating options in a bar encouraging social interaction and isolated tables in a library encouraging solitary reading.",
            "The relationship between the physical environment and social behavior is a reciprocal one, as individuals can act on their environments and change features, such as rearranging moveable chairs or changing lighting, to facilitate particular goals.",
        ],
    ),
}
