# -*- coding: utf-8 -*-
CHAPTER = {
    "num": 15,
    "title": "The Body: Postures, Gait, Proxemics, and Haptics",
    "authors": "David Matsumoto, Hyisung C. Hwang, and Mark G. Frank",
    "domain": "Nonverbal Communication | Body",
    "scrub": (
        "The Reading Room of Postures",
        "You enter a study lounge where you must decode the silent vocabulary of the body. Read each scenario card, identify what the posture says about the sitter's attitude, openness, and status, and label the display correctly (open/closed, dominant/submissive, congruent/incongruent) before moving to the next card. Finish by sorting the posture list into its three dimensions: liking, orientation, and attention.",
        "A softly lit lounge with leather chairs where mannequin-like figures sit in distinctive poses. Overhead captions flash posture labels like 'arms akimbo,' 'legs crossed,' and 'forward lean,' while a progress bar tracks how many postures you have decoded.",
        [
            "Postures are defined as a position of the body or of body parts, and early research showed they communicate attitudinal states and general affect rather than the specific emotions communicated by the face and voice.",
            "The attitudinal and general affective states communicated by posture include liking versus disliking, orientation (closed or open), and attention (direct or indirect), which together summarize general positivity and status relationships.",
            "Body orientation, the degree to which a person's shoulders and legs are turned toward or away from another interactant, is associated with attitude toward that interactant, with the least direct orientation occurring for disliked interactants.",
            "Open arms and legs in a seated position generally communicate a more positive attitude and openness, whereas arms akimbo (arms on hips) or arms crossed in front of one's body are generally associated with more negative attitudes.",
            "Open body postures also communicate more power, as demonstrated in research on status display (Cashdan, 1998; Hall, Coats, & LeBeau, 2005).",
            "In a study using 176 computer-generated mannequin figures, observers could not distinguish disgust, fear, and surprise beyond chance levels, but anger, sadness, and happiness were reliably attributed to a large number of postures, some with greater than 90% agreement rates.",
            "Anger postures were conveyed by a backward head tilt, absence of a backward chest bend, no abdominal twist, an arm raised forward and upward, and weight transfers either forward or backward.",
            "Happiness was conveyed by a backward head tilt, no forward movement of the chest, and arms raised above shoulder level and straight at the elbow, while sadness was conveyed by a forward head tilt, forward chest bend, no twisting, and arms at the sides.",
            "Mirroring, known as the chameleon effect, refers to the tendency to adopt the postures, gestures, and mannerisms of interaction partners, and it produces positive regard when done naturally, but deliberate mirroring makes partners feel manipulated.",
            "Nonverbal behaviors associated with rapport include smiling, direct body orientation, uncrossed legs, symmetrical arms, moderate eye contact, congruent limbs, and forward leaning postures.",
            "Tickle-Degnen and Rosenthal (1990) suggested that the development of rapport is a dynamic process involving mutual attentiveness, positivity, and posture coordination, with positivity and attentiveness more important early and coordination more important later.",
            "Posture-gesture mergers, movements in which a gesture flows directly into a postural shift, were associated with truthfulness versus deception, frustration, relaxation, and judgments of sincerity and effectiveness.",
        ],
    ),
    "dialogue": (
        "Triumph or Tremble: The Body Speaks",
        "You are a movement analyst interviewing actors who must pose a series of whole-body emotions. For each posed emotion, choose the movement profile that matches the evidence (expanded versus contracted, fast versus slow, jerkiness, arm and head positions) and decide whether the display fits pride, triumph, anger, happiness, or shame. Replay each video clip until you classify all five emotions and note which two emotions researchers have not yet cleanly separated.",
        "A dim rehearsal studio with a large mirror and a camera tripod. Actors in point-light suits walk and strike poses, and their movements render as moving dots on a screen while you select labels from a dial like pride, triumph, shame, anger, and happiness.",
        [
            "In a study of 3-second video clips, observers judged angry, happy, sad, and neutral portrayals beyond chance levels, and angry body movements were rated as jerkier, stiffer, harder, more expanded, faster, and with more action than the other emotions.",
            "Participants expressing happiness through free dance movement moved faster, with more acceleration, and made more expanded and more apparently impulsive movements than participants in the sad condition.",
            "Dael, Mortillaro, and Scherer (2012) asked 10 actors to pose 12 emotions and found evidence for patterns of postural movements associated with only three of the 12 emotions: anger, amusement/pleasure, and despair.",
            "The pride expression includes an expanded posture with head tilted back, arms akimbo, and a low-intensity smile on the face, and it is distinguished from other positive emotions.",
            "The pride expression has been reliably recognized in adults across cultures and in children as young as 4 years of age, and it is produced by individuals across cultures as well as by individuals who are congenitally blind.",
            "The triumph expression includes an expanded posture with chest out and head back, arms away from the body and raised above the shoulders, and torso pushed out, along with an aggressive component involving facial grimaces, fists, punching motions, and shouts or utterances.",
            "The triumph expression has been documented in individuals from many cultures and in congenitally blind individuals immediately after a victory in an agonistic context.",
            "Individuals from status-oriented cultures tend to produce more whole-body victory expressions than individuals from more egalitarian cultures, and people of different cultures reliably label these displays as triumph.",
            "The expression of triumph is related to dominance threat displays seen across the animal kingdom and is likely important in the creation and maintenance of status hierarchies in communities.",
            "Behaviors opposite to triumph, such as head tilted forward or down, tongue out, eyes closed, and one or both arms pulled in toward the body, have been labeled shame, but these same behaviors have also been associated with submission.",
            "There is yet to be definitive research delineating the difference between expressive behaviors related to shame and those related to submission.",
            "Movement synchrony between interactants is strongly related to rapport: Bernieri (1988) demonstrated a strong relationship between rapport and movement synchrony in teacher-student interactions, and synchrony has also been related to the quality of mother-infant interactions and opposite-sex courtship rituals.",
        ],
    ),
    "audit": (
        "The Gait Lineup",
        "You are a security analyst reviewing surveillance footage of people walking through an airport corridor. For each walker, use the gait evidence (stride length, foot swing, arm coordination, velocity, confidence) to judge emotion, likely vulnerability, and personality, and flag walkers who match the profile of a would-be victim. Match each gait signature to the correct diagnosis or application before the shift ends.",
        "A monochrome security monitor splits into four feeds showing point-light walkers striding across a checkered floor. Each feed displays animated stride lines and readings for stride length, arm swing, velocity, and footedness, while a red flag icon marks your vulnerability decisions.",
        [
            "Gait is the pattern of movement of the body when walking, and classic research suggested that gait is consistent with other expressive behaviors within an individual and thus partially accountable for one's personality (Allport & Vernon, 1933).",
            "Early studies showed that observers can accurately judge the sex of a person by gait alone, even when targets wear bulky sweatshirts with only reflectors on their shoulders, elbows, hips, knees, and other joints.",
            "Using a point-light technique in which there are no other visibly observable cues, individuals can reliably recognize people through their gait, and there is also evidence that age and sex can be reliably identified across cultures.",
            "When actors posed emotions of pride, happiness, anger, and sadness, they walked with longer strides and more exaggerated foot pounding (heavy footedness) when posing anger than when posing the other emotions.",
            "Gait patterns are different when people simulate different emotional states or while listening to different types of music, and judgments of the emotional state of individuals carrying a concealed handgun versus a concealed 1-L bottle correlated with arm swing and gait.",
            "Gait can be used as cues to determine sexual advances or inappropriate touching, as slow walkers with slow-length strides and personality traits implying vulnerability were identified as targets for inappropriate touching.",
            "Depressed patients show decreased stride length, decreased coordination of arms in movement, and slower velocity, while Parkinson's patients show reduced stride but can be trained to expand the stride by employing various visual clues.",
            "Convicted criminals agree on which people to victimize based on gait: those chosen as would-be victims had strides too long or too short, did not swing their feet, and moved in only two dimensions compared to three.",
            "Criminals who scored higher on psychopathy were more accurate in identifying previously victimized students from videotape and were more likely to mention gait, particularly the confidence in the gait, as a clue to identifying a past victim.",
            "The suggestion that the additional emotional load (such as anxiety) involved with deceptive behavior may produce gait abnormalities has practical applications such as security screening.",
            "There have been no direct studies examining cultural similarities or differences in gait, but research on the pace with which individuals move through cities shows that pace is associated with punctuality, coronary heart disease, and a variety of attitudinal and personality traits.",
            "One concern about posed-emotion studies is that actors are asked to pose emotions, so the produced behaviors may be mimes of an emotion rather than what actually happens when emotions are elicited spontaneously and naturally.",
        ],
    ),
    "matrix": (
        "Bubble Mapping: The Invisible Zones",
        "You are a proxemics consultant mapping a crowded plaza with concentric zone overlays. For each pair of interactants, drag the correct Hall zone (intimate, personal, social, public) onto their bubble, then adjust the bubble size to match the culture, context, and relationship of the pair. Complete the map without letting any bubble cross its intruder threshold, and flag the reactions that follow a violation.",
        "A top-down map of a plaza shows pairs of figures surrounded by translucent concentric bubbles labeled Intimate, Personal, Social, and Public. A slider adjusts bubble radius, and a flash and a frowning face icon appear whenever a bubble is breached, while side notes list intimacy-equilibrium responses.",
        [
            "Proxemics is the use of space in interpersonal interactions, and E. T. Hall's (1966, 1973) classic work specified four levels or zones of interpersonal space depending on social relationship type: intimate, personal, social, and public.",
            "E. T. Hall suggested that in the United States intimate distances are less than 18 in. (45.72 cm), personal distances range from 18 in. (45.72 cm) to 4 ft (1.22 m), social distances range from 4 ft (1.22 m) to 12 ft (3.66 m), and public distances are greater than 12 ft (3.66 m).",
            "Hall suggested that interpersonal distance helps to regulate intimacy by controlling sensory exposures, because the possibility of sensory stimulation (smells, sights, touch) is enhanced at closer distances.",
            "People of all cultures appear to use space according to Hall's major distinctions, but they differ in the size of the spaces they attribute to them, with cultures around the Mediterranean, Middle East, or of Latin origin generally interacting at closer distances.",
            "Arab males tend to sit closer to each other than American males, with more direct, confrontational types of body orientations, greater eye contact, and louder voices, and Arabs at least in the past learned to interact at distances close enough to feel the other person's breath.",
            "When interacting with someone from their same culture, Japanese sat the farthest away, Venezuelans the closest, and Americans in the middle, yet foreigners who spoke in English adopted the American conversational distance compared to when speaking their native language.",
            "Interpersonal spacing differs according to context: individuals chose relatively greater distances after experiencing social isolation, when they believed their interaction would be observed, and when they expected a long conversation on a personal topic.",
            "The single major factor determining interpersonal distances appears to be the relationship of the interactants, as more intimate relationships produce closer distances, with the affective tone of the interaction the next most important factor.",
            "Intermediate distances are generally rated as more comfortable, preferable, and appropriate than more extreme close or far distances, and violations of culturally appropriate space boundaries bring about aversive reactions.",
            "The intimacy equilibrium hypothesis (Argyle & Dean, 1965) suggests that people take steps to reinstate their space when boundaries are intruded, for example by staring at floor numbers in an elevator, changing body orientation away, or deploying buffers such as books or briefcases to demarcate territory.",
            "A meta-analysis demonstrated that personal space gradually and steadily increases between 3 and 21 years of age, and while a 5-year-old intruding on an adult's rear space makes the adult turn toward and speak to the child, 10-year-olds make adults move, lean away, or fidget.",
            "When people ask permission to invade space, males and females react differently: males left more quickly when the confederate sat closer and did not ask permission, whereas females left more quickly when the confederate sat closer but asked for permission.",
        ],
    ),
    "boss": (
        "The Touch Code: Reading Contact",
        "You are a cross-cultural etiquette auditor recording touch events at an international gala. For each interaction, log the toucher, the receiver, the touch type, and the greeting ritual, then classify the touch by its function and predict the reaction, including gender asymmetry, compliance effects, and whether the culture is a contact or noncontact culture. Handle every event without misreading a single touch.",
        "A grand ballroom rendered in a heat-map style where glowing hand symbols appear between interactants and trace the toucher's arm. A panel shows touch categories (embrace, handshake, pat, adaptor), a compliance meter, and a world map tinted by contact and noncontact culture classifications.",
        [
            "Touch (also known as haptics) is related to the use of interpersonal space because it requires close physical contact, and some writers consider interpersonal touch one of humankind's earliest and most basic forms of communication, owing to its importance in early mother-infant caretaking.",
            "Early research indicated that touch conveys positive emotion, closeness, comfort, compassion, intimacy, immediacy, liking, acceptance, warmth, and love, whereas withholding touch can signal negative feelings such as resentment, hostility, anger, or mistrust.",
            "Touch often has different meanings to men and women: men are more likely to interpret touch as communicating affection and sexual attraction, whereas women are more likely to separate those meanings.",
            "Recent research provided initial evidence that touch can communicate distinct emotions such as anger, fear, disgust, love, gratitude, and sympathy across cultures.",
            "Among professional basketball players, increased touch is associated with increased cooperation and improved performance, and touch by female wait staff improved tips offered at restaurants.",
            "Henley (1973, 1977) proposed that higher status individuals have a touching privilege, being allowed to touch others more often than lower status individuals to maintain and express their status differences.",
            "Being touched by close friends of the opposite sex is rated pleasant by both men and women, while being touched by an opposite-sex stranger is unpleasant for women but pleasant for men.",
            "An observational study of 799 intentional touches in public settings reported that other-gender touch was more likely to be initiated by men, and gender asymmetry has been reported in specific types of relationships such as romantic relationships but not others.",
            "Women tend to engage in more same-sex touch than men and report greater comfort with same-sex touch, an effect explained by homophobic attitudes, as men more than women are likely to be seen as homosexual if they exhibit same-sex touch.",
            "Touch increases compliance: in Kleinke's (1977) phone booth study, 96% of people who were touched returned money compared to 63% of those not touched, and touch has also increased compliance with signing petitions, completing surveys, and physicians' requests to take antibiotics.",
            "Cultures regulate touch in social interactions partly through greeting rituals, and Watson (1970) classified 30 countries as either contact cultures (those that facilitate physical contact) or noncontact cultures, a classification largely confirmed by later research.",
            "Self-touching movements, generally called adaptors or manipulators, allow individuals to adapt to internal or external stimuli and have been linked to negative affect, anxiety, withdrawal, hostility, depression, information processing, language construction, Type A behaviors, and attentional focusing, making self-touch an important signal of psychological functioning.",
        ],
    ),
}
