# -*- coding: utf-8 -*-
CHAPTER = {
    "num": 22,
    "title": "Measuring Body Movement: Current and Future Directions in Proxemics and Kinesics",
    "authors": "Nele Dael, Nadia Bianchi-Berthouze, Andrea Kleinsmith, and Christine Mohr",
    "domain": "Nonverbal Communication | Body Movement",
    "scrub": (
        "A Long History of Diverging Approaches",
        "Trace the historical roots of body movement measurement from 17th-century treatises to today's computational sciences. Identify the two major driving forces of methodological development and explain why no golden standard for measuring body movement has yet crystallized.",
        "A museum-like timeline gallery unfolds, showing a plate of hand shapes and supposed meanings from Bulwer's Chirologia of 1644 beside portraits of Darwin and a modern lab with high-resolution motion tracking cameras. Overlay cards flag the two driving forces: pragmatic solutions to theoretical questions and technological advancement.",
        [
            "Methodological development in nonverbal behavior research has two major driving forces: the need for a pragmatic solution to investigate a priori theoretical questions and technological advancement creating new affordances.",
            "The current surge of multimodal accounts of emotion expression and perception demands time-based descriptions of body movement that can be integrated with other time-based accounts from vocal or facial behavior.",
            "Western interest in labeling or describing body movement goes back centuries; Bonifacio (1616) and Bulwer (1644) emphasized the role and importance of body actions as a natural human language.",
            "Darwin (1872) was the first to focus on the functional role of body movement in emotion communication in humans and animals, treating body actions and postures as signs of internal emotional processing.",
            "Clinical psychology focuses on the diagnostic and therapeutic value of nonverbal behavior and, in particular, on behaviors that foster empathy and rapport during clinician-patient interaction.",
            "The multifunctionality, in addition to the anatomical complexity, of the skeletal body system logically leads to a high diversity in descriptive methods.",
            "Even within a research tradition or discipline, there is no consensus on a conceptual framework of body movement from which methods can be derived.",
            "Two scientific virtues seem to stand in opposition to each other in method development: generality and selectivity.",
            "The facial and vocal domains saw a crystallization toward golden standards such as the Facial Action Coding System and standardized vocal extraction techniques, but no such crystallization in measuring body movement has yet occurred.",
            "Researchers tend to focus either on the factors that determine nonverbal behavior at the individual level or microlevel, or on interactions at the macrolevel as influenced by cultural and social dynamic factors.",
            "A research field advances when a common methodology is applied that makes results from different studies comparable.",
        ],
    ),
    "dialogue": (
        "Kinesics: Coding Systems for Body Movement",
        "Act as a kinesics researcher selecting a coding system for a study of emotional body movement. Compare functional, anatomically based form, and spatio-temporal levels of description, and defend a choice using the chapter's reliability evidence.",
        "A split-screen coder interface shows the Body Action and Posture (BAP) coding system's graphical timeline next to a Labanotation score with effort and shape symbols. Hovering over body part labels reveals whether a description is functional, form-based, or spatio-temporal.",
        [
            "Kinesics refers to the study of skeletal body movement, that is, movements of the head, torso, and limbs, excluding gaze and facial expressions.",
            "Birdwhistell, who originally coined the term kinesics, developed one of the first coding systems aimed at exhaustive symbolic transcription of body movement, segmenting it into kinemes, kinemorphs, and kinemorphic constructions.",
            "Laban developed a system of dance notation later referred to as Labanotation, which uses a complex collection of symbols providing highly detailed descriptions of upper and lower body actions and positions.",
            "In kinesics, a posture represents the general alignment of the body to a particular position or configuration, whereas an action is a local excursion of one or more articulators outside a resting configuration.",
            "Gestures are usually distinguished from other body movements by the defining feature that they are voluntary actions arising from the deliberative attempt to convey semantic and pragmatic information.",
            "Based on the work of David Efron, Ekman and Friesen developed a typology distinguishing illustrators, emblems, manipulators or adaptors, and regulators depending on their socioaffective function.",
            "Functional coding systems involve a higher level of inference about the function and purpose of a behavior than pure descriptive coding systems, and form-based descriptions tend to be more reliable than functional ones.",
            "Descriptions of movement form such as direction and orientation are founded in anatomical kinesiology, describing the moving body part with respect to three orthogonal, Cartesian axes (sagittal, vertical, and transversal).",
            "The Body Action and Posture coding system provides 141 codes for the time-aligned microdescription of body movement, which is segmented in posture or action units.",
            "Labanotation puts particular emphasis on the description of the temporal dynamics of body movement, describing movement qualities as aspects of effort and shape.",
            "Intercoder reliability of Laban-derived descriptions has in the past either not been reported or been found difficult to achieve, perhaps due to the high level of subjective interpretation involved.",
            "Gait research in particular has much advanced since the application of refined kinematic analyses derived from motion tracking, and dimension reduction techniques such as principal component analysis are typically applied to model gait.",
        ],
    ),
    "audit": (
        "Sampling Techniques and Human Observation",
        "Plan an observational study of expressive body movement in dyadic interaction. Choose sampling and coding strategies, decide between expert coding and human judgment, and specify how reliability will be established.",
        "A research lab whiteboard fills with flowcharts of event coding, interval coding, and time sampling strategies, while a video annotation window in ANVIL shows color-coded behavior streams on a timeline. A small table of thin-slice correlations updates beside a reliability panel computing Cohen's kappa.",
        [
            "Altmann's widely cited review presents a summary of the characteristics of seven major types of behavior samples and their recommended uses.",
            "Event coding is probably the most common way of recording observational data, allowing flexible data analysis because the observer detects codable events whenever they occur during the stream of behavior.",
            "In interval coding, time is divided into a number of successive intervals and the observer classifies each interval or codes whether certain events occur during it.",
            "Murphy (2005) tested the use of short behavior-coded segments, or thin slices, to predict behavior across longer interactions, and correlations were high for most categories except self-touch.",
            "The judgment method is perhaps the most commonly used method in studies of nonverbal behavior, in which skilled or naive judges rate behavior on a particular attribute or psychological construct.",
            "Coding schemes provide explicit definitions of the behaviors relevant to the study, and Bakeman and Gottman systematically listed desirable features such as the use of mutually exclusive and exhaustive codes.",
            "A typical coding process consists of trained observers following a standardized protocol, after which they independently code a common part of the material and take an intercoder agreement test.",
            "Expert coding is increasingly facilitated by manual video annotation software such as ANVIL, ELAN, and The Observer, which guide standardized and precise time-locked coding.",
            "In judgment studies, adding more judges increases the mean reliability, but high interrater agreement does not imply that observers correctly perceive the behavior, which is a question of validity.",
            "The most commonly used statistic for establishing reliability of behavior coding is Cohen's kappa coefficient, which corrects for chance agreement.",
            "Wallbott (1985) found that lay judgments of hand movement quality were reliably but incorrectly used in evaluating a patient's psychopathological state, whereas the coded hand movement parameters did not differ between therapy admission and discharge.",
            "Pollick and colleagues found that attributions of emotional activation to instrumental arm movements were positively related to temporal movement parameters such as velocity, acceleration, and jerk.",
        ],
    ),
    "matrix": (
        "Automatic Body Movement Processing",
        "Engineer a pipeline for automatic affect recognition from body movement. Select a sensor technology, describe the steps of tracking, segmentation, feature extraction, and classification, and weigh the advantages and drawbacks of each system type.",
        "A high-tech control room displays three capture setups side by side: an optical mocap studio with infrared cameras and reflective markers, a subject in an inertial sensor suit, and a Kinect depth camera with a skeleton overlay. A processing pipeline diagram lights up from body tracking to hidden Markov model classification.",
        [
            "The most notable systems for automatic tracking of body movements are optical motion capture systems, electromechanical or electromagnetic motion capture systems, and markerless vision-based systems.",
            "Many optical motion capture systems such as Vicon and OptiTrack make use of infrared cameras, generally 8-12, to track retro-reflective markers placed on the body and provide the 3D positions of each marker as output.",
            "Electromechanical or electromagnetic motion capture systems require the person to wear active sensors, such as inertial sensors, accelerometers, or magnetometers, which are generally integrated in a suit for full body capture.",
            "Markerless vision-based systems use video or web cameras to record movement and process the data with image-processing techniques to determine the position and orientation of the body.",
            "Variations in lighting conditions, skin color, clothing, body part occlusion, and touching can cause difficulties in automatically extracting, segmenting, and recognizing body movement from complex scenes with vision-based systems.",
            "The Kinect is a low-cost markerless vision-based sensor that projects infrared patterns for depth recovery of motion, and software libraries allowing the extraction of the 3D body skeleton have made it popular even among non-experts.",
            "Feature extraction approaches can be divided into two main categories: spatial action representation, which focuses on body configuration, and temporal action representation, which models the temporal relations between spatial information.",
            "Image-based model approaches detect the body area, such as its silhouette, rather than identifying the different body parts, and have shown results similar to the body model-based methods.",
            "The most used approach to classify a temporal sequence of movement is the hidden Markov model, which is very good at modeling sequential aspects of an overall movement but not at modeling independent body parts.",
            "Automatic classification schemes are starting to be proposed as a way to substitute and improve existing scales for the measurement of higher order phenomena, such as continuously tracking a patient's body behavior to detect level of depression.",
            "Motion tracking allows the body to be represented as three-dimensional according to Cartesian axes and/or Euler angles, which makes computing feature sets reasonably straightforward.",
            "By just using minimalistic sensors such as a smartphone, activity classification can be carried out by exploiting kinematic features gathered by a gyroscope or accelerometer without having to wear sensors on all body parts.",
        ],
    ),
    "boss": (
        "Future Challenges: Behavioral Patterning and Real-Life Settings",
        "Design the next-generation methodology for body movement research: integrate multimodal behavior streams through reliable segmentation and patterning, and move measurement into real-life settings with unobtrusive sensors. Defend the research question as the guide to method choice.",
        "A city street scene dissolves into an overlay of the Brunswik lens model, linking a smiling walker's distal kinematic cues to a perceiver's proximal impressions and attribution. Beside it, the Theme software displays hierarchically organized T-patterns over a timeline, while a wearable sensor jacket traces movement data in the corner.",
        [
            "Unlike spoken language, body movement does not form a language that is out there waiting to be deciphered, and its meaning or diagnostic value is best described as probabilistic.",
            "The theoretical perspective of probabilistic functionalism accounts for variability in interpersonal perception and was formalized by Brunswik in his lens model of visual perception.",
            "Effective communication requires both encoding and appropriate decoding and, thus, a shared lens code between expressor and perceiver, and mismatches between encoding and decoding can present valuable insights.",
            "With no objective ground truth available in field studies, self-report or observer ratings often provide the best, though likely erroneous, approximation of the encoded variable.",
            "Nonverbal behaviors rarely occur in isolation, and often compounds of behaviors co-occur and are interdependent within and across modalities such as face, voice, and body.",
            "Principal component analyses and cluster analyses allow the detection of co-occurring events grouped as higher order behavior components or clusters.",
            "The transitional probability is a basic statistic for describing sequences, and lag-sequential methods offer a more flexible approach to investigate sequences comprising more than two events.",
            "Magnusson proposed the computer program Theme, which detects T-patterns, hierarchically organized patterns of recurrent behaviors that do not need to immediately follow each other.",
            "Optical motion capture systems are not practical outside of a controlled environment, so the focus needs to be on unobtrusive and lightweight sensors that can be placed directly on the body without requiring cameras.",
            "Accelerometers have become the preferred choice for continuous, unobtrusive, and reliable human movement detection and monitoring.",
            "Fully wireless EMG systems offer less obtrusive ways to measure muscle activation, and wireless EMG systems have been shown useful in the field of affective body expressions.",
            "Methods in proxemics and kinesics are often used together even though they have different historical origins, and the choice of method should be guided by the research question.",
        ],
    ),
}
