# -*- coding: utf-8 -*-
"""Phase 2 chapter data for Attached (Levine & Heller), chapters 1-5.
Each chapter: num, title, pages, domain, and 5 slots (scrub/dialogue/audit/matrix/boss),
each slot a 4-tuple (topic, player_mission, visual_frame_description, key_concepts[8-12]).
"""

D = "Attachment Theory | Biological Need for Connection"

CHAPTERS = [
    {
        "num": 1,
        "title": "Everyone Needs Connection",
        "pages": "7-11",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Separation Distress Detector",
            "Scan 12 everyday scenes and spot the sign of attachment distress in each one: restlessness when a spouse is away, blood pressure climbing at a partner's presence, or the relief of a hand held during a stressful moment. Name the need behind the behavior and decide whether the person has a deep connection that can keep them calm.",
            "A city street of couples and families, each scene frozen mid-moment with a glowing tag labeling the attachment behavior - a hand clasp, a worried glance, a blood pressure meter - while a distress meter spikes in red.",
            [
                "To live a healthy and happy life, everyone needs connection",
                "When we know our spouse won't be around for a long time, we all get a creeping sensation called distress",
                "Our emotions of connection to one another lead us to be distressed when we are separated from our spouse",
                "Attachment is a deep connection formed between two individuals that lasts through time and creates a particular desire to stay in touch",
                "Attachment may be a connection between a mother and her kid or a love relationship between two people",
                "There are surprisingly many advantages to establishing deep personal connections",
                "A deep personal connection provides a solid emotional foundation that allows us to stay calm even in stressful circumstances",
                "Grasping your partner's hand through stressful moments gives you comfort in knowing that this particular someone will support you",
                "Even the most unpleasant circumstances become considerably less scary as a result of a deep personal relationship",
                "Researchers put female volunteers in a stressful scenario while allowing some of them to hold their partner's hand",
                "A participant who could grasp her partner's hand had a less active hypothalamus than when she was forced to deal with the stress alone",
                "Those who lack attachment connections are more likely to be unhappy and to suffer severe health problems",
            ],
        ),
        "dialogue": (
            "Dialogue: The Goodbye Distress Exchange",
            "Interview a woman on a lab sofa as researchers attach a stress monitor: question her about separation from her spouse and about an unhappy marriage, and predict how her hypothalamus and blood pressure respond at each stage. Then take the partner's seat and explain what a deep personal connection provides during stressful circumstances.",
            "A university lab split in two: on one side a stress monitor brain map glows while a woman grips her partner's hand, and on the other a couple sits at a kitchen table while a blood pressure cuff ticks upward.",
            [
                "The hypothalamus is the region of the brain that causes us to experience emotional strain",
                "When a participant could grasp her partner's hand, her hypothalamus was less active than when she was forced to deal with the stress alone",
                "We suffer not just emotionally but also physically when we are in an unpleasant relationship",
                "If you are unhappy in your marriage, your partner's presence may increase your blood pressure owing to the discomfort you experience when you are around them",
                "Your blood pressure will stay elevated as long as you are around them, which may lead to severe medical issues such as heart disease",
                "Attachment lasts through time and creates a particular desire to stay in touch with the other person",
                "Distress is the creeping sensation that arises when we know our spouse will not be around for a long time",
                "Knowing that a particular someone will support you provides comfort during stressful moments",
                "Even the most unpleasant circumstances become considerably less scary as a result of a deep personal connection",
                "Those who lack attachment connections are more likely to be unhappy and to suffer severe health problems",
                "Attachment may be a connection between a mother and her kid or a love relationship between two people",
            ],
        ),
        "audit": (
            "Audit: The Hand-Hold Stress Field Log",
            "Spend an afternoon logging every moment you notice a need for connection: separation from a spouse, an offered hand during stress, or discomfort at a partner's presence. For each entry record the physical reaction it triggers - calm hypothalamus activity, elevated blood pressure, or distress - and classify whether the person has a solid emotional foundation.",
            "A field notebook overlaid on a park bench: entries auto-fill as couples pass, each tagged with a hypothalamus meter or a blood pressure gauge while a connection-score bar fills.",
            [
                "A solid emotional foundation is provided by having a deep personal connection with someone",
                "In the hand-holding research, female volunteers were placed in a stressful scenario while some were allowed to hold their partner's hand",
                "The hypothalamus, the region of the brain that causes us to experience emotional strain, was less active in participants who could grasp their partner's hand",
                "Unpleasant relationships make us suffer physically as well as emotionally",
                "In an unhappy marriage, your partner's presence can increase your blood pressure because of the discomfort you feel around them",
                "Blood pressure that stays elevated as long as an unhappy partner is around may lead to severe medical issues such as heart disease",
                "People without attachment connections are more likely to be unhappy and to suffer severe health problems",
                "The emotions of connection to one another lead us to be distressed when separated from our spouse",
                "Grasping your partner's hand through stressful moments provides comfort in knowing that this particular someone will support you",
                "Attachment is a deep connection between two individuals that lasts through time and creates a desire to stay in touch",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Connection x Distress x Health Grid",
            "Fill the grid for 10 connection scenarios from the chapter: classify each as a mother-child or love relationship, mark whether it creates a desire to stay in touch, and record the physical evidence - less active hypothalamus, elevated blood pressure, or distress at separation. Then rank the scenarios by how well the connection provides a solid emotional foundation.",
            "A wall of glowing cells in a data vault; each scenario card drops into a row, lighting green for a deep connection and red for distress, while the hypothalamus and blood pressure icons stamp the verdict.",
            [
                "Attachment is a deep connection formed between two individuals that lasts through time and creates a particular desire to stay in touch",
                "An attachment connection may be between a mother and her kid or between two people in a love relationship",
                "The sensation called distress creeps in when we know our spouse will not be around for a long time",
                "Our emotions of connection to one another are what lead us to be distressed when separated from our spouse",
                "A deep personal connection provides a solid emotional foundation that keeps us calm in stressful circumstances",
                "Grasping your partner's hand through stressful moments provides the comfort of knowing that this particular someone will support you",
                "In the hand-holding study, female volunteers in a stressful scenario could grasp their partner's hand - and their hypothalamus was less active when they did",
                "Those who lack attachment connections are more likely to be unhappy and to suffer severe health problems",
                "An unhappy marriage can raise your blood pressure through your partner's presence alone, and the elevation lasts as long as they are around",
                "Sustained elevated blood pressure from an unpleasant relationship may lead to severe medical issues such as heart disease",
                "Even the most unpleasant circumstances become considerably less scary because of a deep personal connection",
            ],
        ),
        "boss": (
            "Boss Battle: The Hypothalamus Stress Chamber",
            "Run the final stress chamber: a participant faces the worst-case scenario alone, then with her partner's hand to hold, then inside an unhappy marriage. Predict hypothalamus activity, blood pressure, and distress at each stage, and choose which outcomes lead to severe medical issues such as heart disease.",
            "A circular chamber with three booths - solo, hand-holding, and hostile-couple - each with a brain and blood pressure readout climbing or falling while the distress meter swings between calm and panic.",
            [
                "Everyone needs connection to live a healthy and happy life",
                "Distress is the creeping sensation we get when we know our spouse will not be around for a long time",
                "Attachment lasts through time and creates a particular desire to stay in touch with the other person",
                "A deep personal connection provides a solid emotional foundation that allows us to stay calm even in stressful circumstances",
                "Female volunteers who held their partner's hand in a stressful scenario showed less activity in their hypothalamus, the region of the brain that causes emotional strain",
                "People who lack attachment connections are more likely to be unhappy and to suffer severe health problems",
                "We suffer not just emotionally but also physically when we are in an unpleasant relationship",
                "The presence of a partner in an unhappy marriage may increase your blood pressure, which stays elevated as long as they are around",
                "Blood pressure that stays elevated around a partner may lead to severe medical issues such as heart disease",
                "Attachment may be a connection between a mother and her kid or a love relationship between two people",
                "The discomfort you experience when around a partner in an unhappy marriage is what raises your blood pressure",
                "Even the most unpleasant circumstances become considerably less scary as a result of a deep personal connection",
            ],
        ),
    },
    {
        "num": 2,
        "title": "Our Desire for Connection Is Inherited and Shaped by Upbringing",
        "pages": "12-13",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Built-In Bond Scanner",
            "Scan 12 moments from infancy to adulthood and identify the origin of each bond: a newborn's inborn craving, a parent responding to a child's needs, or a later relationship reshaping an attitude. Tag each signal as built into DNA, shaped by upbringing, or influenced by adult experience.",
            "A family timeline flowing across a living room wall: a crib, a dinner table, and a dating scene each beam their bond signals into a scanner that stamps them DNA, UPBRINGING, or EXPERIENCE.",
            [
                "We've been designed by nature to form bonds - when it comes to attachment, it all comes down to our genes",
                "We want connection from the moment we are born",
                "The need for attachment is built into our DNA rather than learned because having a connection is enjoyable",
                "The urge for connection can be traced all the way back to the dawn of time",
                "Our forefathers discovered that depending on one another was the only way to endure the trials of existence and the continuous danger of predators",
                "Only those who were successful in finding trustworthy spouses were able to have children",
                "Our ancestors passed on the genes that assisted their children in finding reliable companions",
                "Our life experiences may affect our genetic propensity to attachment",
                "Even though our partners may drive us crazy at times, we still adore them and want for their love to be reciprocated",
                "Parents' views about relationships in general are shaped by how they treat their children",
            ],
        ),
        "dialogue": (
            "Dialogue: The Upbringing Influence Exchange",
            "Play both sides of a parenting conversation: the parent who forms a secure relationship by knowing the difference between a child wanting affection and being hungry, and the adult whose later engagement turned tumultuous. Explain how each experience shapes the child's chance of secure relationships as an adult.",
            "A split-screen nursery and apartment: on one side a parent reads a child's cues correctly and the relationship gauge rises, on the other a couple argues and the attitude meter dips.",
            [
                "When parents form a secure relationship with their child, providing adequate attention and responding appropriately to the child's needs, it is more likely that this person will have secure relationships as an adult",
                "Parents who respond appropriately know the difference between their child's behavior when he wants affection versus when he is hungry",
                "A child's failure to form solid connections is not always the fault of the child's parents",
                "Relationships that we have later in life may also affect our attachments",
                "Having a tumultuous romantic engagement as an adult may have a negative impact on your attitude about relationships",
                "A negative attitude from a tumultuous engagement may lead future relationships to suffer as a consequence",
                "The need for attachment is built into our DNA",
                "We've been designed by nature to form bonds",
                "Our life experiences may affect our genetic propensity to attachment",
                "Parents' views about relationships in general are shaped by how they treat their children",
            ],
        ),
        "audit": (
            "Audit: The Relationship History Field Log",
            "Keep a field log of every factor that shaped a person's attachment: early parenting, the search for trustworthy companions, and adult romantic turmoil. For each entry record whether it comes from genes, from how parents treated the child, or from later relationships, and note the likely effect on future bonds.",
            "A school hallway converted into a timeline; each life event card drops into a logbook that stamps it GENETIC, UPBRINGING, or LATER EXPERIENCE as a relationship forecast scrolls by.",
            [
                "We want connection from the moment we are born",
                "Depending on one another was the only way our forefathers could endure the trials of existence and the continuous danger of predators",
                "Only those who succeeded in finding trustworthy spouses were able to have children, passing on the genes that assisted them in finding reliable companions",
                "Providing adequate attention and responding appropriately to a child's needs makes secure relationships as an adult more likely",
                "A child's failure to form solid connections is not always the fault of the child's parents",
                "Relationships we have later in life may also affect our attachments",
                "A tumultuous romantic engagement as an adult may negatively impact your attitude about relationships",
                "Future relationships may suffer as a consequence of a negative attitude shaped by a tumultuous engagement",
                "Our different connection requirements influence our actions in partnerships",
                "The need for attachment is built into our DNA, not learned because having a connection is enjoyable",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Genes x Upbringing x Experience Grid",
            "Fill the grid for 10 influences on attachment: classify each as inherited from DNA, shaped by childhood parenting, or produced by later relationships, then mark whether it helps or harms the ability to find reliable companions. Cite the ancestors' predator-era discovery and the tumultuous-engagement example as evidence.",
            "A grand hall of columns labeled DNA, UPBRINGING, and EXPERIENCE; each influence card flies to a column and lights up while a family tree glows in the background.",
            [
                "The need for attachment is built into our DNA",
                "Nature designed us to form bonds - it all comes down to our genes",
                "Life experiences may affect our genetic propensity to attachment",
                "Parents' views about relationships in general are shaped by how they treat their children",
                "A secure parent-child relationship with adequate attention and appropriate responses makes secure adult relationships more likely",
                "A child's failure to form solid connections is not always the fault of the child's parents",
                "Relationships we have later in life may also affect our attachments",
                "A tumultuous romantic engagement as an adult may negatively impact your attitude about relationships and lead future relationships to suffer",
                "Our forefathers found that depending on one another was the only way to endure the trials of existence and the continuous danger of predators",
                "Only those who found trustworthy spouses passed on the genes that assisted their children in finding reliable companions",
                "We want connection from the moment we are born",
            ],
        ),
        "boss": (
            "Boss Battle: The Trustworthy Companion Trial",
            "Take the final trial: three candidates want a lasting bond, and you must trace each one's attachment back to its source - genes designed by nature, parents who responded to needs, or a later tumultuous romance. Decide who passes on the genes that helped ancestors find reliable companions, and who suffers future relationships as a consequence.",
            "A stone hall of judgment where three life maps unroll from crib to adulthood; each branch lights to its source while the ancestral cave of early humans glows through a window.",
            [
                "It all comes down to our genes: we've been designed by nature to form bonds",
                "The urge for connection can be traced back to the dawn of time, when our forefathers depended on one another to endure the trials of existence",
                "Only those who were successful in finding trustworthy spouses were able to have children",
                "Genes that assisted in finding reliable companions were passed on to children",
                "When parents form a secure relationship with their child, providing adequate attention and responding appropriately to their needs, secure adult relationships are more likely",
                "A child's failure to form solid connections is not always the fault of the child's parents",
                "Relationships we have later in life may also affect our attachments",
                "A tumultuous romantic engagement as an adult can negatively impact your attitude about relationships and lead future relationships to suffer",
                "We want connection from the moment we are born",
                "Partners may drive us crazy at times, yet we still adore them and want their love reciprocated",
                "Our different connection requirements influence our actions",
            ],
        ),
    },
    {
        "num": 3,
        "title": "Anxious Attachment - Need for Closeness and Reassurance",
        "pages": "14-16",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Preoccupation Signal Sweep",
            "Scan 12 relationship moments and spot the anxious signal in each: an obsession with the relationship, a fear that the spouse does not love them enough, a declined call read as rejection, or a need for constant contact. Name the attachment style and decide whether the person takes their partner's actions personally.",
            "A phone booth on a rainy street; each scenario freezes with a red ring around the anxious cue - a declining call icon, a worried frown, a missed text - while a worry meter climbs.",
            [
                "People with an anxious attachment style are obsessed with their relationships",
                "Anxious individuals are always concerned that their spouse does not love them enough",
                "An anxious attachment style is marked by a desire for constant contact with your spouse",
                "A proclivity to take their spouse's actions personally marks the anxious attachment style",
                "We don't all have the same reactions to our attachments even though we all have a tremendous need for connection",
                "Our perspectives on relationships and how they should work vary",
                "Attachment style influences our love conduct",
                "The distinctions between attachment types aid in classifying individuals whose attachment style influences their love conduct",
                "An anxious person may fear that a declined call means the spouse has lost interest",
                "Calling your spouse at work because you miss her, then hearing only a dial tone when she declines the call, can trigger anxiety and concern",
            ],
        ),
        "dialogue": (
            "Dialogue: The Declined Call Replay",
            "Replay the declined-call conversation from both seats: the caller who misses her spouse and spirals into fear that she has lost interest, and the spouse who calls back half an hour later to apologize for being in a meeting. Choose the moments where anxious preoccupation shows, then rewrite the ending with a partner who meets the need for contact.",
            "Two phone booths facing each other across a street: the left fills with worry lines and a dial-tone icon, while the right glows with an apology message after thirty minutes of anxious silence.",
            [
                "If you call your spouse at work because you are missing her and she declines the call, you may get anxious and concerned",
                "An anxious person fears that a declined call means the spouse may have lost interest",
                "The spouse calls back half an hour later, after the caller has become ill with worry, to apologize",
                "The spouse explains she was in a meeting and could not answer her phone",
                "If the declined-call scenario seems like something you or your spouse would do, one of you has an anxious attachment style",
                "Anxious attachment is marked by a desire for constant contact with your spouse",
                "Anxious attachment includes a proclivity to take your spouse's actions personally",
                "Anxious individuals are obsessed with their relationships",
                "Anxious individuals are always concerned that their spouse does not love them enough",
                "We don't all have the same reactions to our attachments even though we all have a tremendous need for connection",
            ],
        ),
        "audit": (
            "Audit: The Emotional Resources Hunt Log",
            "Log every relationship moment that reveals an anxious attachment style: constant contact demands, taking the spouse's actions personally, and worrying that the spouse does not love them enough. For each entry record what kind of partner would meet the requirement - a safe attachment type, someone at ease with intimacy, or a person with emotional resources.",
            "A coffee shop overlaid with observation tags; each anxious behavior pings into a field log while a partner-compatibility dial spins toward SAFE, INTIMATE, or MISMATCH.",
            [
                "If an anxious style describes your personality, you should look for someone who has the emotional resources to give you emotional stability",
                "If you were to date someone who couldn't meet your requirements, your relationship would be miserable",
                "Look for someone who is eager and capable of meeting your demand for continuous availability",
                "Someone with a safe attachment type will make you feel genuinely loved and understood",
                "Someone who is at ease with intimacy will make you feel genuinely loved and understood",
                "A safe partner will be aware of your requirements",
                "A safe partner will always be ready to speak with you about your concerns",
                "People with an anxious attachment style have a desire for constant contact with their spouse",
                "A proclivity to take the spouse's actions personally marks the anxious attachment style",
                "Attachment styles classify individuals whose attachment style influences their love conduct",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Anxious x Safe x Mismatch Grid",
            "Fill the grid for 10 partner matchups: mark each partner as having emotional resources or not, safe attachment type or not, and eager for continuous availability or not, then score whether the anxious person feels loved and understood or lands in a miserable relationship.",
            "A matchmaking grid on a dating-app wall; each partner card slides into a row and stamps LOVED AND UNDERSTOOD or MISERABLE as a compatibility meter fills.",
            [
                "An anxious attachment style is marked by a desire for constant contact with your spouse",
                "Anxious individuals have a proclivity to take their spouse's actions personally",
                "Anxious people are always concerned that their spouse does not love them enough",
                "A partner who cannot meet your requirements will make the relationship miserable",
                "Someone with a safe attachment type is eager and capable of meeting your demand for continuous availability",
                "A person who is at ease with intimacy will make you feel genuinely loved and understood",
                "A safe partner is aware of your requirements and always ready to speak with you about your concerns",
                "People with the emotional resources to give you emotional stability are the right partners for an anxious style",
                "Our perspectives on relationships and how they should work vary",
                "The distinctions between attachment types aid in classifying individuals whose attachment style influences their love conduct",
            ],
        ),
        "boss": (
            "Boss Battle: The Continuous Availability Search",
            "Run the final search: an anxious person must find the partner who gives emotional stability, and you must judge every candidate on emotional resources, ease with intimacy, and willingness to speak about many concerns. Choose the partner who meets the demand for continuous availability before the relationship ends in misery.",
            "A grand hall of doors, each hiding a candidate profile; the right door glows green with a safe-attachment badge while the wrong doors flash red with warnings about a miserable relationship.",
            [
                "We all have a tremendous need for connection, but we don't all have the same reactions to these attachments",
                "Anxious individuals are obsessed with their relationships",
                "Anxious attachment includes a desire for constant contact and a proclivity to take the spouse's actions personally",
                "If you have an anxious style, look for someone with the emotional resources to give you emotional stability",
                "Dating someone who couldn't meet your requirements would make your relationship miserable",
                "Look for someone eager and capable of meeting your demand for continuous availability",
                "Someone with a safe attachment type, or at ease with intimacy, will make you feel genuinely loved and understood",
                "A safe partner will be aware of your requirements and always ready to speak with you about your concerns",
                "In the declined-call example, the spouse apologizes half an hour later, saying she was in a meeting and could not answer her phone",
                "Fearing that a declined call means lost interest is typical of the anxious attachment style",
            ],
        ),
    },
    {
        "num": 4,
        "title": "Avoidant Attachment - The Pursuit of Independence",
        "pages": "17-19",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Avoidant Distance Scanner",
            "Scan 12 couple moments and spot the avoidant signal: a partner keeping distance to protect independence, irritation at a coffee slurp, trouble reading the other's emotions, or blame thrown at the spouse during difficulties. Name the deactivation tactic and decide whether the person is searching for 'the one'.",
            "A dinner table viewed from across the room; each scenario freezes with an avoidant cue ringed in blue - a chair pushed back, a wince at a slurp - while an independence meter holds steady.",
            [
                "An avoidant individual strives to preserve their autonomy when in a relationship",
                "People with an avoidant attachment style avoid becoming too close to others for fear of losing their independence",
                "Avoidants have a hard time recognizing others' emotions",
                "Having a hard time recognizing others' emotions makes it difficult for avoidants to sustain connections",
                "The desire for attachment exists in avoidants as well, but they express it in a different way",
                "When it comes to dating, avoidants are often on the lookout for 'the one'",
                "Avoidants are irritated by little details about their partners, such as the way they slurp their coffee or sneeze in a high-pitched tone",
                "Finding little 'issues' gives avoidants an excuse to maintain an emotional distance in their search for 'the one'",
                "A relationship where your spouse is too reliant on you can feel entirely trapped",
                "Avoidants don't see why it's so essential to be fully reliant on anybody",
            ],
        ),
        "dialogue": (
            "Dialogue: The Ideal Relationship Interrogation",
            "Interrogate the avoidant partner about their set image of the ideal relationship: ask how they make concessions, why little details like a high-pitched sneeze irritate them, and what emotional distance those 'issues' excuse. Then switch seats and coach them to search for the cause of conflict inside themselves.",
            "A minimalist apartment in two halves: the left shows a glowing checklist of an ideal partner, the right replays a high-pitched sneeze on a loop while the 'issues' list grows to justify distance.",
            [
                "Avoidants have a set image in their minds of what their ideal relationship should be",
                "Avoidants have trouble making concessions depending on their spouse's personality and requirements",
                "The set image of the ideal relationship exists because avoidants have trouble making concessions based on their spouse's needs",
                "Avoidants should try to think about their spouse in a more favorable way in order to make their relationships function",
                "Avoidants must think about their spouse in a good light rather than as the cause of their problems",
                "When a relationship has difficulties, avoidants are quick to blame others, putting a lot of strain on their spouse",
                "The blame-shifting may be prevented if avoidants are ready to put in the effort",
                "Searching for the cause of conflict inside yourself is the easiest approach",
                "Taking special effort to view the issue through your partner's eyes helps avoidants improve their relationships",
                "In the search for 'the one', little 'issues' like slurping coffee or high-pitched sneezes serve as excuses for emotional distance",
            ],
        ),
        "audit": (
            "Audit: The Blame-Shift Field Log",
            "Keep a field log of every avoidant behavior in a relationship: preserving autonomy, blaming the spouse during difficulties, and failing to recognize the partner's emotions. For each entry record the strain it puts on the spouse and whether the avoidant put in the effort to think of the partner in a good light.",
            "An office lounge overlaid with a logbook; each blame and distance cue is tagged with a strain meter while a mirror icon offers a view through the partner's eyes.",
            [
                "Avoidants are quick to blame others when a relationship has difficulties",
                "Blaming others puts a lot of strain on the avoidant's spouse",
                "Avoidants can prevent the strain of blame-shifting if they are ready to put in the effort",
                "Avoidants must think about their spouse in a good light rather than as the cause of their problems",
                "Searching for the cause of conflict inside yourself is the easiest approach to relationship improvement",
                "Viewing the issue through your partner's eyes takes special effort",
                "Avoidants avoid becoming too close to others for fear of losing their independence",
                "Avoidants have a hard time recognizing others' emotions, making it difficult to sustain connections",
                "Avoidants strive to preserve their autonomy when in a relationship",
                "The need for attachment exists in avoidants, but they express it in a different way",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Independence x Blame x Effort Grid",
            "Fill the grid for 10 avoidant patterns: mark each as preserving autonomy, fearing loss of independence, blaming others, or making concessions, then classify whether it strains the spouse or can be prevented with effort. Cite the slurping-coffee detail and the partner's-eyes approach as evidence.",
            "A courtroom wall of cells: each behavior card drops into a row and lights AUTONOMY, BLAME, or EFFORT, while a two-sided mirror at the center shows the conflict from both partners' eyes.",
            [
                "An avoidant individual strives to preserve their autonomy in a relationship",
                "Avoidants avoid closeness for fear of losing their independence",
                "A hard time recognizing others' emotions makes it difficult for avoidants to sustain connections",
                "Avoidants are often on the lookout for 'the one' when dating",
                "A set image of the ideal relationship stems from trouble making concessions based on the spouse's personality and requirements",
                "Little details like the way a partner slurps coffee or sneezes in a high-pitched tone irritate avoidants",
                "Finding little 'issues' gives avoidants an excuse to maintain emotional distance",
                "Avoidants are quick to blame others when a relationship has difficulties, straining their spouse",
                "Putting in the effort to think of the spouse in a good light can prevent avoidants' blame-shifting",
                "Searching for the cause of conflict inside yourself and viewing the issue through your partner's eyes is the easiest approach",
            ],
        ),
        "boss": (
            "Boss Battle: The Partner's-Eyes Challenge",
            "Take the final challenge: an avoidant's relationship is failing, and you must reorder their habits - stop the little 'issues' that excuse distance, end the blame-shifting that strains the spouse, and put in the effort to think of the partner in a good light. Finish by searching for the cause of conflict inside yourself through your partner's eyes.",
            "A collapsing bridge between two cliffs, each plank labeled with an avoidant habit; the bridge rebuilds as you replace BLAME with EFFORT and LITTLE ISSUES with YOUR PARTNER'S EYES.",
            [
                "An avoidant attachment style means striving to preserve autonomy in a relationship",
                "People with an avoidant style avoid becoming too close for fear of losing their independence",
                "The desire for attachment exists in avoidants too, but they express it in a different way",
                "Avoidants are often on the lookout for 'the one' when dating",
                "Little 'issues' like slurping coffee or high-pitched sneezes serve as excuses to maintain emotional distance",
                "To make their relationships function, avoidants should think about their spouse in a more favorable way",
                "Avoidants are quick to blame others when a relationship has difficulties, putting a lot of strain on their spouse",
                "Blame-shifting can be prevented if avoidants are ready to put in the effort",
                "Searching for the cause of conflict inside yourself is the easiest approach",
                "Taking special effort to view the issue through your partner's eyes is the way to see your spouse in a good light",
                "A hard time recognizing others' emotions makes it difficult for avoidants to sustain connections",
            ],
        ),
    },
    {
        "num": 5,
        "title": "Secure Attachment - The Go-With-the-Flow Advantage",
        "pages": "20-22",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Secure Base Sweep",
            "Scan 12 couple interactions and spot the secure signal: ease with proximity, unconcern about reliance, reading between the lines, or picking up signals without getting upset. Name the attachment style and decide whether the partner comprehends the other's needs without being too concerned or disinterested.",
            "A cozy living room with a sofa; each scenario freezes with a secure cue ringed in green - a relaxed hug, an understanding nod - while a relationship meter stays calm.",
            [
                "A person with a secure attachment style is at ease with proximity and intimacy",
                "Secure individuals are unconcerned with excessive or insufficient reliance, unlike other attachment types",
                "Secure people can read between the lines and comprehend their partner's needs",
                "Secure people comprehend their partner's needs without being too concerned as an anxious person might",
                "Secure people comprehend their partner's needs without being disinterested like an avoidant person",
                "The greatest predictor of a good relationship is being with a safe partner",
                "Relationships between two secure individuals have few difficulties",
                "Even one secure partner may enhance the quality of a relationship",
                "Most of us want the ideal mate who gives us room when we're feeling constrained and cuddles up next to us when we're lonely",
                "People with a secure attachment style are genuine individuals, not something out of a storybook",
            ],
        ),
        "dialogue": (
            "Dialogue: The Interrupted Deskwork Replay",
            "Replay the interrupted-work scenario from both seats: the person with a mountain of work who scolds the spouse for interfering, and the secure spouse who reads the mood and cheers, 'You can do it!'. Take each side and decide how the conversation stays warm instead of escalating.",
            "A home office in two panels: the left shows a desk buried under papers with a bubble of sharp words, the right shows the spouse picking up the signal and a speech bubble reading 'You can do it!'.",
            [
                "In the desk scenario, the spouse enters the room as you grow more concerned about a mountain of work",
                "Instead of telling him about your issue, you scold your spouse for interfering with your job",
                "Your spouse will not be upset by your harsh remarks since he has a secure attachment style",
                "A secure partner knows that you are just not in the mood to speak",
                "A secure partner picks up on your signals and quickly finds methods to help you",
                "A secure partner might cheer you on and say, 'You can do it!'",
                "Secure individuals have the ability to read between the lines and comprehend their partner's needs",
                "A person with a secure attachment style is at ease with proximity and intimacy",
                "Even one secure partner may enhance the quality of a relationship",
                "A secure partner can alleviate issues caused by a different attachment type",
            ],
        ),
        "audit": (
            "Audit: The Partner Signals Field Log",
            "Spend an afternoon logging how partners handle reliance and reading: note who is at ease with proximity and intimacy, who reads between the lines, and who remains unconcerned by excessive or insufficient reliance. For each entry record whether the relationship has few difficulties and whether a single secure partner enhances it.",
            "A park with couples overlaid with observation tags; each secure behavior is stamped EASE, READING, or UNCONCERNED while a relationship-quality meter holds high.",
            [
                "Secure individuals are at ease with proximity and intimacy",
                "Secure individuals are unconcerned with excessive or insufficient reliance",
                "Secure people read between the lines to comprehend their partner's needs",
                "Being with a safe partner is the greatest predictor of a good relationship",
                "Relationships between two secure individuals have few difficulties",
                "One secure partner can alleviate issues caused by a different attachment type",
                "A secure partner who is scolded for interfering will not be upset because they know you are just not in the mood to speak",
                "A secure partner picks up on your signals and finds methods to help you",
                "Most of us want an ideal mate who gives us room when we're feeling constrained and cuddles up next to us when we're lonely",
                "Secure individuals are genuine people, not storybook fantasies",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Secure x Anxious x Avoidant Grid",
            "Fill the grid for 10 partner responses: classify each as anxious (too concerned), avoidant (disinterested), or secure (at ease with proximity and intimacy), then predict whether the relationship has few difficulties. Mark which combinations gain the most from even one secure partner.",
            "A tri-colored grid wall: response cards drop into ANXIOUS, AVOIDANT, or SECURE columns and light green, yellow, or red while a safe-partner predictor needle swings.",
            [
                "A secure attachment style means being at ease with proximity and intimacy",
                "Other attachment types struggle with excessive or insufficient reliance, while secure individuals are unconcerned",
                "An anxious person is too concerned about the partner's needs, while an avoidant person is disinterested",
                "Secure people comprehend their partner's needs without being too concerned or disinterested",
                "The greatest predictor of a good relationship is being with a safe partner",
                "Relationships between two secure individuals have few difficulties",
                "One secure partner can enhance the quality of a relationship by alleviating issues caused by a different attachment type",
                "The ideal mate gives us room when we're feeling constrained and cuddles up next to us when we're lonely",
                "Secure partners are genuine individuals, not characters from a storybook",
                "Secure individuals read between the lines to comprehend their partner's needs",
            ],
        ),
        "boss": (
            "Boss Battle: The Good Relationship Predictor",
            "Run the final trial: the greatest predictor of a good relationship is being with a safe partner, and you must judge each candidate on ease with intimacy, reading between the lines, and staying unconcerned about reliance. Pair two secure partners and then add one secure partner to a struggling couple to see the quality rise.",
            "A hall of scales weighing pairs: two secure partners balance perfectly while a single secure partner tips the scale of a struggling couple upward to few difficulties.",
            [
                "The greatest predictor of a good relationship is being with a safe partner",
                "A person with a secure attachment style is at ease with proximity and intimacy",
                "Secure individuals are unconcerned with excessive or insufficient reliance, unlike other attachment types",
                "Secure people read between the lines and comprehend their partner's needs without being too concerned or disinterested",
                "Relationships between two secure individuals have few difficulties",
                "Even one secure partner may enhance the quality of a relationship by alleviating issues caused by a different attachment type",
                "The ideal mate gives you room when you're feeling constrained and cuddles up next to you when you're lonely",
                "In the desk scenario, the secure spouse is not upset by harsh remarks because he knows you are just not in the mood to speak",
                "The secure spouse picks up on your signals and quickly finds methods to help you, such as cheering you on and saying, 'You can do it!'",
                "The final part of the book teaches how to use everything learned so far to build a good relationship",
            ],
        ),
    },
]
