# -*- coding: utf-8 -*-
"""Phase 2 chapter data for Behave: The Biology of Humans at Our Best and Worst by Robert M. Sapolsky, chapters 7-12. Behavioral Biology | Multilevel Analysis."""

D = "Behavioral Biology | Multilevel Analysis"

CHAPTERS = [
    {
        "num": 7,
        "title": "Chapter 7: Back to the Crib, Back to the Womb",
        "pages": "184-233",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Childhood Scaffolding",
            "Identify childhood environmental cues, from parenting styles to brain-stage timetables, that scaffold the adult brain and behavior.",
            "A split view of a nursery with a developing brain lighting up through synaptogenesis, then the same brain myelinating through a quarter century of schooling into the twenties.",
            [
                "Most synaptogenesis occurs prenatally, before birth",
                "Myelination continues well into the twenties",
                "Childhood events leave persistent influences mediated by biology",
                "Development unfolds in stereotyped universal sequences",
                "Parental coldness is harder to link biologically to adult outcomes than malnutrition is",
                "Parenting cultures use metaphors of flowering, blooming, growing, and blossoming",
                "Individuated justifying requests are a hallmark of one parenting style",
                "The marshmallow test assessed preschool impulse control",
                "Kids who delayed gratification had better frontal function decades later",
                "Kids who delayed gratification had lower BMI forty years later",
                "Impulse-control failure predicts adult violent crime",
                "Cold, inexpressive parenting predicts adults who feel unlovable",
            ],
        ),
        "dialogue": (
            "Dialogue: Marshmallow Fates",
            "Run a scenario dialogue tracing how a preschooler's marshmallow choice forecasts frontal function, BMI, and criminality across the decades.",
            "Two facing chairs: a preschooler eyeing a marshmallow and a single delayed-gratification marshmallow on a plate, with a time-lapse of the same child aging to forty.",
            [
                "Preschoolers who held out for two marshmallows did better decades later",
                "Some kids announce they will hold out and then instantly eat the marshmallow",
                "The instantly-eating variant is a predictor of adult violent crime",
                "Delaying gratification predicted better frontal function decades later",
                "Delaying gratification predicted lower BMI forty years later",
                "The marshmallow test is a famous study of childhood impulse control",
                "Childhood self-control signals reach far into adulthood",
                "Frontal function mediates delayed gratification",
                "The choice between one marshmallow now and two later frames the classic paradigm",
                "Parental environments shape how kids weigh immediate versus delayed rewards",
            ],
        ),
        "audit": (
            "Audit: Parenting Legacy",
            "Audit the evidence linking parenting styles and parental warmth to later adult functioning, separating solid findings from uncertain biological links.",
            "A courtroom-style evidence board: on one side photographs of cold, inexpressive parents; on the other, graphs of adult unlovability, with a red line marked biological link uncertain.",
            [
                "Cold, inexpressive parents tend to raise adults who feel unlovable",
                "The biological link between parental coldness and later outcomes is uncertain",
                "Malnutrition is easier to link biologically to cognition than parental coldness is",
                "Parenting styles shape children's sense of being lovable",
                "Authoritative parenting contrasts with permissive parenting",
                "Individuated justifying requests mark a more engaged style of parenting",
                "Culture shapes the metaphors parents use for raising children",
                "Persistent influences of childhood are mediated by biology",
                "Parenting styles differ in how they explain rules to children",
                "Adult feelings of unlovability track early parental expressiveness",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Parenting Styles",
            "Sort parenting scenarios into styles, discriminating how different approaches shape developmental outcomes.",
            "A matrix grid with columns for authoritative and permissive styles, rows of childhood scenarios, and a pointer highlighting the individuated justifying request.",
            [
                "Authoritative parenting is one recognized style",
                "Permissive parenting is one recognized style",
                "Individuated justifying requests characterize engaged parenting",
                "Parenting styles differ in the structure they provide",
                "Culture frames which parenting metaphors are used",
                "Parental expressiveness ranges from warm to cold and inexpressive",
                "Childhood development follows stereotyped universal sequences",
                "Stage-like development appears in universal sequences",
                "Brain development proceeds on a timetable from prenatal synaptogenesis to myelination in the twenties",
                "Children's behavior in early tests predicts adult traits",
            ],
        ),
        "boss": (
            "Boss Battle: The Unlovable Adult",
            "Defeat the claim that childhood is destiny by mapping the biological and behavioral pathways from early experience to the adult who feels unlovable.",
            "A boss arena where a cold, inexpressive parental figure towers over a timeline of the child's brain through synaptogenesis, myelination, and adult tests of impulse control.",
            [
                "Adults who feel unlovable often had cold, inexpressive parents",
                "The pathway from parental coldness to adult feeling is biologically uncertain",
                "Malnutrition's cognitive effects are easier to demonstrate biologically",
                "Childhood events have persistent influences mediated by biology",
                "Early environment interacts with brain development timetables",
                "Impulse-control failure in childhood predicts adult violent crime",
                "The marshmallow test foreshadows adult frontal function",
                "The marshmallow test foreshadows adult BMI",
                "Parenting style shapes how children justify and accept rules",
                "Culture supplies the metaphors of child-rearing",
                "Development is stage-like and universal in sequence",
            ],
        ),
    },
    {
        "num": 8,
        "title": "Chapter 8: Back to When You Were Just a Fertilized Egg",
        "pages": "233-277",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Gene Environment Crossfire",
            "Spot the genetic cues, from single-gene disorders to the 5HTT variant, that only matter in particular environments.",
            "A double helix under a rain of environmental cues; a focus point highlights the 5HTT promoter region and a flashback to childhood trauma.",
            [
                "The human genome has about twenty thousand genes",
                "Genes code for neurotransmitters, hormones, and their receptors",
                "A single gene can matter enormously with a particular environment",
                "Gene-environment interaction obeys an it-depends rule",
                "The 5HTT serotonin transporter gene comes in different variants",
                "A 5HTT variant increases depression risk only with childhood trauma",
                "PKU results from a single gene mutation",
                "A phenylalanine-free diet prevents PKU brain damage",
                "Pseudoscientific genetics was used to justify prejudice",
                "Genetics pseudoscience fueled racism, sexism, and discrimination",
                "Eugenics drew on misused genetics",
                "Genes are relevant to every aspect of behavior",
            ],
        ),
        "dialogue": (
            "Dialogue: PKU at the Dinner Table",
            "Walk through the PKU example in dialogue to show how one mutated gene produces different fates under different diets.",
            "A family dinner table with a phenylalanine-free dish, while a gene chart on the wall shows the single mutation and the branching dietary outcomes.",
            [
                "PKU is caused by a single gene mutation",
                "A phenylalanine-free diet prevents PKU-related brain damage",
                "The same PKU gene yields different outcomes under different diets",
                "Gene effects depend on environment",
                "Genes code for proteins including enzymes",
                "Single-gene disorders show genes can be fateful",
                "The it-depends rule governs gene-environment interactions",
                "Diet can override a genetic mutation's effects",
                "Untreated PKU damages the brain",
                "The gene for PKU interacts with what is on the plate",
            ],
        ),
        "audit": (
            "Audit: Pseudoscience of Genes",
            "Audit the history where misused genetics justified isms, prejudice, and eugenics, and separate the pseudoscience from real gene-environment findings.",
            "A ledger of past abuses: race science, forced sterilization, and discrimination, each stamped pseudoscience, beside a clean column for the 5HTT and PKU findings.",
            [
                "Pseudoscientific genetics has been used to justify racism",
                "Pseudoscientific genetics has been used to justify sexism",
                "Pseudoscientific genetics has been used to justify discrimination",
                "Eugenics was built on misused genetics",
                "Prejudice has been rationalized with bad genetics",
                "Real gene-environment research shows it depends",
                "The 5HTT variant matters only with childhood trauma",
                "PKU shows a single gene interacting with diet",
                "Genes do not work in isolation from environment",
                "Science misuse has real social consequences",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Gene Variants",
            "Sort gene-environment scenarios into the right cells, discriminating when a variant matters and when it does not.",
            "A matrix with rows of gene variants and columns of environments, a cell glowing where 5HTT meets childhood trauma, another where PKU meets a normal diet.",
            [
                "The 5HTT serotonin transporter gene has short and long variants",
                "The risky 5HTT variant increases depression risk only with childhood trauma",
                "Without trauma the 5HTT variant predicts little",
                "PKU brain damage is prevented by a phenylalanine-free diet",
                "PKU damage proceeds on a normal diet",
                "About twenty thousand genes make up the human genome",
                "Genes code for neurotransmitters, hormones, and receptors",
                "Gene-environment interactions are the rule",
                "The it-depends rule applies to gene effects",
                "Genes are relevant to all behavior",
            ],
        ),
        "boss": (
            "Boss Battle: The Gene Autocrat",
            "Defeat the gene-autocrat claim of genetic determinism using PKU, the 5HTT variant, and the it-depends rule.",
            "A tyrant throne built of DNA towers, confronted by two shields: a phenylalanine-free dinner and a trauma-free childhood, splitting the throne.",
            [
                "Genes alone do not determine outcomes",
                "The it-depends rule governs gene-environment interaction",
                "PKU outcome depends on diet",
                "5HTT depression risk depends on childhood trauma",
                "The human genome contains about twenty thousand genes",
                "Genes code for neurotransmitters, hormones, and receptors",
                "Pseudoscientific genetics has justified racism, sexism, and discrimination",
                "Eugenics misused genetics",
                "Gene effects are probabilistic, not fateful",
                "Environment shapes whether genes matter",
            ],
        ),
    },
    {
        "num": 9,
        "title": "Chapter 9: Centuries to Millennia Before",
        "pages": "277-339",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Millennial Echoes",
            "Spot the century-to-millennia cues, from plow adoption to year-1500 population density, echoing into present-day behavior.",
            "A telescope panning from cave paintings to a plow furrow to a 1500 population map, ending in a modern city with an authoritarian skyline.",
            [
                "Cave paintings about forty thousand years old show hunting",
                "Cave paintings show hardly any unambiguous interhuman violence",
                "Hominins spent most of their history as hunter-gatherers",
                "About ninety-five to ninety-nine percent of hominin history was hunter-gatherer",
                "Pastoralists and agriculturalists span only the last ten to fourteen thousand years",
                "Population density in the year 1500 predicts authoritarianism in the year 2000",
                "Hoe-based versus plow-based farming predicts gender equality",
                "Thirty-three countries show the population-density prediction",
                "Rice domestication about ten thousand years ago required massive communal work",
                "Wheat farming involves individual rather than collective farming",
                "A 2014 Science paper strengthened the rice and collectivism connection",
                "Deep history echoes in contemporary behavior",
            ],
        ),
        "dialogue": (
            "Dialogue: Parking Tickets and Proxies",
            "Run a dialogue using the UN parking-ticket study to show how present-day behavior can betray centuries-old cultural norms.",
            "Two diplomats in front of the UN, one with a stack of unpaid parking tickets stamped with their home country's corruption score.",
            [
                "UN diplomats from corrupt countries rack up unpaid parking tickets in Manhattan",
                "Parking tickets are a proxy for cultural corruption norms",
                "Diplomats enjoy immunity from prosecution",
                "The parking-ticket study links home-country corruption to present behavior",
                "Culture's effects can outlive generations",
                "Cultural norms persist across centuries",
                "Present-day behavior can be traced to historical culture",
                "Corruption norms differ by country",
                "Behavior in Manhattan reveals cultural origin",
                "Culture leaves long-lasting residues",
            ],
        ),
        "audit": (
            "Audit: Gender Gap Ledger",
            "Audit the evidence that culture rather than biology explains the math gender gap, from gender-equal countries to the hoe-versus-plow legacy.",
            "A ledger comparing math scores across countries, with Iceland's girls ahead, and a split image of a hoe and a plow at the top.",
            [
                "Gender-equal countries have a smaller math gender gap",
                "In Iceland girls outperform boys in math",
                "Gender equality shrinks the math gender gap",
                "The hoe-versus-plow adoption pattern predicts gender equality",
                "Historical farming tools echo in modern gender outcomes",
                "Culture shapes the math gender gap",
                "Math gender gaps differ across countries",
                "Societies with more equality show smaller gaps",
                "In Scandinavian countries the math discrepancy becomes statistically insignificant",
                "Culture, not just biology, drives the gap",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Inequality Signals",
            "Sort economic and historical signals into the matrix, discriminating when inequality suppresses helping and generosity.",
            "A matrix of countries sorted by income inequality, with cells glowing red for bullying and antisocial punishment where inequality is high.",
            [
                "Income inequality leads to less helping",
                "Income inequality leads to less generosity",
                "Income inequality leads to less cooperation",
                "Income inequality leads to more bullying",
                "Income inequality leads to more antisocial punishment",
                "Inequality suppresses prosocial behavior",
                "Inequality fosters antisocial behavior",
                "Generosity declines with inequality",
                "Cooperation declines with inequality",
                "Bullying rises with inequality",
            ],
        ),
        "boss": (
            "Boss Battle: The Deep Past Colossus",
            "Defeat the colossus of deep history by reconstructing hunter-gatherer life and showing how millennia shape today's behavior.",
            "A towering colossus built from cave paintings and plows, faced by a hunter-gatherer band of nomads whose shadows fall on a modern city.",
            [
                "Hominins spent ninety-five to ninety-nine percent of their history as hunter-gatherers",
                "Hunter-gatherers lived in small nomadic bands",
                "Cave paintings show hunting scenes",
                "Cave paintings show hardly any unambiguous interhuman violence",
                "Agriculture spans only the last ten to fourteen thousand years",
                "Pastoralism spans only the last ten to fourteen thousand years",
                "Population density in 1500 predicts authoritarianism in 2000",
                "Hoe versus plow adoption predicts gender equality",
                "UN diplomats' parking tickets track home-country corruption",
                "Deep history echoes in present-day behavior",
            ],
        ),
    },
    {
        "num": 10,
        "title": "Chapter 10: The Evolution of Behavior",
        "pages": "339-397",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Selection Signals",
            "Spot the selection cues in traits from salmon to prostate glands and bacteria that reveal what natural selection really does.",
            "A scanning montage: a spawning salmon, a prostate diagram, a petri dish of bacteria, each with a tag showing what selection did and did not favor.",
            [
                "Natural selection acts on present traits",
                "Selection does not plan for the future",
                "Antagonistic pleiotropy means one gene helps early life but harms later life",
                "A prostate's high metabolic rate boosts sperm motility",
                "The same prostate metabolism raises prostate cancer risk later",
                "Salmon exemplify tradeoffs between reproduction and lifespan",
                "Evolution does not select for greater complexity",
                "Bacteria show evolution does not require complexity",
                "Living species are not better adapted than extinct species",
                "Traits are selected for present function, not future preadaptation",
            ],
        ),
        "dialogue": (
            "Dialogue: The Hamlet Pair",
            "Run a dialogue between black hamlet fish to show how Tit for Tat enforces cooperation between a stable pair.",
            "Two black hamlet fish face each other in a coral arena, each holding an egg-and-sperm offer card, alternating turns.",
            [
                "Black hamlet fish form stable pair bonds",
                "Black hamlet pairs alternate spawning roles",
                "Tit for Tat enforces cooperation in black hamlet pairs",
                "Cooperation can be maintained by reciprocity",
                "The black hamlet example shows reciprocity in the wild",
                "Alternating roles sustain cooperation",
                "Reciprocity requires repeat interactions",
                "Tit for Tat punishes defection",
                "Stable pairs are needed for reciprocity",
                "Reciprocity balances giving and taking between partners",
            ],
        ),
        "audit": (
            "Audit: Just a Theory",
            "Audit the evolution is just a theory canard against the evidence from changing selective environments.",
            "A courtroom where a witness points at a wall of evidence: changing selective environments, bacteria, and the fossil record.",
            [
                "The just-a-theory canard misunderstands scientific theory",
                "Evidence for evolution includes changing selective environments",
                "Evolution is supported by multiple lines of evidence",
                "Evolution does not select for complexity",
                "Bacteria persist without complexity",
                "Living species are not better adapted than extinct ones",
                "Traits are selected for present function",
                "Antagonistic pleiotropy shows selection's tradeoffs",
                "Selection acts on existing variation",
                "The fossil record documents change",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Game Strategies",
            "Sort game theory strategies into the matrix, discriminating how Tit for Tat, Forgiving Tit for Tat, and Always Cooperate fare in repeated play.",
            "A tournament bracket matrix of strategy cells, with Tit for Tat holding the winning lane and Forgiving Tit for Tat recovering from it.",
            [
                "Tit for Tat reciprocates cooperation and punishes defection",
                "Forgiving Tit for Tat forgives occasional defections",
                "Always Cooperate never punishes defection",
                "Tit for Tat wins repeated prisoner's dilemma tournaments",
                "Forgiveness rescues cooperation from cascading grudges",
                "Cooperation can emerge among purely self-interested players",
                "Iterated games allow reciprocity",
                "Game theory models repeated interactions",
                "Strategies cycle in success over rounds",
                "Reciprocity stabilizes cooperation",
            ],
        ),
        "boss": (
            "Boss Battle: The Gradualist Leviathan",
            "Defeat the gradualist leviathan using Gould and Eldredge's punctuated equilibrium and the record of bursts and stasis.",
            "A giant smooth linear curve ramps across an arena, and the player shatters it into a staircase of bursts separated by long plateaus of stasis.",
            [
                "Gould and Eldredge proposed punctuated equilibrium in 1972",
                "Punctuated equilibrium holds that evolution proceeds in bursts",
                "Evolution can be stasis punctuated by rapid change",
                "Evolution is not always gradual",
                "The fossil record shows long stability and sudden change",
                "Punctuated equilibrium was a major revision of gradualism",
                "Evolution's tempo varies",
                "Selection acts on present traits, not future ones",
                "Antagonistic pleiotropy illustrates evolutionary tradeoffs",
                "Salmon and prostate metabolism show fitness tradeoffs",
            ],
        ),
    },
    {
        "num": 11,
        "title": "Chapter 11: Us Versus Them",
        "pages": "397-435",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Fifty Millisecond Faces",
            "Spot the rapid neural cues that fire within fifty milliseconds of seeing an out-group face.",
            "A face flashes on a screen for fifty milliseconds while a brain scan lights the amygdala and dims the fusiform face area.",
            [
                "Fifty milliseconds of exposure to an other-race face activates the amygdala",
                "Other-race faces activate the amygdala",
                "Same-race faces activate the fusiform face area more strongly",
                "The amygdala responds to out-group faces",
                "Fifty milliseconds is a subliminal exposure",
                "The brain sorts faces into groups at similar speeds",
                "Gender grouping engages the brain at a similar speed",
                "Social status grouping engages the brain at a similar speed",
                "Rapid categorization precedes conscious thought",
                "The fusiform face area processes same-race faces more",
            ],
        ),
        "dialogue": (
            "Dialogue: White in Oregon",
            "Run a dialogue where one person is classified white in Oregon but not in Florida, exposing race as a cultural construct.",
            "Two state maps with the same silhouette: white in Oregon's ledger, not white in Florida's ledger, above a courtroom desk.",
            [
                "Race is a cultural construct",
                "One person can be classified white in Oregon but not in Florida",
                "Race classifications differ by place",
                "Racial categories vary across cultures",
                "The same individual receives different racial labels",
                "Race is not a fixed biological category",
                "Racial classification is socially determined",
                "African Americans descend from a few West African tribes",
                "Those tribes represent one to two percent of Africa's tribal variability",
                "Genetic variability is greater within Africa than implied by race",
            ],
        ),
        "audit": (
            "Audit: Reclassification Shuffle",
            "Audit the studies showing that gender, age, and occupation can trump race in the brain's categorization.",
            "An evidence board of study cards: Navarrete's fear-extinction, the age study, and the politician-versus-athlete study, each marked trumps race.",
            [
                "Gender trumps race in extinguishing conditioned fear",
                "Navarrete's study showed gender trumping race for male faces",
                "Gender trumped race only for male faces",
                "Age trumps race in categorization",
                "Occupation can trump race",
                "White politicians versus black athletes shifted categorization",
                "Priming occupation shoved race aside",
                "Subtle reclassification can shove race aside",
                "Categorization depends on context",
                "The brain groups by gender at similar speed to race",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Categorization Cues",
            "Sort people into the matrix by the cue that wins their categorization, discriminating when race, gender, age, or occupation dominates.",
            "A four-column matrix grid with faces shuffling between columns as context cues change; a white politicians versus black athletes row glows.",
            [
                "Gender can trump race in fear conditioning",
                "Age can trump race",
                "Occupation can trump race",
                "Context determines which category wins",
                "Navarrete found gender trumping race for male faces",
                "The IAT measures implicit associations",
                "The implicit association test reveals automatic race bias",
                "Racial categorization is automatic",
                "The brain sorts faces by gender and status quickly",
                "Fifty milliseconds activates the amygdala for other-race faces",
            ],
        ),
        "boss": (
            "Boss Battle: The Us Versus Them Titan",
            "Defeat the titan of automatic othering by tracing categorization from the amygdala flash to the cultural constructs that can override it.",
            "A titan of silhouettes labeled Us and Them, weakened by each trump card thrown: gender, age, occupation, and reclassification.",
            [
                "The amygdala activates within fifty milliseconds for other-race faces",
                "The fusiform face area responds less to other-race faces",
                "Race is a cultural construct",
                "Gender, age, and occupation can trump race",
                "Navarrete's study showed gender trumping race for male faces",
                "Subtle reclassification can shove race aside",
                "The IAT reveals implicit race associations",
                "African Americans descend from a few West African tribes",
                "Those tribes represent one to two percent of Africa's tribal variability",
                "Us-versus-them categorization is fast and automatic",
                "Categorization can be retrained and overridden",
            ],
        ),
    },
    {
        "num": 12,
        "title": "Chapter 12: Hierarchy, Obedience, and Resistance",
        "pages": "435-488",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Status Uniforms",
            "Spot the status cues that shift how the brain sorts racially ambiguous faces.",
            "A racially ambiguous face changes attire from janitor's coveralls to a CEO suit, and the categorization label flips from black to white.",
            [
                "Racially ambiguous faces dressed low-status are categorized as black",
                "Racially ambiguous faces dressed high-status are categorized as white",
                "Status cues shift racial categorization",
                "Hierarchy formalizes unequal access to limited resources",
                "A hierarchy is a ranking system",
                "Hierarchy interacts with us-versus-them thinking",
                "Status attire changes classification",
                "Clothing signals social rank",
                "Categorization responds to status signals",
                "Ranking systems allocate resources unequally",
            ],
        ),
        "dialogue": (
            "Dialogue: Choosing the Alpha",
            "Run a dialogue exploring how, unlike most species, humans sometimes choose their alphas and ask leaders to serve the common good.",
            "A town square where a crowd casts ballots toward a candidate podium, while a wolf pack alpha in the background is unchosen.",
            [
                "Unlike most species, humans sometimes choose their alphas",
                "Human leaders can be selected by the group",
                "Leaders are expected to serve the common good",
                "Political ideologies offer differing visions of the common good",
                "Hierarchies formalize unequal access to limited resources",
                "Humans can depose unsatisfactory leaders",
                "Dominance in most species is not elected",
                "Leadership and dominance are not the same",
                "Ideology differs on how the common good is reached",
                "Chosen leadership constrains the alpha",
            ],
        ),
        "audit": (
            "Audit: Obedience Ledger",
            "Audit obedience to authority and to the idea of Authority, weighing how hierarchies and ideologies license compliance.",
            "A ledger with two columns: obedience to persons in authority and obedience to the abstract idea of Authority, with Milgram-style settings in the margin.",
            [
                "People obey authorities and the idea of Authority",
                "Obedience can be directed at the abstract idea of Authority",
                "Hierarchies demand obedience from subordinates",
                "Ranking systems grant authority over resources",
                "Authority figures command compliance",
                "The abstract idea of Authority licenses obedience",
                "Us-versus-them thinking interacts with hierarchy",
                "People differ in their readiness to obey",
                "Obedience shapes resistance and rebellion",
                "Authority is a pillar of moral reasoning for some",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Moral Foundations",
            "Sort moral judgments into Haidt's six foundations, discriminating the liberal and conservative emphases.",
            "A six-cell matrix grid, three cells glowing for liberals and three for conservatives, with sample judgments sliding into cells.",
            [
                "Haidt proposes six moral foundations",
                "The care-versus-harm foundation underlies kindness",
                "The fairness-versus-cheating foundation underlies reciprocity",
                "The liberty-versus-oppression foundation underlies freedom",
                "The loyalty-versus-betrayal foundation underlies group allegiance",
                "The authority-versus-subversion foundation underlies respect for hierarchy",
                "The sanctity-versus-degradation foundation underlies purity",
                "Liberals emphasize care, fairness, and liberty",
                "Conservatives emphasize loyalty, authority, and sanctity",
                "Moral intuitions differ across the political spectrum",
            ],
        ),
        "boss": (
            "Boss Battle: The Hierarchy Sovereign",
            "Defeat the hierarchy sovereign by combining Kohlberg's stages, Haidt's foundations, and the science of chosen leadership.",
            "A sovereign on a resource throne besieged by a six-colored moral-foundations shield wall and a ballot box.",
            [
                "A hierarchy formalizes unequal access to limited resources",
                "Humans sometimes choose their alphas",
                "Leaders are expected to serve the common good",
                "Kohlberg described stages of moral development",
                "Haidt proposes six moral foundations",
                "Liberals emphasize care, fairness, and liberty",
                "Conservatives emphasize loyalty, authority, and sanctity",
                "Obedience targets persons and the idea of Authority",
                "Racially ambiguous faces are categorized by status attire",
                "Us-versus-them and hierarchy interact",
            ],
        ),
    },
]
