# -*- coding: utf-8 -*-
"""Phase 2 chapter data for Truth & Lies, chapters 19-24."""

FF = "Body Language | Friendship & Family | Social Dynamics"

CHAPTERS = [
    {
        "num": 19,
        "title": "Fomo",
        "pages": "99-106",
        "domain": FF,
        "scrub": (
            "Cue Scrubber: Photo Power Pose Decoder",
            "Analyze 10 famous and social-media poses: Napoleon's hand-in-coat, Leonardo's self-portrait, fingermouthing selfies, squinch, teeg, and smize. For each, decode the power or status statement being performed and rate how staged it is.",
            "A gallery wall of portraits and selfies; each frame gets annotated by a pose-decoder: HAND IN COAT = hidden power, FINGERMOUTH = vulnerability display, SQUINCH = confidence performance.",
            [
                "Napoleon's hand-in-coat is a performed power pose",
                "Leonardo's portrait choices are self-presentation, not truth",
                "Fingermouthing selfies perform childlike vulnerability",
                "Squinch (narrowed lids) performs confidence",
                "Teeg (tongue out) performs playfulness",
                "Smize (smiling eyes) performs warmth",
                "Photo body language is staged for the audience",
                "Power poses in photos say what the poser wants believed",
            ],
        ),
        "dialogue": (
            "Dialogue: The Curated Feed",
            "A friend's feed shows a flawless life - mountaintops, artful meals, perfect groups - while their private messages describe burnout and loneliness. Practice the dialogue that separates the performance from the person and opens a door to the real one.",
            "A phone feed scrolls past perfection while a private chat bubble leaks fatigue; you must bridge the gap with a message that sees through the frame.",
            [
                "Curated feeds are highlight reels, not documentaries",
                "Performance peaks often mask private valleys",
                "The gap between feed and life is the real story",
                "Direct, warm messages can reach past the performance",
                "Comparison against curated lives fuels FOMO and envy",
                "Their perfection is their armor, not your measure",
                "Asking 'how are you really?' is a gift",
                "Real connection happens off-platform",
            ],
        ),
        "audit": (
            "Audit: Curated Pose Log",
            "Audit your own last 10 posts or photos: which were staged, filtered, or selected for impression? Note what each performance claimed and what it left out - then compare with how you feel viewing others' performances.",
            "A mirror gallery: your own photos get the same annotation tool you used on celebrities - and the honesty meter dips as you admit the staging.",
            [
                "Everyone curates; awareness is the first step",
                "Selection bias hides the average days",
                "Filters edit reality and expectation",
                "Performing for likes borrows from living",
                "Your feed edits others' view of you - and yours of yourself",
                "Unposted moments are the real life",
                "Auditing your own feed builds empathy for others'",
                "Authenticity is a choice of what to publish",
            ],
        ),
        "matrix": (
            "Matrix: Pose x Platform x Message",
            "Map 10 poses (hand-in-coat, chin in hand, arms crossed, smize, duck face, fingermouthing, peace sign, hand on hip, thumbs-up, candid laugh) across 3 platforms (dating, professional, social) and decode the message each sends in each context.",
            "A 10x3 pose matrix; each cell decodes the message and warns when the pose is a mismatch for the platform.",
            [
                "Hand-in-coat: power in portraits, odd in dating",
                "Smize: warmth anywhere, suspicious in job photos",
                "Duck face: playful on social, wrong for professional",
                "Arms crossed: confident or closed, context decides",
                "Candid laughs read authentic on every platform",
                "Thumbs-up: friendly, cheap on professional pages",
                "Hand on hip: assertive, flirtatious by context",
                "Platform norms set what the pose performs",
            ],
        ),
        "boss": (
            "Boss Battle: The Influencer Dinner",
            "You're at a dinner with an influencer friend who performs the whole evening: planned candid shots, staged laughter, phone-first moments. Decide how to read the performance, whether to name it, and how to connect with the person behind the content without wrecking their brand.",
            "A dinner table where the friend's phone is the third chair; every 'spontaneous' moment is rehearsed. You must find the honest minute between takes.",
            [
                "Their brand is their livelihood - performance is work",
                "Staged spontaneity is the trade's craft",
                "Naming the performance publicly would be a betrayal",
                "Connect between takes: a private, phone-free question",
                "Boundaries: 'let's do one photo, then phones away'",
                "Their FOMO is real - they fear the audience's exit",
                "The person behind the content exists off-camera",
                "Kind honesty costs nothing and builds rare trust",
            ],
        ),
    },
    {
        "num": 20,
        "title": "Control Freak",
        "pages": "107-111",
        "domain": FF,
        "scrub": (
            "Cue Scrubber: Control Style Scanner",
            "Screen 10 controlling behaviors: agenda-setting, seat assignment, schedule control, criticism of your choices, and touch patterns. Classify the control style (overt, covert, caretaker, drama-based) and the fear underneath it - using Hertenstein's touch research to separate care from control.",
            "A control-room dashboard: each behavior logs as OVERT, COVERT, CARETAKER, or DRAMA, with a fear gauge reading beneath - the actual fuel of the control.",
            [
                "Control is fear management - the controller feels powerless",
                "Agenda and seat control are environmental power plays",
                "Touch communicates distinct emotions - Hertenstein's research",
                "Caretaker control is love with a leash",
                "Drama-based control runs on crisis and rescue",
                "Criticism of your choices is boundary erosion",
                "Control escalates when its fear rises",
                "Naming the fear under the control disarms it",
            ],
        ),
        "dialogue": (
            "Dialogue: The Thanksgiving Dictator",
            "A family member assigns seats, schedules the day to the minute, and rejects every contribution. Practice the dialogue that respects their fear without surrendering your choice: offer help inside their frame, take small boundary wins, and pick the one battle worth fighting.",
            "A formal dining table where a seating chart descends like a king's decree; you must negotiate place cards with warmth and spine.",
            [
                "Control freaks respond better to offered help than rebellion",
                "'What can I take off your plate?' enters their frame",
                "Small boundary wins ('I'll sit with cousin this year') accumulate",
                "Pick one battle; let the rest breathe",
                "Their perfectionism is fear of judgment, not malice",
                "Choices within their structure feel safe to them",
                "Escalating every fight exhausts everyone",
                "Empathy plus boundaries is the full toolkit",
            ],
        ),
        "audit": (
            "Audit: Control Pattern Log",
            "Log one relationship's control patterns for two weeks: what is controlled (schedule, money, opinions, space, touch), how (direct, guilt, praise, drama), and your response. Map the controller's fear profile and your boundary success rate.",
            "A ledger with columns CONTROL DOMAIN | METHOD | FEAR | MY RESPONSE; over days the pattern emerges - and the boundary successes tick up.",
            [
                "Control domains reveal the controller's core fear",
                "Guilt and praise are soft control tools",
                "Drama control needs an audience to work",
                "Your compliance rate is data on your boundaries",
                "Fear profiles: abandonment, judgment, chaos, failure",
                "Boundary successes lower their need to control",
                "Consistency defeats control campaigns",
                "The log converts frustration into strategy",
            ],
        ),
        "matrix": (
            "Matrix: Control Type x Relationship x Response",
            "Map 8 control behaviors (schedule control, money control, opinion correction, space invasion, guilt-tripping, drama, surveillance, touch) across 3 relationships (family, friend, partner) and assign the calibrated response for each cell.",
            "A 8x3 matrix where each cell holds a response card: ASSERT, NEGOTIATE, EXIT, or SUPPORT - colored by severity.",
            [
                "Schedule control in family = negotiate; in a partner = watch",
                "Money control anywhere = boundary required",
                "Opinion correction in friends = distance signal",
                "Guilt-tripping in family = pattern; in a partner = toxicity",
                "Drama control needs no audience - stop supplying it",
                "Surveillance is severe in every relationship",
                "Touch control (unwanted) is a violation, always",
                "Severity climbs from assert to exit",
            ],
        ),
        "boss": (
            "Boss Battle: The Rescuer's Web",
            "A friend 'helps' everyone constantly: loans, fixes, crisis calls - then collects loyalty, guilt, and gratitude. Apply the Karpman Drama Triangle: name the rescuer-victim-persecutor loop, refuse the rescued role, and test whether the friendship can survive equality.",
            "A web of strings: the rescuer holds every knot while 'victims' dangle. You must decline the rescue and watch whether the web reweaves without you.",
            [
                "The drama triangle: rescuer, victim, persecutor - roles rotate",
                "Rescue creates dependency, then resentment",
                "Refusing rescue ('I can figure this out') breaks the loop",
                "Guilt after declining is the loop's hook - don't take it",
                "Real help builds capability; rescue builds debt",
                "The rescuer's identity depends on others' crises",
                "Equality test: can the friendship survive your refusal?",
                "Step out of the triangle; stay in the relationship",
            ],
        ),
    },
    {
        "num": 21,
        "title": "Too Close for Comfort",
        "pages": "112-116",
        "domain": FF,
        "scrub": (
            "Cue Scrubber: Touch Zone Scanner",
            "Scan 12 touch interactions and classify them by bond and permission: arm touch, shoulder pat, hair touch, hug types, kiss placement, ownership touches. Apply Suvilehto's topography research - touch depends on the emotional bond - and flag the touches that overstep it.",
            "A human body map glowing with touch zones - dark where strangers may touch (hand), bright where only intimates may (face, waist). Each scene's touch lands on the map for a verdict.",
            [
                "Touch zones track emotional bonds - Suvilehto's topography research",
                "Hands, shoulders, arms are public zones; face and waist are private",
                "Hug duration and pressure encode the bond",
                "Ownership touches (waist, neck) claim territory",
                "Kissing research (Wlodarski and Dunbar): it shapes mate evaluation",
                "Unwelcome touch is a violation regardless of intention",
                "Cultural norms reset every zone",
                "Touch communicates distinct emotions - Hertenstein",
            ],
        ),
        "dialogue": (
            "Dialogue: The Over-Toucher",
            "A coworker touches your shoulder, then your arm, then stands inside your space at the printer. Practice the escalation dialogue: space-claim first (step back, turn), then a light verbal boundary, then a direct one - and decide when HR becomes the answer.",
            "An office printer scene; each approach shrinks the space between you. Your moves - step, turn, speak - rebuild the perimeter visibly.",
            [
                "Claim space first: step back, angle away, create distance",
                "A light boundary: 'I like my space, thanks'",
                "A direct boundary names the touch, not the person",
                "Escalation to HR is for persistent violations",
                "Your comfort is the metric - not their intention",
                "Consistent rebuffing trains the behavior out",
                "Document repeated incidents",
                "Warmth and boundaries can coexist",
            ],
        ),
        "audit": (
            "Audit: Touch Inventory Log",
            "For one week, log every touch you receive and give: type, zone, relationship, and your comfort. Identify the touches that crossed your zone line and the relationships where touch is a healthy bond signal.",
            "A body map journal: comfortable touches glow green, borderline amber, violations red. Patterns reveal who respects the topography.",
            [
                "Touch logs reveal your personal zone line",
                "Comfortable touch correlates with bond depth",
                "Repeated borderline touches are a pattern, not accidents",
                "Context (grief, celebration) shifts zones",
                "Your history sets your zones - both are valid",
                "Giving touch well: ask, observe, stay in their zone",
                "Touch in the workplace is a professional risk",
                "The inventory calibrates both directions",
            ],
        ),
        "matrix": (
            "Matrix: Touch x Bond x Zone Legitimacy",
            "Map 10 touches (handshake, pat, arm squeeze, hug, cheek kiss, hair touch, waist, neck, forehead, hand-hold) against 3 bonds (stranger, friend, intimate) and mark which zone-touch combinations are legitimate, borderline, or violation in each.",
            "A 10x3 grid where legitimacy glows green, amber, or red; the boundaries shift only for the intimate column.",
            [
                "Handshake: universal and safe",
                "Pat: fine for strangers, odd for intimates",
                "Arm squeeze: friendly warmth, acceptable",
                "Hair touch: intimate zone only",
                "Waist and neck: violation unless intimate",
                "Forehead touch: intimate or caretaker",
                "Hand-hold: signals bond status publicly",
                "Bond sets the map; consent is the law",
            ],
        ),
        "boss": (
            "Boss Battle: The Desk Invader",
            "A colleague treats your desk as an annex: leaning over your monitor, touching your things, hovering at your shoulder. Reclaim the territory with escalating moves - spatial, verbal, structural - and keep the working relationship professional.",
            "An office seen from above; your desk is a fortress whose boundary markers keep getting nudged. You must rebuild the moat with posture, words, and furniture.",
            [
                "Desk and body territory are real - claim them",
                "Spatial moves: stand, angle, block the hover",
                "Verbal moves: 'let me get back to you' ends the hover",
                "Structural moves: seating changes, screens, schedules",
                "Touch of your things needs a boundary",
                "Consistency beats confrontation in office wars",
                "Document if the pattern persists",
                "Territory claimed quietly is territory held",
            ],
        ),
    },
    {
        "num": 22,
        "title": "They'll Never Fit in with My Family",
        "pages": "117-122",
        "domain": FF,
        "scrub": (
            "Cue Scrubber: Family Code Decoder",
            "Analyze 12 family interactions for the family's nonverbal code: display rules, seating habits, touch norms, humor style, and conflict rituals - Birdwhistell's kinesics lens. Decode what each family silently expects, and where a partner's neutral behavior gets misread as rejection.",
            "A family dinner captured as a kinesics chart: gesture, posture, and touch lines weave the family's code. A partner's 'wrong' note glows against the pattern.",
            [
                "Families run private nonverbal dialects - Birdwhistell's kinesics",
                "Display rules: what emotions may be shown and to whom",
                "Seating, touch, and humor norms are inherited, not universal",
                "A partner's neutral behavior is read through the family code",
                "Rejection readings can be code mismatches, not rejection",
                "The family's conflict style is on display within minutes",
                "Being 'too quiet' or 'too loud' are code violations",
                "Learning the code is the price of entry",
            ],
        ),
        "dialogue": (
            "Dialogue: The First Family Dinner",
            "Your partner meets your family for the first time: your mother's direct questions, your father's teasing, your sibling's boundary-testing. Coach your partner through the code - and negotiate the family's expectations so the partner isn't judged on a foreign dialect.",
            "A dinner table where each family member throws a code challenge (a tease, a stare, a question); your coaching cards decode each one before it lands.",
            [
                "Prepare your partner for the family dialect in advance",
                "Teasing is often the family's love language",
                "Direct questions may be warmth, not interrogation",
                "Boundary-testing is a ritual, not a verdict",
                "Translating between codes is your job",
                "Protect your partner from genuinely hostile reads",
                "Family acceptance builds through repeated, calm exposure",
                "Agree on a signal to escape the table when needed",
            ],
        ),
        "audit": (
            "Audit: Family Reception Log",
            "Log your partner's first 5 family encounters: who included or excluded, what behaviors were praised or punished, and how the family's code treated your partner. Identify acceptance signals, code mismatches, and any genuine hostility.",
            "A scorecard per encounter: INCLUSION points, CODE MISMATCH flags, HOSTILITY alerts - and a running verdict on the family's true stance.",
            [
                "Acceptance signals: questions, inclusion, invitations, touch",
                "Code mismatch: neutral behaviors read as cold or rude",
                "Praise and punishment reveal the family's rules",
                "Genuine hostility: persistent exclusion, contempt, sabotage",
                "The family tests the partner's fit, then usually warms",
                "Consistent, calm presence erodes initial reserve",
                "Log the pattern; single encounters mislead",
                "You set the pace of exposure",
            ],
        ),
        "matrix": (
            "Matrix: Family Behavior x Meaning x Response",
            "Map 10 family behaviors (silence, teasing, direct questions, touch, seating, gift-giving, gossip, competition, display of wealth, emotional displays) against 3 possible meanings (warmth, testing, hostility) and pick the response that reads correctly in the family's code.",
            "A 10x3 interpretation matrix; each cell teaches the family dialect translation plus the response that the family will read correctly.",
            [
                "Silence can be listening or judgment - code decides",
                "Teasing is often love; contempt is never",
                "Direct questions: warmth in some families, attack in others",
                "Gift-giving may carry status competition",
                "Gossip about you is power, not friendship",
                "Competition at the table is a family sport",
                "Emotional displays: permitted or punished by family rule",
                "Response: learn the dialect before judging the intent",
            ],
        ),
        "boss": (
            "Boss Battle: The Two Families",
            "You and your partner come from opposite family codes: yours hugs and interrupts; theirs sits and waits. At the wedding-planning summit both families misread each other as cold or rude. Broker the cultural merge: name the codes, translate the behaviors, and design rituals both sides can read.",
            "Two banquet tables face each other like embassies; an interpreter's booth waits in the middle. Your translations turn stony faces into nods.",
            [
                "Family codes are inherited culture, not character",
                "Huggers read quiet families as cold - and vice versa",
                "Naming the code ('we show love with food and noise') defuses",
                "Ritual design: seating, toasts, gifts that both sides read",
                "Translation in the moment prevents incidents",
                "Hybrid rituals build a new shared code",
                "The couple becomes the embassy between families",
                "Patience: codes merge over years, not dinners",
            ],
        ),
    },
    {
        "num": 23,
        "title": "House on Fire!",
        "pages": "123-127",
        "domain": FF,
        "scrub": (
            "Cue Scrubber: Emergency vs. Drama Decoder",
            "Screen 10 distress reports and classify each as real emergency, managed crisis, or theatrical drama: urgency in voice, action orientation, problem-solving vs. helplessness, and consistency across retellings. Calibrate your response intensity to the actual fire.",
            "A dispatch console with incoming calls; each voice is waveform-analyzed for REAL FIRE vs. DRAMA FIRE, and response engines adjust dispatch level accordingly.",
            [
                "Real emergencies are action-oriented; drama is attention-oriented",
                "Voice urgency can be genuine or rehearsed",
                "Theatricality and helplessness mark the drama role",
                "Consistency across retellings separates crisis from construction",
                "Calibrating response prevents both over- and under-reaction",
                "The drama pattern: crisis, rescue, calm, repeat",
                "Boy-who-cried-wolf fatigue desensitizes to real alarms",
                "Screen first, then act - seconds matter less than truth",
            ],
        ),
        "dialogue": (
            "Dialogue: The Boy Who Cried Wolf",
            "A colleague declares every deadline a five-alarm fire - then coasts when the smoke clears. Practice the dialogue that keeps their drama from hijacking your day: triage questions ('what's the deadline, what's done, what's blocking?'), scope the actual work, and set the boundary on alarm inflation.",
            "An office fire-alarm panel where one colleague's button is worn out; your triage checklist must decide which alarms get a response team.",
            [
                "Triage questions convert drama into scope",
                "'What's done, what's blocking, what's the deadline?' drains the fog",
                "Respond to the work, not the volume",
                "Calibrated responses train realistic alarm-setting",
                "Missed drama alarms teach: you respond to evidence",
                "Genuine emergencies get full attention - always",
                "The pattern is the colleague's, not yours to absorb",
                "Kind firmness: 'I'll help with the actual block'",
            ],
        ),
        "audit": (
            "Audit: Alarm Calibration Log",
            "Log one week of incoming 'urgent' requests: stated urgency, actual deadline, real consequence, and your response cost. Identify the alarmists and the genuine fires, and recalibrate your average response intensity.",
            "A dispatcher log where each alarm's stated vs. actual severity is charted; your response-cost bars shrink as you calibrate.",
            [
                "Stated urgency and actual severity rarely match",
                "Deadlines and consequences are measurable",
                "Response cost: what you dropped to answer",
                "Alarmists cluster; genuine fires cluster - patterns emerge",
                "Your reputation improves when your alarm is credible",
                "Calibration is a service to the group",
                "Under-responding to real fires is the risk to watch",
                "The log turns 'always urgent' into a dated pattern",
            ],
        ),
        "matrix": (
            "Matrix: Distress Type x Context x Response",
            "Map 8 distress presentations (tears, yelling, silence, rambling, hyperactivity, withdrawal, claims of catastrophe, quiet competence) against 3 contexts (work, home, crisis) and assign the calibrated response for each cell.",
            "A 8x3 matrix where each cell holds a response dial: WARMTH, TRIAGE, SPACE, or ACTION - set by context and presentation.",
            [
                "Tears at work: privacy and support; at home: presence",
                "Yelling in crisis: stay calm; in drama: set limits",
                "Silence in a crisis: check in; in drama: give space",
                "Catastrophe claims always get triage questions",
                "Quiet competence under fire is the real hero - support it",
                "Rambling signals overwhelm; structure helps",
                "Withdrawal during crisis needs a gentle door",
                "Context and presentation set the dial",
            ],
        ),
        "boss": (
            "Boss Battle: The Fire Drill",
            "During a genuinely critical project, your team's chronic drama-king collapses into theatrical helplessness - at the exact moment the real deadline bites. Manage both: fully resource the real fire, calmly scope the drama, and preserve team morale so the real work survives the noise.",
            "An office splits into two screens: a real deadline burns on one, a colleague's performance on the other. You must staff the first, triage the second, and keep the team's eyes on the actual fire.",
            [
                "Real fires get the resources, always",
                "Drama gets triage, not oxygen",
                "Team morale follows the leader's focus",
                "Calm scope questions deflate performance",
                "Crisis reveals who performs and who delivers",
                "Afterward, name the pattern kindly in private",
                "The team remembers how you spent the crisis",
                "Alarm inflation after a real fire is fatal to credibility",
            ],
        ),
    },
    {
        "num": 24,
        "title": "I Am Boring the Pants off Them",
        "pages": "128-131",
        "domain": FF,
        "scrub": (
            "Cue Scrubber: Boredom Signal Scanner",
            "Scan 10 audience moments for the boredom cluster: glazed eyes, minimal blinking, suppressed yawns, posture shifts, phone checks, flat acknowledgments. Distinguish boredom from anxiety, fatigue, and processing - then rate the speaker's rescue options.",
            "An audience rendered as a drowsiness heat-map; glazed eyes and yawn-suppressions glow amber. The speaker's HUD lists rescue plays ranked by cost.",
            [
                "Boredom cluster: glazed eyes, minimal blinking, suppressed yawns",
                "Phone checks are disengagement exits",
                "Polite boredom: nodding without questions, flat 'interesting'",
                "Boredom is a power response - attention withdrawn",
                "Fatigue and anxiety mimic boredom - check context",
                "Attention spans shrink under smartphone training",
                "Zone-out research: minds wander when input fails",
                "The fix is engagement, not volume",
            ],
        ),
        "dialogue": (
            "Dialogue: The Mid-Presentation Rescue",
            "Ten minutes into your presentation, the client's eyes have glazed over. Practice the rescue: acknowledge the room, pivot to their stake ('the part that matters for your department is next'), shorten, and re-engage with a question that makes them talk.",
            "A boardroom where the audience's attention meters sag; your pivot cards - stake, story, question - each lift a different meter.",
            [
                "Naming the drift ('this is heavy - let me make it practical') resets it",
                "Pivoting to their stake re-arms attention",
                "Shorter is a feature, not a failure",
                "A question makes them participants, not spectators",
                "Stories outlast slides",
                "Energy is borrowed from the audience - give some first",
                "Watch the meters: blink rate, posture, phones",
                "Rescue is a skill, not a character trait",
            ],
        ),
        "audit": (
            "Audit: Attention Graveyard Log",
            "Log your own meetings and talks for one week: at which minute does attention dip, what killed it (data dumps, tangents, monotone), what revived it (questions, stories, stakes), and what your repeatable rescue moves are.",
            "A chart plotting attention over time per meeting, with red valleys at the death minutes and green spikes at the revivals; patterns label themselves.",
            [
                "Attention curves are learnable data",
                "The 10-minute wall is real in most rooms",
                "Data dumps are the leading attention killer",
                "Monotone delivery flattens any content",
                "Questions and stories are the reliable revivals",
                "Your best rescue moves are repeatable tools",
                "Shorter agendas respect attention economics",
                "The graveyard log converts meetings into material",
            ],
        ),
        "matrix": (
            "Matrix: Disengagement Cue x Setting x Cause",
            "Map 8 cues (glazed eyes, yawns, phone use, doodling, slumping, flat replies, gaze at exits, silence) against 4 settings (meeting, date, lecture, family dinner) and assign the likely cause (boredom, fatigue, anxiety, overwhelm) plus the fix for each cell.",
            "A 8x4 matrix where each cell rates cause probabilities and shows the fix: ENGAGE, REST, REASSURE, OR SIMPLIFY.",
            [
                "Glazed eyes in a lecture = boredom; in a date = fatigue",
                "Phone use in a meeting = disengagement; in a dinner = habit",
                "Doodling often aids listening - not always boredom",
                "Slumping in a lecture = fatigue; in a date = comfort",
                "Exit-gaze signals a wish to leave",
                "Flat replies in a family dinner = friction, not fatigue",
                "Anxiety and overwhelm mimic boredom",
                "Cause first, then fix",
            ],
        ),
        "boss": (
            "Boss Battle: The Boardroom Snore",
            "The quarterly review is putting the CFO to sleep - literally. Recover the room without humiliation: wake the moment with humor or a question, compress your remaining material to the numbers they need, and win the decision you came for.",
            "A boardroom where the CFO's head dips toward the table; a decision clock ticks. Your moves - jab, pivot, compress - must land the ask before the gavel.",
            [
                "A room's sleep is feedback on the material, not the person",
                "A light, human moment ('should I pause for the nap?') resets it",
                "Compressing to the audience's numbers is respect",
                "Decision asks should come at full attention",
                "Humor saves rooms; apologizing for content bores them",
                "The CFO needs the ask, not the story",
                "End strong: the last thing heard is what's remembered",
                "The win: their decision, your credibility intact",
            ],
        ),
    },
]
