# -*- coding: utf-8 -*-
"""Phase 2 chapter data for Truth & Lies, chapters 31-37."""

WL = "Body Language | Working Life | Power & Deception"

CHAPTERS = [
    {
        "num": 31,
        "title": "Never Going to See Eye to Eye",
        "pages": "162-167",
        "domain": WL,
        "scrub": (
            "Cue Scrubber: Disagreement Decoder",
            "Screen 10 conflict moments and separate the disagreement styles: anger, contempt, stonewalling, and the constructive kind. Apply the smiling-in-pain research (people smile for social reasons during pain) and the relational worldview from Brokenleg's work to read the conflict below the surface.",
            "A debate floor where each participant's conflict style is tagged; smiles are analyzed frame by frame - social smile, pain smile, or contempt - and the true disagreement surfaces.",
            [
                "People smile during pain for social motives - Kunz's research",
                "Smiles can mask, signal, or defuse - read them in context",
                "Anger engages; contempt dismisses - they are different animals",
                "Stonewalling is flooding, not indifference",
                "Disagreement styles are learned family patterns",
                "Brokenleg's lens: relationships are the foundation of behavior",
                "Never seeing eye to eye may be a styles clash, not a values clash",
                "The goal is understanding, not victory",
            ],
        ),
        "dialogue": (
            "Dialogue: The Two Worldviews",
            "A colleague's approach to every problem is opposite to yours, and meetings are becoming battles. Practice the dialogue that separates style from substance: name the pattern ('we're both right about different parts'), map where you agree, and design the split-track solution both can own.",
            "Two river currents merge in a delta; your dialogue must build the channel where both flow without flooding the banks.",
            [
                "Name the style clash before it becomes a war",
                "'We're both right about different parts' reframes the fight",
                "Map agreement zones first - they're bigger than the fight",
                "Split-track solutions let each own their strength",
                "Relational repair precedes technical agreement",
                "Their style is their history, not their verdict on you",
                "Shared goals are the anchor in style storms",
                "Teams that clash in style can still ship together",
            ],
        ),
        "audit": (
            "Audit: Conflict Style Log",
            "Log one week of disagreements: your style, theirs, the trigger, the escalation, and the repair. Identify your default patterns (fight, flee, freeze, fix) and which styles reliably escalate you.",
            "A conflict journal: each entry stamps both parties' styles and plots the escalation curve; your default pattern draws itself across entries.",
            [
                "Conflict styles are habits, not identities",
                "Escalation curves show who raises the stakes",
                "Repair attempts are the health indicator",
                "Your triggers are predictable - learn them",
                "Fight, flee, freeze, fix: know your default",
                "Their style is data, not destiny",
                "Logging breaks the automatic loop",
                "One repair technique that works beats ten theories",
            ],
        ),
        "matrix": (
            "Matrix: Conflict Move x Culture x Response",
            "Map 10 conflict moves (direct attack, silence, teasing, stonewalling, jokes, physical withdrawal, escalation, third-party complaint, direct question, humor) across 3 cultural frames (direct, indirect, high-context) and assign the calibrated response for each cell.",
            "A 10x3 matrix where each cell holds a response: MATCH, TRANSLATE, OR REDIRECT - because the same move means different things in different cultural frames.",
            [
                "Direct attack in direct cultures = honest; in high-context = rupture",
                "Silence in indirect cultures = disagreement, not acceptance",
                "Teasing can be affection or contempt - culture decides",
                "Third-party complaints signal indirect conflict culture",
                "Humor defuses in one culture and insults in another",
                "Stonewalling reads the same in most cultures",
                "Translate before you respond",
                "Calibrated responses build cross-cultural trust",
            ],
        ),
        "boss": (
            "Boss Battle: The Eternal Standoff",
            "You and your partner re-fight the same argument every month: same positions, same escalation, no resolution. Run the breakthrough protocol: map the shared goal underneath, name the repeated loop out loud, change one structural element (time, place, framing), and test a small compromise.",
            "Two chess players replaying the same board; your hand must move a different piece - time, place, or framing - to break the loop before it resets again.",
            [
                "Repeated fights are loops with a hidden shared goal",
                "Naming the loop ('we've had this fight 12 times') disrupts it",
                "The shared goal is usually safety, respect, or fairness",
                "Structural change (time, place, mediator) breaks the groove",
                "Small compromises build the bridge for big ones",
                "Escalation is a bid for connection gone wrong",
                "Repair attempts must land before resolution",
                "One changed element beats ten repeated arguments",
            ],
        ),
    },
    {
        "num": 32,
        "title": "Cold Fish",
        "pages": "168-172",
        "domain": WL,
        "scrub": (
            "Cue Scrubber: Low-Expression Decoder",
            "Screen 10 low-expression encounters and separate the possibilities: autism-style processing, stoic culture, suppressed emotion, psychopathy, or your own misreading. Apply the empathy-imbalance research, the yawn-contagion finding, and Ekman's caution on reading faces without context.",
            "A still-face avatar meets a HUD of possible readings; each theory - PROCESSING, STOIC, SUPPRESSED, DANGEROUS - is tested against the evidence before any verdict sticks.",
            [
                "Low expression is a style, not an absence of feeling",
                "Autism research: cognitive and emotional empathy can diverge",
                "Contagious yawning is reduced in psychopathy - Rundle's finding",
                "Ekman: facial expression is context-dependent, never universal gospel",
                "Emotion AI can track expressions - but not intentions",
                "Stoic cultures read 'cold' to expressive ones",
                "Suppressed emotion is not absent emotion",
                "One flat face is data; repeated cruelty is a pattern",
            ],
        ),
        "dialogue": (
            "Dialogue: The Blank-Face Manager",
            "Your manager gives zero facial feedback: no nods, no smiles, no reaction - and you read it as disapproval. Practice the dialogue that checks the read ('I notice I can't read your reactions - am I on track?'), and learn to work with a low-expression communicator.",
            "A one-way mirror where your manager's face stays blank; your question cards test the mirror - and a crack of warmth answers through it.",
            [
                "Ask directly: 'am I on track?' - low-expression people respond",
                "Blank faces are often processing, not punishing",
                "Watch the words and actions, not just the face",
                "Their feedback style may be written, not facial",
                "Your need for facial validation is yours to manage",
                "Repeated warmth cues (even small) mark the real signal",
                "Low-expression colleagues often value clarity over cues",
                "Test, don't assume",
            ],
        ),
        "audit": (
            "Audit: Expression Baseline Log",
            "For one week, log the baseline expressions of 3 people you find hard to read: typical face, response to good news, response to bad news, and vocal tone. Build their personal baselines and test whether your 'cold' reads survive the comparison.",
            "A profile card per person: baseline face, reaction range, tone markers. The verdict box fills: COLD or EXPRESSION-NEUTRAL?",
            [
                "Everyone has an expression baseline - learn it",
                "Baselines differ by personality and culture",
                "Response to good news reveals warmth capacity",
                "Tone carries what the face withholds",
                "Your own baseline sets your expectations of others",
                "Baseline logs kill the cold-fish misreading",
                "Repeated cruelty, not flatness, is the real signal",
                "Judge people against their own baseline, not yours",
            ],
        ),
        "matrix": (
            "Matrix: Flat Cue x Context x Reading",
            "Map 10 flat-behavior cues (no smile, monotone, no eye contact, no reaction, brief answers, no small talk, delayed responses, literal answers, no empathy display, cruelty) against 3 contexts (work, family, new acquaintance) and rate each as style, processing, or warning.",
            "A 10x3 matrix where cells sort into STYLE, PROCESSING, or WARNING; only the cruelty row glows red in every column.",
            [
                "No smile at work = style or culture, rarely a verdict",
                "Monotone in family = mood or baseline, check context",
                "No eye contact with a new acquaintance = shy or neurotype",
                "No reaction to news = processing or suppression",
                "Brief answers = efficiency or coldness, context decides",
                "Literal answers may signal neurodivergence",
                "Delayed emotional responses = processing style",
                "Cruelty is the only row that is never just style",
            ],
        ),
        "boss": (
            "Boss Battle: The Yawn Test",
            "A colleague who unsettles you with their flat affect yawned - and you didn't feel the contagion from them. You remember the psychopathy research. Before you label anyone: run the full protocol - check baselines, test empathy in action, and keep your conclusion proportional to the evidence.",
            "A lab where a yawn ripple test runs between two avatars; the contagion meter is a curiosity, not a verdict - the full evidence board decides.",
            [
                "Yawn contagion is one narrow research finding",
                "A single test never labels a person",
                "Baseline, history, and action are the real evidence",
                "Psychopathy is a clinical judgment, not a party trick",
                "Flat affect ≠ dangerous - most flat people are safe",
                "Patterns of cruelty and remorse-absence are the warnings",
                "Proportional conclusions protect everyone",
                "When in doubt, gather more data and stay kind",
            ],
        ),
    },
    {
        "num": 33,
        "title": "They're Gonna Blow!",
        "pages": "173-177",
        "domain": WL,
        "scrub": (
            "Cue Scrubber: Anger Escalation Radar",
            "Scan 10 scenes for pre-explosion cues: jaw tension, color change, breathing shift, space invasion, voice hardening. Apply the red-color research (red boosts speed and strength of reactions), the intermittent-explosive-disorder knowledge, and the fist-research (pressure raises assertiveness) to rate each scene's fuse.",
            "A rage radar screen: each scene's subject gets a fuse-length reading; jaw, breath, and color markers tick up. Your dial must engage de-escalation before the fuse hits zero.",
            [
                "Pre-explosion cues: jaw, color, breath, space, voice",
                "Red increases the speed and strength of reactions - Rochester research",
                "Intermittent explosive disorder: rage out of proportion, recurrent",
                "Fist-making raises assertiveness - JESP's research",
                "Anger escalates on a curve - intervene before the peak",
                "Physical space is the safest lever: reduce it or increase it",
                "Contempt mixed with rage is the most volatile blend",
                "Your calm is the only fuse you control",
            ],
        ),
        "dialogue": (
            "Dialogue: The Pre-Blow Conversation",
            "A colleague is radiating: red face, hard jaw, clipped voice. Practice the pre-explosion intervention: lower your own voice and pace, name what you see ('you seem really wound up'), offer a face-saving exit ('let's pick this up in ten'), and steer the conversation away from the trigger.",
            "A pressure gauge rises behind the colleague's avatar; your dialogue options - pace, validation, exit - each vent a little steam before the needle pins.",
            [
                "Lower your voice first - volume contagion is real",
                "Naming the state ('you seem really wound up') opens a door",
                "A ten-minute break is a face-saving exit ramp",
                "Steering away from the trigger defuses the fuse",
                "Validation ('I get why this is frustrating') beats contradiction",
                "Never mirror the escalation",
                "Public de-escalation is humiliating - go private",
                "Post-crisis, address the pattern, not just the moment",
            ],
        ),
        "audit": (
            "Audit: Escalation Stage Log",
            "Log every anger incident you witness for a month: trigger, escalation speed, cues (jaw, color, voice, space), the intervention used, and the outcome. Build the escalation-stage model that predicts blow-ups before they peak.",
            "A waveform journal: each incident traces a spike, annotated with cue markers at each stage; your model's predicted fuse times align with reality.",
            [
                "Escalation is a curve with predictable stages",
                "Triggers cluster: interruption, disrespect, unfairness",
                "Early cues (jaw, breath, color) precede the explosion",
                "Early intervention changes the curve's peak",
                "Volume and pace track the stage",
                "Your past interventions have an outcome record",
                "The stage model predicts - and prediction protects",
                "Logging turns chaos into a map",
            ],
        ),
        "matrix": (
            "Matrix: Anger Stage x Cue x Intervention",
            "Map 5 stages (irritation, frustration, anger, rage, explosion) x 3 cue groups (face/body, voice, behavior) and assign the intervention for each cell: validate, redirect, break, or exit.",
            "A 5x3 intervention matrix: early cells read VALIDATE and REDIRECT, middle cells BREAK, late cells EXIT - the timing is everything.",
            [
                "Irritation: validate and redirect - cheapest intervention",
                "Frustration: acknowledge the blocker, offer paths",
                "Anger: lower pace, offer the break",
                "Rage: space and calm, no reasoning",
                "Explosion: exit, protect, return later",
                "Face cues: jaw, color, eyes - track them",
                "Voice cues: pitch, volume, pacing",
                "Late-stage interventions are damage control, not prevention",
            ],
        ),
        "boss": (
            "Boss Battle: The Explosive Client",
            "A client's frustration has moved to red-faced shouting - and their hand hovers near a laptop they're about to throw. Run the highest-stakes de-escalation: protect yourself physically, lower the temperature with validation and an exit ramp, document the incident, and decide whether the account needs new terms.",
            "A client's office where the fury meter pins; your move cards - SPACE, VALIDATE, EXIT, DOCUMENT - must be played in the right order to end the scene safely.",
            [
                "Physical safety outranks the account",
                "Space, calm voice, and validation lower the peak",
                "The exit ramp ('let's pause and regroup Thursday') ends the scene",
                "Never reason with a peaked amygdala",
                "Document the incident with dates and witnesses",
                "Post-incident terms: meetings with a witness, written agendas",
                "Repeat explosions = contract review",
                "Your dignity is part of the negotiation",
            ],
        ),
    },
    {
        "num": 34,
        "title": "This Meeting Is a Waste of Time",
        "pages": "178-181",
        "domain": WL,
        "scrub": (
            "Cue Scrubber: Meeting Vitality Scanner",
            "Screen 10 meeting moments for the energy cluster: suppressed yawns, glance at watches, posture collapse, doodling, emoticon-style flatness in chat. Apply the ethology lens (Eibl-Eibesfeldt's ritual behavior), the dog-yawn contagion finding, and the emoticon research to read the room and fix it.",
            "A meeting room rendered as a vitality heat-map: yawn clusters, watch-glances, and slumping posture all glow. The scanner prescribes the fix: agenda cut, energy injection, or a break.",
            [
                "Yawn contagion crosses species - dogs catch human yawns",
                "Meetings are rituals with inherited rules - ethology's lens",
                "Suppressed yawns and watch-glances are the energy cluster",
                "Chat emojis are the meeting's digital body language",
                "Emoticon meaning varies by culture - Park's research",
                "Posture collapse tracks attention loss",
                "A cut agenda is the highest-leverage fix",
                "Energy is the meeting's true currency",
            ],
        ),
        "dialogue": (
            "Dialogue: The 3pm Graveyard",
            "It's 3pm, the room is glazing, and the agenda has three more items of low relevance. Practice the room-rescue: name the energy honestly, compress the remaining agenda to decisions only, move the rest to async, and end the meeting five minutes early.",
            "A meeting room at 3pm where attention meters sag; your rescue cards - NAME, COMPRESS, ASYNC, EARLY EXIT - each restore energy and respect.",
            [
                "Naming the energy ('this is heavy - let's cut to decisions') is kind",
                "Compressing to decisions respects everyone's attention",
                "Async follow-ups preserve the content without the glaze",
                "Ending early is a gift, not a failure",
                "The 3pm body has a schedule - respect it",
                "Energy honesty is a leadership signal",
                "Decisions, not slides, justify meetings",
                "People remember the meeting that ended early",
            ],
        ),
        "audit": (
            "Audit: Meeting Energy Log",
            "For every meeting this month, log: length, agenda quality, energy cues (yawns, phones, posture), decision output, and your own contribution. Correlate energy with agenda design and find your meeting-bloat patterns.",
            "A meeting dashboard: energy and output bars per session; the correlation line proves that agenda quality predicts energy - and your best patterns emerge.",
            [
                "Agenda quality predicts meeting energy",
                "Long meetings decay attention logarithmically",
                "Decision output is the meeting's true score",
                "Energy cues are measurable, not vibes",
                "Your contribution pattern is part of the log",
                "Standing, walking, and whiteboards revive rooms",
                "No-agenda meetings are the leading bloat source",
                "The log justifies the agenda cuts",
            ],
        ),
        "matrix": (
            "Matrix: Room State x Cue x Fix",
            "Map 8 room states (post-lunch glaze, topic drift, conflict simmer, decision stall, phone-checking, meeting creep, dominance, dead-air) against their cue clusters and assign the fix for each cell: break, compress, redirect, decide, or dismiss.",
            "A 8-row repair matrix; each row shows the cue cluster and the fix card that works - the leader's cheat sheet for any room.",
            [
                "Post-lunch glaze: break or interactive segment",
                "Topic drift: agenda redirect, park the tangent",
                "Conflict simmer: name it, schedule the hard talk",
                "Decision stall: force the choice with options",
                "Phone-checking: shorten or make it participatory",
                "Meeting creep: timebox with a visible clock",
                "Dominance: rotate the airtime",
                "Dead-air: the leader asks, then waits",
            ],
        ),
        "boss": (
            "Boss Battle: The Emoticon-Only Colleague",
            "Your remote colleague's meeting feedback is emoticons only: a thumbs-up here, a skeptical face there. You must decode the digital body language, verify the read with a direct question, and build the feedback protocol that keeps the project honest despite the thin channel.",
            "A video grid where one tile shows emoticon reactions instead of a face; your decode-and-verify cards turn symbols into requirements.",
            [
                "Emoticons are thin digital body language - decode with care",
                "The skeptical face may mean doubt or keyboard fumbling",
                "Verify: 'you sent the hmm face - what's your take?'",
                "Emoticon meaning varies by generation and culture",
                "Direct questions convert symbols into requirements",
                "A feedback protocol (votes, written notes) beats symbol guessing",
                "Camera-on culture reduces decode risk",
                "Thin channels demand thicker questions",
            ],
        ),
    },
    {
        "num": 35,
        "title": "Looks Like a Winning Team",
        "pages": "182-185",
        "domain": WL,
        "scrub": (
            "Cue Scrubber: Team Bond Scanner",
            "Screen 10 team moments for cohesion: celebratory touch, high-fives, shoulder pats, proximity, shared laughter, and post-success contact. Apply the NBA research - tactile communication predicts cooperation and performance - and read which teams are bonded and which are collections.",
            "An NBA-style tracking overlay on an office: every high-five and pat draws a bright line between teammates; cohesion clusters glow while isolated nodes stay dim.",
            [
                "NBA research: tactile communication predicts cooperation - Kraus and Keltner",
                "Celebratory touch (high-fives, chest bumps) marks bonded teams",
                "Touch frequency correlates with performance outcomes",
                "Proximity and laughter are cohesion markers",
                "Touch norms differ by culture and team - calibrate",
                "Bonded teams forgive errors; collections blame them",
                "Post-success contact cements the memory",
                "Cohesion is observable before it's spoken",
            ],
        ),
        "dialogue": (
            "Dialogue: The Untouched Newcomer",
            "You're the new person in a team that high-fives, bumps shoulders, and celebrates loudly - and you're the quiet one at the edge. Practice joining the culture: mirror the celebratory energy in small ways, accept the touch rituals, and find your comfort line without becoming the cold one.",
            "A team huddle where everyone is connected by glowing touch lines except you; your moves - accept a high-five, offer a pat, join the cheer - each add a line to the constellation.",
            [
                "Teams bond through small physical rituals",
                "Accepting a high-five is joining the culture",
                "Initiating small touch (a pat, a fist bump) declares membership",
                "Your comfort line is legitimate - communicate it warmly",
                "Celebratory energy is contagious by design",
                "The newcomer's edge is visible - closing it is intentional",
                "Culture joining is a choice, not a betrayal of yourself",
                "One honest 'I'm more of a nodder' works with good teams",
            ],
        ),
        "audit": (
            "Audit: Team Bond Log",
            "Log your team's cohesion signals for two weeks: touch events, celebration moments, error responses, and proximity patterns. Score the team's bond and identify which members are outside the constellation.",
            "A social-constellation map that redraws each week; isolated nodes blink - and your intervention plan marks the next steps.",
            [
                "Cohesion signals are countable events",
                "Error responses (blame vs. support) reveal true bonds",
                "Celebration inclusion marks status",
                "Proximity patterns form naturally - and exclude silently",
                "The map shows who the team forgets",
                "Inclusion is a leader's lever: invite, connect, credit",
                "Bond scores correlate with delivery",
                "Logging makes cohesion manageable",
            ],
        ),
        "matrix": (
            "Matrix: Touch Type x Team x Effect",
            "Map 10 touch types (high-five, fist bump, shoulder pat, handshake, hug, back slap, chest bump, head rub, hand-hold, no touch) against 4 teams (startup, corporate, sports, remote) and rate the effect on cohesion plus the norm in each cell.",
            "A 10x4 matrix where each cell rates the touch's effect and flags when it's over the norm; the remote column teaches the touch substitutes.",
            [
                "High-fives: cohesion gold in startups and sports",
                "Hugs: risky in corporate, normal in some teams",
                "Handshakes: baseline everywhere",
                "Back slaps: bonding or dominance, by context",
                "Head rubs: mostly over the line",
                "Remote teams need touch substitutes: emojis, calls, rituals",
                "Norms vary - the team's own baseline is the rule",
                "Effectiveness follows consent and calibration",
            ],
        ),
        "boss": (
            "Boss Battle: The No-Contact Team",
            "Your team delivers good work but feels like four soloists: no celebrations, no touch, no warmth - and the churn is starting. Build the bond protocol: introduce celebration rituals (cheers, high-fives where welcome), credit loudly, and use the NBA insight to explain why touch and cohesion pay - while respecting every boundary.",
            "An office constellation where four nodes orbit separately; your ritual cards - CHEER, CREDIT, TOUCH, TRADITION - weave the first bright lines between them.",
            [
                "Cohesion is buildable, not genetic",
                "Celebration rituals seed the bond",
                "Loud credit is the zero-risk cohesion tool",
                "Touch follows trust - never force it",
                "The NBA research makes the business case for warmth",
                "Respect boundaries; warmth has a consent curve",
                "Churn drops when bonds form",
                "The leader models the culture first",
            ],
        ),
    },
    {
        "num": 36,
        "title": "So, You Think You're the Boss",
        "pages": "186-190",
        "domain": WL,
        "scrub": (
            "Cue Scrubber: Leadership Decoder",
            "Screen 10 leadership moments and separate authority from titles: pointing styles, space claims, voice control, decision ownership, and value consistency. Apply the protean pointing research (pointing varies by culture), Ekman's signal work, and the values-lens from the workplace research.",
            "A leadership stage where each figure's authority renders as visible signals: pointing forms, stance, pace; the decoder separates TITLE POWER from SIGNAL POWER.",
            [
                "Authority is signaled, not just granted",
                "Pointing is protean - its meaning varies across cultures",
                "Titles open doors; signals walk through them",
                "Voice control, stillness, and space claim are the raw signals",
                "Decision ownership marks real authority",
                "Values consistency builds followership - Lauby's lens",
                "One-finger pointing can read aggressive in some cultures",
                "The boss without title leads by signal and substance",
            ],
        ),
        "dialogue": (
            "Dialogue: The Pointless Pointing",
            "You've noticed your pointing habit - index finger out, jabbed at screens - leaves rooms defensive. Practice the alternatives: open-hand gestures, chin and eyebrow direction, and verbal framing that lets people follow without being pointed at.",
            "A mirror room where your pointing hand is outlined in red; each alternative gesture - open palm, nod, chin-tilt - replaces the outline with green.",
            [
                "Index-finger pointing reads as aggression to many",
                "Open-palm direction invites instead of commands",
                "Chin and gaze direction are softer pointers",
                "Verbal framing ('let's look at this') does the job",
                "Pointing habits are trainable with awareness",
                "Cultural norms decide the gesture's charge",
                "Your team's defensiveness is feedback",
                "Authority survives without the jab",
            ],
        ),
        "audit": (
            "Audit: Authority Signal Log",
            "Log your leadership signals for two weeks: how you assign, correct, praise, and decide; your pointing and posture patterns; and the responses you draw. Identify which signals build your authority and which undermine it.",
            "A leadership dashboard: signal frequency vs. team response; the correlation reveals your authority levers - and your leaky ones.",
            [
                "Correction style (public vs. private) shapes authority",
                "Praise specificity builds followership",
                "Decision speed signals ownership",
                "Posture and space claim frame your presence",
                "Consistency is the authority multiplier",
                "The log reveals your leaky signals",
                "Small fixes compound into leadership",
                "Authority is built in the boring minutes",
            ],
        ),
        "matrix": (
            "Matrix: Leadership Cue x Culture x Effect",
            "Map 10 cues (pointing, loud voice, silence, decision speed, praise, delegation, eye contact, space, dress, humor) against 3 cultures (direct, formal, egalitarian) and rate the authority effect plus the risk of misreading in each cell.",
            "A 10x3 matrix where the same cue scores differently across cultures - loud voice is authority in one and bluster in another; each cell shows the calibrated version.",
            [
                "Loud voice: authority in direct cultures, bluster in formal ones",
                "Silence: power in egalitarian rooms, confusion in formal ones",
                "Delegation: trust in egalitarian, weakness in direct",
                "Praise: bonding anywhere, with calibration",
                "Humor: warmth in egalitarian, risk in formal",
                "Eye contact: respect or challenge, by culture",
                "Dress signals hierarchy everywhere",
                "Calibrated signals travel across cultures",
            ],
        ),
        "boss": (
            "Boss Battle: The Boss Without a Title",
            "Your project is failing because the titled manager never leads: no decisions, no signals, no spine - while you have the knowledge and the room's respect but no title. Choose your play: lead from the second chair with calibrated signals, broker a role with the manager, or take the visibility risk - and own the outcome either way.",
            "A control room where the titled chair is empty and the room looks to you; your move cards - LEAD, BROKER, RISK - each light a different path forward.",
            [
                "Leadership is claimed, not waited for",
                "Calibrated signals (decisions, clarity, consistency) build followership",
                "Brokering with the titled manager converts tension into role",
                "Visibility risk is real - and calculable",
                "The room's respect is your currency",
                "Document your leadership for the record",
                "Outcomes legitimize the second-chair leader",
                "Titles follow evidence",
            ],
        ),
    },
    {
        "num": 37,
        "title": "Hand in the Cookie Jar",
        "pages": "191-196",
        "domain": WL,
        "scrub": (
            "Cue Scrubber: Guilt vs. Shame Decoder",
            "Screen 10 interrogation scenes and separate guilt from shame from stress: blocking gestures, self-soothing, avoidance, and verbal slips. Apply the Othello error (Ekman), the remorse research (remorse is not reliably readable), the Dobby effect, and the burden-of-proof principle to each scene.",
            "A corporate interrogation room rendered as a diagnostic theater: stress signals (nail-biting, lip suppression, self-soothing) are cataloged while a judge's gavel repeats: SHAME IS NOT GUILT.",
            [
                "The Othello error: stress looks identical in guilt and innocence",
                "Remorse is not reliably readable - Bandes' research",
                "Shame display is not guilt admission",
                "The Dobby effect: guilt drives self-punishment (shocks study)",
                "Guilt feelings even inflate perceived body weight",
                "Habitual liars may increase eye contact - Vrij's finding",
                "Burden of proof: on the accuser, not the accused",
                "Innocent-until-proven-guilty is the SCAN of justice",
            ],
        ),
        "dialogue": (
            "Dialogue: The Mole Interview",
            "A team leader looks guilty as hell - slumped, head in hands - but you have zero evidence. Run the professional interrogation: build rapport, ask for details beyond their story, listen for verbal bridges and drift, watch for indicator increases, and test with specific questions - while keeping the presumption of innocence.",
            "A conference room where the suspect's stress signals bloom; your question cards - DETAILS, BRIDGES, SPECIFICS, BASELINE - probe the story without breaking it.",
            [
                "Ask for more detail than the story provides",
                "Listen for verbal bridges ('and then') and time-hiding",
                "Watch for increases in body-language indicators",
                "Specific questions demand specific answers",
                "Rapport and face-saving open the truth door",
                "Stress signals prove stress, not guilt",
                "Most people confess when honesty is safer",
                "The innocent survive professional questioning",
            ],
        ),
        "audit": (
            "Audit: Stress Signal Log",
            "Log your own stress signals for two weeks: when do you bite nails, suppress lips, self-soothe, pace, or seek exits? Map your stress fingerprint so you never misread your own body - or project it onto others.",
            "A body-map journal where your personal stress signals register; the fingerprint pattern that emerges is your calibration baseline.",
            [
                "Stress has a personal fingerprint - map yours",
                "Nail-biting, lip suppression, self-soothing are stress, not deceit",
                "Pacing and exit-seeking mark discomfort",
                "Physiology: sweat, breath, blink, pallor, dry mouth",
                "Your fingerprint is the baseline for reading others",
                "Projecting your stress onto others misreads them",
                "Knowing your cues buys recovery time",
                "Calibration starts at home",
            ],
        ),
        "matrix": (
            "Matrix: Signal x Context x Guilt Interpretation",
            "Map 10 signals (head in hands, finger-on-forehead, avoidance, ghosting, over-explaining, eye contact changes, voice stress, self-touch, physical distance, emotional collapse) across 4 contexts (accusation, bad news, interview, conflict) and rate how much each actually implies guilt in that context.",
            "A 10x4 matrix where most cells stay gray - stress without guilt - and only corroborated clusters glow: EVIDENCE REQUIRED before the red verdict stamp.",
            [
                "Head in hands = shame or exhaustion, not proof",
                "Avoidance = discomfort with the situation, not the act",
                "Over-explaining = defense under stress, truth or lie",
                "Voice stress = arousal, cause unknown",
                "Emotional collapse = possible empathy or guilt",
                "Guilt-prone people read blame where none exists",
                "Empathic guilt: feeling guilt for others' acts",
                "Only corroborated clusters earn the verdict stamp",
            ],
        ),
        "boss": (
            "Boss Battle: The Corporate Cookie Jar",
            "Proprietary tech leaked, and your star team lead looks guilty: slumped, sweating, refusing to look up. Gregory Hartley's rules are on the table. Run the full investigation: baseline and rapport, detail expansion, verbal-bridge listening, specificity pressure - and land on evidence, not vibes, before anyone is accused.",
            "A boardroom stands in for an interrogation suite; the suspect's story is a document you must expand, cross-reference, and verify. The verdict stamp requires evidence, not slumped shoulders.",
            [
                "Design the plan around belonging and esteem - Hartley's drives",
                "Ask for details beyond the story's edge",
                "Listen intently for pattern straying",
                "Watch for indicator increases, not static cues",
                "Verbal bridges and specificity deny time-hiding",
                "People confess when honesty serves them",
                "Burden of proof: ei incumbit probatio qui dicit",
                "Evidence first, accusation last",
            ],
        ),
    },
]
