# -*- coding: utf-8 -*-
"""Phase 2 chapter data for Truth & Lies, chapters 1-6.
Each chapter: num, title, pages, domain, and 5 slots (scrub/dialogue/audit/matrix/boss),
each slot a 4-tuple (topic, player_mission, visual_frame_description, key_concepts[8]).
"""

D = "Body Language | Deception Detection | Critical Thinking"

CHAPTERS = [
    {
        "num": 1,
        "title": "Body Language Lies",
        "pages": "18-21",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The 'Body Language Is a Language' Myth",
            "Analyze 8 popular claims about body language. For each, decide whether it treats body language like a spoken language (fixed grammar, one meaning per gesture) and explain why the claim fails. Flag which claims would mislead a jury, a date, or a job candidate.",
            "A wall of glowing neon signs, each a famous body language 'rule' (crossed arms = defensive, nose touch = lying). A lever labeled CONTEXT flips each sign to a different meaning while a voice says 'Not a language. A clue.'",
            [
                "Body language is not a language - it lacks grammar, displacement, and reflexiveness",
                "If-this-then-that body language rules fail because one gesture has many meanings",
                "Crossed arms can mean cold, tired, self-soothing, concentrating, or defensive",
                "Nose touching can mean deception, doubt, stress, allergy, or an itch",
                "Online images are curated performances, not spontaneous behavior",
                "Our egocentric bias makes us interpret others' behavior as being about us",
                "Reductionist thinking feels useful but leads to wrong conclusions",
                "Context is the single most important factor in interpreting any gesture",
            ],
        ),
        "dialogue": (
            "Dialogue: The Three-Text Misunderstanding",
            "A friend sent three short texts with no emojis. Your partner reads them as angry, distant, and passive-aggressive. Play both sides: first the assumption-driven reading, then the SCAN reading that generates three alternative explanations (busy, tired, typed while walking) before choosing a gentle clarifying reply.",
            "A phone screen with a flat text thread. On the left a thought bubble fills with paranoid interpretations; on the right the same thread is re-scored with neutral descriptions and question marks instead of verdicts.",
            [
                "Texts are a curated channel - no tone, no face, no gesture to read",
                "Emoji absence is not anger; it may be busyness or plain writing style",
                "Ambiguity rises when the channel strips body language",
                "Projecting tone onto text is egocentric bias",
                "Ask 'what else?' before assuming hostile intent",
                "A clarifying question costs less than an accusation",
                "SCAN works in digital channels, not just face to face",
                "The medium shapes the message - text is a thin slice",
            ],
        ),
        "audit": (
            "Audit: Live vs. Curated Body Language Log",
            "Track 5 photos or posts you see today. For each, note whether it was staged (posed, filtered, selected) or spontaneous, and what real-life behavior would verify the claim it makes. Compare how much you trusted the image before vs. after the audit.",
            "A detective board with printed photos and selfies pinned between strings labeled STAGED and SPONTANEOUS. A stamp hovers: VERIFY IN PERSON.",
            [
                "Online images are performances - selected, filtered, posed",
                "We confuse curated online body language with live spontaneous behavior",
                "One photo is a thin slice, easily corrupted",
                "Beauty filters and angles manipulate first impressions",
                "People show their best moments, not their average ones",
                "Trust requires live, repeated, real-time observation",
                "Curated content tells you about the performer, not the person",
                "The camera lies more than people do",
            ],
        ),
        "matrix": (
            "Matrix: Gesture x Context x Meaning Grid",
            "Fill the grid for 8 gestures (crossed arms, nose touch, feet pointed away, smile, hand in pocket, looking down, fidgeting, head tilt) x 4 contexts (job interview, party, interrogation, cold room). Assign each cell a likely meaning and mark whether the popular 'rule' reading would be wrong.",
            "A glowing spreadsheet where each gesture row and context column intersect in a colored cell; wrong 'rule' readings flash red, correct contextual readings glow green.",
            [
                "Crossed arms in a cold room = thermal regulation, not defensiveness",
                "Crossed arms in an interview = concentration or nervousness, not rejection",
                "Nose touch in an interrogation = stress or allergy as likely as deception",
                "Smile at a funeral = masking sadness (display rule), not happiness",
                "Eye contact in some cultures = disrespect, not honesty",
                "Hands in pockets in a party = relaxed, in an interview = casual",
                "Head tilt in a date = interest; in an argument = confusion or submission",
                "The same behavior plus different context equals different meaning",
            ],
        ),
        "boss": (
            "Boss Battle: The Viral Body Language Article",
            "Your friend swears by a viral listicle: '7 Body Language Signs They're Lying.' At a party they publicly accuse someone of lying based on a nose touch. Repair the damage: debunk the rule with the person's actual context, demonstrate the if-this-then-that fallacy, and coach your friend on what real observation requires.",
            "A party scene freezes mid-conversation; a smartphone emits a glowing clickbait listicle. You must rip the page and reassemble it into a context wheel.",
            [
                "Clickbait body language rules are reductionist and dangerous",
                "A single gesture never proves deception",
                "Public accusations based on one cue damage trust",
                "The brain is not a computer - it does not process if-this-then-that",
                "Suspending judgment beats acting on instinct",
                "Real detection needs cluster, baseline, and context",
                "Apologizing for a wrong read repairs more than doubling down",
                "Teach the method, not the list",
            ],
        ),
    },
    {
        "num": 2,
        "title": "Powerful Thinking",
        "pages": "22-25",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Power Display Scanner",
            "Scan 12 scenes and classify each person's behavior as a power display, a response to power (submission or resistance), or neutral. Identify which power source is being claimed (strength, status, environment, money, knowledge, confidence) and predict the likely response from a challenger.",
            "A battlefield of silhouettes in a boardroom: one figure expands (chest out, chin up, arms wide), another compresses (head low, shoulders in, gaze down). A HUD labels each move POWER or RESPONSE.",
            [
                "All body language is a display of power or a response to power displays",
                "Power sources: physical strength, social status, environmental control, money, knowledge, confidence",
                "Power display: chest expansion, height increase, space occupation, loud voice, sustained stare",
                "Submission display: head lowering, body compression, gaze down, smaller posture",
                "Head tilt exposes the neck - submission or interest, context decides",
                "Chin jut signals defiance - refusing to submit",
                "Power shifts constantly during a conversation",
                "Power displays attract challengers and predators - they carry risk",
            ],
        ),
        "dialogue": (
            "Dialogue: The Power Shift Negotiation",
            "In a salary negotiation, the recruiter leans back, expands, and talks over you; you feel yourself shrinking. Practice re-claiming power nonverbally (open posture, eye contact, measured voice) while staying collaborative, then trade the power back and forth to see how the conversation's outcomes change.",
            "A chessboard where the pieces are people; each turn moves a 'power token' between recruiter and candidate. The candidate learns that compressing posture loses pieces.",
            [
                "Power shifts occur moment to moment in conversation",
                "Compressing your posture concedes power silently",
                "Claiming space (shoulders, arms, stance) signals presence",
                "A measured voice and pause read as confidence",
                "Sustained, calm eye contact holds the frame",
                "Power display can be assertive without being aggressive",
                "Collapse invites domination - even in negotiation",
                "The powerful speak less and listen more",
            ],
        ),
        "audit": (
            "Audit: Power Exchange Observation Log",
            "Observe one real conversation (meeting, dinner, call). Log every power move: who interrupts, who expands or shrinks, who claims the last word, who mirrors whom. Score the power trajectory minute by minute and note the moment power shifted and why.",
            "A line chart being drawn in real time labeled POWER OVER TIME; interruption spikes red, expansion spikes green, and the chart shows who ended the conversation 'owning the room'.",
            [
                "Interrupting is a dominance display",
                "The last word is a power claim",
                "Mirroring signals alignment or deference",
                "Whoever sets the topic sets the frame",
                "Volume and pace track status in the exchange",
                "Space claimed correlates with perceived rank",
                "Power can be given as well as taken",
                "Observing the trajectory beats judging one instant",
            ],
        ),
        "matrix": (
            "Matrix: Power Display x Context x Meaning",
            "For 10 behaviors (chest puff, chin jut, head tilt, staring, loud voice, touch, stepping closer, arms wide, looking away, smiling) map the likely power reading in a job interview, a date, a police stop, and a family dinner. Mark which readings are submission, dominance, or neutral in each context.",
            "A rotating prism; each face is a context. Behaviors pass through it and emerge recolored: red for dominance, blue for submission, gray for neutral.",
            [
                "A stare in a police stop = stress, not dominance",
                "A stare in a negotiation = claim, not aggression",
                "Stepping closer can be dominance or intimacy",
                "Touch in a date = connection; in a meeting = territorial",
                "Loud voice in a dinner = conflict; in a sports bar = fun",
                "Looking away in an interview = recall, not submission",
                "Smiling at work = rapport; at a funeral = masking",
                "Dominance readings depend on who holds the context's power",
            ],
        ),
        "boss": (
            "Boss Battle: The New Manager's Office",
            "Your new manager runs a dominance display campaign: invading your desk space, talking over you, standing while you sit. Defend your status without a war: claim your space, hold your frame, and rebalance power with respect so the relationship stays workable.",
            "An office corridor seen in forced perspective; the manager's shadow looms larger. You must shrink the shadow by adjusting posture, position, and pace - not by fighting.",
            [
                "Responding to dominance with collapse invites more of it",
                "Claiming physical space resets the frame",
                "Standing to match standing neutralizes height plays",
                "Calm, slow, low-voice responses resist escalation",
                "Boundary statements ('when you interrupt, I lose the point') work",
                "Power can be held without being fought",
                "Consistent, composed presence outlasts theatrical dominance",
                "Respectful resistance earns more respect than surrender",
            ],
        ),
    },
    {
        "num": 3,
        "title": "Mind Your Judgments",
        "pages": "26-27",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Judgment vs. Description Filter",
            "Run 12 statements through the filter. Classify each as a judgment (story, label, verdict) or a description (behavior, observable fact). Then rewrite every judgment as a description plus a list of alternative stories.",
            "A waterfall of spoken phrases; each phrase hits a sieve. Judgments get trapped as lumpy rocks; descriptions flow through as clear water. A caption reads: DESCRIBE, DON'T LABEL.",
            [
                "Judgments are stories we tell about behavior",
                "Descriptions are observable facts - what you actually see",
                "The brain makes assumptions to save energy",
                "Intuitive reads are barely better than chance",
                "Labels ('lazy', 'rude', 'liar') close investigation",
                "Descriptions ('arrived late, avoided eye contact') open it",
                "The obvious error: believing our inference is a fact",
                "Suspending judgment is a skill, not a flaw",
            ],
        ),
        "dialogue": (
            "Dialogue: The 'They Don't Like Me' Trap",
            "Your coworker didn't say hi in the hall. Your judgment: 'they hate me.' Run the dialogue: first play the judgment story out loud, then re-describe the behavior ('walked past quickly, looked at phone') and generate 4 alternative stories (deadline panic, phone notification, missed you, socially awkward). Choose which story you'd act on and why.",
            "A hallway scene; a colleague rushes past. Two thought-bubble paths branch: one path reddens into 'they hate me,' the other expands into a decision tree of neutral possibilities.",
            [
                "A single ignored greeting is a thin slice",
                "The judgment 'they hate me' is a story, not a fact",
                "Egocentric bias: it may not be about you at all",
                "Deadlines, notifications, and stress are common causes",
                "Alternative stories are cheap to generate, expensive to ignore",
                "Testing (a friendly hello tomorrow) beats assuming",
                "Acting on one thin slice damages real relationships",
                "Descriptions keep your options open",
            ],
        ),
        "audit": (
            "Audit: Assumption Reaction Log",
            "For one day, log every moment you catch yourself judging someone (dating profile, driver, colleague, store clerk). Record the trigger behavior, the judgment you formed, one alternative explanation, and how you would test it. Count how often the alternative was plausible.",
            "A journal app page with columns: TRIGGER | MY STORY | OTHER STORY | TEST. The page fills with rows; most rows end with a checkmark beside 'other story plausible.'",
            [
                "Assumptions trigger constantly and automatically",
                "Each assumption is a hypothesis, not a conclusion",
                "Writing the alternative story weakens the first-story grip",
                "Testing designs: a question, a second look, more data",
                "Most 'obvious' readings have at least one rival",
                "Logging builds the habit of suspension",
                "Reaction speed is the enemy of accuracy",
                "You filter every read through your own state",
            ],
        ),
        "matrix": (
            "Matrix: Situation x Judgment x Alternative Reading",
            "Build the grid for 10 situations (cancelled plans, short reply, crossed arms, no invite, late arrival, silence, joke at your expense, compliment, pause in speech, goodbye hug). For each, write the default judgment, one alternative, and the cost of acting on the default without testing.",
            "A two-column courtroom: the left column reads out default judgments; the right column objects 'alternative interpretation!' A judge's gavel labels each case COST OF NOT TESTING.",
            [
                "Cancelled plans = disinterest, or genuine overload",
                "Short reply = coldness, or busyness",
                "Silence after your story = rejection, or processing",
                "No invite = exclusion, or space limits",
                "Compliment = flattery, or honesty",
                "The cost of untested judgment is relationship damage",
                "The cost of testing is a small question",
                "Cheap tests protect expensive relationships",
            ],
        ),
        "boss": (
            "Boss Battle: The Snap-Judgment Interviewer",
            "A hiring panel rejected a candidate because one member 'felt she was lying' when she looked away recalling her employment gap. You have one hour to save the decision: demonstrate how the candidate's behavior was mislabeled, produce the alternative explanations (recall, shame about a layoff, cultural norm), and lead the panel to a retest.",
            "A hiring panel sits behind a long table; the rejected candidate's file glows on it. You must re-open the file and stamp each 'liar' note with ALTERNATIVE EXPLANATION before the panel votes.",
            [
                "Interviews are stress contexts - stress mimics deception cues",
                "Looking away to recall is normal memory behavior",
                "Employment-gap shame reads like guilt but is not deception",
                "Panels convert 'felt' impressions into facts",
                "One member's read can veto a qualified candidate",
                "Retest (structured questions, more data) beats instinct",
                "The 50/50 accuracy problem applies to interviewers too",
                "Decisions need evidence trails, not vibes",
            ],
        ),
    },
    {
        "num": 4,
        "title": "Scan for Truth",
        "pages": "27-30",
        "domain": D,
        "scrub": (
            "Cue Scrubber: SCAN Process Toolkit",
            "Run 10 scenarios through SCAN: S - suspend judgment and describe; C - identify all four context types (physical, psychological, digital, social); A - ask 'what else?' including how your own state biases you; N - form a new judgment and design a test for it.",
            "A scanning beam sweeps over a scene, labeling regions S, C, A, N like a planetary probe. The probe's readout upgrades guesses to calibrated hypotheses.",
            [
                "S: suspend judgment - pause the knee-jerk reaction",
                "S: describe behaviors, not interpretations",
                "C: physical context - environment, timing, setting",
                "C: psychological, digital, and social contexts",
                "A: ask 'what else?' - generate 3+ alternatives",
                "A: include yourself - your state is a filter",
                "N: form a new judgment, then test it",
                "SCAN lifts accuracy above the 50/50 intuitive baseline",
            ],
        ),
        "dialogue": (
            "Dialogue: The Paul Nadeau Interrogation",
            "Replay the homicide interrogation that cracked the Paul Nadeau case: establish rapport and baseline, then shift abruptly to the crime topic and watch for the body-language change (eyes left, head turned, arms crossed, lean back). Choose when to deliver the face-saving accusation - and whether the confession reads as truth or performance.",
            "A two-way mirror room; the suspect sits relaxed, then stiffens when the topic shifts. A timing bar asks: WHEN DO YOU ACCUSE? Wrong timing collapses the confession.",
            [
                "Baseline first: observe relaxed, honest behavior",
                "Rapport (lean in, common ground) precedes truth",
                "Topic shift triggers leakage in the deceptive",
                "Eyes left, head turned, arms crossed = change, not proof",
                "Verbal-nonverbal incongruence: 'no' with body saying otherwise",
                "The face-saving accusation ('you didn't mean to') lowers resistance",
                "Confession body: head in hands, turning away, hiding face",
                "SCAN works in real high-stakes situations",
            ],
        ),
        "audit": (
            "Audit: SCAN Case Log",
            "Document one real situation using all four SCAN steps. Record your initial judgment, the description you forced yourself to write, the contexts you considered, three alternative explanations, your new judgment, and the test you ran - plus what the result taught you.",
            "A lab notebook template: four colored tabs (S-C-A-N) each opening a section of the case file; a final page labeled RESULT AND LESSON.",
            [
                "Writing the description stops the label machine",
                "Naming contexts forces evidence in",
                "Alternatives are discipline, not paranoia",
                "Testing converts guesses into data",
                "The result either updates or confirms the judgment",
                "Every case adds calibration data",
                "SCAN applied to yourself is the hardest step",
                "The process, not the answer, is the tool",
            ],
        ),
        "matrix": (
            "Matrix: SCAN Step x Scenario x Application",
            "Fill the grid for 6 scenarios (dating profile, work conflict, online argument, family dinner, job interview, stranger encounter): what does S, C, A, and N look like in each? Then pick the scenario where skipping a step is most dangerous and explain why.",
            "A 6x4 matrix glowing on a wall; each cell auto-fills with a one-line application. One cell flashes red: the danger spot where skipping C (context) wrecks the read.",
            [
                "Dating: S - what do I see vs. what do I hope to see?",
                "Work: C - what's the team, history, and pressure here?",
                "Online: S - curated performance or spontaneous moment?",
                "Conflict: A - how is my own state coloring this?",
                "Interview: N - test with a structured follow-up question",
                "Skipping context is the most common fatal error",
                "Skipping description lets labels run the show",
                "Every scenario needs all four steps - order matters",
            ],
        ),
        "boss": (
            "Boss Battle: The Shoelace Mystery",
            "A mother is ready to punish her daughter for 'dawdling' by retying her shoelaces on the same corner every morning. Apply SCAN: describe the behavior neutrally, consider context (started suddenly after a specific day), ask what else (trauma witness?), and design the gentle test - asking the girl if she wants the feeling to go away.",
            "A schoolyard corner; a girl reties her shoe again and again while a storm cloud labeled PUNISHMENT gathers over the mother. You must defuse the cloud by completing all four SCAN steps.",
            [
            "Anxious, hypervigilant behavior reads as defiance only to the untrained",
                "Same route, same spot, started suddenly = context clue",
                "What else? She may have witnessed something traumatic",
                "Children's body language is often more honest than adults'",
                "A gentle open question reaches where punishment can't",
                "'Do you want this feeling to go away?' unlocked the truth",
                "Punishing a misread damages trust permanently",
                "SCAN works for parents too",
            ],
        ),
    },
    {
        "num": 5,
        "title": "They're Totally Checking Me Out!",
        "pages": "31-36",
        "domain": "Body Language | Dating & Attraction | Deception Detection",
        "scrub": (
            "Cue Scrubber: Attraction Signal Decoder",
            "Scan 12 social scenes and identify each attraction signal: eye targeting (human sclera makes gaze direction readable), hair display, neck exposure, wrist display, belly exposure, pupil dilation, preening, and mirroring. For each, give a non-attraction alternative and score the signal's reliability in that setting.",
            "A busy café rendered as a thermal view; glowing hotspots mark eye-targeting, grooming touches, and exposed wrists. A HUD warns: SINGLE CUE ≠ INTEREST.",
            [
                "The white sclera makes human gaze direction easy to read",
                "Eye targeting needs 8+ repetitions to be reliable",
                "Hair display and grooming signal health, and maybe habit",
                "Neck exposure = vulnerability or trust, not always invitation",
                "Wrist display offers thin skin - a safety/trust signal",
                "Belly exposure = deep trust or dominance, context decides",
                "Pupil dilation marks arousal - unconscious, hard to fake",
                "Mirroring signals rapport, especially when unconscious",
            ],
        ),
        "dialogue": (
            "Dialogue: The Singles Bar SCAN Challenge",
            "Across the bar, someone keeps looking your way: hair touch, eye contact, look away, look back. Apply SCAN before acting: describe the behavior, name the context (high-feint environment), ask what else (are they targeting your friend?), and design the test - moving away from your friend and watching whether the gaze follows.",
            "A neon-lit bar with split screens: the left eye-tracker counts gaze repetitions; the right shows a question mark over your friend's seat. The test: move, and watch the tracker.",
            [
                "A singles bar is a high-flirt, high-feint environment",
                "Hair touch + gaze + look-away is a cluster, not a verdict",
                "The gaze may be targeting someone beside you",
                "Moving away and watching is a clean test",
                "A returned Duchenne smile is stronger evidence",
                "Eight repetitions beats a single glance",
                "Your own wish to be wanted biases the read",
                "Test before you act - approach is reversible, accusation isn't",
            ],
        ),
        "audit": (
            "Audit: Targeting Count Log",
            "In a social setting, count eye contacts from one person over 10 minutes. Record repetitions, direction (face, neck, hands), and what changed after you moved, smiled, or looked away. Convert your counts into a confidence score for interest.",
            "A tally board with a counter clicking: each eye contact increments a dial; after 8 the dial flashes 'RELIABLE TARGETING' and after 8 with no return gaze it reads 'PERFORMANCE.'",
            [
                "Counting replaces feeling with data",
                "Gaze direction readability comes from the sclera",
                "Return gaze + smile strengthens the signal",
                "Look-away-and-back is allotropic: approach and avoid",
                "Context (bar vs. office) sets the base rate",
                "One glance is noise; eight is signal",
                "Clusters beat single cues",
                "Log your own state - it filters the count",
            ],
        ),
        "matrix": (
            "Matrix: Attraction Cue x Setting x Reliability",
            "Score 10 cues (hair display, neck exposure, wrist display, belly exposure, pupil dilation, mirroring, preening, gaze hold, head tilt, leaning in) across 4 settings (bar, office, gym, first date) on a 1-5 reliability scale and mark which settings turn each cue into noise.",
            "A heat-map grid: rows are cues, columns are settings, cells glow from dim (noise) to bright (reliable). A pointer explains each bright cell.",
            [
                "Hair display in a bar = high reliability; in a gym = habit",
                "Neck exposure on a date = interest; in interrogation = submission",
                "Belly exposure at a party = trust; at the gym = meaningless",
                "Pupil dilation is unreadable in low light",
                "Mirroring on a date = high; in a meeting = deference",
                "Preening at a wedding = romantic; in a review = anxiety",
                "Gaze hold in an interview = confidence, not attraction",
                "Alcohol inflates false positives",
            ],
        ),
        "boss": (
            "Boss Battle: The Wedding Reception Bet",
            "Your friend bets you that 'the best man is totally checking out the maid of honor' after seeing one glance. Track the evidence across the evening: count targeting repetitions, watch preening and mirroring, note approach-and-avoid moves, and call the verdict using the 8-repetition rule and cluster logic.",
            "A wedding reception where two HUD cursors track the best man's gaze and posture across 3 hours; a verdict screen asks you to justify the call with counts, not vibes.",
            [
                "Repeated targeting (8+) across an evening is meaningful",
                "Preening after the target looks = likely interest",
                "Mirroring during conversation strengthens the read",
                "Approach-avoid oscillations suggest real attraction",
                "Clusters (gaze + preen + mirror) beat any single cue",
                "Alcohol and party energy inflate false positives",
                "Counting over an evening beats judging a moment",
                "A test (move, smile, observe the return) settles it",
            ],
        ),
    },
    {
        "num": 6,
        "title": "Playing Hard-to-Get",
        "pages": "37-42",
        "domain": "Body Language | Dating & Attraction | Deception Detection",
        "scrub": (
            "Cue Scrubber: Hard-to-Get Decoder",
            "Analyze 10 courtship moments and classify each as genuine disinterest, coyness (look away to save face), or scarcity strategy (creating value through distance). Use the cluster: neck exposure during look-away, hair display, belly exposure, and whether the person returns attention when you engage elsewhere.",
            "A coy figure keeps half-turning away while exposing the neck; a decoder ring splits the behavior into three labeled tracks: DISINTEREST, FACE-SAVING, STRATEGY.",
            [
                "Allotropic signals: the same gesture means approach and avoid",
                "Look-away plus neck exposure suggests a face-saving interest",
                "Hair display during the look-away tips toward coyness",
                "Belly exposure after the look-away signals trust",
                "Hard-to-get creates value through perceived scarcity",
                "Rejection and physical pain share neural pathways",
                "Responsiveness research: perceived interest feeds desire",
                "The cluster decides which track you're on",
            ],
        ),
        "dialogue": (
            "Dialogue: The Coy Texter",
            "They reply instantly, then disappear for a day; they send a heart, then a neutral 'haha.' Practice reading the pattern with SCAN, then craft a direct-but-warm message that tests interest without chasing - and decide what to do with each possible reply.",
            "A chat thread where messages alternate warm and cold; a tension meter wobbles. Each of your reply options changes the meter and reveals a branch of the likely truth.",
            [
                "Mixed signals in text are often ambivalence, not strategy",
                "Scarcity: instant replies then silence can be a power play",
                "A warm direct question cuts through the noise",
                "Matching effort is a healthy test of interest",
                "Chasing rewards the scarcity game",
                "Your attachment anxiety can misread pauses as rejection",
                "Context: their life may explain the gaps",
                "One clear, low-pressure message decides more than ten guesses",
            ],
        ),
        "audit": (
            "Audit: Scarcity vs. Genuine Busy Log",
            "Track one relationship's communication pattern for a week: response times, initiations by you vs. them, availability excuses, and warmth on reply. Classify the pattern as scarcity strategy, genuine overload, or fading interest - with evidence for each.",
            "A week-view calendar where each message is a dot: your dots blue, theirs orange; the pattern of gaps and warmth draws itself into one of three verdict stamps.",
            [
                "Initiation ratio reveals who holds the power",
                "Consistent delay with warmth = likely busy",
                "Consistent delay with coldness = likely fading",
                "Deliberate distance after intimacy = scarcity strategy",
                "Excuses cluster ('busy', 'tired') signals withdrawal",
                "Warmth on reply beats response speed as a gauge",
                "Patterns over days beat single interactions",
                "One week of data beats one evening of gut",
            ],
        ),
        "matrix": (
            "Matrix: Signal x Stage x Meaning",
            "Map 10 behaviors (look-away, instant reply, delayed reply, neck exposure, teasing, cancellation, gift, silence, mirroring, 'maybe') against 3 relationship stages (early flirt, dating, committed) and assign each a likely meaning plus a test.",
            "A 10x3 matrix on a scroll; cells flip from INTENSE to AMBIGUOUS to WARNING as you drag the stage slider, each with an attached test card.",
            [
                "Instant replies early = high interest; in committed = baseline",
                "Delayed replies early = coyness or disinterest; later = fading",
                "Teasing early = flirt; in conflict = contempt risk",
                'Silence after intimacy = scarcity play or genuine processing',
                "Cancellations early = low priority signal",
                "'Maybe' in committed stage = avoidance, not busyness",
                "Stage changes the meaning of every signal",
                "Every ambiguous signal deserves one clean test",
            ],
        ),
        "boss": (
            "Boss Battle: The Scarcity Negotiator",
            "A vendor you like plays hard-to-get on pricing: slow replies, 'other clients,' and vanishing availability. Beat the game: recognize the scarcity frame, re-anchor value on what you bring, offer a concrete deadline, and watch how their body language (relief, deflection, or contempt) reveals whether the scarcity was real.",
            "A negotiation table where the vendor's replies drip in slowly while a scarcity meter glows red. Your moves - deadline, value re-anchor, silence - drain the meter and reveal the truth frame.",
            [
                "Hard-to-get in business is the same scarcity power play",
                "Slow replies manufacture value through delay",
                "Re-anchor the frame: your volume and timeline matter",
                "A concrete deadline forces a real answer",
                "Relief on acceptance = scarcity was a game",
                "Deflection and contempt = the game continues",
                "Silence is a power tool - use it sparingly",
                "Walk-away power is the only real leverage",
            ],
        ),
    },
]
