# -*- coding: utf-8 -*-
"""Phase 2 chapter data for Truth & Lies, chapters 7-12."""

D = "Body Language | Dating & Attraction | Deception Detection"

CHAPTERS = [
    {
        "num": 7,
        "title": "Just Feeling Sorry for Me",
        "pages": "43-47",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Pity vs. Sympathy Decoder",
            "Analyze 10 interactions and classify each as genuine sympathy, pity (obligation), or manipulation of sympathy. Use the cues: Duchenne vs. forced smile, pupillary contagion, sustained vs. fleeting engagement, and whether the sympathy is invited, offered, or extracted.",
            "A rainy café window; two figures share a table. A HUD reads their smiles: one shows eye-crinkle (Duchenne), the other a flat, rehearsed smile. A label asks: SYMPATHY OR PITY?",
            [
                "Pity dates are obligation, not attraction",
                "The enthusiasm gap separates pity from desire",
                "A Duchenne smile (eye crinkle) marks genuine feeling",
                "Deliberate Duchenne smiles can be faked - Gunnery's research",
                "Pupillary contagion: pupils widen when we feel with someone",
                "Sadness is a vulnerability display that invites care",
                "Sympathy is offered; pity is often performed",
                "Rescuing out of pity drains both people",
            ],
        ),
        "dialogue": (
            "Dialogue: The Pity Invite",
            "A friend invites you to a party 'because you seem down.' Read whether the invite is genuine sympathy or pity: flat tone, avoidant gaze, no Duchenne smile, or warm engagement and real plans. Then choose a reply that preserves the friendship whether it was pity or care.",
            "A phone call visualized as two avatars; yours is slumped, theirs hesitant. Subtitles offer two readings of the same sentence: 'just checking in' vs. 'I feel obligated.'",
            [
                "Flat voice plus avoidant gaze = obligation, not care",
                "Warm tone plus specific plans = genuine sympathy",
                "Pity invites are a gift with strings - and a burden",
                "Accepting pity dates creates resentment later",
                "Declining kindly preserves the friendship",
                "Your own state (sad, needy) distorts the reading",
                "The enthusiasm gap is the tell",
                "Ask 'what else?' before labeling the invite",
            ],
        ),
        "audit": (
            "Audit: Sympathy Signal Log",
            "Track how sympathy flows in your circle for one week: who offers help, who only offers words, who withdraws when you struggle. Note the body language at each offer (leaning in, eye contact, touch vs. distance) and grade each interaction on a genuine-to-performed scale.",
            "A support-network map; each contact node lights up when someone reaches out. Nodes with warm glow = genuine; flickering gray = performed. You adjust each based on observed cues.",
            [
                "Genuine sympathy leans in and stays present",
                "Performed sympathy glances at the clock",
                "Words without presence are scripts",
                "Touch (arm, shoulder) marks engaged sympathy",
                "People who vanish in your crisis show their priority",
                "Repeated one-way support drains the giver",
                "Logging reveals who is actually there",
                "Gratitude should flow toward the genuinely present",
            ],
        ),
        "matrix": (
            "Matrix: Sympathy Cue x Relationship x Meaning",
            "Score 8 sympathy behaviors (hug, pat, 'I'm here', gift, avoidance, silence, long vent call, canceling plans) across 3 relationships (new friend, close friend, family) and mark which combination signals real support vs. performed pity in each.",
            "A three-column display; the same behaviors shift meaning across columns. A 'support meter' fills only for genuine combinations.",
            [
                "A hug from a new friend = warmth; from family = obligation",
                "'I'm here' from a close friend = real; from an acquaintance = script",
                "Silence from family = avoidance or respect, context decides",
                "Gifts can be substitutes for presence - or real care",
                "Canceling plans to show up = strong genuine signal",
                "Long vent calls signal trust, not just pity",
                "Performed pity repeats the same words to everyone",
                "Relationship history sets the meaning of the gesture",
            ],
        ),
        "boss": (
            "Boss Battle: The Permanent Victim",
            "A friend's life is a series of crises and they always call you last on Friday night with a new emergency. Read whether the distress is real or performed (urgency vs. theatricality, problem-solving vs. helplessness), set a kind boundary, and redirect them toward actual solutions without abandoning them.",
            "A phone rings at midnight; a swirling doom-cloud avatar wails on screen. You must answer, triage the signal (REAL vs. PERFORMED), and set the boundary that keeps the friendship alive.",
            [
                "Performed distress resists solutions; real distress accepts them",
                "Theatricality and helplessness signal a drama role",
                "The crisis calendar (every Friday) is a pattern",
                "Giving money or rescue repeats the cycle",
                "A boundary ('I can't tonight, but tomorrow I can help plan') works",
                "Offering process help beats offering rescue",
                "The Karpman triangle: rescuer, victim, persecutor - step out of it",
                "Kind firmness preserves the friendship, rescue destroys it",
            ],
        ),
    },
    {
        "num": 8,
        "title": "I'm Being Ghosted",
        "pages": "48-52",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Ghosting Signal Scanner",
            "Scan 12 communication patterns and classify each as ghosting precursor, genuine busyness, or your own anxiety: response time, message length, emoji use, future planning, topic avoidance, and emotional warmth. Flag the patterns that predict disappearing.",
            "A smartphone screen where message bubbles decay: replies slow, shrink, lose emojis, then stop. A progress bar labeled 'GHOSTING RISK' rises with each decay stage.",
            [
                "Ghosting: withdrawal of communication without explanation",
                "Response time doubling is a common first signal",
                "Message length shrinking signals disinvestment",
                "Emoji and warmth loss flattens the emotional tone",
                "Future planning stops when investment stops",
                "Topic avoidance deflects closeness questions",
                "Hall's proxemics: emotional distance widens space",
                "Ghosting is a power move - it withholds closure",
            ],
        ),
        "dialogue": (
            "Dialogue: The Fading Chat",
            "Your chat partner's replies have thinned from paragraphs to 'lol' and 'haha.' Practice SCAN, then write the message that addresses the pattern without accusation ('I've noticed we're both quieter - is everything okay?') and choose how to respond to a cold, warm, or silent reply.",
            "A chat window with shrinking bubbles; a keyboard prompt asks you to type the honest question. Each possible reply branches into three future threads: WARM, COLD, SILENT.",
            [
                "Address patterns, not personalities",
                "'I noticed we're quieter' opens without accusing",
                "A cold reply is data: investment has dropped",
                "A warm reply is data: they were busy",
                "Silence is also an answer - it ends the thread",
                "One honest question beats ten ghost-hunts",
                "Your anxiety amplifies pauses - check the pattern",
                "Closure sometimes comes from within, not from them",
            ],
        ),
        "audit": (
            "Audit: Digital Distance Log",
            "Track one drifting relationship for 10 days: response times, message lengths, emoji counts, initiations, and future-plan mentions. Compute the 'investment score' trend and decide - with evidence - whether to escalate, maintain, or let go.",
            "A dashboard with five sparkline graphs labeled SPEED, LENGTH, WARMTH, INITIATION, PLANNING; all trend downward. A verdict button waits for your evidence-backed call.",
            [
                "Metrics turn hurt feelings into testable data",
                "Response speed alone misleads - warmth matters",
                "Message length tracks engagement",
                "Initiations reveal who carries the relationship",
                "Future-plan mentions reveal investment",
                "A week of flat metrics = likely drift, not a bad day",
                "Escalating communication is a legitimate test",
                "Letting go is a valid evidence-based decision",
            ],
        ),
        "matrix": (
            "Matrix: Withdrawal Cue x Stage x Interpretation",
            "Map 8 withdrawal behaviors (slow replies, no emojis, canceled plans, 'too busy', silence, cold tone, no questions about you, leaving you on read) against 3 stages (early dating, exclusive, long-term) and assign interpretation plus the right move in each cell.",
            "A sliding-stage matrix; dragging the stage slider recolor cells from YELLOW (normal) to RED (ghosting risk) and swaps the recommended move text.",
            [
                "Slow replies early = fading fast; in long-term = life happens",
                "No emojis early = cold; in long-term = baseline style",
                "Canceled plans once = context; twice with excuses = pattern",
                "'Too busy' repeated = prioritization problem",
                "Left on read daily = communication avoidance",
                "Cold tone in exclusive stage = investment check needed",
                "Stage sets the baseline for every cue",
                "The move is always: one honest check-in first",
            ],
        ),
        "boss": (
            "Boss Battle: The Henley Boy",
            "You've been ghosted after three great dates - no fight, no warning. Reconstruct the signals you missed (post-date texting decline, vague 'maybe' plans), decide whether the ghosting is about you or them, and choose your response: a calm check-in, dignified silence, or the lesson you keep either way.",
            "A date timeline reels backward: dinners, laughs, then message gaps growing wider until silence. You must replay the tape with fresh eyes and pick the exit move that protects your self-worth.",
            [
                "Ghosting is about the ghoster's avoidance, not your worth",
                "Replay the tape: the fade was often visible in patterns",
                "Post-date enthusiasm decline is the earliest tell",
                "Vague 'maybe' plans mask non-investment",
                "A dignified check-in offers closure without begging",
                "Silence can be the strongest reply",
                "Closure: you did nothing wrong by trusting",
                "The lesson is in the pattern, not the punishment",
            ],
        ),
    },
    {
        "num": 9,
        "title": "What a Complete Psycho!",
        "pages": "53-56",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Danger Signal Scanner",
            "Screen 12 relationship behaviors for danger: love-bombing, future-faking, boundary violations, jealousy escalation, surveillance, mood swings, and contempt. For each, name the Hare checklist trait or Navarro dangerous-personality pattern it resembles, and rate the risk with context.",
            "A control room screen flags behaviors with red brackets: too-fast intimacy, tracking, rage at delays. A checklist scrolls: SUPERFICIAL CHARM, LACK OF REMORSE, MANIPULATION.",
            [
                "Love-bombing: excessive flattery and gifts early = control strategy",
                "Future-faking: marriage talk at two weeks = fantasy, not commitment",
                "Boundary violations escalate from small to severe",
                "Jealousy masked as love is surveillance",
                "Punishment for delayed responses is emotional control",
                "Hare's traits: grandiosity, lack of remorse, manipulation",
                "Navarro: dangerous personalities show cluster patterns, not single cues",
                "Safety first - exit plans beat diagnoses",
            ],
        ),
        "dialogue": (
            "Dialogue: The Boundary Test",
            "A new partner showers you with attention, then sulks when you visit friends. Practice setting a clear boundary ('I need my friendships') and observe their reaction: respect, negotiation, rage, or guilt-tripping. Each reaction reveals a different risk level.",
            "A living-room scene; the partner's sweet face flickers to cold when you state the boundary. The dialogue branches: RESPECT, BARGAIN, FURY, GUILT.",
            [
                "Boundary setting is the fastest personality test",
                "Respect of 'no' signals healthy attachment",
                "Guilt-tripping over boundaries = manipulation",
                "Rage at a boundary = danger escalation risk",
                "Negotiation is healthy; renegotiating your boundary isn't",
                "Love-bombing aims to install dependency before boundaries",
                "Watch actions after the talk, not apologies",
                "A violated boundary answered with rage = exit signal",
            ],
        ),
        "audit": (
            "Audit: Red Flag Cluster Log",
            "Log every concern in a dating or friendship situation for two weeks: behavior, frequency, escalation, and your response. Score the cluster (3+ flags with escalation = danger) and record what evidence would change your risk rating.",
            "A flag wall: each incident pins a flag; escalation adds height. The wall tips to DANGER when three tall flags stand together - the cluster rule in action.",
            [
                "A single flag is context; a cluster is a pattern",
                "Frequency and escalation matter more than type",
                "Contempt, cruelty, and rage are the heaviest flags",
                "Charming recovery periods are part of the cycle",
                "Isolation from friends is a red flag tactic",
                "Financial control removes exit options",
                "Track with dates and quotes - memory softens abuse",
                "When the cluster tips, plan the exit",
            ],
        ),
        "matrix": (
            "Matrix: Behavior x Stage x Risk Level",
            "Score 10 behaviors (love-bombing, gifts, checking phone, showing up uninvited, mood swings, criticism, isolation, financial control, threats, remorse cycles) at 3 stages (first month, dating, committed) with a risk level and the calibrated response for each cell.",
            "A 10x3 risk matrix; red cells pulse for behaviors that are dangerous at every stage, yellow for stage-dependent ones. Each cell contains a recommended response.",
            [
                "Love-bombing is most dangerous in the first month",
                "Uninvited appearances = surveillance, risk at any stage",
                "Mood swings early = warning; in committed = crisis",
                "Isolation starts subtle ('they don't like me') and grows",
                "Financial control is severe at any stage",
                "Remorse cycles (abuse, apology, gifts) = escalation",
                "Threats of self-harm = immediate professional help",
                "Risk compounds: flags cluster and escalate",
            ],
        ),
        "boss": (
            "Boss Battle: The Escalation Exit",
            "Your friend's partner has escalated from criticism to surveillance to a shove. Your friend minimizes it. Build the safety plan: document incidents, test the partner's reaction to a boundary, marshal a support network, and prepare a safe exit - while staying a friend, not a rescuer.",
            "A night map with a friend's home at its center; threat markers creep closer each day. You must place the safety net (documents, allies, exits) before the red zone closes.",
            [
                "Documentation counters minimization",
                "Abuse escalates - hope is not a plan",
                "A support network breaks isolation",
                "The partner's boundary reaction reveals the stage",
                "Safe exit prep (money, documents, shelter) is urgent care",
                "Be a friend, not a rescuer - the victim chooses the timing",
                "Hotline and professional resources are part of the plan",
                "You can't save someone who isn't ready to leave",
            ],
        ),
    },
    {
        "num": 10,
        "title": "They Are Running the Show",
        "pages": "57-61",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Relationship Power Radar",
            "Scan 12 couple and group scenes and identify who is running the show: who picks the venue, who interrupts, who gets the last word, who the group watches when decisions need making. Name the power style (overt, covert, charismatic, silent) and the power source behind it.",
            "A dinner table with a power-radar overlay: decision points ping, interruptions flash, and a crown icon hovers over the quiet figure everyone checks before speaking.",
            [
                "The one everyone looks to when deciding is the leader",
                "Overt power: commands, loud voice, expanded posture",
                "Covert power: suggestions, access, information control",
                "Silent power: the one who never asks but is always consulted",
                "Interruption patterns mark the power hierarchy",
                "The last word and topic-setting claim the frame",
                "Darwin and Goodall: dominance displays run deep in our lineage",
                "Power in couples is often enacted, never spoken",
            ],
        ),
        "dialogue": (
            "Dialogue: The Unseen Puppeteer",
            "In your friend group, one quiet person always steers: venues, plans, even opinions - through sighs, pauses, and 'whatever you want.' Practice naming the dynamic, deciding whether it's healthy delegation or covert control, and having the conversation that either validates or rebalances it.",
            "A marionette stage: the puppeteer's strings attach to every friend's shoulders, invisible until a spotlight reveals them. You must decide whether to cut or acknowledge the strings.",
            [
                "Covert power works through strings, not commands",
                "'Whatever you want' with a sigh is a veto",
                "Healthy groups distribute decision turns",
                "Exhaustion and resentment signal imbalance",
                "Naming the pattern ('you vetoed it with a sigh') is the first move",
                "Ask the group directly: 'does everyone get a say?'",
                "Some people lead softly and well - context decides",
                "The question is consent, not control itself",
            ],
        ),
        "audit": (
            "Audit: Decision Power Log",
            "Track one group or couple for a week: log every decision (big and small), who proposed it, who vetoed it, and how (direct, sigh, topic change, sulk). Map the veto power and identify the silent runner of the show.",
            "A ledger of decisions; each entry records PROPOSER, VETOER, METHOD. At week's end a spider chart draws the true power map.",
            [
                "Veto power reveals the real hierarchy",
                "Sighs and topic changes are soft vetoes",
                "Decisions made 'for the group' often serve one person",
                "Gift suggestions are often power plays",
                "Money and access are covert power sources",
                "The chart beats the narrative of 'we're all equal'",
                "Fair systems rotate who decides",
                "Logging makes the invisible visible",
            ],
        ),
        "matrix": (
            "Matrix: Power Display x Relationship x Reading",
            "Map 8 displays (interrupting, choosing venues, silence, gifts, scheduling, advice-giving, finance control, praise) across 3 relationships (couple, friends, work team) and classify each as healthy leadership, negotiation, or control in that setting.",
            "A three-way matrix; the same gesture rotates through three relationship lenses, recoloring from green (leadership) to amber (negotiation) to red (control).",
            [
                "Choosing venues in a couple = habit or control, context decides",
                "Interrupting in work = dominance; in friends = enthusiasm",
                "Finance control in a couple = abuse risk; in business = role",
                "Gifts in friends = care; with strings attached = leverage",
                "Scheduling everyone's time = organizing or managing",
                "Advice-giving in a couple = support or superiority",
                "Praise control (who gets credit) is power",
                "Healthy power is borrowed and returned, not hoarded",
            ],
        ),
        "boss": (
            "Boss Battle: The Invisible Co-Leader",
            "Your team's official leader is affable and absent; a sharp colleague quietly runs everything - priorities, access, credit - from the second chair. Decide what to do: expose the shadow leader, rebalance formally, or make the arrangement explicit and fair.",
            "An org chart whose official boxes fade while a shadow org chart of real power glows beneath. You must align the two charts before the team fractures.",
            [
                "Shadow leaders run the real org chart",
                "They control access, information, and credit",
                "Naming the pattern beats fighting it blindly",
                "Formal rebalancing can fail if trust is missing",
                "Explicit arrangements (shared credit, clear roles) preserve talent",
                "The affable leader may be delegating, not abdicating",
                "Factions form where power is unspoken",
                "Make the invisible visible - respectfully",
            ],
        ),
    },
    {
        "num": 11,
        "title": "I'm Going to Pay for That!",
        "pages": "62-64",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Misreading Cost Calculator",
            "For 10 common misreadings (confidence = competence, nervousness = dishonesty, friendliness = interest, silence = agreement), calculate the cost of acting on the error: a bad hire, a lost friend, a wrong accusation. Then name the science that should correct each error - FACS, Mehrabian's actual findings, gait research.",
            "A calculator display where each wrong read keys in a price: '-$80,000 bad hire', '-a friendship'. The totals column reads: THE TRUTH IS CHEAPER THAN THE MISTAKE.",
            [
                "The 7-38-55 ratio is widely misquoted - Mehrabian's numbers were situational",
                "FACS measures facial movement - Ekman and Friesen's tool",
                "Gait and posture correlate with personality (Satchell's Big Five work)",
                "Confidence is performed; competence is verified",
                "Nervousness in interviews is normal, not deception",
                "Overconfidence in reading others costs real decisions",
                "Costly errors: hiring, accusing, marrying, trusting",
                "Slow, structured judgment beats fast charisma",
            ],
        ),
        "dialogue": (
            "Dialogue: The Price of a Wrong Read",
            "You convinced your friend to distrust their reliable new roommate because the roommate avoids eye contact - a rule you learned online. Now the friendship is strained. Walk back the error: explain the alternative explanations (shyness, culture, ADHD), and help rebuild trust with a test instead of a verdict.",
            "A shattered vase reassembles on screen: each shard is a myth rule; the vase reforms only when the real explanations click into place.",
            [
                "Eye-avoidance rules are cultural and personal, not universal",
                "Shyness, culture, and neurodivergence mimic deception cues",
                "Your confidence in the rule multiplied the damage",
                "A test (casual conversation, patience) beats a verdict",
                "Publicly correcting your own error models honesty",
                "Rebuilding trust takes time, not apologies alone",
                "Online body-language tips carry real costs",
                "Mistakes made with certainty are the expensive ones",
            ],
        ),
        "audit": (
            "Audit: Certainty vs. Evidence Log",
            "Log 5 judgments you made today with your certainty level (1-10) and your actual evidence (count of observations, context checks, alternatives considered). Correlate certainty with evidence - and identify the reads where confidence outran the data.",
            "A scatter plot: x-axis = evidence, y-axis = certainty. Points above the diagonal are red: confident without evidence. Your job: pull them down.",
            [
                "Certainty is a feeling, not a measurement",
                "Evidence = repeated observations, context, alternatives",
                "The diagonal is where confidence matches data",
                "Red points (certain, thin evidence) are the dangerous reads",
                "Familiarity breeds false confidence - we misread friends most",
                "Logging daily calibrates your judgment",
                "Verbal certainty ('definitely') often masks thin data",
                "Ask: would I bet money on this read?",
            ],
        ),
        "matrix": (
            "Matrix: Read Type x Error x Cost",
            "Fill the grid for 6 read types (attraction, deception, competence, mood, interest, trustworthiness) x 3 error costs (relationship, career, safety) and identify which errors are reversible and which are permanent.",
            "A six-row ledger where each read type lists its failure modes and price tags; permanent-cost cells are stamped in red: NO UNDO.",
            [
                "A wrong attraction read costs embarrassment, not ruin",
                "A wrong deception accusation can end a career or marriage",
                "A wrong competence read costs money and time",
                "A wrong trustworthiness read can cost safety",
                "Reversible errors: ask, test, apologize",
                "Permanent errors: accusations, betrayals, safety lapses",
                "Structure judgment where the cost is highest",
                "Cheap insurance: verify before you accuse",
            ],
        ),
        "boss": (
            "Boss Battle: The Interviewer's Mistake",
            "Your team rejected a candidate because one interviewer 'knew' the candidate lied - they looked away when discussing their employment gap. Reopen the case: identify the misread (recall, shame, stress), list the science that contradicts the folk rule, and design the structured retest that gives the candidate a fair shot.",
            "A hiring folder marked REJECTED glows on the table; you must cross out the margin note 'LIED' and replace it with a structured interview protocol before the offer deadline.",
            [
                "Look-away during recall is memory, not deception",
                "Gap shame reads like guilt but isn't",
                "Folk body-language rules have no evidentiary basis",
                "Structured interviews outperform gut reads",
                "One interviewer's certainty can veto a great candidate",
                "Reversal requires process: blind review, structured questions",
                "The cost of false negatives is real and invisible",
                "Fair process protects both candidate and company",
            ],
        ),
    },
    {
        "num": 12,
        "title": "They Are So Mad at Me",
        "pages": "65-69",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Anger Direction Scanner",
            "Scan 10 anger displays and classify them: anger at you, anger at the situation, displaced anger, or anger as power play. Use the cues: who the gaze targets, the complaint's content, escalation pattern, and whether resolution is sought or avoided.",
            "A fury thermometer screen; each scene's anger is traced to its target with an arrow - you, the situation, or the boss who isn't there. The arrow's honesty determines your response.",
            [
                "Anger is usually about power or threat, not just feeling",
                "Displaced anger targets you because you're safe, not guilty",
                "Anger seeking resolution is different from anger seeking submission",
                "Gaze and complaint content reveal the true target",
                "Escalation without resolution = power play",
                "Contempt (eye roll, sneer) is a relationship killer",
                "De-escalation starts with your own body: low, slow, open",
                "Matching volume is fuel - don't take the bait",
            ],
        ),
        "dialogue": (
            "Dialogue: The Irate Client",
            "A client shouts at you over a delayed delivery. Practice the de-escalation dialogue: keep your voice low and slow, validate ('I understand this is frustrating'), avoid defensive posture, offer a concrete next step, and end the exchange without absorbing the blame - or the heat.",
            "A storm client avatar reddens and grows; your avatar must stay cool and stable. Every defensive reply feeds the storm; every calm validation shrinks it.",
            [
                "Volume and pace mirroring escalates - don't mirror",
                "Validation ('I get it') disarms more than excuses",
                "A concrete next step moves from emotion to action",
                "Open posture (palms, uncrossed arms) lowers threat",
                "Personalizing their anger makes you the target",
                "Breathing shifts your own signals first",
                "The complaint is about the delay, not your worth",
                "End with a commitment you can keep",
            ],
        ),
        "audit": (
            "Audit: Anger Trigger Pattern Log",
            "Log your own anger episodes for two weeks: trigger, escalation level, body signals (heat, jaw, fist), your response, and the aftermath. Identify your personal pre-anger cues and the situations that reliably load your temper.",
            "A bio-dashboard: each episode plots trigger, bodily arousal, and outcome. Patterns emerge: 'interrupted during focus' and 'tired' cluster visibly.",
            [
                "Your body signals anger before you feel it",
                "Jaw, fist, heat, and pace are early cues",
                "Triggers cluster: fatigue, hunger, interruption, disrespect",
                "Knowing your pre-anger cues buys a pause",
                "The pause is where choice lives",
                "Aftermath patterns (guilt, damage) motivate change",
                "Logging turns 'I have a temper' into 'I have triggers'",
                "A calm-down protocol beats willpower",
            ],
        ),
        "matrix": (
            "Matrix: Anger Type x Context x Response",
            "Map 8 anger types (righteous, displaced, defensive, contemptuous, passive-aggressive, explosive, controlled, cooling) against 3 contexts (home, work, public) and assign the calibrated response for each cell: de-escalate, confront, set boundary, or disengage.",
            "A 8x3 grid where each cell contains a short response play. A warning column flashes for explosive and contemptuous anger: DISENGAGE FIRST.",
            [
                "Righteous anger at home deserves a hearing",
                "Displaced anger at work should be redirected, not absorbed",
                "Contemptuous anger rarely repairs - protect yourself",
                "Passive-aggressive anger needs direct naming",
                "Explosive anger requires physical safety first",
                "Controlled anger (calm, precise) may be legitimate",
                "Cooling anger needs space, not escalation",
                "Context decides: public shaming risks are real",
            ],
        ),
        "boss": (
            "Boss Battle: The Raging Partner",
            "Your partner's anger has moved from raised voices to slammed doors, and now a thrown object. Apply the scanner: is this stress spillover or a control pattern? De-escalate the immediate moment, set a firm boundary about violence, and decide what help or exit the pattern requires.",
            "A domestic scene flickering between cozy and stormy; a line on the floor marks the boundary. Crossing it during rage triggers the exit protocol, not another round.",
            [
                "Violence is a boundary, not a dispute style",
                "Stress spillover explains anger; it doesn't excuse destruction",
                "De-escalate first: low voice, space, no threats",
                "State the boundary after calm, not during rage",
                "Repeated violence requires help and exit planning",
                "Documentation protects you if you leave",
                "The pattern (remorse-gift-repeat) signals escalation risk",
                "Safety beats saving the relationship",
            ],
        ),
    },
]
