# -*- coding: utf-8 -*-
"""Phase 2 chapter data for Truth & Lies, chapters 25-30."""

FF = "Body Language | Friendship & Family | Social Dynamics"
WL = "Body Language | Working Life | Power & Deception"

CHAPTERS = [
    {
        "num": 25,
        "title": "Lying Through Their Teeth",
        "pages": "132-137",
        "domain": FF,
        "scrub": (
            "Cue Scrubber: Lie Leak Scanner",
            "Screen 10 statements for deception using science, not folk rules: story consistency, detail density, verbal-nonverbal incongruence, and over-control. Debunk the NLP eye-accessing myths and rank each statement's deception risk with reasons.",
            "A polygraph-style console analyzes each statement: consistency lines, micro-leak markers, and a red banner over the NLP myths: EYE ACCESSING CUES - DEBUNKED.",
            [
                "NLP eye-accessing cues are debunked - Wiseman's research",
                "Story consistency across retellings is a strong signal",
                "Over-control (stiff, rehearsed) marks prepared lies",
                "Liars may increase eye contact to sell the lie - Vrij",
                "Truth needs less defense than lies",
                "High-stakes lies leak more; rehearsed ones leak less",
                "White lies show few leaks - little guilt, little fear",
                "Incongruence between words and body is the useful signal",
            ],
        ),
        "dialogue": (
            "Dialogue: The Retell Test",
            "You suspect a friend's story is polished - too polished. Practice the friendly retell test: ask for the story in reverse order or with new details, listen for consistency and specificity, and decide what the result means before any accusation.",
            "A story spins on a turntable; replaying it backwards exposes the seams. Your questions - 'wait, where were you again?' - either knit the truth or unravel it.",
            [
                "Asking for details a liar didn't prepare is the classic test",
                "Reverse-order retelling strains constructed stories",
                "Consistency across tellings is the strongest verbal signal",
                "Over-polished delivery signals rehearsal",
                "Real memories have texture: small, odd, incidental details",
                "Confabulated details change with each telling",
                "One inconsistency is human; a pattern is information",
                "Friendly testing keeps the relationship intact",
            ],
        ),
        "audit": (
            "Audit: Inconsistency Pattern Log",
            "For one week, log any story inconsistencies you observe (retellings, details, timelines) with stakes and context. Note which inconsistencies accompanied deception vs. simple memory error, and refine your personal cue-weights.",
            "A case-file ledger: each entry dates the tellings and marks the drift. Calibration notes accumulate at the bottom.",
            [
                "Inconsistency correlates with deception in high-stakes contexts",
                "Memory error is real - small details drift naturally",
                "Stakes separate lies from sloppy recall",
                "High-stakes consistency = strong honesty signal",
                "Rehearsed liars stay consistent until pressed for new detail",
                "Emotional details that never change may be scripted",
                "Your cue-weights sharpen with logged evidence",
                "Calibration beats folk wisdom",
            ],
        ),
        "matrix": (
            "Matrix: Lie Type x Context x Leak Reliability",
            "Map 8 lie types (white lie, exaggeration, omission, fabrication, denial, deflection, rehearsed lie, pathological) across 4 contexts (social, dating, work, interrogation) and rate leak reliability - which lies show reliable body signals, and which don't.",
            "A 8x4 reliability grid; the white-lie column is mostly gray (few leaks), the interrogation column is bright (high stakes, more leaks) - with caveats stamped on the rehearsed rows.",
            [
                "White lies: low stakes, few leaks",
                "Exaggeration: moderate leaks, context-tolerant",
                "Omission: deflection cues, not classic leak signals",
                "Fabrication: detail drift under retelling",
                "Denial under pressure: high leak potential",
                "Rehearsed lies: over-control, few classic leaks",
                "Pathological lies: hardest - the liar believes them",
                "Stakes and rehearsal set the reliability dial",
            ],
        ),
        "boss": (
            "Boss Battle: The Witness Stand",
            "In a workplace investigation, two colleagues give conflicting accounts of a meeting. One story is polished and consistent, the other is messy with texture. Apply the science: pressure-test both with detail questions, weigh consistency against rehearsal, and deliver your finding to the panel with the evidence trail.",
            "Two witness boxes; each account renders as a thread of evidence. Your detail-questions fray one thread and tighten the other - the panel watches the weaver's hands.",
            [
                "Messy, textured truth vs. polished construction",
                "Detail questions break rehearsed narratives",
                "Inconsistency patterns across people are triangulable",
                "Motivation analysis: who benefits from which version?",
                "Body language in hearings is affected by stress - don't over-read",
                "The evidence trail, not the charisma, decides",
                "Panel findings need the reasoning, not just the verdict",
                "Truth survives pressure; fiction unravels",
            ],
        ),
    },
    {
        "num": 26,
        "title": "Persona Non Grata",
        "pages": "138-140",
        "domain": FF,
        "scrub": (
            "Cue Scrubber: Social Aggression Scanner",
            "Screen 10 social-exclusion moments for covert aggression: eye-rolling, dagger stares, contempt faces, laughter at your expense, and exclusion from conversations. Apply the research on teen girls' nonverbal aggression and Gottman's contempt signal to rate each behavior.",
            "A lunchroom rendered as a threat map; eye-rolls ping like sonar, dagger stares flash red, and contempt faces are circled by the scanner's algorithm.",
            [
                "Eye-rolling is a socially aggressive power signal",
                "Dagger stares are intimidation without words",
                "Contempt (one-sided sneer, eye roll) is Gottman's heaviest warning",
                "Laughter at your expense tests your status",
                "Exclusion rituals: conversations that close when you approach",
                "Teen-girl research shows nonverbal aggression is deliberate craft",
                "Contempt signals the target is beneath consideration",
                "Reading it early prevents being played",
            ],
        ),
        "dialogue": (
            "Dialogue: The Eye-Roll Clique",
            "A group at work rolls their eyes at your ideas and closes ranks when you approach. Practice the options: address the pattern directly, build alliances around the clique, or work around them - and decide which response fits the power structure.",
            "A cafeteria table turns away as one organism; your strategy cards - CONFRONT, ALLY, BYPASS - each show a different future frame of the table.",
            [
                "Direct confrontation works when you hold the power",
                "Alliance-building works when the clique is entrenched",
                "Bypassing works when you control your own deliverables",
                "Naming the behavior ('that eye roll was loud') costs the cover",
                "Their cohesion is strongest when you're the enemy",
                "Individual members are often warmer than the group",
                "Escalate only with allies and evidence",
                "Your results are the strongest reply",
            ],
        ),
        "audit": (
            "Audit: Contempt Log",
            "Log every contempt or exclusion signal you witness or receive for two weeks: behavior, context, source, and your response. Distinguish the deliberate from the careless, and map which relationships are actually hostile.",
            "A field notebook with two columns: DELIBERATE and CARELESS; the deliberate column's entries accumulate names and dates.",
            [
                "Deliberate contempt repeats and targets",
                "Careless slights are diffuse, not personal",
                "Contempt patterns identify real hostility",
                "Your response history shapes the pattern",
                "Responding to carelessness as hostility starts wars",
                "Responding to deliberate contempt with warmth enables it",
                "The log separates enemies from acquaintances",
                "Calibrated responses preserve your reputation",
            ],
        ),
        "matrix": (
            "Matrix: Aggression Signal x Setting x Escalation Risk",
            "Map 8 signals (eye roll, dagger stare, whisper-and-laugh, exclusion, mocking mimicry, silent treatment, smear campaign, physical intimidation) across 3 settings (work, social, family) and rate escalation risk plus the response ladder for each cell.",
            "A 8x3 matrix; risk cells glow from amber to red, each containing a response rung: IGNORE, NAME, CONFRONT, REPORT, EXIT.",
            [
                "Eye rolls: low risk at work, address early in cliques",
                "Whisper-and-laugh: social poison, name it once",
                "Silent treatment: relationship weapon, needs a talk",
                "Mimicry and mockery: bullying, document it",
                "Smear campaigns: reputational attack, respond with facts",
                "Physical intimidation: report, always",
                "Escalation risk rises with isolation of the target",
                "The ladder: ignore, name, confront, report, exit",
            ],
        ),
        "boss": (
            "Boss Battle: The Smear Campaign",
            "A rival has been whispering about your work for weeks, and now a project lead repeats the smear. Rebuild your standing: verify the claims, expose the pattern with facts, repair the lead's impression, and decide whether the rival needs a private boundary conversation.",
            "A rumor web spreads from one node to the project lead's office; you must trace the threads, pin facts over rumors, and sever the web at its source.",
            [
                "Verify every claim before responding",
                "The rumor's source is the pattern's owner",
                "Facts, dates, and artifacts beat counter-rumors",
                "Repair the key impression privately, not at scale",
                "A private boundary conversation with the rival ends most campaigns",
                "Reputation defense is a results game",
                "Don't descend to the tactics - it legitimizes them",
                "Documentation is your shield",
            ],
        ),
    },
    {
        "num": 27,
        "title": "Invisible Me",
        "pages": "141-146",
        "domain": FF,
        "scrub": (
            "Cue Scrubber: Visibility Scanner",
            "Screen 10 room-scenes for invisibility patterns: being talked over, ideas credited to others, no eye contact when you speak, forgotten contributions. Apply the power-posing research - with its replication caveats - and the posture science to plan your visibility moves.",
            "A meeting room where one figure renders translucent each time they're interrupted; a visibility meter rises only when they claim space, voice, and eye contact.",
            [
                "Invisibility: contributions heard but unattributed",
                "Being talked over is a status event, not a hearing problem",
                "Power posing research is contested - use the behavioral core",
                "Posture shapes mood: slumping feeds invisibility",
                "Claiming space: taller stance, wider gestures, steady voice",
                "Eye contact before speaking pre-claims the floor",
                "Timing matters: early in the meeting beats late",
                "Pre-alignment with stakeholders carries your idea in",
            ],
        ),
        "dialogue": (
            "Dialogue: The Repeated Contribution",
            "You made a point; a colleague repeated it and got the credit - again. Practice the three moves: claiming the floor with a calm interruption ('as I said minutes ago'), pre-aligning before the meeting, and having the private conversation if the pattern persists.",
            "A meeting avatar repeats your words to applause while you gray out; your move cards - CLAIM, PRE-ALIGN, CONFRONT - each restore color differently.",
            [
                "Claim calmly: 'as I mentioned earlier' reclaims credit",
                "Pre-alignment plants your idea with stakeholders",
                "Speaking early in the agenda raises attribution",
                "Private conversations with the repeat offender usually fix it",
                "The pattern, not the incident, deserves confrontation",
                "Document repeated credit theft",
                "Your delivery (assertive vs. tentative) sets the frame",
                "Claiming credit is professional, not rude",
            ],
        ),
        "audit": (
            "Audit: Visibility Log",
            "Log one week of meetings: how often you spoke, when (early/late), whether your points were credited, and your posture and preparation. Identify which inputs correlate with visibility - and design the fix.",
            "A meeting scorecard: SPEAK TIMING, CREDIT RECEIVED, POSTURE, PREP - trend lines show what moves your visibility needle.",
            [
                "Speaking early correlates with credit and recall",
                "Tentative framing ('maybe we could') invites takeover",
                "Posture and voice project before content lands",
                "Pre-alignment multiplies your idea's chances",
                "Your preparation quality sets the ceiling",
                "The visibility log is your negotiation brief",
                "Patterns over weeks reveal the real levers",
                "Fix the inputs, watch the outputs",
            ],
        ),
        "matrix": (
            "Matrix: Invisibility Cause x Response x Effect",
            "Map 8 causes of invisibility (tentative delivery, late speaking, low posture, group bias, hierarchy, interruptions, cultural norms, your own quiet style) against 3 response levels (adjust delivery, change structure, escalate) and predict the effect of each.",
            "A 8x3 matrix; each cell shows the likely effect of the fix: HIGH, MEDIUM, or LOW - so you invest where it pays.",
            [
                "Tentative delivery: fix with assertive framing - high effect",
                "Late speaking: move up the agenda - medium effect",
                "Group bias: structural responses needed - variable",
                "Hierarchy: build allies above - medium effect",
                "Interruptions: calm claim-moves - medium effect",
                "Cultural norms: learn the room's code first",
                "Own quiet style: preparation and pre-alignment",
                "Invest where the matrix glows",
            ],
        ),
        "boss": (
            "Boss Battle: The Room That Forgets You",
            "Three meetings in a row, your project was ignored until your manager credited someone else for it. Run the full visibility protocol: claim in the room, pre-align with stakeholders, document the pattern, and have the career conversation - because this is about your trajectory, not just credit.",
            "A conference room where your name keeps getting wiped from the whiteboard; you must re-write it with process (alignment, claims, docs) until it sticks.",
            [
                "Invisibility patterns are career data",
                "Claiming in the room is step one, not the solution",
                "Stakeholder alignment is the structural fix",
                "Documentation turns feelings into a case",
                "The career conversation names the pattern and the ask",
                "Bias (gender, age, style) may be the engine - plan for it",
                "Visibility is built across meetings, not in one",
                "Your trajectory is your responsibility to manage",
            ],
        ),
    },
    {
        "num": 28,
        "title": "I Aced That Interview",
        "pages": "147-151",
        "domain": WL,
        "scrub": (
            "Cue Scrubber: Interview Signal Scanner",
            "Screen 10 post-interview memories and distinguish performance from signal: handshake quality, mirroring, question depth, rapport moments, and the interviewer's engagement. Apply the handshake research - it transmits chemical and social signals - and the Great Place to Work lens on fit.",
            "An interview replay console: the handshake frame is zoomed and annotated, the interviewer's engagement traces a line, and each 'I aced it' belief is tested against the footage.",
            [
                "Handshakes transmit chemical and social signals - Frumin's research",
                "Handshake quality shapes impressions before words do",
                "Mirroring marks rapport - if the interviewer mirrors you, it's warm",
                "Question depth tracks the interviewer's investment",
                "Engagement cues: leaning in, follow-ups, eye contact",
                "'I aced it' is a feeling; the signals are the data",
                "Fit with the culture (Great Place to Work lens) decides offers",
                "Silence during interviews is a test - and a cue",
            ],
        ),
        "dialogue": (
            "Dialogue: The Silent Interviewer",
            "Your interviewer asks one question, then listens stone-faced. Practice surviving and winning the silence: keep answers structured (claim, evidence, close), use their pauses to ask thoughtful follow-ups, and read whether the stone face is evaluation, boredom, or their normal style.",
            "An interview room where the interviewer's avatar sits statue-still; your answer timer runs. Each structured response adds a small glow to their expression.",
            [
                "Stone-faced interviewing is often deliberate evaluation",
                "Structure your answers: claim, evidence, close",
                "Their pauses are your opening for thoughtful questions",
                "Boredom cues (glazed, phone) mean adapt or rescue",
                "Your calm in silence is itself a signal",
                "Mirroring a stone face invites distance - stay warm",
                "Follow-up questions show engagement and interest",
                "The decision is made on your signals too",
            ],
        ),
        "audit": (
            "Audit: Interview Debrief Log",
            "After your next interview, log: handshake details, mirroring moments, question types, engagement cues, your own state, and your gut score. Compare the log against the outcome to calibrate your interview self-assessment.",
            "A debrief form with signal checkboxes and a 'gut vs. evidence' slider; past entries show how often the gut aligned with the offer.",
            [
                "Your gut after interviews correlates poorly with offers",
                "Signal logs calibrate your self-assessment",
                "Handshake and mirroring notes predict rapport claims",
                "Question depth predicts seriousness, not necessarily offers",
                "Your own nerves bias the memory",
                "Outcome feedback sharpens the log",
                "Calibrated self-assessment reduces interview anxiety",
                "The log is practice for the next room",
            ],
        ),
        "matrix": (
            "Matrix: Interview Cue x Stage x Meaning",
            "Map 10 cues (firm handshake, mirroring, follow-ups, note-taking, time overrun, stone face, phone glances, referral talk, salary questions, 'we'll be in touch') against 3 stages (first round, panel, final) and assign meaning plus the correct follow-up for each cell.",
            "A 10x3 matrix where cells predict outcomes: WARM, NEUTRAL, or COLD - with the recommended thank-you note angle for each.",
            [
                "Time overrun is a strong warm signal in finals",
                "Note-taking correlates with serious consideration",
                "Phone glances early = test; at the end = distraction",
                "Referral talk ('you'd work well with X') is a warm tell",
                "Salary questions in round one = screening; in finals = serious",
                "Stone face in a panel is often the norm - don't misread",
                "Follow-up questions mark engagement, not necessarily the offer",
                "The thank-you note should answer the cold cells",
            ],
        ),
        "boss": (
            "Boss Battle: The Odor of the Handshake",
            "You're on the hiring panel and feel instantly colder toward one candidate - the one with the limp, brief handshake. The research says handshakes transmit chemical signals that shape behavior. Decide: does your impression survive scrutiny, and can you separate the handshake effect from the actual candidacy?",
            "A panel table; the candidate's handshake replay glows with chemical-signal annotations. Your decision dashboard separates RAPPORT EFFECT from EVIDENCE.",
            [
                "Handshakes influence impressions through chemical signals",
                "A limp handshake is a signal, not a verdict",
                "Panel bias must be named to be corrected",
                "Structure neutralizes first-impression drift",
                "Rapport and competence are different columns",
                "The candidate's record outranks the grip",
                "Discuss the effect openly - it reduces it",
                "Your panel leadership sets the fairness standard",
            ],
        ),
    },
    {
        "num": 29,
        "title": "They Hate My Work",
        "pages": "152-155",
        "domain": WL,
        "scrub": (
            "Cue Scrubber: Feedback Truth Decoder",
            "Screen 10 feedback messages and separate the signal from the style: emoji use, word choice, response speed, specificity, and follow-up behavior. Apply the emoji research - interpretations vary wildly - and the company-values context to decode what was actually said.",
            "A message inbox where each feedback email is decoded: emoji counts, vague adjectives flagged, specificity scored. The decoder asks: what did they actually mean?",
            [
                "Emoji interpretations vary widely - Miller's research",
                "Emoji are digital body language - thin but real",
                "'Nice work' with no specifics is low-information",
                "Specific praise (what, why) is the real signal",
                "Response speed and follow-up track true investment",
                "Company values set the feedback language (Lauby's lens)",
                "Flat 'fine' in a review culture = code for concern",
                "Ask for specifics - clarity is a right, not a favor",
            ],
        ),
        "dialogue": (
            "Dialogue: The Vague Manager",
            "Your manager said 'solid job, just tighten it up' and moved on. Practice the clarifying dialogue: ask for the specifics ('which section, what would you change?'), schedule the follow-up, and convert the vague feedback into an actionable list.",
            "A meeting room where the manager's feedback floats as fog; your question cards - WHAT, WHERE, HOW MUCH - condense it into bullet points.",
            [
                "'Tighten it up' is a feeling, not feedback",
                "Ask what, where, and how much - specifically",
                "Suggest concrete options ('should the intro go to half a page?')",
                "Schedule the follow-up so the feedback has teeth",
                "Managers often lack feedback training - coach them",
                "Written summaries prevent later disputes",
                "Repeated vagueness = documentation time",
                "Your clarity is a professional standard, not pushback",
            ],
        ),
        "audit": (
            "Audit: Feedback Interpretation Log",
            "Log one week of feedback (verbal, email, chat): the exact words, emoji and tone markers, your interpretation, and the outcome of any clarifying question. Calibrate your decoding of your workplace's feedback dialect.",
            "A translator's log pairing raw feedback with decoded meaning; the dialect dictionary at the end is your personal key to the office.",
            [
                "Feedback style is a workplace dialect you can learn",
                "Emoji use varies by generation and culture",
                "Specificity is the real information carrier",
                "Follow-up behavior confirms or cancels the words",
                "Your interpretation bias (anxiety, hope) colors the decode",
                "Clarifying questions are the calibration tool",
                "The log builds your personal feedback dictionary",
                "Accurate decoding reduces both anxiety and complacency",
            ],
        ),
        "matrix": (
            "Matrix: Feedback Cue x Medium x Meaning",
            "Map 10 cues ('nice work', silence, thumbs up, 'let's discuss', flat face, detailed comments, emoji, delay, public vs. private praise, rework) across 3 mediums (email, chat, face-to-face) and decode the meaning plus the response for each cell.",
            "A 10x3 matrix where each cell decodes the cue in that medium - a thumbs-up in chat is normal, in a review it's thin.",
            [
                "Silence in chat after delivery = busy or avoiding, check in",
                "'Let's discuss' = the real feedback is verbal",
                "Detailed comments = investment and standards",
                "Public praise = status; private praise = intimacy",
                "Rework without explanation = broken feedback loop",
                "Delay in feedback correlates with low priority",
                "Emoji in email soften, not replace, the message",
                "Medium norms set the decode",
            ],
        ),
        "boss": (
            "Boss Battle: The Emoji Performance Review",
            "Your annual review consists of three lines, two smileys, and a 'keep going.' Your career needs specifics. Run the conversation that extracts real feedback, documents the exchange, and sets the goalposts for next year - without burning the relationship.",
            "A review document with two smileys floating on an otherwise blank page; your extraction questions fill the page line by line.",
            [
                "Smileys are not criteria",
                "Extract specifics: priorities, standards, examples",
                "Document the agreed goalposts",
                "Ask about gaps directly: 'what's holding me back?'",
                "Feedback training may be absent - be the structured one",
                "The review document is your negotiation record",
                "Follow-up check-ins keep the goals alive",
                "Career clarity is worth one awkward conversation",
            ],
        ),
    },
    {
        "num": 30,
        "title": "Big Dog",
        "pages": "156-161",
        "domain": WL,
        "scrub": (
            "Cue Scrubber: Presence Decoder",
            "Screen 10 presence displays and separate authentic confidence from performance: stillness, voice pacing, eye contact, space claim, and consistency. Apply the face-perception research - static cues differ from dynamic ones - and the photographer's lens on how presence photographs.",
            "A stage where each presenter's presence is measured: stillness and pace trace steady lines; performance flickers. The decoder separates the big dog from the loud dog.",
            [
                "Static facial cues and dynamic ones are read differently - Hehman's research",
                "Stillness reads as confidence; fidgeting reads as anxiety",
                "Voice pacing: slow, low, and even projects authority",
                "Space claim (stance, arm span) sets the room's frame",
                "Eye contact held calmly marks presence",
                "Loudness is not authority - volume and power diverge",
                "Photographers know pose: the lens exaggerates what you project",
                "Consistency across settings marks the genuine big dog",
            ],
        ),
        "dialogue": (
            "Dialogue: The New VP",
            "A new VP enters with a studied swagger: loud voice, invasive handshakes, half-smiles. Practice reading the performance, finding the actual competence underneath, and building a working relationship that sees past the display - or confirms it.",
            "The VP's entrance replays in slow motion with annotations; your conversation options either feed the performance or reach the person behind it.",
            [
                "Performance and competence are separate columns",
                "Swagger may mask insecurity - or confirm entitlement",
                "Test with work questions, not posture politics",
                "Half-smiles and invasive handshakes are displays, not verdicts",
                "Finding the person behind the display builds rare access",
                "Don't feed the performance - stay neutral and specific",
                "Deliverables reveal the real big dog",
                "Your own presence should hold, not submit",
            ],
        ),
        "audit": (
            "Audit: Presence Log",
            "Log your own presence across 10 interactions: posture, voice, space, eye contact, stillness - and the responses you drew. Identify which presence levers move your outcomes and which you overuse.",
            "A bio-feedback chart per interaction: PRESENCE SCORE vs. OUTCOME; the correlation line shows which levers actually matter.",
            [
                "Presence is a set of levers, not a personality",
                "Posture and stillness are trainable",
                "Voice pacing can be rehearsed to calm",
                "Eye contact is the cheapest authority tool",
                "Space claim varies by culture - calibrate",
                "Outcome data reveals which levers pay",
                "Overused levers (volume) read as aggression",
                "Your presence log is a coaching dashboard",
            ],
        ),
        "matrix": (
            "Matrix: Presence Cue x Setting x Perception",
            "Map 10 cues (stillness, volume, eye contact, space, pace, humor, touch, dress, silence, smile) across 4 settings (negotiation, presentation, interview, social) and predict the perception each cue creates in each setting.",
            "A 10x4 matrix where each cell scores the cue's effect: AUTHORITY, WARMTH, RISK, or NOISE - colored by setting.",
            [
                "Stillness in a negotiation = control; in a party = stiffness",
                "Volume in a presentation = command; in an interview = bluster",
                "Silence in a negotiation = power; in a date = awkward",
                "Touch in a presentation = warmth; in an interview = risk",
                "Humor in social = charm; in a negotiation = leakage",
                "Dress reads instantly and sets expectations",
                "Eye contact in every setting is the baseline authority tool",
                "Perception is set by the setting",
            ],
        ),
        "boss": (
            "Boss Battle: The Alpha Standoff",
            "A senior colleague dominates every meeting: talks over people, claims credit, occupies the room. Apply the big-dog playbook: hold your presence without aggression, use stillness and timing, claim your points calmly, and build the coalition that outlasts the volume.",
            "A meeting room where the alpha's volume bar maxes out; your presence dial - stillness, pace, eye contact - must hold its line without spiking the conflict meter.",
            [
                "Volume is a bluff you don't have to call loudly",
                "Stillness and pacing outlast shouted points",
                "Claim space and points calmly and early",
                "Coalition building beats solo duels",
                "Document credit theft quietly and factually",
                "The room eventually tires of noise",
                "Your calm is a contrast that reads as authority",
                "The alpha's power depends on your participation",
            ],
        ),
    },
]
