# -*- coding: utf-8 -*-
"""Phase 2 chapter data for Truth & Lies, chapters 13-18."""

DD = "Body Language | Dating & Attraction | Deception Detection"
FF = "Body Language | Friendship & Family | Social Dynamics"

CHAPTERS = [
    {
        "num": 13,
        "title": "A Lying Cheat?",
        "pages": "70-74",
        "domain": DD,
        "scrub": (
            "Cue Scrubber: Infidelity Signal Scanner",
            "Screen 10 relationship behaviors for deception: sudden grooming changes, new schedule patterns, phone guarding, intimacy drop, defensiveness spikes, and story inconsistencies. For each, apply Ekman's caution - list the innocent explanations before weighing the guilty ones.",
            "A relationship timeline with flags: a grooming change, a guarded phone, a vague 'work dinner'. Each flag splits into two branches: INNOCENT EXPLANATION vs. DECEPTION CLUSTER.",
            [
                "Sudden appearance changes can signal a new audience - or a new habit",
                "Phone guarding (angle, password) marks secret communication",
                "New schedules with vague explanations invite questions",
                "Intimacy drop plus defensiveness is a classic cluster",
                "Ekman: clusters beat single cues in detecting deceit",
                "The Othello error: stress looks the same in guilt and innocence",
                "Innocent explanations: work stress, health, surprise planning",
                "False accusations damage trust even when unfounded",
            ],
        ),
        "dialogue": (
            "Dialogue: The Cheating Suspect Conversation",
            "Your partner has been evasive and groomed. Practice the conversation that investigates without accusing: state the observed pattern ('I've noticed you're more protective of your phone'), invite explanation, watch the response (relief vs. attack), and decide the next step from their reaction.",
            "A dinner table at dusk; the conversation choices branch: ACCUSE, SULK, OBSERVE AND ASK. The accused's avatar reacts differently to each - rage, tears, or openness.",
            [
                "State patterns, not verdicts",
                "'I've noticed' opens; 'I know you're lying' closes",
                "Defensive rage is a possible deception signal",
                "Relief to talk suggests stress, not necessarily an affair",
                "Innocent partners offer explanations and openness",
                "Guilty partners deflect, minimize, or counter-accuse",
                "Your own fears color the reading - SCAN yourself first",
                "The goal is truth, not victory",
            ],
        ),
        "audit": (
            "Audit: Deception Evidence Log",
            "Track suspicion evidence for two weeks instead of acting on it: each observation (time, behavior, explanation given), consistency across retellings, and innocent alternatives. Grade the evidence: rumor, pattern, or cluster - and note what would confirm or clear the suspicion.",
            "A case file with evidence envelopes; each observation is filed and stamped RUMOR, PATTERN, or CLUSTER. Empty envelopes labeled INNOCENT EXPLANATION wait beside each.",
            [
                "Evidence = dated observations with explanations",
                "Story consistency across retellings is a strong test",
                "Rumors are not evidence",
                "Patterns need time; clusters need corroboration",
                "Innocent explanations must be genuinely considered",
                "Recording prevents emotional inflation of facts",
                "A clear head writes the log; a hurt heart writes the narrative",
                "Resolution needs evidence you can present calmly",
            ],
        ),
        "matrix": (
            "Matrix: Suspicion Cue x Stage x Interpretation",
            "Map 10 cues (grooming change, late work, phone guarding, new friends, money secrecy, intimacy drop, defensiveness, guilt gifts, distance, criticism) against 3 relationship stages (new, established, long-term) and rate each as noise, watch, or alarm - with the right conversation for each cell.",
            "A 10x3 grid where cells glow gray (noise), amber (watch), or red (alarm). Clicking a cell reveals the recommended conversation opener.",
            [
                "Grooming change in a new relationship = normal maintenance",
                "Phone guarding in long-term = higher concern than early",
                "Guilt gifts after distance = possible compensation signal",
                "Money secrecy is its own red flag, separate from infidelity",
                "Late work alone = noise; with evasiveness = watch",
                "Criticism spikes can precede a breakup, not just an affair",
                "Stage sets the baseline; patterns set the alarm",
                "Every alarm cell has a conversation attached",
            ],
        ),
        "boss": (
            "Boss Battle: The Accusation Reversal",
            "You accused your partner of cheating on the evidence of a grooming change and phone guarding - and you were wrong: they were organizing your surprise party. Repair the trust damage: own the error, explain the cluster fallacy, and rebuild a protocol for future suspicion that starts with questions, not verdicts.",
            "A party pops into view; your accusation speech replays over it. You must rewind your words, apologize with specifics, and pin a new protocol on the wall: ASK FIRST.",
            [
                "A wrong accusation is a real betrayal of trust",
                "Clusters can have innocent explanations (surprises, stress)",
                "Owning the error specifically is the only repair",
                "'I was scared' explains; it doesn't excuse",
                "A future protocol: ask, then verify, then conclude",
                "Apologies need behavior change, not just words",
                "Rebuilding trust takes repeated safety",
                "The relationship survived because they chose honesty over rage",
            ],
        ),
    },
    {
        "num": 14,
        "title": "Definitely into My Friend",
        "pages": "75-77",
        "domain": DD,
        "scrub": (
            "Cue Scrubber: Attraction-to-a-Friend Scanner",
            "Analyze 8 scenarios where a partner lights up around a friend: pupil dilation, mutual gaze duration, touch frequency, laughter, and priority shifts. For each, separate attraction signals from friendly warmth - and flag the difference between noticing and accusing.",
            "A dinner scene with a three-way gaze tracker; dilated pupils and long mutual gazes draw glowing lines between two figures. A filter labeled FRIENDLY WARMTH dims the innocent lines.",
            [
                "Pupil dilation marks interest - Binetti's gaze-duration research",
                "Mutual gaze length tracks attraction",
                "Touch frequency and placement separate friend from lover",
                "Laughter at everything they say can be performance or chemistry",
                "Priority shifts (canceling you for them) matter most",
                "Noticing attraction is not proof of action",
                "Jealousy amplifies every warm glance - check the base rate",
                "The cluster, not the smile, is the signal",
            ],
        ),
        "dialogue": (
            "Dialogue: The Friendly Spark",
            "Your partner seems brighter around your best friend: lingering looks, inside jokes, squeezed shoulders. Practice the calm conversation: state observations without accusation, invite their perspective, and set the boundary question - what would a respectful relationship look like to both of you?",
            "A living-room tableau where your partner and friend glow slightly brighter near each other; your dialogue options shift the glow or dissolve it - honesty resets the chemistry meter.",
            [
                "'I noticed you light up around Sam' is an observation, not a charge",
                "Invite their view before forming your verdict",
                "Friendly chemistry is real and not inherently a threat",
                "Boundaries ('I need us to prioritize our couple time') are fair",
                "Defensiveness invites a deeper look",
                "Openness rebuilds the safety that jealousy erodes",
                "Your fear of betrayal deserves words, not surveillance",
                "The relationship's rules get negotiated, not assumed",
            ],
        ),
        "audit": (
            "Audit: Cross-Friend Attraction Log",
            "Log one week of interactions between your partner and the friend in question: frequency of touch, gaze holds, private chats, priority shifts. Score the pattern against friendly norms and against attraction clusters - then decide what, if anything, needs a conversation.",
            "A social-graph view: two nodes brighten with each log entry; a friendly-warmth baseline line separates NORMAL from NOTEWORTHY.",
            [
                "Touch frequency and location are measurable",
                "Gaze holds over 4+ seconds are noteworthy",
                "Private chat volume and timing carry information",
                "Priority shifts (choosing them over you) are the strongest signal",
                "Compare against your partner's baseline with other friends",
                "One evening is noise; a week is data",
                "The log prevents both paranoia and denial",
                "Patterns earn conversations; moments don't",
            ],
        ),
        "matrix": (
            "Matrix: Attraction Signal x Target x Meaning",
            "Map 8 signals (prolonged gaze, touch, private jokes, priority, gift-giving, mirroring, disappearing, mood shifts) across targets (stranger, friend, ex, coworker) and rate whether the signal is warmth, attraction, or crossing a line in your relationship's framework.",
            "A 8x4 matrix; the same signal shifts meaning by target - a gift to a coworker reads differently than to an ex. Cells display your recommended conversation level.",
            [
                "Prolonged gaze at a friend = noteworthy; at a stranger = normal",
                "Touch at a coworker = warmth; at an ex = line-crossing",
                "Private jokes with a friend = friendship; with an ex = risk",
                "Priority shifts matter regardless of target",
                "Mirroring an ex signals unfinished business",
                "Gifts to a coworker = generosity or courtship, context decides",
                "The relationship's boundaries are the matrix frame",
                "Clear agreements turn gray cells into rules",
            ],
        ),
        "boss": (
            "Boss Battle: The Emotional Affair",
            "Your partner shares daily emotional life with a 'work spouse': secrets, moods, first news - while your own evenings are small talk. Decide: is this a threat? Have the conversation that names the pattern, invites rebalancing, and tests whether the friendship can coexist with the marriage.",
            "A seesaw: work-spouse intimacy tips the balance while your side rises empty. You must rebalance it with conversation weights, not accusations.",
            [
                "Emotional affairs often predate physical ones",
                "Sharing first news with them, not you, is the tell",
                "Secrecy (hidden chats) is the line-crossing marker",
                "Naming the pattern ('our intimacy moved') is fair",
                "Invite their view - the affair may be innocent closeness",
                "Rebalancing: date nights, shared news rituals, transparency",
                "A test: would they be comfortable with you reading the chats?",
                "The marriage deserves first news, not leftovers",
            ],
        ),
    },
    {
        "num": 15,
        "title": "A Match Made in Heaven?",
        "pages": "78-83",
        "domain": DD,
        "scrub": (
            "Cue Scrubber: Online Profile Truth Decoder",
            "Screen 10 dating profiles and separate performance from person: photo curation, bio exaggeration, height/age/income inflation, filter use, and group-shot ambiguity. Apply the research - deceptive self-presentation in online dating is common - and design the verification question for each.",
            "A row of dating profiles rendering as stage sets with curtains; a 'truth toggle' lifts each curtain to show the unposed reality behind it.",
            [
                "Online dating profiles are curated self-presentation",
                "Deceptive profiles inflate height, income, and interests",
                "Photos are performances: angles, filters, selection",
                "Group shots obscure who you're actually getting",
                "The bio is marketing copy, not a personality test",
                "Toma's research: deception is common and usually small",
                "Verification: video call, in-person meet, specific questions",
                "Disappointment comes from believing the performance",
            ],
        ),
        "dialogue": (
            "Dialogue: The Video Call Verification",
            "You matched with a profile that's almost too good. Run the verification dialogue: friendly video call, specific questions matching their bio claims, and observational checks (do they look like their photos? does the job story hold?). Decide before the date whether the person matches the profile.",
            "A video-call window where the profile's claims float beside the person: '6'2' vs. reality, 'loves hiking' vs. 'netflix at home'. Your questions shrink the gaps.",
            [
                "A video call verifies appearance and presence",
                "Specific questions test bio claims",
                "Consistency across channels is the test",
                "Flattery in profiles ('everyone's a foodie') is noise",
                "Inconsistency is a flag; one gap is not disqualifying",
                "The goal is calibration, not prosecution",
                "Meet in public; verify in the world",
                "Good profiles can be shy in person - context applies",
            ],
        ),
        "audit": (
            "Audit: Profile vs. Reality Log",
            "For 3 profiles you encounter, log: claimed traits, photo composition (angles, filters, groups), bio consistency, and red flags. Then design one verification question per profile and predict which claims would survive it.",
            "A comparison table: CLAIM | PHOTO EVIDENCE | VERIFICATION. Cells fill as you audit; honest profiles pass, performers accumulate red flags.",
            [
                "Claim-to-photo consistency is the first filter",
                "Group-shot-first profiles hide the person",
                "All-angle selfies can mask body presentation",
                "Bio specifics beat generic adjectives",
                "Age and height inflation are the most common lies",
                "Verification questions should be natural, not interrogations",
                "A pattern of small lies predicts bigger ones",
                "The audit makes you a better shopper, not a cynic",
            ],
        ),
        "matrix": (
            "Matrix: Profile Claim x Platform x Verification",
            "Map 10 claims (height, job, income, hobbies, relationship goals, photos, age, location, education, lifestyle) against 3 platforms (dating app, social media, professional network) and assign the verification method for each cell.",
            "A 10x3 verification grid; each cell holds a method: 'photo metadata', 'linkedin check', 'conversation probe', 'video call'.",
            [
                "Height claims: verify in person, never from photos",
                "Job claims: LinkedIn and conversational details",
                "Income claims: behavior over talk",
                "Hobby claims: specific questions ('where do you hike?')",
                "Relationship goals: conversation consistency over time",
                "Photos: reverse search and video calls",
                "Age: ID at the door, kindly",
                "Platform sets the expected honesty baseline",
            ],
        ),
        "boss": (
            "Boss Battle: The Two Candidates",
            "You're choosing between two matches: one with a modest profile and warm, consistent conversation; one with a stunning profile and rehearsed charm. Apply the compatibility framework - conflict style, responsiveness, consistency - and pick the better partner with the evidence to justify it.",
            "Two doors stand at the end of a corridor; behind each, a dossier of observed behavior. The choice must be defended with clusters, not sparks.",
            [
                "Consistency across time beats charisma in a day",
                "Conflict style predicts long-term compatibility",
                "Responsiveness (interest in your life) is a top predictor",
                "Rehearsed charm may be scripted courtship",
                "Modest profiles can hold genuine people",
                "A General Theory of Love: limbic resonance builds slowly",
                "Sparks are real but thin; patterns are durable",
                "Choose the person you can disagree with well",
            ],
        ),
    },
    {
        "num": 16,
        "title": "They Are So Breaking Up!",
        "pages": "84-89",
        "domain": DD,
        "scrub": (
            "Cue Scrubber: Breakup Cluster Scanner",
            "Screen 10 relationship moments for breakup signals: micro-momentary expressions of contempt, indifference replacing anger, future-planning silence, affection drop, and withdrawal from conflict. Distinguish a rough patch from the endgame cluster.",
            "A relationship vital-signs monitor: heart lines for affection, anger, and planning. The endgame signature - flat indifference - draws itself in red.",
            [
                "Micro-momentary expressions leak true feeling - Haggard and Isaacs",
                "Contempt is the heaviest relationship signal (Gottman, Ekman)",
                "Indifference beats anger as an endgame sign",
                "Future planning stops when the future is doubted",
                "Affection becomes perfunctory before the end",
                "Withdrawal from conflict = they've stopped trying",
                "Thin slices (Blink) read relationship health quickly",
                "One bad week is a patch; the cluster is the ending",
            ],
        ),
        "dialogue": (
            "Dialogue: The 'We Need to Talk'",
            "The phrase has come. Practice the hard conversation: stay descriptive, ask the real question ('are we over?'), avoid bargaining, and gather the information you need to plan - while protecting your dignity and the relationship's history.",
            "A still kitchen scene; the words 'We need to talk' hang in the air. Your dialogue choices decide whether you leave with clarity or with fog.",
            [
                "Ask the direct question; vagueness prolongs pain",
                "Describe, don't plead - 'I've noticed you pulling away'",
                "Bargaining ('I can change') rarely reverses the end",
                "Listen for the core reason; you'll need it to heal",
                "Dignity now protects your future self",
                "Grief is the price of having loved - it's normal",
                "Closure comes from information, not from winning",
                "The relationship's history deserves an honest ending",
            ],
        ),
        "audit": (
            "Audit: Relationship Vital Sign Log",
            "Track your relationship's vital signs for 3 weeks: affection frequency, conflict repair success, future-talk, interest in each other's days, and anger vs. indifference. Plot the trend and honestly classify: patch, decline, or endgame.",
            "A medical-style chart with five trend lines; the diagnosis appears only after the data - 'rough patch, treatable' or 'flatline cluster'.",
            [
                "Affection frequency is measurable",
                "Repair after conflict is the health indicator",
                "Future-talk marks commitment",
                "Interest in each other's days marks connection",
                "Indifference is a more final sign than anger",
                "Trends beat snapshots",
                "Logging forces honesty with yourself",
                "The classification determines the effort you invest",
            ],
        ),
        "matrix": (
            "Matrix: Endgame Signal x Stage x Certainty",
            "Map 10 signals (silence, no future-talk, criticism, affection drop, contempt, distraction, 'fine' answers, avoidance, new interests without you, relief) against 3 stages (dating, engaged, married) and rate each signal's endgame certainty plus the conversation it warrants.",
            "A 10x3 certainty matrix; high-certainty cells glow red, low ones gray. Each cell lists the proportionate conversation: OBSERVE, ASK, OR ACT.",
            [
                "Contempt: near-certain endgame predictor at any stage",
                "'Fine' answers with flat affect = withdrawal",
                "Relief at your absence is a loud signal",
                "New interests built without you mark parallel lives",
                "Silence in dating = fade; in marriage = a talk needed",
                "Criticism spikes can precede the end",
                "Stage changes speed, not direction",
                "Act on clusters, converse on single signals",
            ],
        ),
        "boss": (
            "Boss Battle: The Indifferent Partner",
            "Your partner is calm, kind, and gone: no conflict, no plans, no spark - the indifference cluster. Run the final protocol: name the pattern, ask the direct question, refuse to chase, and take the information into your own planning for whatever comes.",
            "A quiet apartment at evening; your partner smiles warmly at nothing. You must read the flatline and make the courageous call with clarity.",
            [
                "Indifference is the exit dressed as peace",
                "Kind distance is still distance",
                "Naming the pattern invites honesty",
                "Chasing re-engages the drama, not the love",
                "The direct question deserves a direct answer",
                "Your planning starts at their answer, not before",
                "Dignity is the asset you keep",
                "Endings free the space for real next chapters",
            ],
        ),
    },
    {
        "num": 17,
        "title": "Thick as Thieves",
        "pages": "90-94",
        "domain": FF,
        "scrub": (
            "Cue Scrubber: Trust Bond Scanner",
            "Scan 10 friendship moments and classify the bond strength: confidentiality, secret-keeping, matching gestures, inside jokes, mutual aid, and loyalty under pressure. Apply Gambetta's lens - trust is built through costly signals and rituals - and rank each bond.",
            "A vault door labeled TRUST; each costly signal (shared secret, midnight ride, honest criticism) turns a dial. The vault opens only at full bond strength.",
            [
                "Trust is built through costly, hard-to-fake signals",
                "Shared secrets are trust rituals - Gambetta's criminal codes",
                "Inside jokes and matching gestures mark deep attunement",
                "Confidentiality under temptation is the real test",
                "Mutual aid without ledger-keeping = thick bond",
                "Loyalty under pressure separates thieves from friends",
                "Trust signals must be observed over time, not claimed",
                "Criminals know trust; friends can learn from their rigor",
            ],
        ),
        "dialogue": (
            "Dialogue: The Secret-Keeper's Test",
            "Your friend confides a secret and swears you to silence. A mutual friend probes you with a tempting question. Practice the dialogue: deflect without lying, protect the confidence, and strengthen the bond by proving your discretion - then decide what you'd reasonably expect in return.",
            "A candlelit conversation; a probe question hangs like a lockpick. Your answer either holds the vault or cracks the code - the friend's trust bar rises or falls.",
            [
                "Discretion is the cheapest costly signal - and the most tested",
                "Deflecting ('can't say, even to you') beats lying",
                "A trust leak is rarely forgiven",
                "Protecting their secret protects your reputation",
                "Reciprocity expects: they'd keep yours too",
                "Secret-keeping has limits (harm, legality) - know yours",
                "The bond grows with each test passed",
                "Trust is built in drops and lost in buckets",
            ],
        ),
        "audit": (
            "Audit: Friendship Trust Ritual Log",
            "Map your friendships for one week: what rituals exist (regular calls, shared meals, secret-sharing, aid)? Which bonds have costly signals behind them and which are convenience-based? Grade each friendship's trust level with evidence.",
            "A constellation map; each friend is a node, each ritual a connecting line that brightens with cost. Convenience friendships flicker dim.",
            [
                "Rituals (regular contact, shared activities) maintain bonds",
                "Costly signals: crisis aid, honest criticism, discretion",
                "Convenience friends share fun, not burdens",
                "Ritual frequency correlates with bond strength",
                "A bond without any costly signal is thin",
                "Reciprocity is the bond's metabolism",
                "The map shows where to invest and where to accept",
                "Different friends serve different roles - that's fine",
            ],
        ),
        "matrix": (
            "Matrix: Trust Signal x Relationship x Strength",
            "Map 8 signals (secret-sharing, crisis aid, honest criticism, borrowing money, visiting, discretion, matching, inside jokes) across 3 relationships (new friend, close friend, best friend) and rate the signal's trust value in each cell.",
            "A 8x3 trust matrix; cells glow brighter with signal cost. New-friend columns stay dim - trust needs time and proof.",
            [
                "Secret-sharing with a new friend = fast bond or fast risk",
                "Crisis aid from a close friend = strong proof",
                "Honest criticism from a best friend = the deepest signal",
                "Borrowing money early = test or trap, context decides",
                "Visiting during hard times beats texting during good ones",
                "Discretion earns trust at every level",
                "Inside jokes signal shared history",
                "Costly signals are the currency of depth",
            ],
        ),
        "boss": (
            "Boss Battle: The Leaked Secret",
            "Your secret came back to you from someone else's mouth, and you have two suspects: a casual acquaintance who overheard and a close friend who knew. Investigate with SCAN: gather versions, test each suspect's reaction, and deliver the verdict - friendship intact or bond severed - with evidence.",
            "A rumor spreads through a party like ripples; you must trace each ripple to its source while the two suspects give different body-language testimony.",
            [
                "Trace the leak's route before accusing",
                "The overhearer leaks accidentally; the friend leaks by choice",
                "Inconsistent retellings identify the source",
                "Test reactions: denial with detail vs. denial with evasion",
                "An accidental leak costs trust, not the friendship",
                "A deliberate leak is a different animal",
                "Confront the behavior, not the person's soul",
                "Rebuilding after a leak requires new protocols",
            ],
        ),
    },
    {
        "num": 18,
        "title": "My New Bff?",
        "pages": "95-98",
        "domain": FF,
        "scrub": (
            "Cue Scrubber: Fast Friendship Scanner",
            "Screen 10 new-friendship behaviors: rapid intimacy, gifts too early, constant availability, mirroring enthusiasm, and immediate 'best friend' claims. Distinguish genuine chemistry from neediness, charm, or performance - using pacing and reciprocity as the test.",
            "A friendship rocket launches too fast; a gauge labeled PACE flashes red while a second gauge, RECIPROCITY, stays low. The scanner asks: speed or substance?",
            [
                "Fast friendships promise fast intimacy - and fast collapse",
                "Gifts and praise too early may be charm tactics",
                "Immediate 'best friend' claims outpace evidence",
                "Constant availability can mask neediness",
                "Charisma is a skill, not a bond (Levine's research)",
                "Healthy bonding escalates gradually with reciprocity",
                "Mood swings can masquerade as intense connection",
                "Pacing is the price of authenticity",
            ],
        ),
        "dialogue": (
            "Dialogue: The Week-One Best Friend",
            "You met someone great - they already call you their best friend, plan weekends, and share their deepest traumas. Practice the gentle pacing conversation: reciprocate warmth without matching speed, set sustainable boundaries, and watch whether the friendship can breathe at a normal rate.",
            "A sprinter and a walker on the same trail; you must keep pace sustainable while the sprinter waves you to run. The trail ahead shows what each pace preserves.",
            [
                "Match warmth, not speed",
                "'I'm glad we met; I like to take things at a steady pace' works",
                "Rapid trauma-sharing can be bonding or boundary-testing",
                "Boundaries now prevent resentment later",
                "Watch the reaction to your pacing - respect or pressure",
                "Genuine friends adjust; performers escalate",
                "Sustainable friendships survive normal life",
                "Slow trust is real trust",
            ],
        ),
        "audit": (
            "Audit: Friendship Pace Log",
            "Log the first 3 weeks of a new friendship: who initiates, escalation rate (intimacy, gifts, plans), reciprocity of sharing, and boundary responses. Classify the trajectory: healthy ramp, one-sided pursuit, or intensity overload.",
            "A flight-data recorder plots the friendship's altitude and speed; steep climbs flash warning, steady ramps glow green.",
            [
                "Initiation ratio measures mutual interest",
                "Escalation rate beyond reciprocation = imbalance",
                "Sharing should be mutual, not a monologue",
                "Boundary responses reveal character",
                "Intensity overload usually ends in abrupt fade",
                "Steady ramps survive real-world schedules",
                "Logging prevents being swept up",
                "Trajectory, not the first week, predicts the friendship",
            ],
        ),
        "matrix": (
            "Matrix: Bonding Cue x Pace x Risk",
            "Map 8 cues (trauma-sharing, gifts, 'best friend' claims, constant texting, mirroring, emotional need, planning far ahead, jealousy of your others) against 3 paces (slow, normal, fast) and rate risk plus the response for each cell.",
            "A 8x3 pace matrix; fast columns flash amber and red, slow columns stay green. Each cell holds a calibrated response.",
            [
                "Trauma-sharing fast = bonding or testing, risk varies",
                "Gifts early at fast pace = possible charm investment",
                "'Best friend' claims before month one = overclaim",
                "Constant texting at any pace can be need or control",
                "Jealousy of your existing friends is a flag",
                "Far-ahead planning signals fantasy, not history",
                "Slow-to-normal pace minimizes most risks",
                "Response: match pace, set boundaries, observe",
            ],
        ),
        "boss": (
            "Boss Battle: The Intensity Crash",
            "Your new friend was a whirlwind for a month - then vanished. Reconstruct the pattern (love-bombing friendship, mood-driven intensity, boundary resistance), decide whether it's personality or neediness, and choose: reconnect with boundaries, or accept the short bright arc and move on.",
            "A firework trail: brilliant launch, brief bloom, dark ash. You must read the chemical composition - sparkle or stability - before deciding to relight.",
            [
                "Intensity without sustainability is a pattern",
                "Mood-driven friendships flare and fade",
                "Boundary resistance predicts the crash",
                "Reconnection needs new terms: steadier, slower",
                "Not every bright meeting becomes a bond",
                "The crash is information about them, not a verdict on you",
                "Healthy friendships survive silence",
                "Accepting the short arc is a legitimate choice",
            ],
        ),
    },
]
