# -*- coding: utf-8 -*-
"""Phase 2 chapter data for The Definitive Book of Body Language (Pease & Pease), chapters 8-11.
Each chapter: num, title, pages, domain, and 5 slots (scrub/dialogue/audit/matrix/boss),
each slot a 4-tuple (topic, player_mission, visual_frame_description, key_concepts[8-12]).
"""

D = "Body Language | Nonverbal Communication"

CHAPTERS = [
    {
        "num": 8,
        "title": "Eye Signals",
        "pages": "193-224",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Pupil Dilation Range",
            "Work through 14 close-up eye clips and tag each pupil state before the loop resets: dilated, constricted, beady, bedroom, or the instant of maximum dilation at the moment of a problem's solution. Lock your reading of what the pupil reveals - attraction, anger, arousal, or interest - then match each clip to the Hess experiment it belongs to, from opposite-sex pinups to mother-and-baby pictures.",
            "A dark portrait studio where only two enormous floating eyes fill the screen; the pupils slowly bloom or shrink like camera apertures, and you snap a verdict tag onto a dilation gauge running from 'beady' to 'four times its size' while the light level of each clip drops toward romantic-dim.",
            [
                "In given light conditions, pupils dilate or contract as attitude and mood change from positive to negative; excitement can dilate pupils to up to four times their original size",
                "An angry, negative mood contracts the pupils into what are commonly called 'beady little eyes' or 'snake eyes,' and lighter eyes look more attractive because the dilation is easier to see",
                "Eckhard Hess, pioneer of pupillometry at the University of Chicago, found that the pupils of heterosexual men and women dilate when viewing pinups of the opposite sex and constrict when viewing same-sex pinups",
                "Hess found increases in pupil size are positively correlated with mental activity in problem solving, reaching maximum dilation as a person arrives at the solution",
                "The Peases enlarged the pupil size of models in direct-mail photographs and helped increase the catalog sales of Revlon lipsticks by 45 percent",
                "Romantic encounters are most successful in dimly lit places because everyone's pupils dilate there, creating the impression that couples are interested in each other",
                "Men's pupils can dilate to almost three times their size watching pornographic films, while women's pupils gave their greatest dilation when looking at pictures of mothers and babies",
                "Young babies and children have larger pupils than adults, and babies' pupils constantly dilate when adults are present - which is why bestselling children's toys almost always have oversized pupils",
                "Pupil dilation is reciprocal: men looking at pictures of women with dilated pupils showed greater pupil dilation than when they looked at women with constricted pupils",
                "In Hess's five-picture test, men's pupils dilated most at the naked female, gay men's most at the naked male, but women's dilated most at the mother-and-baby picture, with the naked male second",
                "Expert card players won fewer games when their opponents wore dark glasses, because the glasses eliminated the pupil signals that unconsciously warned them not to bet",
                "Ancient Chinese gem traders watched for buyers' pupil dilation when negotiating prices, and prostitutes centuries ago used belladonna drops containing atropine to make themselves appear more desirable",
            ],
        ),
        "dialogue": (
            "Dialogue: The Two-Second Gaze Exchange",
            "Play the person at the far side of a room: read the other person's first gaze signal - held for two to three seconds, then dropped down - and respond at the correct time. Repeat your read-out up to three, four, or five times for the slowest decoders, then send the small Eyebrow Flash that confirms the signal was intended, and decide whether the face-to-face approach is the better play.",
            "A crowded party scene viewed from across the room; the gaze lands on you in a glowing two-to-three-second hold, a counter ticks down, and a small 'signal intended' flash lights the face the moment you get it right.",
            [
                "When a woman wants a man's attention across a room she meets his gaze, holds it for two to three seconds, then looks away and down",
                "Monika Moore's experiment showed most men are not hardwired to read a woman's first gaze signal, so she usually needs to repeat it three times before the average man picks it up",
                "Really slow men need the gaze repeated four times, and five or more times for the especially thick",
                "When she finally gets his attention she often gives a small version of the Eyebrow Flash - a subtle eye-widening gesture that tells him the signal was intended for him",
                "A simple face-to-face verbal approach of 'Hey, I like you!' can be more effective on men who are slow on the uptake",
                "Most primates avert their gaze to show submission, and an ape about to display aggression locks its eyes onto its victim",
                "Under attack we make ourselves appear smaller - hunching the shoulders, pulling arms in close, pressing knees together, locking the ankles, dropping the chin, averting the gaze - gestures that activate an off switch in the aggressor's brain",
                "The small-submission posture is ideal when being reprimanded by a superior who is in the right, but detrimental against a random street attack, where it signals fear and can incite the attack",
                "Walking upright with larger movements, swinging your arms and legs with your front open, projects that you could defend yourself and makes you less likely to be attacked",
                "The Sideways Glance communicates interest, uncertainty, or hostility: with slightly raised eyebrows or a smile it is a courtship signal used frequently by women",
                "Clustered with down-turned eyebrows, a furrowed brow, or down-turned mouth corners, the Sideways Glance signals a suspicious, hostile, or critical attitude",
            ],
        ),
        "audit": (
            "Audit: The Liar's Gaze Autopsy",
            "Replay the staged recorded interviews of liars the way the Peases' seminar audiences did and judge who is lying: flag the 30 percent who constantly look away, then catch the 70 percent who maintain strong eye contact to look convincing. Tally your catch rate against the research figures - 80 percent for the look-away liars, 25 percent for the eye-contact liars - and log the voice and pupil cues that give the rest away.",
            "A video wall of split-screen interview recordings; each witness's gaze track draws a line across the screen showing exactly when their eyes left the interviewer, while a lie-detection scoreboard tallies your hits against the expected catch rates.",
            [
                "In the Peases' experiments approximately 30 percent of liars constantly looked away when they lied, and viewers spotted these lies around 80 percent of the time, with women having a better catch rate than men",
                "The other 70 percent of liars maintained strong eye contact with their victim, assuming they were less likely to get caught if they did the opposite of what people expected - and they were right",
                "Lie-catching on the strong-eye-contact liars dropped to an average of 25 percent, with men scoring a dismal 15 percent success and women 35 percent",
                "Women's more intuitive brains were better than men's at detecting voice changes, pupil dilation, and other cues that gave the liar away",
                "Gaze alone is not a reliable signal of lying - you need to observe other gestures as well",
                "When a person's gaze meets yours for more than two thirds of the time it means one of two things: he finds you interesting or appealing, in which case he'll also have dilated pupils, or he's hostile and issuing a challenge, in which case the pupils will be constricted",
                "Women are good at deciphering pupil signals and can differentiate interest from aggression, but men are significantly worse - which is why the average man can't tell if a woman is about to give him a kiss or a slap",
                "A normal, relaxed blinking rate is six to eight blinks per minute with the eyes closed only about one tenth of a second; people under pressure, such as when lying, dramatically increase their blinking rate",
                "Extended Blinking - eyes shut for two to three seconds or longer - is the brain's unconscious attempt to block you from sight because the person is bored, disinterested, or feels superior",
                "The 'long look' with head tilted back, looking down one's nose, is mainly a Western cultural gesture and a specialty of English people who feel they are upper class",
                "When the eyes dart from side to side the brain is searching for escape routes, revealing a person's insecurity about what is happening",
                "With a boring individual we look more at him and use a Tight-Lipped Smile to feign interest, just as liars increase their eye contact to appear convincing",
            ],
        ),
        "matrix": (
            "Matrix: Gaze Zone x Encounter x Outcome Grid",
            "Fill the three-axis grid mapping the three gaze zones - Social, Intimate, and Power - against encounters (reprimand, courtship, sales pitch, interview) and score the outcome each match produces: the reprimand that loses its sting under Social Gazing, the courtship advance an Intimate Gaze gives away, the bore stopped dead by the Power Gaze. Complete the cells before the face-map timer runs out, and never drop below the level of their eyes.",
            "A holographic face splits into three glowing triangles - eyes to mouth, eyes to chest, and the third eye on the forehead - while a decision grid lights green or red for every zone-and-encounter pairing you lock in.",
            [
                "There are three basic types of gazing: Social Gazing, Intimate Gazing, and Power Gazing",
                "In social encounters the gazer's eyes look in a triangular area between the eyes and the mouth for about 90 percent of the gaze time, and the other person perceives you as nonaggressive",
                "The Intimate Gaze covers the triangular area between the eyes and the chest in close encounters, and from the eyes to the groin or below for distant gazing",
                "Hidden camera studies reveal that everyone gives two quick glances at the body when approaching from a distance - despite strong denials, including nuns",
                "Women's peripheral vision extends at least forty-five degrees to each side, above and below, letting them check out a man from head to toe without getting caught, while men's tunnel vision means they keep getting caught ogling",
                "Looking down during conversation lets a man give a woman the once-over; for a woman it has the dual purpose of checking him out and sending the submissive look-away-and-down signal",
                "The Power Gaze imagines a third eye in the center of the person's forehead and looks in a triangular area between the 'three' eyes, changing the atmosphere to very serious and stopping a bore dead in his tracks",
                "Provided the Power Gaze never drops below the level of their eyes, the pressure stays on; it should never be used in friendly or romantic encounters",
                "The Power Stare: don't blink while maintaining eye contact, narrow your eyelids, and focus closely - move the eyeballs first, then let the head follow with the shoulders still, as Arnold Schwarzenegger used as The Terminator",
                "For a reprimand, Social Gazing takes the sting out of your words, Intimate Gazing can intimidate or embarrass, and Power Gazing tells the receiver you mean business",
                "The 'come-on' look men describe relates to a sideways glance, dilated pupils, and Intimate Gazing; a woman playing hard to get avoids the Intimate Gaze and uses Social Gazing instead",
                "Women are expert at sending and receiving the Intimate Gaze, but most men are not - men are generally unaware of having been given an Intimate Gaze, much to the woman's frustration",
            ],
        ),
        "boss": (
            "Boss: The Interview Gaze Gauntlet",
            "Run the timed gauntlet through the first twenty seconds of a job interview: shake hands, then give the interviewer a two-to-three-second frame of uninterrupted time to look you over, and find the natural task - opening the briefcase, arranging papers, moving the chair - that lets you look down without losing credibility. Then survive the presentation round: lift the pen from the visual aid up to between your eyes and hold the audience with pegged corner points before the clock expires.",
            "A boardroom straight out of the Peases' filming set: a handshake freezes for a two-second countdown, the candidate drops her gaze to a briefcase while the interviewer's eyes roam her appearance, and a teleprompter clock ticks down the 20 seconds.",
            [
                "Being taught to maintain strong eye contact in an interview until you are seated creates problems, because it contradicts the natural evaluation process we go through when meeting someone new",
                "Hidden cameras show men want to check a woman's hair, legs, body shape, and overall presentation, and strong eye contact leaves them stealing glances and getting distracted from the job of interviewing",
                "Women interviewers run the same evaluation process on both male and female interviewees, but their wider peripheral vision means they rarely get caught",
                "Women look at a male candidate's hair length, clothes design, and coordination, the creases in his trousers, and the shine on his shoes - and at the backs of his shoes as he walks out",
                "The solution: shake hands, then give the interviewer a two-to-three-second frame of uninterrupted time to complete the process of looking you over",
                "Use that frame to look down while opening your briefcase, arranging papers, hanging up your coat, or moving your chair in closer, then look up",
                "Filmed sales interviews showed the strategy made interviews feel better for the salespeople and added up to a better outcome in sales results",
                "A politician client who constantly flicked his eyes between reporters and cameras looked shifty-eyed and lost popularity each appearance; training him to look only at the reporter restored his credibility",
                "Another politician addressed his answers mainly to the camera lens, alienating the 150 studio guests but impressing millions of viewers who felt he was talking directly to them",
                "In the dating-agency 'problem eye' experiment, couples who spent the evening searching for a nonexistent lazy eye reported high intimacy and were 200 percent more likely to go on a second date",
                "The Power Lift: point with a pen at the presentation while verbalizing it, then lift the pen to between the other person's eyes and yours - it magnetically lifts his head so he sees and hears you, achieving maximum absorption",
                "The Wharton study found 10 percent retention for verbal presentations but 50 percent for combined verbal and visual presentations - a 400 percent increase in efficiency - and visual aids cut average meeting time from 25.7 minutes to 18.6 minutes",
            ],
        ),
    },
    {
        "num": 9,
        "title": "Space Invaders - Territories and Personal Space",
        "pages": "225-242",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Four Zone Distances",
            "Work through 15 short clips of two people facing each other and tag the zone distance in play before the clip loops: the Intimate Zone at six to eighteen inches, the Personal Zone at eighteen inches to four feet, the Social Zone at four to twelve feet, or the Public Zone beyond twelve feet. Then judge the intrusion - close relative, sexual advance, or imminent attack - and predict the physiological response it triggers.",
            "A white studio floor painted with four glowing concentric rings; each clip drops two avatars into the rings at their measured distance and you pin the zone label onto the gap between them while a vital-signs readout shows heart rate and adrenaline spiking on intrusion.",
            [
                "American anthropologist Edward Hall was a pioneer in the study of man's spatial needs and coined the word 'proxemics' in the early 1960s",
                "Each person carries his own personal portable air bubble, whose size depends on the density of the population in the place where he grew up - so Personal Space is culturally determined",
                "A lion raised in the remote regions of Africa may have a territorial space with a radius of thirty miles, while one raised in captivity has a personal space of only several yards",
                "Prisoners appear to have larger personal space needs than most of the community, making them constantly aggressive when approached; solitary confinement has a calming effect",
                "Violence from passengers on aircraft increased during the 1990s when airlines started packing people close together to compensate for revenue lost to price discounting",
                "The Intimate Zone runs from six to eighteen inches - by far the most important zone, guarded like property - with a subzone up to six inches enterable only during intimate physical contact",
                "The Personal Zone runs from eighteen inches to four feet, the distance we stand from others at cocktail parties, office parties, social functions, and friendly gatherings",
                "The Social Zone runs from four to twelve feet, the distance for strangers, the plumber, the postman, the local shopkeeper, and new employees; the Public Zone is over twelve feet",
                "All these distances tend to reduce between two women and increase between two men",
                "Intrusion by a stranger into the Intimate Zone makes the heart pump faster, pours adrenaline into the bloodstream, and pumps blood to the brain and muscles as fight-or-flight preparation",
                "The golden rule to make people comfortable is 'keep your distance' - a new employee may feel others are cold, but they are keeping him in the Social Zone until he is better known",
                "Lovers press their torsos together within each other's close Intimate Zones, while a New Year's Eve kiss from a stranger, your best friend's spouse, or Aunt Sally keeps the pelvis at least six inches away",
            ],
        ),
        "dialogue": (
            "Dialogue: The Elevator Masking Challenge",
            "Ride a packed elevator and hold the six unwritten rules through every floor: no talking even to people you know, no eye contact at all times, a poker face with no emotion shown, pretended engrossment in a book or newspaper, no body movement, and eyes fixed on the floor numbers. Then repeat the ride in a crowded cinema and handle the armrest territory war with the stranger beside you without breaking the mask.",
            "A cramped elevator cabin seen from the ceiling, six commuters frozen in the ritual - faces blank, eyes on the glowing floor-number strip - while your avatar must hold every rule as the doors open and close on each landing.",
            [
                "The common elevator-riding rules: there will be no talking to anyone, including a person you know; avoid eye contact with others at all times; maintain a 'poker face' with no emotion shown",
                "If you have a book or newspaper, pretend to be deeply engrossed in it; in bigger crowds no body movement is allowed, and you must watch the floor numbers change at all times",
                "This behavior is called 'masking' - each person's attempt to hide their emotions from others by wearing a neutral mask",
                "The blank, expressionless look of rush-hour commuters is misjudged as misery, but they are actually masking - adhering to the rules that apply to the unavoidable invasion of their Intimate Zones",
                "In a crowded public place the people around you become nonpersons - they don't exist as far as you're concerned - so you don't respond as if attacked when someone inadvertently encroaches on your territory",
                "Those who often go to a crowded cinema alone do not take their seats until the lights are out and the film begins",
                "An angry mob does not react like an individual: as crowd density increases, each person has less personal space and feels hostile, so the bigger the mob the angrier it gets, and police break crowds up to let each person regain space",
                "The deer population on James Island in Chesapeake Bay died from overactive adrenal glands - stress from the degradation of each deer's personal territory as the population increased, not starvation, infection, or predators",
                "Areas that have the highest human population density also have the highest crime and violence rates",
                "Interrogators seat criminals on an armless, fixed chair in an open area of the room and encroach into their Intimate Zones when asking questions, remaining there until the criminal answers",
                "The spacing ritual: when claiming a seat at the cinema, a conference table place, or a towel hook, people look for the widest space available between two others and claim the center, midway between them",
                "People choose the end toilets about 90 percent of the time, and men obey the unwritten law of 'Death before eye contact' at public urinals",
            ],
        ),
        "audit": (
            "Audit: The Cultural Space-Attack Autopsy",
            "Audit the case of the Italian couple who migrated to Sydney and were accused of sexual advances: replay the club scene, timestamp each spatial breach - the ten-inch conversational distance against the Australians' eighteen-inch Intimate Zone, the extra eye contact, the extra touch - and prescribe the fix. Then replay the Japanese-and-American conversation at double speed and confirm who leads the waltz around the room.",
            "A split-screen club scene with distance overlays drawn between the couple and the Australian members; a timeline marks each moment the ten-inch gap breached the eighteen-inch line, while a fast-forwarded overhead map traces the Japanese waltz spiraling across the floor.",
            [
                "Three female members complained that the Italian man was making sexual advances toward them, and the male members felt the Italian woman was behaving as if sexually available",
                "Many Southern Europeans have an intimate distance of only eight to eleven inches, and the Italian couple felt at ease at ten inches from the Australians, unaware of intruding on their eighteen-inch Intimate Zone",
                "Italians use more eye contact and touch than Australians, which gave rise to further misjudgments about their motives",
                "Moving into the Intimate Zone of the opposite sex is a way of showing interest in that person and is commonly called an 'advance'",
                "If the advance is rejected, the other person steps backward to reclaim their space; if accepted, the other person holds his ground and allows the intruder to remain",
                "To measure a man's level of interest, a woman steps into his Intimate Zone and then steps back out again, cueing him to step into her space whenever he makes a point",
                "At the Peases' international conferences, city-born Americans stand eighteen to forty-eight inches apart and stay in the same place while talking",
                "A Japanese and an American talking will slowly circle the room - the American backing away, the Japanese stepping forward - and high-speed video replay makes it look like a waltz with the Japanese leading",
                "The Japanese, with his smaller ten-inch Intimate Zone, continually steps forward and invades the American's zone, which is why Asians are called 'pushy' and 'familiar' while Europeans and Americans are called 'cold' and 'standoffish'",
                "A man from a culture with a smaller Personal Zone moves forward to his comfortable distance while the woman leans backward to defend hers, and she may interpret the approach as a sexual move",
            ],
        ),
        "matrix": (
            "Matrix: Origin x Bubble Size x Handshake Grid",
            "Fill the grid matching a person's upbringing - city street, country town, or remote outback - to the size of their personal space bubble and the handshake that fits it: the city dweller's eighteen-inch wrist-to-torso reach, the country person's thirty-six inches, or the remote dweller who prefers a distant wave at up to eighteen feet. Then apply the test to the farming-equipment sales call and choose the greeting that won't read as a territorial intrusion.",
            "A map of a continent scales from city blocks to open farmland; each origin marker drops a numbered bubble around the avatar, and a handshake reach animates wrist-to-torso as the correct greeting snaps into place on the matching grid.",
            [
                "People raised in sparsely populated rural areas need more Personal Space than those raised in densely populated cities",
                "Watching how far a person extends his arm to shake hands gives a clue to whether he is from a large city or a country area",
                "City dwellers typically have their private eighteen-inch bubble, also the measured distance between wrist and torso when they reach to shake hands - letting hands meet on neutral territory",
                "People raised in a country town with a small population may have a space bubble of up to thirty-six inches or more, the average measured wrist-to-body distance for the country handshake",
                "Rural people stand with their feet firmly planted and lean forward to meet your handshake, whereas a city dweller steps forward to greet you",
                "People raised in remote areas can need as much as eighteen feet of space and often prefer not to shake hands, standing at a distance and waving instead",
                "A farmer could have a bubble of three to six feet or more, so a handshake could be seen as a territorial intrusion, causing a negative or defensive reaction",
                "Successful country salespeople greet the rural customer with an extended handshake and the farmer from a remote area with a distant wave - the best negotiating conditions",
            ],
        ),
        "boss": (
            "Boss: The Territory Defense Gauntlet",
            "Face the timed gauntlet defending a territory: spot the encroaching visitor before he takes the boss's favorite chair, run the Luncheon Test by sliding the salt cellar onto your lunchmate's side and reading whether he sits back or pushes everything back to the center, and manage the car-territory round where a cut-in driver triggers road rage while the same intrusion in an elevator reads as apologetic. Hold your boundaries until the summary clock expires.",
            "A dining table seen from above: salt, pepper, sugar, and flowers march across the center line in sequence while your lunchmate's reaction meter swings between 'sits back' and 'pushes it all back'; behind it a highway scene shows the same driver's rage switch flipping.",
            [
                "Unspoken territorial rules divide a restaurant table equally down the middle, with the salt, pepper, sugar, flowers, and other accessories placed on the center line",
                "In the Luncheon Test, subtly moving the salt cellar across to the other person's side causes them to sit back to regain their space or start pushing everything back to the center",
                "Property a person owns or a space he regularly uses is private territory - home, office, car, kitchen, favorite conference-table place, and favorite chair - marked by possessions left on or around the area or by frequent use",
                "Desmond Morris's studies of library seating showed a book or personal object left on a desk reserved the place for an average of seventy-seven minutes, and a jacket over a chair reserved it for two hours",
                "If the boss of the house asks a visitor to be seated and the person innocently sits in the wrong chair, the boss becomes agitated and defensive - asking 'Which chair is yours?' avoids the territorial error",
                "A motor vehicle magnifies the size of a person's Personal Space, in some cases up to ten times, giving the driver a claim to an area of twenty-five to thirty feet in front of and behind the car",
                "Another driver cutting in front can trigger anger and even attack - 'Road Rage' - while the same person stepping into an elevator lets another step in front of him apologetically",
                "For some people the car becomes a protective cocoon in which they hide from the outside world, making intimate adjustments in full view of everyone",
                "Italians, with their smaller spatial needs, are often accused of being tailgaters and pushy on the motorways because they drive closer than is culturally accepted elsewhere",
                "A short spatial distance between two people can mean city dwellers with an intimate approach, a man with a smaller Intimate Zone innocently invading, a cultural difference, or emotional closeness - consider every criterion before judging",
            ],
        ),
    },
    {
        "num": 10,
        "title": "How the Legs Reveal What the Mind Wants to Do",
        "pages": "243-263",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Four Standing Positions",
            "Work through 14 clips of standing figures and tag the stance before the clip loops: At Attention with the 'No Comment' legs-together, the Legs-Apart Crotch Display, the Foot-Forward pointing where the mind wants to go, and the defensive Standing-Leg-Cross. Then read the group logic - who stands farther apart with buttoned coats, who uncrosses first when rapport builds - and predict where each person's feet are pointing by the end of the scene.",
            "A gesture-capture grid where four standing mannequins hold the four positions in glowing wireframe; each clip drops a figure onto the grid and you slam the stance label onto its feet while a compass arrow shows where the lead foot is pointing.",
            [
                "The farther away from the brain a body part is positioned, the less awareness we have of what it is doing - we are least aware of our legs and almost oblivious to our feet",
                "A person can look composed and in control while their foot repetitively taps or makes short jabs in the air, revealing frustration at not being able to escape - jiggling the feet is like the brain trying to run away",
                "At Attention is a formal position showing a neutral attitude with no commitment to stay or go, used by schoolchildren to teachers, junior officers to senior officers, people meeting royalty, and employees to the boss",
                "Legs Apart is predominantly a male gesture like a standing Crotch Display: the feet planted firmly declare no intention of leaving and highlight the genitals as a dominance signal",
                "Sports spectators stand in the Crotch Display at halftime giving their crotch continual adjustments - not from itching but to highlight masculinity and show solidarity as a team",
                "The Foot-Forward position shifts the body weight to one hip, leaving the front foot pointing forward, as painted in the Middle Ages when high-status men displayed their hosiery, shoes, and breeches",
                "We point our lead foot in the direction our mind would like to go: at the most interesting or attractive person in a group, or at the nearest exit when we want to leave",
                "The Standing-Leg-Cross appears among people who don't know each other well, standing at greater than customary social distance with coats or jackets buttoned",
                "Crossed legs show a closed, submissive, or defensive attitude because they symbolically deny access to the genitals; the Scissors position says 'No comment' but he's not leaving",
                "Open legs display masculinity; closed legs protect it - the Crotch Display feels right among men he feels are inferior but vulnerable among superior males",
                "In the closed-to-open sequence, the legs uncross first with feet placed together at Attention, then the folded arm comes out, palms flash, arms unfold, and finally one person takes the Foot-Forward position of acceptance",
            ],
        ),
        "dialogue": (
            "Dialogue: The Ankle Lock Interrogation",
            "Run the debt-collector interview both ways: watch the collector lock his ankles under his chair while his voice sounds relaxed on the phone, then ask 'Are you sure?' until he unlocks, opens his palms, and admits the work drives him crazy. Then switch roles as the interviewer: use positive questions about feelings, and walk around to the interviewee's side of the desk to remove the barrier and unlock the hidden concession.",
            "A phone-bank cubicle under a desk-cam view: ankles locked beneath the chair, the voice track reads 'Fine! It's a lot of fun' while a contradiction meter spikes, and the unlock moment triggers open palms in a burst of light.",
            [
                "When an interviewee locks his ankles he is mentally 'biting his lip,' holding back a negative emotion, uncertainty, or fear, with the feet usually withdrawn under the chair",
                "The male Ankle Lock often combines with clenched fists resting on the knees, hands tightly gripping the chair arms, and a seated Crotch Display",
                "The female version varies: the knees are held together, the feet may be to one side, and the hands rest side by side or one on top of the other on the upper legs",
                "Defendants sitting outside a courtroom just prior to a hearing were three times more likely than plaintiffs to have their ankles tightly locked under their chairs",
                "Of 319 dental patients studied, 88 percent locked their ankles as soon as they sat in the dental chair; 68 percent locked for a checkup versus 98 percent when the dentist administered an injection",
                "Work with police, customs, and tax office showed most people being interviewed lock their ankles at the beginning - just as likely from fear as from guilt",
                "Nierenberg and Calero found that when one party locked his ankles during a negotiation it often meant he was holding back a valuable concession",
                "In the initial stages of study, asking questions succeeded 42 percent of the time in getting interviewees to relax and unlock their ankles",
                "If the interviewer walks around to the interviewee's side of the desk, removing the desk as a barrier, the interviewee often relaxes and unlocks, and the conversation becomes open and personal",
                "The customer debt collector sounded relaxed but locked his ankles beneath his chair during calls, then admitted when asked 'Are you sure?' that the work actually 'drives me crazy'",
                "Salespeople who don't enjoy using the telephone commonly sit in the Ankle Lock position",
                "People who claim they sit in the Ankle Lock because they feel 'comfortable' should remember that any arm or leg position feels comfortable when you hold a defensive, negative, or reserved attitude",
            ],
        ),
        "audit": (
            "Audit: The Figure Four Debate Autopsy",
            "Audit the conference footage where the audience of one hundred managers and five hundred salespeople heard the controversial speaker: timestamp the moment almost all the male managers and around 25 percent of the female managers took the defensive Arms-and-Legs-Crossed position, then the orchestrated shift to the Figure Four when the manager's role came under debate, and flag the managers who couldn't shift for physical reasons. Prescribe the uncrossing countermoves for your own persuasion attempt.",
            "A conference hall in aerial view with audience avatars color-coded by posture: a defensive red sweep ripples across the managers' block, then an amber Figure Four wave replaces it in unison like an orchestra obeying a conductor.",
            [
                "The American Figure Four is a seated version of a Crotch Display that highlights the genitals, used by American males and Americanized youth of Singapore, Japan, and the Philippines",
                "The Figure Four shows an argumentative or competitive attitude, and during the Second World War the Nazis kept a lookout for it because anyone using it was clearly not German or had spent time in the U.S.A.",
                "The Figure Four is still uncommon among older people in Britain and Europe but now appears in Russia, Japan, Sardinia, and Malta among younger generations mirroring American films and television",
                "In parts of the Middle East and Asia the Figure Four is seen as an insult because it shows the sole of the shoe, the part that walks in dirt",
                "Monkeys and chimps use genital displays when aggressive because a good display can avoid the damage of a physical fight, and with all primates the male with the most impressive display is seen as the winner",
                "Women wearing trousers or jeans sometimes sit in the Figure Four, but usually only around other women, not men, so as not to appear too masculine",
                "Most people make most of their final decisions when both feet are on the ground, so the Figure Four is not conducive to asking someone to make a decision",
                "At the Peases' conference of about one hundred managers and five hundred salespeople, almost all the male managers and around 25 percent of the female managers crossed arms and legs when the salesperson took the stage",
                "When the speaker discussed the manager's role, most of the male managers shifted to the Figure Four as if commanded by an orchestra leader - they were mentally debating his point of view",
                "Some managers could not take the Figure Four for physical or medical reasons, such as being overweight, or having leg problems or arthritis",
                "To get a seated Figure Four or crossed-arms person to uncross: invite them to sit beside you, give them things to do or hold, or offer tea or coffee, which makes crossing arms and legs impossible without burning themselves",
                "The Figure Four Leg Clamp locks the position into place with one or both hands - the sign of the tough-minded, stubborn individual who rejects any opinion other than his own",
            ],
        ),
        "matrix": (
            "Matrix: Leg Gesture x Attitude x Countermove Grid",
            "Fill the matrix pairing the leg gestures - European Leg Cross, Figure Four, Leg Clamp, Ankle Lock, Leg Twine, Parallel Legs - with the attitude each reveals and the countermove that breaks it: the tea-and-brochure uncross, the walk-around-the-desk unlock, the warm low-key approach for the Leg Twiner. Score the cells by how each gesture affects decision-making, recall, and negotiation outcomes before the timer drains.",
            "A three-column matrix of seated figures: each leg posture renders as a wireframe mannequin in its own cell, the attitude reads out beneath it, and a countermove card slides in showing the figure's legs swinging open the moment the right play lands.",
            [
                "The European Leg Cross - one leg crossed neatly over the other - is used by 70 percent of people crossing left over right, and is the normal position for European, Asian, and British cultures",
                "When a person crosses both legs and arms they have emotionally withdrawn from the conversation, and it can be futile to try to be convincing while they sit like that",
                "In business, people sitting with arms and legs crossed talk in shorter sentences, reject more proposals, and recall less detail of what was discussed than those in open positions",
                "The Short Skirt Syndrome: women who wore miniskirts keep crossing their legs and ankles out of habit, and the position makes them feel restrained while others unconsciously read it as negative and react with caution",
                "The Leg Twine, almost exclusively female, locks the top of one foot around the other leg, reinforcing an insecure attitude - the shy, timid woman retreating into her shell like a tortoise",
                "A warm, friendly, low-key approach is needed to open the Leg Twiner's clam, despite how relaxed her upper body may appear",
                "Parallel Legs is a powerful signal of femininity because the bone configuration of female legs and hips prevents most men from sitting that way",
                "Over 86 percent of male participants in the Peases' leg-rating surveys voted Parallel Legs the most attractive female sitting position, and it is taught in deportment and modeling classes",
                "Parallel Legs presses one leg against the other for a healthier, more youthful look that appeals to men from a reproductive standpoint",
                "The woman who constantly crosses and uncrosses her legs when with a man she fancies is drawing attention to her legs - not to be confused with the Parallel Legs position",
                "When we're interested in a conversation or person we put one foot forward to shorten the distance; when reticent we put our feet back, usually under a chair if seated",
                "The man showing interest uses foot forward, legs apart, Crotch Display, and Arms-Splayed to take up more space, while her no-go body language is legs together, body facing away, and arms folded",
            ],
        ),
        "boss": (
            "Boss: The Leg-Truth Lie Gauntlet",
            "Face the timed lie gauntlet from under the desk: watch five managers deliver staged lies and count their unconscious foot movements against the baseline, since managers dramatically increase lower-body movements when lying even while controlling their faces and hands. Then decide where to seat yourself - behind a solid desk or a glass-topped table - and separate cold from defensive leg postures, and read the walking styles, before the final summary round.",
            "A split-view interrogation room with under-desk cameras: each manager's legs glow brighter with every lie-induced movement while a foot-movement counter ticks up; a row of desks in front of you - solid oak versus glass-topped - waits for your seat choice.",
            [
                "In the Peases' staged interviews, managers regardless of gender dramatically increased the unconscious number of foot movements they made when lying",
                "Most managers used fake facial expressions and tried to control their hands while lying, but almost all were unaware of what their feet and legs were doing",
                "Psychologist Paul Ekman verified that people increase their lower body movements when they lie, and observers have greater success exposing lies when they can see the liar's entire body",
                "This explains why many business executives feel comfortable only when sitting behind a desk with a solid front, where their lower body is hidden",
                "Glass-topped tables cause more stress than solid tables because our legs are in full view and we don't feel in full control",
                "The legs evolved to serve two purposes - moving forward to get food and running away from danger - so they show a person's commitment to leaving or staying in a conversation",
                "Open or uncrossed leg positions show an open or dominant attitude, while crossed positions reveal closed attitudes or uncertainty",
                "Cold is different from defensive: the cold person thrusts his hands under his armpits rather than tucking them under the elbows, and crossed legs are straight, stiff, and pressed hard against each other",
                "People who habitually cross their arms or legs claim they are cold or 'comfortable' - and it is probably true, because crossed limbs feel comfortable when they match a defensive emotional state",
                "Young, healthy, vibrant people walk faster, swinging their arms higher in front and behind almost like marching - which is why the army march evolved and politicians adopt the striding gait",
                "Women's arms tend to swing even farther back when walking because their arms bend farther out from the elbow to enable them to carry babies more effectively",
            ],
        ),
    },
    {
        "num": 11,
        "title": "The Thirteen Most Common Gestures You'll See Daily",
        "pages": "264-287",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Head Gesture Spectrum",
            "Work through 16 clips of heads and shoulders and tag each gesture before the loop resets: the Head Nod, Head Shake, Head Wobble, Head Up, Head Tilt, Head Down, Head Duck, Head Twist, Chin Thrust, and the single upward Arab 'no.' For each, lock the meaning - yes, no, submission, neutrality, judgment, apology - and note the culture where the same gesture flips, from Bulgaria to Japan to India.",
            "A row of neck-up mannequin heads on a rotating turntable; each clip freezes the head at its angle and you snap a meaning tag onto the neck, while a world map beneath lights the cultures where that exact gesture means something else.",
            [
                "In most cultures the Head Nod signifies 'Yes' or agreement as a stunted form of bowing - the person symbolically goes to bow but stops short, resulting in a nod",
                "Research with people who were born deaf, dumb, and blind shows they also use the Head Nod for 'Yes,' so it appears to be an inborn gesture of submission",
                "In India the head is rocked from side to side in the Head Wobble to signal 'Yes,' while Westerners and Europeans read the same movement as 'Maybe yes - maybe no'",
                "In Japan, head nodding doesn't necessarily mean 'Yes, I agree' - it usually means 'Yes, I hear you'",
                "Arab countries use a single, upward head movement to mean no, while Bulgarians use the common no gesture to mean yes",
                "The Head Shake may be the first gesture humans learn - evolutionary biologists believe the newborn baby shakes its head from side to side to reject its mother's breast when it has had enough milk",
                "When someone says 'I can see your point of view' or 'We'll definitely do business' while shaking his head, be skeptical - the gesture signals a negative attitude, and no woman believes a man who says 'I love you' while shaking his head",
                "Bill Clinton's famous line 'I did not have sex with that woman' during the Monica Lewinsky inquest was delivered without a Head Shake",
                "Head Up is the neutral position taken by someone with a neutral attitude about what is being said, punctuated by occasional small nods and Hand-to-Cheek evaluation gestures",
                "The Head Twist is a peculiar English greeting descended from medieval hat-doffing: head down while twisting to one side, evolved into the salute or tapping the forehead",
                "The Head Duck raises the shoulders and pulls the head down between them to protect the vulnerable neck - used at a loud bang, when walking past others, and by subordinates approaching superiors, revealing status and power play",
            ],
        ),
        "dialogue": (
            "Dialogue: The Three-Nod Rapport Loop",
            "Play listener and speaker in the persuasion loop: nod in slow, deliberate clusters of three to get the other person talking three to four times more than usual, then speed the nods up to signal you've heard enough and want a turn. Finish each of your sentences with a verbal affirmation - 'Isn't it?' 'Wouldn't you?' - and after the answer keep nodding at about one nod per second for five more nods with your hand on your chin, and watch them keep talking.",
            "A split-screen conversation: your nodding head renders as a metronome whose speed knob you turn, a talk-time bar on the other speaker triples with slow triple-nods, and every 'Fair enough?' you land glows green in the listener's ear.",
            [
                "People will talk three to four times more than usual when the listener nods their head using groups of three nods at regular intervals",
                "The speed of the nod signals the patience - or lack of patience - of the listener: slow nodding communicates interest in what the speaker is saying",
                "Fast nodding tells the speaker you've heard enough or that you want them to finish and give you a turn to speak",
                "Body language is an unconscious outward reflection of inner feelings: positive feelings cause the head to nod - and the reverse is also true, nodding the head causes positive feelings",
                "Head nodding is very contagious: if someone nods their head at you, you will usually nod too, even if you don't necessarily agree with what they are saying",
                "Finishing each sentence with verbal affirmations such as 'Isn't it?' 'Wouldn't you?' 'Isn't that true?' or 'Fair enough?' - with both parties nodding - creates a greater likelihood of agreement",
                "After asking a question, nod during the listener's answer, then continue nodding another five times at about one nod per second - by the count of four the listener usually begins speaking again",
                "While listening, put your hand on your chin in an evaluation position and give it light strokes, because research shows this encourages others to keep talking",
                "Head nodding is an excellent tool for creating rapport, getting agreement and cooperation, and its origins in bowing make it a gesture of going along with the other person's point of view",
            ],
        ),
        "audit": (
            "Audit: The Displacement Gesture Autopsy",
            "Audit a video of a meeting where a manager sounds agreeable but is hiding disapproval: timestamp the imaginary lint-picking, the looks down and away from others, and the verbal agreement that contradicts the gestures. Then run the direct approach - open palms, 'What do you think?' - and verify whether the lint-picking continues, flagging the hidden objection you must dig out. Finish by reading the hug: who pats the back to break the clinch and who air-kisses in displacement.",
            "A boardroom freeze-frame where a lint speck glows on the manager's lapel as his fingers pluck at nothing; a transcript underneath reads 'sounds like agreement' while a gesture-meter reads 'disapproval,' and a timecode ticks through the scene.",
            [
                "Displacement gestures are apparently innocent body-language gestures that reveal a withheld opinion about the attitudes of others",
                "Picking imaginary pieces of lint from one's own clothing, while looking down and away from others, is a common signal of disapproval - even when the person sounds as if he agrees with everything",
                "The lint-picker has a secret opinion and prefers not to state it",
                "Open your palms and say, 'What do you think?' or 'I can see you have some thoughts on this. Would you mind telling me what they are?' then sit back, arms apart, palms visible, and wait for the answer",
                "If the person says he is in agreement but continues to pick the imaginary lint, you may need to take an even more direct approach to discover his hidden objections",
                "The back patting that occurs toward the end of a hug is used the way professional wrestlers use it - to tell the other person to end the hug and break the clinch",
                "People forced into a hug they don't want are likely to begin the back patting even before the hug begins",
                "The air kiss, with its accompanying sound, is given as a displacement of a real kiss we don't want to give",
                "Most people use the Shoulder Tap to break a clinch, while sincere huggers hold on tight",
            ],
        ),
        "matrix": (
            "Matrix: Readiness Gesture x Attitude x Countermove Grid",
            "Fill the matrix pairing the readiness clusters - Hands-on-Hips, Cowboy Stance, Legs-Spread, Leg-Over-the-Arm-of-Chair, Straddling a Chair, Catapult, and the Starter's Position - with the attitude each projects and the countermove that disarms it: standing behind the Straddler, moving into his space until he tips backward, placing something just out of reach of the Catapulter, or mirroring the Catapult if you're a man. Score each cell's dominance readout before the timer drains.",
            "A gymnasium-style grid of fighting stances: each gesture renders as a mannequin with threat-value elbow spikes and a dominance meter, and the right countermove plays as an animated disarm sequence that snaps the pose open.",
            [
                "Birds fluff their feathers, fish expand their body size, and cats and dogs make their fur stand on end; humans, with no pelt, invented the Hands-on-Hips gesture to achieve a bigger physical presence",
                "Hands-on-Hips is used by the child arguing with a parent, the athlete before an event, and the boxer before a bout - a universal gesture communicating readiness for assertive action",
                "The pointed elbows act as weapons preventing others from approaching or passing, and even one hand on the hip sends the message, particularly when pointed at the intended victim",
                "In the Philippines and Malaysia the Hands-on-Hips carries the even stronger message of anger or outrage",
                "Closed-Coat-Readiness shows frustration, while the coat open and pushed back is directly aggressive, reinforced by feet evenly apart or clenched fists in the cluster",
                "Professional models use aggressive-readiness clusters to make clothing look modern and assertive, and women may add a pelvic tilt to emphasize the hips-to-waist ratio that indicates fertility",
                "The Cowboy Stance - thumbs tucked into the belt or pocket tops - frames the genital area as a sexually aggressive display, and apes use the same gesture without a belt or trousers",
                "The Cowboy Stance tells others 'I am virile - I can dominate'; a man holding it with dilated pupils and one foot pointing toward a woman is easily read by most women",
                "In the sizing-up-the-competition scene, two men angled away from each other with relaxed lower bodies are unconsciously evaluating and confrontation is unlikely; facing each other directly with feet planted could mean a fight",
                "The Legs-Spread is almost entirely male: if one man does it the others usually mirror to maintain status, but it has very negative effects in front of women in business because she can't mirror it",
                "A woman facing a crotch-displaying male should not react defensively - talking to his crotch with responses like 'You've got a good point there, Bob' can teach a valuable lesson",
                "Seated Readiness following a Chin-Stroke precedes a client's yes more than half the time, while the Arms-Crossed position immediately after the Chin-Stroke usually means no sale",
            ],
        ),
        "boss": (
            "Boss: The Catapult Dominance Gauntlet",
            "Face the boss round against a Catapulter: hands behind the head, elbows menacingly pointed out, silently telling you he has all the answers. Pick your play under the timer - lean forward with palms up and ask 'Would you care to comment?', place something just out of reach so he must lean forward, mirror the gesture if you're a man, or stand up if you're a woman to force him to change position. Then survive the Straddler round by seating him in a fixed chair with arms before he slips into the Catapult.",
            "A boardroom face-off: the Catapulter looms behind his desk with elbows splayed into spiked shadows while a timer circles his head; each correct countermove makes him drop his arms, and a wrong one adds another minute of his smirk.",
            [
                "The Catapult is a seated version of the Hands-on-Hips pose with the hands behind the head and elbows menacingly pointed out, used to intimidate or to imply a relaxed attitude that lulls you into a false sense of security",
                "The Catapult is typical of professionals such as accountants, lawyers, and sales managers, and people feeling superior - the mind reads 'I have all the answers' or 'Everything's under control'",
                "Newly appointed male managers suddenly begin using the Catapult despite seldom using it before promotion, and management personnel use it regularly",
                "The Catapult is usually clustered with a Figure Four leg position or Crotch Display, showing the person feels superior and is likely to argue or dominate",
                "Countermoves: lean forward with palms up and say 'I can see that you know about this. Would you care to comment?' then sit back, or place something just out of his reach and ask 'Have you seen this?' to force him to lean forward",
                "A man can mirror the Catapult to create equality, but it doesn't work for a woman - it puts her breasts on display, and even flat-chested women who attempt it are described as 'aggressive'",
                "If you're a woman and a man Catapults, continue the conversation standing up so he must change position to continue, sitting again when he stops - a nonaggressive way to train others not to intimidate you",
                "If a superior reprimanding you uses the Catapult, copying it intimidates him - two equals use the Catapult in each other's presence to show equality and agreement",
                "In one insurance company, twenty-seven of thirty male sales managers used the Catapult around their salespeople but rarely in the presence of their superiors, where they used submissive clusters instead",
                "The Straddler uses the back of the chair as a shield, becoming aggressive and dominant; the easiest disarm is to stand or sit behind him, exposing his back and forcing him to change position",
                "With a Straddler on a swivel chair, conduct the conversation standing up, looking down on him, and move into his Personal Space - he can even fall backward off the chair in an attempt to move away",
                "The Starter's Position - leaning forward with both hands on both knees, or gripping the chair like the start of a race - signals readiness to conclude the meeting: take the lead, resell, change direction, or terminate the conversation",
            ],
        ),
    },
]
