# -*- coding: utf-8 -*-
"""Phase 2 chapter data for The Definitive Book of Body Language (Pease & Pease), chapters 4-7."""

D = "Body Language | Nonverbal Communication"

CHAPTERS = [
    {
        "num": 4,
        "title": "Arm Signals",
        "pages": "109-127",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Arm Barrier Decoder",
            "Classify 12 arm positions as they appear: Crossed-Arms-on-Chest, Fists-Clenched-Arms-Crossed, Double-Arm-Grip, Partial-Arm-Cross (self-hug), Holding-Hands-With-Yourself, Thumbs-Up-Arms-Crossed, and the Cuff-Link-Adjust. For each, name the gesture and rate the threat level it signals before the timer runs out.",
            "A council chamber rendered in wireframe; seated figures pop in one by one, each frozen in an arm position. A targeting reticle sweeps the crowd while a label bar asks: HOSTILE, DEFENSIVE, SELF-HUG, OR COOL?",
            [
                "Arm-crossing is a learned barrier, evolved from hiding behind furniture as children",
                "By age six children fold their arms tightly; teens relax the gesture and add crossed legs",
                "Arms fold across the heart and lungs - likely inborn, since monkeys and chimps do it",
                "Fists-Clenched-Arms-Crossed adds hostility to defensiveness",
                "Add clenched teeth, a tight-lipped smile, or a red face and an attack can follow",
                "The Double-Arm-Grip is a self-hug with hands gripping the upper arms",
                "Partial-Arm-Cross is women's subtle hugging-yourself version of the barrier",
                "Holding-Hands-With-Yourself is the men's version, also called the Broken Zipper Position",
                "Thumbs-Up-Arms-Crossed: defensive, but the person still feels cool and in control",
                "Symmetrical posture means defensive and submissive; asymmetrical means defensive and dominant",
            ],
        ),
        "dialogue": (
            "Dialogue: The Uncrossed Pitch",
            "You are presenting to a prospect who has folded his arms. Spot the arms-crossed cluster, then choose the right move: hand him a brochure, ask him to lean into the visuals, or lean forward with open palms and ask 'What's your opinion?' Watch his arms for the unfolding that signals an open attitude.",
            "A boardroom split-screen: the prospect's arms are locked across his chest while a live decoder reads 'BARRIER ACTIVE.' A tray of props (pen, brochure, sample) waits for your click to break the pose.",
            [
                "US lecture research: students with folded arms retained 38 percent less",
                "The 1989 replication with 1,500 delegates produced nearly identical results",
                "A negative, defensive, or nervous attitude makes folded arms feel comfortable",
                "The message is in the receiver as well as the sender",
                "Giving the listener a pen, book, brochure, or sample forces the arms to unfold",
                "Lean forward with palms up and say, 'I can see you have a question...'",
                "Body language is more honest than words",
                "Maintaining the gesture forces the attitude to remain",
                "Training centers should use chairs with arms so attendees leave their arms uncrossed",
                "A buyer's arms-folded cluster hides objections that most salespeople never discover",
            ],
        ),
        "audit": (
            "Audit: Arm Cluster Log",
            "Track every arm-cross you observe in one day - meetings, queues, elevators - and log the setting, the cluster (fists, thumb display, arm grip), and who held it (boss, stranger, subordinate). Grade whether the position was defensive, negative, or a superiority display.",
            "A day-timeline board fills with stick figures in arm poses, each tagged with a location and a sentiment meter. Bars tally OPEN vs. CLOSED postures across your day.",
            [
                "Crossed-Arms-on-Chest decodes as defensive or negative almost everywhere",
                "It is commonly seen among strangers in public meetings, queues, and elevators",
                "90 percent of the 'greenies' crossed their arms when the developers addressed the council",
                "Almost 100 percent of the developers crossed theirs when the greenies spoke",
                "A superior type rarely folds his arms: 'I'm not afraid, I'll keep my body open'",
                "New employees cross their arms from apprehension in the boss's presence",
                "People carrying weapons or wearing armor seldom use arm-cross gestures",
                "Gun-carrying police use the fist-clenched position when standing guard",
                "Elbows on the chair armrests convey power; arms dropped inside the arms read as defeated",
                "Even folding your arms for a backache makes observers perceive you as closed",
            ],
        ),
        "matrix": (
            "Matrix: Arm Gesture x Context x Message",
            "Score 10 disguised arm barriers - cuff-link adjusting, watch-band adjusting, wallet checking, briefcase carrying, flower-clutching, handbag-clutching, two-hand glass holding, coffee cup placement - across settings like parties, stage crossings, and negotiations. Mark each as protective, status, or courtship.",
            "A split-room scene: royals, celebrities, and delegates each perform their disguised barrier. Clicking a figure reveals the 'true' gesture beneath - the hidden arm-cross that gives the game away.",
            [
                "The Cuff-Link-Adjust is Prince Charles's trademark security gesture",
                "Anxious men adjust watch bands and check wallets to cross their arms in disguise",
                "A briefcase held in front of the body is a favorite of insecure businessmen",
                "Princess Anne clutches flowers; the Flowers-Handbag-Clutch is Queen Elizabeth's favorite",
                "The Queen's handbag doubles as a security blanket and a message sender",
                "Royal watchers have recorded twelve handbag signals she sends to her minders",
                "Holding a glass with two hands forms an almost unnoticeable arm barrier",
                "A cup placed on the opposite side of the body forms a single-arm barrier: no",
                "A cup placed on the body's own side shows an open, accepting attitude",
                "Hitler used the Broken Zipper Position in public to mask feelings of inadequacy",
            ],
        ),
        "boss": (
            "Boss Battle: The Council Chamber Debate",
            "Run the council debate where developers and greenies argue over cutting down trees. Read each speaker's audience in real time - arms-folded clusters spreading across the room, fists appearing, thumbs rising - and choose the moment to call a break, hand out materials, or change tack before the vote goes negative.",
            "A packed council chamber; a heat-map of crossed arms spreads across both factions as each side speaks. You must break the barrier with the right move before the gesture cluster locks the room negative.",
            [
                "Hiding behind a barrier is a normal response learned early to protect ourselves",
                "Arm-crossing is an unconscious attempt to block a perceived threat",
                "A nervous, negative, or defensive attitude makes folded arms very likely",
                "Folded-arms listeners have more negative thoughts about the speaker",
                "Folded-arms listeners also pay less attention to what is being said",
                "A Palm-Down handshake plus the Prince Philip Palm-in-Palm position signals superiority",
                "Thumbs-Up-Arms-Crossed at the close of a pitch means you can ask for commitment",
                "Fists-Clenched-Arms-Crossed with a poker face means do not ask for the yes",
                "Reading body language lets you see a no before it is verbalized",
                "An experienced speaker knows the gesture calls for a good ice breaker",
            ],
        ),
    },
    {
        "num": 5,
        "title": "Cultural Differences",
        "pages": "128-144",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Global Gesture Decoder",
            "Swipe through 12 flash-cards of the Ring, Thumb-Up, and V-sign shown over different countries and pick the local meaning: OK, money, zero, insult, victory, or 'up yours.' Watch for the palm direction that flips the V-sign from victory to obscenity.",
            "A world map with a rotating gesture icon; each country highlights with its local meaning while a ticker runs the history of the sign. A dial asks you to lock in the reading before the plane icon lands.",
            [
                "The Ring means OK in the West, money in Japan, and zero or worthless in France and Belgium",
                "In Mediterranean countries the Ring is an orifice signal implying a man is gay",
                "To a Turk the Ring means 'arsehole'; in Arab countries it is a threat or obscenity",
                "Nixon's 1950s Latin America OK signal was read as 'You're all a bunch of arseholes'",
                "Thumb-Up in British-influenced lands: hitchhiking, OK, or 'up yours' when jerked sharply",
                "In Greece a thrust-forward thumb means 'get stuffed' - never hitchhike there",
                "Churchill's V for Victory was palm-out; the palm-in version is the obscene insult",
                "The V-sign descends from English archers who kept their two shooting fingers",
                "In parts of Europe the palm-in V still means victory, so an Englishman can lose the insult",
                "Anglo-Saxons show two with middle and index (96 percent); Europeans use thumb and index (94 percent)",
                "The safest international rule: ask locals to show you their insult signals",
            ],
        ),
        "dialogue": (
            "Dialogue: The Foreign Handshake",
            "A conference room hosts Brits, Americans, Germans, and French delegates. Watch the handshake pumping, cheek-kiss count, and hand-holding, then choose the greeting that matches each culture - and spot the single-pump German handshake that leaves Americans feeling cold.",
            "A revolving door of delegates approaches; each handshake is rendered as a pump counter. A scoreboard tracks POMP-CORRECT vs. POMP-DISASTER as you match greeting to culture.",
            [
                "Brits give three to five handshake pumps; Americans give five to seven",
                "Germans and French give one or two firm pumps followed by a short hold",
                "Some French have been noted to shake hands for up to thirty minutes a day",
                "Kiss greetings: single in Scandinavia, double in France, triple for Dutch, Belgians, and Arabs",
                "On Everest, Hillary offered Tenzing a British handshake and got a Tibetan hug and kiss",
                "Italians grab your hands in midair to interrupt - the raised hand holds the floor",
                "French gesture with forearms and hands; Italians with entire arms and body; Brits stand at attention",
                "The smallest innocent gesture can sink an entire international deal",
                "North Americans are the least culturally sensitive of the 42 countries researched",
                "86 percent of North Americans don't have a passport; even Bush had to apply for one",
                "Foreign cultures are impressed by travelers who learn local body-language customs",
            ],
        ),
        "audit": (
            "Audit: Cultural Touch Log",
            "Record the touch frequency between pairs in your daily life - cafés, queues, offices - and count touches per hour. Compare your tally to the world averages: Rome 220, Paris 142, Sydney 25, New York 4, London 0. Then predict where an elbow touch will work best on you.",
            "A stopwatch overlay counts touches per hour as café pairs talk; flags plant on a world map as each tally matches its city. A verdict banner reads: WHERE ARE YOU THE EASIEST TOUCH?",
            [
                "The French and Italians love to continually touch as they talk",
                "The British prefer not to touch at any time unless on a sports field",
                "The sports embrace was copied from South American and Continental players",
                "Ken Cooper recorded 180 touches per hour in Puerto Rico and 110 in Paris",
                "Ken Cooper recorded 2 touches per hour in Florida and 0 in London",
                "Don't-touch cultures: Germany, Japan, England, USA and Canada, Australia, New Zealand",
                "Do-touch cultures: India, Turkey, France, Italy, Greece, Spain, the Middle East, Russia",
                "Whether a touch offends depends on culture, not on the gesture itself",
                "The biggest cultural differences concern territorial space, eye contact, and touch frequency",
            ],
        ),
        "matrix": (
            "Matrix: Gesture x Country x Meaning",
            "Place 10 gestures - the Ring, Thumb-Up, V-sign, head nod, bow, hand-holding, stiff upper lip, horn sign, spat-out nose-blowing, and business card - on a country grid and assign each local meaning. Score your reading as a diplomat would on a foreign tour.",
            "A spreadsheet of flags and gesture icons; cells flip between GREEN (correct local reading) and RED (diplomatic incident). A passport-stamp counter rewards each correct placement.",
            [
                "The Japanese yes - hai - means 'I heard you,' not 'I agree'",
                "Bulgarians nod their heads to mean no - the great Head-Nod exception",
                "Japanese politeness smiles and nods are misread by Westerners as agreement",
                "The closest a Japanese gets to no is 'It is very difficult' or 'We will give this positive study'",
                "Japanese bow on first meeting: the highest status bows least, the lowest bows most",
                "Japanese business cards are exchanged on first meeting so status can be assessed",
                "The British stiff upper lip purses the lips to reduce facial emotion",
                "Henry VIII's small mouth made the Lips-Pursed a 16th-century superiority signal",
                "The Texas Longhorn horn gesture is football spirit in the USA",
                "In Italy the same horn gesture is the 'cuckold' - other men are sleeping with your wife",
            ],
        ),
        "boss": (
            "Boss Battle: The Tokyo Summit",
            "You lead a delegation into a Japanese negotiation. Manage the encounter: bow at the right depth, exchange business cards, never blow your nose, and translate the yes that means 'I heard you.' One misread politeness nod could turn the whole deal into 'Let's forget the whole thing and go home.'",
            "A minimalist Japanese boardroom; your host bows with a depth meter while your delegation's handkerchiefs glow red as hazards. Every polite hai scrolls past with its true translation underneath.",
            [
                "In Japan handshakes, kissing, and bear hugs are considered impolite - bow instead",
                "Keep shoes spotlessly clean: every Japanese bow inspects them",
                "Western nose-blowing into a handkerchief appalls the Japanese",
                "Asians spit or snort - a cultural legacy of European tuberculosis epidemics",
                "Tuberculosis drove Europeans to blow their noses; spitting was feared like spreading AIDS",
                "To a Japanese, a jacket-pocket handkerchief is like dangling toilet paper",
                "Ekman showed six emotion photos across 21 cultures with majority agreement everywhere",
                "Happiness, sadness, and disgust were agreed on in every country; anger only 18 of 21",
                "The Japanese, South Fore, and Dani could not distinguish fear from surprise",
                "Linda Camras found Japanese and American infants show identical facial expressions",
                "Axtell's Gestures identified over 70,000 physical signs and customs globally",
            ],
        ),
    },
    {
        "num": 6,
        "title": "Hand and Thumb Gestures",
        "pages": "145-165",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Hand and Thumb Scanner",
            "Identify 12 hand gestures as they flash up: Palm-Rub, Thumb-and-Finger Rub, Hands-Clenched (face, desk, crotch positions), Raised and Lowered Steeple, Palm-in-Palm behind the back, Hand-Gripping-Wrist, Thumb displays, and the Face Platter. Rate each on the confidence-to-frustration scale.",
            "A surgical scan of two hands; gestures render in glowing wireframe with position markers. A confidence meter swings as each pose is tagged - from welded-finger frustration to steepled smugness.",
            [
                "The human hand has 27 small bones, including 8 pebble-shaped bones in the wrist",
                "There are more nerve connections between the hands and brain than any other body part",
                "Fast Palm-Rubbing signals positive expectation aimed at you",
                "A slow Palm-Rub signals the gesturer expects the benefit for himself",
                "The Thumb-and-Finger Rub is the money-expectancy gesture",
                "Hands-Clenched shows a restrained, anxious, or negative attitude",
                "The higher the clenched hands, the more difficult the person is to deal with",
                "The Steeple is an exception: it often occurs in isolation, not in a cluster",
                "The Raised Steeple accompanies talking; the Lowered Steeple accompanies listening",
                "Steepling with the head tilted back adds an air of smugness or arrogance",
                "Steepling is particularly common among accountants, lawyers, and managers",
            ],
        ),
        "dialogue": (
            "Dialogue: The Property Pitch",
            "A real estate agent describes your dream house while rubbing his palms. Time his rub: fast means the benefit is for you, slow means he is setting you up. Choose your reply - push for details, renegotiate, or walk - before the agent slides into a Thumb-and-Finger Rub about commission.",
            "An open-house living room; the agent's palms glow with a speedometer. The camera zooms on the rub as a subtitle flashes: WHOSE BENEFIT IS THIS?",
            [
                "The dice thrower rubs the dice between his palms as a sign of winning expectancy",
                "The waiter rubbing his palms at the end of the meal expects a good tip",
                "A buyer's fast Palm-Rub and 'Let's see what you have to offer' signals he might buy",
                "Salespeople are taught the fast Palm-Rub to avoid putting buyers on the defensive",
                "Context rules: on a cold bus platform a brisk palm rub just means cold hands",
                "The agent's fast rub signals the results will be to your benefit",
                "The same slow rub reads as sneaky or devious - the benefit would be his",
                "The speed of the hand rub signals whom the gesturer thinks will get the benefit",
                "Professionals should avoid the Thumb-and-Finger Rub with clients at all times",
                "Street vendors use the rub with 'I can save you 40 percent' and friends with 'Can you lend me fifty dollars?'",
            ],
        ),
        "audit": (
            "Audit: Thumb Display Log",
            "Spend a day logging every thumb display you see: thumbs in pockets, thumb hooked in waistcoat, arms-folded-with-thumbs-up, and thumb-pointing. Note the person's apparent status, and grade each display on the superiority meter before the day is out.",
            "A street-level camera follows pedestrians; thumbs render as glowing markers whenever they protrude. A status bar ranks each displayer - from vagrant to waistcoat thruster.",
            [
                "In palmistry the thumbs represent strength of character and the ego",
                "Thumb displays show dominance, assertiveness, or aggressive attitudes",
                "Thumb gestures are secondary gestures, usually part of a cluster",
                "Men use Protruding Thumbs around women to whom they are attracted",
                "People who wear high-status or prestige clothing display their thumbs",
                "You will rarely see a low-status individual, such as a vagrant, doing it",
                "Thumb displayers rock on the balls of their feet to seem taller",
                "Thumbs-Protruding-from-Coat-Pocket marks a person who feels superior",
                "It is Prince Charles's regular gesture; the boss uses it around the office",
                "None of the subordinates would dare use it in front of the boss",
                "Women rarely used thumb displays until the 1960s, when they began wearing trousers",
                "Thumb-pointing at a person is ridicule - 'She always nags'",
            ],
        ),
        "matrix": (
            "Matrix: Hand Gesture x Position x Reading",
            "Plot 10 hand gestures across positions - front of face, waist height, behind back, in pocket - and assign the correct emotional reading: superiority, frustration, confidence, or self-control. Note how a one-position shift, like gripping higher on the arm, changes the whole message.",
            "A pose laboratory with an adjustable mannequin; dragging the hands to new positions recalculates the reading and the emotional meter beneath.",
            [
                "Napoleon's hand-in-waistcoat pose was painted by David from memory - he never sat for it",
                "Nivelon's 1738 A Book of Genteel Behavior called it 'manly boldness, tempered with modesty'",
                "The famous painting makes the 5'4\" Napoleon look over six feet tall",
                "Palm-in-Palm behind the back signals superiority, confidence, and power",
                "The pose exposes the vulnerable stomach, heart, crotch, and throat in fearless display",
                "Hand-Gripping-Wrist is frustration and an attempt at self-control",
                "The higher one hand grips the arm, the more frustrated the person is",
                "The Upper-Arm Grip is the origin of 'get a good grip on yourself'",
                "Wrist-gripping appears outside courtrooms and in customers' reception areas",
                "Unarmed police use Palm-in-Palm; gun-carrying officers let their arms hang",
                "The Face Platter presents the face for admiration - a positive courtship gesture",
                "Hand gestures can be practiced until you have good control over them",
            ],
        ),
        "boss": (
            "Boss Battle: The Chess Gambit",
            "You play chess against a steepler. Rest your hand on a piece and read his reaction: a Steeple means he loves the move - don't make it; Hands-Clenched or Arms-Crossed means he hates it - play it. Close out the game by converting his gesture tells into three straight wins.",
            "A marble chessboard between two players; your hand hovers over pieces while your opponent's fingers form tells above the board. A confidence readout ticks with every move you hold.",
            [
                "An opponent's Steeple over your move means he is confident - do not make it",
                "Hands-Clenched or Arms-Crossed over your move means he dislikes it - make it",
                "A Steeple after positive gestures means you have the go-ahead to ask for the order",
                "A Steeple after negative gestures means he is confident he can get rid of you",
                "The gestures preceding the Steeple are the key to its outcome",
                "The Steeple should be avoided when persuading - it can read as smugness",
                "Some steeplers convert the gesture into a praying pose to appear God-like",
                "Chirac and Gerry Adams have sometimes appeared God-like this way",
                "Nierenberg and Calero found Hands-Clenched is a frustration gesture in negotiation",
                "A negotiator describing his lost deal clenched until his fingers looked welded together",
                "Hands-Clenched is a favorite of Queen Elizabeth on royal visits, positioned on her lap",
                "Unlock clenched fingers by offering a drink or asking the person to hold something",
            ],
        ),
    },
    {
        "num": 7,
        "title": "Evaluation and Deceit Signals",
        "pages": "166-192",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Deceit Gesture Scanner",
            "Scan 12 hand-to-face movements and classify each as one of the eight common lying gestures: Mouth Cover, Nose Touch, Eye Rub, Ear Grab, Neck Scratch, Collar Pull, Fingers-in-the-Mouth, or an itch. Flag which are deceit and which are plain reassurance or allergies.",
            "A polygraph-style scanner trains on a face; hand-to-face movements freeze in amber frames while a classification wheel spins. A verdict light flashes LIE CLUSTER or BENIGN ITCH.",
            [
                "The Mouth Cover is the brain's attempt to suppress deceitful words",
                "A fake cough can disguise the Mouth Cover; actors use it when playing gangsters",
                "The Nose Touch is a quick rub; women make smaller strokes to avoid smudging makeup",
                "Lying releases catecholamines that swell nose tissue - the Pinocchio Effect",
                "Clinton touched his nose once every four minutes - 26 touches in his grand jury testimony",
                "The Eye Rub is the brain's attempt to block out deceit or the face being lied to",
                "The Ear Grab is the adult version of the child's Hands-Over-Both-Ears",
                "The Neck Scratch signals doubt, averaging exactly five scratches",
                "The Collar Pull eases the sweat of deceit - 'getting hot under the collar'",
                "Fingers-in-the-Mouth signals a need for reassurance, not deceit",
                "A listener's Mouth Cover can mean he feels you are hiding something",
                "A speaker who sees Mouth Covers should stop and invite questions",
            ],
        ),
        "dialogue": (
            "Dialogue: The Lying Interviewee",
            "Interview a candidate who answers with crossed arms, little palm use, and a stream of eye-rubs and nose-touches. Decide whether his story is true or rehearsed, probe his past employers, and choose to hire or reject based on the gestures - not the smooth words.",
            "An interview desk across a glaring light; the candidate's face is a live cue-map with eye-rub and nose-touch hotspots pulsing. A HIRE / REJECT dial waits for your evidence-based verdict.",
            [
                "Words are the least dependable lying signs - lies can be rehearsed",
                "Automatic gestures are the most reliable clues, made without control",
                "Feldman's study of 121 couples: 62 percent told two to three lies every ten minutes",
                "James Patterson found 91 percent of Americans lied regularly at home and at work",
                "The Peases' interviewee crossed his arms and legs, used little palm, and looked away",
                "Eye-rubbing and nose-touching came with answers about his previous employers",
                "Overseas references proved he gave false information - he was not hired",
                "Interrogators place a suspect in full view because lies are easier to see",
                "The easiest way to lie is over the telephone or in an e-mail",
                "Professional liars: politicians, lawyers, actors, and television announcers",
            ],
        ),
        "audit": (
            "Audit: Evaluation vs Boredom Log",
            "Watch one presenter and log the audience's hand-to-face clusters for ten minutes: chin on thumb, fist supporting the head, heel of the palm, index finger up the cheek, finger drumming, foot tapping. Grade each seat on the interest-to-boredom thermometer before the presenter loses the room.",
            "An auditorium heat-map over the crowd; each listener's hand position re-scores their seat from GREEN (interest) to RED (snoring). A presenter's morale bar drains as boredom spreads.",
            [
                "Boredom begins with the chin supported by the thumb, then by the fist",
                "Extreme lack of interest: the head is fully supported by the hand",
                "The ultimate boredom signal is the head in both hands with snoring sounds",
                "Finger drumming and foot tapping signal impatience, not boredom",
                "The faster the tap, the more impatient the listener is becoming",
                "Genuine interest: the hand rests lightly on the cheek and does not support the head",
                "Index finger up the cheek with the thumb under the chin means critical thoughts",
                "Middle managers feign interest to the president until the head-support gives them away",
                "Rodin's The Thinker shows evaluation, but the posture reveals a dejected man",
                "The longer a gesture cluster is held, the longer the attitude remains",
                "Handing something to the listener can alter his pose and his attitude",
            ],
        ),
        "matrix": (
            "Matrix: Hand-to-Face x Situation x Reading",
            "Score 10 hand-to-face gestures - Mouth Cover, Nose Touch, Eye Rub, Ear Grab, Neck Scratch, Collar Pull, Fingers-in-the-Mouth, glasses-arm chewing, chin stroke, and head slap - across three situations: interrogation, negotiation, and casual chat. Mark each as deceit, doubt, boredom, or decision.",
            "A three-panel situational grid; the same gesture lands differently in each panel. Cells tint RED for deceit, AMBER for doubt, BLUE for boredom, and GREEN for decision-making.",
            [
                "The Mouth Cover can appear as the 'Shhh' gesture inherited from parents",
                "The Nose Touch must be read in clusters and context - it could be hay fever",
                "An itchy nose is scratched deliberately; the Nose Touch is a light, quick stroke",
                "'Lying through your teeth' is the cluster of clenched teeth, false smile, and Eye Rub",
                "Prince Charles uses the Ear Grab and Nose Touch in crowds - never in his car",
                "In Italy the Ear Grab signals that someone is effeminate or gay",
                "The Neck Scratch can contradict 'I can understand how you feel'",
                "Ask a collar-puller, 'Could you repeat that, please?' to spring the trap",
                "Glasses arms, pens, and cigarettes in the mouth stall a decision",
                "An object in the mouth means the person is unsure and needs reassurance",
                "Gulps of saliva increase when lying - visible on men's Adam's apples",
                "Desmond Morris's nurses showed more hand-to-face gestures when they lied",
            ],
        ),
        "boss": (
            "Boss Battle: Beat Bob at Chess",
            "Bob is a chess colleague whose tells have been secretly videotaped. Play him: he rubs his ear or touches his nose only when unsure, steeples when he likes your move, and Mouth-Covers, Ear-Grabs, or Neck-Scratchs when he does not. Exploit his tells to beat him three games in a row.",
            "A video room replays Bob's old games in slow motion while a live board sits between you. Bob's hands hover over pieces; his tells flash on the replay screen as your winning moves queue up.",
            [
                "Bob rubbed his ear or touched his nose only when unsure of his next move",
                "Bob steepled when he felt confident he could beat a proposed move",
                "Bob used the Mouth Cover, Ear Grab, or Neck Scratch when uncertain or unhappy",
                "Once his cues were shared, most of the chess group could beat Bob",
                "The role-play interviewee Mouth-Covered when thinking of the negative answer",
                "His hand dropped away when he thought of the positive answer",
                "A hand-to-face gesture means a negative thought: doubt, deceit, or exaggeration",
                "The correct negative is identified by the gestures preceding it and the context",
                "Microgestures occur within a split second - readable only by trained observers",
                "Eye-blinking rate can jump from ten to fifty blinks per minute while lying",
                "Attractive people are more believed - JFK and Clinton got away with more",
                "Women tell more complicated lies; men tell simple ones like 'I missed the bus'",
            ],
        ),
    },
]
