# -*- coding: utf-8 -*-
"""Phase 2 chapter data for The Definitive Book of Body Language (Pease & Pease),
Introduction + chapters 1-3."""

D = "Body Language | Nonverbal Communication"

CHAPTERS = [
    {
        "num": 0,
        "title": "Introduction: All Things Are Not What They Seem",
        "pages": "18-23",
        "domain": D,
        "scrub": (
            "Cue Scrubber: See-What's-Really-There Scanner",
            "Analyze 12 everyday scenes where words and body signals disagree. For each, identify the real signals being sent (open palms, pointed finger, closed hand, posture), flag who in the scene would have misread them, and say what the signals actually mean before the story's twist is revealed.",
            "A hotel lobby illusion with hanging plants: guests mistake their own mirror reflection for a stranger. A HUD labels each misread - 'fat, ugly guy?' - while the true signal lights up in green.",
            [
                "Most people only see the things they think they are seeing - the goat was chained to the railway sleeper",
                "A 'go away' said with open palms means the person is not aggressive and it is safe to persist",
                "A soft-voiced 'go away' with a pointed finger or closed hand means it is time to leave",
                "Less than 5 percent of people can identify the back of their own hand from a photograph",
                "85 percent of men failed to recognize their own reflection in the hotel lobby mirror",
                "58 percent of women recognized the mirror; 30 percent said the other 'guest' looked familiar",
                "Half the tourists failed to notice a completely different man took over the tourism counter",
                "Men were twice as likely as women to completely miss the change in the tourist bureau experiment",
                "Politicians duck, dodge, pretend, and lie - and we watch closely for the body signals that trip them up",
                "Reading people means matching what you see and hear in its environment and drawing probable conclusions",
                "The human animal is rarely aware that its postures and gestures tell one story while its voice tells another",
                "Most people cannot describe which arm crosses on top until they actually try to reverse it",
            ],
        ),
        "dialogue": (
            "Dialogue: The Rubber-Sponge Sales Call",
            "Play both sides of the eleven-year-old Pease's door-to-door sponge sale: the seller who must decide to persist or leave from palm and finger signals, and the homeowner whose hands leak the truth. Run four callbacks with escalating difficulty and pick the moment to push the presentation or walk away.",
            "A front doorstep at dusk; the homeowner says 'go away' softly while their hands glow - open palms green (persist), pointed finger red (leave).",
            [
                "Open palms say 'unarmed and honest' - a legacy of showing no weapons were concealed",
                "A dismissive tone with exposed palms means you can safely persist with the presentation",
                "A soft voice with a pointed finger or closed hand means leave now",
                "The palms are like the vocal cords of body language - they did more 'talking' than any other body part",
                "Salespeople are taught to watch for exposed palms when a customer gives reasons or objections",
                "Someone giving valid reasons flashes their palms; someone not telling the truth conceals their hands",
                "Men who lie hide their palms in pockets or an arms-crossed position while explaining themselves",
                "Women who hide something prefer to look busy while talking about a range of unrelated topics",
                "Hidden palms give the listener an intuitive feeling that the person is not telling the truth",
                "The Law of Cause and Effect: exposing your palms makes it hard for you to tell a convincing lie",
                "As open-palm gestures become habitual, the tendency to tell untruths diminishes",
                "Talking with your palms exposed puts pressure on the other person to be truthful with you",
            ],
        ),
        "audit": (
            "Audit: The 15-Minute Body Language Watch",
            "Spend fifteen minutes observing people at an airport, party, or meeting and log every signal you catch - palms, posture, clusters, contradictions. Then run the TV test: watch with the sound off, predict what is happening, and check your accuracy every few minutes.",
            "An airport arrival gate: travelers embrace, wave, fume, and pace while a stopwatch ticks 15:00 and a notebook auto-fills with gesture entries and accuracy stamps.",
            [
                "Set aside at least fifteen minutes a day to study the body language of other people and your own gestures",
                "An airport is a prime reading ground - eagerness, anger, sorrow, happiness, and impatience on display",
                "TV practice: turn down the sound, read the picture, then check accuracy by turning the sound up every few minutes",
                "Deaf people understand entire programs without sound - the skill is fully learnable",
                "The Body Language Watcher studies people at functions, beaches, offices, and on television",
                "Birdwhistell estimated the average person speaks words for only ten or eleven minutes a day",
                "The average spoken sentence takes only about 2.5 seconds",
                "We can make and recognize around 250,000 facial expressions",
                "Body language accounts for 60-80 percent of the impact made around a negotiating table",
                "People form 60-80 percent of their initial opinion of a new person in less than four minutes",
                "Negotiating face to face, we make final decisions more on what we see than what we hear",
                "A bird-watcher doesn't study birds to shoot them - understanding makes every encounter an experience",
            ],
        ),
        "matrix": (
            "Matrix: Words x Body Signals x Verdict Grid",
            "Fill the grid for 10 scenes: the spoken words, the body signals present, and the verdict - congruent, incongruent, or context-dependent. Flag every scene where the same gestures change meaning when the context changes.",
            "A courtroom wall with three columns: WORDS | BODY | VERDICT. A cold bus-terminal scene slides behind the gesture column and flips a verdict from 'defensive' to 'cold'.",
            [
                "Rule 1: read gestures in clusters - one gesture is a word; three or more make a sentence",
                "Head scratching can mean sweating, uncertainty, dandruff, fleas, forgetfulness, or lying",
                "The Critical Evaluation cluster: index finger up the cheek, another finger covering the mouth, thumb supporting the chin",
                "Tightly crossed legs plus arms crossing the body plus head and chin down spell 'I don't like what you're saying'",
                "Rule 2: look for congruence - nonverbal signals carry about five times the impact of the verbal channel",
                "When words and body language conflict, people - especially women - rely on the nonverbal message",
                "Freud's patient slipped her wedding ring on and off while praising her marriage - problems surfaced later",
                "Rule 3: read gestures in context - arms tightly crossed at a cold bus terminal means cold, not defensive",
                "The same crossed arms across a sales table mean the person is negative or rejecting your offer",
                "A politician with arms folded and chin down while claiming openness to young people sends two stories",
                "Short, sharp karate chops to the lectern contradict a claim of a warm, caring approach",
                "Repeated hair touching or twirling usually means uncertainty or anxiety - mother's way of comforting us",
            ],
        ),
        "boss": (
            "Boss Battle: The Cold Reading Table",
            "Take the fortune-teller's chair: read four 'clients' using only careful observation of their body-language signals, appearance, and reactions to your statements plus probability - no ESP allowed. Deliver an 80-percent-accurate reading and make the hardened skeptic believe strange forces are at work.",
            "A dim, smoke-filled room with a jewel-encrusted turban, a moon-shaped table, and a crystal ball; each client's micro-reactions light up like a telemetry feed and an accuracy meter climbs toward 80 percent.",
            [
                "Cold reading is careful observation of body-language signals plus an understanding of human nature and probability - not ESP",
                "A well-constructed 'psychic' reading is more than 80 percent accurate for any person who reads it",
                "Vague claims like 'you are sometimes outgoing, sometimes reserved' apply to almost everyone",
                "Readers decode the client's reactions to each statement and question in real time",
                "Information gathered from simple observation of a person's appearance is instant data",
                "Positive expectations: people who regularly visit psychics arrive expecting the outcome",
                "Dim lighting, weird music, tarot cards, a crystal ball, and theater complete the illusion",
                "Most 'psychics' are female - women have the extra brain wiring to read body signals and emotions",
                "Many cold readers are unaware of their own signal-reading skill and believe they are psychic",
                "The reading is really a conversation where the client supplies the details",
                "Twitches, posture changes, and expressions reveal which statements hit home",
                "The same skill that amazes clients at the fortune-teller's table reads anyone anywhere",
            ],
        ),
    },
    {
        "num": 1,
        "title": "Understanding the Basics",
        "pages": "24-45",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Gesture Cluster Reader",
            "Analyze 12 scenes and assemble each one's gestures into clusters of three or more. Decode the body-language 'sentence' each cluster makes, then check whether those signals are congruent with the words being spoken.",
            "A stream of silhouettes; each gesture snaps on as a word-chip to build a sentence on a ticker: 'legs crossed + arm crossed + chin down = I disagree.'",
            [
                "Each gesture is a single word; a cluster of three or more gestures makes a body-language sentence",
                "The word 'dressing' has ten meanings - gestures, like words, only make sense with other words",
                "Scratching the head can mean sweating, uncertainty, dandruff, fleas, forgetfulness, or lying",
                "The main Critical Evaluation signal is hand-to-face with the index finger pointing up the cheek",
                "In Critical Evaluation, another finger covers the mouth while the thumb supports the chin",
                "Tightly crossed legs and an arm crossing the body add 'defensive' to the sentence",
                "The head and chin down position adds 'negative or hostile'",
                "Continual hair touching or twirling usually reveals uncertainty or anxiety",
                "People stroke their hair or head because that is how their mother comforted them as children",
                "A man tugging the fold of skin under his chin may feel self-conscious about gaining weight",
                "A woman smoothing her dress down may be aware of extra pounds on her thighs",
                "The perceptive person reads the body-language sentence and matches it against the verbal sentence",
            ],
        ),
        "dialogue": (
            "Dialogue: The 'Intuitive Feeling' Interview",
            "Play both sides of the job applicant who quit 'for insufficient opportunity': the candidate who praises his former boss while micro-signals leak, and the female interviewer who trusts her hunch. Then review the slow-motion video, find the split-second sneer, and decide the applicant's fate.",
            "A split-screen interview room; on replay, the left side of the applicant's face flashes a sneer in freeze-frame while the interviewer's hunch meter spikes.",
            [
                "Harvard research: women decoded filmed couples accurately 87 percent of the time vs. 42 percent for men",
                "Men in nurturing occupations - artists, actors, nurses - and gay men scored nearly as well as women",
                "Female intuition grows from years of relying on the nonverbal channel to communicate with a baby",
                "The applicant flashed a split-second sneer on the left side of his face each time he praised his boss",
                "Contradictory signals flash across a face in a fraction of a second - untrained observers miss them",
                "The applicant had actually been fired for dealing drugs to other staff members",
                "Pupil dilation, sweating, and blushing cannot be consciously faked",
                "Exposing the palms to try to appear honest is easily learned",
                "Fakers can only pretend for a short period - the body eventually shows contradictory signals",
                "Miss World and Miss Universe contestants use studiously learned movements to imply warmth and sincerity",
                "Politicians who fake body language well - JFK and Adolf Hitler - are said to have 'charisma'",
                "Body language is easier to fake with men because men aren't good readers of body language",
            ],
        ),
        "audit": (
            "Audit: Sound-Off TV Reading Log",
            "Watch a ten-minute television scene with the sound off and log your predictions of each character's emotion, attitude, and relationships. Unmute every few minutes to verify, score your accuracy, and note which clusters you misread and why.",
            "A muted TV screen with a notepad column of predictions beside it; each unmute slams correct or incorrect stamps onto the log as the show runs.",
            [
                "Before radio, most communication was written - ugly politicians and poor speakers like Abraham Lincoln could still win",
                "The radio era favored the spoken word - Winston Churchill's voice was his weapon",
                "Today's politicians hire personal body-language consultants to appear sincere, caring, and honest",
                "Body language has been actively studied on any scale only since the 1960s; the 1978 book made it public",
                "Speech developed between two million and five hundred thousand years ago as the brain tripled in size",
                "Words are used primarily to convey information; body language negotiates interpersonal attitudes",
                "A woman can give a man a 'look to kill' and convey a clear message without opening her mouth",
                "Birdwhistell learned to tell what language a person spoke simply by watching their gestures",
                "Chirac, Reagan, and Bob Hawke revealed the relative sizes of issues in their minds with their hands",
                "Bob Hawke held his hands a yard apart for politicians' salaries but only a foot apart for executives'",
                "Humans are a species of primate - a hairless ape that has learned to walk on two limbs",
                "Seven out of ten people cross their left arm over their right - possibly a genetic gesture that cannot be changed",
            ],
        ),
        "matrix": (
            "Matrix: Inborn vs. Learned x Gesture x Evidence",
            "Classify 10 gestures as inborn, genetic, learned, or culturally variable using the chapter's evidence: studies of blind people, comparisons across cultures, and primate behavior. Place each gesture on the grid and justify its placement.",
            "A two-axis laboratory chart - one axis BLIND AND PRIMATE EVIDENCE, the other CULTURE - where gesture cards drop into quadrants as their evidence is weighed.",
            [
                "Eibl-Eibesfeldt found children born deaf and blind still smile - smiling is inborn",
                "Ekman, Friesen, and Sorenson: five widely different cultures use the same basic facial gestures for emotion",
                "Most primate babies are born with the immediate ability to suck - inborn or genetic",
                "Nodding the head for 'yes' is probably inborn because it is also used by people born blind",
                "Head-shaking for 'no' is learned in infancy - the baby turns its head to reject the breast",
                "Smiling is a threat gesture in carnivores; primates pair it with nonthreatening signals to show submission",
                "Baring the teeth and nostril flaring derive from the act of attacking - primitive signals of other primates",
                "Nostril flaring oxygenates the body for fight or flight and calls for backup support in the primate world",
                "Sneering warns that teeth will be used - humans still sneer when angry, threatened, or irritated",
                "The Shoulder Shrug: exposed palms, hunched shoulders, and raised brow - the universal 'I don't know'",
                "Most men put on a coat right arm first; most women left - each uses a different brain hemisphere",
                "In a crowded street a man turns his body toward a woman as he passes; she turns away to protect her breasts",
            ],
        ),
        "boss": (
            "Boss Battle: The Confession Video Review",
            "Review the slow-motion interview of the applicant who quit 'because there was insufficient future opportunity.' Hunt for the split-second left-side sneer, weigh his praising words against his microgestures, and phone the former boss for the verdict - all before the four-minute hiring decision clock expires.",
            "A video-editing suite frozen at 25 percent speed; a timeline slider hunts the sneer frame while a phone line to the former employer hums onscreen and a decision clock ticks.",
            [
                "A five-year-old telling a lie immediately covers his mouth with one or both hands",
                "Teenagers rub their fingers lightly around the mouth instead of slapping a hand over it",
                "Adults turn the Mouth-Covering gesture into a Nose-Touch - faster, subtler, but the same signal",
                "As people get older their gestures become more subtle - a fifty-year-old is harder to read than a five-year-old",
                "Older people have less muscle tone in the face, making expressions harder to read",
                "A split-second sneer on the left side of the applicant's face gave the game away",
                "The female interviewer's 'intuitive feeling' was a real read of contradictory microgestures",
                "A soft handshake can mean weak character - or arthritis, or a surgeon protecting valuable hands",
                "Artists, musicians, and surgeons may use a 'dead fish' handshake to protect their hands",
                "Physical limits change the read: obese people can't cross their legs; short skirts force tight leg-crossing",
                "When a faker shows open palms and smiles at a lie, microgestures - contracted pupils, lifted eyebrow, twitching mouth - contradict him",
                "The key is separating real gestures from fake ones so a genuine person can be distinguished from a liar",
            ],
        ),
    },
    {
        "num": 2,
        "title": "The Power Is in Your Hands",
        "pages": "46-83",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Palm Power Command Scanner",
            "Scan 12 command scenes and classify each as Palm-Up, Palm-Down, or Palm-Closed-Finger-Pointed. Predict the listener's likely feeling and the audience-response score each gesture would earn in the eight-lecturer experiment.",
            "A stadium of frozen lecturers mid-gesture; a scoreboard tallies 84% for Palm-Up, 52% for Palm-Down, and 28% for Finger-Pointed as each pose is scanned.",
            [
                "Palm-Up is submissive and nonthreatening - the pleading gesture of a street beggar, showing no weapons",
                "Palm-Down projects immediate authority - the other person senses an order and may feel antagonistic",
                "The Nazi salute had the palm facing directly down - the symbol of power and tyranny of the Third Reich",
                "If Hitler had saluted in the Palm-Up position no one would have taken him seriously - they would have laughed",
                "Palm-Closed-Finger-Pointed uses the pointed finger like a symbolic club - 'do it or else'",
                "The pointing gesture precedes a right overarm blow, a primal move most primates use in attack",
                "In Malaysia and the Philippines, finger-pointing at a person is an insult - you only point at animals",
                "Malaysians use the thumb to point to people or give directions",
                "The eight-lecturer experiment: Palm-Up talks earned 84 percent positive testimonials",
                "The same presentation with Palm-Down dropped to 52 percent positive response",
                "Finger-Pointed lectures scored only 28 percent - and some participants walked out",
                "Fingertip-Touch speakers were rated 'thoughtful, goal-oriented, and focused'; pointers were 'aggressive, belligerent, and rude'",
            ],
        ),
        "dialogue": (
            "Dialogue: The Power Handshake Counter",
            "Someone greets you with a Palm-Down Thrust. Play both sides: the power player delivering the dominant grip, and you practicing the two counters - the Step-to-the-Right and the Hand-on-Top - until you can straighten the handshake and match pressure for rapport.",
            "A mirror suite of two figures shaking hands; your left-foot step shifts the grip from red (dominant) to green (equal) on a pressure gauge.",
            [
                "The Palm-Down Thrust, reminiscent of the Nazi salute, is the most aggressive of all handshakes",
                "Step-to-the-Right: step forward with the left foot, then cross the right leg in front of the person",
                "Ninety percent of people naturally step forward on the right foot - leaving them at a disadvantage",
                "The maneuver straightens the handshake or turns it into the submissive position - the equivalent of winning arm wrestling",
                "The Step-to-the-Right also takes control by invading the power player's personal space",
                "The Hand-on-Top: answer with your palm up, then put your left hand over his right to form a Double-Hander",
                "The Hand-on-Top is a much simpler counter and is much easier for women to use",
                "Grasping his hand on top and shaking can shock a power player - do it only as a last resort",
                "Rapport requires both palms in the vertical position so no one is dominant or submissive",
                "Apply the same pressure you receive - a 7 meeting a 5 on a 1-10 scale means backing off 20 percent in strength",
                "The average male hand can exert around twice the power of the average female hand",
                "Evolution gave male hands a grip of up to 100 pounds for tearing, gripping, carrying, and hammering",
            ],
        ),
        "audit": (
            "Audit: Handshake Census Field Log",
            "Log 10 handshakes today - in meetings, shops, or at a party. Classify each as dominant, submissive, or equal, note who reached first, how many pumps were used, and whether it was one of the eight worst. Score your own approach and which foot you step forward on.",
            "A crowded reception line; each handshake freezes briefly, tagged with a rating card and a verdict stamp while a footstep counter tracks left versus right foot.",
            [
                "The handshake evolved in the nineteenth century to seal commercial transactions between men of equal status",
                "Hands are normally pumped five to seven times; in Germany they pump two or three times with an extra hold",
                "The French are the biggest glad-handers, shaking on both greeting and departure",
                "Roman leaders greeted each other with a standing version of arm wrestling - the Upper-Hand position",
                "In a study of 350 senior executives, 88 percent of men and 31 percent of women used the dominant handshake",
                "Women who initiate a firm handshake are rated as more open-minded with better first impressions",
                "A soft handshake in social contexts highlights femininity; in business it makes men not take the woman seriously",
                "Chaplin (University of Alabama, 2001): extroverts use firm handshakes; shy, neurotic personalities don't",
                "Women open to new ideas used firm handshakes; men's handshakes did not vary with openness",
                "The Wet Fish reads as weak character - but a limp handshake is the norm in some Asian and African cultures",
                "One in twenty people suffer hyperhydrosis, a genetic condition causing chronic sweating of the hands",
                "Cold, clammy hands come from fight-or-flight blood diversion - visualizing an open fire raises palm temperature 3-4 degrees",
            ],
        ),
        "matrix": (
            "Matrix: Worst Handshake x Credibility x Counter",
            "Populate the grid for the world's eight worst handshakes: assign each its credibility rating, its tell or origin, and the correct counter or recovery move.",
            "A museum of eight glass cases, each holding a frozen handshake statue; rating plaques glow 1/10, 4/10, 0/10, 2/10, 3/10, 3/10, 4/10, 2/10 as you tabulate.",
            [
                "The Wet Fish: 1/10 - soft, flaccid, and easily turned over; universally unpopular, read as weak character",
                "The Vise: 4/10 - palm down, one sharp downward pump, a grip that can stop blood flow; sometimes used by the insecure",
                "The Bone-Crusher: 0/10 - trademark of the overly aggressive; women should avoid rings on the right hand in business",
                "Counter the Bone-Crusher by saying 'Ouch! That really hurt my hand. Your grip is too strong.'",
                "The Finger-Tip Grab: 2/10 - common in male-female greetings; the initiator lacks confidence",
                "The Finger-Tip Grab can result from mismatched personal space - one person's intimate space at two feet, another's at three",
                "Recovery: take their right hand with your left, place it correctly, and say with a smile 'Let's try that again!'",
                "The Stiff-Arm Thrust: 3/10 - keeps you at a distance; also used by rural-raised people with larger space needs",
                "The Socket-Wrencher: 3/10 - a sharp reverse thrust dragging the receiver in, off balance, and out of his territory",
                "The Pump Handle: 4/10 - rural overtones; up to seven pumps is acceptable but the pumper never stops",
                "The Dutch Treat: 2/10 - 'giving a handshake like a bunch of carrots'; younger Dutch call it De Slappe Vaatdoek (Sloppy Dishcloth)",
                "Vertical palms plus matching grip is usually perceived as a 10/10 handshake",
            ],
        ),
        "boss": (
            "Boss Battle: The Photo-Op Power Game",
            "Analyze the 2003 Blair-Bush handshake and the 1993 Arafat-Rabin White House shot, then place yourself in the frame: win the left-of-picture position, decide which counters beat the Back Hold and the Bent-Arm-Pull-In, and control how the photograph reads.",
            "A split newsroom; two famous handshake photos freeze, annotated with arrows showing feet, grip angle, and who owns the left side, while your silhouette walks into the frame.",
            [
                "Bush delivered the Upper Hand from the left side of the photograph - perceived as dominant and calling the shots",
                "In the 2003 shot Bush dressed like an Armed Forces Commander-in-Chief; Blair looked like a schoolboy meeting the headmaster",
                "Bush planted his feet firmly together and used a Back Hold to control Blair during the handshake",
                "The person on the left of a picture is perceived to have a dominant edge - JFK's favorite move",
                "Kennedy-Nixon 1960: radio listeners picked Nixon, TV viewers picked Kennedy - body language won the presidency",
                "If trapped on the right-of-picture, extend your arm early so the other person faces you straight on",
                "For photos, always approach so you occupy the left-of-picture position; at worst use a Double-Hander for equal footing",
                "Arafat-Rabin 1993: Rabin held his ground with a Stiff-Arm Thrust, leaning forward to guard his personal space",
                "Arafat stood absolutely erect and countered with a Bent-Arm-Pull-In",
                "Clinton was the key figure in the shot: unobstructed center position, extra height, and Arms-Spread-Open-Palms",
                "Clinton's Half-Moon, Lips-Sucking smile showed the emotional restraint he either felt or faked",
                "The Double-Hander restricts the receiver's overarm-blow defense - never use it without an emotional bond",
            ],
        ),
    },
    {
        "num": 3,
        "title": "The Magic of Smiles and Laughter",
        "pages": "84-108",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Genuine vs. Fake Smile Detector",
            "Scan 12 faces and classify each smile as genuine or fake: check the eye cover fold, the dip of the eyebrows, and the crow's feet, then flag whether one side of the smile is stronger or whether it arrived too quickly and lasted too long.",
            "A wall of 12 portraits; a magnifier hovers over the eyes as the HUD scores orbicularis oculi contraction against the mouth's zygomatic pull.",
            [
                "Duchenne de Boulogne cataloged face muscles using electrodiagnostics and the heads of guillotine victims",
                "The zygomatic major muscles run down the face, pull the mouth back, and are consciously controlled",
                "The orbicularis oculi pull the eyes back, make them narrow, and cause crow's feet",
                "The orbicularis oculi act independently and reveal the true feelings of a genuine smile",
                "The first place to check a smile's sincerity is the wrinkle lines beside the eyes",
                "Ekman and Friesen devised the Facial Action Coding System (FACS) to distinguish genuine from fake smiles",
                "In a genuine smile the eye cover fold moves downward and the ends of the eyebrows dip slightly",
                "Saying 'cheese' pulls back the zygomatic majors - the result is a false smile and an insincere photograph",
                "False emotions are more pronounced on the left side of the face because the cortex's expression center is right-hemisphere",
                "A liar's smile comes more quickly and is held much longer, almost as if the liar is wearing a mask",
                "Bob misread the tight-lipped, no-teeth-visible smile as interest - most men are oblivious to it",
                "We smile from five weeks of age; laughter starts between the fourth and fifth months",
            ],
        ),
        "dialogue": (
            "Dialogue: The Smuggler's Interrogation",
            "Play both sides of the 1986 Australian Customs interview: the traveler who may be smuggling contraband, and the officer watching whether the smile rate rises or falls. Decide who to search using smile frequency alone, then deliver the verdict.",
            "A customs booth; a body-cam line chart plots smile frequency over the interview - the innocent's line climbs, the smuggler's flatlines, and a search/no-search stamp waits.",
            [
                "We were commissioned by Australian Customs in 1986 to increase seizures of illegal contraband and drugs",
                "Law enforcement had assumed liars increased their smiling - analysis of filmed liars proved the opposite",
                "When liars lie they smile less or not at all, regardless of culture",
                "Innocent people telling the truth increase their smiling frequency - smiling is rooted in submission",
                "The innocent were attempting to appease their accusers; the professional liars reduced smiles and other body signals",
                "A police car pulling up beside you at traffic lights makes even the innocent smile with guilt",
                "Fake smiling is controlled and should always be considered in the context where it occurs",
                "Smiling tells another person you are nonthreatening and asks them to accept you on a personal level",
                "Dominant people rarely smile - Putin, James Cagney, Clint Eastwood, Margaret Thatcher, and Charles Bronson",
                "Chimpanzees bare their lower fangs to threaten; humans drop or thrust the lower lip forward the same way",
                "The chimp 'fear face' and 'play face' are both submission gestures - the ancestors of the human smile",
                "Courtroom research: an apology offered with a smile incurs a lesser penalty than an apology without one",
            ],
        ),
        "audit": (
            "Audit: Smile Type Census Log",
            "In one social hour, count and classify every smile you see into the five common types - tight-lipped, twisted, drop-jaw, sideways-looking-up, and the Bush grin. Note who smiles more, and what each tight-lipped or coy smile communicated to the people around it.",
            "A park café scene; every smile is tagged with a colored label as it happens while a running counter divides the total by type and by gender.",
            [
                "The Tight-Lipped Smile hides a secret or withheld opinion - a favorite of women who don't want to reveal dislike",
                "Other women read the Tight-Lipped Smile as a rejection signal; most men are oblivious to it",
                "Richard Branson sports a wide toothy smile because he is happy to reveal exactly how he succeeded",
                "The Twisted Smile mirrors into two opposite faces - a cheesy grin on one side, an angry frown on the other",
                "The Twisted Smile is peculiar to the Western world, can only be done deliberately, and sends only sarcasm",
                "The Drop-Jaw Smile is practiced - a favorite of The Joker, Bill Clinton, and Hugh Grant to win reactions and votes",
                "The Sideways-Looking-Up Smile looks juvenile, playful, and secretive - and is men's favorite everywhere",
                "Princess Diana's Sideways-Looking-Up Smile made men want to protect her and women want to be like her",
                "The Bush Grin is a permanent Texan smirk - Birdwhistell found smiling most common in Atlanta, Louisville, Memphis, Nashville, and most of Texas",
                "In New York a smiler may be asked 'What's so funny?' - in Texas an unsmiling person is asked if they are angry",
                "Nancy Henley (UCLA): in social encounters women smile 87 percent of the time versus 67 percent for men",
                "Women are 26 percent more likely to return smiles from the opposite sex; unsmiling women read as unhappy, unsmiling men as dominant",
            ],
        ),
        "matrix": (
            "Matrix: Smile Type x Situation x Signal",
            "Map 8 smile behaviors - tight-lipped, twisted, drop-jaw, sideways-looking-up, Bush grin, half-moon, permanent down-mouth, and the genuine Duchenne smile - across 4 situations: negotiation, date, apology, and interrogation. Score each cell's likely message and its risk of being misread.",
            "A four-faced rotating die; each face is a situation. Smile cards slide through it and emerge stamped with the message each situation actually receives.",
            [
                "Dimberg (Uppsala): 120 volunteers' facial muscles mirrored happy and angry pictures even when told not to",
                "A smile causes the other person to reciprocate - even when both smiles are fake",
                "Ruth Campbell (UCL) believes a 'mirror neuron' triggers instant copying of faces and expressions we see",
                "Smiling at the opening stages of negotiation, while people size each other up, produces better outcomes",
                "The brain can identify a smile in an upside-down face - and separate the smile from every other part",
                "The upside-down Hugh Grant photo reads as relaxed and happy; inverted, it shows a completely different emotion",
                "Ekman: smiling and laughing faces affect our autonomic nervous system - we smile back and release endorphins",
                "Surrounded by miserable people, we mirror their expressions and become morose or depressed",
                "Provine: laughter is more than thirty times as likely in social situations than when alone",
                "Only 15 percent of our laughter has to do with jokes - laughter is mostly about building relationships",
                "Adults laugh about fifteen times a day; preschoolers laugh about four hundred times",
                "Baby girls smile far more than baby boys by eight weeks - women's extra smiling is probably inborn",
            ],
        ),
        "boss": (
            "Boss Battle: Direct the Laughter Room",
            "Run a hospital Laughter Room for one week: program 30-60 minute daily sessions of joke books, comedy films, and clown visits for 12 patients, then track painkiller use and discharge dates. Justify your schedule with the research - Cousins's cure, endorphins, and the physiology of laughter.",
            "A cheerful hospital ward with a clown at the door; a vitals board tracks patient mood, painkiller counts, and a bell curve of laughs per session as stay length shrinks.",
            [
                "Norman Cousins, diagnosed with ankylospondylitis and told to expect a painful death, cured himself with laughter",
                "Cousins rented Marx Brothers, Airplane, and The Three Stooges - six months later his illness was completely gone",
                "Cousins's cure led to Anatomy of an Illness and massive research into endorphins",
                "Endorphins released by laughter have a chemical composition similar to morphine and heroin and build the immune system",
                "Rubenstein found one minute of solid laughter provides up to forty-five minutes of subsequent relaxation",
                "Fry (Stanford): one hundred laughs give the body an aerobic workout equal to ten minutes on a rowing machine",
                "Laughter quickens breathing, oxygenates the blood, dilates the arteries, stimulates the appetite, and burns calories",
                "Davidson (UW-Madison): EEG shows intentionally produced smiles make the brain's left-hemisphere happy zone surge",
                "Cann (UNC): three weeks of comedy videos improved early-depression symptoms versus a nonhumorous control group",
                "People with ulcers frown more than people without - put a hand on your forehead while talking to train out the frown",
                "1980s Laughter Rooms: patients exposed to 30-60 minute daily sessions had shorter hospital stays and needed fewer painkillers",
                "Machleit (University of Cincinnati): humor in advertisements increases sales, acceptance of claims, and source credibility",
            ],
        ),
    },
]
