# -*- coding: utf-8 -*-
"""Phase 2 chapter data for The Body Language of Liars (Glass), chapters 9-12.
Each chapter: num, title, pages, domain, and 5 slots (scrub/dialogue/audit/matrix/boss),
each slot a 4-tuple (topic, player_mission, visual_frame_description, key_concepts[8-12]).
"""

D = "Body Language | Deception Detection"

CHAPTERS = [
    {
        "num": 9,
        "title": "The Voice of a Liar: Pitch, Volume, Tone, and Pacing",
        "pages": "165-179",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Vocal Tell Classifier",
            "Screen 15 voice clips: babyish high pitch, deliberately lowered pitch, too-soft speech, booming volume, fading sentence endings, creaky tone, shaky tremor, constant throat clearing, attacking bursts, nasal whine, dull monotone, sugary sweetness, frenetic speed, sudden staccato articulation, and nervous laughter. Classify each tell and the emotion leaking through it, and flag which ones are baseline quirks versus deception signals.",
            "A mixing-board console with waveform meters for pitch, volume, and pace; each clip lights up a tell label - CREAKY, WHINY, MONOTONE - while an emotion gauge shows the leak beneath.",
            [
                "The voice is a barometer of how we feel about ourselves",
                "Speech is processed by the auditory cortex, then passed to the limbic system",
                "An excessively high-pitched voice can signal insecurity, tension, or hidden anger",
                "A rise in pitch can be a tell for deception and righteous indignation",
                "Men who deliberately lower their voice may be over-compensating for insecurity",
                "People who speak too softly can be passive-aggressive and manipulative",
                "Liars often speak more loudly - if it's loud, it must be true",
                "Fading out at the ends of sentences can signal a lie",
                "The autonomic nervous system tries to shut down the lie on a physical level",
                "A creaky, raspy tone comes from tense throat and voice-box muscles",
                "A shaky voice comes from throat muscles alternately tightening and relaxing",
                "Nervous laughter cuts straight from the laugh to a serious expression, with no smile",
            ],
        ),
        "dialogue": (
            "Dialogue: The Too-Sweet Phone Call",
            "A former friend calls with a sugary-sweet, reassuring voice after months of silence and asks a favor. The pitch runs high, the pacing is frantic, and the sentence endings keep fading out. Choose the responses that check the tells without breaking the connection - then decide what to actually believe.",
            "A phone booth rendered as a lie-detector dashboard: pitch, volume, and pace needles wobble as the caller speaks while you pick replies from a response wheel.",
            [
                "No one is nice, happy, and cheery all the time - if they are, run",
                "Chronic sugary sweetness is usually a mask for hidden anger",
                "Sweet tones are used to gather information and turn it against you",
                "Sweet-talkers are the most manipulative of all liars",
                "Reassurance-seeking phrases fish for safety to continue the lie",
                "Fast, frenetic, cheerleader-style speech carries urgency meant to make you hop to it",
                "Frenetic talkers rope you into schemes that cost time or money",
                "Take your time to process everything they say and set boundaries",
            ],
        ),
        "audit": (
            "Audit: Your Own Vocal Baseline",
            "Record yourself answering 10 questions - first comfortably, then with a small lie. Measure your own pitch, volume, and pacing in both passes, then audit a deposition clip of a real case to separate baseline quirks from deception deviation.",
            "Side-by-side waveform strips: YOUR HONEST PASS versus YOUR LIAR PASS versus THE WITNESS; the audit flags where each voice deviates from its own baseline.",
            [
                "Tells are meaningless unless you have a good handle on the person's baseline",
                "Evaluate deviations from baseline with the greater context in mind",
                "Not all people with high-pitched voices are liars",
                "A shaky voice may be a neurological condition or medication side effect",
                "Not everyone who stammers is lying - a speech impediment is not a tell",
                "Southern drawls and medication-related slow speech are not tells",
                "The same vocal cue can mean different things in different contexts",
                "Context and baseline are what turn a voice feature into a tell",
            ],
        ),
        "matrix": (
            "Matrix: Vocal Tell x Emotion x Context",
            "Build the matrix for 8 vocal tells - fading endings, creaky tone, shaky voice, throat clearing, attacking bursts, nasal whine, monotone, sweet tone - mapping the underlying emotion (anxiety, anger, manipulation, depression, rage) and the context where each tell is most dangerous: interviews, dating calls, court, negotiations, and press appearances.",
            "An 8x3 matrix grid where each cell lights with a readout - 'CREAKY + CAUGHT IN LIE = Scott Peterson denying the 24th' - and the danger level glows redder as the grid fills.",
            [
                "Scott Peterson's voice creaked and rasped as he lied about calling Amber Frey",
                "Lance Armstrong's audible creakiness on Oprah may have indicated dishonesty",
                "Drew Peterson could barely squeak out a reply when confronted on the Today Show",
                "Bernard Madoff faded out so much you could barely hear his sentence endings",
                "O.J. Simpson spoke louder the more he was questioned",
                "Madoff was so soft-spoken people constantly asked him to speak up",
                "Tiger Woods' apology monotone made many doubt the sincerity of his feelings",
                "Psychopaths and sociopaths often speak in a dull, lifeless monotone",
                "Jodi Arias was described as sweet by everyone - right up to the murder",
                "Richard Heene's harsh, attacking tone fit his violence on Wife Swap",
            ],
        ),
        "boss": (
            "Boss Battle: The Deposition",
            "A 5-minute simulated deposition: the witness mixes a warm, engaging tone with fading sentence endings, throat clearing, and a sudden switch to formal, contraction-free answers. Decide in real time when to re-ask, when to press, and when to call out the shift - before the fake pleasantness lands.",
            "A dark boardroom with a single witness chair under a hot light; a live tell-strip ticks across the bottom, and each wrong call costs you credibility with the panel of attorneys.",
            [
                "Deposition tapes with creaky voices are a red flag in Glass's consultations",
                "When someone suddenly stops using contractions, he is probably lying",
                "Clinton's contraction-free denial: 'I did not have sex with that woman'",
                "A sudden switch to choppy, hyper-articulated cadence may signal deception",
                "Stuttering over crucial information is a huge tell for deception",
                "Attacking tones reveal hostility even when the words are nice",
                "Pay attention not just to what people say but the tone they say it in",
                "Swallowed words at sentence ends may be an indicator of lying",
            ],
        ),
    },
    {
        "num": 10,
        "title": "Speech Content: It's Not Just Words",
        "pages": "180-194",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Verbal Tell Scanner",
            "Screen 15 statements for verbal tells: excessive tangents, unrequested detail, filler-word overload, dropped contractions, tense shifts, question-repeating, honesty claims, reassurance fishing, 'I don't know' evasion, minimizing phrases, and table-turning. Tag each statement and rank how hard the tell screams.",
            "A teleprompter line-by-line scanner; each line is stamped with the tell it leaks - TANGENT, FILLER FARM, NO CONTRACTIONS, PROTEST TOO MUCH - plus a deception score.",
            [
                "Too much unrequested information means a high probability of lying",
                "Liars tend toward excess verbosity to try to sound more convincing",
                "Bush's 'the TV was obviously on' volunteered needless tangential detail",
                "The word 'obviously' is a red flag when describing a shocking event",
                "Filler words - 'uh,' 'um,' 'you know' - reflect deception under pressure",
                "Repeating the question buys time to think up an answer that passes muster",
                "Avoiding contractions - 'I did not' - stresses that they are not lying",
                "Psychopaths and sociopaths often confuse their verb tenses",
                "A sudden upward inflection mid-conversation can reveal reluctance",
                "Constant 'I don't know' and 'I don't recall' usually means they do know",
                "Mixing up words - 'hedging' for 'heading' - is the brain doing damage control",
            ],
        ),
        "dialogue": (
            "Dialogue: The Movie Alibi",
            "Your partner gives a detailed account of last night at the movies - unrequested specifics, a volunteered 'I would never cheat on you,' and your question repeated back at you. Practice the dialogue that tests the alibi without accusation, and decide what the extra details are actually covering.",
            "A living room couch at 11pm; a thought-bubble ledger tracks every volunteered detail while your reply options shift the mood lighting from warm to interrogative.",
            [
                "Sometimes a liar will bring up the truth all on his own",
                "Jennifer wasn't thinking about cheating - until Ken brought it up",
                "An excess of unrequested details signals a lie",
                "Repeating the question before answering is a time-buying tell",
                "Evasive answers like 'I was anywhere and everywhere' mean the guy is lying",
                "People who tell the truth are consistent - the story never changes",
                "Liars change their stories, embellish them, or omit significant details",
                "Inconsistency is one of the biggest and most obvious signs of lying",
            ],
        ),
        "audit": (
            "Audit: Transcript Forensics",
            "Audit three famous transcripts - Bush on the 9/11 classroom, Heene's CNN interview with Wolf Blitzer, and Madoff's court apology. Mark every tangent, filler, contraction-free denial, reassurance phrase, and excuse, then write the deception summary the attorneys would pay for.",
            "A forensic desk with three annotated transcripts pinned to the wall, each marked up in red with the tell found, the speaker line, and a suspicion score.",
            [
                "Bush said he saw the plane hit the tower 'of a TV' - no TV was on anywhere",
                "Bush claimed he was 'whisked off' but remained seated in the classroom",
                "Heene answered Blitzer with 'Well, you know...' and repetitive fillers",
                "Heene said 'appalled' three times - a display of righteous indignation",
                "Heene's 'I see where this is hedging' mixed up words under pressure",
                "Madoff's court apology was spoken in an emotionless monotone",
                "Madoff twisted to face his victims for one second, then immediately sat down",
                "Madoff was very complimentary - he played verbal music to clients' ears",
                "Bogus phishing emails are usually filled with flattering comments",
            ],
        ),
        "matrix": (
            "Matrix: Verbal Tell x Speaker x Setting",
            "For 10 verbal tells, map the speaker archetype - blameshifter, flatterer, minimizer, victim, protester - and the setting where each tell surfaces: court, press tour, cheating spouse, scam call. Score how each tell reads in each context.",
            "A 10x2 matrix of speaker archetypes and settings; filling a cell spawns a flashback clip - Armstrong blameshifting on Oprah, the Las Vegas call-center scammer turning hostile.",
            [
                "Lance Armstrong blamed the culture, his fans, his cancer, his mother, and Floyd Landis",
                "Aileen Wuornos blamed the police, society, and the court even hours before execution",
                "Clinton and his aides blamed the press for making up the Lewinsky story",
                "Lindsay Lohan's parents blame everyone but Lindsay for her behavior",
                "Sandusky repeated Costas's question: 'Am I sexually attracted to young boys?'",
                "Sandusky took awkward seconds-long pauses before answering",
                "Armstrong minimized: 'only EPO' and testosterone 'because of my testicular cancer'",
                "Armstrong detached by saying 'It's a flaw' instead of 'I have a flaw'",
                "O.J. referred to himself as 'you' when describing his planned answer to his kids",
                "The fake SAG union boss turned hostile when the therapist hung up on him",
                "The 702 area code traced to a call center in Las Vegas running a scam",
            ],
        ),
        "boss": (
            "Boss Battle: The Live Interview",
            "You anchor a live interview with a celebrity who cheated and got caught. Every answer hides a tell: tangents, question-repeating, filler overload, 'honestly' claims, and blameshifting. Choose the follow-up questions that expose the inconsistencies on air - without letting the guest steamroll you.",
            "A broadcast studio with a live red light; a ticker of verbal tells scrolls under the guest's face, and each follow-up you pick either cracks the story or lets the guest wriggle free.",
            [
                "'Honestly' and 'to tell you the truth' mean they are trying to convince you",
                "'You better listen to me' and 'I don't care if you don't believe me' usually mean lying",
                "In Shakespeare's words, 'the lady doth protest too much'",
                "Clinton's admonishing preamble: 'I am gonna say this again'",
                "Righteous indignation is common to almost all liars",
                "'I was only kidding' - they are not kidding; the insult is exactly how they feel",
                "A liar who says 'I don't know that I have a great answer' knows exactly why",
                "Liars who blameshift believe that nothing is their fault",
            ],
        ),
    },
    {
        "num": 11,
        "title": "Your Lying Eyes: Lovers Who Cheat and Deceive",
        "pages": "195-208",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Couple Photo Tell Finder",
            "Screen 10 paparazzi-style photos of couples: walking ahead, looking in opposite directions, big physical gaps, inward-pointing toes, one blocking the other, hands that never touch. Classify the tell, the likely relationship status, and the projected time to breakup.",
            "A contact-sheet wall of couple photos; each gets marked up with arrows and heat lines - GAP, TOES, GAZE LINES - and a breakup countdown meter starts ticking.",
            [
                "Walking two to three steps ahead of your mate signals lost interest",
                "Ashton Kutcher was photographed steps ahead of Demi Moore a year before the end",
                "Walking in front without grabbing your hand means he wants to get away from you",
                "Couples consistently looking in different directions are not like-minded",
                "Shriver and Schwarzenegger rarely photographed looking in the same direction",
                "Too much physical space and too little contact predicts trouble",
                "Kim Kardashian and Kris Humphries' marriage lasted only 72 days",
                "Affection has to be reciprocated if a relationship has any chance of lasting",
            ],
        ),
        "dialogue": (
            "Dialogue: The Couple Next Door",
            "Jenny and Andy - the couple you had dinner with last week - are divorcing. Replay the night: he ordered for her, slapped her wrist off the bread, and said 'Relax, I'm only kidding' when she frowned. Practice the phone conversation with Jenny that gets the real story, and the questions that test whether Andy's jokes were ever jokes.",
            "A dinner table flashback rendered in sepia; each memory - the wrist slap, the turned-away chairs, the frown - is a chip you lay down as you talk to Jenny on the phone.",
            [
                "'I was only kidding' - in almost all cases, the rude statement is how they feel",
                "Andy belittled Jenny and made her the brunt of his jokes",
                "He ordered for her and lightly slapped her wrist when she reached for bread",
                "The couple sat facing away from one another and barely looked at each other",
                "Jenny shook her head and frowned when he told her to stop",
                "Controlling 'handling' of a partner is not a good sign for a relationship",
                "Put-downs disguised as jokes are a red flag in couples",
                "What looks like kidding around can be a private nightmare",
            ],
        ),
        "audit": (
            "Audit: The Anniversary Album",
            "Pull 10 photos from your own relationship - or a friend's you know well - and score them for the eight tells: walking ahead, opposite gazes, space gaps, wrong-pointing feet, limelight blocking, handling, and unreciprocated touch. Then compare your scores against the couple's own claim that everything is fine.",
            "A scrapbook annotated like a crime board: red circles around hand gaps and foot angles, with a split screen of the COUPLE'S STORY versus the BODY STORY.",
            [
                "People are even in denial about their own relationships and miss the signs",
                "Katie Holmes' toes pointed inward, pigeon-toed, at the Mission Impossible premiere",
                "Tom Cruise's toes pointed toward Katie, his body leaning in with a relaxed jaw",
                "Katie's lower jaw and facial muscles appeared very tense",
                "No matter how much spin handlers put on it, the signs cannot be hidden",
                "Kim and Kris rarely touched, and attempts at touching looked awkward",
                "Tiger and Elin kept extreme physical distance during reconciliation",
                "Elin looked down and not at Tiger - another bad sign for the marriage",
            ],
        ),
        "matrix": (
            "Matrix: Couple Cue x Position x Meaning",
            "Map 8 couple cues - walking ahead, opposite gazes, space gap, inward toes, blocked partner, handling, non-reciprocated touch, no hand-holding - against each partner's position in the frame and what the cue means for the relationship's future.",
            "An 8x3 matrix where each cell renders a stick-figure couple in that configuration, annotated with the relationship verdict and the celebrity photo that proved it.",
            [
                "Russell Brand blocked Katy Perry by getting in front of her",
                "Russell's intense stare was focused on the camera, not on his wife",
                "Marc Anthony constantly positioned or pulled Jennifer Lopez behind him",
                "J-Lo finally looked happy and less tense after the split",
                "Tiger looked straight ahead, hands cupped, while Elin leaned in with her arm around him",
                "Chris Brown ignored Rihanna's affection, absorbed in the basketball game",
                "At the 2013 Grammys Rihanna put her head on Chris's shoulder - he did not reciprocate",
                "Rihanna held onto herself, as if in mute protest",
                "A competitive couple destroys love no matter how much physical chemistry they have",
            ],
        ),
        "boss": (
            "Boss Battle: The Newsmaker Couple",
            "The press is about to run a story on a celebrity couple who insist they are fine. Review the final 12 photos before publication: separate the staged romance from the leaked truth, decide whether the story runs, and predict - on air - how long the marriage lasts.",
            "A newsroom deadline desk under a countdown clock; each photo either gets CUT (staged) or RUNS (tell evidence), and the live prediction ticker adjusts with every call you make.",
            [
                "Glass was the first to predict the demise of the Kardashian-Humphries marriage",
                "The couple appeared awkward and unaffectionate - nothing like lovers",
                "Their reality show dynamic showed even more distance than affection",
                "Tom had no clue Katie was miserable - his body language said he loved her",
                "Katie's body language revealed disdain six months before she left",
                "Serious signs of unhappiness were visible well ahead of the east coast move",
                "Katie secretly gathered her belongings and moved out with daughter Suri",
                "Examining old photos could have let Tom spot trouble on the horizon",
            ],
        ),
    },
    {
        "num": 12,
        "title": "A Profile of the Most Toxic Liar of All: The Psychopath/Sociopath",
        "pages": "209-216",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Psychopath Tell Radar",
            "Screen 12 behaviors from interviews: past-tense speech, 'because' clauses, filler-heavy pauses, monotone delivery, fake tears wiped one eye at a time, mask-like smiles, unblinking stares, hands interlocked, sudden sweating, feigned illness, grandiose claims, and self-contradiction within one sentence. Flag each as psychopathic or merely nervous.",
            "A radar scope with concentric rings; each clip paints a blip labeled with the trait - MONOTONE, CROCODILE TEARS, GRANDIOSE - and the threat ring glows redder with every hit.",
            [
                "Psychopaths are organized and methodical - like Dahmer and Bundy",
                "Sociopaths are more disorganized and impulsive - like Scott Peterson",
                "Psychopaths and sociopaths comprise just one to two percent of the population",
                "Psychopaths use the past tense more often than the present tense",
                "Researchers at the University of British Columbia found psychopaths use 'because' and 'so that'",
                "Cause-and-effect statements frame the crime as a plan's logical outcome",
                "Psychopaths use twice as many words about basic needs like food, shelter, and clothing",
                "Nonpsychopathic murderers talk more about spirituality, religion, and family",
                "Most psychopaths have a history of being cruel to animals",
            ],
        ),
        "dialogue": (
            "Dialogue: The Charming New Friend",
            "The charming new acquaintance at the party is too good: lavish compliments, intense eye contact, rapid questions about what makes you sad and angry, and one chilling joke about animals. Practice the exit dialogue that stays polite, reveals nothing, and gets you out of the room.",
            "A party scene where the charmer's compliments hover in glowing text while his questions tighten into a web; your responses either give ground or open a polite escape route.",
            [
                "Psychopaths ask a lot of questions to figure out your emotional hot buttons",
                "They play upon those emotions - emotions they lack entirely",
                "Their verbal manipulations can be persistent and inexorable",
                "They make good first impressions because they say what you want to hear",
                "An insensitive or sadistic remark can inadvertently reveal who they are",
                "Never ignore your body's response warning you that something is wrong",
                "They are highly sensitive to perceived slights and can turn verbally or physically hostile",
                "They cajole you with excessive compliments and flattery",
                "They see people as objects, vehicles to satisfy their desires and needs",
            ],
        ),
        "audit": (
            "Audit: Interview Forensics - The Murderer's Tape",
            "Audit three prison interviews: Kuklinski with psychiatrist Park Dietz, Bundy's last interview hours before execution, and Wuornos the night before hers. Tag the past-tense patterns, cause-effect justifications, victim-speak, and grandiose self-claims, then rate each subject on the psychopath profile.",
            "Three tape reels on a forensic deck; each transcript gets tagged with green (truthful risk) and red (manipulation) labels as you scrub through the audio.",
            [
                "Kuklinski admitted he was angry at Dietz but didn't know why - he felt judged",
                "Bundy's last prison interview showed precise, hyperarticulated speech",
                "Wuornos insisted: 'I didn't do anything as wrong as they said'",
                "Wuornos blamed the police and society for allowing her crimes",
                "Charles Manson does the same kind of blameshifting from behind bars",
                "Grandiose speaking springs from the psychopath's over-inflated sense of entitlement",
                "The psychopath speaks of himself in grandiose terms while taking no responsibility",
                "Psychopaths often contradict themselves, even within a single sentence",
                "Rephrase a question slightly and the psychopath may tell you the truth",
            ],
        ),
        "matrix": (
            "Matrix: Psychopath Trait x Channel x Interview",
            "For 8 psychopath traits - past-tense speech, cause-effect reasoning, monotone voice, crocodile tears, weighty stare, mask-like smile, rigid posture, swagger - map the channel where each shows (voice, face, body, speech) and the interview where it surfaced: the Today Show, Diane Sawyer, Oprah, or the courtroom.",
            "An 8x2 matrix of trait and channel; each cell fires a clip - Drew Peterson's clasped hands on Today, Susan Smith's fake tears, Gacy's painted-on clown smile.",
            [
                "Drew Peterson's intense, compelling gaze was evident on the Today Show",
                "Peterson sat with hands clasped and never deviated from his body position",
                "The weighty stare is a type of control",
                "Staring then suddenly ignoring is intermittent operant conditioning",
                "Psychopaths may suddenly sweat or their skin flushes as they heat up with anger",
                "Psychopaths often move in closer or lean in when they speak",
                "The psychopath's smile is mask-like and tight-lipped, never genuine",
                "Genuine smiles raise the apples of the cheeks, squint the eyes, and show teeth",
                "Gacy dressed as a clown, painting a happy expression on his emotionless face",
            ],
        ),
        "boss": (
            "Boss Battle: The 1 Percent",
            "You sit across from a suspect in a missing-person case. He blinks rarely, speaks in a past-tense monotone, wipes under one eye without tears, and describes his 'loss' as a plan's logical outcome. Classify the tells in real time and choose the rephrased question that cracks the contradiction before the interview ends.",
            "A bare interrogation room, two chairs, one camera; a trait-meter builds from COLD to CALLOUS to CONVICTED with every tell you correctly call - one wrong call and the mask snaps back on.",
            [
                "Fake tears are usually wiped underneath each eye, one at a time",
                "Genuine tears are wiped from both eyes at once",
                "Real crying makes the small muscles on either side of the bottom lip droop downward",
                "The psychopath's lower lip stays stationary or turns up in a slender smile - duping delight",
                "Scott Peterson's fake distress was the dead giveaway in Diane Sawyer's interview",
                "Susan Smith's fake tears raised suspicions that she killed her children",
                "Psychopaths can switch from tears to smiles in a millisecond, with no transition",
                "Psychopaths feign illness or ailment - Bundy's removable arm cast lured in young women",
                "A puffed-out chest and a swagger mark the psychopath's walk",
                "Sandusky walked to court with hands in both pockets - something to hide",
            ],
        ),
    },
]
