# -*- coding: utf-8 -*-
"""Phase 2 chapter data for The Body Language of Liars (Glass), chapters 7-8.
Each chapter: num, title, pages, domain, and 5 slots (scrub/dialogue/audit/matrix/boss),
each slot a 4-tuple (topic, player_mission, visual_frame_description, key_concepts[8-12]).
"""

D = "Body Language | Deception Detection"

CHAPTERS = [
    {
        "num": 7,
        "title": "The Body Language of a Liar",
        "pages": "81-127",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Liar's Body - Breath, Skin, Posture, Hands, Feet",
            "Screen 12 short interview clips and flag each deception tell by body region: upper-chest breathing instead of abdominal, cheek-puff exhales, flushing or upper-lip sweat, hunched turtle posture, collar tugging, gulps, itchy scratchies, palm-toward-body gestures, hidden hands, and heel off the ground. Rate each tell's strength and mark the exact region that gave the liar away.",
            "A split-screen interrogation suite where each clip renders as a wireframe body with region overlays: the chest and shoulders glow when the breathing shifts, the face blooms red when the flush appears, and the hands and feet light up as each tell fires. A tell-strength meter per region ticks across the bottom of the screen.",
            [
                "Calm breathing moves the abdomen; deception shifts breathing to the upper chest and shoulders",
                "The cheek-puff exhale oxygenates to flush CO2 buildup - a huge tell (O.J. Simpson on jury-selection day, Las Vegas 2008)",
                "Flushed, blotchy skin results from adrenalin and expanding capillaries; redness shows on cheeks, nose, ears, and neck",
                "Upper-lip sweat accumulates because the upper-lip muscles tense during deception (Clinton's Lewinsky denial)",
                "Customs inspector Diana Dean caught 'Millennium Bomber' Ahmed Ressam on upper-lip sweat at Port Angeles, December 1999",
                "Liars hunch into a quasi-fetal, turtle-like position when caught, minimizing to feel small (Chris Brown's Not Guilty plea)",
                "Shrugging shoulders at a critical question signals lying by omission (Barry Bonds; O.J.'s apology to Judge Jackie Glass)",
                "Being 'taken aback': the body jerks backward, rigid and erect, the instant a lie is exposed (O.J. with Catherine Crier)",
                "Desperate liars lean forward to fake intimacy and ingratiate (Scott Peterson with Diane Sawyer; Jodi Arias on 48 Hours)",
                "Rigid, catatonic stillness is the 'fight' response; fidgeting is 'flight' (Drew Peterson; Nicki Minaj vs. Mariah Carey)",
                "The head jerk, head bow, and head cock or tilt after a pointed question each signal deception (Armstrong, Tiger Woods 2010, O.J.)",
                "Covering the throat, collar-tugging 'hot under the collar,' and the big gulp betray a dry, vulnerable throat (Al Pacino; O.J. loosening his tie awaiting the verdict)",
            ],
        ),
        "dialogue": (
            "Dialogue: The Forward-Lean Interrogation",
            "Play both sides of an interrogation: as the interviewer, push a suspect whose shoulders have hunched and whose hand keeps covering his throat, and decide when to probe deeper or back off; as the suspect, try to stay calm and watch how each tell - the cheek-puff, the shrug, the collar tug - leaks anyway. Replay the scene and catch the tells before they fire.",
            "A two-panel interview room: on the left, the interviewer's question cards; on the right, the suspect's body renders in heat - hunch glow, throat-cover flash, forward lean - as you decide whether to press or pivot.",
            [
                "A hunched, turtle-like posture after a question is law enforcement's cue to become more direct and probe more deeply",
                "The forward lean is a manipulative bid for false intimacy from liars desperate to be believed",
                "Hands over the throat or groin mark vulnerability when testimony hits a nerve (John Edwards covering his groin on Nightline)",
                "Tugging the collar or loosening the tie signals 'hot under the collar' from autonomic body heat",
                "The big gulp - a dry, scratchy throat from diminished saliva - forces a midsentence swallow to lubricate the lie",
                "Finger-pointing is righteous indignation: the liar makes YOU wrong and shifts focus onto your lack of trust",
                "Words and body disagree: the truth leaks when a liar's head nods while he denies (Armstrong's incongruence with Oprah)",
                "The 'itchy scratchies' - sudden scratching of chin, face, or neck - follow the lie's topic as blood flow expands capillaries",
                "Forward-leaning criminals rarely move from the position during entire interviews (Drew Peterson, Jodi Arias)",
                "A shrug paired with 'I didn't want to hurt any of these guys' belied O.J.'s intent - Judge Jackie Glass rejected the apology and gave him 15 years",
            ],
        ),
        "audit": (
            "Audit: Deception Tell Log",
            "Log five real or filmed conversations this week: for each, record the speaker's baseline breathing, posture, and hand position, then note every deviation - chest breathing, cheek-puff, sweat breakout, shrug, lean, collar tug, gulp, scratch, hidden hands, heel lift - and whether the deviation tracked a sensitive topic. Score each deviation as a possible tell.",
            "A timeline journal where each conversation draws two tracks: the baseline as a steady line and each deviation as a red spike. Every spike is annotated with a region label, and the audit scores which topics reliably spike the line.",
            [
                "Context is key: comfort habits and baselines decide whether a cue is a tell",
                "Sudden posture stiffening with shoulders rolling forward tracks deception",
                "The heel off the ground or toes pointed toward the exit signal the 'flight' part of fight-or-flight",
                "The pigeon-toed stance marks guardedness and hidden agendas (Katie Holmes's toes inward before leaving Tom Cruise)",
                "Feet gravitate toward people we like - Brad Pitt's right foot inched toward Angelina while both hid their hands",
                "Brushing imaginary lint, hair play, and finger-picking are self-soothing around lies (Mayumi Heene's thigh-brushing on CNN)",
                "Cupped hands and small fists signal anger when the truth hits too close to home (Armstrong's cupped fingers in Austin, 2006)",
                "Hands in pockets can be comfort - but sudden pocket-thrusting mid-conversation signals hiding (Kris Humphries's jammed fingers)",
                "A contradictory double gesture - one palm up, one palm down - reveals mixed truth and self-deception (Lindsay Lohan)",
                "Sudden reddening of the ears, nose, and neck accompanies increased blood flow during deception (Armstrong's interview redness)",
            ],
        ),
        "matrix": (
            "Matrix: Body Region x Tell x Liar Case",
            "Build the 6x4 cross-reference grid: body regions (breath, skin, posture, head, hands, feet) against documented liar cases (Armstrong, O.J. Simpson, Clinton, the Heenes, Drew Peterson, Katie Holmes). Assign the tell that fired in each cell, mark which cells repeat across cases, and derive each liar's personal signature cluster.",
            "A glowing 6x4 matrix on a courtroom wall; each populated cell holds a labeled snapshot of the tell in action, and cells that repeat across cases pulse in red, revealing the universal tells of deception.",
            [
                "Armstrong's interview signature: chest breathing, gulps, itchy chin scratches, palms toward his body, flared nasal breathing",
                "O.J.'s courtroom signature: cheek-puff exhales, collar and tie loosening, shrugging apology, forward lean, jutting jaw",
                "Clinton's denial signature: angry finger-pointing, icy glare, pursed lips, and upper-lip sweat",
                "The Heene balloon hoax: Falcon's mouth-covering confession, Mayumi's thigh-grooming, Richard's hemming and backpedaling",
                "Drew Peterson: stone-still rigid posture with clasped hands, plus a head cock when the question about Stacy landed",
                "Katie Holmes vs. Tom Cruise: her pigeon-toed feet turned inward while his right foot pointed at her - mismatched feet, mismatched feelings",
                "Posture collapse from ramrod straight to hunched marks the fall from cocky to caught (Jerry Sandusky's arc)",
                "The universal cluster: breath shift, redness or sweat, protective gestures on vulnerable parts, and feet toward the exit",
            ],
        ),
        "boss": (
            "Boss Battle: The Courtroom Tell-Off",
            "You are the body-language consultant behind the witness stand: 12 video clips of a defendant speaking under oath, one pointed question each, 90 seconds total. Decide under time pressure whether each response is LIE or TRUTH using only the body tells - and if you catch a lie, name the exact region that gave it away. Land 10 of 12 verdicts to win the case.",
            "A dark courtroom where each clip loads into a decision booth; a 90-second fuse burns down as four region badges - BREATH, SKIN, HANDS, FEET - light up when their tells fire. Your verdict stamp slams down before the fuse hits zero.",
            [
                "The sudden cheek-puff exhale is the single biggest breathing tell of a liar",
                "Beads of sweat on the upper lip while denying involvement is a classic deception signal",
                "A body that jerks backward after a question has been 'taken aback' by exposure",
                "Hands suddenly thrust into pockets or behind the body hide the truth along with the hands",
                "Rigid, catatonic stillness over-controls the body the way micromanaging liars do (Nicki Minaj on the panel)",
                "The turtle-like hunch with bowed head marks shame and guilt despite a Not Guilty plea (Chris Brown in court)",
                "Righteous indignation - finger-pointing and admonishment - is the liar turning the tables on the questioner",
                "Sudden scratching of the chin, face, or neck right after a hard question reflects the autonomic nervous system's itch",
            ],
        ),
    },
    {
        "num": 8,
        "title": "The Facial Language of a Liar",
        "pages": "128-164",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Liar's Face - Eyes, Nose, Mouth, Jaw",
            "Screen 12 freeze-frames of famous faces and flag each facial tell: broken eye contact, the unblinking stare, wide eyes of surprise, rapid blinking, shifty eyes, squinting, raised brows and wrinkled forehead, nose-touching, lip licking, the fake smile, lip swing, pursed lips, lip biting, and the jutting or dropped jaw. Sort each flag by facial zone and judge every cue against the person's baseline strip.",
            "A photo-forensics wall where each face is dissected into zone overlays - eyes, nose, mouth, jaw - and each zone glows when its tell appears. A baseline strip under every face shows the person's normal range so no flag is ever judged in a vacuum.",
            [
                "The lateral geniculate nucleus (LGN), tied to the limbic system, links eye movements to emotional state",
                "Breaking eye contact hides from the detection in your face; the direction looked (right, left, up, down) carries no special significance",
                "Madoff's cold, unblinking stare seduced the nation's richest investors - con men overcompensate with fixed eye contact",
                "The wide eyes of surprise expose 'duped delight' - the liar's thrill at getting away with it (Armstrong, O.J., Lindsay Lohan)",
                "Rapid blinking tracked Nixon's 'I am not a crook' speech and John Edwards's 'physically impossible' paternity lie",
                "Squinting during a lie is involuntary self-evaluation: 'I don't want you to detect my deception'",
                "University of British Columbia researchers found small facial muscles betray liars through tension and autonomic response",
                "The nose actually swells and itches as capillaries expand - the Pinocchio effect, to a much smaller degree",
                "Flared nostrils (the alae) signal the liar's short-breath need for more oxygen under autonomic overdrive",
                "Dried spittle at the corners of the mouth and lip licking mark cotton mouth under stress (O.J. awaiting his sentence)",
            ],
        ),
        "dialogue": (
            "Dialogue: The Baseline Check",
            "Interview a coworker twice: first, ten minutes of easy questions to capture their facial baseline - eye-contact style, blink rate, smile shape, nose-touching habits - then the hard questions about a missing report. Practice asking one pointed question, watching for departures from baseline, and following a tell with a direct probe rather than an accusation.",
            "A split-screen conversation: the left half plays the baseline pass and the right half the hard pass; departure cues draw red brackets on the right screen as the dialogue tree offers you PROBE, PAUSE, or REPHRASE.",
            [
                "Establish the baseline before judging - some people always look around the room when they speak",
                "A straight shooter who normally holds gaze but breaks it at the critical moment reveals the deviation",
                "Breaking eye contact is one of the most obvious signs of deception - liars want to control, not connect",
                "Liars look down to focus on the tale they are spinning and avoid others' negative reactions (Tiger Woods, John Edwards)",
                "Covering or pressing the eyes relieves the muscular fatigue and tension of keeping a lie straight",
                "A genuine smile needs four signs: eye crinkles, raised cheek apples, teeth showing, lips parted and slanting upward",
                "The fake smile - tense, tight-lipped, eyes uninvolved - masks true feelings (Edwards's mug shot grin)",
                "The lip swing leaks hidden negative feelings; the upper-lip version is called the 'lip of disgust'",
                "Pursed lips after a lie say 'I've said my lie and now I'm done' - Clinton's wordless punctuation",
                "Tells are meaningless without baseline, context, and timing - verify before you accuse",
            ],
        ),
        "audit": (
            "Audit: Facial Baseline Log",
            "Log the facial baselines of three people you see daily - their normal eye contact, blink pace, smile shape, and nose habits - then note every deviation you catch this week, the topic that triggered it, and whether it repeated. Build the deviation-pattern map that predicts when each person is holding something back.",
            "Three profile cards with animated face-lines: each card draws the person's normal range as a shaded band, and each observed deviation spikes above the band, tagged with the topic that caused it. Repeated spikes etch a permanent pattern line.",
            [
                "Facial language analysis requires noting departures from a person's usual expressions and movements",
                "Rapid and unusual blinking is an automatic stress reaction - the fear of being found out",
                "Shifty side-to-side eye searching appears when a liar hunts for an answer (Nixon: 'I have never obstructed justice')",
                "Eye rubbing soothes lying fatigue - the same autonomic response as the itchy scratchies",
                "Children rub their eyes and sneeze more when lying; their nasal membranes are more sensitive to autonomic changes",
                "Raised eyebrows and a wrinkled forehead signal surprise and indignation that integrity is being questioned (O.J. on Court TV)",
                "The dropped jaw marks the moment the lie is exposed - the face literally loses control (Richard Heene with Meredith Viera)",
                "The clenched jaw with pulsating muscles under the cheekbone masks anger when testimony lands (O.J.'s trial; Armstrong)",
                "Jutting the jaw forward after lying is defiance against being doubted (O.J. questioned about Nicole)",
                "Repeated tells on the same topic are the pattern; a single cue without a baseline is just data",
            ],
        ),
        "matrix": (
            "Matrix: Facial Cue x Context x Verdict",
            "Map 10 facial cues (eye avoidance, staring, wide eyes, rapid blink, squint, nose scratch, cotton-mouth lick, fake smile, lip swing, pursed lips) against 3 contexts (police interview, celebrity press junket, family dinner) and mark each cell LIKELY TELL, DEPENDS, or NORMAL. Rescore the same cue in every context before any verdict is allowed.",
            "A 10x3 matrix table that re-lights as the context shifts: squinting glows LIKELY TELL in the interrogation column but NORMAL in the bright-outdoor column - context and baseline rule every verdict.",
            [
                "Eye avoidance in a police interview is a likely tell; in a shy family dinner it can be normal",
                "The unblinking stare can be honest sincerity - or the con man's seduction tool (Madoff charmed investors with his)",
                "Wide eyes of surprise fire when the liar is busted or senses no one believes her (Lohan in the Beverly Hills courtroom)",
                "Squinting during deception is involuntary; squinting in sunlight is just squinting",
                "Nose-touching: children do it when they hear parents lie; celebrities do it to dodge relationship questions (Jennifer Aniston)",
                "Cotton mouth - dry mouth, thick tongue, spittle - tracks interrogation stress; suspects gulp the offered water down",
                "The fake smile: clenched teeth, drooping cheek apples, dead eyes - Edwards's mug shot and Sandusky's courtroom grin",
                "The lip swing leaks contempt for a rival before the insult is spoken (Professor X's lip of disgust toward Professor Y)",
                "Duping delight - a smug smile where sadness belongs - leaks true pleasure (Schwarzenegger with Leslie Stahl; Bali bomber Muklas)",
                "No cue is a verdict without the person's baseline and the moment's context",
            ],
        ),
        "boss": (
            "Boss Battle: The 60 Minutes Face-Off",
            "You are the investigative journalist: five suspects, one unforgiving camera, and one question each that could crack their story - a fake pregnancy claim, a stolen-pension denial, an affair denial, a missing-funds excuse, a rigged-game defense. Under a 60-second clock per face, classify each as TRUTH, LIE, or HOLDING BACK, then cite the exact facial cue that decided the verdict. Land 4 of 5.",
            "A 60 Minutes-style studio: the interviewer's chair faces a monitor wall where each suspect's face runs in slow motion, bracketed by facial zones; a 60-second sweep hand crosses the screen as you stamp TRUTH, LIE, or HOLDING BACK on each verdict card.",
            [
                "When a lie is exposed, the jaw muscles suddenly loosen - the dropped jaw with wide eyes (Lindsay Lohan's courtroom shock)",
                "Blinking rapidly only on the hard questions marks the liar's tic (Edwards's paternity denial on Nightline)",
                "The shifty-eyed search accompanies denials like Nixon's 'I have never obstructed justice'",
                "The fake smile hides the truth: mouth smiling while eyes and cheek apples stay dead (Madoff's tight-lipped grin)",
                "The lip swing leaks the truth about feelings - Susan Smith's lip swing alongside her fake tears",
                "The pursed-lip press says the speaker has nothing more to reveal (Clinton; Tiger Woods before more mistresses came forward)",
                "Righteous indignation - narrowed eyes, tight angry jaw, a flash of mockery - signals deception (Heene: 'ticked off at these false accusations')",
                "Before stamping any verdict, check baseline, context, and timing - tells alone are meaningless",
            ],
        ),
    },
]
