# -*- coding: utf-8 -*-
"""Phase 2 chapter data for The Body Language of Liars (Glass), chapters 4-6.
Each chapter: num, title, pages, domain, and 5 slots (scrub/dialogue/audit/matrix/boss),
each slot a 4-tuple (topic, player_mission, visual_frame_description, key_concepts[8-12]).
"""

D = "Body Language | Deception Detection"

CHAPTERS = [
    {
        "num": 4,
        "title": "The Seven Reasons Adults Lie",
        "pages": "46-58",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Seven Reasons Classifier",
            "Work through 14 brief deception vignettes and classify each lie by its motive among Glass's seven reasons: avoiding hurt feelings, ulterior motives, self-preservation, favorable image/rejection-avoidance, avoiding punishment, protecting others, or motivating others. Flag the cases where two motives overlap and name the dominant one.",
            "A courtroom-style evidence board split into seven colored columns, each labeled with a reason. Lie cards fly in and the board slots each into its motive bin; ambiguous cards shimmer between two columns until you lock the verdict.",
            [
                "Mark Twain's 1882 essay 'On the Decay of the Art of Lying': 'everybody lies - every day; every hour'",
                "Reason 1: lying to avoid hurting others' feelings - the Seinfeld 'Ugly Baby' episode, where Kramer blurts that the baby looks like Lyndon Johnson",
                "The Hamptons baby lie: Jerry and Elaine say 'gorgeous' while privately calling the baby a Pekingese ('too much chlorine in that gene pool')",
                "Reason 2: lying for ulterior motives - insincere flattery wielded like a weapon to keep a job, make a sale, or woo a lover",
                "Salesman Mike: 'Every lady is beautiful to me when she gives me her credit card and I charge up a sale'",
                "Reason 3: lying for self-preservation - the 1997 film Liar Liar, where Jim Carrey's truth-bound attorney calls his boss a 'pedantic, pontificating, pretentious bastard'",
                "Dave was fired for being too honest: he raised his voice in criticism and his supervisor focused on his anger, not his argument",
                "Witnesses lie after crimes because being labeled a snitch can be a death knell in certain communities",
                "Reason 4: lying to present a favorable image - Marie, 58, got zero responses with her real age, then overwhelming responses when she claimed 45",
                "Reason 5: lying to avoid punishment - Clinton lied about Lewinsky to avoid losing his marriage and presidency; O.J. Simpson lied to avoid prison",
                "Reason 6: lying to protect others - Cindy Anthony lied on the stand about chloroform searches to spare her daughter Casey from death row",
                "Reason 7: lying to motivate others - doctors tell patients they will walk again, and positive lies can become self-fulfilling prophecies",
            ],
        ),
        "dialogue": (
            "Dialogue: The Ugly Baby Test",
            "A new mother asks you, 'Isn't she gorgeous?' while her partner, her best friend, and a blunt acquaintance watch. Read the room: the partner expects a kind lie, the friend expects honesty. Choose the reply that keeps the peace without destroying your credibility, then explain which of the seven reasons your lie serves.",
            "A nursery scene rendered in soft pastels; the crib glows, and three NPC faces float beside it with expectation meters above their heads. Your reply options appear as thought-bubbles, each shifting the three meters.",
            [
                "Kramer's blunt 'She looks like Lyndon Johnson' shows the social cost of total honesty",
                "Elaine's strained 'Yes, yes. Gorgeous' shows the social cost of lying badly",
                "Most adults were taught as school children that lying to prevent hurt feelings is okay",
                "The ugly knitted Christmas sweater: we smile and say 'Thank you' even though we hate it",
                "Boyfriends learn they can't be 100 percent honest when asked 'Does this make me look fat?'",
                "An honest insult wounds self-esteem and damages your own best interests",
                "Total honesty to everyone would be 'tantamount to social suicide'",
                "Lying to avoid hurt feelings is a small lie that preserves relationships",
            ],
        ),
        "audit": (
            "Audit: Motive Log of a Liar's Week",
            "Audit one week of your own everyday lies, real or reconstructed from the chapter's examples ('Fine', 'you look great', 'I'll call you later'). Log each lie, tag its trigger, classify it under one of the seven reasons, and judge whether it was protective, selfish, or self-destructive - then compare your tally against the chapter's claim that most lies go unnoticed by the liar.",
            "A weekly calendar grid, each day covered in sticky notes. You drag each lie-note into one of seven motive slots on a side panel; the grid glows red where a lie was costly and green where it preserved something.",
            [
                "People lie automatically: 'How are you?' - 'Fine' - even when the truth is bankruptcy and a failing marriage",
                "'I'll call you later' said with no intention of calling is a lie of politeness",
                "Telling someone she looks great when her face is 'all Botoxed' is a lie we tell without realizing it",
                "Insincere flattery is a weapon: 'every woman wants to hear she is hot and looks good, even if it is a lie'",
                "Buttering up your dad so he loans you the car is a lie told for your own gain",
                "Frenemies: gritting your teeth through 'necessary (if galling) pleasantries' is everyday self-preservation lying",
                "Linda lied about her disastrous European cruise to make her life look enviable to colleagues",
                "Embellishing achievements and omitting failures protects the ego and self-perception",
                "Nina faked morning enthusiasm for sex to keep her marriage and lifestyle intact",
                "Being too honest can get you fired - Dave's year of unemployment taught him to keep his mouth shut",
            ],
        ),
        "matrix": (
            "Matrix: Motive x Target x Consequence Grid",
            "Score 9 lies (ugly-sweater thank-you, boss flattery, witness denial, dating-age lie, doping denial, chloroform cover-up, doctor's white lie, Armstrong 'story' lie, Te'o continued lie) across the axes of motive, target (stranger/intimate/authority/public), and consequence (social glue, financial, freedom, life). Mark which cells map to which of the seven reasons and where the chapter's exceptions (protective heroes) break the pattern.",
            "A 9x9 data wall: rows are lies, columns are motive, target, and consequence; each cell fills with a color from the seven-reason palette. The Armstrong row and the Judy Feld Carr row flash as opposite poles of the same grid.",
            [
                "Perceived harshness of punishment is directly proportional to the tenacity of the lie - hence death-row inmates die proclaiming innocence",
                "An armed robber caught on video still denied the robbery to avoid prison time",
                "Michelle's husband denied his affair despite phone records, Victoria's Secret receipts, and hotel bills",
                "Lance Armstrong kept lying about doping because his cancer-victim 'story' sounded good to the public and press",
                "Manti Te'o kept up his dead-girlfriend story because he was 'too embarrassed to admit the truth' and wanted public approval",
                "Cindy Anthony's nurse supervisor verified she was at work on the day she claimed to search for chloroform at home",
                "An Orange County Sheriff's forensic expert confirmed no 'neck breaking' pop-up ever appeared - someone actively searched the term",
                "Andrew Aldridge Young publicly claimed paternity of Rielle Hunter's baby to protect John Edwards' presidential bid",
                "Judy Feld Carr, a Canadian housewife and music professor, lied to authorities and bribed officials to free about 3,000 Syrian Jews",
                "Glass's stroke-stricken celebrity client recovered and returned to film after her 'little white lie' that the public wanted him back",
                "The 1960s Popeye spinach lie motivated a generation of children to eat their vegetables",
                "Some lies protect strangers: Eastern Europeans who hid Jews from the Nazis in the 1940s were 'righteous heroes'",
            ],
        ),
        "boss": (
            "Boss Battle: The Boardroom Roast",
            "You are Jim Carrey's character under the birthday wish: for 24 hours you cannot tell a lie, and your boss just asked, 'So, what do you really think of me?' - in front of the board. Decide what to say, defuse the fallout, and survive the day without getting fired (Dave's fate) while still honoring the truth constraint - then re-run the scene choosing the tactful-lie path to see the alternative timeline.",
            "A glass boardroom at dusk; eight suited silhouettes turn toward you as the boss smiles. A countdown clock reads 24:00. Every NPC has a LIE-DETECTOR meter over their head; every truthful answer you give swings a career-luck meter between FIRED and RESPECTED.",
            [
                "Carrey's character blurted 'pedantic, pontificating, pretentious bastard, a belligerent old fart, a worthless steaming pile of cow dung' - and his boss laughed, loving 'a good roast'",
                "In real life, most employers would not take kindly to your honest assessment",
                "Dave's fatal mistake was letting anger show: his supervisor focused on his raised voice, not his valid criticisms",
                "Dave vowed afterward to keep his mouth shut and his honest opinions to himself",
                "Lying can be key to self-preservation: in some communities 'talking' is viewed as snitching, which can be a death knell",
                "Carrey's character even told the truth about who passed gas on a crowded elevator",
                "The son's magical wish proves one full day of truth is absurd, insulting, and socially catastrophic",
                "The film is hilarious; in real life the same honesty would constantly hurt everyone's feelings and damage your reputation",
                "There is such a thing as being too honest - even honest suggestions can get you fired",
                "Total honesty can also destroy your best interests: Carrey's honesty nearly cost him everything in the film",
            ],
        ),
    },
    {
        "num": 5,
        "title": "Cyber Liars",
        "pages": "59-75",
        "domain": D,
        "scrub": (
            "Cue Scrubber: 15 Online Red Flags Scanner",
            "Scan 15 real chat messages and profile snippets and flag every red flag in Glass's list: too-good-to-be-true offers, premature love declarations, sob stories, inconsistencies, sarcasm and macabre talk, excessive detail, curt replies, self-deprecating jokes, money talk, egocentrism, poor grammar, odd handles, instant sex talk, guilt trips, and lying photos. Rate each message on a 1-5 scam risk scale.",
            "A glowing chat window fills the screen; message bubbles pulse red as you hover, each tagged with its flag number. A DELETE / BLOCK button hovers beside a RISK dial that climbs with each confirmed flag.",
            [
                "About 80 percent of people lie about at least one physical attribute online - age, height, or weight",
                "Women lie more about age and weight; men lie more about height, job, status, and finances",
                "About 30 percent of people are not honest with the photographs they post",
                "Flag 1: offers that sound too good to be true - money while you sleep, no credentials needed",
                "Flag 2: professing love too quickly - 'be the mother of his children' means he wants your wallet",
                "Flag 3: sob stories of perpetual victims - a son's life-saving operation, an orphaned profile, 'everyone wrongs him'",
                "Flag 4: multiple inconsistencies - ask the same question rephrased and hear a different answer",
                "Flag 5: sarcasm, nastiness, and macabre references - even a 'threat followed by LOL' should be taken seriously",
                "Flag 8: self-deprecating comments said in jest - 'bad girl' and other negatives followed by LOL are actual truths",
                "Flag 11: a stream of wrong verb tenses can be a telltale sign of a sociopath",
                "Flag 12: handles like 'model,' 'gorgeous,' or 'hottie' mean looks focus; 'athletic' or 'big boned' means overweight",
                "Flag 15: photos that lie - check the background, the baby carrier, the other women, the professional shots",
            ],
        ),
        "dialogue": (
            "Dialogue: The Too-Quick Romeo",
            "A man you matched with two days ago is already planning your Bahamas getaway, your wedding, and your children's names - and now asks you to wire money for his plane ticket. Play the conversation: deflect the romance talk, ask the verification questions, and craft the reply that ends contact cleanly (delete and block) or, if you choose, tests whether he can produce any proof of identity.",
            "A split-screen dating app: his bubble typewriter-ticks out heart emojis and future plans while a fake plane ticket graphic floats beside him. Your reply bar glows red with DELETE and BLOCK options at the corner.",
            [
                "He wants something from you, but it sure isn't love - love declared too fast is a scam trademark",
                "Offering to raise money before meeting is code for 'pay for my plane ticket'",
                "If you cough up the money, it will be the last time you see it - 'Romeo' takes the money and runs",
                "Bahamas fantasies and future plans with a stranger mean he is idealizing a relationship with anyone - any warm body",
                "These 'carrots' are a ploy to see if you will bite and jump into a manufactured relationship",
                "For you it is romance and a future; for her it is merely a game and all about now",
                "People like this usually disappear quickly - or stick around to suck more money and perks out of you",
                "Because you lack visual and auditory cues online, you must rely on the exact words and phrases you read",
            ],
        ),
        "audit": (
            "Audit: Profile Autopsy",
            "Pull apart five fake and real dating profiles side by side. Audit each line for the flags: age/height/weight claims, photo authenticity (backgrounds, professional shots, time-period clothing), handle choice, self-description words, level of detail, financial references, and grammar patterns. Produce a risk verdict and an evidence list for each profile, as Glass did when she spotted the stolen yacht photos.",
            "Five profile cards laid out on a forensic light table. A magnifier sweeps each photo; a dress-style date-stamp appears on clothing, and an authenticity meter rates the pictures while the text auto-tags flag numbers in red.",
            [
                "Lying about age online stops initial rejections: Marie's honest 58 earned zero responses, her 45 earned an overwhelming response",
                "Marie told her future husband her real age on the first date - and he admitted he would never have selected her at 58",
                "Fake profiles often contain overly detailed, extremely personal information people don't reveal initially",
                "Stream-of-consciousness writing can unintentionally reveal secrets and lies",
                "People who are stingy with information about who they are usually have something to hide",
                "Too many questions about your personal or work life may mean he is checking whether you know someone useful to him",
                "Overly focused on finances - 'times are tough,' 'too expensive' - signals he is looking for someone to pay",
                "Photos that look too professional, or too good-looking with no candid shots, may not be of him at all",
                "How someone is dressed - styles and trends from a certain period - reveals the age of the posted photo",
                "A photo taken in a sparsely furnished home contradicts a claimed fortune; a baby carrier contradicts 'no kids'",
            ],
        ),
        "matrix": (
            "Matrix: Flag x Context x Action Grid",
            "Cross-tabulate 12 red flags (instant love, sob story, inconsistency, macabre joke, money talk, egocentrism, grammar collapse, odd handle, instant sex, guilt trip, lying photo, too-good-to-be-true offer) against 4 relationship contexts (stranger, 1 week, 1 month, declared love) and choose the action for each cell: delete, block, verify, or proceed with caution. Learn which flags are fatal in any context and which are context-dependent.",
            "A 12x4 matrix grid glows; each cell resolves into a colored action chip as you click. Fatal cells burn red instantly, while context-dependent cells flicker between yellow and green depending on the timeline row.",
            [
                "Sociopaths reveal themselves through inconsistent, scattered thought processes",
                "Confront an inconsistency and you get: hemming and hawing, an over-detailed effusive answer, or defensiveness - all bad signs",
                "'He doesn't have kids' followed weeks later by 'taking my son to soccer' is a very bad sign",
                "Belligerence is a screening process: sadists test for masochists and doormats who will accept abuse",
                "A Valentine's poem full of death, necrophilia, and murder was a warning one woman ignored - she fled a date through the back door",
                "Cutting you down ('pretty face, prettier if you lost a few pounds') is how a scammer finds your weak spot to manipulate",
                "Sincere people don't mention sex right off the bat - instant sex talk is bait to test if you are like-minded",
                "Never send provocative or nude photos: they can be used to extort money or ruin your reputation",
                "An innocent teenager was cyber-bullied into suicide after a fake online 'suitor' shared her topless photo with her school",
                "Guilt trips - 'why didn't you respond?' - are attempts to gain emotional control over you",
                "Egocentrism: every sentence starting with 'I,' dozens of selfies, and no questions about you means your only value is as an audience",
                "If his handle differs from his real name, he may be living a double life - and defensiveness about it is a delete-worthy flag",
            ],
        ),
        "boss": (
            "Boss Battle: The Catfish Hunt",
            "Your famous client, a record producer, is head-over-heels for a voice on the phone - a blond Tulane socialite model he's never seen, who keeps the lights off in hotel rooms. Investigate the claim like Glass did: verify the photos, check the stories against public records, confront her, and deliver the verdict. Then face the advanced round: a new friend's 'Italian model' boyfriend sends yacht and polo photos - spot the stolen images (Gabriel Aubrey) and break the news gently.",
            "A dim hotel room: you watch a doorway, a silhouette enters and refuses to turn on the lights. A dossier interface holds his evidence - photos, voice notes, Vanity Fair clippings - each item marked REAL or FAKE as you verify it. The room brightens as you complete each check.",
            [
                "Miranda Grosvenor told Richard Perry she was a blond Tulane student, wealthy socialite, and international model - she was really Baton Rouge social worker Whitney Walton",
                "Miranda ran the same seduction on Warren Beatty, Bono, Bob Dylan, Ted Kennedy, Robert De Niro, Rush Limbaugh, Richard Gere, and Billy Joel",
                "Perry proposed marriage without ever meeting her - dining nightly in front of the speakerphone; she demanded the hotel lights stay out",
                "When his eyes adjusted he saw an overweight, physically unattractive woman with a large mole - not the 23-year-old bombshell",
                "The term 'catfish' comes from Nev Schulman's 2010 documentary: Angela faked an 8-year-old artist daughter and a beautiful 'Megan' using stolen photos and YouTube MP3s",
                "Vince's explanation: catfish are put in with live cod shipped from Asia to keep them active - catfishers keep people running in circles",
                "Nev Schulman told 20/20 that when someone says she is a model, most likely it isn't true",
                "Glass spotted the fake 'Giovanni' instantly: his yacht and polo pony photos had no one on them - generic grabs off the Internet",
                "'Giovanni's' photos were actually of Gabriel Aubrey, the Canadian model who is the father of Halle Berry's child - 'My dear, you have been played!'",
                "Manti Te'o's 'Lennay Kekua' was a hoax by Ronaiah Tuiasosopo and two accomplices; Te'o heard 'her' breathing on the phone all night while she 'recovered'",
                "After the hoax broke, Te'o lied to his own father and friends, claiming a physical relationship - he became the liar to avoid embarrassment",
                "The rule: meet in person right away or get on Skype and 'see the whites of his eyes' - excuses and cancellations are a huge warning sign",
            ],
        ),
    },
    {
        "num": 6,
        "title": "Instincts and Context",
        "pages": "77-80",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Instinct vs. Second-Guessing",
            "Run 12 scenarios of first impressions and decide whether the visceral reaction is a true alarm (rapid heartbeat, flushed face, stomach pains) or a misread of the chapter's decoys: allergies, anxiety, nerves. For each, identify the physical signal, name the emotion, and choose to trust it, investigate further, or dismiss it - while tracking how much each wrong choice costs.",
            "A monochrome room where a red heat map blooms over a body silhouette - chest, face, stomach - as each scenario's alarm fires. A HUD asks: TRUST, INVESTIGATE, or DISMISS? while a wallet meter ticks down on every dismissed warning.",
            [
                "Larissa's senses picked up on Steve: her limbic system translated data into emotions and gut feelings",
                "The body's alarms: a sudden, rapid heartbeat, a flushed face, and stomach pains",
                "Never ignore 'a twinge in your stomach, a sudden sinking feeling, or any other bodily signal'",
                "Direct your attention to immediate physical changes and try to name the exact emotion you are feeling",
                "Don't second-guess yourself into thinking you are being too judgmental",
                "Don't project positive traits that don't exist onto other people - that is wishful thinking",
                "Seeing people as you want them to be, not as they really are, is how scams get paid for",
                "Your instincts always have your best interests at heart, and they are almost always right",
                "Larissa dismissed her instincts, chastised herself for being superficial, and lost $2,000",
                "Steve's tells: clammy handshake, slow and deliberate movements, boring monotonous drone, and lack of eye contact",
            ],
        ),
        "dialogue": (
            "Dialogue: The Radio Show Producer",
            "A 'producer' promises you $100,000 a year and a multi-market radio show - for a $2,000 demo-tape fee. He has a clammy handshake, a monotone drone, and eyes that never meet yours. Decide what to ask, whether to trust the fluttering in your stomach, and how to exit the conversation with your money and dignity intact - then role-play the alternative: the woman who says yes.",
            "A diner booth at night; across the table a heavyset figure gestures grandly while a shimmering $100,000 sign floats over his shoulder. Your body avatar pulses red at the chest and stomach as a MONOTONE meter and NO-EYE-CONTACT meter tick in the corner.",
            [
                "Steve guaranteed $100,000 in her first year under his management - for just $2,000 up front",
                "A part of Larissa was excited; the other part said 'no way' - she dismissed the no and paid the price",
                "Had she known the tells - clammy handshake, slow deliberate movements, monotonous drone, lack of eye contact - she'd have been leery",
                "When she was conned, Steve gave constant excuses about promised meetings he never intended to arrange",
                "He became unreachable: she could never get him on the phone, and finally he changed his number",
                "Larissa later met Kari, another victim, who knew four other women he had scammed",
                "Larissa was lucky to lose only $2,000 - the others lost a lot more",
                "Trust your instincts: they are almost always right, and they always have your best interests at heart",
            ],
        ),
        "audit": (
            "Audit: Baseline Log",
            "For one week, log a target person's baseline: their posture, fidgets, voice pitch, speech rate, and eye contact when telling you verifiable truths. Then replay the chapter's Jack scenario - nose pulls and arm scratches while discussing the new dog - and log deviations when the topic shifts to where they were last night. Score each deviation against the documented baseline and declare whether context explains it or deception is likely.",
            "A two-column timeline: BASELINE events in blue on the left, SUSPICIOUS EVENTS in red on the right. Each red entry auto-compares against the blue for deviation magnitude; a verdict banner reads CONTEXT vs. DECEPTION.",
            [
                "The baseline is how someone acts when he or she is telling the truth - establish it before judging anything",
                "Everything a person says and does must be evaluated against that baseline of normalcy",
                "Jack tugs his nose and scratches his skin while talking about his new dog - but nose pulling and scratching can be harmless",
                "Context alternative: Jack may simply have allergies",
                "Context alternative: the dog talk itself may be eliciting anxiety - the puppy nips him and he fears it will bite the kids",
                "But if you've never seen Jack pull his nose before, and he does it when asked where he was last night - that is different",
                "An elaborate story with 'many tangents and too much information' is a classic embellishment",
                "Lance Armstrong never pursed his lips, pointed his finger, or grew defensive about his twins and family",
                "When bluntly asked if he ever 'doped,' Armstrong's pursed lips, finger-pointing, and defensive tone 'spoke volumes'",
                "Stop, look, and listen before assessing lies - the same caution as crossing a street against oncoming cars",
                "Watch faces, body movements, tone of voice, speech patterns, and the content of what is actually said",
            ],
        ),
        "matrix": (
            "Matrix: Cue x Baseline x Context Grid",
            "Build a 3-axis matrix for 10 cues (nose tug, arm scratch, pursed lips, finger pointing, monotone voice, defensive tone, rapid heartbeat, flushed face, stomach pain, excessive detail) across baseline state (absent/present in truth-telling) and context (allergies, anxiety, deception, excitement). Mark which cell combinations are reliable deception signals and which are noise, using Jack and Armstrong as the anchor cases.",
            "A rotating 3D cube of colored cells; each face is an axis (CUE, BASELINE, CONTEXT). You spin the cube and click cells; green cells mean reliable tell, gray cells mean noise, and the two anchor cases Jack and Armstrong glow as pinned evidence cards.",
            [
                "A cue present in the baseline is context; a cue that deviates from the baseline is evidence",
                "Nose pulling and scratching are listed deception signs, but allergies produce the same movements in an innocent man",
                "Anxiety - even about a puppy biting the kids - can produce the same fidgets as lying",
                "When the nose pull appears only on the loaded question 'where were you last night?', context flips toward deception",
                "Tangents and too much information are consistent with a fabricated elaborate story",
                "Armstrong's lips, finger, and tone stayed clean on family questions - the baseline - and degraded only on the doping question",
                "Context is key: the same gesture means different things at different moments in the same person",
                "Your gut feeling (the limbic translation) plus baseline deviation is the strongest warning combo",
            ],
        ),
        "boss": (
            "Boss Battle: The $2,000 Gut",
            "A smooth-talking promoter is pitching you a dream deal, but your body is screaming - racing heart, flushed face, stomach pains - while his handshake is clammy and his voice drones. Decide under time pressure: walk away, stall for verification, or pay. Every dismissed instinct costs you money on a loss meter; every false alarm costs you a real opportunity. Survive five rounds of escalating pitches, ending with the one pitch that is genuinely legitimate - can you still tell the difference?",
            "A stage with five curtained booths, each hiding a promoter. Your avatar's vitals panel - HEART, FLUSH, STOMACH - spikes as each curtain rises. A 10-second decision timer spins while a wallet counter and an opportunity counter trade off in the corner.",
            [
                "Larissa's negative feelings were reflected in sudden rapid heartbeat, flushed face, and stomach pains",
                "The limbic system, deep inside the brain, translates sensed data into emotions and gut feelings",
                "'If something sounds like a lie, or someone looks as though they are lying, chances are there is deception going on'",
                "Stop, look, and listen before you judge - just as you do before crossing a street",
                "Define the exact emotion you are feeling instead of denying the alarm bells",
                "The perceived harshness of a punishment is proportional to the tenacity of the lie - con artists never stop at one pitch",
                "Con artists rely on your wishful thinking: they project a future you want, not the one that exists",
                "Steve's victims each dismissed the same gut warning - Larissa, Kari, and four other women all lost money",
                "Trusting instincts is a skill: name the feeling, check the baseline, then act before the demo-tape fee is paid",
            ],
        ),
    },
]
