# -*- coding: utf-8 -*-
"""Phase 2 chapter data for Influence: The Psychology of Persuasion (Robert Cialdini, New & Expanded edition), Introduction and chapters 1-4.
Each section: num, title, pages, domain, and 5 slots (scrub/dialogue/audit/matrix/boss),
each slot a 4-tuple (topic, player_mission, visual_frame_description, key_concepts[10-12]).
"""

D = "Influence & Persuasion | Cognitive Heuristics"

CHAPTERS = [
    {
        "num": 0,
        "title": "Introduction",
        "pages": "10-14",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Patsy Patter",
            "Walk through five everyday encounters - a street fundraiser, a free-sample stand, a telemarketer, a donation letter, and a charity caller - and spot the moment each one is about to trigger your automatic yes. Name the principle the pitch is about to commission and call out how the author's 'patsy' pattern would respond. Score yourself on how fast you catch the lever before it clicks.",
            "A neon-lit street of booths where each peddler's pitch plays as a scrolling script while a red LEVER DETECTED stamp slams onto the screen the instant a compliance tactic appears.",
            [
                "Cialdini admits he has been a lifelong patsy, an easy mark for the pitches of peddlers, fundraisers, and operators of one sort or another",
                "With personally disquieting frequency he found himself in possession of unwanted magazine subscriptions or tickets to the sanitation workers' ball",
                "His research asks what factors cause one person to say yes to another and which techniques most effectively use those factors to bring about compliance",
                "He began as an experimental social psychologist, running laboratory experiments on college students to find which psychological principles influenced the tendency to comply",
                "He realized the experimental work wasn't enough, so he turned to the compliance professionals who had been using the principles on him all his life",
                "The law of survival of the fittest assures that those who know how to get people to say yes stay and flourish, while those who don't fall away",
                "For nearly three years he combined his experiments with a program of systematic immersion in the world of salespeople, fundraisers, marketers, and recruiters",
                "His program included interviews with practitioners and their natural enemies - police fraud-squad officers, investigative reporters, and consumer-protection agencies",
                "Most frequently it took the form of participant observation, a research approach in which the investigator becomes a spy of sorts with disguised identity and intent",
                "He answered ads for sales trainees and let magazine, vacuum-cleaner, portrait-photograph, and health-supplement sales organizations teach him their methods",
                "Although there are thousands of different compliance tactics, the majority fall within seven basic categories governed by seven fundamental psychological principles",
                "The seven principles are reciprocation, liking, social proof, authority, scarcity, commitment and consistency, and unity",
            ],
        ),
        "dialogue": (
            "Dialogue: The Compliance Professional Interview",
            "Take the interviewer's seat and grill a compliance professional - a recruiter, a fundraiser, or a sales trainer - about why their tactics work. Push them to explain which of the seven levers they reach for, then switch roles and answer the questions as the practitioner who profits from the rule.",
            "A dim boardroom where the interviewer's question bubbles glow green while the practitioner's answers reel out as physical levers, each one pulling a marionette string into a customer's shopping bag.",
            [
                "The compliance practitioners represented the richest vein of information about compliance available to Cialdini",
                "Each of the seven principles is discussed both in terms of its function in society and in terms of how its enormous force can be commissioned by a compliance professional",
                "The principles can be deftly incorporated into requests for purchases, donations, concessions, votes, or assent",
                "The book is organized around the seven principles, one principle to a chapter",
                "Each principle is examined as to its ability to produce a distinct kind of automatic, mindless compliance - a willingness to say yes without thinking first",
                "The ever-accelerating pace and informational crush of modern life will make this form of unthinking compliance more and more prevalent in the future",
                "It will be increasingly important for society to understand the how and why of automatic influence",
                "Dr. Gregory Neidert's Core Motives Model of Social Influence holds that the communicator's prime goal at the time affects which influence principles the communicator should prioritize",
                "When cultivating a positive relationship is the prime goal, the principles of reciprocation, liking, and unity are particularly appropriate",
                "When reducing uncertainty is the priority, social proof and authority should never be ignored, because evidence that a choice is well regarded by peers or experts makes it appear prudent",
                "When motivating action is the main objective, the appeal should include the principles of consistency and scarcity",
                "Cialdini is not suggesting these associated principles are the sole options for achieving their goals, only that failing to employ an aligned principle would be a considerable mistake",
            ],
        ),
        "audit": (
            "Audit: The Immersion Field Log",
            "Spend a day logging every compliance pitch you encounter, from junk mail to checkout displays to charity calls. For each entry record the setting, the request, and which of the seven levers the pitch is trying to pull, then grade whether you responded with automatic or controlled responding.",
            "A bulletin board plastered with pinned pitch samples - ads, letters, coupons - each tagged with a colored string linking it to one of seven labeled levers mounted on the wall.",
            [
                "Cialdini's program of observation combined interviews, intensive examination of written materials such as sales manuals, and participant observation",
                "Sales manuals are one way compliance techniques are passed down from one generation of practitioners to another",
                "The thousands of compliance tactics fall into seven basic categories, each governed by a fundamental psychological principle that directs human behavior",
                "The seven principles are reciprocation, liking, social proof, authority, scarcity, commitment and consistency, and unity",
                "The book examines each principle in terms of how its force can be commissioned for purchases, donations, concessions, votes, or assent",
                "Automatic, mindless compliance is a willingness to say yes without thinking first",
                "Modern life's pace and informational crush will make unthinking compliance increasingly prevalent",
                "Society will need to understand the how and why of automatic influence to deal with its growth",
                "The chapter sequencing follows which principles are more useful depending on the persuasive goal the communicator wishes to achieve",
                "Messages are more likely to be successful if recipients can first be made to feel positively toward the messenger",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: The Seven Levers Sorter",
            "Sort a stack of twenty pitches - a free sample, a celebrity endorsement, a limited-supply warning, a poll result, a doctor's recommendation, a 'you always said' reminder, and a family discount - into the correct one of the seven levers. Then reassign each to the persuader motive it best serves: relationship, certainty, or action.",
            "A conveyor belt feeding pitch cards into seven color-coded chutes labeled with the principles, each chute ending in a goal-of-persuasion stamp.",
            [
                "The seven principles are reciprocation, liking, social proof, authority, scarcity, commitment and consistency, and unity",
                "Reciprocation, liking, and unity are particularly appropriate when the goal is cultivating a positive relationship",
                "Social proof and authority are the principles for reducing uncertainty, because evidence that peers or experts endorse a choice makes it appear prudent",
                "Consistency and scarcity suit the goal of motivating action",
                "A well-liked friend may show sufficient proof that almost everyone believes daily exercise is good, but that proof may not be enough to get a person to do it",
                "Reminding someone of what they have said publicly in the past about the importance of their health uses the consistency principle",
                "Reminding someone of the unique enjoyments they would miss if they lost their health uses the scarcity principle",
                "The message combining consistency and scarcity has the best chance of getting a person up in the morning and off to the gym",
                "A positive relationship with a communicator does not necessarily mean message recipients will be persuaded",
                "Before changing their minds, people want to be assured that any decision they are being urged to make is wise",
                "Failing to employ an aligned principle when it is available for an aligned goal would be a considerable mistake",
                "The arrangement of the chapters takes into account which principles are suited to the three motives of persuaders",
            ],
        ),
        "boss": (
            "Boss Battle: The Core Motives Gauntlet",
            "Face a final boss who wants you to change a stubborn friend's behavior: first get them to like you, then make the choice look safe, then push them to act. Pick the right principles for each stage of the gauntlet and survive the counters - a friend who likes you but won't move, and proof that doesn't produce action.",
            "A three-tier tower, each tier a locked gate labeled Relationship, Certainty, and Action, with the seven principles floating as keys that only open their matching gate.",
            [
                "Dr. Gregory Neidert's Core Motives Model of Social Influence describes the persuader's prime goals of cultivating relationships, reducing uncertainty, and motivating action",
                "Reciprocation, liking, and unity serve the motive of relationship cultivation",
                "Social proof and authority serve the motive of uncertainty reduction",
                "Consistency and scarcity serve the motive of motivating action",
                "Reminding a friend of what they said publicly in the past about the importance of their health is a consistency-based appeal",
                "Reminding a friend of the unique enjoyments they would miss if they lost their health is a scarcity-based appeal",
                "Proof that almost everyone believes daily exercise is a good thing may not be enough to get a person to do it",
                "Moving from a mere decision to act to steps based on that decision requires the right message",
                "The message combining consistency and scarcity is the one with the best chance to move a person to act",
                "It is important to recognize that the associated principles are not the sole options for achieving their respective goals",
                "Failing to employ an aligned principle when it is available would be a considerable mistake",
                "The sequencing of the chapters reflects which principles are suited to the three motives of persuaders",
            ],
        ),
    },
    {
        "num": 1,
        "title": "Chapter 1: Levers of Influence: (Power) Tools of the Trades",
        "pages": "14-33",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Trigger Feature Hunt",
            "Scan twelve scenes - a sale sign, a uniform, a crowd, a free sample, a 'because' phrase - and identify the single trigger feature each pitch is built on. Name the fixed-action pattern it activates and decide whether the response this time would be a shortcut win or a costly mistake.",
            "A detective's evidence board where each scene photo has one element circled in pulsing red - the cheep-cheep, the redbreast feather, the word because - while a program reel labeled CLICK RUN rolls beneath.",
            [
                "Fixed-action patterns are rigid, mechanical behavior sequences that occur in virtually the same fashion and in the same order every time",
                "The behavior programs are activated by a trigger feature, often one tiny aspect of the totality that is the approaching intruder",
                "A mother turkey accepted and gathered a stuffed polecat under her when it played the cheep-cheep sound of chicks, and attacked it viciously when the sound was turned off",
                "A male robin will vigorously attack a clump of robin redbreast feathers while ignoring a perfect stuffed replica of a robin without redbreast feathers",
                "In Langer's Xerox study, 'May I use the Xerox machine because I'm in a rush?' produced nearly total compliance, with 94 percent letting her skip ahead in line",
                "The bare request with no reason produced only 60 percent compliance",
                "A third request that added nothing new - 'because I have to make some copies' - still won 93 percent compliance, showing the word because alone was the trigger",
                "The turquoise jewelry sold only after the price was accidentally doubled when the employee read the '1/2' in the owner's note as a '2'",
                "The customers, mostly vacationers with little knowledge of turquoise, used the expensive = good stereotype, so price alone became the trigger feature for quality",
                "In the energy-drink study, volunteers charged the retail price of $1.89 solved more mental puzzles than those charged only $0.89",
                "People told a pain reliever cost $2.50 per unit rated it much more effective than those told it cost $0.10, though all received the same pain reliever",
                "Our preset programs usually work to our advantage, but trigger features can dupe us into running the right programs at the wrong times",
            ],
        ),
        "dialogue": (
            "Dialogue: The Xerox Line Confrontation",
            "Play both sides of Langer's copying-machine experiment: the confederate who needs to cut the line and the person waiting who must decide whether the 'because' deserves compliance. Run the three request versions - no reason, real reason, and empty 'because' - and watch the compliance percentage swing.",
            "A library copy room with a queue of students; each request text floats above the speaker's head and a percentage meter ticks up or down as the sentence completes.",
            [
                "People simply like to have reasons for what they do",
                "'Excuse me, I have five pages. May I use the Xerox machine, because I'm in a rush?' produced 94 percent compliance",
                "The request without any reason produced only 60 percent compliance",
                "The request ending in 'because I have to make some copies' produced 93 percent compliance despite adding no real reason",
                "It was not the whole series of words but the first one - because - that made the difference",
                "The word because triggered an automatic compliance response even when no real reason or new information was provided",
                "Langer and many other researchers are convinced that most of the time human behavior does work in a mechanical, click-activated way",
                "The strange behavior of the jewelry-store customers makes sense only when viewed in click, run terms",
                "Research shows that people who are unsure of an item's quality often use the expensive = good stereotype",
                "Automatic, stereotyped behavior is prevalent because in many cases it is the most efficient form of behaving, and in other cases it is simply necessary",
                "Without simplifying features we would stand frozen - cataloging, appraising, and calibrating - as the time for action sped by",
                "As the stimuli saturating our lives grow more intricate, we will depend increasingly on our shortcuts to handle them",
            ],
        ),
        "audit": (
            "Audit: The Click-Run Field Sweep",
            "Log a day of your own automatic responses: the price tags you trusted, the expert you obeyed without scrutiny, the sale that moved you. For each entry record the trigger feature, the shortcut rule it engaged, and whether a profiteer was present to exploit it.",
            "A park bench surrounded by floating snapshot moments of everyday decisions, each tagged with its trigger feature and a small suited figure grinning whenever a profiteer stands nearby.",
            [
                "Judgmental heuristics are mental shortcuts that allow simplified thinking which works well most of the time but leaves us open to occasional, costly mistakes",
                "One shortcut especially relevant to the book: 'If an expert said so, it must be true'",
                "Automatic (click, run) responding reacts mechanically to one piece of information in a situation",
                "Controlled responding is the tendency to react on the basis of a thorough analysis of all of the information",
                "People deal with information in a controlled fashion when they have both the desire and the ability to analyze it carefully",
                "Students with no personal stake in comprehensive exams were primarily persuaded by the speaker's expertise, paying little attention to argument strength",
                "Students for whom the issue mattered personally ignored the speaker's expertise and were persuaded primarily by the quality of the arguments",
                "Complicated issues, tight time, intrusive distractions, strong emotional arousal, or deep mental fatigue can force even personally relevant decisions onto the shortcut",
                "Accident investigators at the FAA noted that frequently an obvious error made by a flight captain was not corrected by the other crew members and resulted in a crash",
                "In the Potomac crash, the copilot said 'Larry, we're going down' and the captain replied 'I know it' after the crew deferred to his suspect takeoff reading",
                "Most of us know very little about our automatic behavior patterns, which makes us terribly vulnerable to anyone who does know how they work",
                "Automatic responding preserves crucial time, energy, and mental capacity, but increases the chances of error, especially when it is mindless",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Click-Run vs. Controlled Responding",
            "Classify a dozen decision scenarios - an urgent medical choice, a routine purchase, a life-or-death cockpit moment, a trivial favor - as cases for automatic or controlled responding. Justify each call with desire-and-ability reasoning, then re-sort them to spot where a profiteer has gamed the shortcut.",
            "A courtroom split-screen where each scenario card lands on one of two platforms - a whirring AUTOMATIC gearbox or a candle-lit CONTROLLED deliberation desk.",
            [
                "Controlled responding is the tendency to react on the basis of a thorough analysis of all of the information",
                "Automatic responding reacts mechanically to one piece of information, such as the speaker's status as expert",
                "In the comprehensive-exam study, students with a personal stake in the issue ignored the speaker's expertise and weighed the arguments' quality",
                "Students without a personal stake used the 'If an expert said so, it must be true' rule",
                "We resist reacting to a single trigger feature when an issue is important to us - a kind of safety net",
                "But the form and pace of modern life often leave us in no cognitive condition to operate mindfully, important topic or not",
                "The airline phenomenon of Captainitis shows that even clear personal importance does not guarantee correction of an expert's error",
                "Mimics copy the trigger features of other animals in an attempt to trick them into playing the right behavior programs at the wrong times",
                "Photuris firefly females mimic the flashing mating signals of Photinus males, whose triggered courtship program flies them into death's, not love's, embrace",
                "Bacteria and viruses adopt critical features of useful hormones or nutrients to gain entry into healthy host cells, causing diseases such as rabies and the common cold",
                "Human profiteers mimic trigger features for our own brand of automatic responding",
                "Our automatic programs usually develop from psychological principles or stereotypes we have learned to accept",
            ],
        ),
        "boss": (
            "Boss Battle: The Jujitsu Sales Floor",
            "Survive a showroom run by a jujitsu master who sells the suit before the sweater, parks you in a 'setup' house, and threads options into the car deal one small price at a time. Spot each contrast-principle trap before signing, then decide whether to buy.",
            "A showroom and car lot layered in forced perspective where every purchase object looms smaller next to its expensive predecessor, and the dealer's grin fades whenever a customer sees through the contrast.",
            [
                "The contrast principle says that if the second item is fairly different from the first, we tend to see it as more different than it actually is",
                "A cheeseburger is judged much higher in calories - 38 percent higher in one study - if we first estimate the calories in a salad",
                "A hand placed in cold water feels hot when both hands are put in room-temperature water, while the hot-water hand feels cold",
                "Clothing stores instruct their sales personnel to sell the costly item first, so sweater prices do not seem as high in comparison",
                "Presenting an inexpensive product first and following it with an expensive one makes the expensive item seem even more costly",
                "Real-estate salesman 'Phil' showed customers a couple of undesirable 'setup' properties at inflated prices so the genuine properties benefited from the comparison",
                "Car dealers wait until the price of a car has been negotiated before suggesting options, so each small extra seems almost trivial in comparison",
                "At O'Hare, a desk agent's joking offer of a $10,000 voucher made his actual $200 offer seem like a pittance, and he had to raise the offer twice before getting volunteers",
                "The great advantage of the contrast principle is not only that it works but also that it is virtually undetectable",
                "A jeweler introduced a necklace at its regular $500 price, then gave it to his friend for $250, leaving the friend thrilled rather than offended",
                "The expensive = good stereotype is learned from the rule 'You get what you pay for,' which has been borne out over and over in people's lives",
                "By reacting solely to price, the tourists were betting the shortcut odds, which represents the most rational approach in the long run",
            ],
        ),
    },
    {
        "num": 2,
        "title": "Chapter 2: Reciprocation: The Old Give and Take",
        "pages": "33-76",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Indebtedness Detector",
            "Scan ten encounters - a gift card, a free sample, a compliment, a mint with the bill, a concession - and flag the moment an obligation is being manufactured. Name the favor, the return that is being seeded, and how big the intended payback is.",
            "A market square where every free offering attaches a glowing chain from giver to receiver, and the chains grow heavier the longer they go unreturned.",
            [
                "The rule of reciprocation says that we should try to repay, in form, what another person has provided us",
                "Holiday cards came pouring back to the professor from strangers who had neither met nor heard of him - they mechanically sent one in return",
                "In the United Kingdom, when a request for a full day's salary was preceded by a small packet of sweets, contributions more than doubled",
                "The Magna Carta of 1215 used the rule to define how countries should treat enemy-nation merchants at the outbreak of war",
                "The Japanese word for thank you, sumimasen, literally means 'this will not end,' connoting the future reach of the obligation",
                "Sociologist Alvin Gouldner and other sociologists report that all human societies subscribe to the rule of reciprocation",
                "Archaeologist Richard Leakey claims we are human because our ancestors learned to share food and skills in an honored network of obligation",
                "In 1985, Ethiopia sent $5,000 of relief aid to Mexico City because Mexico had sent aid to Ethiopia when it was invaded by Italy in 1935",
                "Lord Arthur George Weidenfeld founded Operation Safe Haven to rescue endangered Christians because, saved by a Kindertransport train, he said, 'I had a debt to repay'",
                "Because there is a general distaste for those who take and make no effort to give in return, we go to great lengths to avoid being considered a freeloader",
                "A phrase such as 'much obliged' has become a synonym for thank you in English and in other languages, such as the Portuguese term obrigado",
            ],
        ),
        "dialogue": (
            "Dialogue: The Regan Raffle Interrogation",
            "Play the Coke-giver and the Coke-receiver: run the art-appreciation cover, deliver the unrequested soda, then watch raffle-ticket purchases double - or refuse the favor and see whether the pitch still works. Then switch sides and decide how much obligation a dime buys.",
            "A lab room where one character hands over a fizzy bottle and a counter labeled RAFFLE TICKETS climbs from one to seven as the other character's sense of debt visibly weights their hand.",
            [
                "In the Regan experiment, Joe left the room for a couple of minutes and returned with two bottles of Coca-Cola, saying he had bought one for the subject too",
                "Subjects who received the earlier favor bought twice as many raffle tickets as subjects who had not been given the prior favor",
                "The relationship between liking and compliance was completely wiped out in the condition where subjects had been given a Coke by Joe",
                "Subjects who indicated they disliked Joe bought just as many of his tickets as those who indicated they liked him",
                "The rule of reciprocation was so strong it overwhelmed the influence of liking for the requester, a factor that normally determines compliance",
                "A 10-cent Coke led subjects to buy, on average, two of Joe's 25-cent raffle tickets - a 500 percent return on investment",
                "The study was done in the late 1960s, when the price of a Coke was a dime",
                "A person can trigger a feeling of indebtedness by doing us an uninvited favor - the rule does not require us to have asked for what we received",
                "All the genuinely free choices were Joe's: he chose the form of the initial favor and the form of the return favor",
                "A student whose car was jump-started by a stranger later lent him her new car, which he totaled, because she felt obligated by the earlier favor",
                "Most of us find the state of obligation highly disagreeable, and it demands to be removed",
                "A Japanese proverb makes the point: 'There's nothing more expensive than that which comes for free'",
            ],
        ),
        "audit": (
            "Audit: The Gift-Versus-Gimmick Ledger",
            "Collect the gifts that arrive unsolicited in your mailbox, inbox, and on your doorstep - address labels, greeting cards, trial packs - and log what each organization seeds and what it asks in return. Classify each as an honest favor or a compliance device, and record whether you would accept on the rule's own terms.",
            "A cluttered desk where each mailed gift is unwrapped by a gloved hand onto a balance scale: favor on one pan, sales scheme on the other.",
            [
                "The Disabled American Veterans' simple mail appeal for donations produces a response rate of about 18 percent",
                "When the mailing also includes an unsolicited gift of gummed, individualized address labels, the success rate nearly doubles to 35 percent",
                "French anthropologist Marcel Mauss described an obligation to give, an obligation to receive, and an obligation to repay",
                "The obligation to receive reduces our ability to choose those to whom we wish to be indebted, putting the power in the hands of others",
                "Missionary programs sent greeting cards that were not to be directly paid for but were designed 'to encourage your kindness'",
                "There is strong cultural pressure to reciprocate a gift, even an unwanted one, but no such pressure to purchase an unwanted commercial product",
                "Mailing a $5 'gift' check along with an insurance survey was twice as effective as offering a $50 payment for sending back a completed survey",
                "Survey researchers find that sending a monetary gift with a mailed questionnaire greatly increases completion rates compared to an after-the-fact reward",
                "Food servers who simply give customers a candy or mint along with their bill significantly increase tips, whatever the guests' nationality",
                "Servers who gave diners a piece of candy with the bill increased tips by 3.3 percent, and two pieces raised the tip by 14 percent (Strohmetz et al., 2002)",
                "In McDonald's restaurants in Brazil and Colombia, giving children a balloon as they left raised the total family check by 25 percent, including a 20 percent increase in coffee purchases",
                "Jonestown's Diane Louie refused Jim Jones's offer of special food while she was ill, saying, 'I knew once he gave me those privileges, he'd have me'",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Favor vs. Concession vs. Trick",
            "Sort a dozen moves - a birthday gift, a price retreat, a free inspection, a two-year favor offer, a yogurt sample - into honest favor, reciprocal concession, or manufactured compliance device. For each device, name the redefinition that frees you from the rule.",
            "A courtroom table where each exhibit card is ruled on by a stamp - FAVOR, CONCESSION, or DEVICE - with a hooded figure slipping redefinition notes to the defense.",
            [
                "The reciprocity rule governs two kinds of exchanges: a favor is to be met with a return favor, and a concession is to be met with a return concession",
                "The rejection-then-retreat technique, also known as the door-in-the-face technique, begins with a larger request that will most likely be turned down",
                "Cialdini bought two $1 chocolate bars from the Boy Scout after declining his $5 circus tickets, despite disliking chocolate bars and liking dollars",
                "In the zoo-chaperon experiment, the rejection-then-retreat sequence tripled the percentage of students volunteering, from 17 to 50 percent",
                "Research at Bar-Ilan University in Israel shows the tactic backfires if the first set of demands is so extreme as to be seen as unreasonable",
                "The larger-then-smaller request sequence simultaneously engages the reciprocity rule and the perceptual contrast principle",
                "G. Gordon Liddy's approved $250,000 Watergate plan was a concession from his earlier $1 million and $500,000 proposals",
                "Only LaRue expressed direct opposition to the plan - and he was the only one of the three present who had not attended the prior two meetings",
                "Magruder recalled that Liddy 'had asked for the whole loaf when he was quite content to settle for half or even a quarter'",
                "In the Canadian mental-health-agency study, rejection-then-retreat produced more verbal agreement (76 vs 29 percent) and a higher show-up rate (85 vs 50 percent)",
                "Students asked to give blood via the technique were far more willing to be called upon to donate again (84 vs 43 percent)",
                "Because the tactic uses a requester's concession, the victim feels more responsible for and satisfied with the arrangement, which is why compliance carries over to future requests",
            ],
        ),
        "boss": (
            "Boss Battle: The Fire-Safety Inspector's Gambit",
            "Face the boss-level pitch: a free home inspection, a free extinguisher, and then a hard sell on an overpriced alarm system. Run the mental redefinition that turns every 'gift' into a sales device, refuse the purchase without a tug of obligation, and counterattack by profiting from the profiteer's own lever.",
            "A living room where a uniformed inspector's gift box is peeled open to reveal a ticking sales pitch; the player calmly stamps each gift RE-DEFINED: DEVICE and the box deflates.",
            [
                "Our best defense against the use of reciprocity pressures is not systematic rejection of the initial offers of others",
                "Blanket rejection insults authentically generous individuals and can produce social friction and isolation",
                "We should accept initial favors or concessions in good faith but be ready to redefine them as tricks should they later be proved as such",
                "Once an initial offer is perceived and defined as a compliance device instead of a favor, the giver no longer has the reciprocation rule as an ally",
                "The rule says that favors are to be met with favors; it does not require that tricks be met with favors",
                "Door-to-door home fire-alarm companies give a free extinguisher and inspection, then pressure an immediate sale of overpriced heat-triggered systems",
                "Using the free-information-and-inspection gambit, fire-protection sales organizations have flourished",
                "After redefinition, you might even take the inspector's own lever and use it against him, because the rule asserts that exploitation attempts should be exploited",
                "Cialdini recommends retaining earned influence by saying, 'If our positions were ever reversed, I know you'd do the same for me' instead of dismissing a favor as no big deal",
                "After switching seats with a claustrophobic man on a flight, Cialdini was the one his neighbor offered cashews, gum, and the sports section to first - the one owed mattered most",
                "A consultant's personalized postcards matched to her client's art collecting made her invoices get paid almost immediately, cutting his six-month payment delay in half",
                "In a fast-food restaurant, a yogurt gift matched to visitors' need for food increased purchases to 24 percent, versus 12 percent for an equal-value key ring",
            ],
        ),
    },
    {
        "num": 3,
        "title": "Chapter 3: Liking: The Friendly Thief",
        "pages": "76-123",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Friendly Thief Tells",
            "Scan ten friendly interactions - the mirroring waitress, the name-dropping prospect, the compliment-heavy colleague, the 'we're both runners' negotiator - and spot the liking lever each one works. Name the factor at play: attractiveness, similarity, praise, familiarity, cooperation, or association.",
            "A cocktail party rendered in x-ray, where every flattering phrase leaves a glowing residue on the listener's heart-shaped meter while a counter ticks upward.",
            [
                "The liking rule says we are more influenced by the people we like, and the rule can apply even to individuals we have never met",
                "When people were led to believe George Clooney had made favorable comments about a pro-evolutionary book, they became significantly more accepting of the theory",
                "The Clooney effect occurred regardless of the participants' age, sex, or degree of religiosity",
                "The result replicated when the study was redone using the widely liked actress Emma Watson",
                "Medical malpractice attorney Alice Burkin said, 'People just don't sue the doctors they like'",
                "Compliance professionals seek to benefit from the liking rule even when no friendship exists, by first getting us to like them",
                "Joe Girard's formula for selling Chevrolets was a fair price plus someone you like to buy from",
                "Behavioral scientists have identified factors that reliably cause liking: physical attractiveness, similarity, compliments, familiarity, cooperation, and association",
                "Attractive people are better liked, better paid, more persuasive, more frequently helped, and seen as possessing more desirable personality traits and greater intellectual capacities",
                "We automatically assign to good-looking individuals such favorable traits as talent, kindness, honesty, and trustworthiness, without realizing attractiveness played a role",
                "Adults view aggressive acts as less naughty when performed by attractive elementary school children, and teachers presume nice-looking children are more intelligent",
                "The social benefits of good looks begin to accumulate early in life",
            ],
        ),
        "dialogue": (
            "Dialogue: The Tupperware Living Room",
            "Play the hostess who profits from her friends' purchases and the guest who came for the games and stayed for the guilt. Run the party from prizes to the purchase moment, then switch sides and decide how to refuse a friend's sales pressure without insulting her.",
            "A sunlit living room full of partygoers playing Barnyard Bingo; each purchase is handed across the coffee table from friend to friend while a profit meter rings up the hostess's cut.",
            [
                "At a Tupperware party, the true request to purchase does not come from the demonstrator but from a friend to every person in the room",
                "The party hostess, who called her friends together in her home, makes a profit from each piece sold at the party",
                "Consumer researchers found that the strength of the social bond between hostess and partygoers is twice as likely to determine purchases as preference for the product itself",
                "Tupperware sales now exceed $5.5 million a day, and a Tupperware party starts somewhere in the world every 1.8 seconds",
                "In 2003 Tupperware severed its profitable relationship with the retailer Target because store sales were too strong and damaged home-party arrangements",
                "Less than a quarter of Tupperware sales now take place in North America",
                "The Shaklee Corporation's 'endless chain' method presses customers for the names of friends, who are then approached by a salesperson armed with a friend's name",
                "A Nielsen Company survey found that 92 percent of consumers trust product recommendations from someone they know, 22 percent more than the next-highest source, online reviewers",
                "Customers referred by a friend proved 18 percent more loyal to one bank over three years and 16 percent more profitable",
                "An MCI salesperson told Consumer Reports that the Friends and Family Calling Circle 'works 9 out of 10 times'",
                "A single Tesla owner who referred 188 people made $135,000 in rewards while Tesla made $16 million in sales",
                "Charity organizations recruit volunteers to canvass close to their own homes because it is much harder to turn down a request from a friend or neighbor",
            ],
        ),
        "audit": (
            "Audit: The Likability Factors Field Book",
            "Spend an afternoon people-watching and log every liking factor in play: grooming and looks, mirrored postures, shared-interest claims, compliments, name drops, and friendly familiarity. For each, note who deployed it and what request followed.",
            "A street-side cafe table with an open field book; passersby freeze into tableaus while colored markers tag each liking factor and a small speech bubble forecasts the coming request.",
            [
                "A halo effect occurs when one positive characteristic of a person dominates the way that person is viewed in most other respects",
                "In a study of a Canadian federal election, attractive candidates received more than two-and-a-half times as many votes as unattractive ones",
                "Seventy-three percent of Canadian voters surveyed denied in the strongest possible terms that their votes had been influenced by physical appearance",
                "In one study, good grooming of applicants in a simulated employment interview accounted for more favorable hiring decisions than did job qualifications",
                "Economist Daniel Hamermesh estimated that over the course of one's career, being attractive earns a worker an extra $230,000",
                "We like people who are like us, a fact that applies to human infants as young as nine months",
                "In a massive study of 421 million potential romantic matches from an online dating site, the factor that best predicted favorability toward a partner was similarity",
                "Marchers in an antiwar demonstration were more likely to sign the petition of a similarly dressed requester - and to do so without reading it first",
                "Changing one small feature of a mailed survey - making the survey-taker's name resemble the recipient's - nearly doubled survey completion",
                "Voters prefer political candidates who share minor facial similarities with them",
                "Bargainers are much more likely to come to an agreement after learning of similarities with their bargaining opponent",
                "Food servers trained to mimic customers' words received higher tips, and salespeople instructed to mirror customers' behavior sold more electronic equipment",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: The Liking Factor Sorter",
            "Classify a dozen influence moves - a compliment, a shared hobby claim, a mirrored posture, a free lunch, a celebrity in the ad, a 'we're teammates' pitch - into the liking factor each exploits. Then flag which ones are honest strategies versus manufactured tricks.",
            "A sorting carousel with six labeled bins - looks, similarity, praise, contact, cooperation, association - and each move-card lighting its correct bin as a judge nods or frowns.",
            [
                "In an experiment on a group of men in North Carolina, the evaluator who provided only praise was liked best",
                "Pure praise produced just as much liking for the flatterer when it was untrue as when it was true",
                "In a brain-imaging study, teenagers' reward sectors lit up when their social-media photos received lots of likes - the same sectors activated by eating chocolate or winning money",
                "Customers complimented by a server in a restaurant or a stylist in a hair salon responded with significantly larger tips",
                "Individuals who received flattering feedback from their computer liked the machine more, even though they were told the feedback was preprogrammed",
                "Gregory Razran's 'luncheon technique' found that subjects became fonder of political statements shown while food was being eaten",
                "When putrid odors were piped into the room, approval ratings for the slogans shown declined",
                "The presence of MasterCard logos made college students willing to spend an average of 29 percent more money for mail-order catalog items",
                "Students were markedly more likely to give to the United Way when the room contained MasterCard insignias - 87 percent versus 33 percent",
                "Feinberg found the facilitation effect only among people who had a positive history with credit cards, not those who had paid above-average interest charges",
                "Men who saw a new-car ad with a seductive female model rated the car as faster, more appealing, and better-designed, yet refused to believe she had influenced them",
                "Advertisers bet we will respond to their products in the same ways we respond to the attractive models merely associated with them - and we do",
            ],
        ),
        "boss": (
            "Boss Battle: The Dealin' Dan Gauntlet",
            "Spend forty-five minutes in Dealin' Dan's showroom and defeat the liking gauntlet: coffee and doughnuts, compliments on your choices, laughs, and a staged battle with the sales manager. Catch yourself liking him more than expected, mentally separate Dan from the deal, and decide on the car's merits alone.",
            "A dealership lot where the salesperson's every charm move fires as a projectile that bounces harmlessly off a force field labeled SEPARATE THE DEALER FROM THE DEAL.",
            [
                "The defense against the liking rule concentrates on effects rather than causes: be sensitive to the feeling that we like the practitioner more than we should under the circumstances",
                "We should not attempt the nearly impossible task of detecting and deflecting all the psychological influences on liking",
                "We have to be sensitive to only one thing: that we have come to like the practitioner more quickly or more deeply than we would have expected",
                "The simple recognition of unwarranted liking should be enough to trigger a counter-maneuver",
                "The recommended reaction is to mentally separate the requester from the request and judge the offer's merits alone",
                "Actively disliking Dan would be unfair, since some individuals are naturally likable, and turning against all likable professionals would shut off good business interactions",
                "If we choose Dan's car, we will be driving it, not him, off the dealership lot - his likability is irrelevant to a wise purchase",
                "Once immersed in even a brief social contact with a requester, we may easily forget the distinction between our feelings about the person and the request",
                "The big mistakes are likely to come when we like the person making the request",
                "New-car salespeople take our side and 'do battle' with their bosses, but the salesman Gary simply had a soft drink in silence with the boss before returning with the deal he had planned all along",
                "Good Cop/Bad Cop interrogation works partly because the Good Cop's interventions create a cooperator, and from savior it is a short step to trusted father confessor",
                "In Sherif's boys' camp experiments, common goals like a stuck truck and a broken water supply turned rivals into allies who ended up buying each other milkshakes",
            ],
        ),
    },
    {
        "num": 4,
        "title": "Chapter 4: Social Proof: Truths Are Us",
        "pages": "123-185",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Crowd-Counter",
            "Scan twelve scenes - a long nightclub line, a salted tip jar, a laughing studio audience, a five-star review cluster, a crowded platform - and identify the manufactured social evidence in each. Name the fake proof, who planted it, and who is meant to imitate it.",
            "A city street where each crowd is revealed to be partially mannequins - paid actors, ringers, pre-seeded tip dollars - while a truth-scanner highlights the planted evidence in red.",
            [
                "Certain nightclub owners manufacture visible social proof by creating long waiting lines outside when there is plenty of room inside",
                "Bartenders often salt their tip jars with a few dollar bills at the beginning of an evening to simulate tips left by prior customers",
                "Church ushers sometimes salt collection baskets for the same reason and with the same positive effect on proceeds",
                "Evangelical preachers are known to seed their audience with ringers, rehearsed to come forward at a specified time to give witness and donations",
                "Product-rating websites are regularly infected with glowing reviews that manufacturers have faked or paid people to submit",
                "Claquing is said to have begun in 1820 with a pair of Paris opera-house habitués named Sauton and Porcher, whose business was applause",
                "Claques offered the pleureuse, chosen for her ability to weep on cue, the bisseur, who called 'bis' and 'encore,' and the rieur, selected for the infectious quality of his laugh",
                "Sauton and Porcher charged by the staffer, recognizing that the more claqueurs scattered among an audience, the greater the persuasive impression that many liked the performance",
                "Experiments show that fabricated merriment leads audiences to laugh more frequently and longer, as well as to rate humorous material funnier (Provine, 2000)",
                "In Ecuador, 'lloronas' - hired criers - made more people cry at funerals",
                "In presidential-debate studies where on-site audience responses were technologically modified, whichever candidate seemed to get the strongest audience response won with remote viewers",
                "In 2019, the FTC charged Sunday Riley Skincare with posting positive customer reviews authored by employees who were pressured to do so by company leaders",
            ],
        ),
        "dialogue": (
            "Dialogue: The Bystander Emergency Interrogation",
            "Play the emergency victim and the frozen crowd: suffer a stroke-like collapse in a park, then test the moan, the cry for help, and the pinpointed command - 'You, sir, in the blue jacket, I need help. Call 911.' Then switch sides and decide who rescues whom.",
            "A park lawn where a figure crumples under a tree while dozens of onlookers are frozen mid-glance; each utterance option highlights a different onlooker, and the pinpointed one snaps into motion.",
            [
                "Pluralistic ignorance occurs when everyone looks to see what everyone else is doing, and all see others looking unruffled, so the event is roundly interpreted as a nonemergency",
                "The classic report began with a New York Times article: Kitty Genovese was killed in a late-night attack while thirty-eight of her neighbors watched without lifting a finger, though researchers later debunked the journalistic details",
                "In the Chicago case of Lee Alexis Wilson, a man who heard a scream about 2 p.m. did not investigate 'because no one else seemed to be paying attention'",
                "Once uncertainty is removed and witnesses are convinced an emergency exists, aid is very likely",
                "In staged Florida accidents where it was clear the maintenance man was hurt, he was helped 100 percent of the time in two experiments, and 90 percent of the time when the helping involved potentially dangerous electric wires",
                "Groups of bystanders fail to help because the bystanders are unsure rather than unkind",
                "The victim should call out clearly, 'Help,' and not worry about being wrong - embarrassment in such a situation is a villain to be crushed",
                "The most effective tactic is to single out one individual: 'You, sir, in the blue jacket, I need help. Call 911 for an ambulance'",
                "Pointing at one bystander removes all the uncertainties about whether aid is needed, who should provide it, and how to provide it",
                "In staged public fights between a man and a woman, nearly 70 percent of observers assumed the pair was romantically involved, while only 4 percent thought they were strangers",
                "A woman under attack should shout 'I don't know you!' to counter the lovers'-quarrel assumption that makes bystanders unwilling to intervene",
                "Observers were less willing to help a woman who shouted 'I don't know why I ever married you' than one who shouted 'I don't know you,' even though the fight's severity was identical",
            ],
        ),
        "audit": (
            "Audit: The Social-Proof Field Sweep",
            "Log a day of popularity cues - bestseller shelves, most-popular menus, trending feeds, waiting lines, review counts - and for each, record whether the evidence is genuine, planted, or misleadingly selective. Grade each one's validity, feasibility, and social-acceptance pull.",
            "A scrolling data wall where each popularity cue resolves into a bar graph of true versus manufactured followers, and a gauge swings between VALID and RIGGED.",
            [
                "Beijing restaurant dishes labeled 'most popular' jumped in sales by an average of 13 to 20 percent each - the dishes became more popular because of their popularity",
                "A truthful sign in a London pub that its porter was the week's most popular beer doubled porter sales immediately",
                "Telling McDonald's customers 'The McFlurry is our visitors' favorite' jumped McFlurry sales 55 percent, and naming the favorite topping raised topping purchases another 48 percent",
                "Sales and motivation consultant Cavett Robert: 'Since 95 percent of the people are imitators and only 5 percent initiators, people are persuaded more by the actions of others than by any proof we can offer'",
                "When the city of Louisville, Kentucky, told parking-ticket recipients that the majority of such citations are paid within two weeks, payments increased by 130 percent",
                "During the COVID-19 outbreak, the only major factor driving Japanese citizens' mask-wearing frequency was seeing other people wearing masks",
                "After learning that the majority of their peers try to eat fruit to be healthy, Dutch high school students increased fruit consumption by 35 percent, despite claiming no intention to change",
                "Governments that publicize environmental ratings of polluting firms produced dramatic improvements - upwards of 30 percent - mostly from the heavy polluters who saw how poorly they compared",
                "In Cialdini's household-energy study, the message 'Most of your fellow community residents do try to conserve energy at home' generated 3.5 times as much energy savings as appeals to the environment, social responsibility, or saving money",
                "At the Petrified Forest National Park, where 2.95 percent of visitors per day stole fossils, a sign depicting three thieves nearly tripled theft to 7.92 percent, while a lone-thief sign cut it to 1.67 percent",
                "Sociologist David Phillips found that within two months after every front-page suicide story, an average of 58 more people than usual killed themselves",
                "Phillips found that following certain highly publicized suicide stories, deaths in commercial-airline crashes increased by 1,000 percent, and pure-suicide stories produced only single-fatality wrecks while suicide-murder stories produced multiple-fatality wrecks",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Uncertainty, The Many, Similarity",
            "Sort a dozen influence scenarios - an unfamiliar menu, a packed restaurant, a peer's solar panels, a crowd looking skyward, a similarity-claiming fundraiser - into the optimizing condition each exploits: uncertainty, the many, or similarity. Then re-sort them by whether the proof is honest or counterfeit.",
            "A three-chamber sorting engine - a fog bank labeled UNCERTAINTY, a multiplying mirror hall labeled THE MANY, and a mirror pool of look-alikes labeled SIMILARITY - each scenario card dropping into its chamber.",
            [
                "The principle of social proof states that we determine what is correct by finding out what other people think is correct",
                "Social proof works best under three optimizing conditions: uncertainty, the many, and similarity",
                "The Beijing restaurant's 'most popular' label worked on all sorts of diners, but most strongly on infrequent visitors who couldn't rely on existing experience",
                "Sylvan Goldman's shopping carts sat unused until he hired shoppers to wheel them through the store, after which the invention swept the nation and made him wealthy",
                "In the New York City sky-staring experiment, a group of friends gazing upward caused 80 percent of passersby to lift their gaze, with the effect growing with group size up to about twenty people",
                "The more others performing an action, the more it appears correct and valid, feasible, and socially acceptable",
                "In the Essex shopping-mall study, a poster of a single early-lunch visitor raised prenoon food-court activity 25 percent, while a poster of several visitors raised it 75 percent",
                "Female fruit flies became 70 percent more willing to mate with males of a color they had seen other females choose - social proof operating without complex cognitive capacities",
                "A great strength of 'the many' is that it destroys the problem of uncertain achievability: if many neighbors conserve energy, conserving comes to seem realistic and actionable",
                "In a brain-scanner study, resisting the consensus of other people activated the amygdala, which the researchers called 'the pain of independence'",
                "In a smokers' clinic described by Yale psychologist Irving Janis, the lone dissenter who quit was attacked by the group and returned to two packs a day, greeted with applause",
                "Cults use love bombing - an initial showering of affection - to recruit members, and the threatened withdrawal of that affection to keep them once their outside bonds are cut",
            ],
        ),
        "boss": (
            "Boss Battle: The Jonestown Decision",
            "Stand in the unfamiliar jungle settlement where every similar other walks calmly toward the poisoned vat. Read the social evidence - the first volunteers, the unruffled crowd - and resist the herd: name the uncertainty, the exclusive similarity, and the pluralistic ignorance that made the compliance orderly. Then decide your own act.",
            "A tropical clearing at dusk where a line of figures moves peacefully toward a bright vat while the player stands apart, overlaying the scene with labeled vectors: UNCERTAINTY, SIMILAR OTHERS, PLURALISTIC IGNORANCE.",
            [
                "Reverend Jim Jones moved the People's Temple from San Francisco to a jungle settlement in Guyana in 1977, where it existed in relative obscurity until November 1978",
                "After Congressman Leo Ryan's party was murdered as it tried to leave by plane, Jones called for a unified act of self-destruction, and 910 people died in an orderly, willful fashion",
                "The first response came from a young woman who calmly administered one dose of the strawberry-flavored poison to her baby and one to herself, then sat down and died with her child within four minutes",
                "Psychiatrist Dr. Louis Jolyon West, who had observed the People's Temple for eight years, said of the mass suicide, 'This wouldn't have happened in California'",
                "The relocation created dread uncertainty: the members were dropped into a physical and social environment unlike anything they had experienced in San Francisco",
                "In a country such as Guyana, there were no similar others for a Jonestown resident but the people of Jonestown itself",
                "Each member looked to the others and found calmness because everyone else was surreptitiously assessing rather than reacting - a large-scale instance of the pluralistic-ignorance effect",
                "The first set of compatriots who willingly took the poison served as potent social evidence, far more compelling than the suicides of similar strangers in news stories",
                "The members had not been hypnotized; they had been convinced - partly by Jones but more importantly by peer-suasion - that suicide was correct conduct",
                "Jones's real genius was his realization of the limitations of individual leadership: no leader can persuade all members single-handedly, but the fact that a substantial number are convinced can convince the rest",
                "The most influential leaders are those who know how to arrange group conditions to allow the principle of social proof to work in their favor",
                "As slaughterhouse operators have long known, the mentality of a herd makes it easy to manage: get some members moving in the desired direction and the others will peacefully go along",
            ],
        ),
    },
]
