# -*- coding: utf-8 -*-
"""Phase 2 chapter data for Man's Search for Meaning (Viktor E. Frankl),
3 sections: Part I (Experiences in a Concentration Camp), Part II
(Logotherapy in a Nutshell), Postscript (The Case for a Tragic Optimism).
Each section: num, title, pages, domain, and 5 slots (scrub/dialogue/audit/matrix/boss),
each slot a 4-tuple (topic, player_mission, visual_frame_description, key_concepts[10-12]).
"""

D = "Existential Psychology | Resilience"

CHAPTERS = [
    {
        "num": 1,
        "title": "Part 1: Experiences in a Concentration Camp",
        "pages": "15-88",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Will-to-Live Gauge",
            "Scan a grid of camp scenes frozen at their critical moment and name the tell in each: the prisoner lighting his hidden cigarette, the morning refusal to dress and wash, the cold eye that no longer averts at a beating. Judge whether each man sits in shock, in relative apathy, or in the giving-up crisis before the scene's verdict is stamped.",
            "A foggy Appellplatz at dawn turned into a diagnostic board; every frozen prisoner is ringed in red while a gauge labeled Will to Live swings between Holds On and Gives Up and a chronometer ticks through the three phases of camp reaction.",
            [
                "Frankl was Number 119,104 and for most of his imprisonment dug and laid tracks for railway lines; he worked as a doctor only in the last few weeks",
                "Three phases of the inmate's mental reactions to camp life became apparent: the period following admission, the period when he is well entrenched in camp routine, and the period following his release and liberation",
                "The symptom that characterizes the first phase is shock, which under certain conditions may even precede the prisoner's formal admission to the camp",
                "In the second phase the prisoner achieved a kind of emotional death - relative apathy - which was partly a defensive mechanism and partly the result of hunger, lack of sleep, and the absence of nicotine and caffeine",
                "When the prisoners saw a comrade smoking his own cigarettes, they knew he had given up faith in his strength to carry on, and once lost, the will to live seldom returned",
                "The prisoner who had lost faith in the future was doomed: he would refuse one morning to get dressed and wash or go out on the parade grounds, and he simply gave up, lying in his own excreta",
                "The camp's most imperative law of self-preservation was 'Do not be conspicuous' - prisoners tried to submerge into the middle of the formation to escape the guards' blows and the bitter winds",
                "The death rate in the week between Christmas 1944 and New Year's 1945 increased beyond all previous experience because most prisoners had lived in the naive hope of being home by Christmas; the sudden loss of hope and courage can have a deadly effect",
                "Senior block warden F--, who dreamed that the war would end for him on March 30, 1945, fell ill on the 29th, became delirious on the 30th, and died on the 31st - his faith in the future and will to live had become paralyzed",
                "At the first selection the SS officer's finger pointed the sick and work-incapable to the left; about 90 percent of Frankl's transport were sent left and their sentence was carried out within the next few hours",
                "On the march to the work site, thoughts of his wife showed Frankl that love is the ultimate and highest goal to which man can aspire - 'The salvation of man is through love and in love'",
                "After liberation the prisoners were seized by depersonalization - everything appeared unreal - and they had literally lost the ability to feel pleased and had to relearn it slowly",
            ],
        ),
        "dialogue": (
            "Dialogue: The Hut at Lights Out",
            "Play Frankl in the darkened earthen hut the night the electric bulb failed after a day of fasting and hangings, and then play the despairing comrade who protests he has nothing more to expect from life. Speak of the future's hidden chances, the past that no power on earth can take away, and the sacrifice that gives suffering meaning - then switch seats and decide whether the words reach you before the light comes back.",
            "An earthen hut in pitch darkness where fifty emaciated figures lie motionless; a single voice speaks from the blackness while a dead electric bulb waits to flare back to life and reveal faces streaked with tears.",
            [
                "The tender beginnings of psychotherapy in camp aimed to prevent suicides, and a strict camp ruling forbade cutting down a man who tried to hang himself, so prevention was all-important",
                "Two would-be suicides both argued they had nothing more to expect from life, but each was shown something still expected of him - for one, his adored child waiting in a foreign country; for the other, the scientific books he still had to finish",
                "Frankl told the hut that even in the sixth winter of the war their situation was not the most terrible imaginable and that 'Whoever was still alive had reason for hope'",
                "Frankl quoted Nietzsche to the hut: 'Was mich nicht umbringt, macht mich starker' - that which does not kill me makes me stronger",
                "Frankl estimated his own chances of survival at about one in twenty, yet told the men he had no intention of losing hope, for no man knew what the next hour would bring",
                "He quoted the poet's line that what you have experienced no power on earth can take from you, and said having been is also a kind of being, perhaps the surest kind",
                "Frankl told the prisoners that someone looks down on each of us in difficult hours - a friend, a wife, somebody alive or dead, or a God - and would not expect us to disappoint him by suffering miserably",
                "He spoke of a comrade who made a pact with Heaven that his suffering and death should save the human being he loved from a painful end - for this man, suffering and death were meaningful",
                "When the bulb flared up again, the miserable figures of his friends limped toward Frankl to thank him with tears in their eyes",
                "He confessed that only too rarely did he have the inner strength to make contact with his companions in suffering, and that he must have missed many opportunities",
                "In the last camp a semi-starved prisoner broke into the potato store; when the authorities ordered the guilty man given up or the whole camp would starve, the 2,500 prisoners preferred to fast",
                "The right example was more effective than words: a senior block warden who did not side with the authorities had a thousand opportunities to exert a moral influence on those under him",
            ],
        ),
        "audit": (
            "Audit: The Three-Phase Field Log",
            "File every camp scene you witness under the correct phase of the prisoner's mental reaction: shock, relative apathy, or the psychology of liberation. For each entry record the symptom - the delusion of reprieve, the deadened emotions, depersonalization, bitterness, disillusionment - and note the exact moment the phase turns.",
            "A tattered prison ledger stamped with three seals - Admission, Entrenchment, Liberation - while vignettes of camp life fly in to be filed, each dissolving into the phase it exemplifies.",
            [
                "The newly arrived prisoner lived under a 'delusion of reprieve,' clinging to shreds of hope that he would be spared to the very last moment, like a condemned man expecting a last-minute pardon",
                "During the first phase the prisoners experienced a grim sense of humor and cold curiosity; after the showers, surprise that they did not catch cold - 'Textbooks tell lies!'",
                "The prisoners dreamed most frequently of bread, cake, cigarettes and warm baths; the lack of satisfaction of these simple desires led to wish-fulfillment in dreams",
                "Undernourishment explained the general preoccupation with food and the general absence of the sexual urge in the all-male camps",
                "There was a 'cultural hibernation' in camp with two exceptions - politics, which was talked about almost continuously on the basis of rumors, and religion, whose depth and vigor often surprised a new arrival",
                "In the typhus outbreak of the winter and spring of 1945, Frankl kept awake most nights composing speeches in his mind and reconstructing the manuscript he had lost in the disinfection chamber of Auschwitz",
                "Spiritual life could deepen in camp: sensitive people were able to retreat from terrible surroundings to a life of inner riches and spiritual freedom, which helped explain why some of less hardy make-up survived better",
                "The prisoners' complete lack of sentiment showed when Frankl's request for one look through the peephole at his native Vienna was refused with the words, 'You lived here all those years? Well, then you have seen quite enough already!'",
                "At the liberation the guards offered the prisoners cigarettes, but the word 'freedom' had lost its meaning; the first spark of joy came only at the sight of a rooster with a tail of multicolored feathers",
                "Bitterness struck the liberated man who heard the same phrases everywhere - 'We did not know about it' and 'We, too, have suffered'",
                "Disillusionment was different: a man who had reached the absolute limit of suffering found that suffering has no limits, and that he could suffer still more, and still more intensely",
                "The crowning experience of the homecoming man is the wonderful feeling that, after all he has suffered, there is nothing he need fear any more - except his God",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Decent or Indecent",
            "Sort a wall of faces - Capos, SS guards, foremen, senior wardens, ordinary prisoners - into the two races of men Frankl found in the camps: the decent and the indecent. Justify every call with the evidence on the card: the commander who bought medicines from his own pocket, the foreman's piece of bread, the senior warden who beat his own fellow prisoners.",
            "A barbed-wire sorting chamber where prisoners and guards step onto twin scales weighing decency and indecency, while a caption glows above the racks: 'No group consists entirely of decent or indecent people - no group is of pure race.'",
            [
                "From all this we may learn that there are two races of men in this world, but only these two - the race of the decent man and the race of the indecent man - and both are found everywhere",
                "The boundaries between groups overlapped: human kindness could be found in all groups, even those which as a whole it would be easy to condemn",
                "The prisoners found the lack of character in a prisoner who treated his own companions badly exceptionally contemptible",
                "The commander of the camp from which Frankl was liberated paid a small fortune from his own pocket to purchase medicines for his prisoners from the nearest market town",
                "The senior camp warden, a prisoner himself, was harder than any of the SS guards and beat the other prisoners at every slightest opportunity, while the camp commander never once lifted his hand against any of them",
                "A foreman once secretly gave Frankl a piece of bread which he knew must have been saved from his breakfast ration - it was the human 'something,' the word and look that accompanied the gift, that moved him to tears",
                "The Capos were chosen from the most brutal prisoners, although there were some happy exceptions; often they were harder on the prisoners than the SS men themselves",
                "Among the guards there were sadists in the purest clinical sense, and these sadists were always selected when a really severe detachment of guards was needed",
                "The feelings of the majority of the guards had been dulled by years of witnessing brutal methods; these hardened men refused to take active part in sadistic measures but did not prevent others from carrying them out",
                "A prisoner who lost the will to live and wanted to 'enjoy' his last days would smoke his own cigarettes - the only exception to the rule that smoking was reserved for the Capos",
                "Life in a concentration camp tore open the human soul and exposed its depths, where we found only human qualities which in their very nature were a mixture of good and evil",
                "The mere knowledge that a man was either a camp guard or a prisoner tells us almost nothing about the man's character",
            ],
        ),
        "boss": (
            "Boss Battle: The Final Selection",
            "Stand before the SS officer's lazily pointing finger on the Auschwitz railway ramp and rule on each life that files past - and then work the other side of the gate, keeping the man who has given up hope from becoming another corpse within the forty-eight hours. Survive the war of nerves of rumor and disappointment, and bring your own 'why' - the lost manuscript, the beloved - into the fight against the death of the will.",
            "The railway ramp at Auschwitz in the grey of dawn: a column of ragged men files past a slim, spotless SS officer who points right or left with one forefinger, while overhead the crematorium chimney sends a column of flame dissolving into smoke over the sky of Poland.",
            [
                "At the station the SS officer's finger pointed far more frequently to the left - the way for the sick and those incapable of work, who were marched straight to the crematorium building that had the word 'bath' written over its doors",
                "Frankl hid his haversack under his coat and forced himself to walk upright past the selecting officer, who put both hands on his shoulders and turned him to the right side",
                "About 90 percent of the transport's first selection meant death, and their sentence was carried out within the next few hours",
                "Frankl's friend P-- was sent to the left; a hand pointed to the chimney a few hundred yards off and the answer came: 'That's where your friend is, floating up to Heaven'",
                "At the disinfection chamber Frankl was told that his life's work, the manuscript of his scientific book, was nothing but 'Shit' - and at that moment he struck out his whole former life",
                "When Frankl saw a comrade smoking his own cigarettes, he knew the man had given up faith in his strength to carry on, and once lost, the will to live seldom returned",
                "The prisoner who saw no more sense in his life, no aim, no purpose, was soon lost; his typical reply to all encouragement was, 'I have nothing to expect from life any more'",
                "Nietzsche's words, 'He who has a why to live for can bear with almost any how,' could be the guiding motto for all psychotherapeutic and psychohygienic efforts regarding prisoners",
                "It did not really matter what we expected from life, but rather what life expected from us - life ultimately means taking the responsibility to find the right answer to its problems",
                "When a man finds that it is his destiny to suffer, he must accept his suffering as his single and unique task; his unique opportunity lies in the way in which he bears his burden",
                "We had realized suffering's hidden opportunities for achievement, as Rilke wrote, 'Wie viel ist aufzuleiden!' - how much suffering there is to get through - and there was no need to be ashamed of tears, for tears bore witness to the courage to suffer",
                "In the war of nerves, many times hopes for a speedy end of the war were disappointed; some men lost all hope, but it was the incorrigible optimists who were the most irritating companions",
            ],
        ),
    },
    {
        "num": 2,
        "title": "Part 2: Logotherapy in a Nutshell",
        "pages": "88-119",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Logos Detection Lab",
            "Scan twelve consulting-room vignettes and detect the clinical signature in each: the will to meaning, existential frustration, a noogenic neurosis, the existential vacuum, anticipatory anxiety, hyper-intention, or hyper-reflection. Name the condition, then prescribe the logotherapeutic move - paradoxical intention, dereflection, or reorientation toward meaning - before the case file seals itself.",
            "A Viennese consulting room rebuilt as a diagnostic scanner where each patient's hidden logos glows as a golden thread while gauges label the failure modes - vacuum, frustration, vicious circle - and a chalkboard lists the logotherapeutic counter-moves.",
            [
                "Logos is a Greek word which denotes 'meaning'; logotherapy, called by some the Third Viennese School of Psychotherapy, is a meaning-centered psychotherapy that focuses on the meanings to be fulfilled by the patient in his future",
                "The striving to find a meaning in one's life is the primary motivational force in man - the will to meaning - in contrast to the pleasure principle of Freudian psychoanalysis and the will to power of Adlerian psychology",
                "When the will to meaning is frustrated, logotherapy speaks of existential frustration, which can result in noogenic neuroses - neuroses originating in the noological, or spiritual, dimension rather than in psychological conflicts",
                "Not every conflict is necessarily neurotic: some amount of conflict is normal and healthy, and suffering may well be a human achievement rather than a symptom of neurosis",
                "A high-ranking American diplomat analyzed for five years was told his dissatisfaction with his career was hatred of 'father images'; Frankl saw his will to meaning frustrated by his vocation, and after changing careers he remained contented for over five years",
                "Mental health is based on a certain degree of tension - the gap between what one is and what one should become - which Frankl calls noo-dynamics; what man needs is not a tensionless homeostasis but the striving for a freely chosen worthwhile goal",
                "The existential vacuum stems from a twofold loss: man lost the animal instincts which secure an animal's behavior, and the traditions which buttressed his behavior are now rapidly diminishing",
                "No instinct tells man what he has to do, and no tradition tells him what he ought to do; instead he either wishes to do what other people do - conformism - or does what other people wish him to do - totalitarianism",
                "The existential vacuum manifests itself mainly in a state of boredom, including the 'Sunday neurosis'; depression, aggression and addiction are not understandable unless we recognize the existential vacuum underlying them",
                "The meaning of life differs from man to man, from day to day and from hour to hour; asking for it in general terms is comparable to asking a chess champion what is the best move in the world",
                "Ultimately, man should not ask what the meaning of his life is, but must recognize that it is he who is asked; he can only answer to life by answering for his own life - by being responsible",
                "The logotherapist's role is that of an eye specialist rather than a painter: he widens and broadens the visual field of the patient so that the whole spectrum of potential meaning becomes conscious and visible",
            ],
        ),
        "dialogue": (
            "Dialogue: The Eye Specialist's Chair",
            "Sit opposite the grieving general practitioner, the frustrated diplomat, and the young woman who lives in fear of the toll her childhood trauma will take, and improvise Frankl's questions - 'What would have happened, Doctor, if you had died first?' - to widen each patient's visual field. Then switch seats and answer as the patient: does the meaning become visible in your own words?",
            "An eye chart of meaning hangs in a plain consulting room where the therapist never paints a picture but only widens the view; behind each patient's head the spectrum of potential meanings slowly swims into focus.",
            [
                "To the elderly general practitioner mourning his wife, Frankl said her suffering had been spared her at the price that he must now survive and mourn her - in some way, suffering ceases to be suffering at the moment it finds a meaning, such as the meaning of a sacrifice",
                "Man's main concern is not to gain pleasure or to avoid pain but rather to see a meaning in his life; that is why man is even ready to suffer, on the condition that his suffering has a meaning",
                "Suffering is in no way necessary to find meaning; meaning is possible even in spite of suffering - provided the suffering is unavoidable, for to suffer unnecessarily is masochistic rather than heroic",
                "Love is the only way to grasp another human being in the innermost core of his personality, and by his love the loving person enables the beloved to actualize his potentialities",
                "In logotherapy love is not a mere epiphenomenon of sexual drives; love is as primary a phenomenon as sex, and normally sex is a mode of expression for love",
                "Self-actualization is possible only as a side-effect of self-transcendence: the more one forgets himself by giving himself to a cause to serve or another person to love, the more human he is",
                "Being human always points, and is directed, to something or someone other than oneself - be it a meaning to fulfill or another human being to encounter",
                "The young woman's frigidity had not been caused by the childhood abuse itself but by her constant fearful expectation of the toll it would someday take - anticipatory anxiety, plus excessive attention centered on herself rather than on her partner",
                "When her attention was refocused toward the proper object, the partner, and her excessive attention and intention were 'dereflected,' the orgasm established itself spontaneously",
                "Pleasure is, and must remain, a side-effect or by-product, and is destroyed and spoiled to the degree to which it is made a goal in itself",
                "Life's meaning is an unconditional one, for it even includes the potential meaning of unavoidable suffering - life retains this meaning literally to the end",
                "In the coat of a prisoner already sent to the gas chamber, Frankl found a single page torn from a Hebrew prayer book containing the Shema Yisrael - which he could only interpret as a challenge to live his thoughts instead of merely putting them on paper",
            ],
        ),
        "audit": (
            "Audit: The Noo-Dynamics Ledger",
            "Audit a week of case notes and file each patient under the three ways of discovering meaning - creating a work or doing a deed, experiencing something or encountering someone in love, or taking the right attitude toward unavoidable suffering. Balance each entry between what has been achieved and what still ought to be accomplished, and flag every case where a tensionless state is mistaken for health.",
            "A three-column ledger written in golden ink - Work, Love, Attitude - where every dropped case card makes a tension gauge rise toward noo-dynamics while a banner warns that equilibrium is not the goal.",
            [
                "According to logotherapy, meaning can be discovered in three different ways: by creating a work or doing a deed, by experiencing something or encountering someone, and by the attitude we take toward unavoidable suffering",
                "In the French public-opinion poll, 89 percent of the people polled admitted that man needs 'something' for the sake of which to live, and 61 percent conceded there was something, or someone, in their own lives for whose sake they were ready to die",
                "In the Johns Hopkins survey of 7,948 students at forty-eight colleges, 78 percent said their first goal was 'finding a purpose and meaning to my life,' while only 16 percent checked 'making a lot of money'",
                "Of Frankl's European students, 25 percent showed a more-or-less marked degree of existential vacuum; among his American students the figure was 60 percent",
                "In the Nazi concentration camps, those who knew that there was a task waiting for them to fulfill were most apt to survive - a conclusion reached also by studies of Japanese, North Korean and North Vietnamese prisoner-of-war camps",
                "Frankl's own deep desire to rewrite the confiscated manuscript helped him survive; jotted notes on scraps of paper in the Bavarian typhus camp assisted him in overcoming the danger of cardiovascular collapse",
                "Logotherapy's categorical imperative reads: 'Live as if you were living already for the second time and as if you had acted the first time as wrongly as you are about to act now!'",
                "The pessimist resembles a man who watches his wall calendar grow thinner with each passing day, while the activistic man files each removed leaf away with diary notes and reflects with pride on all the life he has lived to the fullest",
                "In the past nothing is irretrievably lost but everything irrevocably stored - having been is the surest kind of being",
                "A short life, like that of the mother's dead eleven-year-old boy, could be so rich in joy and love that it could contain more meaning than a life lasting eighty years",
                "Logotherapy is a meaning-centered therapy but also an analytical process that cares for existential realities, such as the potential meaning of the patient's existence to be fulfilled",
                "The transitoriness of existence in no way makes it meaningless; it constitutes our responsibleness, for everything hinges on our realizing the essentially transitory possibilities",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: The Three Viennese Schools",
            "Drag each case onto the doctrine that owns it - the pleasure principle of Freud, the striving for superiority of Adler, or the will to meaning of logotherapy - and separate psychogenic from noogenic origins at the same time. Justify every placement by quoting the theory behind it before the cases multiply into the collective neurosis of the age.",
            "A three-way sorting machine in a Viennese lecture hall: case cards slide down chutes labeled Pleasure, Power, and Meaning, while a counterweight shows which motive truly drives each patient and a gauge separates the psychological from the noological dimension.",
            [
                "Freudian psychoanalysis centers on the pleasure principle - the will to pleasure - while Adlerian psychology focuses on the striving for superiority, the will to power",
                "In contrast, logotherapy holds that man's search for meaning is the primary motivation in his life and not a 'secondary rationalization' of instinctual drives",
                "Meaning and values are not 'nothing but defense mechanisms, reaction formations and sublimations,' for man is able to live and even to die for the sake of his ideals and values",
                "Unmasking should stop as soon as one is confronted with what is authentic and genuine in man; the unmasking psychologist who goes further only unmasks his own unconscious need to debase what is genuinely human",
                "Noogenic neuroses do not emerge from conflicts between drives and instincts but from existential problems - from the frustration of the will to meaning",
                "Existential frustration is in itself neither pathological nor pathogenic: a man's concern, even his despair, over the worthwhileness of life is an existential distress but by no means a mental disease",
                "Logotherapy deviates from psychoanalysis insofar as it considers man a being whose main concern consists in fulfilling a meaning, rather than in gratifying drives or reconciling the id, ego and superego",
                "Freud's pansexualism was blamed for much, but the more erroneous and dangerous assumption is pan-determinism - the view that disregards man's capacity to take a stand toward any conditions whatsoever",
                "Man is not fully conditioned and determined but rather determines himself: man does not simply exist but always decides what his existence will be, what he will become in the next moment",
                "Dr. J., 'the mass murderer of Steinhof,' died in Lubianka prison in Moscow as the best comrade his fellow prisoner ever met - so how can we dare to predict the behavior of man?",
                "Freedom is the negative aspect of the whole phenomenon whose positive aspect is responsibleness; freedom degenerates into mere arbitrariness unless lived in terms of responsibleness",
                "Frankl recommended that the Statue of Liberty on the East Coast be supplemented by a Statue of Responsibility on the West Coast",
            ],
        ),
        "boss": (
            "Boss Battle: The Anticipatory Anxiety Loop",
            "Break the vicious circle of the sweating physician, the bookkeeper's writer's cramp, the lifelong stutterer, the sixty-five-year-old washing compulsion, and the insomniac - turning each fear back on itself with paradoxical intention before the feedback loop tightens into full phobia. One week per patient, and remember the mechanics: fear brings about what one is afraid of, and hyper-intention makes impossible what one wishes.",
            "A spiral staircase of anxiety looping forever upward; at its summit a trembling patient faces a mirror that shows the paradoxical wish - 'I only sweated out a quart before, but now I'm going to pour at least ten quarts!' - and the whole loop shatters into laughter.",
            [
                "Logotherapy's technique of paradoxical intention is based on the twofold fact that fear brings about that which one is afraid of, and that hyper-intention makes impossible what one wishes",
                "In paradoxical intention the phobic patient is invited to intend, even if only for a moment, precisely that which he fears; Frankl described the technique in German as early as 1939",
                "Anticipatory anxiety is characteristic of neurotic individuals: an individual afraid of blushing when entering a large room will actually be more prone to blush - the fear is mother of the event",
                "The young physician who feared perspiring was advised to resolve deliberately to show people how much he could sweat - and after four years of phobia he freed himself permanently of it within one week, after a single session",
                "The procedure is a reversal of the patient's attitude: his fear is replaced by a paradoxical wish, and by this treatment the wind is taken out of the sails of the anxiety",
                "Paradoxical intention must make use of the specifically human capacity for self-detachment inherent in a sense of humor - the neurotic who learns to laugh at himself may be on the way to self-management, perhaps to cure",
                "The bookkeeper with writer's cramp was told to write with the worst possible scrawl, saying 'Now I will show people what a good scribbler I am!' - and within forty-eight hours he was freed from his cramp",
                "The stutterer's only free moment in his life came at twelve when he tried to stutter to a streetcar conductor's sympathy and found he could not do it - he had practiced paradoxical intention without meaning to",
                "A sixty-five-year-old woman who had suffered for sixty years from a washing compulsion was able to lead a normal life two months after logotherapeutic treatment began",
                "For sleep disturbance, Frankl advises the patient not to try to sleep but rather to try to stay awake as long as possible - sleep soon follows the paradoxical intention not to fall asleep",
                "Paradoxical intention is effective regardless of the etiological basis of the case: factors that cause neuroses in early childhood may be entirely different from factors that relieve them in adulthood",
                "It is not the neurotic's self-concern, whether pity or contempt, which breaks the circle formation; the cue to cure is self-transcendence",
            ],
        ),
    },
    {
        "num": 3,
        "title": "Postscript: The Case for a Tragic Optimism",
        "pages": "119-142",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Tragic Triad Scanner",
            "Scan twelve life-scenes for the tragic triad - pain, guilt, and death - and judge which transformation each one permits: suffering turned into achievement, guilt turned into self-change, transitoriness turned into responsible action. Ring the instant a person finds the meaning, or sound the alarm when give-up-itis sets in and the forty-eight-hour countdown begins.",
            "A scanning arch over a hospital corridor where each scene's pain, guilt and death components glow red, amber and grey while the scanner overlays the golden paths of transformation available to the human potential.",
            [
                "Tragic optimism means that one is, and remains, optimistic in spite of the 'tragic triad' - pain, guilt, and death - and presupposes that life is potentially meaningful under any conditions, even the most miserable",
                "The human potential at its best always allows turning suffering into a human achievement and accomplishment, deriving from guilt the opportunity to change oneself for the better, and deriving from life's transitoriness an incentive to take responsible action",
                "Optimism is not anything to be commanded or ordered, and what is true for hope is true for faith and love as well - none of the three can be commanded",
                "To the European, being commanded to 'be happy' is characteristic of American culture, but happiness cannot be pursued; it must ensue - one must have a reason to be happy, and once the reason is found, one becomes happy automatically",
                "In concentration camps, the prisoners who one morning at five refused to get up and go to work and instead stayed in the hut and took out a hidden cigarette would be watched dying within the next forty-eight hours",
                "Meaning orientation had subsided in those dying prisoners, and consequently the seeking of immediate pleasure had taken over - a parallel to the 'no future' generation, which resorts not to a cigarette but to drugs",
                "The drug scene is one aspect of the feeling of meaninglessness resulting from frustration of our existential needs, a universal phenomenon in industrial societies",
                "In Vienna, 29 percent of the population complain that meaning is missing from their lives, differing from Irvin D. Yalom's Palo Alto figures by only 1 percent",
                "People today have enough to live by but nothing to live for; they have the means but no meaning - though some do not even have the means",
                "The feeling of meaninglessness is per se not a matter of pathology but the proof of one's humanness; it is not caused by anything pathological but it may well cause a pathological reaction",
                "The mass neurotic syndrome of depression, aggression and addiction is due to what logotherapy calls the existential vacuum, a feeling of emptiness and meaninglessness",
                "In his four years in charge of Austria's largest state hospital, Frankl explored about twelve thousand patients, mostly admitted after suicide attempts",
            ],
        ),
        "dialogue": (
            "Dialogue: The Deathbed Retrospective",
            "Lead the logodrama: put the wealthy, childless woman and the mother of the crippled son on their imagined deathbeds at eighty and let each look back over her life. Ask the questions that let them pass their own verdict - 'What will you think of it? What will you say to yourself?' - then switch seats and decide for yourself which life was the failure.",
            "Two hospital beds side by side in a darkened theater of the mind: the woman who lived it up sees her life dissolve into dust, while the mother who cared for her son watches her deeds glow like grain stored in the granary of the past.",
            [
                "The woman who had 'married a millionaire and lived it up' could not, looking back at eighty, see what it all was for - 'my life was a failure!'",
                "The mother of the handicapped son could say: 'I can look back peacefully on my life; for I can say my life was full of meaning, and I have tried hard to fulfill it - I have done my best - I have done the best for my son'",
                "A life of short duration, like that of her dead eleven-year-old boy, could be so rich in joy and love that it could contain more meaning than a life lasting eighty years",
                "The crippled son who had prevented his mother's suicide liked living - for him life had remained meaningful, and this posed the question of why it was not so for his mother",
                "Jerry Long, a quadriplegic since a diving accident at seventeen, typed with a mouth stick, attended college by telephone, and wrote: 'I view my life as being abundant with meaning and purpose... I broke my neck, it didn't break me'",
                "Long believed his handicap would only enhance his ability to help others: 'I know that without the suffering, the growth that I have achieved would have been impossible'",
                "Long had not chosen to break his neck, but he did decide not to let himself be broken by what had happened to him",
                "Researchers at the Yale University School of Medicine were impressed by Vietnam POWs who claimed that, although their captivity was filled with torture, disease and solitary confinement, they benefited from it as a growth experience",
                "An Austrian public-opinion poll reported that those held in highest esteem are neither great artists nor great statesmen but those who master a hard lot with their heads held high - empirical evidence for the 'know-how to suffer'",
                "A Polish cardiologist called it heroism when the SS leads you to a gas chamber and you can do nothing about it except go your way with dignity - attitudinal heroism",
                "Guilt is the second facet of the tragic triad: even criminals abhor being explained away as machines, and prefer to be held responsible for their deeds",
                "To the prisoners of San Quentin, Frankl said they were free to commit a crime, to become guilty, and now they are responsible for overcoming guilt by rising above it and growing beyond themselves - they felt understood",
            ],
        ),
        "audit": (
            "Audit: The Meaning Inventory",
            "Conduct an audit of a modern life - the young addict, the unemployed man, the pensioner, the person with means but no meaning - and file each under the three avenues to meaning: creating a work, experiencing love and encounter, or taking a stand toward suffering. For every entry, record whether you are seeing the proof of humanness or the pathology it can become.",
            "A municipal census office where human dossiers are weighed on the scales of the three avenues while a banner reads: 'They have the means but no meaning - man does not live by welfare alone.'",
            [
                "In unemployment neurosis, being jobless was equated with being useless, and being useless with having a meaningless life",
                "When the unemployed patients filled their abundant free time with unpaid but meaningful activity - youth organizations, adult education, public libraries - their depression disappeared although their economic situation had not changed",
                "Of the alcoholics studied by Annemarie von Forstmeyer, 90 percent had suffered from an abysmal feeling of meaninglessness, and of the drug addicts studied by Stanley Krippner, 100 percent believed that 'things seemed meaningless'",
                "In Carolyn Wood Sherif's experiment, the boy scouts' mutual aggressions subsided only when they dedicated themselves to a collective purpose - dragging out of the mud a carriage in which food had to be brought to camp",
                "In his explanation to a suicide-prone patient, Frankl noted that patients repeatedly told him how happy they were that their suicide attempt had not been successful - 'you have to survive in order to see that day dawn'",
                "A strong meaning orientation plays a decisive role in the prevention of suicide: an impulse to take one's life may be overcome if one is aware of some meaning and purpose worth living for",
                "The perception of meaning is completely down to earth: it boils down to becoming aware of a possibility against the background of reality - becoming aware of what can be done about a given situation",
                "Like a movie made of thousands of individual pictures, each situation in life carries a meaning, though the meaning of the whole cannot be seen before the last sequence is shown",
                "Conscience, for logotherapy, is a prompter that indicates the direction in which we have to move in a given life situation, evaluating it against a hierarchy of values rooted in our biological heritage",
                "The three main avenues to meaning in life are creating a work or doing a deed, experiencing something or encountering someone - meaning can be found not only in work but also in love - and the attitude taken toward a hopeless situation",
                "Even the helpless victim of a hopeless situation, facing a fate he cannot change, may rise above himself and grow beyond himself, and by so doing change himself - he may turn a personal tragedy into a triumph",
                "Logotherapy's notion that experiencing can be as valuable as achieving compensates for the one-sided emphasis on the external world of achievement at the expense of the internal world of experience",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Dignity or Usefulness",
            "Sort a stream of persons - the incurably ill, the old, the unemployed, the successful, the addicted - into the two value registers society constantly confounds: dignity that no condition can remove versus usefulness that can be lost at any moment. Reject every case where the achievement-oriented society blurs the decisive difference, and expose the mercy-killing logic hiding behind the confusion.",
            "Two courtroom scales side by side: one weighed down with dollar signs of usefulness, the other inscribed in indelible ink with the dignity of each person; the sorting clerk must send every soul to the correct register before the euthanasia program claims them.",
            [
                "The unconditional meaning of life is paralleled by the unconditional value of each and every person - it warrants the indelible quality of the dignity of man",
                "The value of each person is based on the values he has realized in the past and is not contingent on the usefulness he may or may not retain in the present",
                "Today's achievement-oriented society adores people who are successful and happy and virtually ignores the value of all those who are otherwise, blurring the difference between being valuable in the sense of dignity and being valuable in the sense of usefulness",
                "If one holds that an individual's value stems only from present usefulness, one owes it only to personal inconsistency not to plead for euthanasia along the lines of Hitler's 'mercy' killing of those who have lost their social usefulness",
                "There is no reason to pity old people; instead, young people should envy them, for the old have realities in the past - actualized potentialities, fulfilled meanings - that nothing and nobody can ever remove",
                "People tend to see only the stubble fields of transitoriness but overlook the full granaries of the past, into which they have brought the harvest of their lives: deeds done, loves loved, and sufferings gone through with courage and dignity",
                "Nihilism does not contend that there is nothing, but it states that everything is meaningless; George A. Sargent coined the concept of 'learned meaninglessness' from a therapist who taught that the world is a joke",
                "Frankl has never tired of arguing against the concept of collective guilt since the end of World War II - it is totally unjustified to hold one person responsible for the behavior of another person or a collective",
                "To the American woman who reproached him for writing in Hitler's language, Frankl asked how she could still use knives after so many killers had used them to stab and murder their victims",
                "Regarding guilt, the mysterium iniquitatis means a crime remains inexplicable, and totally explaining it would be tantamount to seeing in the criminal not a free and responsible human being but a machine to be repaired",
                "An ex-felon wrote to Frankl that he had started a logotherapy group for ex-felons twenty-seven strong, and the newer ones were staying out of prison through the peer strength of the original group",
                "Frankl's imperative against death's transitoriness: 'Live as if you were living for the second time and had acted as wrongly the first time as you are about to act now'",
            ],
        ),
        "boss": (
            "Boss Battle: The Give-Up-Itis Intervention",
            "Face the prisoner who refuses to rise at five o'clock and reaches for the hidden cigarette - you have forty-eight hours to restore his meaning orientation before the death watch begins. Persuade him that he must live to see the day dawn, and then fight the twin monsters that wait outside the wire: bitterness at the shrugs of the town, and disillusionment with a fate that seems to have no limits.",
            "A dark hut at dawn where a single figure lies on straw wet with urine and filth, the cigarette already lit; above him a two-day hourglass drains while the voices of hope and despair argue for his soul.",
            [
                "The prisoners who gave up and started smoking their hidden cigarettes would be watched dying within the next forty-eight hours - meaning orientation had subsided, and the seeking of immediate pleasure had taken over",
                "In American prisoner-of-war camps a parallel behavior pattern crystallized which soldiers called 'give-up-itis'",
                "Frankl told the suicide-prone that even if things only take a good turn in one of a thousand cases, no one can guarantee it will not happen in theirs - 'in the first place, you have to live to see the day on which it may happen'",
                "Since Auschwitz we know what man is capable of, and since Hiroshima we know what is at stake",
                'The world is in a bad state, but everything will become still worse unless each of us does his best - hence the challenge to join the minority of decent people, however rare they are',
                "In the camps people unmasked themselves: both the swine and the saints - think of Father Maximilian Kolbe, starved and finally murdered by an injection of carbolic acid at Auschwitz and canonized in 1983",
                "Contrary to Freud's prediction that hunger would blur all individual differences, in Auschwitz people became more different, not less - 'individual differences' did not blur",
                "If the suffering is avoidable, the meaningful thing to do is to remove its cause; if one cannot change a situation that causes his suffering, he can still choose his attitude",
                "The priority stays with creatively changing the situation that causes us to suffer, but the superiority goes to the 'know-how to suffer,' if need be",
                "An incurably sick person's life retains meaning up to the last moment, and life's meaning is an unconditional one, at least potentially",
                "The logotherapist should immunize the trainee against nihilism rather than inoculate him with cynicism, and may howl with the wolves while remaining a sheep in wolf's clothing",
                "Elisabeth S. Lukas noted that throughout the history of psychotherapy there has never been a school as undogmatic as logotherapy; Frankl argued for the degurufication of logotherapy and for passing the torch to independent and creative spirits",
            ],
        ),
    },
]
