# -*- coding: utf-8 -*-
"""Phase 2 chapter data for Mistakes Were Made (But Not by Me) (Tavris & Aronson,
3rd ed): Introduction + Chapters 1-4.
Each chapter: num, title, pages, domain, and 5 slots (scrub/dialogue/audit/matrix/boss),
each slot a 4-tuple (topic, player_mission, visual_frame_description, key_concepts[10-12]).
"""

D = "Self-Justification | Cognitive Dissonance"

CHAPTERS = [
    {
        "num": 0,
        "title": "Introduction",
        "pages": "12-20",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Past-Exonerative Phrase Hunt",
            "Scan a stream of public statements and flag every 'mistakes were made' phrasing: Kissinger on war crimes, Cardinal Egan on the bishops, Jamie Dimon on executive bonuses, McDonald's on beef-flavored fries. Name who is being absolved, decide whether the speaker is lying to others or to himself, and rate the stakes of each mistake.",
            "A newsroom ticker of apology headlines scrolls past; each statement freezes as a bracket highlights the passive voice while a silhouette of the speaker splits in two, one half labeled LIAR TO OTHERS and the other LIAR TO HIMSELF.",
            [
                "The phrase 'Mistakes were made' is a glaring effort to absolve oneself of culpability, so familiar it has become a national joke",
                "Political journalist Bill Schneider called 'Mistakes were made' the 'past exonerative' tense: 'Mistakes were made, but not by me, by someone else, someone who shall remain nameless'",
                "When Henry Kissinger said the administrations he served in made mistakes, he was sidestepping that as national security adviser and secretary of state he essentially was the administration",
                "Self-justification is more powerful and more dangerous than the explicit lie because it lets people convince themselves that what they did was the best thing they could have done",
                "The higher the stakes - emotional, financial, moral - the greater the difficulty of saying 'I was wrong; I made a terrible mistake'",
                "Most people, when directly confronted by evidence that they are wrong, do not change their point of view but justify it even more tenaciously",
                "George W. Bush was wrong about WMDs, Saddam's link to al-Qaeda, joyful Iraqis, a quick war, and the costs of the war, yet told a delegation of columnists, 'I've never been more convinced that the decisions I made are the right decisions'",
                "Lyndon Johnson would not heed advisers who said Vietnam was unwinnable and sacrificed his presidency to his self-justifying certainty that all of Asia would 'go Communist'",
                "Everyone can recognize a hypocrite in action except the hypocrite; as a character in Huxley's Point Counter Point says, 'I don't believe there's such a thing as a conscious hypocrite'",
                "Newt Gingrich railed about Bill Clinton's affair while having an extramarital affair himself, and evangelist Ted Haggard denounced homosexuality while enjoying a relationship with a male prostitute",
                "Self-justification is not the same thing as lying: a guilty man may lie to save his skin, but self-justification means he is lying to himself",
                "Whether the behavior is spilling ink on a hotel bedspread or embezzlement, the mechanism of self-justification is the same, as when professor Gordon Marino's friends persuaded him not to report his ink spot",
            ],
        ),
        "dialogue": (
            "Dialogue: The Dean Interrogation",
            "Play the interviewer questioning John Dean about how Nixon's men believed their own lies, then run the follow-up: watch a president justify a war to himself and decide whether he can still be corrected. Switch roles and test whether you can keep a self-justifying witness pinned to the facts.",
            "A 1970s press-conference room splits the screen: on one side Dean calmly says 'If you said it often enough, it would become true,' while on the other a president's face hardens as each inconvenient fact is deflected like a pinball.",
            [
                "John Dean, Nixon's White House counsel, explained that those who made up the cover-up stories were believing their own lies: 'If you said it often enough, it would become true'",
                "Dean said the national-security justification for the wiretaps was 'concocted as a justification after the fact,' yet when they said it they really believed it",
                "According to biographer Robert Caro, when Lyndon Johnson came to believe in something he believed it 'totally, with absolute conviction, regardless of previous beliefs, or of the facts in the matter'",
                "LBJ aide George Reedy said Johnson 'literally willed what was in his mind to become reality,' treating any contrary evidence as the prevarication of enemies",
                "A president who justifies his actions to the public might be induced to change them; a president who justifies his actions to himself is impervious to self-correction",
                "Memory is an unreliable, self-serving historian that prunes and shapes the past with an ego-enhancing bias, blurring the edges of events and softening culpability",
                "When researchers asked wives what percentage of the housework they did, the wives said at least 90 percent and the husbands said about 40 percent - the total always exceeded 100 percent by a large margin",
                "Over time, as self-serving distortions of memory kick in and we forget or misremember past events, we may come to believe our own lies, little by little",
                "We start underestimating our own responsibility, whittling away at it until it is a mere shadow of its former hulking self",
                "Before long, we have persuaded ourselves to believe privately what we said publicly",
                "People will lie to duck the fury of a lover, parent, or employer, but there is a big difference between telling the public something you know is untrue and persuading yourself that you did a good thing",
                "Politicians may reluctantly acknowledge error when their backs are against the wall, but they rarely acknowledge their responsibility for it",
            ],
        ),
        "audit": (
            "Audit: The Justification Field Log",
            "Spend a day logging every self-justification you catch yourself making - the finessed tax deduction, the office texting, the dead-end relationship you stay in. For each entry, identify the line you crossed, note who the justification fools, and rate whether the claim is true, partly true, or invented.",
            "A diary page overflows with handwritten rationales that each branch into a decision tree; a cursor drags each one onto a scale that tips between HONEST MISTAKE and SELF-DECEPTION while a second scale weighs 'was it true?' against 'why say it?'",
            [
                "People finesse expenses on income taxes by reasoning that the government wastes money on pork-barrel projects they detest",
                "People text, write personal e-mails, and shop online at the office because those 'perks of the job' are their own form of protest against stupid company rules",
                "We stay in an unhappy relationship or deadening job far too long because we invest effort in finding reasons to justify staying",
                "We buy a lemon of a car because it looks gorgeous, spend thousands to keep it running, then spend even more to justify that investment",
                "Gordon Marino decided not to report the ink spot he left on a hotel bedspread after a friend argued that management builds such accidents into the price of the rooms",
                "Whether those justifications are true or false is irrelevant - we are justifying behavior we know is wrong so we can continue to see ourselves as honest people",
                "Marino reasoned he would have reported the accident in a family-owned bed-and-breakfast, 'yadda yadda yadda went the hoodwinking process'",
                "We self-righteously create a rift with a friend over a real or imagined slight yet see ourselves as the pursuers of peace if only the other side would apologize",
                "Self-justification minimizes our mistakes and bad decisions and blurs the discrepancy between our actions and our moral convictions",
                "It also explains why we each draw our own moral lines: the tax finesser is 'entitled' given what the government wastes, and the office texter's boss 'doesn't appreciate all the extra work'",
                "Mindless self-justification, like quicksand, can draw us deeper into disaster, blocking our ability to even see our errors, let alone correct them",
                "To err is human, but humans then have a choice between covering up and fessing up - and we cannot learn from mistakes unless we first admit that we made them",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Explanation x Evidence x Consequence Grid",
            "Fill the grid for five mysteries that open the book: the Dinka and Nuer tooth extraction, Semmelweis's ignored discovery, Farnham's career advice, the Kern County detectives' choice, and the refusers of handwashing. For each, sort the rational explanation from the self-justifying one and decide whether lives were saved or lost by the choice.",
            "A museum wall of five case files lights up one by one; each file's evidence strips are sorted into two columns, 'what the facts say' and 'what the ego insists,' while a toll counter of lives lost ticks upward beneath the unsolved files.",
            [
                "In the 1840s, childbed fever killed about 15 percent of women delivering in one Vienna maternity ward, and at the epidemic's peak one-third of them died - three times the rate in the ward attended by midwives",
                "Ignaz Semmelweis hypothesized that doctors and medical students carried a 'morbid poison' from the autopsy rooms to the delivery rooms",
                "When Semmelweis had his students wash their hands in a chlorine antiseptic solution, the women stopped dying - astonishing, lifesaving results",
                "Semmelweis's colleagues refused to accept the evidence of the lower death rate among his patients",
                "The physicians could not accept his lifesaving intervention because they would have had to admit they had caused the deaths of all those women - an intolerable blow to their view of themselves as wise healers",
                "The Dinka and Nuer tribes still extract their children's front teeth, a practice that began when tetanus (lockjaw) was widespread and missing teeth let sufferers drink, long after the epidemic passed",
                "The toothless look survives because the villagers say it is beautiful, that full teeth make a man look like a donkey, and that the ritual is a sign of maturity - the original medical justification is gone but the psychological self-justification remains",
                "Marynia Farnham, coauthor of the bestseller Modern Woman: The Lost Sex, claimed women who achieved in 'male spheres of action' became frigid and damaged, yet built her own career on telling women not to have careers",
                "Kern County, California, detectives chose to believe a career criminal facing six years in prison over a woman with no criminal record and corroborating calendars and boss, and the retired principal Patrick Dunn was arrested for murder on that basis",
                "The question 'How can they live with themselves?' is answered by self-justification: ruthless dictators, corrupt CEOs, and priests who molest children live with themselves exactly the way the rest of us do",
                "Self-justification has costs and benefits: it lets us sleep at night and spares us regret, but it distorts reality and keeps professionals from changing outdated attitudes that can harm the public",
                "Understanding the inner workings of self-justification lets us defeat the wiring - the authors promise solutions in chapter 8 and the party-loyalty dilemma in chapter 9",
            ],
        ),
        "boss": (
            "Boss Battle: The Semmelweis Refusal",
            "Stand in the Vienna hospital and defend Semmelweis's chlorine handwashing before his colleagues: present the death-rate evidence, anticipate each dismissal of the data, and persuade the physicians to accept responsibility. Then face the second boss - a president justifying a failed war - and find the argument that reaches a man who has justified everything to himself.",
            "A candlelit 1840s ward with two columns of graves: the physicians' ward has a tower of small white crosses while the midwives' ward stands lower, and every time a colleague refuses the chlorine basin a new cross drops onto the tower.",
            [
                "Semmelweis told his medical students to wash their hands in a chlorine antiseptic solution before entering the maternity ward, and the women stopped dying",
                "The lower death rate among Semmelweis's patients was astonishing, lifesaving evidence, and yet his colleagues refused to accept it",
                "The refusal happened long before the era of malpractice suits, so we can say with assurance that the physicians were acting to protect their egos, not their income",
                "Their refusal is called the Semmelweis phenomenon: accepting his simple intervention would have meant admitting that they had been the cause of all those unnecessary deaths",
                "A president who justifies his actions to himself, believing he has the truth, is impervious to self-correction",
                "Bush's justifications for the war grew: he was removing a 'very bad guy,' fighting terrorists, bringing democracy, and finishing 'the task our troops gave their lives for'",
                "Sixteen American intelligence agencies reported that the occupation had increased Islamic radicalism, yet Bush's mental armor of self-justification could not be pierced",
                "None of us can avoid making blunders, but we have the ability to say, 'This is not working out here. This is not making sense'",
                "Without self-justification we would prolong the awful pangs of embarrassment and agonize over every decision - which is why it lets us sleep at night",
                "The good news is that by understanding how the mechanism works, we can defeat the wiring; understanding is the first step toward change and redemption",
                "Self-justification keeps the guilty from taking responsibility for their deeds and prolongs and widens rifts between lovers, friends, and nations",
                "All of us share the impulse to justify ourselves and avoid taking responsibility for actions that turn out to be harmful, immoral, or stupid",
            ],
        ),
    },
    {
        "num": 1,
        "title": "Chapter 1: Cognitive Dissonance: The Engine of Self-Justification",
        "pages": "20-46",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Dissonance Detector",
            "Scan twelve everyday scenarios - a smoker defending cigarettes, a doomsayer after the failed date, a cheater on an exam - and name the two clashing cognitions in each. Then choose how the person reduces the tension: by changing behavior, changing the belief, or adding a justifying belief.",
            "A scanner bay where each scenario's two conflicting ideas glow red against each other like repelling magnets until a person-shaped figure pulls a justification blanket over them and the glow fades to calm blue.",
            [
                "Cognitive dissonance is a state of tension that occurs when a person holds two cognitions that are psychologically inconsistent, such as 'Smoking is a dumb thing to do because it could kill me' and 'I smoke two packs a day'",
                "Dissonance produces mental discomfort ranging from minor pangs to deep anguish, and people don't rest easy until they find a way to reduce it",
                "The most direct way for the smoker to reduce dissonance is by quitting; if she has failed to quit, she must reduce dissonance by convincing herself that smoking isn't really so harmful",
                "Festinger's theory is about how people strive to make sense of contradictory ideas and lead lives that are, at least in their own minds, consistent and meaningful",
                "Festinger and two associates infiltrated a group who believed the world would end on December 21, 1954, and whose leader Marian Keech promised the faithful would be picked up by a flying saucer at midnight on December 20",
                "Many of Mrs. Keech's followers quit their jobs, gave away their houses, and disbursed their savings in anticipation of the end",
                "Festinger predicted that believers who made only weak commitments would quietly lose their faith, but those who had given away their possessions would increase their belief and try to convert others",
                "At 4:45 a.m., with no spaceship in sight, Mrs. Keech had a new vision: the world had been spared because of the impressive faith of her little band",
                "The group's mood shifted from despair to exhilaration, and followers who had never proselytized began calling the press and buttonholing passersby to convert them",
                "Hardly anyone who believes in doomsday predictions ever says 'I blew it!' - most of the time the doomsayers become even more deeply convinced of their powers of prediction",
                "Mrs. Keech's prediction had failed, but not Leon Festinger's",
                "The theory inspired more than three thousand experiments and entered popular culture, from political columns and bumper stickers to Jeopardy! and a New Yorker humor column",
            ],
        ),
        "dialogue": (
            "Dialogue: The Believing-Is-Seeing Debate",
            "Play the violinist whose beloved Stradivarius tests inferior to modern violins, and argue against the researcher who keeps coming back with better studies. Then become Lenny Bruce at the 1960 Nixon-Kennedy debate, watching both rooms of fans declare their candidate the winner, and decide what evidence would ever change a committed partisan's mind.",
            "A concert hall materializes mid-blind-test: goggled violinists bow instruments behind a curtain while a luxury violin case glows under a spotlight, and on the far wall two living rooms replay the debate with each side's cheers doubling like an echo chamber.",
            [
                "If new information is consonant with our beliefs we think it is well founded - 'Just what I always said!' - but if it is dissonant we consider it biased or foolish",
                "When people are forced to look at disconfirming evidence, they find a way to criticize, distort, or dismiss it so they can maintain or even strengthen their existing belief - a mental contortion called the confirmation bias",
                "In blind tests in hotel rooms, thirteen of twenty-one professional violinists chose a new instrument over a Stradivarius, and everyone's least favorite of six instruments was a Strad",
                "A follow-up study with ten soloists testing six old and six new violins in a rehearsal room and a concert hall found the modern violins rated higher on playability, articulation, and projection, with guesses no better than chance",
                "Strads were rated as sounding better only when listeners knew what they were hearing: 'If you know it's a Strad, you will hear it differently,' said the lead researcher",
                "Lenny Bruce watched Kennedy fans declare 'He's really slaughtering Nixon' and Nixon fans declare 'How do you like the shellacking he gave Kennedy?' - each group loved its candidate so much no evidence would move them",
                "After 2003 made clear there were no WMDs in Iraq, most Republicans resolved the dissonance by telling a Knowledge Networks poll that the weapons had been found",
                "Democrats who had backed Bush reduced dissonance by forgetting: 46 percent supported the invasion before it, but by 2006 only 21 percent remembered having done so",
                "In Westen's MRI study, the reasoning areas of the brain virtually shut down when participants confronted dissonant information, and emotion circuits activated when consonance was restored",
                "Readers of dueling articles on the death penalty did not move toward each other; each side became even more committed to its own position",
                "The backfire effect means people who receive disconfirming information may support their original wrong opinion even more strongly - changing our minds is literally hard work",
                "The absence of evidence is treated as evidence: when the FBI found no satanic-cult murders, believers said that proved how clever the cult leaders were, and General John DeWitt called the absence of Japanese-American sabotage 'a disturbing and confirming indication'",
            ],
        ),
        "audit": (
            "Audit: The Justification-of-Effort Log",
            "Audit six initiations - the severe fraternity hazing, the Thaipusam kavadi, and Elliot's Lady Chatterley experiment - and log how much liking each ordeal produced. Then interview the participants: the severe-initiation members who called the boring tape fascinating and the Mauritian men who donated after the mountain climb, and decide whether effort truly caused the commitment.",
            "A gymnasium-sized ledger where each ordeal is a row: needles, hooks, and barefoot mountain climbs in one column and a chart of resulting donations and membership ratings climbing in the other, each rise tied back to the ordeal by a red string.",
            [
                "Elliot predicted that people who go through pain, discomfort, effort, or embarrassment to get something will be happier with it than if it came easily - a preposterous idea to behaviorists",
                "In the experiment with Judson Mills, Stanford students randomly assigned to a severely embarrassing initiation recited lurid passages from Lady Chatterley's Lover, while others read sexual words from the dictionary",
                "All students then heard the same boring, worthless taped discussion of the secondary sex characteristics of birds",
                "Mild-initiation students correctly rated the discussion worthless and the members unappealing, but severe-initiation students rated the discussion interesting and exciting and forgave the one stammering member who hadn't done the reading",
                "The experiment has been replicated with techniques from electric shock to excessive physical exertion - severe initiations always increase a member's liking for the group",
                "At the Hindu festival of Thaipusam in Mauritius, participants in the severe kavadi ritual are pierced with needles and skewers and drag carts attached by hooks to their skin for more than four hours before climbing a mountain barefoot",
                "Afterward, the severe-ordeal participants anonymously donated much more money to the temple than the low-ordeal participants - the greater the pain, the greater the commitment",
                "The findings mean that if you voluntarily go through a difficult experience to attain a goal, that goal becomes more attractive - a flowerpot falling on your head would not make you like a group, but volunteering to be hit would",
                "The racetrack study found that bettors who had placed their bets were far more certain their horses would win than people still standing in line - only the finality of the bet had changed",
                "The more costly and irrevocable a decision, the greater the dissonance and the greater the need to overemphasize the good things about the choice made",
                "Sunk costs make people throw good money after bad rather than cut their losses, so ask advice from someone still gathering information, and get the data from controlled experiments, not testimonials",
                "After the initiation experiment, every severe-initiation participant insisted his liking of the group had nothing to do with the severity - yet almost all of them liked the group more than the mild-initiation people did",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Choice x Cost x Irrevocability x Bolstering Grid",
            "Fill the grid for five post-decision spirals: Nick's Mercedes, Elliot's canoe, the Casablanca choice, Mrs. Keech's converts, and the pyramid-of-choice cheaters. For each, record the cost, whether the decision was irrevocable, and the exact self-justifying arguments the decider marshaled afterward.",
            "A decision-pyramid hologram fills the room: each choice starts as a point of light at the apex, and as the decider's justifications pile up, two figures slide down opposite edges until they stand at opposite corners of a glowing base.",
            [
                "Dan Gilbert's data on Casablanca showed that whether Ingrid Bergman stayed with Bogart or rejoined her husband, either decision would have made her happy - she would have found reasons to justify either choice",
                "Nick, who impulsively traded his eight-year-old Honda Civic for a fully loaded Mercedes, began criticizing his friends' cars and lecturing them that little cars are unsafe, marshaling arguments to justify his purchase",
                "Nick's need to reduce dissonance was increased by the irrevocability of his decision - he could not unmake it without losing a lot of money",
                "Mrs. Keech's true believers saved their self-esteem by deciding they hadn't done anything stupid: their faith had saved the world from destruction, so smart people would join them too",
                "Dissonance is most painful when an important element of self-concept is threatened - you feel far more devastating dissonance doing an immoral thing yourself than hearing about a celebrity's transgression",
                "The Lake Wobegone effect: the great majority of people think they are better than average - smarter, nicer, more ethical, funnier, more competent, even better drivers",
                "Two identical young men facing the same temptation - one yields to cheating, one resists - a week later are a great distance apart: the cheater decides cheating is no big deal and everyone does it, and the resister decides cheaters should be permanently expelled",
                "By the bottom of the pyramid, both students have internalized their beliefs and are convinced they always felt that way - it's the people who almost decide to live in glass houses who throw the first stones",
                "After seventy-one Stuyvesant High School students were caught exchanging exam answers, they redefined cheating as 'taking a risk,' a 'necessary evil,' or 'helping classmates in need'",
                "Hana Beshara, sent to prison for sixteen months for pirating films, said 'It didn't seem like it was something to be bothered with. Even if it is wrong'",
                "Entrapment runs on action, justification, further action: Jeb Magruder first justified Haldeman's brutal chewing out over a missing golf cart, a tiny first step onto the road to Watergate",
                "Magruder said Liddy's plan was approved because 'Decisions that now seem insane seemed at the time to be rational' - they were past the point of halfway measures or gentlemanly tactics",
            ],
        ),
        "boss": (
            "Boss Battle: The Milgram Escalation",
            "Stand at the shock machine and decide where you draw the line as the voltage climbs from ten toward the switch marked XXX DANGER - nearly everyone predicts they will stop early, and two-thirds of real participants went all the way. Then counsel Jeb Magruder after his sentencing, and explain exactly how an honest man loses his ethical compass one step at a time.",
            "A laboratory corridor of toggle switches lit in ascending red, each click ratcheting a pain gauge; at the far end a man in a lab coat intones 'The experiment requires that you continue,' while behind him a courtroom judge watches a defendant whose compass needle spins loose.",
            [
                "In Milgram's original version, two-thirds of the participants administered what they thought were life-threatening levels of electric shock simply because the experimenter kept saying, 'The experiment requires that you continue'",
                "When people were asked in advance how far they would go, almost no one said they would go to 450 volts - but in the situation, two-thirds went all the way to the maximum level they believed was dangerous",
                "Participants escalated by justifying each step: 'This small shock doesn't hurt; twenty isn't much worse than ten; if I've given twenty, why not thirty?'",
                "With each justification they committed themselves further, until by the time they were administering strong shocks most found it difficult to justify a decision to quit",
                "Participants who resisted early, questioning the validity of the procedure itself, were less likely to become trapped by it and more likely to walk out",
                "Haldeman flattered and charmed Magruder at San Clemente, telling him he was working to solve the problems of the country and the world",
                "After Haldeman gave his assistant a 'brutal chewing out' over a missing golf cart, Magruder soon justified the behavior: after being spoiled by the perfection of San Clemente, a missing golf cart could seem a major affront",
                "Liddy's first plan was to spend one million dollars on squads to rough up demonstrators, kidnap activists, sabotage the Democratic Convention, and blackmail leading Democrats; Mitchell rejected the extreme plan as too expensive and Liddy returned with a mere break-in and wiretaps",
                "Magruder wrote that had Liddy proposed 'a plan to burglarize and wiretap Larry O'Brien's office, we might have rejected the idea out of hand,' but they began toning down his elaborate scheme while feeling they should leave him a little something",
                "At his sentencing, Magruder told Judge John Sirica, 'Somewhere between my ambition and my ideals, I lost my ethical compass'",
                "How do you get an honest man to lose his ethical compass? You get him to take one step at a time, and self-justification will do the rest",
                "Knowing how dissonance works won't make anyone automatically immune - Elliot bought a canoe in a Minnesota January to justify buying the suburban house, and his wife's reaction was 'Ask Leon Festinger!'",
            ],
        ),
    },
    {
        "num": 2,
        "title": "Chapter 2: Pride and Prejudice... and Other Blind Spots",
        "pages": "46-72",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Blind-Spot Scanner",
            "Scan twelve scenes - Scalia duck hunting with Cheney, Al Campanis on Nightline, the Hasidic Jews at the Museum of Tolerance - and locate the blind spot in each: the bias the person is certain they do not have. Name the delusion the brain is conferring and decide what evidence could make the person see it.",
            "A scanning chamber where each person's visual field is projected on a wall, complete with a dark patch they cannot see; the projector tracks their confident gaze while a narrator whispers the size of the patch they are missing.",
            [
                "The brain is designed with blind spots, optical and psychological, and one of its cleverest tricks is to confer on its owner the comforting delusion that he or she does not have any",
                "Lee Ross named the conviction that we perceive objects and events clearly, 'as they really are,' naive realism",
                "Naive realism presupposes that open-minded, fair people ought to agree with a reasonable opinion, and that any opinion I hold must be reasonable - so if opponents don't agree after listening, they must be biased",
                "Justice Antonin Scalia, flying on a government plane to duck hunt with Dick Cheney while Cheney had a pending case, refused to recuse himself, writing, 'I do not think my impartiality could reasonably be questioned'",
                "Al Campanis, who had punched a bigoted player for insulting Jackie Robinson, told Ted Koppel on Nightline that black men 'may not have some of the necessities to be, let's say, a field manager,' and was fired two days later",
                "Campanis was not a bigot: he had a blind spot - he thought black men could be great players but weren't smart enough to be managers - and as general manager his blind spot kept him from even considering hiring one",
                "A year later Campanis said he had been 'wiped out' during the interview, but when people say they said things because they were tired, worried, angry, or drunk, we can be pretty sure they really believe them",
                "At the Museum of Tolerance, the UNPREJUDICED door is locked, and the authors once watched four Hasidic Jews pounding angrily on it, demanding to be let in",
                "Marynia Farnham, who made her fortune advising women to stay home, saw no irony in being a working physician who was not staying home raising her own two children - privilege is their blind spot",
                "People who fly in the main cabin call business-class passengers wasteful snobs until they themselves are flying business, when pity and disdain for the 'steerage' passengers take over",
                "Our innate biases are like optical illusions: they lead us to wrong conclusions from data, and their apparent rightness persists even when we have been shown the trick",
                "Introspection alone will not help our vision, because it will simply confirm our self-justifying beliefs that we personally cannot be co-opted or corrupted",
            ],
        ),
        "dialogue": (
            "Dialogue: The Ross Negotiation Table",
            "Mediate a peace table where the same proposal is judged brilliant when attributed to your side and worthless when attributed to theirs - Ross's Israeli-Palestinian experiment made this visible. Then run Cohen's welfare experiment and ask the participants to explain their 'logical' reasoning, and finally rule on Scalia's impartiality as the perfect test case of a blind spot wearing a robe.",
            "A negotiation table where proposal documents slide between two delegations and an overhead projector swaps the attribution labels; each time the label flips, the judges' favorability meters swing in opposite directions while everyone insists their judgment was objective.",
            [
                "Ross took peace proposals created by Israeli negotiators, labeled them as Palestinian proposals, and asked Israeli citizens to judge them - they liked the Palestinian proposal attributed to Israel more than the Israeli proposal attributed to the Palestinians",
                "Ross asks: if your own proposal isn't attractive when it comes from the other side, what chance is there the other side's proposal will be attractive when it actually comes from them?",
                "Geoffrey Cohen found that Democrats endorsed an extremely restrictive welfare proposal if they thought the Democratic Party proposed it, and Republicans supported a generous welfare policy if they thought it came from the Republican Party",
                "Label the same proposal as coming from the other side, and you might as well be asking people to support a policy proposed by Hitler, Stalin, or Attila the Hun",
                "None of the people in Cohen's study were aware of their blind spot - all claimed their beliefs followed logically from their own careful study of the policy",
                "We believe our own judgments are less biased partly because we rely on introspection to tell us what we are thinking, but we have no way of knowing what others are truly thinking",
                "We take our own involvement in an issue as a source of accuracy ('I've felt strongly about gun control for years, therefore I know what I'm talking about') but regard others' feelings as a source of bias",
                "A study of 4,519 votes by Supreme Court justices in over five hundred cases between 1953 and 2011 found they favored free speech for speakers they agreed with: conservative Roberts-court justices ruled for conservative speakers about 65 percent of the time and liberal speakers about 21 percent",
                "Justice Oliver Wendell Holmes Jr. said the First Amendment protects 'freedom for the thought that we hate' - strong dissonance for judges to overcome, though most imagine they are up to the challenge",
                "Even when each side of the Israeli-Palestinian conflict recognizes the other perceives the issues differently, each thinks the other side is biased while they themselves are objective",
                "The need to avoid dissonance assures us, when we look into our souls, that we have only the best and most honorable of motives",
                "All of us are as unaware of our blind spots as fish are unaware of the water they swim in",
            ],
        ),
        "audit": (
            "Audit: The Funding-Bias Ledger",
            "Audit the trail of money in research and medicine: compare industry-funded and independent studies on the same chemicals, count the gifts flowing to physicians and bioethicists, and trace how each recipient justified taking them. Log each gift with its size, its recipient, and the exact justification offered - 'It's only a flower,' 'It's only a pizza.'",
            "A forensic accountant's board pins a web of dollar bills between drug companies and clinics; each bill is tagged with the recipient's spoken justification, and the tags grow longer the smaller the gift while a neutrality gauge quietly empties.",
            [
                "Of 161 studies of four chemicals' health risks, only 14 percent of industry-funded studies found harmful effects while fully 60 percent of independently funded studies did",
                "Of more than 100 controlled clinical trials comparing a new medication with an older one, only 13 percent favoring the traditional drug had been funded by drug companies, versus 87 percent by nonprofit institutions",
                "In 159 clinical trials published in the British Medical Journal, findings were 'significantly more positive toward the experimental intervention' when the study was funded by a for-profit organization",
                "When motivated to show a new drug is effective, a researcher will downplay misgivings and resolve ambiguity in the company's favor - the reasoning of Merck-funded investigators studying Vioxx before independent scientists produced evidence of its risks",
                "A national survey of nearly three thousand physicians found that 84 percent had received some form of compensation from the pharmaceutical industry - samples, food, reimbursements, payments for services",
                "In a five-month period in 2013, pharmaceutical companies and device makers paid $3.5 billion to health-care professionals and teaching hospitals, including about $380 million in fees to 546,088 individual physicians",
                "Physicians regard small gifts as ethically more acceptable than large ones, and the AMA approves of gift-taking as long as no single gift is worth much more than a hundred dollars - but most physicians are influenced even more by small gifts than by big ones",
                "Being given a gift evokes an implicit desire to reciprocate: the Fuller Brush salespeople's foot-in-the-door and the Hare Krishna flower at the airport both work because the gift creates a feeling of indebtedness",
                "The amount of contact doctors have with pharmaceutical representatives is positively correlated with the cost of the drugs the doctors later prescribe",
                "Hal Elliott, a psychiatrist, went from giving a community talk about depression to lecturing on a drug company's new antidepressant - 'When did the prostitution actually start? Wasn't it at that party?'",
                "Bioethicists justify consulting fees with claims like 'Objectivity is a myth' and by comparing ethics consultation to a financial audit, which Carl Elliott rejects: 'How do you tell the difference between an ethics consultant who has changed her mind for legitimate reasons and one who has changed her mind for money?'",
                "The AMA's own initiative to educate doctors about gift-taking was funded by $590,092 in gifts from Eli Lilly, GlaxoSmithKline, Pfizer, and other drug companies",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Prejudice x Justification x Target Grid",
            "Fill the grid mapping each prejudice episode to its self-justification: Campanis's 'necessities,' Allport's Mr. X, the antigay students explaining away Robert's football watching, and the Stormfront members explaining away their DNA results. For each, record what stereotype did the justifying and what behavior it excused.",
            "A wall of index cards cross-indexed by strings: each card holds a slur or stereotype on one side and the dissonance-reducing excuse on the other, and every card is connected by red thread to the harmful act it justified.",
            [
                "Stereotypes are energy-saving devices that let us make efficient decisions from past experience, but they flatten out differences within a category and exaggerate differences between categories",
                "Marilynn Brewer's kindergarten daughter declared 'boys are crybabies' from seeing two boys cry, while explaining that only some girls cried and she didn't - already dividing the world into us and them",
                "Us is the most fundamental social category in the brain's organizing system: in one experiment, participants liked nonsense syllables such as xeh and yof more when they were linked with in-group words like us, we, or ours - and none guessed why",
                "In Tajfel's classic experiment, boys told they were overestimators or underestimators of dots assigned more points to boys they thought were like them, and emerging from their rooms they were cheered by their kind and booed by the others",
                "Ethnocentrism - believing your own culture, nation, or religion is superior - aids survival by strengthening bonds to primary social groups, and when we are angry, anxious, or threatened our blind spots are automatically activated",
                "The path between attitudes and action runs in both directions: Campanis, lacking the will to push the Dodgers to hire a black manager, justified his failure by telling himself blacks couldn't do the job anyway",
                "When we have enslaved, deprived, or denied another group, we invoke stereotypes to justify our actions and avoid feeling guilty or unethical about how we treat them",
                "Allport's Mr. X, confronted with evidence that Jews give generously to charity, replied that they were trying to buy favor, and told that few Jews are bankers, replied that they only run night clubs - the hallmark of prejudice is imperviousness to reason and counterexample",
                "Holmes said, 'Trying to educate a bigot is like shining light into the pupil of an eye - it constricts,' and most people wave away disconfirming evidence as 'exceptions that prove the rule'",
                "Elliot's Minneapolis neighbor said, 'You're Jewish? But you're so much nicer than I expected' - by admitting he didn't fit her stereotype she could feel open-minded while keeping her prejudice toward the whole category",
                "In Sherman's experiments, highly prejudiced students paid more attention than others to stereotype-inconsistent information - they needed to figure out how to explain it away, as antigay students said Robert watched football only because his cousin Fred was visiting",
                "Stormfront members consoled would-be members whose DNA revealed non-European ancestry by claiming the tests' statistics were inaccurate or that Jewish-owned testing companies had a malevolent agenda - and one woman was told that Persians 'are Aryans'",
            ],
        ),
        "boss": (
            "Boss Battle: The St. Andrews Slippery Slope",
            "Play the politician offered the first free lunch by a lobbyist and decide whether to accept it, then face each escalating offer - the local golf course, the trip to St. Andrews - while your reputation meter drains. Then take the witness stand as the parent of a three-year-old accused of molesting her, or as the supervisor who must hire a black manager, and see where blind spots override the evidence.",
            "A fairway stretches toward a distant Scottish castle: each accepted inducement walks the figure one hole closer while a chyron reads 'Who would jeopardize a career for a trip to Scotland?' and a locker-room door labeled HIRING ROOM waits at the clubhouse.",
            [
                "New York Times editorial writer Dorothy Samuels asked how Tom DeLay could risk his career for a lobbyist-bestowed freebie like a trip to St. Andrews golf course from the corrupt Jack Abramoff",
                "Dissonance theory's answer is one step at a time: politicians accept lunch with a lobbyist because that's how politics works, and justify it as efficient information-gathering",
                "Once you accept the first small inducement and justify it, you have started your slide down the pyramid: lunch leads to the local golf course, which leads to St. Andrews",
                "No one would jeopardize a career and reputation for a trip to Scotland if that were the first offer, but many would if it had been preceded by several smaller ones - pride, followed by self-justification, paves the road to Scotland",
                "Their professional pride makes judges, scientists, and physicians see themselves as above financial or personal interests, which makes them even more vulnerable to being hooked",
                "When Jonas Salk was asked in 1954 whether he would patent the polio vaccine, he replied, 'Could you patent the sun?'",
                "The 1980 Supreme Court ruling that patents could be issued on genetically modified bacteria opened the gold rush of scientists' commercial ventures and shifted the ethos from science for the public interest to science for profits",
                "Andrew Wakefield's 1998 Lancet claim linking the MMR vaccine to autism was retracted by ten of the thirteen coauthors, who revealed he had been paid more than eight hundred thousand dollars by lawyers for parents of autistic children and had failed to disclose the conflict",
                "There is no causal relationship between autism and thimerosal, the supposed culprit preservative, which was removed from vaccines in 2001 with no attendant decrease in autism rates",
                "Vaccination programs have prevented more than a hundred million cases of serious contagious diseases since 1924 and saved between three and four million lives, yet 2019 saw the greatest number of measles cases in twenty-five years",
                "Nyhan found that parents with negative feelings toward vaccines who received reassuring scientific information became less likely to vaccinate - the backfire effect of self-justification at the bottom of the pyramid",
                "Abraham Lincoln was one of the rare presidents who understood the importance of surrounding himself with people willing to disagree with him, creating a 'team of rivals' cabinet of four political opponents who disagreed furiously on how to preserve the Union",
            ],
        ),
    },
    {
        "num": 3,
        "title": "Chapter 3: Memory, the Self-Justifying Historian",
        "pages": "72-96",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Reconstructed-Memory Scanner",
            "Scan twelve memories - the Brokaw-Vidal interview, Carol's copy of The Wonderful O, a fifth birthday party - and flag the confabulations, the source confusions, and the self-enhancing spins. For each, identify the current feeling or belief the memory error serves before the scanner rules it RECONSTRUCTED or SOUND.",
            "A memory theater where each recollection plays as flickering film frames with visible splices; a narrator's hand inserts borrowed frames - a family photo, a TV scene, a teacher's voice - while a certainty meter reads 100 percent.",
            [
                "Tom Brokaw came to remember the Gore Vidal interview as one in which he wanted to talk politics and Vidal wanted to discuss bisexuality - a total reversal of what happened, made unconsciously to make himself look good",
                "When two people produce entirely different memories of the same event, observers usually assume one is lying, but most of us are neither telling the whole truth nor intentionally deceiving - we aren't lying, we are self-justifying",
                "Memory becomes our personal, live-in, self-justifying historian: Anthony Greenwald described the self as ruled by a 'totalitarian ego' that rewrites history from the standpoint of the victor",
                "Whereas a totalitarian ruler rewrites history to put one over on future generations, the totalitarian ego rewrites history to put one over on itself - if mistakes were made, memory helps us remember that they were made by someone else",
                "Recovering a memory is not like retrieving a file or playing a recording; it is like watching a few unconnected frames of a film and figuring out what the rest of the scene must have been like",
                "Because memory is reconstructive, it is subject to confabulation - confusing an event that happened to someone else with one that happened to you, or believing you remember something that never happened",
                "Source confusion is the 'where did I hear that?' problem - after a while you cannot distinguish your actual memory from information that crept in from family stories, photographs, or TV",
                "Carol Tavris's vivid memory of her father reading her James Thurber's The Wonderful O was wrong: the first edition was published in 1957, one year after her father's death, and someone else must have read it to her",
                "A vivid memory full of emotion and detail can be indisputably wrong, and even being absolutely, positively sure a memory is accurate does not mean that it is",
                "Memory smooths out the wrinkles of dissonance by enabling the confirmation bias: in Jones and Kohler's 1958 experiment on desegregation, each side remembered the plausible arguments for its view and forgot the plausible arguments of the opposition",
                "Metaphors of memory - the wax tablet, the library, the video camera, the computer - are popular, reassuring, and wrong; we do not remember everything that happens to us, and we select only highlights",
                "Nietzsche captured it: 'I have done that,' says my memory. 'I cannot have done that,' says my pride, and remains inexorable. Eventually - memory yields",
            ],
        ),
        "dialogue": (
            "Dialogue: The He Said/She Said Hearing",
            "Hear both sides of a disputed sexual encounter and adjudicate: neither party is necessarily lying, each may be giving 'honest but false testimony.' Play the woman who 'remembers' saying no, the man who 'remembers' verifying consent, and the alcohol that blurred it all, then rule on where memory ends and self-justification begins.",
            "A courthouse with two witness stands facing each other: each speaker's account renders as a film reel on their side of the room, and the frames that exist only in the speaker's mind glow faintly, invisible to the other side, while a glass of amber liquid casts its shadow over the whole chamber.",
            [
                "Deborah Davis calls the indirect communication of sexual wishes a 'dance of ambiguity': most straight men and women, even long-term couples, communicate their wishes through hints, body language, eye contact, and mind reading",
                "The dance of ambiguity protects each party's ego in case the other says no, but it causes problems: the woman really thinks the man should have known she wanted him to stop, and he really thinks she gave consent",
                "Davis, Villalobos, and Leo suggest the primary reason for many he said/she said disagreements is that each partner provides 'honest but false testimony' - both believe they are telling the truth, but one or both may be wrong",
                "Self-justification causes individuals to distort their memories to conform to their views of themselves, so they can 'remember' saying things that they only thought about saying or intended to say",
                "The woman might falsely remember saying things she only thought about saying to stop the situation, because she sees herself as an assertive person who would stand up for herself",
                "The man might falsely remember that he tried to verify the woman's consent, because he sees himself as a decent guy who would never rape a woman - she's misremembering, he's self-justifying",
                "Alcohol significantly impairs the cognitive interpretation of another person's behavior: drunk men are less likely to interpret non-consent messages accurately, and drunk women convey less emphatic signs of refusal",
                "Alcohol severely impairs both partners' memory of what transpired, and as they form their memories, self-justification will freeze them in amber",
                "A person doesn't have to be lying to be wrong - an understanding of memory and self-justification leads to a more nuanced perspective than taking one party's side",
                "When we tell a story, we tend to leave ourselves out: my father did thus-and-such because of who he was, not because of the kind of kid I was - that's the self-justification of memory",
                "Every parent has been an unwilling player in the you-can't-win game: force piano lessons and she will say you wrecked her love of the piano; let her quit and she will say you should have made her continue",
                "Parent blaming is a popular and convenient form of self-justification because it allows people to live less uncomfortably with their regrets - mistakes were made, but only by my parents",
            ],
        ),
        "audit": (
            "Audit: The Life-Narrative File Review",
            "Open your own life narrative and audit it for self-enhancing distortions: the Offer study, Ralph Haber's shoebox of letters, and Conway and Ross's study-skills course are your calibration files. Check your memories of skills, grades, sexual history, voting, charity, and your children's milestones against any records you can find, and log each discrepancy with the self-image it protects.",
            "An archival reading room where old diaries, letters, and grade reports slide out of boxes and face a current self-portrait; every mismatch lights up a comparison screen that reads 'memory vs. record,' while a portrait of the past self slowly changes pose to match the present.",
            [
                "Ralph Haber always remembered leaping for joy when Stanford offered him admission, but twenty-five years later his mother handed him a shoebox of letters showing he had decided to stay at Michigan and that she had pleaded with him to go to Stanford - 'I must have rewritten the entire history of this conflicted choice'",
                "Haber rewrote the history to be consistent with what he actually did, with how he wanted to see himself, and with his need for a loving mother who wanted him nearby - and his professional specialty is autobiographical memory",
                "In Offer's study, seventy-three teenage boys were interviewed in 1962 and re-interviewed at forty-eight: their ability to guess what they had said about themselves in adolescence was no better than chance",
                "Most of the men who remembered themselves as bold, outgoing teenagers had described themselves as shy at age fourteen, and nearly half remembered approving of teenage sex in high school though only 15 percent actually had felt that way",
                "Men and women remember having fewer sexual partners than they actually had, far more sex with those partners, and more frequent condom use",
                "People remember voting in elections they didn't vote in, voting for the winning candidate rather than the one they chose, giving more to charity than they did, and children who walked and talked earlier than they really did",
                "In Conway and Ross's study-skills experiment, the course had no effect on grades, but students who took it misremembered their initial skills as far worse than they had stated and their later grades as higher - 'getting what you want by revising what you had'",
                "The waiting-list students, having expended no effort, felt no dissonance and remembered their abilities and grades accurately",
                "All of us do grow and mature, but generally not as much as we think: each of us feels we have changed profoundly while our friends are 'the same old Harry'",
                "Memories create our stories, but our stories also create our memories: in Tversky and Marsh's experiments, people who wrote a letter of recommendation added false details like 'Rachel is bubbly' and later remembered those invented details as part of the original story",
                "When people recall actions dissonant with their current view of themselves, they visualize the memory from a third-person perspective as if watching a stranger; consonant memories are told as first-person stories",
                "Teenagers in Feeney and Cassidy's study who felt close to their parents remembered a quarrel as less intense than they had rated it, while those feeling ambivalent remembered it as angrier and more bitter",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: False-Memory Case x Mechanism x Motive Grid",
            "Classify the false-memory cases into the grid: Wilkomirski's Fragments, Will Andrews's alien abduction, Clancy's experiencers, and Michael Shermer's alien encounter. For each case, name the generating mechanism - imagination inflation, sleep paralysis, source confusion, suggestion - and the self-justifying need the false memory satisfies.",
            "A diagnostic laboratory where each case's story renders as a timeline: a line labeled REALITY runs straight while the memory line loops and branches, and each detour is stamped with its mechanism - IMAGINATION INFLATION, SUGGESTION, PARALYSIS - and a small caption naming what the memory was built to explain.",
            [
                "Binjamin Wilkomirski's Fragments, the award-winning Holocaust memoir, was a confabulation from start to finish: the author was Bruno Grosjean, a Swiss musician born in 1941 with no Jewish ancestry who had never set foot in a concentration camp",
                "Grosjean's story was drawn from history books, films, and Jerzy Kosinski's novel The Painted Bird, and the New York Times called the book 'stunning' while it won the 1996 National Jewish Book Award",
                "Historian Stefan Maechler concluded Grosjean's motivation was self-persuasion, not calculated self-interest: he spent more than twenty years transforming himself into Wilkomirski, and 'he truly blossomed in his role as concentration-camp victim, for it was in it that he finally found himself'",
                "When the historians at Majdanek laughed at his claim of a children's quarantine, Wilkomirski dismissed them: 'From that moment on, I knew that I could depend more on my memory than on what is said by the so-called historians'",
                "Elizabeth Loftus calls the process by which imagining makes you confident something happened 'imagination inflation' - the more you imagine it, the more details you add, and the more real the false memory becomes",
                "In Mazzoni's experiment, participants given a false 'personalized' dream analysis about being lost or harassed before age three were more likely to believe it, and about half eventually produced detailed memories of the experience",
                "Simply imagining an unlikely scenario - a school nurse taking a skin sample for a national health test that never existed - made people more confident it had happened to them, and the more confident they became, the more sensory details they added",
                "Maryanne Garry finds that as people tell you how an event might have happened, it starts to feel real to them - children are especially vulnerable to this suggestion",
                "Michael Shermer's alien abduction was triggered by riding 83 straight hours and 1,259 miles in the Race Across America: extreme sleep deprivation and exhaustion produced a waking dream whose alien figures came from the 1960s television series The Invaders",
                "Sleep paralysis, which McNally calls 'no more pathological than a hiccup,' has been felt by about 30 percent of the population, but only about 5 percent have the waking hallucinations as well",
                "Susan Clancy found that once people suspected they'd been abducted, 'there was no going back': they began to search for confirmatory evidence, and once the search began, 'the evidence almost always turned up'",
                "The abduction explanation captures the emotional intensity of the experiencers' frightening waking dreams and also lets them avoid responsibility for their mistakes, regrets, and problems - one woman explained her marital coldness and bad sex as the work of the beings",
            ],
        ),
        "boss": (
            "Boss Battle: The Fragments Verdict",
            "Decide whether to publish Fragments: weigh the testimonials of the therapist and the psychologist friend against the letter from the man who knew the truth, and see how easy it is to be convinced. Then take the witness stand in the Ramona malpractice trial - as therapist, as jury, or as Holly - and watch how a verdict that shatters the story is absorbed.",
            "A publisher's office where an unsolicited letter accusing the memoir of falsehood sits under a paperweight while two letters of expert support glow with authority on the desk; behind the window a courtroom fades in where a family is being torn apart by a recovered memory.",
            [
                "While Fragments was in production, the publisher received a letter alleging the story was untrue, but letters from Elitsur Bernstein and the therapist Monika Matta vouched for its authenticity and the book was published on schedule",
                "Bernstein wrote that 'only someone who has experienced such things can write about them in such a way,' and Matta insisted Wilkomirski had 'an extraordinarily precisely functioning memory' - 'The publisher, convinced by the testimonials and reassurances of the experts, brought the book out on schedule'",
                "Therapist techniques that conflate imagination with reality - writing down memories, analyzing dreams, drawing pictures - are staples of psychotherapy, and for someone trying to remember something that never happened they inflate it into a memory",
                "Wilkomirski's writing confirmed his memories: 'My illness showed me that it was time for me to write it all down for myself, just as it was held in my memory, to trace every hint all the way back'",
                "Holly Ramona went into therapy for depression and bulimia and, at the urging of her therapist and a psychiatrist who administered sodium amytal (popularly but mistakenly called 'truth serum'), came to remember being repeatedly raped by her father between the ages of five and sixteen",
                "Holly's father sued both therapists for malpractice for implanting or reinforcing false memories, and the jury agreed, exonerating the father and finding the therapists guilty",
                "Holly could accept the verdict and reconcile her family, or reject it and renew her commitment to recovered-memory therapy - the latter was by far the easier choice because of her need to justify the harm she had caused",
                "Holly Ramona not only vehemently rejected the verdict but went to graduate school to become a psychotherapist",
                "The Courage to Heal tells readers with no memory of abuse that 'when you first remember your abuse... you may feel tremendous relief. Finally there is a reason for your problems. There is someone, and something, to blame'",
                "False memories allow people to forgive themselves and justify their mistakes, but sometimes at a high price: an inability to take responsibility for their lives",
                "Writer Mary Karr had lived by the memory of being abandoned by her father, but when she searched the teenage reminiscences, the facts showed he had kept picking her up and making her breakfast - 'I left him for Mexico and California with a posse of drug dealers, and then for college'",
                "Karr concluded, 'If I'd hung on to my assumptions... I wouldn't have learned what really happened. Which is what I mean when I say God is in the truth'",
            ],
        ),
    },
    {
        "num": 4,
        "title": "Chapter 4: Good Intentions, Bad Science: The Closed Loop of Clinical Judgment",
        "pages": "96-124",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Closed-Loop Detector",
            "Scan twelve therapy vignettes - Grace's panic attack, Holly's bulimia, a client with an erection problem - and detect the closed-loop reasoning in each: the observation that confirms what the therapist already believes. Name the belief, the observation, and what would count as disconfirming evidence that never gets collected.",
            "A consulting room with a one-way mirror: on the couch a client speaks, and over the therapist's head a loop of film plays showing the same belief replaying - 'my client's bulimia must mean she was molested' - with no frame ever showing an alternative explanation.",
            [
                "A woman called Grace went into therapy after a panic attack, but instead of treating the panic her therapist decided her symptoms meant her father had sexually abused her as a child, and when Grace doubted the recovered memories the therapist replied, 'You're sicker than you ever were'",
                "The closed loop of clinical judgment: what therapists see confirms what they believe, and what they believe shapes what they see",
                "Did my client improve? Excellent; what I did was effective. Did my client remain unchanged or get worse? She is resistant to therapy and deeply troubled - 'besides, sometimes the client has to get worse before she can get better'",
                "Do I believe repressed rage causes sexual difficulties? Then my client's erection problem must reflect his repressed rage at his mother or his wife",
                "Do I believe sexual abuse causes eating disorders? Then my client's bulimia must mean she was molested as a child",
                "Psychotherapy is a private interaction between therapist and client, with no one looking over the therapist's shoulder, so therapists who lack training in science and skepticism have no internal corrections to their self-protecting cognitive biases",
                "By its very nature, the privacy of the interaction means mistakes can persist without correction - the chapter is not an indictment of therapy but an examination of the mistakes the closed loop can cause",
                "Clinical psychologists are the closest equivalent to traditionally trained lawyers: most have a PhD and know that cognitive and behavioral methods are the treatments of choice for panic attacks, depression, eating disorders, insomnia, and chronic anger, often as effective as medication",
                "Most psychiatrists learn about medicine and medication but rarely about basic research in psychology, and anthropologist Tanya Luhrmann found psychiatry residents were not expected to read much or question what they were taught",
                "The word psychotherapist is largely unregulated; in many states, anyone can say he or she is a therapist without having any training in anything",
                "Skepticism teaches therapists to be cautious about taking what clients tell them at face value: the skeptical therapist can feel empathy for a woman who says her mother put spiders in her vagina without believing the event literally happened",
                "Science is a form of arrogance control: the scientific method uses procedures designed to show that our predictions and hypotheses might be wrong, forcing us to confront our self-justifications",
            ],
        ),
        "dialogue": (
            "Dialogue: The Van der Kolk Deposition",
            "Conduct the deposition of an expert witness: ask Bessel van der Kolk about the research on clinical judgment, disconfirming evidence, false memories, and hypnosis, and watch his answers reveal a Psychology 101 finding he never learned. Then cross-examine a modern expert who has quietly swapped the word 'repression' for 'dissociation,' and decide whether the new brain language is science or gobbledygook.",
            "A deposition room where a court reporter's stenotype machine prints every answer: 'No.' 'No.' 'I really can't think of any good evidence against that,' while a floating textbook labeled PSYCHOLOGY 101 pages itself open in the corner, and a later scene shows brain images shimmering behind an expert's testimony like a PowerPoint mirage.",
            [
                "Bessel van der Kolk, a prominent psychiatrist who testified frequently for plaintiffs in repressed-memory cases, had never taken a course in experimental psychology and was unaware of any research on the reliability of clinical judgment based on interview information",
                "Asked for the strongest piece of disconfirming evidence against the repression theory, van der Kolk answered, 'I really can't think of any good evidence against that' - and he had not read the literature on false memories created by hypnosis",
                "Van der Kolk trusted 'internal consistency' and 'appropriate affect' - if people tell you something with internal consistency and appropriate affect, you tend to believe the stories are true",
                "John Kihlstrom observed that 'the weakness of the relationship between accuracy and confidence is one of the best-documented phenomena in the 100-year history of eyewitness memory research' - a finding every undergraduate in Psychology 101 would know",
                "Thousands of mentally healthy people believe they were abducted by aliens and report internally consistent stories with all the appropriate feeling, so internal consistency cannot distinguish true from false memories",
                "If you are going to use hypnosis, you should never use it to help a client retrieve memories, because a willing, suggestible client will often make up a memory that is unreliable - hypnosis can aid relaxation, pain management, and quitting smoking",
                "As evidence accumulated, promoters of recovered memory did not admit error; they changed the mechanism from repression to dissociation, allowing them to keep testifying as experts",
                "Christine Courtois, a recovered-memory proponent whose practice was closed in 2016, testified in 2014 that in trauma, 'different parts of the brain either light up or shut down' and memories are 'sequestered in the brain' - language that sounds scientific but is gobbledygook",
                "Weisberg and colleagues showed that laypeople rate the same explanation as more scientific - and more real - when vague references to the brain are thrown in, the 'seductive appeal of neuroscience explanations'",
                "Paul Meehl worried that 'the general scientific commitment not to be fooled and not to fool anyone else' no longer seemed as fundamental a part of psychologists' mental equipment as it was half a century ago",
                "The scientific method consists of procedures designed to show not that our predictions are right, but that they might be wrong",
                "Scientific reasoning matters profoundly when therapists claim expertise and certainty in domains where their unverified clinical opinions can ruin lives",
            ],
        ),
        "audit": (
            "Audit: The Benevolent-Dolphin Case File",
            "Audit the reasoning in six clinical claims by hunting for the missing disconfirming cases: the shipwrecked sailor rescued by a dolphin, the cycle of abuse, the molested-child symptom checklist, the anatomically correct dolls, and the therapists who never found castration anxiety. For each claim, list the confirming observations, then list what you would need to see to test it - and note where the control group is missing.",
            "A maritime chart room where each claim is a storyboard: the dolphin nudges the sailor to shore while a question mark marks the drownings nobody survived to report, and a ledger column labeled INVISIBLE CASES stays stubbornly empty beside the column of confirming examples.",
            [
                "The benevolent-dolphin problem: we hear about shipwrecked sailors nudged safely to shore, but we don't know how many were nudged farther out to sea to drown - so the dolphin is probably neither benevolent nor evil, just playful",
                "Freud said analysts who worked for dozens of years without finding a sign of castration anxiety were performing 'virtuosity in the art of overlooking and mistaking' - if analysts see the complex, Freud is right, and if they fail to see it, they are overlooking it, and Freud is still right",
                "For any theory to be scientific, it must be stated so it can be shown to be false as well as true - a theory with no way to be wrong is a matter of faith, not science",
                "When Saul Rosenzweig suggested experimental testing in 1934, Freud replied that 'the wealth of dependable observations' made his assertions 'independent of experimental verification'",
                "A clinical social worker removed a child from her mother's custody because the mother had been physically abused as a child and 'we all know' that meant she would become an abusive parent - relying only on confirming cases of the cycle of abuse",
                "The disconfirming cases - abused children who do not grow up to become abusive parents - are invisible because, by definition, they don't end up in prison or treatment",
                "Longitudinal studies have found that while childhood abuse increases the chance of becoming an abusive parent, the great majority of abused children - nearly 70 percent - do not repeat their parents' cruelties",
                "When researchers asked how common bed-wetting, sex play, and fearfulness are in the general population, they found non-molested children also masturbate, and temperamentally fearful children also wet the bed and fear the dark",
                "A review of forty-five studies of sexually abused children found that 'no one symptom characterized a majority of sexually abused children' and approximately one third of victims had no symptoms - there is no specific syndrome of sexual abuse",
                "Children who have not been abused do not appreciably differ from abused children in how they play with anatomically detailed dolls, and in a study by Bruck and Ceci a child pounded a stick into the doll's vagina to demonstrate what supposedly happened during a doctor's exam that was videotaped and had never happened",
                "Scientists invented the control group to guard against the bias of direct observation: in a Viagra study, 41 percent of women with sexual problems reported their libido returned, but so did 43 percent of the control group who took a sugar pill",
                "The Viagra study showed conclusively that the organ most responsible for sexual excitement is the brain",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Case x Evidence x Mechanism x Verdict Grid",
            "Fill the grid for the daycare panic cases - McMartin, Wee Care's Kelly Michaels, Bernard Baran - and the Garven and Horner experiments. For each, log the 'evidence,' the suggestive mechanism that produced it, and the verdict the system delivered, then recompute what the verdict should have been under skeptical protocols.",
            "A wall of court exhibits where each case file is pinned with its testimony transcripts; a highlighter traces every leading question in yellow, every 'Was it yes?' in red, and the conviction stamps slide off the files one by one as the highlighting spreads.",
            [
                "In 1983, teachers at the McMartin Preschool in Manhattan Beach were accused of torturing children in satanic rituals in underground chambers, slaughtering pet rabbits, and taking them flying in an airplane; the prosecution could not convince the jury the children had been abused",
                "Bernard 'Bee' Baran, a young gay man in Massachusetts, was the first person wrongfully convicted in the daycare panic; the father who began the accusations had complained he 'didn't want no homo' teaching his child, and Baran spent twenty-one years in jail before a retrial freed him",
                "Kelly Michaels of the Wee Care Nursery School was convicted of 115 counts of sexual abuse and sentenced to forty-seven years, then released after five years when an appeals court ruled the children's testimony had been tainted by how they were interviewed",
                "The panic began when a four-year-old having his temperature taken rectally said, 'That's what my teacher does to me at school'",
                "Pediatric nurse Susan Kelley used Bert and Ernie puppets to 'aid' recall, and when a child said 'Nobody' touched her, Kelley asked, 'Who didn't touch you?' - the Catch-22 question that treats denial as proof",
                "In Garven's experiment using techniques based on McMartin transcripts, children asked only leading questions said 'Yes, it happened' to about 15 percent of false allegations, but children exposed to influence tactics - telling them what other kids said, expressing disappointment, praising allegations - said yes to over 80 percent of false allegations if they were three-year-olds",
                "The Garven results came after interviews lasting only five to ten minutes, while real investigations question children repeatedly over weeks and months, and many inaccurate statements crystallized into stable but false memories",
                "Children under age five often cannot tell the difference between something they were told and something that actually happened to them, and preschoolers who overhear adults exchanging rumors will later believe they experienced the events themselves",
                "The most powerful finding is that adults are highly likely to taint an interview when they go in already convinced a child has been molested - there is only one 'truth' they are prepared to accept, and the child's no means the child is denying or afraid to tell",
                "Twenty-one years after the McMartin trials, Kyle Zirpolo, who had testified against the teachers, publicly apologized: he lied to please his punitive police-officer stepfather, and when he finally told his mother 'Nothing happened! Nothing ever happened to me at that school,' she didn't believe him",
                "In Horner's study, expert clinicians given identical information were split between certainty the abuse had occurred and certainty it had not, and 129 other specialists assessing the same case ranged from forbidding the father ever to see his daughter to giving him full custody - 'for the unskeptical experts, believing is seeing'",
                "New model protocols drafted by the National Institute of Child Health and Human Development instruct interviewers to test the hypothesis of possible abuse rather than assume they know what happened - a change from 'believe the children' to 'understand the children'",
            ],
        ),
        "boss": (
            "Boss Battle: The Repression Ruling",
            "Rule as judge on the scientific status of repressed memory: weigh McNally's review, the Holocaust-survivor evidence, and the 2014 survey of professional beliefs, then sentence the recovered-memory therapists who won't admit error. Finally counsel Linda Ross, the rare therapist who faced the parents and admitted her part, and decide what it takes to break out of the closed loop.",
            "A courtroom transformed into a laboratory timeline: Richard McNally's book opens like a gavel on the bench while a column of statistics - 17.7 percent, 60 percent, 69 percent, 81 percent - rises beside the witness stand, and in the gallery a therapist stands facing a roomful of parents whose faces are maps of loss.",
            [
                "Richard McNally concluded in Remembering Trauma that 'the notion that the mind protects itself by repressing or dissociating memories of trauma, rendering them inaccessible to awareness, is a piece of psychiatric folklore devoid of convincing empirical support'",
                "Overwhelmingly, the evidence shows the opposite: the problem for most people who have suffered trauma is not that they forget it but that they cannot forget it - the memories keep intruding",
                "McNally: 'if the abuse was traumatic at the time it occurred, it is unlikely to be forgotten. If it was forgotten, then it was unlikely to have been traumatic'",
                "As far as anyone knows, no Holocaust survivors have forgotten or repressed what happened to them; Camp Erika survivors recalled what they endured with remarkable accuracy when their recollections were compared with their original depositions",
                "One team of recovered-memory advocates cited the Camp Erika study as evidence that 'amnesia for Nazi Holocaust camp experiences has also been reported' - but some survivors had simply forgotten a few details, which is normal forgetting, not repression",
                "McNally calls recovered-memory therapy 'the worst catastrophe to befall the mental-health field since the lobotomy era'",
                "Sybil, the 1973 book about a woman with sixteen personalities, sold more than five million copies, and forty million Americans watched the 1976 television special; in 1980 the American Psychiatric Association made multiple personality disorder a legitimate diagnosis",
                "Journalist Debbie Nathan's 2011 biography showed that Sybil's psychiatrist Cornelia Wilbur had virtually concocted the story, and Sybil generated her personalities in response to Wilbur's pressures - by the mid-1990s there were, by various estimates, more than forty thousand people with 'alters'",
                "A 2014 study found only 17.7 percent of members of the Society for a Science of Clinical Psychology believed traumatic memories are often repressed, versus 60 percent of general psychotherapists, 69 percent of psychoanalysts, and 81 percent of neurolinguistic programming therapists and hypnotherapists",
                "John Briere admitted the large number of recovered-memory cases may have been caused by 'overenthusiastic' therapists who tried to 'liposuction memories out of their brains' - mistakes were made, by them, but he added that only a few therapists were involved",
                "Colin Ross, who rose to fame claiming repressed memories cause multiple personality disorder, concluded that 'false memories are biologically normal and, therefore, not necessarily the therapist's fault' - if a client comes up with a mistaken memory, it's the client's fault",
                "Linda Ross, shaken out of the closed loop by meeting accused parents in person, said, 'I had been so supportive of women and their repressed memories, but I had never once considered what that experience was like for the parents,' and she told them she was 'certainly aware that I was in need of their forgiveness' - as Alix Spiegel noted, 'The experts, for once, are strangely silent'",
            ],
        ),
    },
]
