# -*- coding: utf-8 -*-
"""Phase 2 chapter data for Mistakes Were Made (But Not by Me) (Tavris & Aronson, 3rd ed), chapters 5-9.
Each chapter: num, title, pages, domain, and 5 slots (scrub/dialogue/audit/matrix/boss),
each slot a 4-tuple (topic, player_mission, visual_frame_description, key_concepts[10-12]).
"""

D = "Self-Justification | Cognitive Dissonance"

CHAPTERS = [
    {
        "num": 5,
        "title": "Chapter 5: Law and Disorder",
        "pages": "124-152",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Tunnel Vision Case Sweep",
            "Sweep the case files of a DNA-era wrongful conviction and scrub every stage for tunnel-vision cues: coached eyewitnesses, jailhouse informants trading testimony for leniency, and confessions wrung out by marathon interrogations. Name each cue, say whose self-justification produced it, and rule on whether the case survives a fresh review.",
            "A courthouse evidence wall where every folder ignites red as its tunnel-vision cue is exposed while a shadowy detective's certainty meter refuses to budge a single degree.",
            [
                "Thomas Lee Goldstein spent twenty-four years in prison for a 1980 murder he did not commit, convicted largely on the testimony of a jailhouse informant with thirty-five arrests and three felony convictions",
                "The informant Edward Fink had already testified against ten different men, claiming each had confessed to him while sharing a jail cell, and a prison counselor called him a con man who tends to handle the facts as if they were elastic",
                "The Central Park Five teenagers, ages fourteen to sixteen, confessed after fourteen to thirty hours of interrogation even though no physical evidence linked them to the crime",
                "Matias Reyes, in prison for three rape-robberies and a rape-murder, admitted that he alone had committed the attack, and his DNA matched the semen found on the victim",
                "Linda Fairstein told a reporter in 2004 that she was certain the original convictions were correct and that the five had been freed only because it was politically expedient",
                "In 1932 Edwin Borchard published Convicting the Innocent, and one prosecutor told him that innocent men are never convicted because it is a physical impossibility",
                "The Innocence Project, founded by Barry Scheck and Peter J. Neufeld, recorded 365 prisoners cleared by DNA testing by 2019",
                "Estimates of the rate of false convictions in the United States range from half of 1 percent at the low end to 2 to 3 percent at the high end",
                "The National Registry of Exonerations had recorded nearly twenty-five hundred exonerations by 2019, more than four times the number of innocent people freed by DNA testing",
                "The Center for Prosecutor Integrity estimated 16,196 cases of prosecutorial misconduct since 1970, with fewer than 2 percent resulting in any punishment for the offending prosecutor",
                "Rob Warden described how detectives develop a theory of the crime that produces tunnel vision, concluding that they could not have been wrong because they are good guys",
                "Richard Ofshe compared convicting the wrong person to a physician amputating the wrong arm",
            ],
        ),
        "dialogue": (
            "Dialogue: The Interrogation Room Role Swap",
            "Take both seats in a marathon interrogation: run the Reid Technique as the detective, then suffer it as the innocent suspect who must decide whether to demand a lawyer, hold the story, or break. After each round, compare what each of you believes about the confession and why.",
            "A bare interrogation room split by a two-way mirror, the detective's script scrolling on one side while the suspect's heartbeat trace spikes on the other as hour twelve ticks over.",
            [
                "Police interrogators are trained to get a confession even if that means lying to the suspect, using what one detective proudly called trickery and deceit, which is entirely legal",
                "The Reid manual states that an interrogation is conducted only when the investigator is reasonably certain of the suspect's guilt",
                "About 13 to 15 percent of the National Registry's exonerated prisoners had confessed to crimes they had not committed",
                "In Kassin's mock-theft experiment, the deadliest combination paired an interrogator convinced of the suspect's guilt with a suspect who was actually innocent",
                "The more the innocent suspect denied guilt, the more certain the interrogator became that he was lying, and the more he upped the pressure",
                "Joe Buckley, president of the Reid School, answered a question about innocent people confessing with: No, because we don't interrogate innocent people",
                "Kassin and Fong's Reid-trained students and forty-four professional detectives did no better than chance at detecting lies, yet believed their accuracy was close to 100 percent",
                "In Drizin and Leo's examination of 125 false-confession exonerations, more than half of the confessors were not mentally ill, mentally deficient, or juveniles",
                "More than 80 percent of the false confessors had been grilled for more than six hours straight, half for more than twelve hours, some almost nonstop for two days",
                "Interrogators resolve the suspect's dissonance by offering explanations such as you blanked it out, as the Escondido detectives offered Michael Crowe a good Michael and a bad Michael",
                "The Reid Technique is a closed loop: denials, nervousness, and averted eyes are all read as signs of guilt, and the manual tells interrogators to deny suspects the eye contact they treat as evidence of innocence",
                "As of 2019 only twenty-six states plus the District of Columbia required police to electronically record interrogations in some or all felony crimes",
            ],
        ),
        "audit": (
            "Audit: The Wrongful Conviction Autopsy",
            "Autopsy a post-DNA exoneration file stage by stage - suspect selection, interrogation, prosecution, appeal - and grade each decision against what an unbiased reviewer would have done. Log every self-justification you find and draft the corrective procedure that would have caught it.",
            "A four-tier courthouse rendered as a giant checklist pyramid, each level stamped PASS or FAIL in glowing ink while an innocent man's silhouette walks the halls below.",
            [
                "Mock jurors in a reenacted murder trial immediately constructed a story and then accepted only the evidence that supported it; early jumpers were the most confident and the most likely to vote for an extreme verdict",
                "Once a detective decides he has found the killer, confirmation bias sees to it that the prime suspect becomes the only suspect",
                "The LAPD Rampart Division produced dozens of officers charged with false arrests, perjured testimony, and framing, and nearly one hundred convictions were overturned",
                "The 1992 Mollen Commission concluded that police falsification of evidence was so common in certain precincts that it spawned its own word: testilying",
                "Andrew McClurg observed that officers who must lie in their official duties learn to smother their dissonance under a protective mattress of self-justification",
                "About three-fourths of all DNA exonerations involve cases that rested on mistaken identification by eyewitnesses",
                "Prosecutors use DNA to confirm a suspect's guilt early in an investigation but dismiss DNA results as irrelevant once a defendant has been indicted and convicted",
                "Peter Neufeld documents post-conviction reinterpretations such as the unindicted co-ejaculator theory that preserve the original verdict",
                "In the Stephanie Crowe case, the detectives ruled out the vagrant Richard Tuite until her blood was found on his sweatshirt, and Tuite was convicted in May 2004",
                "Vic Caloca, who reopened the Crowe case, was not part of the original team, so the evidence implicating Tuite was simply evidence to him, not dissonance",
                "The PEACE model used throughout the UK does not presume the suspect's guilt, forbids bluffing and lying, and treats the interview as a search for information",
                "Texas passed a junk-science statute permitting habeas corpus writs based on new scientific evidence that the conviction evidence was false, misleading, or inaccurately applied",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: The Evidence Sorting Grid",
            "Drop each piece of evidence from a reopened case into the grid of reliable versus junk: DNA, recorded interrogations, coached lineups, informant deals, and voice stress tests. Weight each cell by probative value and rule which evidence belongs in the trial and which belongs in the pseudoscience bin.",
            "A five-by-five evidence grid floating over a courtroom, cells flashing green and red as informant deals and voice stress readings are demoted to the junk column with a judge's gavel.",
            [
                "The Escondido detectives used their voice stress analyzer on Michael Crowe but not on Richard Tuite, reasoning that the test might not be valid on a suspect with mental illness, in other words only on suspects they already believed were guilty",
                "The computerized voice stress analyzer is a pseudoscientific technique that no one has scientifically demonstrated to be valid",
                "Reid Technique promoters claim 80 to 85 percent accuracy in detecting lies, a claim with no scientific support",
                "Training in the Reid Technique does not increase accuracy; it increases people's confidence in their accuracy",
                "Philadelphia district attorney Bruce Castor Jr. rejected a DNA exoneration, saying he had no scientific basis and knew because he trusted his detective and his tape-recorded confession",
                "Texas prosecutor Michael McDougal argued that DNA excluding Roy Criner meant only that the sperm found in the victim was not his",
                "Chief Judge Sharon Keller ruled that DNA excluding a convicted rapist was not determinative because he might have worn a condom",
                "In Billy Wayne Cope's case, DNA identified the rapist as career criminal James Sanders, yet the prosecutor insisted the only logical explanation was that Cope and Sanders acted together, and Cope died in prison maintaining his innocence",
                "The body language the military investigator described in Kassin's case - nervousness, roaming eyes, crying - was, said Kassin, a person under stress, not proof of guilt",
                "Nervousness, fidgeting, avoiding eye contact, and slouching may be signs of nervousness, adolescence, cultural norms, deference to authority, or anxiety about being falsely accused",
                "The Reid manual instructs interrogators to deny suspects eye contact, the very behavior they regard as evidence of innocence",
                "By the logic of the Reid system, the only error a detective can make is failing to get a confession",
            ],
        ),
        "boss": (
            "Boss Battle: The Certain Prosecutor's Showdown",
            "Face the final boss: a district attorney who refuses to reopen a case despite DNA that exonerates your client. Counter every self-justification he throws - finality, the victim's feelings, the myth that innocents never confess - and force him to either admit error or explain himself to history.",
            "A midnight courtroom where the prosecutor looms as a marble monument over the scale of justice, and each of your exhibits strikes his pedestal like a cannonball of light.",
            [
                "Doubt is not the enemy of justice; overconfidence is",
                "The prosecutor in Goldstein's case said he was very confident they had the right guy within hours of the judge's dismissal, and the DA's office conceded two months later that it had no case",
                "Former prosecutor Bennett Gershman said the system has to create this aura of close to perfection, of certainty that we don't convict innocent people",
                "Joshua Marquis argued that Americans should be more worried about the wrongfully freed than the wrongfully convicted and dismissed documented misconduct as episodic",
                "In California, courts set aside convictions in only about 20 percent of 707 confirmed misconduct cases, and only 1 percent of the offending prosecutors were publicly disciplined by the state bar",
                "Mark Godsey, a former prosecutor turned attorney for the wrongfully convicted, wrote that he blew off a snitch's revelation about a fabricated confession because of cognitive dissonance",
                "Thomas Vanes, a prosecutor for thirteen years, helped track down the rape kit for a retest convinced it would vindicate him, then wrote that the man was right and he was wrong",
                "Many states provide no compensation, no official apology, and often no expungement of the record for people who have been exonerated",
                "The harshness toward exonerated victims is in direct proportion to the system's inflexibility about admitting error",
                "A California judge dismissed Goldstein's case in furtherance of justice, citing its cancerous nature and reliance on a professional informer who had perjured himself",
                "Former prosecutor Jack O'Malley kept asking of an exoneration how it could be, and, said Rob Warden, he really didn't get it",
                "Self-justification not only puts innocent people in prison but sees to it that they stay there",
            ],
        ),
    },
    {
        "num": 6,
        "title": "Chapter 6: Love's Assassin: Self-Justification in Marriage",
        "pages": "152-172",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Blame Decoder",
            "Listen to both partners' accounts of the same blowup and scrub each one for self-justification cues: trait labels such as passive and crazy, selective memories, and that's-the-way-I-am declarations. Name the cue, identify the self-concept it protects, and judge whether the couple can still find common ground.",
            "A living room split into his side and her side replaying the same Friday night, caption tags popping in opposing colors over the words tolerant, stubborn, insensitive, and crazy.",
            [
                "Frank justifies his unwillingness to discuss painful topics in the name of his tolerance and his ability to just let things ride",
                "Debra thinks her emotional expressiveness just shows she is human, the same trait Frank calls emotional immaturity",
                "Debra's implicit theory is that Frank is socially awkward and passive; Frank's is that Debra is insecure and cannot accept herself or him as they are",
                "Once an implicit theory forms, confirmation bias kicks in and partners stop seeing evidence that doesn't fit it",
                "When explaining our own behavior, we credit ourselves for good actions and let the situation excuse the bad ones",
                "Unhappy partners invert the logic: a partner's nice act is a situational fluke, but a thoughtless act is a personality flaw, as in she snapped at me because she's a bitch",
                "June Tangney found that being criticized for who you are rather than for what you did evokes deep shame and helplessness, and shamed spouses tend to strike back in anger",
                "John Gottman found that contempt - criticism laced with sarcasm, name calling, and mockery - is one of the strongest signs that a relationship is in free fall",
                "Anger reflects the hope that a problem can be corrected; when it burns out it leaves the ashes of resentment and contempt, the handmaiden of hopelessness",
                "The two versions of serious marital self-justification are I'm right and you're wrong and even if I'm wrong, too bad, that's the way I am",
                "Misunderstandings, conflicts, personality differences, and even angry quarrels are not the assassins of love; self-justification is",
                "Frank and Debra each understand the other's point of view perfectly, but the need for self-justification prevents them from accepting it as legitimate",
            ],
        ),
        "dialogue": (
            "Dialogue: The Friday Night Replay",
            "Re-script Frank and Debra's drive home from the dinner party twice: once as it actually happened, with each partner spinning self-justifications, and once with each anticipating the other's fears and expressing genuine concern. Run both versions and see which ending produces closeness and which produces the locked guest-room door.",
            "The same car interior on a split screen, one drive filling with accusation captions while the other glows with the words honey, are you feeling okay as warmth meters diverge.",
            [
                "The evening might have ended differently if Frank had expressed admiration for Debra's sociability and admitted feeling down on himself, and if Debra had asked about his low mood instead of pressing the comparison",
                "All couples have differences, even identical twins, and differences are often exactly why couples fell in love",
                "Successful couples have conflicts and get angry just as unhappy couples do, but they manage conflicts by talking, fixing, letting go, or learning to live with the problem",
                "Unhappy couples retreat to their familiar positions, brood, and stop listening, thinking that they know how the other feels but they are not going to change because they are right",
                "The claim that a raised voice is natural because that's the way I am is hollow, because people manage to restrain it with police officers, employers, and strangers",
                "Shaming shifts the purpose of a quarrel from solving a problem to wounding, insulting, and scoring, which produces a refusal to compromise",
                "As a couple's new story takes shape, they become blind to each other's good qualities, the ones that initially caused them to fall in love",
                "Julie Gottman's angry wife, asked how the couple met, answered contemptuously that it was at school, where she mistakenly thought he was smart",
                "John Gottman says that nothing foretells a marriage's future as accurately as how a couple retells its past",
                "Gottman predicted with 100 percent accuracy which seven of fifty-six couples would divorce, three years before they planned to separate",
                "The soon-to-divorce couples recalled marrying because it seemed natural, the next step, while happy couples called the same difficulties rough spots they had survived",
                "When one partner is leaving, the same facts that once justified staying now justify leaving, culminating in the pitiless remark I never loved you",
            ],
        ),
        "audit": (
            "Audit: The Relationship Ratio Ledger",
            "Audit your own relationship's emotional books for a week: count every positive and negative interaction, compute your five-to-one ratio, and flag each entry where you excused yourself but blamed your partner. Balance the ledger by adding empathy entries and see where the tipping point sits.",
            "A kitchen table floating beneath a giant balance scale, hearts weighed against grievances like coins while a ledger auto-tabulates the magic ratio in glowing digits.",
            [
                "The tipping point is when the magic ratio dips below five to one positive to negative interactions",
                "It doesn't matter if a couple is volatile, quarreling eleven times a day, or placid, quarreling once a decade; it is the ratio that matters",
                "Ayala Pines's happily married Ellen resolved a missing birthday present by accepting that her husband would never become the Bill Gates of domestic giving",
                "Donna, an unhappily married woman, read the same missing birthday present as proof that he doesn't value me, he doesn't love me, and kept a hate book of her grievances",
                "Once couples hit this low point, they start revising their memories, encouraging the negative events to bubble to the surface instead of sending them under the bridge",
                "Distortions of past events and complete amnesia confirm the suspicion that each married a complete stranger",
                "As long as couples choose to stay, dissonance reduction supports staying with it's not really that bad; when they decide to leave, the justifications change",
                "Divorce mediators Saposnek and Rose described how polarized characterizations such as he's a weak, violent drunk become reified and immutable over time",
                "Don Saposnek said that in more than four thousand custody mediations he has never once heard a parent say the other parent should get custody",
                "Each partner, having induced the other to behave badly, uses that bad behavior to justify his or her own retaliation",
                "Dissonance theory predicts that those with the greatest ambivalence about divorcing have the greatest urgency to justify the decision to leave",
                "Ambivalence morphs into certainty, guilt into rage; the love story becomes a hate book",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: The Attribution Sorting Grid",
            "Drop each act from a sample marriage - the forgotten birthday, the slammed door, the unplanned flowers - into the grid of situation versus disposition, self versus partner. Grade each placement as generous or self-serving, then flip the viewpoint and watch the whole marriage change shape.",
            "A two-axis grid of situation and disposition hangs over a dinner table, the unplanned flowers landing in the generous quadrant and the cold silence in the blaming quadrant as the grid tilts between two pairs of eyes.",
            [
                "We say we were provoked or had no choice for our hurtful acts, but generous acts are credited to our character: we did them because we are generous and open-hearted",
                "Successful partners forgive each other's missteps as situational - poor guy, he is under a lot of stress - and credit thoughtful acts to the partner's good nature",
                "Unhappy partners treat a partner's niceness as a fluke, like flowers bought only because the other men in the office were buying flowers, and annoyance as a flaw",
                "Frank doesn't say Debra acted crazy out of frustration that he wouldn't talk; he calls her a crazy person, and Debra doesn't say Frank was weary; she says he is passive",
                "Implicit theories affect the very purpose of an argument: if each is a good person who did something wrong but fixable, there is hope of correction and compromise",
                "Negative ways of thinking and blaming usually come first and are unrelated to the couple's frequency of anger or feelings of depression",
                "Happy and unhappy partners think differently about each other's behavior even when responding to identical situations and actions",
                "The shouter who protests that's the way I am rarely grants the same justification to the partner, instead turning it into the insult that's the way you are, you're just like your mother",
                "You're just like your mother means your flaw is genetic and irredeemable, a criticism of who you are, like being criticized for being too short or too freckled",
                "Charlie, who yelled and pounded tables like his father and grandfather, gradually reduced his flare-ups after Maxine told him his anger frightened her",
                "Maxine, who learned that no one in her family ever expressed anger, learned to distinguish legitimate feelings of anger from unacceptable ways of expressing them",
                "Personality, history, genetics, and temperament put limitations on how much anyone can change, but Charlie and Maxine each moved",
            ],
        ),
        "boss": (
            "Boss Battle: The Contempt Colossus",
            "Defeat the final boss of a dying marriage: a giant of accumulated contempt that grows with every blaming word and shrinks with every undefensive listen. Choose the empathy response at each turn - separate the mistake from the person, admit I was wrong, and restore the ratio - before the relationship tips past saving.",
            "A shadow-monster of mockery and name-calling towering over a wedding altar, dissolving with each genuine apology and each moment of listening the player chooses.",
            [
                "Contempt is the final revelation to the partner that I don't value the who that you are, and it predicts divorce because it reflects psychological separation",
                "The couples who grow together are able to listen to each other's criticisms, concerns, and suggestions undefensively",
                "Successful, stable couples put empathy for the partner ahead of defending their own territory",
                "They reduce the dissonance caused by small irritations by overlooking them and the dissonance caused by mistakes and major problems by solving them",
                "Charlie and Maxine, married more than forty years, compromise on dinner - we eat at five to eight - and treat small differences as facts of life not worth sulking about",
                "In good marriages, a confrontation or angry quarrel can bring the couple closer by helping each partner learn something new",
                "Without self-justification we might be left standing emotionally naked in a pool of regrets and losses, but the result teaches us something deeply important about ourselves",
                "Vivian Gornick realized that much of her loneliness was self-inflicted, having more to do with her angry, self-divided personality than with sexism",
                "Gornick wrote that in the name of equality she tormented every man who ever loved her until he left, holding them to accountability in ways that wearied them both",
                "Leonore Tiefer's couple could not discuss the issues that affected them as a pair because discussion might require them to compromise or consider the partner's point of view",
                "Successful couples figure out how to yield, just enough, on the self-justifying excuse that's the kind of person I am",
                "Charlie's first impulse was to justify himself - it's my right, I can't do anything about it - but once he considered how his anger affected Maxine, he realized he could modify his behavior",
            ],
        ),
    },
    {
        "num": 7,
        "title": "Chapter 7: Wounds, Rifts, and Wars",
        "pages": "172-196",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Origin Blame Kit",
            "Trace a family feud or an international standoff backward through both sides' narratives and scrub for the moment blame was assigned: the other-guy-started-it move, the long memory, and the date each side picks as the true beginning. Identify whose self-justification each cue serves and locate the point of no return.",
            "A war-room table where two timelines unroll in opposite directions in different colors, each side's origin moment circled in red while the word self-justification burns in the gap between them.",
            [
                "In a rift no one will admit lying, stealing, or cheating without provocation, so each side claims it is only responding as any reasonable, moral person would",
                "The Terri Schiavo family war had its root in money: the 1993 malpractice settlement, over which each side felt legitimately entitled to decide Terri's life and death",
                "To justify keeping Terri alive at all costs, her parents accused Michael of being a controlling adulterer and possibly a murderer; to justify letting her die, Michael accused them of being opportunistic media manipulators",
                "Who started the final confrontation over Terri's death? Each says the other. What made it intractable? Self-justification",
                "Americans saw the 1979 hostage seizure as unprovoked aggression, while Iranians remembered the 1953 American-supported coup against Mossadegh, the arms, SAVAK, and the admission of the shah",
                "When did the hostage crisis begin? Most Iranians chose answers that justified their anger at the United States, and most Americans chose answers that justified their anger at Iran",
                "The remarkable thing about self-justification is that it lets us shift from victim to perpetrator in the blink of an eye without applying what we learned from one role to the other",
                "Pain felt is always more intense than pain inflicted, even when the amount of pain is identical, and escalation of pain is a natural by-product of neural processing",
                "Baumeister's participants all told both a victim story and a perpetrator story, ruling out explanations that treat victims and perpetrators as different kinds of people",
                "Sweet, kind people are as likely as crabby ones to be victims or perpetrators and to justify themselves accordingly",
                "Perpetrators are motivated to reduce their moral culpability; victims are motivated to maximize their moral blamelessness",
                "Every successful revolution, observed Barbara Tuchman, puts on in time the robes of the tyrant it has deposed",
            ],
        ),
        "dialogue": (
            "Dialogue: The Perpetrator-Victim Divide Session",
            "Sit a perpetrator and a victim of the same old wound across from one another and hear each full narrative, then force each to answer the other's core question: the perpetrator's but it was over and the victim's why did he do that. Decide what it would actually take for the victim to set the burden down.",
            "Two chairs facing each other across a chasm filled with floating memories - a yellowing bridal gown, a sealed envelope, a battlefield map - each belonging to the side that never forgot.",
            [
                "More than two-thirds of the perpetrators claimed external or mitigating circumstances, but victims were disinclined to grant them these forgiving explanations",
                "Nearly half of the perpetrators said they couldn't help what happened; they had acted impulsively, mindlessly",
                "Perpetrators were far more likely than victims to describe the episode as an isolated incident, over and done, with happy endings like today we are good friends",
                "Only one of the sixty-three victim stories described the perpetrator as justified in his behavior, and none thought the actions could not be helped",
                "More than half of the victims said the episode had seriously damaged the relationship, with continuing hostility, loss of trust, and unresolved feelings",
                "Many victims said they were unable to make sense of the perpetrator's intentions even long after the event: why did he do that, what was she thinking",
                "The man whose wife announced divorce after eighteen years learned there were eighteen years of dust balls under the bed; the Iranians brooded for twenty-six years",
                "Victims think of their months of rumination as restraint: I consider that an underreaction",
                "Rage itself can be a form of retribution, as with Dickens's Miss Havisham, who sacrificed her life to being a professional victim in her yellowing bridal gown",
                "How could such a bad thing have happened to me, a good person is perhaps the most painful dissonance-arousing question we confront in our lives",
                "Perpetrators, whether individuals or nations, write histories in which their behavior was justified; victims write accounts in which nothing turned out for the best",
                "That is why history is written by the victors, but it's victims who write the memoirs",
            ],
        ),
        "audit": (
            "Audit: The Escalation Audit",
            "Audit a conflict's escalation curve - the tit-for-tat finger pressure, the eye-for-a-tooth counter, the dehumanizing label - and log the justification each side used at every round. Compute how far down the pyramid each side has slid and mark the earliest point where a mediator could have broken the cycle.",
            "A spiral staircase viewed from above, each step labeled with a retaliation and its justification, the spiral tightening in both directions as the walls close in.",
            [
                "In the neurologists' tit-for-tat experiment, each partner retaliated with considerably greater force than he had felt, believing he was giving what he had gotten",
                "The spiral of retaliation runs they didn't take an eye for an eye, they took an eye for a tooth; we must get even, let's take a leg",
                "Once people commit to an opinion about who started this, they become less able to accept information that is dissonant with their positions",
                "As soon as you describe one side's atrocities, someone protests but what about the other side's atrocities",
                "Retaliation makes original perpetrators minimize their harm and claim the mantle of victim, setting in motion a cycle of oppression and revenge",
                "George Bush's post-9/11 call for a crusade against terrorism angered Muslims, for whom the First Crusade of 1095, the slaughter of Jerusalem, might have occurred last month",
                "Some Jewish historians call the Crusades the first Holocaust, for thousands of Jews were slaughtered as the pilgrims marched through Europe",
                "By the middle of the tenth century half the Christian world had been conquered by Muslim Arab armies, and Saladin had recaptured Jerusalem by the end of the twelfth century",
                "Pope Urban II promised that killing a Muslim was an act of Christian penance that would bypass purgatory and go directly to heaven",
                "Timothy Garton Ash pushed the start of the 2006 Israel-Lebanon war back through 1982, 1979, and 1948 to the virulent European anti-Semitism of the nineteenth and twentieth centuries",
                "Both American and white Southern narratives of the Civil War cast their own side as victims: we defeated the traitor Jefferson Davis versus greedy, crude Northerners destroyed our states' rights",
                "The other guy started it is one of the most eternally popular dissonance reducers, practiced by everyone from toddlers to tyrants, and even Hitler said they started it",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: The Evil Doer's Scorecard",
            "Run each atrocity claim from the records - Abu Ghraib photographs, war-crimes testimony, torture justifications - through a matrix that scores how the perpetrator minimized harm, dehumanized the victim, and claimed righteousness. Mark where each account lands on the scale from ordinary fallibility to committed evil.",
            "A tribunal chamber where photographs and testimony cards are dragged onto a glowing scorecard, each dehumanizing phrase lighting up as a red mark against the perpetrator's own self-image.",
            [
                "Charles Graner and Lynndie England did not believe they were doing evil while laughing over their naked victims; self-justification let them believe the victims deserved it",
                "Amos Oz was wrong that every child knows when it deliberately inflicts pain: we are good people, therefore the other must have deserved it, therefore we are doing good",
                "Slobodan Milosevic insisted at his trial that Serbs had been victims of Muslim propaganda and that he was only responding to the aggression they perpetrated",
                "All seven ruthless dictators interviewed by Riccardo Orizio, including Idi Amin and Baby Doc Duvalier, claimed their tortures and murders were done for the good of their country",
                "Baby Doc Duvalier's poster announced that he should be remembered as the person who irreversibly founded democracy in Haiti",
                "In Davis and Jones's experiment, students who had to report that another student was shallow, untrustworthy, and dull convinced themselves that he deserved the criticism",
                "In Berscheid's shock experiment, the only participants who denigrated their victims were those who believed the victims were helpless and could not retaliate",
                "Milgram found that many subjects who obeyed harshly devalue the victim as a consequence of acting against him",
                "General Westmoreland explained Vietnam's civilian casualties with the claim that life is cheap in the Orient",
                "Dehumanizing the victim virtually guarantees a continuation or even an escalation of cruelty, setting an endless chain of violence and self-justification",
                "John Conroy found almost every military or police official he interviewed justified his practices by saying, in effect, our torture is never as severe and deadly as their torture",
                "We have met the enemy and he is us, said Walt Kelly's Pogo",
            ],
        ),
        "boss": (
            "Boss Battle: The Ticking-Bomb Tribunal",
            "Face the final boss: an official defending a brutal interrogation program with the ticking-time-bomb argument and the claim that we don't torture. Counter each dissonance-reducing move - redefining torture, invoking the greater good, citing impunity - with the documented facts, then decide whether the nation can be reconciled without amnesty or accountability.",
            "A Senate chamber turned battleground where a hooded figure of self-justification whispers they deserved it while photographs of Abu Ghraib and a shattered clock tower loom overhead.",
            [
                "George W. Bush said we do not torture, we use an alternative set of procedures, and Dick Cheney insisted the administration was very careful to stop short of torture",
                "Senator James Inhofe said Abu Ghraib prisoners deserved everything they got because they were murderers and terrorists, though military intelligence officers told the Red Cross that 70 to 90 percent of Iraqi detainees were arrested by mistake",
                "The ticking-time-bomb justification fails because tortured suspects will say anything, and the Senate Intelligence Committee confirmed that no information gained from torture proved useful in capturing or killing any terrorist, including Osama bin Laden",
                "Once torture is justified in one case, it is easier to justify it in others, so methods justified for finding ticking bombs became routine",
                "Condoleezza Rice denied that any torture was used and claimed the interrogations stopped terrorist attacks and saved innocent lives",
                "A December 2014 Pew survey found 51 percent of Americans said the CIA's use of torture was justified, with 76 percent of Republicans and 37 percent of Democrats agreeing",
                "Barack Obama banned enhanced interrogation techniques but said we tortured some folks, looked the other way on his predecessor's policy, and declined to hold anyone accountable",
                "Darius Rejali warned that nothing predicts future behavior as much as past impunity, and impunity rewards self-justification in the nation that exonerates the perpetrators",
                "John McCain called the use of torture shameful and unnecessary and said the question is not about our enemies but about who we were, who we are, and who we aspire to be",
                "Frederik de Klerk revoked the ban on the ANC and freed Nelson Mandela after twenty-seven years, and both men shared the Nobel Peace Prize in 1993",
                "The Truth and Reconciliation Commission, chaired by Desmond Tutu, offered amnesty in exchange for perpetrators' admissions of harm, seeking understanding but not vengeance and reparation but not retaliation",
                "William Broyles returned to Vietnam to meet his former enemies as people, not abstractions, and after the visit his nightmares stopped",
            ],
        ),
    },
    {
        "num": 8,
        "title": "Chapter 8: Letting Go and Owning Up",
        "pages": "196-222",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Weasel-Word Detector",
            "Scan a stack of public apologies and corporate statements and scrub each for the weasel signs: passive voice, formulaic regret, on-my-watch framing, and hand-waving about feedback. Flag which admissions would actually satisfy a listener and which are self-justification in apology's clothing.",
            "A press-conference stage where every spoken apology scrolls past as text, weasel phrases glowing amber until a genuine it-was-all-my-fault admission floods the screen in honest white.",
            [
                "In the bicyclist study with 556 participants, the responsibility-accepting apology - the accident was all my fault - produced the most positive evaluations, forgiveness, and willingness to accept a reasonable settlement",
                "John F. Kennedy was the last American president to tell the country he had made a mistake, saying of the Bay of Pigs that the final responsibility was his and his alone, and his popularity soared",
                "Cass Sunstein found that for many people apologies are for losers, and they can backfire when the listener takes them as evidence of weakness or incompetence",
                "Apologies fail when the statement feels formulaic and obligatory, a sure sign the speaker doesn't really believe the apology is warranted",
                "Apple's non-apology apology over iPhone batteries apologized without saying what the apology was for: the batteries, the communication, or the customers' feelings",
                "Daniel Yankelovich found that beneath the public's cynicism about institutions is a genuine hunger for honesty and integrity",
                "Studies of hospitals found patients are actually less likely to sue when doctors admit and apologize for mistakes and when changes are implemented so it won't happen again",
                "The physician's fear that admitting mistakes would puncture an aura of infallibility is wrong: the infallible image often backfires as arrogance and even heartlessness",
                "Richard Friedman wrote that most patients will forgive their doctor for an error of the head, but rarely for one of the heart",
                "Bob Kardon's Mistakes seminar forced twenty nonprofit leaders to stay with the mistake, and a half hour in, the room filled with the near-hysterical laughter of release",
                "In the traffic-school story, not one student had broken the law until a man said he didn't stop at a stop sign and was entirely wrong and got caught - and the room erupted in cheers",
                "IBM's Tom Watson told the junior executive who lost $10 million that the company had just spent $10 million educating him",
            ],
        ),
        "dialogue": (
            "Dialogue: The Friend's Mistake Negotiation",
            "Mediate the dissonance between loving someone and condemning what they did, as Sarah Silverman did with Louis CK and Margo Jefferson did with Michael Jackson. Hold the two ideas apart - the friend remains a friend, and the mistake remains a mistake - and coach yourself and others to wait for the evidence instead of leaping off the pyramid.",
            "Two glowing statements - I love Louis and Louis did these things - suspended in the air side by side, refusing to merge, while a jury of onlookers learns to hold both at once.",
            [
                "Shimon Peres, asked about Reagan's planned visit to the Bitburg cemetery where Waffen-SS officers were buried, said when a friend makes a mistake, the friend remains a friend, and the mistake remains a mistake",
                "The Peres third course lets people remain committed to their nation, religion, or party while disagreeing with actions they find inappropriate, misguided, or immoral",
                "Sarah Silverman said of Louis CK: I love Louis, but Louis did these things. Both of those statements are true",
                "After Leaving Neverland, one side of Michael Jackson's fans reduced dissonance by denying the allegations and vilifying the accusers, the other by vowing never to listen to his music again",
                "Amanda Petrusich framed the tension: victims should be believed, and the accused are innocent until proved guilty - can these two ideas coexist",
                "Margo Jefferson wrote that we can't erase what we've learned about Jackson; we can only accept it, acknowledge what it stirs in us, and try to turn it into wisdom",
                "When the dissonance is our own, we can articulate the cognitions and keep them separate: I remain a decent, smart person and the mistake remains a mistake",
                "Waiting for the evidence is the harder, more radical course than slotting stories into frameworks like children never lie or all fraternity men are rapists",
                "The McMartin preschool case and the Duke lacrosse case both showed the danger of taking sides before the evidence arrived",
                "We can balance sympathy and skepticism and learn to hold our conclusions lightly enough to let them go if justice demands",
                "The coworker exercise asks us to separate the message from the messenger: how would I feel about it if it came from my ally on this project",
                "Becoming aware that we are in a state of dissonance lets us make sharper, smarter choices instead of letting automatic self-protection resolve our discomfort in our favor",
            ],
        ),
        "audit": (
            "Audit: The Institutional Blame Audit",
            "Audit an organization - a hospital, a police force, a prosecutor's office - for whether its culture rewards or punishes admissions of error. Score its external safeguards - checklists, recordings, review boards, oversight - and identify where power without accountability is letting self-justification smooth the way.",
            "A government building rendered as a transparent diagram, with checklists and camera feeds flowing in green and the 95 percent of unexamined cases pooling in a dark unlit cellar.",
            [
                "Because human beings are not automatically self-correcting, external procedures must be in place to correct the errors they will inevitably make",
                "Prescribed checklists of steps in surgery, emergency-room procedures, and aftercare have reduced normal human error and mortality rates in hospitals worldwide",
                "Mandatory electronic recording of forensic interviews lets independent observers later assess whether bias or coercion crept in",
                "Even cameras on every car, lamppost, and phone will not fully fix the problem because believing is seeing: people watch the same videos of the same events and come away with different views of who was to blame",
                "Viewers saw the chokehold death of Eric Garner, the shooting of Michael Brown, the shooting of Tamir Rice, and the shooting of Philando Castile either as unprovoked brutality or as acceptable police behavior",
                "Prosecutors generally have immunity from civil suits and are subject to almost no judicial review",
                "Fully 95 percent of the cases that police hand to a prosecutor's office never reach a jury, so most prosecutorial decisions occur outside public scrutiny",
                "Power without accountability permits individuals and even entire departments to do anything for a win, with self-justification to smooth the way",
                "When district attorneys actively seek to release an innocent inmate, it is usually because, like Robert Morgenthau, they were not the original prosecutors and have no dissonance to reduce",
                "Independent commissions must have members with no conflicts of interest, no decisions to justify, no cronies to protect, and no dissonance to reduce",
                "Scientific and medical journals are instituting stronger measures to reduce the chances of publishing biased, corrupt, or fraudulent research",
                "The ultimate correction for the tunnel vision that afflicts all of us mortals is more light",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: The Mistake Mindset Grid",
            "Sort the ways a culture can react to error into the grid of learning versus punishment: the Japanese classroom that cheers a boy's forty-five-minute struggle, the American classroom that treats mistakes as proof of stupidity, the praise-for-effort and praise-for-ability classrooms, and the scam victim's sunk-cost spiral. Decide which cell produces growth and which produces fear.",
            "Two classrooms side by side under a giant grid, one filling with cheers as a boy redraws his cubes and the other going silent as a child is praised for being a natural math whiz.",
            [
                "About a fourth of the entire American adult population has been taken in by one scam or another, and old people are hit hardest, losing several times as much money in any given scam as young people",
                "Con artists know that people who think of themselves as smart will justify spending money by spending even more to recoup their sunk costs, protecting self-esteem while guaranteeing further victimization",
                "Anthony Pratkanis found that lecturing a defrauded relative is one of the worst things a family member can do: it makes the victim more defensive and pushes him further into the fraudster's clutches",
                "Before a scam victim will inch back from the precipice, he or she needs to feel respected and supported, with loved ones listening uncritically to the values that influenced the decision",
                "Con artists take advantage of people's best qualities - kindness, politeness, the desire to honor commitments and reciprocate gifts",
                "By fifth grade, the lowest-scoring Japanese classroom was outperforming the highest-scoring American classroom",
                "The Japanese boy kept drawing cubes for forty-five minutes, making repeated mistakes, utterly unself-conscious, and eventually mastered the problem to the cheers of his classmates",
                "James Stigler said our culture exacts a great cost psychologically for making a mistake, whereas in Japan mistakes, error, and confusion are all just a natural part of the learning process",
                "American parents, teachers, and children were far more likely than their Japanese and Chinese counterparts to believe mathematical ability is innate",
                "Edison answered the question about his ten thousand failures with: I successfully discovered ten thousand elements that don't work",
                "Carol Dweck found that children praised for effort performed better and liked learning more, while children praised for natural ability cared more about looking competent",
                "Children praised for their intelligence who then failed lost interest in learning to resolve the dissonance of being smart and yet screwing up",
            ],
        ),
        "boss": (
            "Boss Battle: The Self-Justification Hydra",
            "Face the final boss: the hydra of self-justification that sprouts a new excuse every time you cut one down - what else could I have done, it's the other guy's fault, I was just following orders. Defeat it by staying on the hook, separating the mistake from your identity, and speaking the words the mistake was mine - then watch the whole monster dissolve.",
            "A mythic hydra with each head whispering a familiar excuse rises over a mirror pool; the player's confession of error lands like a sword, and each head crumbles as the mirror shows the speaker's own face.",
            [
                "We must steer between the Scylla of blind self-justification and the Charybdis of merciless self-flagellation, staying on the hook long enough to understand what went wrong",
                "N. Wayne Hale, launch integration manager at NASA, wrote publicly of the Columbia disaster that he was guilty of allowing Columbia to crash, and was later promoted to manager of the space-shuttle program",
                "The mind wants to protect itself from the pain of dissonance with the balm of self-justification, but the soul wants to confess",
                "The ability to reduce dissonance preserves our beliefs, confidence, and self-esteem, but it can also get us into big trouble, from pursuing self-destructive courses to supporting torturers and tyrants on our side",
                "In soldiers, the inability to let go of harms they cannot morally accept shows up as PTSD, and Jonathan Shay calls killing someone you didn't need to kill a scar on the soul",
                "Robert E. Lee said of Pickett's Charge: all this has been my fault; I asked more of my men than should have been asked of them",
                "General Daniel Bolger's mea culpa for Iraq and Afghanistan ended with: as a general, I got it wrong, and I did so in company with my peers",
                "Eisenhower's D-Day failure note originally read the troops have been withdrawn; he crossed it out and wrote and I have withdrawn the troops",
                "Janine, who left her husband of twenty years, learned to look again at her decisions whenever she feels 100 percent sure she is right",
                "Americans are inclined to skip act two, the struggle with our demons, but the road to redemption runs through it, as in Elliot's reading of Death of a Salesman",
                "Elliot warned against using self-compassion as a Band-Aid: confession makes no difference if you don't get what the bad thing was and that you are not going to do it again",
                "Reggie Shaw, who killed two people while texting, transformed into a zealous advocate telling audiences I don't want to be that guy, and Eric Fair, who tortured at Abu Ghraib, says I tortured rather than I am a torturer, separating his behavior from his identity",
            ],
        ),
    },
    {
        "num": 9,
        "title": "Chapter 9: Dissonance, Democracy, and the Demagogue",
        "pages": "222-254",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Demagogue Rhetoric Scanner",
            "Scan a demagogue's speeches and tweets for the classic cues: grandiosity, the unquenchable need for praise, fear-arousing lists, I-alone-can-fix-it claims, the press as enemy of the people, and us-versus-them scapegoating. Name each rhetorical move, say which need of the crowd it feeds, and rate the danger level of the collective slide.",
            "A rally stage where every spoken phrase scrolls past in glowing text, fear cues flaring red and self-praise flaring gold while a crowd meter climbs toward the edge of the pyramid.",
            [
                "Trump and Mussolini share the classic characteristics of a demagogue, starting with grandiosity and an unquenchable need for praise",
                "Trump said in accepting his party's nomination that nobody knows the system better than him, which is why he alone can fix it",
                "Demagogues thrive on the reasoning and self-justifications of those willing to push aside their moral objections in exchange for political advantage",
                "Demagogues need adoring crowds, and they create them by using the timeless method of arousing fear",
                "At his nomination speech Trump offered a litany of fears, including a rising crime rate that is a lie, for nationwide crime has been declining for decades",
                "Robert Dallek argues that Huey Long, Joseph McCarthy, and George Wallace can be seen as predecessors of Trump's ascent to political power, but none attained the presidency",
                "Trump called the free press, the bedrock of a democracy, an enemy of the people, and his supporters wore T-shirts reading NOOSE. TREE. JOURNALIST. SOME ASSEMBLY REQUIRED",
                "When Trump asked how to stop immigrants at a May 2019 rally, a crowd member yelled Shoot them and thousands cheered; two months later a white supremacist murdered twenty people in El Paso",
                "Oxford Dictionaries made post-truth its word of the year in 2016, defining it as circumstances in which objective facts are less influential than appeals to emotion and personal belief",
                "Kellyanne Conway called Sean Spicer's falsehoods alternative facts, and alternative facts persist because they are sticky: each repetition makes a falsehood more familiar and therefore more believable",
                "Zachary Jacobson warned that we should fear not the Big Lie but the profusion of little ones designed to confuse, distract, and flood",
                "The election of a demagogue to the White House has arguably been the greatest internal threat to our democracy since the Civil War",
            ],
        ),
        "dialogue": (
            "Dialogue: The Loyalist's Confession Booth",
            "Sit inside the mind of a loyalist and talk your own dissonance down, using the actual justifications supporters gave: he's not a politician, he's rough around the edges, he has good intentions, the Democrats are worse, he has faults but don't we all. Then switch seats and try the dialogue from the side of the doubter who stepped off the pyramid.",
            "A confessional booth where each rationalization the player chooses lights up in scripture-light or broadcast-light, while on the wall the numbers 90 percent approval and 65 percent unpresidential hover.",
            [
                "As of mid-2019, nearly 90 percent of Republicans approved of Trump's performance, even though 65 percent also said they considered his conduct unpresidential",
                "In the 2016 primaries, the majority of Republican voters preferred other candidates; in the first round only about one-third supported Trump",
                "Trump voters diverged on taxes, immigration, race, and other issues, and many had previously voted for Barack Obama",
                "After the election, supporters minimized their discomfort by focusing on what they liked about him and dismissing the rest, tuning in more regularly to Sean Hannity",
                "A woman at a rally dismissed Trump's faults with: he has faults, but don't we all",
                "A Women for Trump rally attendee said he is not a politician and has a backbone, and what he says is what the rest of us are thinking",
                "One supporter said the daily criticism of Trump makes us want to support him more - the stronger the criticism, the more entrenched the need to ignore it",
                "Political scientist Ashley Jardina found much white anger stems from the misperception that white people are getting a disproportionately low share of the nation's resources",
                "White evangelical Christians made up 26 percent of voters in 2016, and 81 percent of them voted for Trump, remaining steadfast after the impeachment inquiry began",
                "The majority of evangelicals and Republicans who watch Fox News said in a survey that there was nothing Trump could do to lose their approval",
                "Ari Fleischer, who left his ballot blank, became an enthusiastic supporter by saying, essentially, the Democrats are worse",
                "A Republican donor said that when he looks at what Trump has done for Israel, he is not going to take issue with anything he has said or done",
            ],
        ),
        "audit": (
            "Audit: The Slide-Down-Pyramid Log",
            "Audit the trajectory of a public figure who went from calling the leader a race-baiting, xenophobic, religious bigot to embracing him at a rally, and log every self-justification that paved the slide. Chart the steps with Comey's map of descent - silent assent, public praise, complicity - and flag the point where he has eaten your soul.",
            "A pyramid-shaped ledger on a Capitol Hill screen, names sliding downward step by step while each rationalization scrolls in the margin and a soul-meter drains to empty.",
            [
                "Ted Cruz, who said history isn't kind to the man who holds Mussolini's jacket, later bear-hugged Trump at a rally in Texas",
                "Lindsey Graham, who called Trump a race-baiting, xenophobic, religious bigot, later denied that Trump was a racist",
                "All presidents lie: Sorensen wrote most of Profiles in Courage, Nixon said I am not a crook, Clinton said I did not have sex with that woman, and Obama's if you like your health care plan you can keep it was PolitiFact's Lie of the Year",
                "The Washington Post reported Trump passed the ten-thousand-lie mark by April 19, 2019, and the total reached 15,413 by December 17",
                "PolitiFact rated 69 percent of Trump's statements as mostly false or worse and only 17 percent as mostly true",
                "At Helsinki, Trump sided with Vladimir Putin over his own intelligence agencies, then claimed the next day that he had meant to say wouldn't instead of would",
                "Trump feels no dissonance when caught because feeling dissonance requires shame, guilt, empathy, and remorse, and he cuts dissonance off at the pass, never allowing it into his brain",
                "The Brookings Institution reported a senior staff turnover rate of 43 percent within two years, which Stephanie Denning called a signal of rot and decay within any organization",
                "James Comey described the descent: first you sit silently in a silent circle of assent, then you praise the leader publicly, then you are silent as he attacks your values - and then you are lost, he has eaten your soul",
                "Seeing disagreement as disloyalty is a hallmark of demagogues, and observers compared Trump's demand for loyalty to a Mafia mob boss, with flipping almost ought to be outlawed",
                "Trump called the CIA whistleblower's complaint close to a spy's act, saying you know what we used to do in the old days with spies and treason",
                "Michael Cohen said his loyalty to Trump cost him everything: his family's happiness, friendships, his law license, his company, his livelihood, his honor, his reputation, and soon his freedom",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: The Ends-Means Trade",
            "Run the history of a democracy sliding under a demagogue through the matrix of means versus ends: the Vatican's deal with Mussolini, evangelicals' bargain with Trump, Pompeo's Queen Esther reasoning, each look-away-from-the-moral-indiscretion trade. Score each transaction for what was gained and what the means cost the soul of the nation.",
            "A medieval papal court and a modern megachurch reflected in a single two-axis grid, each deal logged as a coin moving from the values column to the power column.",
            [
                "Mussolini wooed Pius XI step by step: cabinet kneeling in prayer, baptized children, crucifixes in courts and classrooms, and mandatory Catholic education in the schools",
                "The 1929 accords made the Catholic religion the only religion of the state, silencing Catholics who hoped the pope opposed the Fascist regime",
                "Pius XI began distinguishing good Fascism, which recognized the Church's rights, from bad Fascism, and even blessed Mussolini's genocidal invasion of Abyssinia as a holy war",
                "Mussolini bragged to the German foreign minister that all it took was doing small favors for the higher clergy, such as tax concessions and free railway tickets",
                "On his deathbed Pius XI planned a speech condemning Hitler, Mussolini, and the prohibition of marriages between Aryans and non-Aryans; he died before delivering it",
                "Pius XI's successor ordered the speech's notes gathered and every copy of the text destroyed, then almost immediately lifted the ban on Catholics joining the Action Française",
                "The rise of any demagogue never happens overnight, and it is never the result of one election; it occurs because of the slow shift in beliefs and values that follows every self-justifying decision citizens make, one step at a time",
                "The ends-justify-the-means justification tramples the norms, rules, customs, and traditions of a democracy, and that legacy endures beyond the policies it justifies",
                "Greg Weiner named the post Trump, ergo propter Trump fallacy: because violations were followed by desired policies, defenders assume the violations produced the policies",
                "Wanda Alger, who had demanded sixteen godly qualities in leaders, decided after two years that a good leader need not be godly, citing Romans 13's leaders who bear the sword",
                "Even evangelicals have a bridge too far: Robert Jeffress said taking the Lord's name in vain is very offensive, and I can take just about everything else, except that",
                "Mike Pompeo justified his sycophancy by saying God raised up Trump as he did Queen Esther, therefore God and Trump must be obeyed",
            ],
        ),
        "boss": (
            "Boss Battle: The Whistleblower's Last Stand",
            "Face the final boss: the full weight of a demagogue's machinery arrayed against you for telling the truth. Choose your cost - your job like Maria Caffrey, your career like Chuck Park, your safety like the CIA whistleblower - and give your testimony anyway, because the bottom of the pyramid is exactly where the nation needs its dissenters.",
            "A Capitol hearing room where a lone witness sits at a table facing a towering wall of faces, each revelation she makes cracking the wall until a single line of light breaks through.",
            [
                "George Will stepped off the pyramid, saying this is not my party, and advised his fellow conservatives to make sure Trump lost",
                "For Max Boot, disillusionment was painful and prolonged, in fact existential, and he wrote that the GOP must be burned to the ground",
                "Jim Mattis resigned after Trump announced the withdrawal of forces from Syria, which would abandon America's Kurdish allies and give Turkey and Russia the plum they wanted",
                "Justin Amash, the first Republican in Congress to call for Trump's impeachment, announced on July 4, 2019, that he was leaving the Republican Party",
                "Peter Wehner concluded that the harm Trump caused outweighed his achievements: he is volatile and emotionally unstable, and he is corrupt from stem to stern",
                "Shane Claiborne was threatened with arrest for trespassing if he preached at Liberty University, where he wanted to protest the Gospel of Trump that doesn't look much like the Gospel of Jesus",
                "Maria Caffrey lost her job at the National Park Service for refusing to delete references to the human causes of the climate crisis, calling the pressure climate science denial",
                "Chuck Park, a Foreign Service officer, resigned because he could no longer justify to his son or to himself his complicity in the actions of the administration",
                "Marie Yovanovitch defied the administration's order not to appear at the impeachment hearings, warning that the State Department is becoming hollowed out from within",
                "The unnamed CIA intelligence officer who filed the whistleblower complaint acted with immense courage, knowing most whistleblowers lose their jobs, families, and security",
                "We have learned that a democracy rests not only on its laws and institutions but also on its norms and values, and on the consensus of its citizenry that those norms and values are worth upholding",
                "Jim Mattis wrote that our democracy is an experiment, and one that can be reversed, and that tribalism must not be allowed to destroy our experiment",
            ],
        ),
    },
]
