# -*- coding: utf-8 -*-
"""Phase 2 chapter data for The Moral Animal (Robert Wright), chapters 7-12.
Each chapter: num, title, pages, domain, and 5 slots (scrub/dialogue/audit/matrix/boss),
each slot a 4-tuple (topic, player_mission, visual_frame_description, key_concepts[10-12]).
"""

D = "History of Science | Natural Theology vs. Evolution"

CHAPTERS = [
    {
        "num": 7,
        "title": "Chapter 7: Families",
        "pages": "163-189",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Altruism Odds Room",
            "Work the ledger for a series of self-sacrificing acts - the ground squirrel's alarm call, the sterile ant, the cow with well-marbled beef - and compute whether each pays off from the gene's point of view. Name the degree of relatedness (r) at play in each scene and decide whether the sacrifice beats the threshold c less than br before you stamp it a genuine product of kin selection.",
            "A dim vault where every act of sacrifice floats as a numbered slip; each slip splits into cost and benefit columns while a genetic abacus slides the r-value beads into place, red-lighting the deals that lose the gene more than they save.",
            [
                "Darwin spent more than a decade wondering how natural selection could produce whole castes of ants that create no descendants - a paradox he called 'insuperable, and actually fatal to my whole theory'",
                "In 1963 the young British biologist William D. Hamilton sketched the theory of kin selection, articulating Darwin's insight in the language of genetics",
                "Hamilton saw selection as taking place at the level of the gene, the only potentially immortal organic entity, and was the first to sound the theme of survival from the gene's point of view",
                "A ground squirrel that gives an alarm call can benefit the gene for the call if the call saves four full siblings, two of which carry the gene, even if the sentry dies",
                "Hamilton's symbol r is the degree of relatedness: 1/2 among full siblings, 1/4 among half-siblings, nieces, nephews, aunts, and uncles, and 1/8 among first cousins",
                "The new math says genes for sacrificial behavior thrive so long as the cost to the altruist is less than the benefit to the recipient times the degree of relatedness (c is less than br)",
                "Because of a bizarre form of reproduction, sister ants share 3/4 of their genes by common descent rather than 1/2, justifying altruism of extraordinary magnitude among them",
                "Haldane noted in 1955 that a gene for jumping in a river to save a drowning child, taking a one-in-ten chance of dying, could flourish if the child were your offspring, sibling, or even first cousin",
                "People tend to have the warmest feelings for the people who share the largest fraction of their genes; feelings are proxies for calculation, so Paleolithic people needed no math whizzes",
                "Kin recognition works through cues such as watching a mother feed and care for a child, observing her social affiliations, and, since the advent of language, her explicit instruction in who is who",
                "Hamilton's 1964 paper 'The Genetical Evolution of Social Behaviour' went underappreciated for years but became one of the most widely cited works in the history of Darwinian thought",
                "Because sterile cells in the human body share an r of 1 with the sex cells, the body behaves like a tight-knit community in which altruism is ultimate",
            ],
        ),
        "dialogue": (
            "Dialogue: The Weaning Standoff",
            "Play the caribou mother and her calf locked in the contentious mammalian ritual of weaning, each side bargaining over how long the milk lasts. Argue the calf's case - it is completely related to itself but only partially related to its future siblings - then switch sides and defend the mother, who values the two offspring equally and reaches the point of refusal sooner.",
            "A frozen tundra clearing at dusk: the calf shrieks and strikes for milk while the mother stands immobile, her udder framed by a slowly dividing genetic-interest meter that ticks between them like a metronome.",
            [
                "Robert Trivers, the biologist who first emphasized the partial emptiness of the cup of common genetic interest, dissected parent-offspring conflict in a 1974 paper of that name",
                "A child should in theory see itself as twice as valuable as its sibling, while the parent, being equally related to the two, values them equally",
                "A caribou calf will continue to suckle long after milk has ceased to be essential, even though this prevents the mother from conceiving another calf that will share some of its genes",
                "The theory of inclusive fitness implies that conflict over weaning will be a regular part of mammalian life - veteran baboon watchers know to listen each morning for mother-offspring strife",
                "Children use any tools at their disposal in the battle over resources, including dishonesty: young Willy Darwin told Annie, 'Yours is larger than mine Annie,' trying to prevent her wanting his apple",
                "Two-year-old Doddy Darwin gave his sister his last bit of gingerbread and then cried in a vain-glorious tone 'Oh kind Doddy, kind Doddy' - an example of conspicuous nonconsumption",
                "Three-year-old Leonard Darwin embellished his needs, telling his father after scraping his wrist, 'The skin's come off - and its lost - and the bleed's coming out'",
                "At peak intensity the child's emphasis on parental cruelty and injustice is known as a temper tantrum, part of young life in chimpanzees, baboons, and other primates as well as humans",
                "Parents are ripe for exploitation because attention to a child's crying and complaining serves the parent's genes, since cries may signal real needs of a vehicle containing copies of them",
                "Natural selection should equip parents with antimanipulation devices such as suspicion of childhood whining, then children with counterdiscernment technology - an arms race that goes on forever",
                "Trivers stressed that parents are themselves dishonestly manipulative, wanting to extract more kin-directed altruism and love from the child than is in the child's genetic interest",
                "Trivers wrote that 'The personality and conscience of the child is formed in an arena of conflict'",
            ],
        ),
        "audit": (
            "Audit: The Family Investment Ledger",
            "Audit a string of family budgets - rich and poor, high- and low-status - and log how each household doles out its attention, nursing, and inheritance between sons and daughters. For each entry record the Trivers-Willard prediction the family either obeys or flouts, then close the ledger by classifying every observed favoritism as a sound Darwinian bet or a cultural artifact.",
            "A Victorian counting room stacked with ledgers bound in leather; each open book shows a family tree whose children glow brighter in proportion to parental investment while a gold-standard scale weighs sons against daughters.",
            [
                "Robert Trivers and the mathematician Dan E. Willard argued in 1973 that in any polygynous species, mothers in poor physical condition might profit genetically from treating daughters as more valuable assets than sons",
                "Malnourished males may be shut out of reproductive competition altogether, whereas a fertile female in almost any condition can usually attract a sex partner",
                "Florida pack rat mothers, if fed poorly, will force sons off the teat, even letting them starve, while daughters nurse freely",
                "Mildred Dickemann, studying nineteenth-century India and China and medieval Europe, concluded that female infanticide has been most intensively practiced among the upper classes",
                "Wealthy families in many cultures, including Darwin's, pass their largest assets down to their sons rather than their daughters",
                "The anthropologists Laura Betzig and Paul Turke, working in Micronesia, found that high-status parents spend more time with sons and low-status parents with daughters",
                "In a North American study, around 60 percent of daughters born to affluent women were breast-fed and nearly 90 percent of sons; low-income women had another child sooner after a son than after a daughter",
                "Natural selection tends to work underground, shaping human feelings rather than making humans conscious of its logic",
                "Hamilton noted in his 1964 paper that 'the behaviour of a post-reproductive animal may be expected to be entirely altruistic'",
                "Since only women spend much of their lives post-reproductive, older women shower attention on kin far more than older men - the single aunt who devotes her life to relatives is far more common than the single uncle",
                "When Darwin's sister Marianne died, his middle-aged unmarried sister Susan adopted her children while brother Erasmus did not",
                "The Smothers Brothers comedy team made famous the complaint 'Mom always liked you best,' with the dull-witted Tommy addressing his sharper, more dynamic brother Dick",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Kin versus Nonkin Altruism",
            "Sort a deck of altruistic incidents - the alarm call, the weaning dispute, the widow's care for her grandchildren, the stranger's rescue, the queen bee's feast - into the three governing regimes of kin selection, parent-offspring conflict, and pure self-interest. For each card, name the r between the parties, state who profits, and flag any scene where the cup of common genetic interest is half-empty rather than half-full.",
            "A sorting table under a single cold lamp: cards depicting animals and families slide into labeled troughs as an r-meter overhead lights up with fractions, while a few defiant cards refuse every slot.",
            [
                "Even pure sibling love isn't total love: Haldane is said to have remarked that he would give his life for 'two brothers or eight cousins'",
                "To define the degree of commitment to any relative is to define the degree of indifference and, potentially, antagonism - the cup of common interest between siblings is half-empty as well as half-full",
                "It is hard to teach children to share equally with brothers and sisters, for equal sharing runs against their genetic interest",
                "When Annie hurt herself with no adults in view, nearly five-year-old Willy Darwin first attempted to comfort her nicely, then his fortitude gave way and he began to cry also",
                "Darwin never explained sibling love in terms of kin or 'family' selection; he seems never to have seen the connection between insect self-sacrifice and mammalian affection",
                "Kin selection ensures that the conscience looks out for siblings, generating guilt after any major neglect of them - and parents play on this guilt-center",
                "Trivers saw the prevailing view of child-rearing as 'enculturation' as naive, since virtues like honesty and generosity affect the altruistic and egoistic behavior impinging on the parent's kin",
                "The child is biologically vulnerable to a parent's propaganda campaign because it so often makes Darwinian sense to do what parents say - there is a 50 percent overlap of genetic interests",
                "Parents should, in theory, do what Trivers called 'molding' in the guise of 'teaching,' overemphasizing their role as teachers to minimize resistance in their young",
                "When the r between organisms is 1, as among the asexually reproducing cells of the slime mold, altruism is ultimate: the neighbors' welfare is identical to one's own",
                "The ultimate unit of selection is the gene: those genes conducive to the survival and reproduction of copies of themselves are the genes that win - hence the title of Dawkins's The Selfish Gene",
                "Natural selection doesn't care whether we are made happy or sad in the process of gene transmission; it will countenance any suffering that serves its purpose",
            ],
        ),
        "boss": (
            "Boss Battle: The Sibling Rivalry Gauntlet",
            "Stand trial as the parent of the Darwin household and referee an escalating round of sibling squabbles - the single sandwich, the stolen apple, the scratch that needs more pity - while an unseen judge grades every ruling against the gene's-eye view. Allocate the scarce resource so that both the parent's equal valuation and each child's two-to-one self-favoritism are respected, and survive the tantrum that follows any ruling against a child.",
            "A nursery made of courtroom furniture: two small children on opposite benches glare at a single sandwich on the judge's dais, while above them a giant scale weighs a child's genetic interest against its sibling's and a parent's love against both.",
            [
                "Given two siblings and one sandwich, the question of its allotment should not be expected to be amicably resolved - siblings fiercely compete for parental affection and attention with jealousy so petty it's hard to credit them with love",
                "When a sibling becomes truly needy or seems genuinely endangered, love surfaces - the same child who schemed for the apple rushes to comfort a hurt brother or sister",
                "Trivers argued that a child's genetic interest diverges not only from a sibling's but from a parent's, so parents will try to teach the equal sharing that runs against each child's interest",
                "The arms race between child exploitation and parental countermeasures never ends: whining begets suspicion of whining, which begets more heartfelt whining",
                "One good way to short-circuit parental demands for greater sacrifice is to exaggerate - or selectively highlight - sacrifices already made",
                "Parents' genes benefit from attention to a child's crying, so parents love their children and can be blinded by that love",
                "The idea of a temper tantrum as manipulation won't strike most parents as revolutionary, evidence that parents aren't entirely blind to the ploy",
                "Children's genes should 'want' the child to tap into the uniquely devoted databanks housed in its parents, since no one has a stronger genetic incentive than a parent to fill a child's head with useful facts",
                "One of Darwin's daughters recalled that 'Whatever he said was absolute truth and law to us' - though five-year-old Leonard told Darwin that jumping on the sofa was fine and 'I advise you to go out of the room'",
                "A Darwin relative, the economist Josiah Wedgwood, noted that among wealthier predecessors in his sample the sons received a larger share than daughters, while equal division was much more common in smaller estates",
                "Culture can push our behavior against the grain of Darwinian logic, as when the subservience of women was a social ideal among the lower classes",
                "Reproductive potential changes over the life cycle, and parental devotion should grow until early adolescence, when it peaks, then begin to drop",
            ],
        ),
    },
    {
        "num": 8,
        "title": "Chapter 8: Darwin and the Savages",
        "pages": "189-198",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Savage Stereotype Sweep",
            "Review Darwin's raw Beagle observations of the Fuegians - the screaming Indians, the cannibalism report, the slave-like treatment of old women - and tag each entry as verified fact, travelers' apocrypha, or Victorian projection. Strike the false reports from the record, then recompose Darwin's verdict on primitive humanity using only what the evidence supports.",
            "A ship's cabin papered with observation slips that glow green or red as a truth-meter vets each one; the apocryphal tale of eating old women dissolves into ash while the rest of the wall stays lit.",
            [
                "When the Beagle sailed into Tierra del Fuego, Darwin saw Indians who 'seemed the troubled spirits of another world' - but the story that the Fuegians ate old women when food got scarce turned out to be apocryphal",
                "Darwin reported a Fuegian boy's reply to why they didn't eat their dogs instead: 'Dog catch otter - woman good for nothing - man very hungry'",
                "The savage, Darwin wrote decades later in The Descent of Man, 'delights to torture his enemies, offers up bloody sacrifices, practises infanticide without remorse'",
                "Darwin wrote in his popular account of the voyage: 'I could not have believed how wide was the difference, between savage and civilized man'",
                "Fuegian life did include friendship, signified by mutual generosity and sealed by a ritual of solidarity: the old man patted Darwin's breast, made a chuckling noise, then gave three hard slaps and bared his bosom for the compliment to be returned",
                "Captain FitzRoy had brought four Fuegians to England, and three were being returned freshly educated and civilized - an experiment that failed when one newly civilized Fuegian stole all the possessions of another",
                "Darwin was incessantly struck while living with the Fuegians aboard the Beagle with how similar their minds were to ours",
                "The perception of a fundamental unity among human beings - a human nature - is the first step toward becoming an evolutionary psychologist",
                "Darwin chose to confront a major obstacle to his theory: the moral sentiments, 'the moral sense, which tells us what we ought to do, and ... the conscience which reproves us if we disobey it'",
                "Bronislaw Malinowski noted that the Trobriand Islanders have two words for 'friend' - one meaning 'friend within the barrier' and one 'friend across the barrier'",
            ],
        ),
        "dialogue": (
            "Dialogue: The Beagle Confession",
            "Play the letters Darwin wrote home from the Beagle - the horror to mentor John Henslow, the disgust to sister Caroline - and face the counter-case from the three English-speaking Fuegians returning home aboard the ship. Argue both the Victorian gentleman's verdict of barbarism and the traveler's dawning sense that their minds are like ours, then decide whether the apology for the cannibalism story gets written.",
            "A lamplit corner of the ship's chart room: two inkwells, two chairs, and two ghostly interlocutors - a letter to England on one side, a scarred Fuegian face on the other - while the word 'disgust' is crossed out in a trembling hand.",
            [
                "Darwin wrote to his mentor John Henslow that the Fuegians 'seemed the troubled spirits of another world' with 'their long hair streaming'",
                "Their language, 'according to our notions, scarcely deserves to be called articulate'; their houses 'are like what children make in summer, with boughs of trees'",
                "Darwin found no affection between Fuegian husband and wife 'unless indeed the treatment of a master to a laborious slave can be considered as such'",
                "Darwin wrote to his sister Caroline: 'Was ever any thing so atrocious heard of, to work them like slaves to procure food in the summer & occasionally in winter to eat them'",
                "Aboard the Beagle Darwin antagonized Captain FitzRoy by sarcastically probing his defense of slavery",
                "After living with the Fuegians, Darwin wrote that 'The American aborigines, Negroes and Europeans are as different from each other in mind as any three races that can be named' - yet he was struck by the many little traits showing how similar their minds were to ours",
                "Even the Fuegians, those 'miserable savages,' had been able to make friends with a young white-skinned man who came from across the ocean",
                "Kin selection accounts only for acts of conscience within the family; the question remains why we have friends across the barrier",
                "Human beings can feel sympathy for people across the barrier whom they don't even know - why are there Good Samaritans, and why do most people have trouble walking past a beggar without a twinge of discomfort?",
                "Darwin found an answer to these questions that now seems misguided - but misguided in a very illuminating way, resting on a confusion that swept away only late in the century",
            ],
        ),
        "audit": (
            "Audit: The Moral Code Diversity Inventory",
            "Survey a globe's worth of moral customs - the horror of the Hindoo who breaks caste, the shame of the Mahometan woman who exposes her face, the Thug's conscientious regret - and log each one under the two things Darwin held universal. For every entry, separate the innate basis of moral feeling from the historically contingent contents of the code, and flag which customs even Darwin judged to be in error.",
            "A museum of world customs where each exhibit's plaque splits in two - a steel engraving labeled 'innate social instinct' and a wax tablet labeled 'learned contents' - while a clerk stamps verdicts of error or judgment.",
            [
                "Darwin wrote with perplexity of the 'absurd rules of conduct' reflected in the 'horror felt by a Hindoo who breaks his caste' and the 'shame of a Mahometan woman who exposes her face'",
                "If morality is grounded in human biology, moral codes differ widely - but modern evolutionary psychology does not favor the answer that Arabs, Africans, and Englishmen have different 'morality genes'",
                "Darwin did believe the races had inborn mental differences, some morally relevant - a standard nineteenth-century belief, though some scholars argued the races weren't races at all but species",
                "Darwin asserted that 'the love of approbation and the dread of infamy, as well as the bestowal of praise or blame' are grounded in instinct - adherence to any moral rule has an innate basis",
                    "The violation of some trivial bit of etiquette, when recalled even years after, can bring back a 'burning sense of shame'",
                "Darwin believed different peoples have different rules because, for their own historical reasons, they judge different norms to be in the interest of the community - often in error, yielding behavior in 'complete opposition to the true welfare and happiness of mankind'",
                "Savages seemed to possess 'insufficient powers of reasoning' to discern nonobvious connections between moral laws and public welfare, and lacked, perhaps constitutionally, self-discipline",
                "Fuegians and Englishmen alike possessed the 'social instincts,' central among them sympathy for their fellow man",
                "Darwin recorded that 'an Indian Thug conscientiously regretted that he had not strangled and robbed as many travellers as did his father before him' - a question of the scope of sympathy, not its existence",
                "Darwin saw sympathy in crows that fed their blind compatriots and baboons that heroically saved their youngsters from a pack of dogs, and asked 'Who can say what cows feel, when they surround and stare intently on a dying or dead companion?'",
                "Darwin suggested the word moral itself be reserved for our species, since humans can learn precisely what conduct is expected of them and can recall the painful result of letting social instincts be overridden",
                "Behavior, not thought or emotion, is what natural selection passes judgment on: Darwin wrote that animals' social sensations were developed in order that those which would profit by living in society should be induced to live together",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Family Selection versus Group Selection",
            "Line up the two rival engines Darwin proposed for conscience - selection applied to the family and selection applied to the whole tribe - and judge each explanation against the fate of the altruist's genes. For every moral trait on the table, decide whether it could spread through everyday intratribal competition or whether it needs a convoluted story of warring tribes to get started, and award the credit to kin selection or mark the claim as group selectionism.",
            "A courtroom with two engines drawn in chalk on the floor: a modest family loom on one side, a towering tribal war machine on the other, while a line of altruistic traits waits to be fed into whichever mechanism can honestly explain them.",
            [
                "Darwin's concept of 'family' selection, or kin selection, can explain altruism in mammals and hence conscience - but only for acts of conscience within the family",
                "In The Descent of Man Darwin wrote that 'an advancement in the standard of morality and an increase in the number of well-endowed men will certainly give an immense advantage to one tribe over another' - his central group-selectionist explanation of the moral sense",
                "Darwin himself saw the main snag: 'It is extremely doubtful whether the offspring of the more sympathetic and benevolent parents ... would be reared in greater number than the children of selfish and treacherous parents of the same tribe'",
                "The bravest, most self-sacrificial men would on average perish in larger number than other men, and a noble man 'would often leave no offspring to inherit his noble nature'",
                "Even if a tribe full of selfless people would prevail over a tribe full of selfish people, it is hard to see how a tribe would get full of selfless people in the first place",
                "Everyday prehistoric life would presumably favor the genes of people who hoarded food rather than shared it - an intratribal advantage that would grow when intertribal competition heated up",
                "The problem with group-selectionist theories is that it is hard to imagine group selection spreading a trait that individual selection on its own wouldn't favor",
                "George Williams proposed in Adaptation and Natural Selection an official bias against group selectionism: 'One should postulate adaptation at no higher a level than is necessitated by the facts'",
                "Williams's credo - first look hard for a way genes could be favored in everyday head-to-head competition, resorting to competition between populations only with great caution - became the unofficial credo of the new paradigm",
                "Writing in the mid-sixties just after Hamilton explained altruism among kin, Williams suggested a way evolution could extend altruism beyond the barrier of kinship",
            ],
        ),
        "boss": (
            "Boss Battle: The Tribe of Selfless Warriors",
            "Defend or demolish Darwin's theory that the moral sentiments evolved because tribes full of patriotic, obedient, sympathetic members conquered tribes of selfish ones. Run the simulation of prehistoric life: seed the tribe with sympathetic genes, then watch what everyday competition does to them before any intertribal war can harvest their virtue, and rule on whether group selection can ever resolve a direct conflict between group welfare and individual welfare in favor of the group.",
            "Two shadowy tribes clash across a valley floor while a magnifying lens descends on one village to show the daily ledger inside - hoarders reproducing, sharers dying young, and the tribe's meager selflessness shrinking even as its warriors savor victory.",
            [
                "Yes, Darwin's tribe scenario would be natural selection - if it actually happened; but the more you think about it, the less likely it seems",
                "Even if you magically implanted 'sympathetic' genes in 90 percent of a population, they would steadily lose out to their less ennobling rival genes",
                "All tribes are subject to the same internal logic, so the victors presumably wouldn't be paragons of virtue themselves",
                "Any meager quantity of selflessness a victorious tribe had put to good use should, in theory, be declining even as it savored the fruits of victory",
                "One can dream up scenarios with particular rates of migration and group extinction where group selection might favor individual sacrifice, and a few biologists believe group selection played an important role in human evolution",
                "Unless societies took exceedingly good care of the kin of dead war heroes, the self-sacrificial would keep losing out",
                "Group-selectionist scenarios do tend to be a bit convoluted compared with the gene's-eye view",
                "The recognition that Darwin's analysis of human morality rested on this confusion was swept away only late in the century, clearing the path for modern evolutionary psychology",
                "Darwin's analysis of human morality, up to the point where he made his big mistake, is in some ways exemplary - a paragon of the method of evolutionary psychology even by today's standards",
                "In The Voyage of the Beagle Darwin wrote of an island off Chile: 'It is a pleasant thing to see the aborigines advanced to the same degree of civilization, however low that may be, which their white conquerors have attained'",
            ],
        ),
    },
    {
        "num": 9,
        "title": "Chapter 9: Friends",
        "pages": "198-220",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Non-Zero-Sum Exchange Table",
            "Take the stand as the accountant of friendship and value a chain of trades - chimp meat in a famine, hide-splicing for spear-carving, gossip about who cheated whom - computing the gain to each side of every exchange. Flag each deal as zero-sum or non-zero-sum, name the surplus item that became a rare and precious good, and certify which exchanges could have fueled the evolution of reciprocal altruism.",
            "A bazaar table where goods are valued twice - once for the giver, once for the receiver - and a set of golden scales keeps refusing to balance, tipping always to the side of the hungry; a ledger stamps each deal 'non-zero-sum' in green ink.",
            [
                "Darwin wrote in The Descent of Man that as reasoning powers improved, each man would learn from experience that if he aided his fellow-men he would commonly receive aid in return - but his added claim that habits followed during many generations tend to be inherited is wrong",
                "No life experiences, except exposure to radiation, affect the genes handed down to offspring; habits are passed by instruction or example, not via the genes",
                "George Williams wrote in 1966 that 'an individual who maximizes his friendships and minimizes his antagonisms will have an evolutionary advantage' - and that neither giver nor receiver need be aware of the logic",
                "Animals, including people, often execute evolutionary logic not via conscious calculation but by following feelings designed as logic executers - including compassion and gratitude",
                "In 1971, exactly one hundred years after Darwin's allusion to reciprocal altruism, Robert Trivers published 'The Evolution of Reciprocal Altruism' in The Quarterly Review of Biology",
                "Trivers's abstract claimed that 'friendship, dislike, moralistic aggression, gratitude, sympathy, trust, suspicion, trustworthiness, aspects of guilt, and some forms of dishonesty and hypocrisy can be explained as important adaptations to regulate the altruistic system'",
                "Game theory, developed during the 1920s and thirties, pays for neatness with unrealism: humans aren't calculating machines but are designed by a calculating machine that maximizes inclusive fitness",
                "In a non-zero-sum exchange one player's gain isn't canceled by the other's loss: a chimp gives five ounces of meat worth six points to a hungry fellow, and both can end better off",
                "Division of labor is a common source of non-zero-sumness: one animal's surplus item can be another animal's rare and precious good",
                "Darwin recalled his exchange with the Fuegian Indians - 'both parties laughing, wondering, gaping at each other; we pitying them, for giving us good fish and crabs for rags'",
                "In the ancestral environment the most common commodity of exchange, almost surely, was information - and trading gossip may be one of the main reasons friendship exists",
            ],
        ),
        "dialogue": (
            "Dialogue: The Prisoner's Dilemma Interrogation",
            "Play both cells of the classic prisoner's dilemma - the prosecutor's offer to each man, the one-year lesser charge, the scot-free confession, the ten-year betrayal - and then run the game again and again as an iterated dilemma. Choose your strategy as if you were an animal that can't grasp repayment, and discover why mutual fidelity beats mutual betrayal even though each single decision seems to favor cheating.",
            "Two separate cells face each other across a corridor, each prisoner drawing the same branching tree of years on his wall; through the window a computer screen flickers with round after round of the same choice.",
            [
                "In the prisoner's dilemma, the state lacks evidence to convict the partners of the grave offense but can convict both on a lesser charge, giving each a reason to confess and implicate the other",
                "Weighing options one by one, each prisoner would almost certainly decide to confess - to 'cheat' on his partner - yet mutual cheating yields three years while mutual silence yields one",
                "Because the prisoners can't communicate about their concurrent decisions, each is like a prospectively altruistic animal unsure whether any friendly overture will be matched",
                "An iterated prisoner's dilemma lets each player refer to the other's past behavior, so each may reap in the future what he has sown in the past - just as with reciprocal altruism",
                "The essence of the logic that leads to cooperation in the iterated prisoner's dilemma is non-zero-sumness",
                "Even in a non-zero-sum game, cooperation doesn't necessarily make sense: you gain six points by cheating, accepting generosity and never returning it",
                "Whether non-zero-sumness fuels the evolution of reciprocal altruism depends heavily on the prevailing social environment",
                "Biologists can't rewind the tape and replay evolution, but in the late 1970s Robert Axelrod devised a computer world in which strategies for the iterated prisoner's dilemma competed for survival",
                "After every program had had 200 encounters with every other program, Axelrod added up scores and culled the weak, letting the fittest survive into generation after generation",
                "The winning program, TIT FOR TAT, designed by the Canadian game theorist Anatol Rapoport, cooperated on the first encounter and thereafter did whatever the other program had done last time",
            ],
        ),
        "audit": (
            "Audit: The Friendship Emotion Inventory",
            "Take inventory of the emotional equipment a dim-witted Australopithecus would need to run reciprocal altruism - sympathy for the first overture, gratitude and obligation for repaying, anger and dislike for cheaters, forgiveness for reformed meanies - and log how each feeling found in all human cultures maps onto a step of the TIT FOR TAT strategy. File each emotion under the machine part it works, and note which cultures you'd need to visit to confirm each one is universal.",
            "A museum of the mind where each emotion sits in a labeled glass case wired to a giant TIT FOR TAT flow chart on the wall; gratitude's case hums as a favor returns along the diagram's glowing arrow.",
            [
                "TIT FOR TAT has no human foresight and doesn't understand the value of reciprocation - it just reciprocates, and in that sense is perhaps more like Australopithecus, our small-brained forebears",
                "A sense of gratitude and obligation would produce TIT FOR TAT's reliable return of favors; anger and dislike would cut off largesse to mean australopithecines; forgiveness would make nice those who mended their ways",
                "All of these feelings - sympathy, gratitude, anger, forgiveness - are found in all human cultures",
                "Because real contributions don't exactly balance, human rules for reciprocal altruism are less binary than TIT FOR TAT's: affection and trust for the reliably nice, hostility and mistrust for the habitually mean",
                "Friendship, affection, and trust held human societies together long before contracts and written laws, and remain one reason human societies vastly surpass ant colonies in size and complexity despite near-zero kinship",
                "Altruism toward nonkin needn't have been created for the good of the tribe: Williams wrote that it was developed by the differential survival of individuals and designed for the perpetuation of the genes of the individual providing the benefit",
                "Cooperation can feed on itself: the more TIT FOR TAT creatures there are, the better each fares, producing an evolutionarily stable strategy impervious to small-scale invasion",
                "Axelrod and Hamilton wrote that 'the gear wheels of social evolution have a ratchet' - but a single TIT FOR TAT in a climate of pure meanness is doomed to extinction",
                "Kin selection probably gave reciprocal altruism a subtle boost: genes directing altruism toward suckling siblings could be followed by genes directing altruism toward altruists",
                "Long before they were reciprocal altruists, our ancestors were capable of familial affection, trust in kin, and guilt - handy psychological agents for natural selection to wire together in a new way",
                "Leda Cosmides has shown that people solve otherwise baffling logical puzzles when cast as social exchange, suggesting a 'cheater-detection' module among the mental organs governing reciprocal altruism",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Real Altruism versus Reputation Management",
            "Sort a stack of real-world helping behaviors - the vampire bat's regurgitated blood, the chimp's shared meat, the eye contact with a homeless man, the emergency-room charity, the public fistfight over honor - into the categories of genuine reciprocation, reputation-building, and pure kin service. For each card, trace the I.O.U. being written, note who is watching, and decide whether the act would survive the extinction of all witnesses.",
            "A dark laboratory with a vending machine labeled 'I.O.U.' dispensing printed gratitude notes; each card of behavior drops through a filter that stains red if the act depends on being seen.",
            [
                "Vampire bats that return to the roost empty-handed are often favored with regurgitated blood from other bats, and tend to return the favor - much sharing takes place within partnerships of unrelated bats that recognize each other by distinctive 'contact calls'",
                "Williams noted the mutually supportive coalitions of rhesus monkeys, and suspected the mutually 'solicitous' behavior of porpoises was reciprocal - a suspicion later confirmed",
                "Chimpanzees share food reciprocally, form somewhat durable alliances, groom friends, help them confront enemies, and show seemingly heartfelt outrage when one friend betrays another",
                "Trivers argued that gratitude, by reflecting the value of the benefit received, calibrates the repayment in order - gratitude is an I.O.U., so naturally it records what's owed",
                "The more desperate the plight of the beneficiary, the larger the I.O.U.: 'our deepest compassion is our best bargain hunting'",
                "Moral indignation guards against exploitation: Trivers noted that 'small inequities repeated many times over a lifetime may exact a heavy toll,' justifying a strong show of aggression when cheating is discovered",
                "Indignation is even more valuable when publicly observed - in a hunter-gatherer society where almost all behavior is public, one bloody fistfight can deter scores of neighbors from cheating you",
                "In a 1966 experiment, subjects who believed they had broken an expensive machine were more inclined to volunteer for a painful experiment, but only if the damage had been discovered - guilt's intensity tracks who knows, not your misdeeds",
                "When we pass a homeless person, what really gets the conscience twinging is making eye contact and still failing to help - we mind being seen not giving more than not giving",
                "Reputation is the object of the game for this 'moral' animal, and hypocrisy flows from two natural forces: the tendency to publicize the sins of others and the tendency to obscure our own sins",
                "A 'club-forming' gene could make you sacrifice for a team as a whole, extending loyalty and sacrifice outward to ever-larger groups without invoking group selection",
                "Daly and Wilson's view, shared by most evolutionary psychologists: 'Morality is the device of an animal of exceptional cognitive complexity, pursuing its interests in an exceptionally complex social universe'",
            ],
        ),
        "boss": (
            "Boss Battle: The Tournament of Strategies",
            "Enter a single program into Axelrod's tournament and duel the assembled strategies - the steadily mean, the steadily nice, the clever exploiters - across 200 encounters apiece. Choose whether to trust first, when to retaliate, when to forgive, and watch the culling sift generations until either your conditional niceness dominates the computer world or the exploiters eat you alive, and justify your design to the theory of reciprocal altruism.",
            "A vast mainframe hall glowing with green text where programs flicker through their 200 duel rounds; a leaderboard on the wall ticks over, and the shortest program on the list - five lines long - slowly climbs past the elaborate ones.",
            [
                "TIT FOR TAT's program was five lines long, the shortest submitted, so had strategies been created by random mutation it probably would have been among the first to appear",
                "If a program demonstrates a tendency to cooperate, TIT FOR TAT immediately strikes up a friendship; if it cheats, TIT FOR TAT cuts its losses by withholding cooperation until it reforms",
                "TIT FOR TAT never gets repeatedly victimized as indiscriminately cooperative programs do, and avoids the mutually costly chains of betrayal that entrap the relentlessly exploitative",
                "Strategies geared toward exploitation tended to lose out as the game wore on, denied both the large gains of exploitation and the moderate gains of mutual cooperation",
                "TIT FOR TAT is subject to positive, frequency-dependent feedback: the more TIT FOR TATs there are, the more successful each one is",
                "Axelrod, after watching TIT FOR TAT triumph, concluded that it was evolutionarily stable: no alternative strategy introduced via a single mutant gene can flourish against it",
                "Conditional cooperation is more infectious than unmitigated meanness - but steadfast uncooperativeness is itself an evolutionarily stable strategy, immune to invasion by a single mutant",
                "Had TIT FOR TAT been tossed in with forty-nine steadfast meanies, there would have been a forty-nine-way tie for first place and only one clear loser",
                "The theory of reciprocal altruism wins by default within biology - the only rivals are group-selectionist theories - and has fared well in tests since 1971",
                "The theory also passes the test of parsimony: a single simple evolutionary force plausibly accounts for sympathy, dislike, friendship, enmity, gratitude, obligation, and sensitivity to betrayal",
                "Reciprocal altruism is a misnomer: its goal is that the organism be left under the impression that we've helped, and the impression alone may be enough to bring the reciprocation",
            ],
        ),
    },
    {
        "num": 10,
        "title": "Chapter 10: Darwin's Conscience",
        "pages": "220-238",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Conscience Malfunction Monitor",
            "Run the diagnostic on Darwin's famously overactive conscience - the reflexive apologies in his letters, the nights rehashing conversations, the grief over Brazilian slaves, the pale walk home from the ill-used horse - and classify each symptom as designed adaptation or malfunction. For every twinge, name the genetic or environmental dial that set it, and mark whether natural selection's goal, genetic proliferation, was being served.",
            "A Victorian study turned clinic: the sleeping Darwin lies wired to a bank of gauges labeled 'guilt,' 'obligation,' and 'self-reproach' while a physician in modern scrubs reads the needles and a family tree glows on the wall.",
            [
                "The psychiatrist John Bowlby found Darwin's conscience 'overactive' and 'overbearing,' leaving him prone to self-reproach, chronic anxiety, and episodes of fairly severe depression",
                "Self-reproach was second nature to Darwin: an appreciable fraction of his voluminous correspondence consists of apologies for itself - 'How shockingly untidy this letter is,' he wrote as a teenager",
                "According to his son Francis, anything which had vexed or troubled Darwin in the day would haunt him at night - he might lie awake rehashing a conversation, worried he had caused offense",
                "Many years after the Beagle, Darwin was still plagued by the memory of slaves being tortured in Brazil",
                "Francis Darwin remembered his father returning from a walk 'pale and faint from having seen a horse ill-used'",
                "Natural selection doesn't 'want' us to be happy, only genetically prolific - and it didn't do too badly in Darwin's case: ten children, seven of whom survived to adulthood",
                "Darwin's conscience can serve as Exhibit A of a basically sound adaptation, goading him into acts that amplified his genetic legacy even if the goading hurt",
                "The conscience's rewards and punishments lack sensuality - it makes us feel as if we have done something wrong or right, a shameless ploy for a process as amoral and crassly pragmatic as natural selection",
                "Kin selection has ensured that people everywhere feel deeply guilty about grievously harming or neglecting a brother, sister, daughter, or son",
                "There is no known culture in which neglecting a friend is a guiltless and widely approved behavior - reciprocal altruism extends obligation selectively beyond kin",
            ],
        ),
        "dialogue": (
            "Dialogue: The Shrewsbury Reputation Audit",
            "Walk the streets of Victorian Shrewsbury as the young Darwin being shaped by sister Caroline's zealous improvements and father Robert's towering severity - 'You care for nothing but shooting, dogs, and rat-catching, and you will be a disgrace to yourself and all your family' - and then switch roles to the parent who must decide how much of that instruction is honest guidance and how much is Trivers-style molding. Choose the sermons to deliver about sharing with siblings, and hear what the child should discount.",
            "A cobbled Shrewsbury street frozen in a single evening: Caroline stands in a doorway asking what she will blame him for now, Robert's shadow falls across the garden, and a faint ledger overhead tallies the genes each lesson truly serves.",
            [
                "Darwin credited his humanity to the 'instruction and example of my sisters,' and abandoned plans for an insect collection because 'it was not right to kill insects for the sake of making a collection'",
                "Chief moralist was sister Caroline, nine years his elder, who functioned as surrogate mother after their mother's death in 1817 - Darwin recalled asking himself before entering a room where she was, 'What will she blame me for now?'",
                "Darwin's father Robert was a large, imposing, often austere man; one biographer summarized a common profile of him as 'a domestic bully' whose effect on his son was 'a continuing disaster of neurosis and disability'",
                "The young Darwin idolized his father and committed to lifelong memory his crudest rebuke - 'You care for nothing but shooting, dogs, and rat-catching' - and devoutly worked to win his approval",
                "Parents and other authority figures, including older kin, mold the conscience with praise and blame - basically the way Freud described the formation of the superego, and he seems to have gotten it basically right",
                "Because kin share so many genes with the young child, they have a strong, though not unbounded, reason to give useful guidance - and the child has reason to follow",
                "Trivers noted cause for skepticism on the part of children - for example, discounting parental sermons about sharing equally with siblings, though grounds for obedience grow when dealing with friends and strangers",
                "Behavioral geneticists say the heritability of 'conscientiousness' is between .30 and .40 - about one-third of differences trace to genes, leaving two-thirds traceable to environment",
                "The conscience is an example of genetically endowed knobs getting environmentally tuned to widely varied settings: everyone feels guilt, but not everyone feels it as acutely as Darwin over everyday conversations",
                "Trivers suggested that 'moral guidance' is a euphemism: parents are designed to steer kids toward 'moral' behaviors only insofar as those behaviors are self-serving",
                "Trivers wrote that one would expect selection to favor developmental plasticity of traits regulating altruistic and cheating tendencies, so the growing organism's sense of guilt may be 'educated, perhaps partly by kin'",
                "The voice of close kin carries a special resonance: Darwin's letters to Caroline from college still apologize for his penmanship and strain to convince her of his religious piety",
            ],
        ),
        "audit": (
            "Audit: The Victorian Character Field Study",
            "Tour Samuel Smiles's Victorian England - the character ethic of truthfulness, integrity, and goodness, the small-town morality of Shrewsbury - and log how the payoff for honesty rises and falls with town size and gossip speed. For each custom on your clipboard, compute the present value of a good name under stable neighbors versus urban anonymity, and mark which Victorian virtues would still pay off on a modern city street.",
            "A cobblestone town square doubling as a chalkboard: above every door floats a running tally of the reputational dividends of 'Be What You Seem,' while at the far edge of town the streets dissolve into anonymous city blocks where the tallies go blank.",
            [
                "The essence of Victorian character was 'truthfulness, integrity, and goodness,' and 'integrity in word and deed is the backbone of character' - in contrast with 'personality,' the twentieth century's amalgam of charm and social garnish",
                "Samuel Smiles approvingly quoted the man of 'sterling independence of principle and scrupulous adherence to truth' who noted that obedience to conscience is 'the road to prosperity and wealth'",
                "Smiles wrote that 'character is power,' quoting George Canning: 'My road must be through Character to power; I will try no other course'",
                "Most people in Victorian England lived in the rough equivalent of a small town, encountering the same small group of folks year after year - true in spades of Darwin's hometown, Shrewsbury",
                "In a small and steady social setting there's no escaping your past: 'Men whose acts are at direct variance with their words, command no respect'",
                "Smiles relayed the anecdote of the man who would give a thousand pounds for his good name 'because I could make ten thousand by it'",
                "The Darwin described by young Emma Wedgwood - 'the most open, transparent man I ever saw, and every word expresses his real thoughts' - was well equipped to thrive in Shrewsbury",
                "If you make Axelrod's computer world more like a small town, allowing creatures to gossip about who is or isn't scrupulous, cooperative strategies flourish even faster - cheaters get away with fewer swindles before people start shunning them",
                "If you allow frequent migration into and out of the group, the power of TIT FOR TAT wanes visibly and the success of meaner strategies grows - reputation matters less when acquaintances are fleeting",
                "'Those little courtesies which form the small change of life, may separately appear of little intrinsic value, but they acquire their importance from repetition and accumulation'",
                "Axelrod's computer can model cultural change: once people have flexible moral equipment, cooperation can spread or retreat over generations without any change in the gene pool",
                "The more conscientious the Victorians got, the more conscientious it made sense to be - the pendulum picks up momentum in both directions",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Honest Conscience versus Environmental Tuning",
            "Sort a pile of moral profiles - the scrupulous Shrewsbury gentleman, the inner-city teenager with short time horizons, the Victorian hypocrite, the childhood liar - and classify each one as an honest conscience, a tuned-by-environment conscience, or a pose. For each profile, name the dials that shaped it, decide whether the behavior is genetically fixed or environmentally cramped, and rule on whether the conscience's 'reach' extends past the in-group to the out-group.",
            "A laboratory of moral profiles where each subject stands in a glass booth labeled with its settings - village size, gossip speed, life expectancy - and a dial labeled 'reach of the conscience' stretches longer or shorter across the floor.",
            [
                "Darwinism suggests that from an early age, the conscience of many poor children - the very capacity for sympathy and guilt - is hemmed in by the environment, and settles somewhat firmly into a cramped form",
                "Martin Daly and Margo Wilson have argued that the 'short time horizons' for which criminals are famous may be 'an adaptive response to predictive information about one's prospects for longevity and eventual success'",
                "Once you think of genes as programming behavioral development rather than just behavior, we all start to look like victims or beneficiaries of our environment, no less than of our genes",
                "There is no 'urban underclass' notch in the developmental program that shapes the conscience, any more than there is a 'Victorian' notch",
                "The ancestral environment did, at times, present opportunities for profitable crime, notably periodic contact with nearby villages",
                "The human mind contains a binary moral landscape, comprising an in-group that deserves consideration and an out-group that deserves exploitation - even scrupulously polite Victorian men went to war convinced of the justness of the death they dished out",
                "Moral development is often a question not just of how strong the conscience will be, but of how long a reach it will have",
                "In a highly 'moral' society a good moral reputation is vital and a bad one costly - more incentive to exaggerate one's goodness, which is why the Victorians were more given to this type of deception than we are",
                "Walter Houghton wrote in The Victorian Frame of Mind that 'the Victorians were more given to this type of deception than we are. They lived in a period of much higher standards of conduct'",
                "Victorian England was an admirable society but not one composed of especially admirable people - they were acting conscientiously and considerately to the extent that it pays, and it just paid more in those days",
                "Even in modern industrial societies, when males kill males they know, there is usually an audience - a pattern that seems perverse except in terms of evolutionary psychology",
                "Children whose parents often lie are more likely than average to become chronic liars, and so are children who simply lack close parental supervision",
            ],
        ),
        "boss": (
            "Boss Battle: The Adaptation Executer's Verdict",
            "Sit in final judgment on Charles Darwin's conscience - the gardens planted for the Fuegian Indians, the Downe Friendly Society with its fines for swearing and drunkenness, the farmer prosecuted for letting sheep starve - and decide, with the full authority of modern Darwinism, whether each act was fitness-maximizing or adaptation-executing. Confront the dead sheep that cannot repay, the slaves who cannot reciprocate, and rule whether this 'excessively' moral man was a smoothly functioning adaptation or a conscience running past its evolutionary usefulness.",
            "A courtroom with a magistrate's bench facing the evidence: a small garden by the sea, a village clubroom with a fine-box, a field of starved sheep, and the ghost of an old slave-ship memory standing in the well of the court.",
            [
                "While in South America Darwin planted gardens for the Fuegian Indians, and in the village of Downe he founded the Downe Friendly Society, which provided a savings plan for local workers and a clubroom where swearing, fighting, and drunkenness were subject to a fine",
                "The dead sheep were poorly positioned to repay Darwin, the farmer certainly wouldn't, and the 'reputation effects' of behavior so fanatical might not have worked entirely to his advantage",
                "Human beings aren't 'fitness maximizers' but rather 'adaptation executers': the conscience was designed to exploit the local environment in the name of genetic self-interest, but success is far from assured",
                "In social settings alien to natural selection, the conscience can lead people to do things that aren't in their self-interest except in the sense of salving the conscience itself",
                "Sympathy, obligation, and guilt, unless subjected to a veritable extermination campaign during youth, always have the potential to bring behaviors of which their 'creator' would not 'approve'",
                "When Darwin heard a local farmer had let some sheep starve to death, he personally gathered the evidence and brought the case to the magistrate",
                "Jean Piaget, in his 1932 study of moral development, wrote that 'the tendency to tell lies is a natural tendency ... spontaneous and universal'",
                "Darwin was 'much given to inventing deliberate falsehoods': he claimed to have discovered a hoard of stolen fruit he had hidden himself, and told a boy he could produce variously coloured flowers by watering them with coloured fluids",
                "Childhood lies are the first in a series of test runs for self-serving dishonesty, shaped by positive reinforcement for undetected and fruitful lies and negative reinforcement for uncovered ones",
                "The transmission of moral instruction from old to young parallels the transmission of genetic instruction: Samuel Smiles wrote that 'The characters of parents are thus constantly repeated in their children'",
                "Darwin worked to endow his own children with solid reciprocal-altruism skills, writing to a son at school with precise instructions on how to thank Mr. and Mrs. Wharton",
                "Darwin's verdict, rendered with the authority of everything we now know about genes: he was a product of his environment - good in passive reflection of his society's goodness, and much of his goodness paid off",
            ],
        ),
    },
    {
        "num": 11,
        "title": "Chapter 11: Darwin's Delay",
        "pages": "238-245",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Two-Decade Timeline Examiner",
            "Lay out the twenty years between Darwin's discovery of natural selection in 1838 and the publication of the Origin in 1859 and tag every milepost - the 1844 sketch to Emma, the barnacle books, the 1858 letter from Wallace's theory, the final 'abstract' - as work done or work deferred. For each delay, name the cause that fits the record: illness, fear of censure, unfinished theory, or the seduction of Cirripedia, and mark which explanations are speculation.",
            "A drawing room with a long wall of calendar leaves, each stamped with an event and a verdict ribbon - 'prolific,' 'deferred,' 'subconscious forestalling' - while a single clock on the mantel ticks through two decades.",
            [
                "After discovering natural selection in 1838, Darwin spent the next two decades not telling the world about it; he didn't start writing a book on the theory until 1855",
                "Only in 1858, when he learned that another naturalist had arrived at the same theory, did he decide to produce what he called an 'abstract' - The Origin of Species, published in 1859",
                "Though slowed by frequent illness - violent shivering and vomiting attacks, gastric pain and epic flatulence, faintness, heart palpitations - Darwin was prolific in the 1840s",
                "During the first eight years of his marriage Darwin published papers, finished editing the five volumes of The Zoology of the Voyage of H.M.S. Beagle, and wrote three books: Coral Reefs (1842), Volcanic Islands (1844), and South America (1846)",
                "On October 1, 1846 Darwin noted in his journal, 'How much time lost by illness!' after finishing his geology - vintage Darwin in its grim resignation, endless self-criticism, and obsession with using time well",
                "In 1844 Darwin gave Emma a 230-page sketch of the theory of natural selection, with written instructions to publish it - and 'take trouble in promoting it' - in the event of his death",
                "The move to the rural village of Downe was testament to Darwin's physical decline: a tightly structured regimen of work, recreation, and rest to extract a few good hours of output each day",
                "Darwin's long involvement with barnacles began with curiosity about a Chilean species; by the end of 1854 he had published two books on living barnacles and two on barnacle fossils",
                "One of Darwin's young sons, visiting a neighbor's home, asked 'Where does he do his barnacles?' - so central was the study to Darwin's life",
                "In a letter to Hooker Darwin wrote: 'I am going to begin some papers on the lower marine animals, which will last me some months, perhaps a year, & then I shall begin looking over my ten-year-long accumulation of notes on species' - an attitude that could lead to an eight-year barnacle project",
            ],
        ),
        "dialogue": (
            "Dialogue: The Confession to Hooker",
            "Play the famous 1844 letter in which Darwin confesses his heresy to Joseph Hooker - 'it is like confessing a murder' - and then take the other side of the desk as Hooker, who must decide how to answer a friend who has found 'the simple way by which species become exquisitely adapted to various ends.' Choose your exact wording knowing the letter is one of the most defensive passages Darwin ever produced, and weigh how much of his fear belongs to the age and how much to the man.",
            "A study lit by one candle: two sheets of paper face each other across the desk, one trembling with 'Heaven forfend me from Lamarck nonsense,' the other blank and waiting; outside the window a whole village sleeps unaware.",
            [
                "The most common theory of Darwin's delay is the most obvious: writing a book that affronts the religious beliefs of virtually everyone in your part of the world - including many colleagues and your wife - is a task not to be approached without circumspection",
                "Darwin's grandfather Erasmus advanced a theory of evolution in 1794 in Zoonomia, and delayed its publication for some twenty years, finally saying 'I am now too old and hardened to fear a little abuse'",
                "Jean-Baptiste de Lamarck's grand exposition appeared in 1809, the year of Darwin's birth, and was denounced as immoral",
                "The 1844 book Vestiges of the Natural History of Creation, by the Scottish publisher Robert Chambers, was called 'a foul and filthy thing, whose touch is taint, whose breath is contamination'",
                "None of the earlier heretical theories was quite as godless as Darwin's: Chambers had a 'Divine Governor,' Erasmus Darwin was a deist, and Lamarckian evolution featured an inexorable tendency toward greater organic complexity",
                "Even before his belief in evolution crystallized, Darwin weighed rhetorical tactics to blunt criticism, writing in his notebook in the spring of 1838: 'Mention persecution of early Astronomers'",
                "In his 1844 letter to Hooker Darwin wrote: 'I am almost convinced (quite contrary to opinion I started with) that species are not (it is like confessing a murder) immutable'",
                "Darwin added: 'Heaven forfend me from Lamarck nonsense of a tendency to progression ... but the conclusions I am led to are not widely different from his - though the means of change are wholly so'",
                "Emma, who held her religion dear and was pained by her husband's evolutionism, heightened the tension between his science and his social environs",
                "A letter from Emma before their marriage reads: 'nothing could make me so happy as to feel that I could be of any use or comfort to my own dear Charles when he is not well ... So don't be ill any more my dear Charley till I can be with you to nurse you'",
            ],
        ),
        "audit": (
            "Audit: The Illness Inventory",
            "Audit Darwin's mysterious illness - the palpitations that began in September 1837 just after he opened his first evolution notebook, the shivering and vomiting, the gastric pain - and classify each episode as bona fide disease, psychosomatic procrastination, or emotionally induced illness. For every symptom, weigh the evidence for Chagas' disease or chronic fatigue against the evidence for a mind forestalling the day of reckoning, and rule on whether the nursing of Emma made unwellness easier than was healthy.",
            "A sickbed watched over by a physician's lamp: Darwin lies among charts of symptoms, a notebook open on the counterpane with 'species' written at the top, and Emma's folded letter glows beside the medicine bottle.",
            [
                "Darwin was feeling heart palpitations in September 1837, a couple of months after opening his first evolution notebook, and his reports of illness grow fairly frequent as the notebooks unfold toward the theory",
                "In the more elaborate versions of the theory, Darwin's illness - never clearly diagnosed, still a mystery - figures as a psychosomatic procrastination device",
                "Anxiety about social rejection is an ultimately physiological thing and takes a physiological toll - Darwin may have simply had what is known today as an emotionally induced illness",
                "Some people accept that Darwin had a bona fide disease, probably contracted in South America - perhaps Chagas' disease or chronic fatigue syndrome - but say he used barnacles to subconsciously forestall the day of reckoning",
                "The barnacles may have done Darwin a great service: they immersed him fully in the details of taxonomy and gave him an entire subclass of animals to examine in light of natural selection",
                "One theory of the delay is the simplest: in 1846, in 1856, and really in 1859 when the Origin was published, Darwin had not fully figured out natural selection",
                "Not until 1857 did Darwin solve the puzzle of insect sterility, with his precursor of the theory of kin selection",
                "Another puzzle Darwin never solved was the problem of heredity itself: Darwinian evolution depends on change in the range of inherited traits, but neither sexual recombination nor mutation made obvious sense before people knew about genes",
                "For Darwin to have talked about 'random mutations' when asked how the pool of traits changes would have been like saying, 'It just does - trust me'",
                "A great virtue of Darwin's theory is that it doesn't depend, as Lamarck's did, on the inheritance of acquired traits - a giraffe's stretching needn't affect the neck length of its offspring",
                "The evolutionary-psychology view of the delay doesn't yield a whole new theory but helps drain the episode of mystery once the roots of Darwin's ambitions and fears are clear",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Heresy Trials across the Century",
            "Line up the four evolutionists - Erasmus Darwin, Lamarck, Chambers, and Charles Darwin - side by side and grade each theory's offense against Victorian piety: the Divine Governor, the deist clock-winder, the inexorable tendency to complexity, and the slow accretion of fortuitous change. Sort the theories by godlessness, predict the abuse each received, and identify which one alone required the deepest fear before publication.",
            "A pillory line on a town green: four bound figures wear placards listing their doctrines, and a judge walks the line carrying a scale that tips farther down with each missing deity.",
            [
                "Erasmus Darwin's Zoonomia finally appeared after some twenty years, and he got the abuse he no longer feared",
                "Lamarck's scheme, though denounced by Chambers as 'disrespectful of Providence,' was downright spiritual compared to Darwinian evolution - it featured an inexorable tendency toward greater organic complexity and more highly conscious life",
                "Darwin's theory involved no Divine Governor, no clock-winder, and no inherent progressive tendency - nothing but the slow accretion of fortuitous change",
                "Darwin pointedly left open the possibility of a clock-winder, but his theory did not require one",
                "Chambers kept his name secret as author of Vestiges, perhaps wisely",
                "The Origin of Species was written as an 'abstract' because another naturalist - Alfred Russel Wallace - had arrived at the same theory by 1858",
                "The Origin of Species still begins with the epigraph from Darwin's notebooks about the persecution of early astronomers being worth mentioning as a rhetorical tactic",
                "In 1841 Darwin wrote to Charles Lyell of his illness: 'I shall probably do little more, but must be content to admire the strides others make in Science'",
                "Darwin described his life at Downe in a letter to Captain FitzRoy: 'My life goes on like Clockwork, and I am fixed on the spot where I shall end it'",
                "Darwin's books on barnacles are consulted to this day by biologists studying the subclass Cirripedia of the subphylum Crustacea",
            ],
        ),
        "boss": (
            "Boss Battle: The Day of Reckoning",
            "Confront the sum of Darwin's two decades of delay at the moment he must finally produce - the finished geology, the secure workplace at Downe, the sound of the grim reaper's footsteps - and decide what pushes him across the line: the threat of being scooped, the completed barnacle books, or the fear that the whole thing 'explodes like an empty puff-ball.' Defend your verdict against every theory of the delay, and name the single force that finally broke the twenty-year silence.",
            "A study at midnight: the barnacle volumes stand in a row like a wall between Darwin and a writing desk where a blank manuscript page waits; through the window the mail packet arrives carrying another naturalist's paper on species.",
            [
                "Given a secure workplace, the faint sound of the grim reaper's footsteps, and completion of all scholarly obligations from the Beagle expedition, the cause of further postponement was, in a word: barnacles",
                "By the end of 1854 - eight years after Darwin predicted his barnacle work would take a few months, maybe a year - he had established an enduring reputation within the realm of barnacles",
                "When the last of the barnacle books was published in 1854, the time had come for Darwin to muster his full reserves of enthusiasm for the coming culmination of his life's work",
                "Darwin wrote to Hooker: 'How awfully flat I shall feel, if, when I get my notes together on species, &c. &c, the whole thing explodes like an empty puff-ball'",
                "It is only logical, before unveiling a theory that will get you defamed and hated, to try to get it into good shape",
                "Darwin's fear of censure is evident in his correspondence - the confession to Hooker features one of the most defensive passages he ever produced",
                "The theory that Darwin was slowed by a hostile social climate assumes many forms, ranging from baroque to simple, depicting his delay in ways ranging from pathological to wise",
                "By so devotedly nursing him, Emma made his unwellness easier than was healthy - the high-water mark of her premarital ardor",
                "In 1857 Darwin solved the puzzle of insect sterility with his precursor of kin selection - one of the puzzles that had faced him since before the 1840s",
                "The story of the delay can be assessed from the standpoint of evolutionary psychology, which helps drain the episode of some mystery",
            ],
        ),
    },
    {
        "num": 12,
        "title": "Chapter 12: Social Status",
        "pages": "245-273",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Hidden Hierarchy Detector",
            "Re-examine the supposedly egalitarian societies - the Fuegians tearing cloth into shreds, the Ache with their communal meat pool, the Aka with no headman - and tag each one for the status structure hiding beneath the surface. For every society, name the informal rank that carries clout, identify who gets the extra wives, food, or offspring, and rule on whether any truly egalitarian human society has ever existed.",
            "A diorama gallery of 'classless' villages: as you walk, magnifying lenses descend and thin red threads begin to connect the village's real beneficiaries - the extra mouths fed, the extra children born - into a hidden pyramid.",
            [
        "Darwin found troubling the Fuegians' apparent lack of social inequality: 'even a piece of cloth is torn into shreds and distributed; and no one individual becomes richer than another'",
                "Darwin noted that the inhabitants of Otaheite, governed by hereditary kings, 'had arrived at a far higher grade' than the republican New Zealanders of the same people",
                "Darwin added the afterthought that 'it is difficult to understand how a chief can arise till there is property of some sort by which he might manifest and still increase his authority'",
                "To an affluent Englishman reared amid servants, a society never far from starvation will seem starkly egalitarian - but social hierarchy can assume many forms, and in every human society it seems to find one",
                "Anthropologists have been burdened by a hopeful belief in the almost infinite malleability of the human mind, fostered especially by Franz Boas and his students Ruth Benedict and Margaret Mead",
                "The Ache of South America seem to possess idyllic equality, but the best hunters have more extramarital affairs and more illegitimate children than lesser hunters, and their offspring have a better chance of surviving",
                "The Aka pygmies of central Africa have no 'headman,' but their kombeti subtly influences big group decisions, often earns the rank through hunting prowess, and gets the lion's share of the food, the wives, and the offspring",
                "It becomes doubtful that any truly egalitarian human society has ever existed: some societies lack the concept of status but they do have status - and everyone knows who is who",
                "In 1945 the anthropologist George Peter Murdock published 'The Common Denominator of Cultures,' venturing that 'status differentiation' was a human universal",
                "Being known as a good hunter among the Ache is an informal rank that carries clout with men and women alike",
            ],
        ),
        "dialogue": (
            "Dialogue: The Pecking Order Negotiation",
            "Play the newly assembled flock of hens and settle into a linear hierarchy - A pecks B with impunity, B pecks C - and then argue the case for the two rival explanations of what you've built. Take the hen's-eye view of selective fear that saves the costs of battle, then switch to the group-selectionist plea that submission keeps organized society from collapsing into anarchy, and let the judge rule which account survives the gene's-eye test.",
            "A farmyard at first light where a line of hens squares off in pairs; above them a chalk diagram assembles itself letter by letter while two lawyers - one in feathers, one in a tweed jacket - address the roost.",
            [
                "The Norwegian biologist Thorleif Schjelderup-Ebbe noticed the pecking order of hens in the 1920s, and declared in a frenzy of overextrapolation that 'Despotism is the basic idea of the world'",
                "The order of the pecking is not arbitrary: each hen defers to hens that will probably win anyway, saving itself the costs of battle - hierarchy is the sum of individual self-interest",
                "Pecking orders are yet another case where the 'thinking' has been done by natural selection: the organism need only tell its neighbors apart and feel a healthy fear of the ones that have brutalized it",
                "George Williams wrote that 'the dominance-subordination hierarchy shown by wolves and a wide variety of vertebrates and arthropods is not a functional organization. It is the statistical consequence of a compromise made by each individual in its competition for food, mates, and other resources'",
                "Robert Ardrey argued that without inherent capability for submission, 'organized society would be impossible and we should have only anarchy'",
                "Judging by the large number of essentially asocial species, natural selection doesn't share Ardrey's concern for social order and is perfectly willing to let organisms pursue inclusive fitness amid anarchy",
                "How would genes counseling submission, and thus lowering fitness, gain a foothold amid everyday competition among genes within the society? They'd tend to be banished from the gene pool first",
                "John Maynard Smith's 'hawk-dove' analysis shows dominance thriving while submissives abound, then fading as dominants meet in costly combat - equilibrating at a fixed ratio of dominants to submissives",
                "Among Harris sparrows, darker birds are aggressive and dominant while lighter ones are passive and submissive, with indirect evidence that the two strategies are equally conducive to fitness",
                "But the finding that low status brings low reproductive success in the Ache, the Aka, and many other societies is the hallmark of low-status animals trying to make the best of a bad situation, not an evolutionarily stable mix",
            ],
        ),
        "audit": (
            "Audit: The Status Signal Field Guide",
            "Spend a day cataloging the universal signals of rank - the erect posture of the proud man, the bowed head of the defeated child, the strut of the dominant chimp, the crouch of the loser - and record each sighting against the cross-cultural evidence. For every gesture, log where it was observed, whether nonhuman primates share it, and what it tells you about the bearer's place in the hierarchy before the first word is spoken.",
            "A world atlas whose pages flip through scenes - a Tahtitian chief, a schoolyard fight, an Arnhem chimp run - and a field notebook that auto-stamps each sighting with its cross-cultural entry number.",
            [
                "Darwin, after widely questioning missionaries and world travelers, concluded that 'scorn, disdain, contempt, and disgust are expressed in many different ways ... and that these are the same throughout the world'",
                "Darwin also noted that 'a proud man exhibits his sense of superiority over others by holding his head and body erect'",
                "A century later, studies showed posture becomes straighter immediately after social triumph, as when a student gets a high test score",
                "The ethologist Irenaeus Eibl-Eibesfeldt found that children in diverse cultures, after losing a fight, lower their heads in self-abasement",
                "People in all cultures feel pride upon social success, embarrassment or even shame upon failure, and anxiety pending these outcomes",
                "Put a group of children together and before long they fall into distinct grades: the ones at the top are best liked, most frequently imitated, and best obeyed - rudiments seen among children only a year old",
                "At first status equals toughness, and for males toughness matters well through adolescence - but as early as kindergarten some children ascend the hierarchy via skill in cooperation",
                "Status hierarchies run in our family: they emerge with clarity among chimps and bonobos and in simpler form among gorillas and many other primates",
                "Nonhuman primates send some of the same status signals: dominant male chimps strut proudly and expansively, while after a fight the loser crouches abjectly - a bowing repeated thereafter to express submission",
                "The whole point of the human brain is behavioral flexibility, and it would be very unlike natural selection to deny anyone a chance at the genetic payoffs of high status",
                "Some of the ways people signify status seem to hold steady across cultures, and these universals of expression have reflections within",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Serotonin, Status, and Destiny",
            "Sort the biochemical evidence - the vervet dominant's serotonin, the fraternity officer's serotonin, the impulsive criminal's low serotonin - and classify each correlation as genetic destiny, environmental product, or adaptive response. For every data point, decide whether the hormone level came before the status or after it, and rule on the once-flourishing misconception that behavior under biological control is genetically determined.",
            "A laboratory with two columns of test tubes, one labeled 'cause' and one labeled 'effect,' while above a row of vervet monkeys and fraternity officers sorts itself into a hierarchy; a banner reads 'not destining, equipping.'",
            [
                "In vervet monkey societies, dominant males have more of the neurotransmitter serotonin than do their subordinates",
                "In college fraternities, officers on average have more serotonin than their less powerful fraternity brothers",
                "It is not the case that all behavior under 'hormonal control' is 'genetically determined': serotonin level, though biological, is largely a product of the social environment",
                "If you check the serotonin levels of a fraternity president well before his political ascent, you may find them unexceptional - serotonin isn't nature's way of destining people at birth for leadership",
                "Serotonin is nature's way of equipping people for leadership once they've gotten there - and, some evidence suggests, of encouraging them to make a bid for leadership at a politically opportune moment",
                "Often serotonin seems to relax people, making them more gregarious and socially assertive, much as a glass of wine does - and one of alcohol's effects is to release serotonin",
                "Extremely low levels of serotonin can accompany not just low self-esteem but severe depression, and may precede suicide; antidepressants such as Prozac boost serotonin",
                "Psychologists found that artificially lowering self-esteem made people more likely to cheat in a subsequent game of cards, and a more recent study finds people with lower serotonin more likely to commit impulsive crimes",
                "Both findings may say the same thing in evolutionary terms: 'cheating' is an adaptive response triggered when people are shunted to the bottom of the heap and find it hard to get resources legitimately",
                "No one is born to lead and no one is born to follow; everyone is born with the capacity for high serotonin - with the equipment to function as a high-status primate given a conducive setting",
                "If the acceptance of low status had evolved for group success, you wouldn't expect low-status animals to spend their time subverting the group's order",
            ],
        ),
        "boss": (
            "Boss Battle: The Arnhem Throne Room",
            "Survive the soap-operatic struggle for alpha status among the Arnhem chimpanzees - Yeroen's alliance with the females, Luit's relentless challenge, Nikkie's rise as figurehead - and make every Machiavellian move yourself: the baby kissing before election day, the punishment of rivals' supporters, the coy alliance that topples the king. Play each chimp in turn, balance the female coalition against the young Turks, and hold the throne without losing your testicles, then defend the verdict on whether de Waal's anthropology is science or sentiment.",
            "A two-acre island in a Dutch zoo at dusk: three male chimps move through the trees in a silent ballet of displays and embraces while the females sit in a ring like a parliament, and a scoreboard overhead ticks the allegiance of every ape.",
            [
                "Yeroen, while alpha, relied on the allegiance of females, most notably Mama, the dominant female; when challenged by the younger, stronger Luit, it was to the females he turned for help",
                "During the weeks before Luit's first overt defiance, Yeroen had more than doubled the amount of time he spent in friendly contact with adult females - politicians do most of their baby kissing around election time",
                "Luit punished Yeroen's supporters for weeks, threatening or assaulting any female caught grooming Yeroen, yet might later groom the same female or play with her children - so long as she wasn't with Yeroen",
                "Nikkie, emerging from adolescence, struggled to establish dominance over all females, and the affiliation with Luit made this simple - a natural partnership sealed by special sexual privileges",
                "Luit proved a wise and mature leader, stepping between fighting chimps with calm authority and almost always siding with the one who was losing - populism that impressed the females, who placed a premium on social stability",
                "Yeroen, seemingly aware of his pivotal place in the balance of power, played Luit and Nikkie off against each other, shifted his weight toward Nikkie, and toppled Luit",
                "Alpha status went to Nikkie, but for the next year it was Yeroen, not Nikkie, who led all males in sexual activity - de Waal considered Nikkie a 'figurehead' and Yeroen the power behind the throne",
                "After Luit resumed alpha status, Nikkie and Yeroen wounded him mortally in a brutal fight, ripping out his testicles; de Waal later said, 'I cannot look at Yeroen without seeing a murderer'",
                "A peace overture can carry intimations of submission, and submission during a leadership struggle carries real Darwinian costs - hence the reluctance to be first to apologize, which we call a sense of honor",
                "During human evolution, males who too readily sought reconciliation after a fight saw their status drop, and with it their inclusive fitness",
                "The deepest source of the 'sense of fairness' is reciprocal altruism: de Waal's two basic rules of chimpanzee conduct - 'One good turn deserves another' and 'An eye for an eye' - amount to a description of TIT FOR TAT",
                "When Nikkie displayed at the female Puist and Luit failed to protect her, Puist turned on Luit, barking furiously, chasing him across the enclosure and hitting him - fury much like chastising a friend who deserted you",
            ],
        ),
    },
]
