# -*- coding: utf-8 -*-
"""Phase 2 chapter data for The Moral Animal (Robert Wright), chapters 13-18.
Each chapter: num, title, pages, domain, and 5 slots (scrub/dialogue/audit/matrix/boss),
each slot a 4-tuple (topic, player_mission, visual_frame_description, key_concepts[10-12]).
"""

D = "History of Science | Natural Theology vs. Evolution"

CHAPTERS = [
    {
        "num": 13,
        "title": "Chapter 13: Deception and Self-Deception",
        "pages": "273-298",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Self-Inflation Lab",
            "Scan a gallery of twelve self-presentation scenes, from a Photuris firefly flashing a mating signal to a Victorian gentleman citing his foreign translations. In each one name the deceptive cue, say whether the performer is under any illusion about his own act, and judge whether natural selection cares about the accuracy of the picture being presented.",
            "A dim Victorian natural-history museum where each exhibit case freezes mid-scene, a cue highlighted in a pulsing amber ring while a truth-meter labeled 'Selection's Priorities' never moves from 'Indifferent'.",
            [
                "Female fireflies of the genus Photuris mimic the mating flash of Photinus females and then eat the males they attract",
                "Some orchids look quite like female wasps to lure male wasps that unwittingly spread pollen, and harmless snakes have evolved the coloration of poisonous snakes to gain undeserved respect",
                "Some butterfly pupae bear an uncanny resemblance to a snake's head, with fake scales and fake eyes, and rattle menacingly if bothered",
                "Erving Goffman's The Presentation of Self in Everyday Life stressed how much time we spend on stage, and he marveled that people get sincerely convinced that the impression of reality they stage is the real reality",
                "In the mid-1970s Richard Alexander and Robert Trivers hypothesized that we deceive ourselves in order to deceive others better",
                "Trivers argued that if deceit is fundamental to animal communication, strong selection to spot deception ought in turn to select for a degree of self-deception, rendering some facts and motives unconscious",
                "Trivers called the conventional view that natural selection favors nervous systems producing ever more accurate images of the world a very naive view of mental evolution",
                "Our accurate depiction of reality, to others and sometimes to ourselves, is not high on natural selection's list of priorities",
                "Reciprocal altruism and social hierarchy may together be responsible for most of the dishonesty in our species, which accounts for a good part of the dishonesty in the animal kingdom",
                "We are far from the only dishonest species, but we are surely the most dishonest, if only because we do the most talking",
                "When a chimp threatens a rival its hair stands on end, making it seem larger than life, and vestiges of this illusion appear in frightened people whose hair stands on end",
                "Natural selection neither 'prefers' honesty nor 'prefers' dishonesty; truth and honesty are never favored in and of themselves, and when accurate reporting coincides with genetic interest that is just a happy accident",
            ],
        ),
        "dialogue": (
            "Dialogue: The Left-Brain Press Agent",
            "Play Michael Gazzaniga's split-brain patients: your left hand has just grabbed a nut you deny seeing, and your command-walk needs a story. Produce the convincing explanation the left hemisphere gives, then switch sides and interrogate Darwin about Richard Owen's savaging review of the Origin, catching the unknowing dishonesty in his account.",
            "An operating theater divided by a glowing seam, with the left half narrating its own plausible alibi in bright letters while the right half silently points at the truth behind a frosted window.",
            [
                "Split-brain patients have had the link between left and right hemispheres cut to stop severe epileptic seizures, with surprisingly little effect on everyday behavior",
                "If the word nut is flashed only to a split-brain patient's right hemisphere, the subject denies conscious awareness yet his left hand will seize a nut from a box of objects",
                "When the command walk is sent to a man's right brain, his left brain, not privy to the real reason, invents a story: he is going to get a soda, and he is convinced",
                "A nude image flashed to a woman's right brain makes her laugh, and when asked what is funny she gives an answer less racy than the truth",
                "Gazzaniga said language is merely the 'press agent' for other parts of the mind, justifying whatever acts they induce and convincing the world the actor is reasonable and rational",
                "It may be that the realm of consciousness itself is in large part such a press agent, infusing unconsciously written press releases with conviction",
                "The Darwinian anthropologist Jerome Barkow wrote that the primary evolutionary function of the self may be to be the organ of impression management rather than a decision-maker",
                "The feeling that we are consciously in control of our behavior may be a purposeful illusion, designed by natural selection to lend conviction to our claims",
                "It is not beyond the pale to suggest that the philosophical position of free will itself is essentially an adaptation",
                "In shock experiments, subjects told to behave cruelly toward someone tended afterwards to derogate their victim, as if to convince themselves he deserved his mistreatment",
                "When subjects delivered 'shocks' after being told the victim could retaliate later, they tended not to derogate him, as if the mind follows a rule that only unbalanced accounts need rationalization",
                "People justify failures to help others by minimizing the person's plight, their own responsibility for it, and their own competence to help",
            ],
        ),
        "audit": (
            "Audit: The Skewed Social Ledger",
            "Audit Darwin's private accounts of debts and credits: the college debts he later scaled down by half, the dismissive footnote about grandfather Erasmus's anticipatory sentence on sexual selection, and the shifting appraisal of Leonard Jenyns. For each entry decide whether the balance was recorded honestly or slanted toward the self, and log it in the ledger of reciprocal altruism.",
            "A candlelit study where a leather-bound ledger floats open, each entry glowing red when the recorded balance favors the book's owner and green when it matches an impartial referee's copy.",
            [
                "Central to reciprocal altruism is the monitoring of exchanges, the record of whom you owe, who owes you, and how much is owed",
                "From the gene's point of view, monitoring the two sides of the ledger with equal diligence would be foolish: if you give more than you get by even the smallest increment, that is an increment of loss",
                "People keep closer track of what they are owed than of what they owe, obvious enough a century and a half ago to fuel a joke Darwin relayed from the Beagle about Byron's altered debtor",
                "Darwin accumulated debts in college and, one biographer reports, when mentioning his extravagances in after years seems to have scaled them down by half",
                "Darwin's grandfather Erasmus wrote a sentence strikingly anticipating sexual selection, yet in the third edition of the Origin Darwin dismissed him in a footnote as a pre-Lamarckian harbinger of Lamarck's confusion",
                "As one biographer wrote, 'generous though Darwin always was to those whose empirical observations he found useful, he barely acknowledged those whose ideas had influenced him'",
                "Darwin lavished credit on scores of minor-league researchers while diminishing the few predecessors who might have been remote contenders for his crown, a sound formula for high status",
                "Bronislaw Malinowski observed that the Trobriand Islanders were inclined to boast of their own gifts while disputing the value of what they themselves received",
                "Wars routinely feature a deep and sure sense of grievance on both sides, and even next-door neighbors can bring comparable conviction to their differing historical records",
                "Because Axelrod's computer made life binary, getting slightly more than you give was conflated with cheating, but real life is finely graded and slight overpayment can make sense for both parties",
                "Thomas Schelling noted the irony that in a non-zero-sum game the power to constrain an adversary may depend on the power to bind oneself, as in the game of chicken or buying a car",
                "Darwin wrote in his autobiography of a 'golden rule': immediately write down any observation inconsistent with his theories, since such facts escape the memory far more readily than favorable ones",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Genuine Sentiment or Status Signal",
            "Classify sixteen scenes - Owen's envious review, Darwin's reverence of FitzRoy, a humiliated man's low self-esteem, a wife 'deceiving down' to build her husband's confidence - as genuine sentiment, adaptive signal, or self-deceptive signal. For each, name the currency involved: status or reciprocal altruism.",
            "A rotating carousel of dioramas where each frozen tableau slides under a classification stamp that reads 'Sentiment', 'Status Signal', or 'Self-Deception', and a ticker tape shows which Darwinian currency the scene trades in.",
            [
                "Status hierarchies place a premium on seeming competent, attractive, strong, and smart, while reciprocal altruism puts its accent on niceness, integrity, and fairness",
                "Richard Alexander stressed the evolutionary importance of moral self-advertisement, noting modern society is filled with myths of our goodness, from humble scientists to devoted teachers",
                "Low self-esteem may have evolved as a way to reconcile people to subordinate status when reconciliation is in their genetic interest",
                "John Hartung, in 1988, raised the possibility of self-deceptively lowering self-esteem, which he called 'deceiving down', and suggested women may sometimes falsely subordinate themselves to men",
                "In the galvanic skin response experiment, people lowered in self-esteem tended to deny their own recorded voice, while people raised in self-esteem claimed other voices as their own, even though their GSR showed the truth was tallied correctly",
                "Trivers wrote of the experiment that we expand ourselves when succeeding and shrink our presentation of self when failing, yet are largely unconscious of this process",
                "Randolph Nesse has stressed that mood can efficiently focus energy: people get lethargic when prospects look dim and grow optimistic when opportunities arise, as if resting up for a big match",
                "Darwin's July 1857 gloom after Lubbock pointed out a gross blunder in his calculations had three possible functions: a self-esteem deflator, a negative reinforcement, and a course changer",
                "Whether you are a 'good' or a 'worthless' person is a question whose objective meaning is, at best, elusive, and truth is a concept to which natural selection is indifferent",
                "Being a person's true friend means endorsing the untruths he holds dearest, so that friendship links individual nodes of self-serving dishonesty into webs of collective dishonesty",
                "The strongest friendships may be the ones in which the partners see each other least clearly, since the best friends share the deepest bias",
                "A common bond between friends is a common enemy: two people playing a prisoner's dilemma cooperate more in the presence of someone they both dislike",
            ],
        ),
        "boss": (
            "Boss Battle: The Owen Review Siege",
            "Face Richard Owen, whose savaging review of the Origin has just appeared, in a war of rival appraisals where both of you are sincerely convinced of your own righteousness. Out-deflate him without ever admitting - even to yourself - that your verdict serves your status, and survive his counter-review with your coalition intact.",
            "A foggy London print shop where two quills duel over a broadsheet, each ink stroke turning into a glowing accusation while both writers' faces, behind the type, radiate equally genuine indignation.",
            [
                "Richard Owen, an eminent zoologist with his own ideas about how species might change, savaged the Origin of Species in a review",
                "After the review appeared, Darwin noted that the Londoners said Owen was mad with envy because his book had been talked about",
                "Probably one or the other, and possibly both, of the two men had self-servingly convinced himself about the rival's motives: Owen that Darwin's work was inferior, Darwin that Owen was driven by selfish envy",
                "The keen sensitivity with which people detect the flaws of their rivals is one of nature's wonders, and reining in the perception itself is truly a job for a Buddhist monk",
                "Honesty of evaluation is simply beyond the reach of most mortals",
                "Self-deprecation is without cost when everyone knows better and can have benefit, since a reputation for humility boosts the credibility of subtle boasting - witness Darwin",
                "Darwin captured the morally charged nature of enmity in The Expression of the Emotions in Man and Animals: few individuals can long reflect about a hated person without feeling and exhibiting signs of indignation or rage",
                "Enmity is a cocreation of reciprocal altruism and status hierarchies: it grows out of rivalry, and it is the flip side of reciprocal altruism, since being a successful reciprocal altruist means keeping track of those who take your aid but don't return it",
                "When people are our enemies, the standard response is to convincingly say bad things about them, and the best way to do that is to believe those things",
                "Darwin's appraisal of Leonard Jenyns shifted: he called him selfish with a 'weak mind' after Jenyns refused him a beetle specimen, then found him 'an excellent naturalist' eighteen months later after a magnificent present of flies",
                "When grudges expand into networks, as friends form coalitions to support each other's status, the result is vast webs of self-deception and, potentially, of violence",
                "Feelings of enmity, grievance, and righteous indignation probably have their deepest roots in ancient conflicts among coalitions of males for status within bands",
            ],
        ),
    },
    {
        "num": 14,
        "title": "Chapter 14: Darwin's Triumph",
        "pages": "298-324",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Westminster Abbey Ascent",
            "Track Charles Darwin's climb from beetle-collecting undergraduate to burial beside Newton in Westminster Abbey, spotting the status cues in each scene: the rivalry with Jenyns, the reverence for Henslow, the effusive praise of FitzRoy, and the bounded step on Ascension Island. Name the maneuver and say which rung of the social ladder it was aimed at.",
            "A vertical diorama of Westminster Abbey interior, with Darwin's figure ascending step by step while each relationship he cultivates lights up like a rung and the coffin maker's rough workmanlike box fades behind a polished state coffin.",
            [
                "When Darwin died in 1882 he was buried in Westminster Abbey, not far from the body of Isaac Newton - alpha-male territory",
                "Darwin was one of our finest specimens at what human beings are designed to do: manipulating social information to personal advantage",
                "Darwin was not alone in authoring the theory: Alfred Russel Wallace arrived at natural selection independently and circulated a written description of it before Darwin went public",
                "As a young Cambridge beetle collector Darwin wrote that he thought he beat Jenyns in Colymbetes, and was glad to see his name in Stephens's last number if only to spite Mr. Jenyns",
                "John Bowlby's portrait of Darwin - nagging self-contempt, ever-present fear of criticism, exaggerated respect for authority - doesn't sound like an alpha male in the making",
                "Often the first step up the social scale is to forge a bond with a primate of higher status, which involves an act of submission, a profession of inferiority",
                "Darwin's most extreme deference at Cambridge was reserved for the professor and reverend John Stevens Henslow, whom he helped set up lectures for and who made him known as 'the man who walks with Henslow'",
                "Darwin came prepared to reverence Captain FitzRoy, writing that FitzRoy was 'as perfect as nature can make him' until years later, when he could afford to describe his 'consummate skill in looking at everything in a perverted manner'",
                "On Ascension Island Darwin learned that Adam Sedgwick had said he would some day 'have a great name among the Naturalists of Europe', and he clambered over the mountains with a bounding step",
                "Six years into Darwin's rise, his old mentor William Fox felt a new asymmetry in their friendship, apologizing for the dullness of his letters and noting Darwin's time was valuable while his was worth nothing",
                "We tend to like people we find we can influence, and to like them even more if they have high status - social psychologists showed this in the 1950s, and natural selection seems to have done the thinking",
                "Darwin's relationship with Lyell was a bond of reciprocal altruism: Darwin brought mountains of fresh evidence for Lyell's geology while Lyell provided guidance, social sponsorship, and a spot in the Athenaeum Club",
            ],
        ),
        "dialogue": (
            "Dialogue: The Lord Chancellor Arbitration",
            "Replay the correspondence of June 1858: play Darwin weighing whether he can honorably publish a sketch, then play Lyell and Hooker deciding to present both theories as equals to the Linnean Society. Argue each position in Darwin's own words, then decide - and justify - whether Wallace should have been consulted before the papers went in.",
            "A writing desk in the gloom of Down House where two letters glow on the blotter, one signed 'your affectionate friend C. Darwin', the other stamped with a judge's gavel that neither hand quite dares to touch.",
            [
                "On June 18, 1858, the mail brought a letter from Wallace containing a precise sketch of his theory of evolution whose likeness to Darwin's was stunning: 'Even his terms now stand as heads of my chapters'",
                "Darwin proposed a pious course of action to Lyell - offering to send Wallace's paper to any journal - and left it for Lyell to propose a less pious one",
                "Darwin wrote that there was nothing in Wallace's sketch not written out much fuller in his 1844 sketch read by Hooker, and in the sketch sent to Asa Gray, so that he could most truly say and prove that he took nothing from Wallace",
                "In his anguished letter Darwin repeatedly asked Lyell whether publication would be honorable and whether Wallace's sending the sketch tied his hands, then washed his hands of the affair by appointing Lyell 'a Lord Chancellor'",
                "Darwin's anguish was deepened by his daughter Etty's diphtheria and his baby Charles Waring's scarlet fever, from which the child would soon die",
                "Lyell and Hooker decided to treat Darwin's and Wallace's theories as equals, introducing both at the next meeting of the Linnean Society and publishing them together",
                "Since Wallace was in the Malay Archipelago and the meeting was imminent, Lyell and Hooker proceeded without consulting him, and Darwin let them",
                "Wallace wrote proudly to his mother that the eminent men thought so highly of his essay that they read it before the Linnean Society, which assured him their acquaintance and assistance on his return home",
                "Hooker and Lyell introduced the papers by noting that 'while the scientific world is waiting for the appearance of Mr. Darwin's complete work, some of the leading results of his labours, as well as those of his able correspondent, should together be laid before the public'",
                "The option the three men pursued was the only one that ensured natural selection would go down in history as Darwin's theory, and it entailed publishing Wallace's paper without his expressed permission",
                "Darwin wrote to Lyell that he would far rather burn his whole book than have Wallace or any other man think he had behaved in a paltry spirit - being conscientious was, in his social environment, the same as being savvy",
                "Darwin's later appeals for Lyell's support showed the same pragmatism, as he begged Lyell's verdict, which he regarded as far more important than any other dozen men's",
            ],
        ),
        "audit": (
            "Audit: The Twenty-Year Delay Audit",
            "Audit Darwin's two decades of silence after discovering natural selection: the strengthened argument, the barnacle credentials, and the assembled coalition of Lyell, Huxley, Hooker, and Gray. For each prong of the strategy decide whether it was calculation, self-doubt, or both, and log what each move bought in the currency of status.",
            "A ledger-shaped chart of the years 1838-1858, each entry splitting into three columns labeled 'Argument', 'Credentials', 'Coalition', with a small frightened rodent image recurring in the margin near the word 'delay'.",
            [
                "Evolutionary psychology silhouettes two forces wrenched Darwin: an inherent love of esteem, which one route to was authoring a revolutionary theory, and the near-certainty of public hostility toward it",
                "In a famous 1950s experiment a surprisingly large number of people professed obviously incorrect opinions about the lengths of two lines when placed with others who professed them",
                "Another fifties-era experiment showed a person's recollections vary with the audience he expects to address, leading the authors to suggest much mental activity is imagined communication with imagined or real audiences",
                "Darwin's bent for self-doubt in the face of disagreement was quintessentially human - unusual in degree, but not in kind",
                "Natural selection 'wants' us to feel uneasy when pondering actions that augur a massive loss of public esteem, which explains Darwin's anxiety during the Origin's gestation",
                "Adam Sedgwick, whose praise had so thrilled Darwin, led the assault on Robert Chambers's evolutionist tract Vestiges with the warning that the world cannot bear to be turned upside down",
                "Frank Sulloway compared Darwin's modest-to-a-fault concern with personal error, which erected a theory that stood the test of time, with Freud's confident 'conquistador' ambition that produced nineteenth-century fantasies masquerading as science",
                "Sulloway argued that a moderate degree of lowered self-esteem coupled with dogged persistence is actually a valuable attribute in science, helping to prevent over-estimation of one's own theories",
                "The speculation is irresistible that Darwin's father, in implanting a lifelong source of discomfort, was functioning as designed, adjusting his son's psyche in ways that promised to raise social status",
                "We are built to be effective animals, not happy ones, and Darwin's heightened fear of criticism kept him chronically distanced from serenity and therefore busy trying to reach it",
                "Credibility grows with prestige, and Peter Brent suggested that in studying barnacles for four volumes Darwin was not training himself but qualifying himself",
                "Darwin advised a young botanist to let theory guide his observations but, till his reputation was well established, to be sparing in publishing theory, since it makes persons doubt your observations",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Ambition or Decency",
            "Sort Darwin's recorded acts - the deference to FitzRoy, the 'abdication' to Lyell, the pleading letters for support, the praise of Hooker's character - into conscious ambition, genuine decency, or natural-selection-without-conscious-calculation. For each verdict name the adaptation that does the 'thinking' when the conscious mind does not.",
            "A courtroom portrait gallery where each of Darwin's letters is projected onto a canvas, and a brush of light repaints it three times: once as Machiavellian plot, once as saintly candor, and once as an organ of the evolved mind no more self-aware than a beating heart.",
            [
                "Darwin's whole career looks less like an erratic quest stymied by self-doubt and more like a relentless ascent deftly cloaked in scruples and humility",
                "The notion of Darwin as a typical young male bent on conquest seems at odds with standard appraisals, but the deference to mentors is a common ingredient of social success",
                "The tendency to view the next rung on the social ladder with respect is most effective when people are thoroughly in its thrall and not conscious of its purpose: we feel genuinely in awe of people before whom we might profitably grovel",
                "Our gauging of people's worth reflects partly the place they occupy in our social universe at the time, and we are selectively blinded to qualities it would be inconvenient to acknowledge",
                "FitzRoy wrote to a naval officer that he liked what he saw and heard of Darwin much, requesting that Darwin be named the ship's naturalist, as Darwin was rationally pursuing long-term self-interest with the aid of short-term prejudice",
                "Elevations of status may bring a reevaluation of one's social constellation, and Darwin's old mentor Fox sensed the silent renegotiation of their reciprocal-altruism contract",
                "Lyell's friendship with Darwin had a common cause in geology, and common causes are a frequent sealer of friendships, apparently for Darwinian reasons, since both men's status would rise or fall with the theory's fortunes",
                "Self-serving behavior needn't involve conscious calculation; natural selection has given us an affinity for people who will be reliable reciprocal-altruism partners, with trust joining common interest as the sine qua non of friendship",
                "Darwin's compulsion to have a confidant before going public can be viewed as evolutionary calculation: 'I do not think I am brave enough to have stood being odious without support'",
                "Mutinies of all kinds in all cultures begin with whispers, and even an untutored six-year-old feels the wisdom of discreetly eliciting opinions about the local bully before mounting a challenge",
                "The Oxford evolution debate was famously won by Thomas Huxley over Bishop Wilberforce, but Joseph Hooker gave Darwin a different account in which Huxley couldn't command the audience and Hooker himself smacked Wilberforce amid rounds of applause",
                "Both Huxley's and Hooker's stories of the Oxford debate did two things at once: raise their stature in Darwin's eyes and leave him indebted to them",
            ],
        ),
        "boss": (
            "Boss Battle: The Linnean Double Bill",
            "Face the greatest crisis of Darwin's career: Wallace's paper is in your hands and the Linnean meeting approaches. Balance priority against propriety, marshal Lyell and Hooker to present the two papers, then face the accusation - from a century of hindsight - that you passed your toughest moral test without flying colors.",
            "A gaslit Linnean Society hall where two papers are laid side by side on the lectern, the smaller one already fading to an asterisk, while in the gallery the same man who reads them out also reads the future indictments.",
            [
                "The greatest crisis of Darwin's career began in 1858 when Wallace, who had discovered natural selection two decades after Darwin, stood poised to preempt him",
                "Darwin fiercely pursued his self-interest but so smoothly, and shrouded in so much moral angst, that observers have ever since called the episode another example of his superhuman decency",
                "The biochemical essence of Darwin's panic probably goes back to our reptilian days, but it was triggered not by threat to life and limb but by a threat to status, a concern more characteristic of our primate days",
                "Wallace's paper was published without his expressed permission, an act whose propriety someone with Darwin's scruples might normally question, and the option pursued was the only one that ensured history would record the theory as Darwin's",
                "Julian Huxley called the outcome a monument to the natural generosity of both great biologists, and Loren Eiseley called it an example of mutual nobility, but both are only half right",
                "Wallace, ever gracious, insisted correctly but generously that Darwin's length and depth of thought had earned him the title of premier evolutionist, and even titled a book of his Darwinism",
                "Wallace began to doubt that natural selection could account for the full powers of the human mind and concluded that man's mental capacities were divinely implanted",
                "Darwin's values proved exquisitely pliable: he had called territoriality unworthy of searchers after truth, yet when his turf was threatened he defended it, and he told Hooker he had fancied he had a grand enough soul not to care, but found himself mistaken and punished",
                "Darwin later claimed in his autobiography that he cared very little whether men attributed most originality to him or Wallace, a claim anyone who has read his distraught letters must marvel at as an instance of self-deception",
                "The conscience can be viewed as the administrator of a savings account in which moral reputation is stored, and the Wallace episode was a time to risk some of Darwin's vast accumulated capital",
                "Darwin's moral anguish was authentic - Bowlby diagnosed his 'self-contempt for being vain' - and it was the proven authenticity of the anguish that helped convince Hooker and Lyell, and then the world, that he strongly resisted glory",
                "The distinction between a conscience that serves kin selection and one that serves reciprocal altruism was highlighted by the episode: with nonkin, the perception of altruism, not the altruism itself, is what brings reciprocation",
            ],
        ),
    },
    {
        "num": 15,
        "title": "Chapter 15: Darwinian (and Freudian) Cynicism",
        "pages": "324-338",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Triune Brain Observatory",
            "Watch twelve scenes of psychic life through Paul MacLean's triune brain: a reptilian urge surfacing as an id impulse, a superego restraint, an ego rationalization, and a repressed memory re-emerging when a friend's status falls. Identify which part of the brain is onstage in each and say which evolutionary currency the scene serves.",
            "A cross-section of a skull rendered as a three-story theater, the reptilian basement stage, the limbic middle, and the neomammalian balcony, with each actor's line projected onto the appropriate floor.",
            [
                "Paul D. MacLean calls the human brain a 'triune' brain whose three parts recapitulate evolution: a reptilian core, a 'paleomammalian' brain that endowed ancestors with affection for offspring, and a 'neomammalian' brain with abstract reasoning and language",
                "MacLean writes that the neomammalian brain is the handmaiden for rationalizing, justifying, and giving verbal expression to the protoreptilian and limbic parts of our brains",
                "Freud's 'id', the beast in the basement, presumably grows out of the reptilian brain, a product of presocial evolutionary history",
                "The 'superego', loosely the conscience, is a more recent invention, the source of inhibitions and guilt designed to restrain the id in a genetically profitable manner, preventing us from harming siblings or neglecting friends",
                "The 'ego' is the part in the middle whose ultimate, if unconscious, goals are those of the id, pursued with long-term calculation and mindful of the superego's cautions",
                "Randolph Nesse and Alan T. Lloyd see psychic conflict as a clash among competing advocacy groups, much as tension among branches of government is designed to yield good governance",
                "The basic discourse runs between selfish and altruistic motivation, pleasure-seeking and normative behavior, and individual and group interests, with the id matching the first half of each pair",
                "The basic truth behind the ego/superego side of the discourse is the delayed nature of benefits from social relationships",
                "Malcolm Slavin suggests selfish motives may be repressed by children as a way to stay in the good graces of parents, and retrieved moments later when the need to please passes",
                "We may repress the memory of a friend's transgressions, a wise trick if the friend is of high status, and the memory can resurface should the friend's status plummet",
                "A man can better convince a woman of his future devotion if he isn't vividly imagining sexual intercourse with her, an impulse that can blossom later once the ground is prepared",
                "Nesse and Lloyd note that several ego defenses are intelligible in Darwinian terms, including 'identification' and 'introjection' as ways of cozying up to high-status people, and 'rationalization', the concoction of pseudoexplanations that conceal our true motives",
            ],
        ),
        "dialogue": (
            "Dialogue: The Ego-Defense Debriefing",
            "Run the same memory problem twice: Darwin's golden rule about forgetting inconvenient facts, first through Freud's arena of opposing tendencies, then through the Darwinian account that explains inconvenient facts, grievances, and humiliations separately. Interrogate both interpreters until each admits what its model cannot explain.",
            "A two-sided confession booth with a memory card pinned between them, one side labeled 'One Arena', the other 'Three Accounts', and both hands pointing at the same golden rule quoted in Darwin's handwriting.",
            [
                "Freud cited Darwin's golden rule as evidence of the Freudian tendency to ward off from memory that which is unpleasant, a tendency he took to be broad and general",
                "Freud himself acknowledged, only a few sentences after citing Darwin's rule, that painful memories are sometimes the very hardest to forget, particularly the recollection of grievances or humiliations",
                "Freud's answer was that the tendency to discard painful memories is sometimes successful and sometimes not, the mind being an arena, a sort of tumbling-ground, where opposing tendencies collide",
                "Evolutionary psychologists can handle the question more deftly because they don't have a simple, schematic view of the mind but believe it was jerry-built over the eons for a host of different tasks",
                "Darwinians explain three memory questions separately: forgetting facts inconsistent with our theories eases arguing with force and conviction, since arguments often had genetic stakes in the environment of our evolution",
                "Remembering grievances may bolster haggling by reminding people of reparations we are owed, and a well-preserved grievance may ensure the punishment of our exploiters",
                "The uncomfortable persistence of humiliations dissuades us from repeating status-lowering behaviors, and great humiliations may adaptively lower self-esteem",
                "Freud's model of the mind may have been, believe it or not, insufficiently labyrinthine: the mind has more dark corners than he imagined and plays more little tricks on us",
                "Freud misunderstood evolution in basic and elementary ways, putting much emphasis on the Lamarckian idea that traits acquired through experience get passed on biologically",
                "Genes that specifically encouraged a death instinct, penis envy, or the Oedipus complex wouldn't exactly be destined to spread through a hunter-gatherer population overnight",
                "Martin Daly and Margo Wilson argue that Freud conflated several Darwinian dynamics in the Oedipal conflict, including competition with fathers for women in polygynous societies, but not the mother, since incest often produces deficient offspring",
                "At a younger age a child's paternal conflict may be over the mother's valuable time and attention rather than sex, with the son's genetic interest calling for delaying the arrival of a sibling",
            ],
        ),
        "audit": (
            "Audit: The Pain Prescription Audit",
            "Audit the pains in Darwin's life - the awkwardness that kept him from fighting at school, the craving for reassurance, the exaggerated respect for authority, the motherless childhood - and for each write a prescription note: pain as design, pain as parental tuning, or pain as price of the genetic program. Then decide what the audit implies for psychiatry.",
            "A Victorian apothecary where each of Darwin's discomforts is a bottle on the shelf, and the labels the pharmacist writes read 'Design', 'Parental Tuning', and 'Price', with a mortar and pestle grinding out the words 'knobs and tunings'.",
            [
                "Evolutionary psychologists must abandon the assumption, implicit in Freud's thought and most everyone else's, that pain is a symptom of something abnormal, a sign that things have gone awry",
                "Randolph Nesse has stressed that pain is part of natural selection's design, which is not of course to say that it's good",
                "Vast quantities of pain were generated by traits that helped make Darwin an effective animal: his overactive conscience, his relentless self-criticism, his craving for reassurance, his exaggerated respect for authority",
                "It may be a mistake to assume the young Darwin didn't himself encourage his father's painful influence, since people may well be designed to absorb painful guidance that conduces to genetic proliferation",
                "Many things that look like parental cruelty may not be an example of Trivers's parent-offspring conflict, in which some psychic fine-tuning is for the genetic benefit of the parent rather than the child",
                "Insecurity may be an adaptation for those who can't ascend the social hierarchy through brute force, good looks, or charisma, driving them instead to a redoubled commitment to reciprocal altruism",
                "The stereotypes of the arrogant, inconsiderate jock and the ingratiating, deferential wimp are no doubt overdrawn, but they may reflect a statistically valid correlation that makes Darwinian sense",
                "Darwin wrote that at grade school he could not get up his courage to fight, and a schoolmate recalled he was 'pleased to do any little acts to gratify his fellows'",
                "Sharp intellectual self-scrutiny might grow out of early social frustration, as children to whom status doesn't come naturally work harder to become rich sources of information",
                "Darwin's two basic kinds of self-doubt - moral and intellectual - may be two sides of the same coin, both manifestations of social insecurity designed to make him a prized social asset",
                "Thomas Huxley spoke of Darwin's 'acute sensitiveness to praise and blame', which can account for his fastidiousness in both realms and may be rooted in a single principle of mental development",
                "The early death of Darwin's mother is fertile ground for speculation, since in the ancestral environment complacency was a luxury that a motherless child could not afford",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Freudian or Darwinian Cynicism",
            "Sort a dozen claims about human motivation - the person is an unwitting accomplice, the unconscious hides selfishness by design, repression is a recent invention of civilization, the commonsense order of judgment and behavior is backward - into Freudian, Darwinian, or both. For each, state what the two schools would each say about the function of pain.",
            "Two circus mirrors facing each other across a hall of judgment, a claimant standing between them; one mirror stretches the figure into a Victorian consulting room, the other into an African savanna, and neither image is ever quite the same shape.",
            [
                "Like the new Darwinism, Freudian thought finds sly unconscious aims in our most innocent acts, and it sees an animal essence at the core of the unconscious",
                "Both Darwinian and Freudian cynicism carry less bitterness than garden-variety cynicism because their suspicion of motives is in large part suspicion of unconscious motives, making the conscious person a kind of unwitting accomplice",
                "To the extent that pain is the price paid for internal subterfuge, the person may be worthy of compassion as well as suspicion, and everyone comes out looking like a victim",
                "Freud thought of himself as a Darwinian and tried to look at the human mind as a product of evolution, which would forever endear him to evolutionary psychologists",
                "Freud rightly saw the mind as a place of turbulence, much of it subterranean, with an animal of ultimate ruthlessness born into a complex and inescapable social web",
                "In Civilization and Its Discontents Freud wrote that humans are not gentle creatures and quoted homo homini lupus - man is a wolf to man",
                "Freud's claim that primitive man was better off knowing no restrictions of instinct is a myth: even chimpanzees must weigh predatory impulses against the fact that another chimp can be a potential helper",
                "Male chimpanzees and bonobos find their sexual impulses frustrated by females that demand food and favors in exchange for sex, and growing male parental investment extended these restrictions well before modern cultural norms",
                "Repression and the unconscious mind are products of millions of years of evolution, well developed long before civilization further complicated mental life",
                "The Darwinian notion of the unconscious is more radical than the Freudian one: the sources of self-deception are more numerous, diverse, and deeply rooted, and the line between conscious and unconscious is less clear",
                "If Freud stressed people's difficulty in seeing the truth about themselves, the new Darwinians stress the difficulty of seeing truth, period, coming close to calling into question the very meaning of the word truth",
                "By Darwinian lights, moral, political, and even academic discourse are raw power struggles in which a winner will emerge but there's often no reason to expect that winner to be truth",
            ],
        ),
        "boss": (
            "Boss Battle: The Unconscious Mind Duel",
            "Confront Freud in the arena of his own tumbling-ground, defending the Darwinian unconscious against his one-arena model. Trade objections: his death instinct, his penis envy, his Oedipus complex, his claim that civilization is the source of repression - and end the duel by deciding whether 'moral' can be anything but a joke.",
            "A Viennese lecture hall collapsing into a savanna plain, two podium-mounted brains arguing across the ruins, each claim landing as a chess piece on a board that redraws itself between every move.",
            [
                "Freud described Freudianism as an attempt to prove to the ego that it is not even master in its own house, content with the veriest scraps of information about its unconscious mind",
                "By Darwinian lights Freud's wording gives too much credit to the self, since the delusion seems so pervasive that the usefulness of thinking about any distinct core of honesty falls into doubt",
                "The commonsense picture - we make judgments and then behave accordingly - is not just wrong but backward: we believe the things about morality, personal worth, and even objective truth that lead to behaviors that get our genes into the next generation",
                "What is in our genes' interests is what seems 'right' - morally right, objectively right, whatever sort of rightness is in order",
                "Postmodern cynicism differs from modern cynicism in that it can't take ideals seriously in the first place: the prevailing attitude is absurdism, since everyone is equally ridiculous and there is no moral basis for passing judgment",
                "Deconstructionist literary theorists, anthropologists, and adherents of critical legal studies already view human communication as discourses of power, which the new Darwinism underscores",
                "Avant-garde irony has become the order of the day: cutting-edge talk shows joke about cue cards written on cue cards and film cameras filming cameras",
                "What is to be avoided at all costs in the postmodern age is earnestness, which betrays an embarrassing naivete",
                "The question of whether the human animal can be a moral animal, which modern cynicism greets with despair, may seem increasingly quaint after the new Darwinism takes root",
                "Freud's best insight was sensing the paradox of being a highly social animal: at our core libidinous, rapacious, and selfish, yet having to reach our animal goals via a tortuous path of cooperation, compromise, and restraint",
                "Freud's scorecard is not bad: he and his followers identified lots of mental dynamics that may have deep evolutionary roots, though his diagnosis went misleading when it pitted self against civilization instead of self against society",
                "If present-day Freudians recast their ideas using kin selection, parent-offspring conflict, parental investment, reciprocal altruism, and status hierarchy, they may save Freud's name from the eclipse it will probably suffer if the task is left to Darwinians",
            ],
        ),
    },
    {
        "num": 16,
        "title": "Chapter 16: Evolutionary Ethics",
        "pages": "338-357",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Moral Relativity Scanner",
            "Scan a gallery of moral scenes from the Descent of Man onward: the bee-society thought experiment, the Edinburgh Review's prophecy, the retributive impulse, and the love that survives doubt. For each scene, name the moral sentiment on display and trace it to the Darwinian currency - status, reciprocal altruism, or kin selection - that built it.",
            "A planetarium of moral feelings where each sentiment floats as a constellation labeled with its organic history, and a scanner cursor reads out 'vestige of organic history on a particular planet' over every light.",
            [
                "In 1871, twelve years after the Origin, Darwin published The Descent of Man, setting out his theory of the 'moral sentiments' without trumpeting that the very sense of right and wrong is an arbitrary product of our peculiar evolutionary past",
                "Darwin wrote that if human society were patterned after bee society, our unmarried females would think it a sacred duty to kill their brothers, and mothers would strive to kill their fertile daughters, and no one would think of interfering",
                "The Edinburgh Review warned that if Darwin's theory were right, our moral sense would turn out to be a mere developed instinct, and a revolution in thought would shake society to its very foundations",
                "Sympathy, empathy, compassion, conscience, guilt, remorse, and even the sense of justice can now be viewed as vestiges of organic history on a particular planet",
                "We cannot take solace, as Darwin did, in the mistaken belief that these things evolved for the good of the group: our ethereal intuitions about right and wrong are weapons designed for daily, hand-to-hand combat among individuals",
                "By the lights of the new paradigm, a moral code is a political compromise molded by competing interest groups, shaped disproportionately by the parts of society where power resides",
                "Herbert Spencer, generally regarded as the father of social Darwinism, wrote that the poverty of the incapable and the shoulderings aside of the weak by the strong are the decrees of a large, farseeing benevolence - in 1851, eight years before the Origin",
                "John D. Rockefeller said the withering of weak companies in a laissez-faire economy was 'the working-out of a law of nature and a law of God'",
                "Darwin found crude moral imputations to his theory laughable, noting a Manchester squib showing he had proved 'might is right' and therefore Napoleon was right",
                "Spencer was not as heartless as his severe utterances imply: he emphasized the goodness of altruism and sympathy, was a pacifist, and believed evolution moved species toward longer, more comfortable lives and secure rearing of offspring",
                "In 1903 G. E. Moore decisively assaulted the idea of drawing values from evolution or any aspect of observed nature, labeling the error the 'naturalistic fallacy'",
                "Darwin's moral sentiments, designed ultimately to serve selfishness, renounced this criterion of design as soon as it became explicit - the very first organism ever to see its creator did precisely that",
            ],
        ),
        "dialogue": (
            "Dialogue: The Ichneumonid Interrogation",
            "Interview Charles Darwin at Down House in 1860, the year after the Origin: press him on his letter to Asa Gray about parasitic wasps feeding within living caterpillars and the cat playing with mice, then have him meet John Stuart Mill and G. E. Moore to defend - and quibble with - the greatest-happiness principle.",
            "A lamplit parlor where a parasitic wasp is pinned under glass on the table between two teacups, and the letter about the Ichneumonidae floats in the air above the conversation.",
            [
                "Darwin wrote to Asa Gray in 1860 that he could not see evidence of design and beneficence on all sides, since there seemed too much misery in the world, and he could not persuade himself that a beneficent and omnipotent God would have designedly created the Ichneumonidae with the express intention of their feeding within the living bodies of caterpillars",
                "John Stuart Mill's essay 'Nature' argued that if there are any marks of special design in creation, one of the things most evidently designed is that a large proportion of all animals should pass their existence in tormenting and devouring other animals",
                "Mill wrote that nature impales men, breaks them as if on the wheel, and has hundreds of other hideous deaths in reserve, with supercilious disregard of both mercy and justice",
                "Mill concluded that if Nature and Man are both the works of a Being of perfect goodness, that Being intended Nature as a scheme to be amended, not imitated, by Man",
                "Mill dismissed moral intuition as a device 'for consecrating all deep-seated prejudices'",
                "Mill argued the question of whether nature deserves slavish emulation boils down to whether nature appears to be the handiwork of a benevolent and omnipotent God",
                "Both Darwin and Mill believed that in a universe which for all we know is godless, one reasonable place to find moral guidance is utilitarianism",
                "Mill's Utilitarianism, published as articles in Fraser's magazine in 1861, two years after On Liberty and the Origin, became the doctrine's classic defense",
                "The idea of utilitarianism is simple: things are good to the extent they raise the amount of happiness in the world and bad to the extent they raise the amount of suffering",
                "Darwin quibbled with the formulation, distinguishing the general good or welfare of the community from the general happiness, but conceded that since happiness is an essential part of the general good, the greatest-happiness principle indirectly serves as a nearly safe standard of right and wrong",
                "Mill never professed to have proven the goodness of pleasure, believing 'first principles' beyond proof, and argued pragmatically that we all conduct our lives as if happiness were the object of the game",
                "Mill wrote that the golden rule of Jesus of Nazareth contains the complete spirit of the ethics of utility: to do as one would be done by, and to love one's neighbour as oneself",
            ],
        ),
        "audit": (
            "Audit: The Moral Ledger Audit",
            "Audit the retributive impulse as an accounting system: verify the claim that grievances aren't tallied with divine objectivity, discount moral indignation by 50 percent, and run the archbishop-versus-chambermaid calculation to see who a sober utilitarian should save from the burning building. Log every entry the genes have slanted.",
            "A courtroom of scales where the ledger of grievances glows with a built-in bias toward the self, and a calculator stamped 'Utilitarian Audit' reweights each entry while a burning building flickers in the window.",
            [
                "The retributive impulse, one of the basic governors of reciprocal altruism, evolved not for the good of the species or the tribe but for the good of the individual, and its ultimate function is to get the individual's genetic information copied",
                "The aura of reverence surrounding the retributive impulse is harder to credit once it is seen to be a self-serving message from our genes rather than a beneficent message from the heavens",
                "There is a defense of retribution in moral terms: it helps solve the 'cheater' problem that any moral system faces, since people seen to take more than they give are thereafter punished and discouraged from always being a door holdee",
                "Even though the retributive impulse wasn't designed for the good of the group, it can and often does raise the sum of social welfare, keeping people mindful of the interests of others",
                "Our moral accounting system is wantonly subjective, informed by a deep bias toward the self: we tend to find our rivals morally deficient, our allies worthy of compassion, our compassion geared to their social status, and the socially marginal ignored altogether",
                "We are right to say we never dislike people without a reason, but the reason is often that it is not in our interests to like them, and the feeling of 'rightness' accompanying our dislike is just window dressing",
                "Love, like hate, exists only by virtue of its past contribution to genetic proliferation, but it survives doubt in good shape because it makes us further the happiness of others, and makes the sacrifice feel good, magnifying total happiness",
                "The moral evaluation of love is the same as the evaluation of retribution: clear away the window dressing of intuitive rightness and soberly assess the effect on overall happiness",
                "The ultimate genetic selfishness underlying an impulse is morally neutral, grounds neither for embracing the impulse nor for condemning it",
                "The new paradigm will tend to lead the thinking person toward love and away from hate, because it helps us judge each feeling on its merits, and on grounds of merit love usually wins",
                "A good rule for engaging the enemy is to discount moral indignation by about 50 percent, mindful of its built-in bias, and to be similarly suspicious of moral indifference to suffering",
                "Thomas Huxley's 1893 Oxford lecture 'Evolution and Ethics' declared that the ethical progress of society depends not on imitating the cosmic process, still less in running away from it, but in combating it",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Utilitarian or Retributive",
            "Sort a dozen judgments - punishing to deter future crime, punishing to satisfy a sense of justice, saving an archbishop before a chambermaid, discounting high-status indulgence, the Texas mother's cheerleading murder plot - into utilitarian warrant, retributive impulse, or window dressing. State the effect on overall happiness for each.",
            "A twin-pan scale in a philosophy seminar room where each moral claim drops into one pan labeled 'Happiness Calculus' and the other labeled 'Retributive Aura', and the needle reveals which pan the genes actually built.",
            [
                "Utilitarianism's foundation consists largely of the simple assertion that happiness, all other things being equal, is better than unhappiness",
                "Belief in the goodness of happiness and the badness of suffering is increasingly the only basic part of moral discourse that everyone shares; thereafter fragmentation ensues over divinely imparted or seemingly self-evident truths",
                "Mill argued that the greatest-happiness principle has had a large share in forming the moral doctrines even of those who most scornfully reject its authority",
                "A utilitarian can fiercely defend 'inviolable' values so long as their violation would plausibly lead to big problems in the long run, making such a person a 'rule' utilitarian, as Mill seems to have been, rather than an 'act' utilitarian",
                "The argument for utilitarian morality can be put concisely: widely practiced utilitarianism promises to make everyone better off, and so far as we can tell, that's what everyone wants",
                "Thanks to non-zero-sumness, everyone's happiness can in principle go up if everyone treats everyone else nicely, as with the example of holding open a door for the person behind you",
                "The standard answer to whether you would save an archbishop or a chambermaid from a burning building is to save the archbishop, even if the chambermaid is your mother, since he will do more good in the future",
                "Most high-status people are not archbishops, there is little evidence they have any proclivity toward conscience or sacrifice, and the new paradigm stresses they attained their status for themselves and can be expected to use it accordingly",
                "Status merits much less indulgence than it generally gets: it is only human nature to extend deference to Mother Teresa and Donald Trump, and in the second case this part of human nature is perhaps unfortunate",
                "The pretense of selflessness is about as much a part of human nature as its frequent absence, as we dress ourselves up in tony moral language and self-righteously decry selfishness in others",
                "The feeling of moral 'rightness' is something natural selection created so that people would employ it selfishly; morality, you could almost say, was designed to be misused by its own definition",
                "Darwin wrote that a moral being is one who is capable of comparing his past and future actions or motives and of approving or disapproving of them, and that we have no reason to suppose any of the lower animals have this capacity",
            ],
        ),
        "boss": (
            "Boss Battle: The Engagement with the Enemy",
            "Go into battle against the cosmic process armed with Huxley, Singer, and Williams: the enemy is natural selection itself, worse than Huxley thought and equipped with a longer list of vices. Win the engagement by discounting your own righteous indignation, and finish by judging whether we are naturally moral animals or merely potentially moral ones.",
            "A field hospital on the edge of a jungle where the enemy's fortifications are made of fangs, wasps, and playing cats, and the medics' instruction manual reads 'Understand the enemy to defeat the enemy'.",
            [
                "Peter Singer, one of the first philosophers to take the new Darwinism seriously, noted that the more you know about your opponent, the better your chances of winning",
                "George Williams embraced both Huxley's and Singer's points, writing that his revulsion at natural selection's values is even greater than Huxley's, based on the more extreme contemporary view of natural selection as a process for maximizing selfishness",
                "If the enemy is worse than Huxley thought, there is a more urgent need for biological understanding",
                "A powerful person who uses his station humanely is a valuable social asset and thus may merit special treatment, so long as the treatment facilitates such conduct",
                "People prone to grow indignant about the behavior of distinct groups whose interests conflict with their own should be especially vigilant, as should those inconsiderate of low-status people and exceedingly tolerant of high-status people",
                "Selfishness seldom presents itself to us in naked form: belonging to a species whose members justify their actions morally, we are designed to think of ourselves as good and our behavior as defensible, even when this is objectively dubious",
                "The new paradigm strips self-absorption of its noble raiment, making the illusion harder to buy by exposing the biological machinery behind it",
                "To ponder natural selection is to be staggered by the amount of suffering and death that can be the price for a single, slight advance in organic design, whose purpose is often to make other animals suffer or die more surely",
                "Organic design thrives on pain, and pain thrives on organic design",
                "If a parasitic wasp or a cat playing with mice embodies nature's values, so much the worse for nature's values: Darwin rejected the criterion of design as soon as it became explicit",
                "Even people who don't buy utilitarianism should at least be consistent in light of the new Darwinism: either subject all that moral posturing to skeptical scrutiny or quit the posturing",
                "We are potentially moral animals - which is more than any other animal can say - but we aren't naturally moral animals: to be moral animals, we must realize how thoroughly we aren't",
            ],
        ),
    },
    {
        "num": 17,
        "title": "Chapter 17: Blaming the Victim",
        "pages": "357-377",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Serotonin Crime Scanner",
            "Scan a newsreel of the biology of behavior: low serotonin and crime, oxytocin and love, Ecstasy and benignity, endorphins and gambling, the Twinkie defense and premenstrual syndrome. For each frame decide whether the chemical finding removes the act from the realm of volition, and log who stands to benefit from the removal.",
            "A courtroom projector where each headline is a slide: a brain scan glows under the counsel's table, and a defense lawyer's hand is already reaching for the next exhibit before the slide even clicks into place.",
            [
                "Today scientists link crime to low serotonin, molecular biologists isolate genes that incline the brain toward mental illness, oxytocin is found to underlie love, and the drug Ecstasy induces a deeply benign state of mind",
                "The picture that we are all machines, pushed and pulled by forces we can't discern but that science can, though utterly biological, has no special connection with evolutionary biology, since these mind-control elements are studied mostly without inspiration from Darwinism",
                "Low serotonin seems to encourage crime by reflecting a person's perception of closed routes to material success, natural selection possibly 'wanting' that person to take alternate routes",
                "Serotonin and Darwinism together could bring sharp testament to vague complaints about how criminals are 'victims of society': a young inner-city thug pursues status by the path of least resistance, compelled by forces just as strong as the ones that made you what you are",
                "You may see, on reflection, that you would have been the purse snatcher had you been born in his circumstances",
                "The most famous erosion of volition is the 'Twinkie defense', in which a lawyer convinced a California jury that a junk-food diet left his client with a diminished capacity to premeditate murder",
                "In both British and American courts, women have used premenstrual syndrome to partly insulate themselves from criminal responsibility",
                "Martin Daly and Margo Wilson rhetorically asked in their book Homicide whether a 'high-testosterone' defense of male murderers can be far behind",
                "Posttraumatic stress disorder, a defense lawyer's favorite malady, is said to encompass everything from battered-woman syndrome to depression-suicide syndrome, in which people bungle crimes with the unconscious goal of being caught",
                "An expert witness touting a conjectured 'action-addict syndrome' traced the problem to endorphins, which the criminal desperately craves and obtains via crime",
                "Compulsive gamblers have abnormally high levels of endorphins in their blood when they gamble, but we all do things to get endorphins, from jogging to sex, and our levels rise when we do",
                "Every time a behavior is found to rest on chemistry, someone - typically a defense lawyer - tries to remove it from the realm of volition",
            ],
        ),
        "dialogue": (
            "Dialogue: The Twinkie Defense Cross-Examination",
            "Try the case: a man has murdered, and his lawyer pleads diminished capacity from a junk-food diet while the prosecutor pleads free will. Cross-examine both, then call Darwin's notebooks as a witness on whether anyone deserves blame or credit for anything, and let the jury decide whether the verdict erodes society's moral fiber.",
            "A wood-paneled California courtroom where a box of Twinkies sits on the evidence table beside a facsimile of Darwin's 'Old & Useless Notes', and the judge's gavel hovers over a scale that only has one pan.",
            [
                "Darwin addressed the deepest questions of moral responsibility more than a century ago in thoroughly acute and humane fashion, but he never published his thoughts, which remained in his private writings labeled 'Old & USELESS notes about the moral sense & some metaphysical points'",
                "Darwin was a scientific materialist who didn't think any nonphysical forces were needed to explain human behavior or anything else in the natural world",
                "'[O]ne doubts existence of free will,' Darwin wrote in his notebooks, because 'every action determined by hereditary constitution, example of others or teaching of others'",
                "Darwin saw how heredity and environment have their combined effect: by determining a person's physical 'organization', which in turn determines thought and feeling and behavior",
                "'My wish to improve my temper, what does it arise from but organization,' Darwin asked, noting that organization may have been affected by circumstances, education, and choice",
                "All influences on human behavior, environmental as well as hereditary, are mediated biologically, since whatever physical organization your brain has at a moment determines how you will respond",
                "Darwin had a strikingly twentieth-century explanation of why we feel as if we're making free choices: our conscious mind isn't privy to all the motivating forces",
                "'The general delusion about free will obvious. - because man has power of action, & he can seldom analyse his motives... he thinks they have none,' Darwin wrote",
                "'This view should teach one profound humility, one deserves no credit for anything,' Darwin wrote in his notes, '[N]or ought one to blame others'",
                "Darwin saw that determinism, by eroding blame, threatens society's moral fiber, but wasn't too worried about the doctrine spreading, since most people aren't thoughtful scientific materialists",
                "Darwin took comfort in the hope that his insights about determinism would never become common knowledge",
                "We must view a wicked man, Darwin wrote, 'like a sickly one', since it would 'be more proper to pity than to hate & be disgusted'",
            ],
        ),
        "audit": (
            "Audit: The Blame Calculus Audit",
            "Audit the legal system's handling of blame: compare the two utilitarian questions - did the defendant commit the crime, and what is the practical effect of punishment - with the messy question of volition. Run the desert-island case of the forgotten ninety-five-year-old escapee through both systems, and log where 'free will' has been a useful fiction and where it is outliving its usefulness.",
            "A judge's chambers where the penal code's five stated functions of punishment are pinned to a board, and the word 'volition' is being slowly crossed out and replaced with two questions written in utilitarian ink.",
            [
                "In American law, punishment has several explicit functions, most of them strictly practical: keeping the criminal off the streets, discouraging him from crime after release, discouraging others who witness his fate, and rehabilitating him - all of which a utilitarian would applaud",
                "One of the stated functions of punishment is strictly 'moral': retribution, pure and simple, considered good even if it serves no discernible purpose",
                "If on a desert island you happen upon a ninety-five-year-old prison escapee whose existence was long ago forgotten, retributive doctrine says you will serve the cause of justice by somehow making him suffer",
                "Even now retribution is one reason courts spend so much time deciding whether people 'volitionally' committed a crime, as opposed to being insane, temporarily insane, or having diminished capacity",
                "If utilitarians ran the world, messy words like 'volition' would never enter the picture; the courts would ask two questions: did the defendant commit the crime, and what is the practical effect of punishment on the criminal and on other would-be criminals",
                "When a woman who has been beaten or raped by her husband kills him, the question wouldn't be whether she has a disease called battered-woman syndrome, but whether punishment would prevent these people, and similarly situated people, from committing crimes in the future",
                "Daly and Wilson write that the enormous volume of mystico-religious bafflegab about atonement and penance and divine justice is the attribution to higher, detached authority of what is actually a mundane, pragmatic matter: discouraging self-interested competitive acts by reducing their profitability to nil",
                "'Free will' has been a fairly useful fiction, a rough proxy for utilitarian justice",
                "The time-wasting debates now in progress - Is alcoholism a disease? Are sex crimes an addiction? Does premenstrual syndrome nullify volition? - suggest that 'free will' is beginning to outlive its usefulness",
                "As the biological underpinnings of behavior come into view, we must get used to the idea of holding robots responsible for their malfunctions, so long as this accountability will do some good",
                "'[I]t is right to punish criminals; but solely to deter others,' Darwin wrote, in the spirit of the time-honored utilitarian prescription",
                "There is nothing good, in itself, about retribution: the suffering inflicted on wrongdoers is just as sad as the suffering of everyone else, and counts equally in the grand utilitarian calculus, warranted only when outweighed by the growth it brings in the welfare of others through the prevention of future crime",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Genetic or Environmental Determinism",
            "Sort a dozen accusations and defenses from the sociobiology wars - genetic determinism, cultural determinism, biological determinism, knobs and tunings, free will - into their actual referents, and for each state whether the insertion of the word 'genetic' makes any difference to the determinism in question.",
            "A philosopher's dartboard where each dart is labeled with a determinism, and the board rotates to reveal that all the darts are sticking into the same target.",
            [
                "In the mid-1970s, the book Sociobiology gave the new Darwinian paradigm its first burst of publicity and its author, E. O. Wilson, his first burst of public abuse: he was called a racist, a sexist, a capitalist imperialist",
                "Darwinians were accused of 'genetic determinism', which was said to leave no room for free will, and they then accused their accusers of confusion, since Darwinism rightly understood posed no threat to lofty political and moral ideals",
                "Some fears on the left have a firm grounding even after the confusion is dispelled, and the question of moral responsibility in evolutionary psychology is large enough to alarm the right as well as the left",
                "The phrase 'genetic determinism' exudes ignorance as to what the new Darwinism is about: everyone is a victim not of genes but of genes and environment together, knobs and tunings",
                "A stereo has no more control over its tunings than over the knobs it was born with, so whatever importance you attach to the two factors, there's no sense in which the stereo is to blame for its music",
                "The fears of 'genetic determinism' current in the 1970s were unfounded, but the fears of 'determinism' weren't",
                "The then-reigning philosophy of the social sciences was 'cultural determinism' or 'environmental determinism', and when it comes to free will, and thus to blame and credit, determinism is determinism is determinism",
                "Richard Dawkins noted that whatever view one takes on the question of determinism, the insertion of the word 'genetic' is not going to make any difference",
                "Any force that is not in the genes or the environment is outside of physical reality as we perceive it, beyond scientific discourse - though this doesn't mean it doesn't exist",
                "Though some on the far right might be thrilled to hear that businessmen can't help but exploit laborers, they would be less happy to hear that criminals can't help but commit crimes",
                "The sense in which E. O. Wilson is a 'biological determinist' is the sense in which B. F. Skinner was one, which is the sense in which all psychology is biologically determinist",
                "Evolutionary psychology professes to be the surest path to a complete explanation of human behavior, and to know all is to forgive all: once you see the forces that govern behavior, it's harder to blame the behaver",
            ],
        ),
        "boss": (
            "Boss Battle: The Metanorm Tribunal",
            "Preside over the tribunal where society punishes not only the violator but those who tolerate the violator: decide what happens to Dickens's friends if he goes public with his mistress, and judge whether the spectators' rage - which the new determinism may soften into bemused detachment - is what holds the moral order together.",
            "A Victorian drawing room arranged as a courtroom of public opinion, where every guest who fails to cut a known adulterer is itself put on trial, and the room's mirrors begin watching the audience with the detachment of absurdists.",
            [
                "Charles Dickens was afraid to take up publicly with his mistress not because his wife would have punished him, but because he was afraid of infamy",
                "Effective moral codes fight fire with fire: whenever a strong animal impulse is consistently thwarted by a moral code, violation would bring low repute, the avoidance of which is also a strong animal impulse",
                "Robert Axelrod finds that robust moral codes rest not just on norms but on 'metanorms': society disapproves not only of the code's violators but also of those who tolerate violators by failing to disapprove",
                "Had Dickens gone public with his adultery, his friends might well have had to cut ties with him or else suffer punishment themselves for failing to punish",
                "The rage of spectators may wane as they come to believe that male philandering is 'natural', a biochemical compulsion, and that the wife's retributive furor is an arbitrary product of evolution",
                "Life - the life, at least, of those other than ourselves, our kin, and our close friends - becomes a movie that we watch with the bemused detachment of an absurdist, the specter of a thoroughly postmodern morality",
                "The basic paradox - the intellectual groundlessness of blame and the practical need for it - is something few people seem eager to acknowledge",
                "An anthropologist made two statements about divorce, that people can help programmed behaviors and that divorce is a natural pattern people needn't feel failure about, and each is defensible, but you can't have it both ways",
                "To tell people they're not to blame for past mistakes is to make future mistakes more likely: the truth is hardly guaranteed to set us free",
                "In Darwin's day men were told that animal impulses are formidable foes but can, with constant and arduous effort, be defeated, and this then became, for many men, the truth: free will was, in an important sense, created by their belief in it",
                "The self-disciplined Victorians don't upset the doctrine of determinism; they were just products of their environment, of a time and place where belief in the possibility of self-control was in the air",
                "Morality is the cheapest and least creepy way to harvest the fruits of non-zero-sumness that aren't harvested by kin-selected or reciprocal altruism, since a strong moral code uniquely offers the more elusive benefits without lots of police",
            ],
        ),
    },
    {
        "num": 18,
        "title": "Chapter 18: Darwin Gets Religion",
        "pages": "377-407",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Demon's First Cigarette",
            "Scan a gallery of temptation scenes drawn from the world's scriptures - Satan, Mara with his daughters Rati and Raga, the demon and the drug dealer sharing the same opening line - and in each identify the lure, the stage of habituation it begins, and the reward system it subverts.",
            "A scripture-scripted bazaar where every stall sells the same first taste, and a serpent's shadow coils around each purchase while the phrase 'Just try a little; it will feel good' echoes across the booths.",
            [
                "One great theme of the great religions is demonic temptation: an evil being tries, in the guise of innocence, to entice people into seemingly minor but ultimately momentous wrongdoing",
                "In the Bible and the Koran there is Satan, and in Buddhist scripture there is the arch-tempter Mara, who insidiously deploys his daughters Rati (Desire) and Raga (Pleasure)",
                "Demonic temptation captures nicely the dynamics by which habits are acquired: slowly but surely",
                "Natural selection 'wants' men to have sex with an endless series of women, realizing this goal with a subtle series of lures that can begin with the mere contemplation of extramarital sex and then grow steadily more powerful and ultimately inexorable",
                "Donald Symons observed that Jesus said 'Whosoever looketh on a woman to lust after her hath committed adultery with her already in his heart' because he understood that the function of the mind is to cause behavior",
                "It is no coincidence that demons and drug dealers use the same opening line ('Just try a little; it will feel good') or that religious people often see demons in drugs",
                "Habituation to any goal - sex or power, say - is literally an addictive process, a growing dependence on the biological chemicals that make these things gratifying",
                "The more power you have, the more you need, and any slippage will make you feel bad, even if it leaves you at a level that once brought ecstasy",
                "Drug addiction itself is a miracle of technology that natural selection never 'meant' to encourage: an unanticipated biochemical intervention, a subversion of the reward system",
                "We were meant to get our thrills the old-fashioned way, from a hard day's work: eating, copulating, undermining rivals, and so on",
                "The concept of 'evil' is metaphorically apt, since there is indeed a force devoted to enticing us into pleasures that are in our genetic interests but don't bring long-term happiness and may bring great suffering to others - you could call it the ghost of natural selection, or more concretely our genes",
                "When the Buddha tells us to 'dig up the root of thirst' so that 'Mara, the tempter, may not crush you again and again', we are supposed to steel ourselves for the battle to come",
            ],
        ),
        "dialogue": (
            "Dialogue: The Beagle Bible Quotation",
            "Replay the slow death of Darwin's faith: the officers laughing at his quoting the Bible, the Old Testament's 'revengeful tyrant', the daydreamed manuscripts that would corroborate the Gospels, and the long plateau of theism before agnosticism. Interview him at each stage about what he can and cannot trust the evolved mind to conclude.",
            "A candlelit cabin of the Beagle where a Bible lies open beside a geological hammer, and the same hand that quotes scripture writes the words 'Disbelief crept over me at a very slow rate' in a journal.",
            [
                "When the HMS Beagle left England, Darwin was an orthodox and earnest Christian, later recalling being heartily laughed at by several of the officers, though themselves orthodox, for quoting the Bible as an unanswerable authority on some point of morality",
                "He was troubled by the Old Testament's manifestly false history of the world and its depiction of God as 'a revengeful tyrant'",
                "Though he found the moral teachings of Jesus beautiful, he saw that their 'perfection depends in part on the interpretation which we now put on metaphors and allegories'",
                "Darwin daydreamed about the unearthing of ancient manuscripts that would corroborate the Gospels, but it didn't help: 'Disbelief crept over me at a very slow rate'",
                "Having lost his Christian faith, Darwin held for many years to a vague theism, believing in a 'First Cause', a divine intelligence that had set natural selection in motion with some end in mind",
                "He began to wonder whether the mind of man, which has been developed from a mind as low as that possessed by the lowest animal, can be trusted when it draws such grand conclusions",
                "Darwin finally settled into a more or less stable agnosticism, entertaining theistic scenarios in upbeat moments, which for long periods of his life weren't common",
                "In one sense Darwin always remained a Christian: he was steeped in the moral austerity of Evangelicism, living by the tenets that found secular expression in Samuel Smiles's Self-Help",
                "Darwin lived by the creed that a man, by exercising his 'powers of action and self-denial', could stay 'armed against the temptation of low indulgences', which he called the highest stage in moral culture",
                "If Darwin was in this sense an Evangelical Christian, he could with almost equal accuracy be called a Hindu or Buddhist or Muslim, since the theme of strict self-governance appears again and again in the world's great religions",
                "Six centuries before Jesus, Lao-tzu had said, 'It is the way of the Tao... to recompense injury with kindness', and Buddhist scriptures call for an all-embracing love for all the universe, unmarred by hate within and not rousing enmity",
                "Hinduism has the doctrine of 'ahimsa', the absence of all harmful intent",
            ],
        ),
        "audit": (
            "Audit: The First Cause Audit",
            "Audit the ledger of Darwin's spiritual bookkeeping: the orthodox Christianity of the young man who quoted the Bible to the officers, the vague theism of the First Cause, the settled agnosticism, and the Evangelical austerity that never left. For each entry, note which part of the mind - evolved organ or cultural inheritance - did the accounting.",
            "A church ledger with three columns headed 'Orthodox', 'Theist', 'Agnostic', and a note in the margin in Darwin's hand: 'I am like a man who has become colour-blind'.",
            [
                "The Darwinian line on spiritual discourse is much like the Darwinian line on moral discourse: people tend to say and believe things that are in their evolutionarily ingrained interests",
                "Some religious doctrines, such as celibacy, may dramatically fail to spread genes, but the expectation is simply that the doctrines people latch on to will have a kind of harmony with the mental organs natural selection has designed",
                "Belief in an afterlife gratifies the will to survive, while other doctrines suppress thirsts so unslakable as to be a burden, such as lust",
                "Donald T. Campbell suggested that recipes for living evolved, tested, and winnowed through hundreds of generations of human social history may be regarded, on purely scientific grounds, as better tested than psychology's and psychiatry's speculations on how lives should be lived",
                "Some ideas seem to parasitize brains: they are 'viruses', as Richard Dawkins puts it, like the idea that injecting heroin is fun, which keeps infecting people by appealing to myopic cravings, rarely to their ultimate advantage",
                "Even if an idea does spread by serving people's long-term interests, the interests may be those of its sellers, not its buyers: religious leaders tend to have high status, and their preachings may be a form of exploitation, a subtle bending of the listener's will to the speaker's goals",
                "Jesus's, the Buddha's, and Lao-tzu's teachings had the effect of amplifying the power of Jesus, Buddha, and Lao-tzu, raising their stature within a growing group of people",
                "The Buddha, though born to a noble station, didn't stress supernatural authority and is said to have abandoned the trappings of status to roam the world and teach, his movement starting from scratch",
                "The great religions are at some level ideologies of self-help, and many people at various times have bought various religious doctrines under no great external coercion, presumably for some psychological payoff",
                "It would indeed be wasteful, as Campbell suggests, to throw out eons of religious tradition without inspecting it first: the sages may have been self-serving, like the rest of us, but that doesn't mean they weren't sages",
                "The Hindu scriptures teach that a single universal soul resides in everyone, and the wise man 'sees himself in all and all in him'",
                "As a metaphor for the equal sacredness - read as utilitarian worth - of every human sphere of consciousness, the Hindu teaching is profound, and as a practical rule of living - that the wise man refrains from harming others so that 'he harms not himself' - it is prescient",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Self-Help or Social Control",
            "Sort a dozen religious doctrines - the Ten Commandments, the Buddha's abandonment of status, Jesus's promises about the afterlife, Krishna's urging of Arjuna - into self-help wisdom, exploitation by high-status sages, or both, and for each state whose genes the doctrine's spread most plausibly serves.",
            "A scripture exchange floor where every holy book is also a prospectus, and a broker's ticker reads out the two theories of every doctrine's value, one column headed 'Sage' and the other 'Sheep'.",
            [
                "The Ten Commandments had a certain totalitarian authority, conveyed by the political leadership and carrying God's own signature, while Jesus, though lacking political office, regularly invoked God's endorsement",
                "The most cynical explanation of why so many sages urged an expanded moral compass is that a large compass expands the power of the sages doing the urging",
                "The Ten Commandments, with their bans on lying, stealing, and murder, made Moses' flock more manageable, and the Buddha's warnings about dogmatic squabbling kept his power base from splintering",
                "The odes to selflessness in the Bhagavad Gita come in a somewhat ironic context: Lord Krishna is spurring the warrior Arjuna toward self-discipline so that he will more effectively slaughter an enemy army, one that contains some of his own kin",
                "In Paul's Epistle to the Galatians, after singing the praises of love, peace, gentleness, and goodness, he says, '[L]et us do good unto all men, especially unto them who are of the household of faith' - wise words indeed, coming from the head of the household",
                "The case has been made that even Jesus didn't really preach universal love, that his injunctions to love your 'enemies', when appraised carefully, are seen to apply only to Jewish enemies",
                "Singer's 'expanding circle' seems an extension less of moral logic than of political reach: as social organization goes beyond the hunter-gatherer band to tribe, city-state, and nation-state, religious organization on an ever larger scale becomes feasible",
                "Appeals for brotherly love are comparable to a politician's self-serving appeals to patriotism, which are, in a way, appeals for brotherly love on a national scale",
                "Peter Singer's The Expanding Circle asks how the range of human compassion grew beyond its primitive bounds, noting that human nature long ago got people in the habit of publicly justifying their actions in objective terms",
                "Singer believes the 'autonomy of reasoning' takes over once the habit of disinterested defense of one's conduct is established: the idea grew out of self-interest but takes on a logic of its own leading to extension beyond the bounds of the group",
                "Plato urged his fellow Athenians to adopt what was then a major moral advance: Greeks should not, in war, enslave other Greeks, lay waste their lands, or raze their houses, doing these things only to non-Greeks",
                "Darwin shared the hope of expanding sympathy, writing in The Descent of Man that as small tribes unite into larger communities, the simplest reason would tell each individual to extend his social instincts and sympathies to all members of the same nation, with only an artificial barrier preventing extension to the men of all nations",
            ],
        ),
        "boss": (
            "Boss Battle: The Ultimate Mutiny",
            "Lead the mutiny the sages preached: refuse to play the game of ephemeral pleasures, dig up the root of thirst, and rebel against your creator by acting as a utilitarian magnifier. Withstand the sages' own cynicism - the opiate-of-the-masses reading of everything you preach - and win by pairing harshness toward self with leniency toward others.",
            "A candlelit mutiny on the decks of the Beagle of the soul, where the crew throws sensual pleasures overboard one by one while the ship's owner, natural selection, writes fresh promises on the water.",
            [
                "The advice of the sages - that we refuse to play the game of ever-escaping pleasures - is nothing less than an incitement to mutiny, to rebel against our creator",
                "Sensual pleasures are the whip natural selection uses to control us and keep us in the thrall of its warped values system, and to cultivate some indifference to them is one plausible route to liberation",
                "We are designed to feel that the next great goal will bring bliss, and the bliss is designed to evaporate shortly after we get there: natural selection has a malicious sense of humor, leading us along with a series of promises and then keeping saying 'Just kidding'",
                "As the Bible puts it, 'All the labour of man is for his mouth, and yet the appetite is not filled', and remarkably, we go our whole lives without ever really catching on",
                "The Buddha put his emphasis not so much on a laundry list of proscriptions as on a generally austere attitude, a cultivated indifference to material rewards and sensory pleasure: 'Cut down the whole forest of desires, not a tree only!'",
                "It remains true that pleasure is ephemeral, that its constant pursuit is not a reliable source of happiness, and that we are built not to easily grasp this fact",
                "The sages saw clearly one particular human delusion, the basic moral bias toward self, as in Jesus's 'He that is without sin among you, let him first cast a stone' and the Buddha's 'The fault of others is easily perceived, but that of one's self is difficult to perceive'",
                "Walter Houghton described the 'puritan conscience' of a Victorian man who wrote down all his sins and errors and habitually detected selfishness in every effort and resolve, an idea going back to Martin Luther, who said a saint is someone who understands that everything he does is egotistical",
                "No doctrine heightens one's consciousness of hidden selfishness more acutely than the new Darwinian paradigm: if you understand it, buy it, and apply it, you will spend your life in deep suspicion of your motives",
                "The second step after self-suspicion is to keep this newly learned cynicism from poisoning your view of everyone else: to pair harshness toward self with leniency toward others",
                "Darwin did a reasonable job of this, half-jokingly calling himself 'quite demoniacal about Owen' while meaning to try to get 'more angelic' in his feelings, coming close to the nearly impossible: detached modern cynicism toward self paired with Victorian earnestness toward others",
                "One antidote to despair over the baseness of human motivation is gratitude: at the dawn of evolution there were only two possibilities - a species with conscience, sympathy, and love grounded ultimately in genetic self-interest, or no species possessing these things at all - and the first one happened",
            ],
        ),
    },
]
