# -*- coding: utf-8 -*-
CHAPTER = {
    "num": 5,
    "title": "Hand-to-Face Gestures",
    "authors": "Allan Pease",
    "domain": "Body Language | Face and Hand Cues",
    "scrub": (
        "Scrub the Origins: The Three Wise Monkeys and the Birth of the Deceit Gestures",
        "Your mission is to scrub through the raw footage of deceit: how the hand-to-face actions of the three wise monkeys who hear, speak and see no evil form the basis of the human deceit gestures, why the young child covers his mouth, ears and eyes so openly, and how the gestures become refined and less obvious with age while still firing when a person lies, covers up or witnesses deceit. Then weigh the evidence: that a hand-to-face gesture does not always mean lying, that it must never be interpreted in isolation, and Desmond Morris's report that nurses instructed to lie to their patients showed a greater frequency of hand-to-face gestures than truth-tellers.",
        "A three-wise-monkeys triptych morphs into a montage of people covering mouth, ears and eyes, ageing from a child's obvious hands to an adult's subtle touches; a clipboard checklist ticks off deceit can mean doubt, uncertainty, lying or exaggeration, while a split-screen role-play shows lying nurses gesturing more than truth-telling nurses.",
        [
            "Recognition of the non-verbal deceit gestures can be one of the most important observation skills one can acquire.",
            "The hand-to-face actions depicted by the three wise monkeys who hear, speak and see no evil form the basis of the human deceit gestures.",
            "When we see, speak and hear untruths or deceit, we often attempt to cover our mouth, eyes or ears with our hands.",
            "If the young child tells a lie, he will often cover his mouth with his hands in an attempt to stop the deceitful words from coming out.",
            "If a child does not wish to listen to a reprimanding parent, he simply covers his ears with his hands, and when he sees something he doesn't wish to look at, he covers his eyes with his hands or arms.",
            "As a person becomes older, the hand-to-face gestures become more refined and less obvious, but they still occur when a person is lying, covering up or witnessing deceit.",
            "Deceit can also mean doubt, uncertainty, lying or exaggeration.",
            "When someone uses a hand-to-face gesture, it does not always mean that he or she is lying, but it does indicate that the person may be deceiving you.",
            "It is important that you do not interpret hand-to-face gestures in isolation, because further observation of other gesture clusters can confirm your suspicions.",
            "Dr Desmond Morris noted that American researchers tested nurses who were instructed to lie to their patients about their health in a role-play situation.",
            "The nurses who lied showed a greater frequency of hand-to-face gestures than those who told the truth to the patients.",
            "The mouth guard is one of the few adult gestures that is as obvious as a child's, with the hand covering the mouth and the thumb pressed against the cheek.",
        ],
    ),
    "dialogue": (
        "Dialogue on the Face Maskers: The Mouth Guard, Nose Touch, Eye Rub and Ear Rub",
        "Your mission is to stage a dialogue among the four maskers that hide deceit: the mouth guard whose hand covers the mouth while the brain subconsciously tries to suppress the deceitful words, the fake cough that disguises it and the Bogart gangster who used it, the speaker who signals his own lie and the listener who signals that he thinks you are lying. Then hear the nose touch argue that it is a disguised mouth guard, from the hand that pulls away at the last moment to the tingling nerve endings in the nose, and audit the eye rub, 'lying through your teeth', and the ear rub's 'hear no evil' variations from the finger drill to the earlobe pull.",
        "A round-table debate with four seats: the mouth guard with thumb pressed to the cheek, the nose touched by light strokes, the eye rubbed by a man vigorously and by a woman gently below the eye, and the ear covered by a cupped hand; a cough bubble bursts from a fake cougher, Bogart leans in from a film frame, and a chain of gestures runs from lying through your teeth to a hand bending an ear forward.",
        [
            "The brain subconsciously instructs the hand covering the mouth to try and suppress the deceitful words that are being said, and sometimes the mouth guard gesture may only be several fingers over the mouth or even a closed fist, but its meaning remains the same.",
            "Many people try to disguise the mouth guard gesture by giving a fake cough.",
            "Humphrey Bogart often used the mouth guard gesture when playing a gangster discussing criminal activities or being interrogated by the police, to show non-verbally that he was being dishonest.",
            "If the person who is speaking uses the mouth guard gesture, it indicates that he is telling a lie, while if he covers his mouth while you are speaking, it indicates that he feels you are lying.",
            "When a public speaker sees his audience all using the mouth guard gesture whilst he is speaking, it is wise to stop the presentation and ask, 'Would someone care to comment on what I've just said?'",
            "In essence, the nose touch gesture is a sophisticated, disguised version of the mouth guard gesture, consisting of several light rubs below the nose or one quick, almost imperceptible touch, and some women perform it with small discreet strokes to avoid smudging their make-up.",
            "One explanation of the nose touch is that the subconscious instructs the hand to cover the mouth but, at the last moment, the hand pulls away from the face and a quick nose touch gesture is the result.",
            "Another explanation of the nose touch is that lying causes the delicate nerve endings in the nose to tingle, and the rubbing action takes place to satisfy this feeling.",
            "The itch in a person's nose is normally satisfied by a very deliberate rubbing or scratching action, as opposed to the light strokes of the nose touch gesture.",
            "The eye rub is the brain's attempt to block out the deceit, doubt or lie that it sees or to avoid having to look at the face of the person to whom he is telling the lie, and men usually rub their eyes vigorously while women use a small, gentle rubbing motion just below the eye.",
            "'Lying through your teeth' refers to a gesture cluster of clenched teeth and a false smile, combined with the eye rub gesture and an averted gaze.",
            "The ear rub is an attempt by the listener to 'hear no evil' by putting the hand around or over the ear, and its variations include rubbing the back of the ear, the finger drill, pulling at the earlobe or bending the entire ear forward to cover the earhole.",
        ],
    ),
    "audit": (
        "Audit the Deceit Kit: Neck Scratch, Collar Pull, Fingers in the Mouth and the Pain-in-the-Neck",
        "Your mission is to audit the second drawer of the deceit kit, ticking off each exhibit: the neck scratch that scratches about five times as a signal of doubt or uncertainty, the collar pull that Morris traced to the tingling sensation lying causes in the facial and neck tissues and the trickle of sweat when the deceiver suspects he is caught, and the 'Would you repeat that, please?' probe that flushes the deceiver out. Then stamp the fingers-in-the-mouth as an unconscious return to the security of the mother's breast and a need for reassurance, and close the books on Calero's 'pain-in-the-neck' gesture, the forehead slap versus the neck slap of forgetfulness, and the habitual neck-rubber's negativity.",
        "An evidence ledger with glass exhibits: a hand scratching the neck with a tally counter stuck at five, a collar pulled away from a sweaty neck, fingers, a cigarette and a pen held in the mouth, and a palm rubbing the back of the neck labeled pain-in-the-neck; a split figure slaps his forehead and then his neck while a caption asks whether you are not intimidated or literally a pain-in-the-neck.",
        [
            "In the neck scratch gesture, the index finger of the writing hand scratches below the earlobe or the side of the neck, and the person scratches about five times, rarely less than five and seldom more than five.",
            "The neck scratch gesture is a signal of doubt or uncertainty and is characteristic of the person who says, 'I'm not sure I agree.'",
            "Desmond Morris noted that research into the gestures of those who tell lies revealed that the telling of a lie caused a tingling sensation in the delicate facial and neck tissues and a rub or scratch was required to satisfy it.",
            "Some people use the collar pull gesture when they tell a lie and suspect that they have been caught out, as if the lie causes a slight trickle of sweat to form on the neck when the deceiver feels that you suspect he is lying.",
            "The collar pull gesture is also used when a person is feeling angry or frustrated and needs to pull the collar away from his neck in an attempt to let the cool air circulate around it.",
            "When you see someone use the collar pull gesture, a question like 'Would you repeat that, please?' or 'Could you clarify that point, please?' can cause the would-be deceiver to give the game away.",
            "Morris's explanation of the fingers-in-the-mouth gesture is that the fingers are placed in the mouth when a person is under pressure, as an unconscious attempt to revert to the security of the child sucking on his mother's breast.",
            "The young child substitutes his thumb for the breast, and as an adult he not only puts his fingers to his mouth but inserts such things as cigarettes, pipes, pens and the like into it.",
            "Whereas most hand-to-mouth gestures involve lying or deception, the fingers-in-mouth gesture is an outward manifestation of an inner need for reassurance, so giving the person guarantees and assurances is appropriate when this gesture appears.",
            "An exaggerated version of the collar pull gesture is the palm rubbing the back of the neck in what Calero called the 'pain-in-the-neck' gesture, which is also used as a signal of frustration or anger.",
            "A person who uses the pain-in-the-neck gesture when lying usually avoids your gaze and looks down.",
            "A subordinate who has forgotten to complete a task non-verbally signals his forgetfulness by slapping his head, either on the forehead or the back of the neck, as if he were symbolically hitting himself, and if he slaps his forehead he signals he is not intimidated while slapping the back of the neck tells you that you are literally a 'pain-in-the-neck' for pointing out his error.",
        ],
    ),
    "matrix": (
        "Matrix Match: Context, Clusters and the Art of Misinterpretation",
        "Your mission is to build the interpretation matrix for hand-to-face gestures: drop each evidence card into its cell, the assumption that a negative thought has entered the mind into WHAT-IS-THE-NEGATIVE, the chess friend's ear rub and nose touch into PRECEDING GESTURES, the overseas applicant's eye-rubbing and nose-touching answers and the videotaped interviewee's sudden mouth guard into CONTEXT, and the head-supported boredom, finger drumming impatience and thumb-supported critical evaluation into the CLUSTER row. Then place the verdict card: only constant study and observation, with regard to context, leads to accurate assessment of someone's thoughts.",
        "A wall matrix with columns labeled WHAT IS THE NEGATIVE, PRECEDING GESTURES, CONTEXT and CLUSTER: a chess player rubs his ear as he hesitates, an applicant rubs his eyes and touches his nose under interview lights, a videotape freezes on a mouth guard, a bored listener's head sinks fully into his hand, a finger drummer taps faster and faster, and an index finger points up the cheek while the thumb supports the chin.",
        [
            "The ability to accurately interpret hand-to-face gestures in a given set of circumstances takes considerable time and observation to acquire.",
            "We can confidently assume that, when a person uses one of the hand-to-face gestures just mentioned, a negative thought has entered his mind, whether it be doubt, deceit, uncertainty, exaggeration, apprehension or outright lying.",
            "The real skill of interpretation is the ability to pick which of the negatives is the correct one, which can best be done by an analysis of the gestures preceding the hand-to-face gesture and interpreting it in context.",
            "Pease's chess-playing friend often rubs his ear or touches his nose during the game, but only when he is unsure of his next move.",
            "If, as Pease touches his chess piece, his opponent covers his mouth or rubs his nose or ear, it means that he is uncertain about the move, his next move or both, so the more moves Pease can make after a negative hand-to-face gesture, the greater his chances of winning.",
            "A young man interviewed for a position in Pease's company kept his arms and legs crossed, used critical evaluation clusters, had very little palm exposure and met the interviewer's gaze less than one-third of the time.",
            "Pease decided not to hire the overseas applicant based on what is commonly called 'gut feeling' after his answers were accompanied by a series of eye-rubbing and nose-touching gestures, and later discovered the man had given false information about his past.",
            "During a videotape role play of an interview scene, the interviewee suddenly covered his mouth and rubbed his nose when asked a question, and he said afterwards that he had been thinking of the negative answer and the interviewer's possible reaction to it at that moment.",
            "When the listener begins to use his hand to support his head, it is a signal that boredom has set in and his supporting hand is an attempt to hold his head up to stop himself from falling asleep, and extreme boredom is shown when the head is fully supported by the hand.",
            "Drumming the fingers on the table and continual tapping of the feet on the floor signal impatience rather than boredom, and the speed of the finger tap or foot tap is related to the extent of the person's impatience.",
            "Evaluation is shown by a closed hand resting on the cheek, often with the index finger pointing upwards, but should the person begin to lose interest the position will alter slightly so that the heel of the palm supports the head, and genuine interest is shown when the hand is on the cheek but not used as a head support.",
            "When the index finger points vertically up the cheek and the thumb supports the chin, the listener is having negative or critical thoughts about the speaker, and because a gesture position affects a person's attitude, the longer he holds the gesture the longer the critical attitude will remain.",
        ],
    ),
    "boss": (
        "Boss Level: From Evaluation to Decision — Reading the Chin Stroke and Closing the Sale",
        "Your mission is to defeat the final boss, the decision: hold the audience's evaluation gestures up to the light as you present your idea, then catch the moment the evaluation ceases and the hand moves to the chin for the chin-stroking gesture that signals the listener is making a decision. Then run the gauntlet of the sale: the buyer who must not be interrupted mid-stroke, the crossed arms and legs that spell 'No', the readiness gesture that ends in 'how would you prefer to pay?', the glasses frame and the pipe slipped into the mouth, the pen that stalls the decision, and the combination clusters where evaluation, boredom and decision-making blend at the same time.",
        "A boss arena that is a boardroom sale: a presenter finishes his pitch while the audience's hands move from cheeks to chins; a buyer strokes his chin and then folds his arms and sits back under a red NO stamp, while a second buyer's chin stroke flows into a readiness gesture and a green PURCHASE stamp; a glasses frame and a pipe hover at a decision-maker's mouth, and a split-frame shows evaluation and boredom blending with the head resting on the hand.",
        [
            "The next time you present an idea to a group of people, most if not all the members of your audience will bring one hand up to their faces and begin to use evaluation gestures.",
            "As you come to the conclusion of your presentation and ask for opinions or suggestions, the evaluation gestures will cease and one hand will move to the chin and begin a chin-stroking gesture.",
            "The chin-stroking gesture is the signal that the listener is making a decision.",
            "When you have asked the listeners for a decision and their gestures have changed from evaluation to decision-making, the following movements will indicate whether their decision is negative or positive.",
            "A sales person would be foolish to interrupt or to speak when a buyer begins the chin-stroking gesture after he has been asked for a decision to purchase, and his best strategy is careful observation of the buyer's next gestures, which will indicate the decision he has reached.",
            "If the chin-stroking gesture is followed by crossed arms and legs and the buyer sits back in his chair, the sales person has been non-verbally told 'No', and he would be wise to review the main points of the presentation immediately before the buyer verbalises his negative answer.",
            "If the chin-stroking gesture is followed by the readiness gesture, the sales person only needs to ask how the buyer would prefer to pay for the product and the buyer will proceed to make his purchase.",
            "Someone who wears glasses often follows evaluation clusters by removing them and putting one arm of the frame in his mouth instead of using the chin-stroking gesture when making a decision, and a pipe-smoker will put his pipe in his mouth.",
            "When a person places an object such as a pen or a finger in his mouth after having been asked for a decision, it is a signal that he is unsure and reassurance is needed because the object in his mouth allows him to stall making an immediate decision.",
            "As it is bad manners to speak with your mouth full, the buyer who places an object in his mouth feels justified in not giving an immediate decision.",
            "Occasionally the boredom, evaluation and decision-making gestures come in combinations, each showing an element of the person's attitude, and when evaluation moves to the chin with the hand also stroking the chin, the person is evaluating the proposition while making decisions at the same time.",
            "When the listener begins to lose interest in the speaker, the head begins to rest on the hand, as shown by evaluation with the head supported by the thumb while the listener becomes uninterested.",
        ],
    ),
}
