# -*- coding: utf-8 -*-
CHAPTER = {
    "num": 14,
    "title": "Body Lowering and Status",
    "authors": "Allan Pease",
    "domain": "Body Language | Status Signals",
    "scrub": (
        "Scrub the History: Highness, Lowness and the Ancient Language of Height",
        "Your mission is to scrub through the historical record of body lowering: how lowering the height of one's body in front of another person has been used to establish superior and subordinate relationships, why we call royalty 'Your Highness' and unpleasant people 'low', how the soapbox speaker, the elevated judge and the penthouse dweller each command more authority by their height, how cultures divide themselves into upper and lower classes, and how the curtsey, the inclined head and the modern salute all survive as relics of the act of making yourself smaller than the other person.",
        "A time-scrubber playhead glides over a royal court where a woman curtseys and a man removes his hat before a seated monarch, then over a rally speaker on a soapbox, a judge on a raised bench, a penthouse skyline, and a soldier's salute morphing from a deep bow into the raised hand of the modern military salute.",
        [
            "Historically, lowering the height of one's body in front of another person has been used as a means of establishing superior and subordinate relationships.",
            "We refer to a member of Royalty as 'Your Highness', whereas individuals who commit unsavoury acts are called 'low'.",
            "The protest rally speaker stands on a soapbox to be higher than everyone else, and the judge sits higher than the rest of the court.",
            "Those who live in a penthouse command more authority than those who live at ground level, and some cultures divide their social classes into the 'upper class' and 'lower class'.",
            "Despite what many people would like to believe, tall people command more authority than short people.",
            "Most women curtsey when they meet Royalty and men incline their heads or remove their hats, making themselves appear smaller than the Royal person.",
            "The modern salute is a relic of the act of body lowering.",
            "The more humble or subordinate an individual feels towards another, the lower he stoops his body.",
            "In business, the people who continually 'bow' to the management are labelled with such derogatory name tags as 'bootlickers' or 'crawlers'.",
            "Unfortunately, little can be done to help people become taller or shorter, so Pease turns to exploring some useful applications of height.",
        ],
    ),
    "dialogue": (
        "Dialogue on the Height Principle: Authority, Eye-to-Eye Contact and Shrinking Yourself",
        "Your mission is to stage a dialogue on the height principle: debate whether height always grants authority, argue the case that height can actually be detrimental to one-to-one communication where you need to talk on the same level or hold an eye-to-eye discussion, and defend the counter-strategy that it is possible to avoid intimidating others by consciously making yourself appear smaller in relation to them. Then weigh what the stooped body signals about humility and subordination, and what the slouched body signals when informality itself becomes the aggression.",
        "A debate table where one speaker towers over the other while a level marker shows eye-to-eye contact failing; a panel then splits in two, one half showing a stooped, smaller figure winning trust, the other half showing a slouched lounger in an easy chair radiating dominance, with a caption reading The more humble, the lower he stoops.",
        [
            "Height can be detrimental to some aspects of one-to-one communication where you need to 'talk on the same level' or have an 'eye-to-eye' discussion with another person.",
            "Despite what many people would like to believe, tall people command more authority than short people.",
            "The more humble or subordinate an individual feels towards another, the lower he stoops his body.",
            "It is possible to avoid intimidating others by consciously making yourself appear smaller in relation to them.",
            "Most women curtsey when they meet Royalty and men incline their heads or remove their hats, making themselves appear smaller than the Royal person.",
            "The modern salute is a relic of the act of body lowering.",
            "Historically, lowering the height of one's body in front of another person has been used as a means of establishing superior and subordinate relationships.",
            "In business, the people who continually 'bow' to the management are labelled with such derogatory name tags as 'bootlickers' or 'crawlers'.",
            "We refer to a member of Royalty as 'Your Highness', whereas individuals who commit unsavoury acts are called 'low'.",
            "It is the complete informality on the other person's territory that communicates the dominant or aggressive attitude.",
        ],
    ),
    "audit": (
        "Audit the Speeding Stop: The Negatives of Staying in the Car and the Four-Step Stoop Technique",
        "Your mission is to audit the roadside encounter step by step: tick off why the officer may regard you as an adversary, then run the ledger of the driver's usual behaviour, debiting the officer's forced exit from his territory, the excuses that read as an attack, and the barrier created by staying in the car, each increasing your chances of being booked. Then pass the alternative: leaving your car for his territory, stooping to be smaller than him, lowering your own status while raising his, and the open palms with trembling voice, and close the books on the claim that this technique can save you from being booked more than 50 per cent of the time.",
        "An audit ledger by a parked patrol car: on the debit column a driver stays inside his car while a policeman crosses from his patrol car to the window, a barrier drawn between them; on the credit column the driver walks to the officer's car, stoops over smaller than the officer, shows open palms and a trembling voice, and the officer's ticket book closes unmarked with a 50 per cent stamp.",
        [
            "In the circumstances where you have been speeding in your car and are stopped by the police, the officer may regard you as an adversary as he approaches your vehicle.",
            "A driver's usual reaction when stopped is to remain in the car, wind the window down and make excuses for having exceeded the speed limit.",
            "One nonverbal negative of staying in the car is that the officer is forced to leave his territory, the patrol car, and come across to your territory, your vehicle.",
            "Another negative is that, assuming you have in fact broken the speed limit, your excuses may represent an attack to the officer.",
            "By remaining in your car, you create a barrier between yourself and the policeman.",
            "Considering that under these circumstances the police officer is obviously in a superior position to you, this type of behaviour only serves to make things go from bad to worse and your chances of being booked are increased.",
            "The recommended approach when flagged down is to get immediately out of your car, your territory, and go over to the police officer's car, his territory, so that he is not inconvenienced by having to leave his territory.",
            "You should stoop your body over so that you are smaller than the police officer is.",
            "You should lower your own status by telling the officer how foolish and irresponsible you are and raise his status by thanking him for pointing out the error of your ways and telling him that you realise how difficult his job must be with fools like you around.",
            "With your palms out and in a trembling voice, you should ask the officer not to give you a ticket.",
            "This type of behaviour shows the police officer that you are not a threat to him and often causes him to take the role of an angry parent, in which case he gives you a stern warning and tells you to be on your way, without a speeding ticket.",
            "When this technique is used as directed, it can save you from being booked more than 50 per cent of the time.",
        ],
    ),
    "matrix": (
        "Matrix Match: The Counter Barrier, Territory and the Two Faces of Lowering",
        "Your mission is to build a four-cell matrix from the chapter's situations: place the irate customer and the store counter barrier into one cell, the storekeeper's escape from his own side of the counter with stooped body and visible palms into another, the slouch in the easy chair that inverts lowering into a dominance signal into a third, and the rule that a person is always superior on his own territory into the fourth. Then drop the territorial law into each scenario to explain why the officer, the storekeeper and the home owner each behave as they do.",
        "A wall matrix of four storefront cards: an irate customer faced across a counter with a barrier line drawn, a storekeeper ducking around to the customer's side with open palms, a visitor slouched deep in an easy chair while the standing owner watches, and a map showing home territory marked superior while a caption reads A person will always be superior on his own territory.",
        [
            "The same technique that works with the police officer can be used to calm an irate customer who is returning some faulty goods to a retail store.",
            "In the retail situation, the counter represents a barrier between the store owner and the customer.",
            "Control of an irate customer would be difficult if the storekeeper remained on his own side of the counter, and this staking-out of territory would make the customer angrier.",
            "The best approach would be for the storekeeper to come around to the customer's side of the counter with his body stooped over and palms visible and to use the same technique as was used with the police officer.",
            "Interestingly, there are some circumstances under which lowering the body can be a dominance signal.",
            "Lowering the body becomes a dominance signal where you slouch down and make yourself comfortable in an easy chair in another person's home while the owner is standing.",
            "It is the complete informality on the other person's territory that communicates the dominant or aggressive attitude.",
            "It is also important to remember that a person will always be superior on his own territory, especially in his own home.",
            "Submissive gestures and behaviour are very effective methods for getting the person on side with you.",
            "The more humble or subordinate an individual feels towards another, the lower he stoops his body.",
        ],
    ),
    "boss": (
        "Boss Level: Invert the Bow, Own the Territory and Win the Person Over",
        "Your mission is to defeat the final boss, the paradox that the same gesture can serve opposite masters: master the ordinary rules first, stooping smaller, staying on the other side of the barrier and shrinking your status, then flip the lesson and wield lowering as aggression by slouching into an easy chair in another person's home, and finally exploit the law that a person is always superior on his own territory by using submissive gestures and behaviour as effective methods for getting the person on side with you, from the police officer to the angry store customer.",
        "A boss arena that is a living room: the visitor sinks low into the owner's easy chair, relaxed and sprawled, while the standing owner's authority visibly drains; a mirror then flips the scene to the same visitor stooping small before a police officer and a storekeeper, and a banner reads Submissive gestures get the person on side.",
        [
            "Interestingly, there are some circumstances under which lowering the body can be a dominance signal.",
            "This dominance effect occurs where you slouch down and make yourself comfortable in an easy chair in another person's home while the owner is standing.",
            "It is the complete informality on the other person's territory that communicates the dominant or aggressive attitude.",
            "A person will always be superior on his own territory, especially in his own home.",
            "Submissive gestures and behaviour are very effective methods for getting the person on side with you.",
            "It is possible to avoid intimidating others by consciously making yourself appear smaller in relation to them.",
            "This type of behaviour shows the police officer that you are not a threat to him and often causes him to take the role of an angry parent, in which case he gives you a stern warning and tells you to be on your way, without a speeding ticket.",
            "When the stooped-body technique is used as directed, it can save you from being booked more than 50 per cent of the time.",
            "The best approach for a storekeeper facing an irate customer is to come around to the customer's side of the counter with his body stooped over and palms visible.",
            "Historically, lowering the height of one's body in front of another person has been used as a means of establishing superior and subordinate relationships.",
            "The more humble or subordinate an individual feels towards another, the lower he stoops his body.",
            "Most women curtsey when they meet Royalty and men incline their heads or remove their hats, making themselves appear smaller than the Royal person.",
        ],
    ),
}
