# -*- coding: utf-8 -*-
CHAPTER = {
    "num": 13,
    "title": "Carbon Copies and Mirror Images",
    "authors": "Allan Pease",
    "domain": "Body Language | Mirroring and Rapport",
    "scrub": (
        "Scrub the Phenomenon: What Carbon Copying Is and What It Says",
        "Your mission is to scrub through the carbon copy phenomenon itself: how people at social functions adopt the identical gestures and posture of the person they are talking with, how this unconscious mimicry tells the other person I think the same as you, and how the copying continues for as long as the two people remain in agreement. Then trace the evidence, from the two men at the hotel bar who mirror every move, to the way married couples walk, stand, sit and move in identical ways, to Scheflen's finding that strangers studiously avoid holding mutual positions, and finish with why this is one of the most important non-verbal lessons we can learn.",
        "A time-scrubber playhead glides over a social gathering where pairs of people stand in matching postures; it pauses on two men at a hotel bar who uncross their arms and pocket their hands in sync, then zooms out to married couples walking in identical stride, while a caption reads I think the same as you over one pair's mirrored stances.",
        [
            "At any social function or place where people meet and interact, a number of people will have adopted the identical gestures and posture of the person with whom they are talking, and this is called carbon copying.",
            "Carbon copying is a means by which one person tells the other that he is in agreement with his ideas and attitudes.",
            "By copying his postures and gestures a person non-verbally says to the other, 'As you can see, I think the same as you, so I will copy your posture and gestures.'",
            "This unconscious mimicry is quite interesting to observe, as shown by the two men standing at the hotel bar in Figure 134, who had mirrored each other's gestures, making it reasonable to assume they were discussing a topic upon which they had the same thoughts and feelings.",
            "If one of the two men at the bar uncrosses his arms and legs or stands on the other foot, the other will follow, and if one puts his hand in his pocket, the other will copy, and this mimicry will continue for as long as the two men are in agreement.",
            "Carbon copying also occurs among good friends or people at the same status level, and it is common to see married couples walk, stand, sit and move in identical ways.",
            "Scheflen found that people who are strangers studiously avoid holding mutual positions.",
            "The significance of carbon copying can be one of the most important non-verbal lessons we can learn, for it is one way that others tell us that they agree with us or like us.",
            "Carbon copying is also a way for us to tell others that we like them, by simply copying their gestures.",
            "If an employer wishes to develop an immediate rapport and create a relaxed atmosphere with an employee, he need only copy the employee's posture to achieve this end.",
        ],
    ),
    "dialogue": (
        "Dialogue on Status and Rapport: Who Copies Whom Among Bosses, Employees and Couples",
        "Your mission is to stage a dialogue on the social choreography of mirroring: debate the employer who copies an employee's posture to build rapport against the up-and-coming employee who copies his boss's gestures to show agreement, then trace how groups fall into step with their leaders, from the first man through a doorway to the boss at the head of the boardroom table, and finish in the living room, where married couples walk, stand, sit and move in identical ways and the salesperson must watch who initiates the gestures and who follows.",
        "A seminar table showing two matched pairs: an employer leaning into an employee's mirrored posture on one side, and an up-and-coming employee mirroring his boss's hands-behind-head gesture on the other; above them a doorway where the boss walks through first, a boardroom where he sits at the head of the table, and a couch where a wife's gesture is copied by a talking husband.",
        [
            "If an employer wishes to develop an immediate rapport and create a relaxed atmosphere with an employee, he need only copy the employee's posture to achieve this end.",
            "An up-and-coming employee may be seen copying his boss's gestures in an attempt to show agreement.",
            "Research shows that when the leader of a group uses certain gestures and positions, subordinates copy them.",
            "Leaders also tend to be the first of a group to walk through a doorway, and they like to sit on the end of a couch or bench seat rather than in the centre.",
            "When a group of executives walk into a room, the boss usually goes first.",
            "When executives are seated in the board room, the boss usually sits at the head of the table, often farthest from the door.",
            "If the boss sits with a hands-behind-head T-cross gesture (Figure 96), his subordinates will copy.",
            "It is common to see married couples walk, stand, sit and move in identical ways because carbon copying occurs among good friends or people at the same status level.",
            "People who sell to married couples in their home are well advised to watch the couple's gestures, to see who initiates the gestures and who follows.",
            "If the husband is doing all the talking and the wife sits there saying nothing, but the husband copies his wife's gestures, you will inevitably find that she makes the decisions and writes the cheques, so it is a good idea to direct your presentation to her.",
        ],
    ),
    "audit": (
        "Audit the Deliberate Technique: Mirroring as a Sales Instrument",
        "Your mission is to audit mirroring used as a deliberate tool of influence: check off how copying the positive gestures and postures of the other person can influence a face-to-face encounter, how it puts the other person in a receptive and relaxed frame of mind because he can 'see' that you understand his point of view, and then open Pease's own sales ledger, where he deliberately copied every movement of a 'cold' insurance prospect until rapport was established, and where a sale resulted whenever the prospect began copying his gestures.",
        "An audit ledger opens on a sales ledger page: a clipboard with a checklist showing Copy positive gestures, Create receptive frame of mind, Establish strong enough rapport, and Proceed with presentation, while a figure 135 caption reads he can 'see' that you understand his point of view over a salesman and prospect in matching postures, and a bell rings marked SALE when the prospect copies back.",
        [
            "Using the knowledge of carbon copying, it is possible to influence a face-to-face encounter by copying the positive gestures and postures of the other person.",
            "Copying the other person's postures has the effect of putting the other person in a receptive and relaxed frame of mind, as he can 'see' that you understand his point of view (Figure 135).",
            "When Pease was selling insurance he found copying a very effective technique for a 'cold' prospective customer.",
            "Pease deliberately copied each movement the prospective customer made until he felt he had established a strong enough rapport to allow the presentation to proceed.",
            "Invariably, if the prospect began copying his gestures, a sale would result.",
            "An employer who copies an employee's posture can develop an immediate rapport and create a relaxed atmosphere, without saying a word about agreement.",
            "Because copying the other person's gestures tells him you think the same as he does, it is a way for us to tell others that we like them.",
            "The mimicry between two people will continue only for as long as the two are in agreement, so a copying prospect in the midst of a sales presentation is itself a signal of agreement.",
            "People who sell to married couples in their home are well advised to watch the couple's gestures, to see who initiates the gestures and who follows, before aiming the presentation.",
            "When the husband copies his wife's gestures while he does the talking, the wife makes the decisions and writes the cheques, so the presentation should be directed to her.",
        ],
    ),
    "matrix": (
        "Matrix Match: When Mirroring Backfires, the Status Equation and Taking Control",
        "Your mission is to build a matrix of when copying works and when it backfires: drop the junior clerk who copies his manager's superiority T-cross and figure 4 leg lock into the backfire cell, note that even subordinate verbal communication cannot save him from the intimidated, insulted manager, then place the accountants, lawyers and management personnel who assume these postures in the presence of those they consider inferior, and finish in the control cell, where taking the same posture as a 'superior' type disconcerts him and forces him to change position, handing you the control.",
        "A wall matrix with four cells: one shows the clerk copying the manager's T-cross and figure 4 leg lock while a red X stamps JOB IN JEOPARDY, another shows accountants, lawyers and managers leaning back in dominance, a third shows a man taking the same posture and disconcerting a 'superior' type who shifts in his chair, and the fourth shows a boardroom where subordinates copy the boss's hands-behind-head gesture.",
        [
            "Before copying the other person's gestures when negotiating, it is vital that your relationship with that person be taken into consideration.",
            "When the junior clerk of a large corporation has asked for a pay rise and is called into the manager's office, the manager may ask him to sit down and then assume a superiority T-cross gesture (Figure 96) and a figure 4 leg lock (Figure 81) while he leans back in his chair to show his superior, dominant and competitive attitude.",
            "If the clerk copied the manager's dominant posture while discussing his potential salary rise (Figure 136), even if his verbal communication were on the subordinate level, the manager would feel intimidated and even insulted by the clerk's non-verbal behaviour.",
            "A clerk who copies his manager's dominant posture while asking for a salary rise could put his job in jeopardy.",
            "Copying a superior's dominant posture is a highly effective method of disarming 'superior' types who try to take the control.",
            "Accountants, lawyers and management personnel are known for assuming these dominant postures in the presence of people whom they consider inferior.",
            "By taking the same posture as a person who assumes a superior, dominant and competitive attitude, you can effectively disconcert them and force them to change their position, allowing you to take the control.",
            "Research shows that when the leader of a group uses certain gestures and positions, subordinates copy them, which is why the boss's hands-behind-head T-cross gesture (Figure 96) is copied in the board room.",
            "Because strangers studiously avoid holding mutual positions, while friends and equals copy each other, copying is only appropriate when the relationship already supports rapport.",
            "The mimicry between two people continues only as long as they are in agreement, so copying the wrong posture, such as a dominant one, tells the other person you are claiming his territory of control.",
        ],
    ),
    "boss": (
        "Boss Level: Reading the Mirror to Find the Decision Maker and Win the Encounter",
        "Your mission is to defeat the final boss, a boardroom negotiation where everyone copies the leader: read who initiates the gestures and who follows, spot the boss as the first through the doorway and at the head of the table, catch the husband who copies his silent wife and know that she writes the cheques, use copying to put the other person in a receptive and relaxed frame of mind, and turn the manoeuvre on the 'superior' types who lean back with T-cross and figure 4 leg lock, forcing them to change position so you take the control.",
        "A boss arena shaped like a board room where the boss sits at the head of the table farthest from the door with a hands-behind-head T-cross gesture and subordinates copy him; a spotlight picks out a silent wife whose every gesture is mirrored by her talking husband, while a ledger stamp reads SHE WRITES THE CHEQUES, and a final challenger forces a leaning-back manager to shift in his chair and surrender the control.",
        [
            "The next time you attend a social function or a place where people meet and interact, take note of the number of people who have adopted the identical gestures and posture of the person with whom they are talking, for this carbon copying is a means by which one person tells the other that he is in agreement with his ideas and attitudes.",
            "The significance of carbon copying can be one of the most important non-verbal lessons we can learn, for this is one way that others tell us that they agree with us or like us.",
            "By simply copying another person's gestures we can tell them that we like them, which is why an employer need only copy an employee's posture to develop an immediate rapport and a relaxed atmosphere.",
            "Scheflen found that people who are strangers studiously avoid holding mutual positions, while married couples commonly walk, stand, sit and move in identical ways.",
            "Using the knowledge of carbon copying it is possible to influence a face-to-face encounter, because copying the other person's positive gestures and postures puts him in a receptive and relaxed frame of mind as he can 'see' that you understand his point of view.",
            "In selling insurance to a 'cold' prospective customer, Pease deliberately copied each movement the prospect made until he felt he had established a strong enough rapport to allow the presentation to proceed, and invariably, if the prospect began copying his gestures, a sale would result.",
            "People who sell to married couples in their home are well advised to watch the couple's gestures to see who initiates the gestures and who follows, because if the husband copies his wife's gestures, she makes the decisions and writes the cheques.",
            "When a group of executives walk into a room the boss usually goes first, and when they are seated in the board room he sits at the head of the table, often farthest from the door, where his hands-behind-head T-cross gesture (Figure 96) is copied by his subordinates.",
            "Accountants, lawyers and management personnel are known for assuming superior, dominant postures in the presence of people they consider inferior, and by taking the same posture you can effectively disconcert them and force them to change their position, allowing you to take the control.",
            "Before copying the other person's gestures when negotiating it is vital that your relationship with that person be taken into consideration, because a junior clerk who copies his manager's dominant posture could find his job in jeopardy.",
            "The mimicry between two people will continue for as long as they are in agreement, so both the mirroring you copy and the mirroring you receive are running signals of whether agreement is holding.",
        ],
    ),
}
