# -*- coding: utf-8 -*-
CHAPTER = {
    "num": 6,
    "title": "Arm Barriers",
    "authors": "Allan Pease",
    "domain": "Body Language | Arm Barriers",
    "scrub": (
        "Scrub the Origins: From Childhood Hiding to the Folded-Arms Research Lab",
        "Your mission is to scrub through the evolution of the arm barrier: how hiding behind solid objects as children, tables, chairs and mother's skirts, matured into the folded-arms posture by about age six, how the gesture was refined in our teens with crossed legs, and how folding one or both arms forms a barrier that blocks out the impending threat. Then weigh the evidence: the American lecture-room study in which the folded-arms group retained 38 per cent less and judged the lecturer more critically, why training centres should provide chairs with arms, and why 'it's comfortable' is really a match between gesture and a negative attitude.",
        "A time-scrubber playhead runs from a child hiding behind a table and mother's skirt to a six-year-old folding his arms, a teen relaxing the gesture with crossed legs, and a lecture room where one group sits with arms open and another with arms tightly folded while a bar chart tilts showing 38 per cent less retention for the folded-arms group.",
        [
            "Hiding behind a barrier is a normal human response that we learn at an early age to protect ourselves, and as children we hid behind solid objects such as tables, chairs, furniture and mother's skirts whenever we found ourselves in a threatening situation.",
            "As we grew older, this hiding behaviour became more sophisticated, and by the age of about six, when hiding behind solid objects had become unacceptable behaviour, we learned to fold our arms tightly across our chests whenever a threatening situation arose.",
            "During our teens we learned to make the crossed-arms gesture a little less obvious by relaxing our arms a little and combining the gesture with crossed legs.",
            "By folding one or both arms across the chest, a barrier is formed that is, in essence, an attempt to block out the impending threat or undesirable circumstances.",
            "When a person has a nervous, negative or defensive attitude, he will fold his arms firmly on his chest, a strong signal that he feels threatened.",
            "In American research a group of students instructed to keep their arms tightly folded across their chests throughout a series of lectures learned and retained 38 per cent less than a group instructed to keep their arms unfolded.",
            "The group that sat with folded arms during the lectures also had a more critical opinion of the lectures and of the lecturer.",
            "When the listener folds his arms, not only does he have more negative thoughts about the speaker, but he is also paying less attention to what is being said.",
            "Training centres should have chairs with arms so that the attendees can leave their arms uncrossed during lectures.",
            "Many people claim they habitually take the arms folded position because it is comfortable, but any gesture will feel comfortable when you have the corresponding attitude, so the negative, defensive or nervous person genuinely finds the folded arms position good.",
            "In non-verbal communication the meaning of the message is also in the receiver, not only the sender, and studies have shown that the reception of crossed-arms or stiff back and neck gestures is negative.",
        ],
    ),
    "dialogue": (
        "Dialogue on the Barrier: The Universal Defensive Gesture and the Speaker's Reply",
        "Your mission is to stage a dialogue between the defensive listener and the challenged speaker: the standard arm-cross as a universal gesture seen among strangers in queues, cafeterias and elevators, the lecture-hall experiment in which 90 per cent of the audience folded their arms after Pease defamed respected colleagues, the experienced speaker's ice breaker, and the rule that the non-verbal medium does not lie while the verbal medium does. Then replay the unblocking moves: handing the person a pen or book, leaning forward to view a visual presentation, and the open palms-up invitation that exposes the hidden objection.",
        "A two-person negotiation table where one side sits with arms tightly folded and the other slides a pen across and then leans forward with open palms, while an auditorium on the back wall shows 90 per cent of an audience folding their arms after a speaker's verbal attack.",
        [
            "The standard arm-cross gesture is a universal gesture signifying the same defensive or negative attitude almost everywhere, commonly seen when a person is among strangers in public meetings, queues, cafeterias, elevators or anywhere that people feel uncertain or insecure.",
            "In a lecture experiment Pease deliberately defamed several highly respected men well-known to the seminar audience, and about 90 per cent of the audience had taken the folded arms position immediately after the verbal attack began.",
            "Most people will take an arms folded position when they disagree with what they are hearing.",
            "Many public speakers have failed to communicate their message to the audience because they have not seen the folded arms gestures of their listeners.",
            "Experienced speakers know that the folded arms gesture demonstrates the necessity of using a good ice breaker to move the audience into a more receptive posture that will alter the listeners' attitude towards the speaker.",
            "When you see the arm-cross gesture during a face-to-face encounter, it is reasonable to assume that you may have said something with which the other person disagrees, even though the other person may be verbally agreeing with you.",
            "The fact is that the non-verbal medium does not lie, whereas the verbal medium does.",
            "As long as the arms-folded gesture remains, the negative attitude will remain, because the attitude causes the gestures to occur and prolonging the gesture forces the attitude to remain.",
            "A simple but effective method of breaking the folded-arms position is to hand the person a pen, a book or something that forces him to unfold his arms to reach forward, which moves him into a more open posture and attitude.",
            "Asking the person to lean forward to look at a visual presentation can also be an effective means of opening the folded-arms position.",
            "Another useful method is to lean forward with your palms facing up and say, 'I can see you have a question, what would you like to know?' or, 'What do you think?' and then sit back to indicate that it is the other person's turn to speak.",
            "By leaving your palms visible you non-verbally tell the other person that you would like an open, honest answer, and Pease as a salesman never proceeded with a presentation until he had uncovered a buyer's reason for suddenly folding his arms, which was more often than not a hidden objection.",
        ],
    ),
    "audit": (
        "Audit the Defensive Variations: Reinforced, Fist-Clenched and the Arm-Gripping Cluster",
        "Your mission is to audit the escalation ladder of the arm barrier: tick off the reinforced arm-cross in which clenched fists mark a hostile and defensive attitude, the clenched-teeth and red-face warning of an imminent attack and the submissive palms-up approach that defuses it, then the arm-gripping gesture with its white knuckles and cut circulation, seen in doctors' waiting-rooms and on first-time air travellers, and close the books with the courtroom contrast of the fists-clenched prosecutor against the arm-gripping defence.",
        "An audit ledger of escalating arm barriers: three exhibit cards showing the plain arm-cross, the reinforced version with clenched fists and red face, and the arm-gripping pose with white knuckles, while a courtroom stamp marks the prosecutor fists-clenched and the defence arm-gripping, and a waiting-room scene shows a nervous patient gripping his upper arms.",
        [
            "If as well as the full arm-cross gesture the person has clenched fists, it indicates a hostile and defensive attitude.",
            "The reinforced arm-cross cluster is often combined with clenched teeth and a red face, in which case a verbal or physical attack may be imminent.",
            "A submissive palms-up approach is needed to discover what caused the hostile gestures if the reason is not already apparent.",
            "The person using the fist-clenched gesture cluster has an attacking attitude, as opposed to the person who has taken a defending arm-cross position.",
            "The arm-gripping gesture is characterised by the hands tightly gripping the upper arms to reinforce the position and to stop any attempt to unfold the arms and expose the body.",
            "The arms in the arm-gripping gesture can often be gripped so tight that the fingers and knuckles turn white as the blood circulation is cut off.",
            "The arm-gripping style is common to people sitting in doctors' and dentists' waiting-rooms, or first-time air travellers who are waiting for the plane to lift off, and it shows a negative restrained attitude.",
            "In a lawyer's office the prosecutor may be seen using a fists-clenched arm-cross while the defence may have taken the arm-gripping position.",
            "The full arm-cross gesture can escalate from a defensive attitude into an attacking one when the fists are clenched, signalling that the person may strike verbally or physically.",
            "The tightly gripping hands of the arm-gripping gesture both reinforce the barrier and betray a stronger level of restraint than the standard folded arms.",
        ],
    ),
    "matrix": (
        "Matrix Match: Status, Thumbs-Up and the Sales Close",
        "Your mission is to build the status and selling matrix: place the general manager who never folds his arms after his dominant handshake into the STATUS cell, the nervous new employees who take full or partial arm-folds into the APPREHENSION cell, and the young executive's thumbs-up arm-cross, the Fonz gesture of self-confidence and protection, into the SUPERIOR-PEER cell. Then work the selling grid: the thumbs-up combined with positive gestures as the green light to close, the fist-clenched poker-face as the red light to retreat to questions, the 'No' that becomes hard to change once verbalised, and the gun-carrying officer who only folds his arms with clenched fists on guard.",
        "A wall matrix with four cells labelled STATUS, APPREHENSION, SUPERIOR-PEER and SALES CLOSE: cards fly into place showing a general manager with hands in the palm-in-palm position, new employees with folded arms, a young executive with both thumbs pointing up like the Fonz, and a buyer whose fist-clenched arms and poker face stop a salesperson at the close.",
        [
            "Status can influence arm-folding gestures, and a superior type can make his superiority felt in the presence of persons he has just met by not folding his arms.",
            "At a company social function the general manager greets new employees with a dominant handshake and stands with his hands by his side, behind his back in the superior palm-in-palm position, or with one hand in his pocket, and he rarely folds his arms to show the slightest hint of nervousness.",
            "After shaking hands with the boss, the new employees take full or partial arm-fold gestures because of their apprehension about being in the presence of the company's top man.",
            "Both the general manager and the new employees feel comfortable with their respective gestures as each is signalling his status relative to the other.",
            "When a general manager meets a young, up-and-coming executive who is also a superior type, the likely outcome is that after a dominant handshake the young executive takes an arm-fold gesture with both thumbs pointing vertically upwards.",
            "The thumbs-up arm-cross is the defensive version of both arms being held horizontally in front of the body with both thumbs up to show that the user is 'cool', a gesture characterised by Henry Winkler, who played the Fonz in the television series Happy Days.",
            "The thumbs-up gesture is our way of showing that we have a self-confident attitude and the folded arms give a feeling of protection.",
            "If the buyer's thumbs-up gesture comes towards the end of the sales presentation and is combined with many other positive gestures, the sales person can move comfortably into closing the sale and asking for the order.",
            "If at the close of the sale the buyer moves into the fist-clenched arm cross position and has a poker face, the sales person can be inviting disastrous consequences by attempting to ask for the order, and it is better to go back to the sales presentation and ask more questions to try to discover the buyer's objection.",
            "In selling, if the buyer verbalises 'No', it can become difficult to change his decision, and the ability to read body language allows you to see the negative decision before it is verbalised and gives you time to take an alternative course of action.",
            "People who carry weapons or wear armour rarely use defensive arm-fold gestures because their weapon or armour provides sufficient body protection.",
            "Police officers who wear guns rarely fold their arms unless they are standing guard, and they normally use the fist-clenched position to show quite clearly that nobody is permitted to pass where they stand.",
        ],
    ),
    "boss": (
        "Boss Level: Partial and Disguised Barriers, Spotting the Hidden Nervousness",
        "Your mission is to defeat the final boss, the subtlest arm barriers: catch the partial arm-cross that hides fear in meetings, the holding-hands-with-oneself gesture that Desmond Morris ties to the child's hand held by a parent, then the disguised arm-cross of politicians, sales people and television personalities who touch a handbag, bracelet, watch or shirt cuff instead of folding their arms, and finally the tell-tale two-handed wine glass, the dance-floor and trophy-walk of the young man in full view, and the famous figures who hide nervousness without knowing it.",
        "A boss arena that is a crowded cocktail party: one figure crosses a dance floor to ask a lady to dance while adjusting his watch, a nervous woman holds a wine glass with two hands and a handbag in the crook of her arm, a politician touches his shirt cuff at the podium, and a freeze-frame spotlight catches the disguised barrier that the trained observer reads as a dead giveaway.",
        [
            "The full arm-cross gesture is sometimes too obvious to use around others because it tells them that we are fearful, so occasionally we substitute a subtler version, the partial arm cross, in which one arm swings across the body to hold or touch the other arm to form the barrier.",
            "The partial arm barrier is often seen at meetings where a person may be a stranger to the group or is lacking in self-confidence.",
            "Another popular version of a partial arm barrier is holding hands with oneself, a gesture commonly used by people who stand before a crowd to receive an award or give a speech.",
            "Desmond Morris says that the holding-hands-with-oneself gesture allows a person to relive the emotional security that he experienced as a child when his parent held his hand under fearful circumstances.",
            "Disguised arm-cross gestures are highly sophisticated gestures used by people who are continually exposed to others, including politicians, sales people and television personalities, who do not want their audience to detect that they are unsure of themselves or nervous.",
            "In the disguised arm-cross, one arm swings across in front of the body to grasp the other arm but, instead of the arms folding, one hand touches a handbag, bracelet, watch, shirt cuff or other object on or near the other arm, and once again the barrier is formed and the secure feeling is achieved.",
            "When cufflinks were popular, men were often seen adjusting them as they crossed a room or dance floor where they were in full view of others.",
            "As cufflinks lost their popularity, a man would adjust the band on his watch, check the contents of his wallet, clasp or rub his hands together, play with a button on his cuff or use any other gesture that would allow the arms to cross in front of the body.",
            "To the trained observer these disguised gestures are a dead giveaway because they achieve no real purpose except as an attempt to disguise nervousness.",
            "A good place to observe disguised barrier gestures is anywhere that people walk past a group of onlookers, such as a young man who crosses the dance floor to ask an attractive young lady to dance with him or someone crossing an open room to receive a trophy.",
            "Women are less obvious than men in their use of disguised arm barrier gestures because they can grasp such things as handbags or purses when they become unsure of themselves.",
            "One of the most common versions of the disguised arm barrier is holding a glass of beer or wine with two hands, and since you need only one hand to hold a glass of wine, the use of two hands allows the nervous person to form an almost undetectable arm barrier, a gesture used by almost everyone and often by well-known figures who are completely unaware they are doing it.",
        ],
    ),
}
