# -*- coding: utf-8 -*-
CHAPTER = {
    "num": 16,
    "title": "Desks, Tables and Seating Arrangements",
    "authors": "Allan Pease",
    "domain": "Body Language | Seating and Space",
    "scrub": (
        "Scrub the Territory: From Knapp's Environments to the Four Basic Seating Positions",
        "Your mission is to scrub through the geography of the desk: how Mark Knapp warned that the environment and the direction of the seats distort seating behaviour, how crowded restaurants force intimate couples into a defensive opposite position, and how the standard rectangular office desk gives person B four basic positions in relation to person A. Then walk the corner position B1 as the friendly casual slot with unlimited eye contact and a partial barrier at the desk corner, and the co-operative position B2 as the mutually oriented slot where the trick is taking it without invading A's territory, including the three-party strategy of 'siding with the opposition'.",
        "A cutaway office with a rectangular desk and person A at the head while four labelled positions B1, B2, B3 and B4 circle around it; a playhead sweeps from a crowded restaurant where a couple is forced to sit facing each other, to the desk corner glowing as the friendly slot with eye-contact beams crossing it, to a technical expert seated opposite the client while the sales person sits beside him.",
        [
            "Mark Knapp, in his book Non-Verbal Communication in Human Interaction, noted that although there is a general formula for the interpretation of seating positions, the environment may have an effect on the position chosen.",
            "Research conducted with white middle-class Americans showed that seating positions taken in the public bar of a hotel can vary from the seating positions taken in a high-class restaurant.",
            "The direction in which the seats are facing and the distance between tables can have a distorting influence on seating behaviour.",
            "Intimate couples prefer to sit side by side wherever possible, but in a crowded restaurant where the tables are close together this is not possible and the couples are forced to sit opposite each other in what is normally a defensive position.",
            "Because of a wide range of moderating circumstances, the seating examples in the chapter relate primarily to arrangements in an office environment with a standard rectangular desk.",
            "Person B can take four basic seating positions in relation to person A: the corner position, the co-operative position, the competitive-defensive position and the independent position.",
            "The corner position is normally used by people who are engaged in friendly, casual conversation and allows for unlimited eye contact and the opportunity to use numerous gestures and to observe the gestures of the other person.",
            "The corner of the desk provides a partial barrier should one person begin to feel threatened, and this position avoids territorial division on the top of the table.",
            "The most successful strategic position from which a sales person can deliver a presentation to a new customer is the corner position, assuming A is the buyer, and simply moving the chair to this position can relieve a tense atmosphere and increase the chances of a favourable negotiation.",
            "The co-operative position occurs when two people are mutually oriented, both thinking alike or working on a task together, and it is one of the most strategic positions for presenting a case and having it accepted.",
            "The trick in taking the co-operative position is for B to be able to take it without A feeling as though his territory has been invaded.",
            "When a sales person introduces a technical expert into a second interview, the expert is seated at position C opposite customer A and the sales person takes the co-operative or corner position, a strategy known as 'siding with the opposition' that lets him question the technician on behalf of the client.",
        ],
    ),
    "dialogue": (
        "Dialogue on the Battle Line: The Competitive Position, the Doctor's Desk and the Invaded Territory",
        "Your mission is to stage a dialogue across the table: argue the competitive-defensive position as the solid barrier that makes parties take firm stands, and weigh Argyle's doctor's office experiment where removing the desk raised the at-ease patients from 10 per cent to 55 per cent. Then cross-examine the influencing business, the deliberate reprimand, the unconscious division of the table into two equal territories, and re-enact Pease's restaurant test in which the menu, ashtray, sugar bowl and salt and pepper shakers were pushed across the centre line until the victim squirmed, sweated and fled.",
        "A dialogue scene split in two: left, a doctor's office where a gauge jumps from 10 per cent to 55 per cent as the desk is removed, right, a small rectangular restaurant table with the salt, pepper, sugar bowl and napkins being pushed across a dashed centre line by two opposing hands while a bead of sweat forms on the victim's brow.",
        [
            "Sitting across the table from a person can create a defensive, competitive atmosphere and can lead to each party taking a firm stand on his point of view because the table becomes a solid barrier between both parties.",
            "The competitive-defensive position is taken by people who are either competing with each other or when one is reprimanding the other, and it can also establish that a superior/subordinate role exists when it is used in A's office.",
            "Argyle noted that an experiment conducted in a doctor's office showed that the presence or absence of a desk had a significant effect on whether a patient was at ease or not.",
            "Only 10 per cent of the patients were perceived to be at ease when the doctor's desk was present and the doctor sat behind it, but this figure increased to 55 per cent when the desk was absent.",
            "If B is seeking to persuade A, the competitive-defensive position reduces the chance of a successful negotiation unless B is deliberately sitting opposite as part of a pre-planned strategy.",
            "It may be that A is a manager who must severely reprimand employee B, and the competitive position can strengthen the reprimand, or B may deliberately sit directly opposite A to make A feel superior.",
            "Whatever line of business you are in, if it involves dealing with people you are in the influencing business, and your objective should always be to see the other person's point of view, to put him or her at ease and make him or her feel right about dealing with you.",
            "The competitive position does not lead towards putting the other person at ease, and more co-operation will be gained from the corner and co-operative positions than will ever be achieved from the competitive position.",
            "Conversations are shorter and more specific in the competitive position than from any other seating position.",
            "Whenever people sit directly opposite each other across a table, they unconsciously divide it into two equal territories, with each claiming half as his own territory and rejecting the other's encroaching upon it, which is why two people seated competitively at a restaurant table mark their territorial boundaries with the salt, pepper, sugar bowl and napkins.",
            "In Pease's restaurant test the menu, ashtray, sugar bowl and salt and pepper shakers were pushed one by one into the companion's territory, making him sit back, squirm around in his seat and break into a light film of sweat on his brow.",
            "When Pease returned to the table after the salesman had excused himself, he found all the table items had been pushed back to the centre line, demonstrating the tremendous resistance that a person has to the invasion of his territory.",
        ],
    ),
    "audit": (
        "Audit the Signal Test: The Article on the Desk, the Independent Position and the Shape of the Table",
        "Your mission is to audit the reader's reactions at the desk: place the book, quotation or sample on the table and tick off the three possible responses, the lean forward that says stay on your side, the take into the territory that invites the corner or co-operative position, and the push back that spells trouble, against the golden rule of never encroaching without permission. Then audit the independent position in library, park bench and restaurant, and work through the square table's beside-you co-operation and opposite-you resistance and the round table's relaxed informality of equal status.",
        "An audit board with three stamped cards above a rectangular desk: a book placed on the table while a figure leans forward, another hand taking the book across the line and a red-stamped push back card; below, three table shapes, a square with a friendly arrow to the side seat and a red arrow to the opposite seat, a round table with equal wedge territories, and a library bench where two people sit apart with an angry bubble between them.",
        [
            "When you have a visual presentation, such as a book, quotation or sample, to show to a person sitting behind a rectangular desk, you should first place the article on the table.",
            "The other person will lean forward and look at the article, take it into his territory, or push it back into your territory.",
            "If the other person leans forward to look at the article, you must deliver your presentation from where you sit, as this action non-verbally tells you that he does not want you on his side of the desk.",
            "If he takes the article into his territory, this gives you the opportunity to ask permission to enter his territory and take either the corner or co-operative positions.",
            "If, however, he pushes the article back, you are in trouble, and the golden rule is never to encroach on the other person's territory unless you have been given verbal or non-verbal permission to do so or you will put them offside.",
            "The independent position is the position taken by people when they do not wish to interact with each other, and it occurs in such places as a library, park bench or restaurant.",
            "The independent position signifies lack of interest and can even be interpreted as hostile by the other person if the territorial boundaries are invaded, so it should be avoided where open discussion between A and B is required.",
            "Square tables create a competitive or defensive relationship between people of equal status and are ideal for having short, to-the-point conversations or to create a superior/subordinate relationship.",
            "At a square table the most co-operation usually comes from the person seated beside you, and the one on the right tends to be more co-operative than the one on the left.",
            "At a square table the most resistance usually comes from the person seated directly opposite.",
            "A round table creates an atmosphere of relaxed informality and is ideal for promoting discussion among people who are of equal status, as each person can claim the same amount of table territory.",
            "Removing the table and sitting in a circle also promotes the same relaxed, equal-status result as the round table.",
        ],
    ),
    "matrix": (
        "Matrix of Power: King Arthur's Round Table, the Rectangular Boardroom and the Family Dining Room",
        "Your mission is to build a power matrix from the table shapes: plot King Arthur's Round Table where the king held the most power, the knights on his right and left the next amount and the knight directly across in the competitive-defensive position, then map the rectangular table's influence order of A, B, C, D with the back-to-the-door reversal, and the name badge strategy for structuring power plays. Finish by sorting the family dining table into the round 'open' family, the square 'closed' family and the rectangular 'authoritative' family, and the executive's split use of square work desk and round persuasion table.",
        "A wall matrix with four labelled cells: a round table with a crown at the top and power numbers fading with distance to the knight opposite, a rectangular boardroom table with A, B, C and D name badges and a red flash on the chair whose back faces the door, three family table shapes labelled OPEN, CLOSED and AUTHORITATIVE, and an executive office where a square desk faces a round coffee table with wrap-around seating.",
        [
            "King Arthur used the Round Table as an attempt to give each of his knights an equal amount of authority and status.",
            "King Arthur was unaware that if the status of one person is higher than the others in the group, it alters the power and authority of each other individual.",
            "The king held the most power at the Round Table, so the knights seated on either side of him were non-verbally granted the next highest amount of power, the one on his right having a little more than the one on the left.",
            "The amount of power at the Round Table diminished relative to the distance that each knight was seated away from the king.",
            "The knight seated directly across the table from King Arthur was, in effect, in the competitive-defensive position and was likely to be the one who gave the most trouble.",
            "Many of today's business executives use both square and round tables, with the square work desk used for business activity, brief conversations and reprimands, and the round coffee table with wrap-around seating used to create an informal relaxed atmosphere or to persuade.",
            "On a rectangular table position A has always commanded the most influence, and in a meeting of people of equal status the person sitting at position A will have the most influence, assuming that he does not have his back to the door.",
            "If A's back were facing the door at a rectangular table, the person seated at B would be the most influential and would be strong competition for A.",
            "Assuming that A was in the best power position at a rectangular table, person B has the next most authority, then C, then D.",
            "This seating information makes it possible to structure power plays at meetings by placing name badges on the seats where you want each person to sit so that you may have the maximum influence over them.",
            "The choice of the shape of a family dining room table can give a clue to the power distribution in that family, assuming that the dining-room could have accommodated a table of any shape and that the table shape was selected after considerable thought.",
            "'Open' families go for round tables, 'closed' families select square tables and 'authoritative' types select rectangular tables.",
        ],
    ),
    "boss": (
        "Boss Level: Getting the Decision Over Dinner, From the Cave Feast to the Restaurant",
        "Your mission is to defeat the final boss, the dinner-table decision: trace man's feeding behaviour from the vegetarian tree-dweller to the co-operative hunter who divided the spoils at dusk in the communal cave, with the fire at the entrance and his back against the wall, and then re-enact that safety at the restaurant with the prospect's back to a solid wall or screen, dimmed lights, muffled music, a round table and the prospect's view of others obscured by a screen or large green plant. Finish by weighing the physiology of the open space behind the back and the relaxation techniques top restaurants use to extract money from their customers' wallets.",
        "A boss arena that is a cave mouth at dusk: hunters divide the spoils around an open fire while one caveman eats with his back against the cave wall, then the scene crossfades to a candle-lit restaurant booth where the prospect sits with his back to a solid wall, a large green plant obscures the room, dim lights glow and muffled music plays, while a gauge shows respiration, heart rate, brain wave frequencies and blood pressure calming down.",
        [
            "Anthropologists tell us that man's origin was that of a tree-dweller who was strictly vegetarian, his diet consisting of roots, leaves, berries, fruit and the like, until about a million years ago he came out of the trees onto the plains to become a hunter of prey.",
            "Prior to becoming a land dweller man's eating habits were those of the monkeys, involving continual nibbling throughout the day, with each individual entirely responsible for his own survival and for obtaining his own food.",
            "As a hunter man needed the co-operation of other individuals to capture large prey, so large co-operative hunting groups were formed that would leave at sunrise to hunt throughout the day and return at dusk with the day's spoils.",
            "The spoils of the hunt were divided equally among the hunters, who would eat inside a communal cave where a fire was lit at the entrance to ward off dangerous animals and to provide warmth.",
            "Each caveman sat with his back against the wall of the cave to avoid the possibility of being attacked from behind while he was engrossed in eating his meal.",
            "The ancient process of food sharing at dusk around an open fire was the beginning of a social event that modern man re-enacts in the form of barbecues, cookouts and dinner parties, and modern man reacts and behaves at these events in much the same way as he did over a million years ago.",
            "A positive decision in your favour is easier to obtain when your prospect is relaxed, free of tension and his or her defensive barriers have been lowered.",
            "Research shows that respiration, heart rate, brain wave frequencies and blood pressure rapidly increase when a person sits with his back to an open space, particularly where others are moving about.",
            "Tension is further increased if the person's back is towards an open door or a window at ground level, so whether dining at home or at a restaurant you should have your prospect seated with his back to a solid wall or screen.",
            "The lights should be dimmed and muffled background music played, and many top restaurants have an open fireplace or facsimile near the entrance of the restaurant to recreate the fire that burned at the ancient cave feasts.",
            "It would be best to use a round table and to have your prospect's view of other people obscured by a screen or large green plant if you are to have a captive audience.",
            "It is far easier to obtain a favourable decision in a relaxed restaurant than in one with bright lighting, tables and chairs placed in open areas and the banging of plates, knives and forks, which is why top restaurants use these types of relaxation techniques to extract large amounts of money from their customers' wallets for ordinary food, and men have been using them for thousands of years to create a romantic atmosphere for the benefit of their women.",
        ],
    ),
}
