# -*- coding: utf-8 -*-
CHAPTER = {
    "num": 11,
    "title": "Cigars, Cigarettes, Pipes and Glasses",
    "authors": "Allan Pease",
    "domain": "Body Language | Objects and Gestures",
    "scrub": (
        "Scrub the Rituals: Smoking as Tension Release and the Staller's Toolkit",
        "Your mission is to scrub through the opening of the chapter: why smoking is an outward manifestation of inner turmoil rather than nicotine addiction, how it works as a displacement activity for the tensions of social and business encounters, what the anxious non-smoker does instead, and why smoking gestures can be read because they are performed in a predictable, ritualistic manner. Then run the two ritual tapes side by side: the pipe smoker's cleaning, lighting, tapping, filling, packing and puffing routine with its sales research on delayed decisions, and the cigarette smoker's tapping, twisting, flicking and waving mini-gestures that betray above-normal tension and buy him stalling time.",
        "A time-scrubber playhead glides over a split scene: on one side a patient jitters outside a dentist's surgery while a smoker draws on his cigarette, a nail-biter, a foot-tapper and a tie-player crowd the waiting room; on the other side a pipe smoker taps, packs and relights his pipe at a tense sales interview while a stopwatch runs, and a cigarette smoker twitches through a cascade of mini-gestures in fast-forward.",
        [
            "Pease states that smoking is an outward manifestation of an inner turmoil or conflict and has little to do with nicotine addiction.",
            "Smoking is described as one of the displacement activities that people in today's high-pressure society use to release the tensions that build up from social and business encounters.",
            "Pease observes that most people experience inner tension while waiting outside the dentist's surgery to have a tooth removed, and while a smoker covers up his anxiety by smoking, non-smokers perform other rituals such as grooming, nail biting, finger and foot tapping, cufflink adjusting, head scratching, taking a ring off and putting it back on, and playing with a tie.",
            "The reassurance gestures of the anxious non-smoker all tell us that the person needs reassurance.",
            "Smoking gestures can play an important part in assessing a person's attitude because they are usually performed in a predictable, ritualistic manner that can give us important clues to the person's attitude.",
            "Pipe smokers perform a cleaning, lighting, tapping, filling, packing and puffing ritual with their pipes, and this is a very useful way to help relieve tension when they are under pressure.",
            "Sales research has shown that pipe smokers usually take longer to make a decision to buy than do cigarette smokers or non-smokers, and that the pipe ritual is performed most often during the tense moments of the sales interview.",
            "Pipe smokers are people who like to stall decision-making and who can do so in an unobtrusive and socially acceptable way.",
            "Pease advises that if you want a quick decision from a pipe smoker, you should hide his pipe before the interview.",
            "Like pipe smoking, cigarette smoking is a displacement of inner tension and allows time to stall, but the cigarette smoker generally reaches his decision faster than the pipe smoker.",
            "The pipe smoker is, in effect, a cigarette smoker who needs more time to stall in making decisions than his cigarettes allow.",
            "The cigarette ritual involves tapping, twisting, flicking, waving and other mini-gestures indicating that the person is experiencing more tension than may be normal.",
        ],
    ),
    "dialogue": (
        "Dialogue on the Smoke: Up and Down Exhalation as a Window on Attitude",
        "Your mission is to stage a dialogue between the upward blower and the downward blower: argue the case that the direction of exhaled smoke reveals whether a person feels positive, superior and confident or negative, secretive and suspicious, and weigh the corner-of-mouth blow as an even darker signal, while conceding the caveat of the smoker who blows upwards just to avoid offending others. Then debate the speed of exhalation, the movie gang leader's ceiling-shot of superiority against Humphrey Bogart's downward puff as he plots a gaol break, and close on the poker table, where the four-aces bluffer throws his cards down in disgust and then sits back and blows the smoke upwards.",
        "A stage with two smoking figures facing each other in silhouette: one tilts his head back and fires smoke up at the ceiling with a superiority halo, the other blows a grey stream down from the corner of his mouth while secretive shadows creep in; a film strip flickers between a motorcycle gang leader's sharp head tilt and Bogart's inverted cigarette, then a poker player discards his four aces in a staged tantrum before a telltale upward puff.",
        [
            "One particular signal indicates whether the person has a positive or negative attitude towards his circumstances, and that signal is the direction in which the smoke is exhaled, whether it is up or down.",
            "A person who is feeling positive, superior or confident will blow the smoke in an upward direction most of the time, while a person in a negative, secretive or suspicious frame of mind will blow the smoke down most of the time.",
            "Blowing the smoke down and from the corner of the mouth indicates an even more negative or secretive attitude.",
            "The smoke-direction reading assumes that the smoker is not blowing the smoke upwards simply to avoid offending others, in which case he could have blown the smoke in either direction.",
            "In motion pictures, the leader of a motorcycle gang or criminal syndicate is usually portrayed as a tough, aggressive person who, as he smokes, tilts his head back sharply and with controlled precision blows the smoke towards the ceiling to demonstrate his superiority to the rest of the gang.",
            "Humphrey Bogart was often cast as a gangster or criminal who always held his cigarette inverted in his hand and blew the smoke down from the corner of his mouth as he planned a gaol break or other devious activity.",
            "There appears to be a relationship between how positive or negative the person feels and the speed at which he or she exhales the smoke.",
            "The faster the smoke is blown upwards the more superior or confident the person feels, and the faster it is blown down, the more negative he feels.",
            "If a card player who is smoking is dealt a good hand, he is likely to blow the smoke upwards, whereas a poor hand may cause him to blow it downwards.",
            "Some card players see a poker face when playing cards as a method of not displaying any body signals that may give them away, while other players like to be actors and use misleading body language to lull the other players into a false sense of security.",
            "A poker player dealt four aces who wanted to bluff the other players could throw the cards face down on the table in disgust, curse, swear or fold his arms and put on a non-verbal display that would indicate that he had been dealt a poor hand, and then quietly sit back and blow the smoke upwards.",
        ],
    ),
    "audit": (
        "Audit the Close: Cigar Status, Nostril Smoke and the Termination Signals",
        "Your mission is to audit the remaining smoking signals and tick them off in the ledger: cigars as a display of superiority by cost and size, their place with executives, gang leaders and high-status people, and their use in celebrating victories, checked against Pease's own tally of 400 recorded cigar exhalations of which 320 were upward. Then verify the nostril-blown smoke of the confident individual who tilts his head back in a looking-down-his-nose position, against the head-down angry bull version, and finally stamp the two general signals, the continual tapping on the ashtray that shows inner conflict, and the cigarette extinguished early as the smoker's decision to terminate the conversation, which the alert observer can hijack to close on his own terms.",
        "An audit ledger with stamps: a cigar floats in a golden circle beside executive silhouettes and a celebration scene with a baby, a wedding ring, a signed deal and a lottery ticket, next to a tally counter reading 320 of 400; a nose-blowing figure tilts his head back in superiority and then drops his head to snort like an angry bull; an ashtray receives a relentless series of taps and a cigarette is stubbed out long before its normal length while a clock hands over control of the conversation.",
        [
            "Cigars have always been used as a means of displaying superiority because of their cost and size.",
            "The big-time business executive, the gang leader and people in high-status positions often smoke cigars.",
            "Cigars are used to celebrate a victory or achievement such as the birth of a baby, a wedding, clinching a business deal or winning the lottery.",
            "It is not surprising that most of the smoke exhaled by cigar smokers is upwards, and Pease records that of 400 recorded cigar smoke exhalations at a celebration dinner where cigars were distributed freely, 320 were in an upward direction.",
            "Blowing smoke out through the nostrils is a sign of a superior, confident individual, and the smoke is blown downwards only because of the physical location of the nostrils.",
            "The person who nose-blows his smoke often tilts his head back in a looking down his nose position.",
            "If the person's head is down as he nose-blows the smoke, he is angry and is trying to look ferocious, like an angry bull.",
            "The continual tapping of a cigar or cigarette end on the ashtray shows that an inner conflict is taking place and that you may need to reassure the smoker.",
            "Most smokers smoke their cigarette down to a certain length before extinguishing it in the ashtray.",
            "If the smoker lights a cigarette and suddenly extinguishes it earlier than he normally would, he has signalled his decision to terminate the conversation.",
            "Watching for the early-extinguishing termination signal can allow you to take control or to close the conversation, making it appear that it was your idea to end it.",
            "Observation of smoking gestures in selling shows that when a smoker is asked to buy, those who have reached a positive decision blow the smoke upwards, whereas those who have decided not to buy blow it downwards.",
        ],
    ),
    "matrix": (
        "Matrix Match: Glasses as Props, From the Mouth Arm to the Folded Frame",
        "Your mission is to build a four-cell matrix of the glasses wearer's gestures: drop the arm-of-the-frame-in-the-mouth card into REASSURANCE, citing Desmond Morris's finding that objects against the lips or in the mouth relive the baby's security at the mother's breast, and pair it with the stalling function that peaks at the close of a negotiation when a decision has been asked for. Then slot the lens-cleaning card into STALLING, where silence is the best tactic immediately after the request, read the follow-up gestures, the glasses put back on meaning the person wants to see the facts again, the folded frames put away signalling the wish to terminate, and map each cell to the negotiator's correct response.",
        "A wall matrix of four labelled cells; cards fly into place showing a man mouthing the arm of his glasses beside a baby at its mother's breast and a thumb-sucking child, a negotiator polishing his lenses while a pause meter ticks, a pair of glasses sliding back onto a nose as documents re-emerge, and folded frames disappearing into a pocket as the handshake begins.",
        [
            "Almost every artificial aid used by man gives its user an opportunity to perform many revealing gestures, and this is certainly the case with those who wear glasses.",
            "One of the most common gestures with glasses is placing one arm of the frame in the mouth.",
            "Desmond Morris says that the act of putting objects against the lips or in the mouth is a momentary attempt by the person to relive the security he experienced as a baby at his mother's breast, which means that glasses-in-mouth is essentially a reassurance gesture.",
            "Smokers use their cigarettes for the same reassurance reason as the glasses-in-mouth gesture, and the child sucks his thumb.",
            "Like pipe smoking, the glasses-in-mouth gesture can be used to stall or delay a decision.",
            "In negotiating, it has been found that the glasses-in-mouth gesture appears most frequently at the close of the discussion when the person has been asked for a decision.",
            "The act of continually taking the glasses off and cleaning the lenses is another method used by glasses wearers to gain time for a decision.",
            "When the lens-cleaning gesture is seen immediately after a decision has been asked for, silence is the best tactic.",
            "The gestures that follow the stall gesture signal the person's intention and allow an alert negotiator to respond accordingly.",
            "If the person puts the glasses back on, this often means that he wants to see the facts again, whereas folding the glasses and putting them away signals an intention to terminate the conversation.",
            "Watching for the glasses-folding termination signal allows the alert negotiator to take control and close the conversation on his own terms.",
        ],
    ),
    "boss": (
        "Boss Level: The Peering Over Glasses and the Etiquette of the Frames",
        "Your mission is to defeat the final boss, the critical peering-over-glasses look: trace it back to the actors of the 1920s and 1930s movies who used it to portray the judgmental master of an English public school, understand why the reading-glasses wearer finds looking over the tops more convenient than removing them, and feel the scrutiny of whoever is on the receiving end. Then beat the costly mistake: the listener's inevitable folded arms, crossed legs and negative attitude, and apply the counter-strategy of removing the glasses to speak and putting them back on to listen, which relaxes the other person, hands the wearer control of the conversation, and teaches the listener the off-and-on signal system of when to stay silent and when to talk.",
        "A boss arena lit like a 1930s movie set: a stern public-school master peers over his spectacles at a cowering pupil while the word JUDGED hovers between them, and the pupil's arms fold and legs cross frame by frame; beside it a diagram of the champion's move, glasses off for speaking with a green light, glasses on for listening with a red light, as the pupil learns when he may talk.",
        [
            "Actors in the motion pictures made during the 1920s and 1930s used the peering-over-glasses gesture to portray a critical or judgmental person such as the master of an English public school.",
            "Often the person may be wearing reading glasses and finds it more convenient to look over the tops, rather than removing them to look at the other person.",
            "Whoever is on the receiving end of the peering look may feel as though he is being judged or scrutinised.",
            "Looking over the glasses can be a very costly mistake, as the listener inevitably responds to this look with folded arms, crossed legs and a correspondingly negative attitude.",
            "Glasses wearers should remove them when speaking and put them back on to listen.",
            "Removing the glasses to speak and putting them back on to listen not only relaxes the other person but allows the glasses wearer to have control of the conversation.",
            "The listener quickly learns that when the glasses are off he must not interrupt the wearer, and when they are put back on he had better start talking.",
            "Almost every artificial aid used by man gives its user an opportunity to perform many revealing gestures, and glasses wearers are among the most revealing of all.",
            "The continual tapping of a cigar or cigarette end on the ashtray shows that an inner conflict is taking place and that you may need to reassure the smoker.",
            "If the smoker lights a cigarette and suddenly extinguishes it earlier than he normally would, he has signalled his decision to terminate the conversation.",
            "Watching for the early-extinguishing termination signal can allow you to take control or to close the conversation, making it appear that it was your idea to end it.",
        ],
    ),
}
