# -*- coding: utf-8 -*-
CHAPTER = {
    "num": 10,
    "title": "Courtship Gestures and Signals",
    "authors": "Allan Pease",
    "domain": "Body Language | Courtship Signals",
    "scrub": (
        "Scrub the Ritual: From Graham's Built-in Radar to the Courtship Signals of the Human Animal",
        "Your mission is to scrub through the courtship ritual from the start: how Graham's built-in radar psychs out the available women and escorts them out in record time, how zoologists find that animal courtship follows predetermined patterns with the strutting bird and the indifferent female, how courtship signals are sent and read back as a non-verbal green light for a more intimate approach, why success with the opposite sex depends on sending and recognising courtship signals, why women are aware of these gestures while men are blind to them, and how the same man is called 'sexy' by women and 'arrogant' by his male rivals.",
        "A party scene where Graham's radar locks onto a woman across the room while an animated bird struts and puffs its feathers beside him; the exit doors swing open as he escorts her out, a traffic-light dot flashes green, and split captions show women whispering 'sexy, masculine' while men scowl 'aggressive, insincere'.",
        [
            "Pease's friend Graham developed an art that most males would love to acquire, attending social functions where he could quickly 'psych out' the available women and sometimes in as little as ten minutes be seen heading towards the exit with the woman, escorting her to his car.",
            "Research into animal courtship behaviour conducted by zoologists and behavioural scientists reveals that male and female animals use a series of intricate courtship gestures, some quite obvious and others extremely subtle, and that most are done subconsciously.",
            "In the animal world, courtship behaviour in each species follows specific and predetermined patterns, as when the male bird struts around the female giving a vocal display, puffing up his feathers and performing many intricate body movements to gain her attention.",
            "The bird courtship ritual, with the strutting male and the female who appears to display little or no interest, is similar to that performed by the human animal when courtship begins.",
            "Graham's technique was to display male courtship gestures to the prospective females, and those who were interested would respond with the appropriate female courtship signals, giving Graham the non-verbal green light to proceed with a more intimate approach.",
            "The success that people have in sexual encounters with members of the opposite sex is directly related to their ability to send courtship signals and to recognise those being sent back.",
            "Women are aware of the courtship gestures, as they are aware of most other body gestures, but men are far less perceptive, often being totally blind to them.",
            "Women described Graham as 'sexy', 'masculine' and 'someone who makes you feel feminine', their reactions to his constant array of courtship signals.",
            "Men described Graham as 'aggressive', 'insincere' and 'arrogant', their reaction to the aggressive competition that Graham represented, and consequently he had very few male friends, since no male likes a rival for the attentions of his female.",
            "More space is devoted to female courtship signals than to male signals because women have a greater range of courtship signals than men.",
        ],
    ),
    "dialogue": (
        "Dialogue on the Body's Answer: Inborn Cues and Scheflen's Quasicourtship",
        "Your mission is to stage a dialogue about the body's automatic answer: debate whether courtship signals are studied and deliberate or completely unconscious and possibly inborn, walk through Dr Albert Scheflen's quasicourtship findings on high muscle tone, the protruding chest, the pulled-in stomach and the youthful erect posture, and watch the beach experiment where the changes switch on at the moment of eye contact and switch off after the couple passes each other, plus the pupil dilation and flushed cheeks of excited interest.",
        "A beach at dusk where a man and woman approach each other from a distance; as they meet each other's gaze a wireframe body straightens, the stomach pulls in and the chest protrudes, the bagging under the eyes smooths away, and then the old posture returns after they pass, with a footnote card reading Scheflen, 'Quasicourtship behaviour in psychotherapy'.",
        [
            "While some courtship signals are studied and deliberate, others are given completely unconsciously, and a popular theory is that they may be inborn.",
            "Dr Albert Scheflen, in his article 'Quasicourtship behaviour in psychotherapy', noted that when a person enters the company of a member of the opposite sex, certain physiological changes take place.",
            "Scheflen found that high muscle tone becomes evident in the body in preparation for a possible sexual encounter.",
            "Scheflen found that 'bagging' around the face and eyes decreases, body sagging disappears, the chest protrudes and the stomach is automatically pulled in when courtship begins.",
            "Pot-bellied slumping disappears, the body assumes an erect posture and the person appears to become more youthful in appearance during courtship interaction.",
            "The ideal place to observe these courtship changes is on a beach, when a man and woman approach each other from a distance.",
            "The physiological changes take place when the man and woman are close enough to meet each other's gaze and continue until after they have passed each other, at which time the original posture returns.",
            "Excited interest also causes pupil dilation and a flushed appearance in the cheeks during courtship interaction.",
        ],
    ),
    "audit": (
        "Audit the Male Arsenal: Preening, Thumbs-in-Belt and the Intimate Gaze",
        "Your mission is to audit the male courtship arsenal: check off the preening behaviour, the reach for the throat and the straightening of the tie, the smoothed collar and the imaginary dust brushed from the shoulder, the rearranged cufflinks and smoothed hair, the thumbs-in-belt genital highlight, the foot pointed at the female, the intimate gaze held a split second longer, the dilated pupils, the hands on hips and the seated crotch display, and weigh Pease's verdict that most men fish with a big stick while women carry the lures.",
        "A checklist card for the male arsenal: a tie being straightened, an imaginary dust brush on a shoulder, thumbs hooked into a belt, a foot pointing at the female, hands on hips and an arrow tracing a seated crotch display; beside it a man stands in a river whacking the water with a big stick while a fish leaps into a woman's net.",
        [
            "Like most animal species, the human male displays preening behaviour as the female approaches.",
            "In addition to the automatic physiological reactions, the courting male will reach for his throat and straighten his tie as the female approaches.",
            "If he is not wearing a tie, the male may smooth his collar or brush imaginary dust from his shoulder, and rearrange his cufflinks, shirt, coat and other clothing.",
            "The male may also preen himself by smoothing his hair.",
            "The most aggressive sexual display the male can make towards the female is the aggressive thumbs-in-belt gesture that highlights his genital region.",
            "The courting male may turn his body towards the female and point his foot at her.",
            "The courting male uses the intimate gaze and holds her gaze for a split second longer than normal.",
            "If the courting male is really keen, his pupils will be dilated.",
            "The courting male often stands with his hands on hips to accentuate his physical size and show his readiness to be involved with the female.",
            "When seated or leaning against a wall, the courting male may spread his legs to give a crotch display.",
            "Pease writes that when it comes to courtship rituals, most men are about as effective as someone standing in a river trying to catch fish by hitting them on the head with a big stick.",
            "Pease notes that women have more lures and fishing skills to land their fish than any male could ever hope to acquire.",
        ],
    ),
    "matrix": (
        "Matrix Match: The Female Courtship Signals I, From Head Toss to Wet Lips",
        "Your mission is to build a matrix of the female courtship signals, part one: place each signal card in its cell, the shared preening gestures of hair touching and clothing smoothing, the single thumb tucked in the belt, the head toss, the exposed wrists and visible palms, the open legs against the defensive crossed legs, the rolling hips, the sideways glance under dropped eyelids, and Desmond Morris's wet-lip selfmimicry with the ancient lipstick mimicry of reddened genitals.",
        "A signal-grid board where female courtship cards fly into place: the head toss with flying hair, a wrist exposed while smoking a cigarette, legs opened wide, rolling hips, a sideways glance under dropped eyelids, wet lips and a lipstick bullet, each card captioned with its meaning and provenance.",
        [
            "Women use most of the same basic preening gestures as men, including touching the hair, smoothing the clothing, one or both hands on hips, foot and body pointing towards the male, extended intimate gaze and increasing eye contact.",
            "Although the thumbs-in-belt is a male aggression gesture, women adopt it with feminine subtlety, displaying only one thumb tucked into a belt or protruding from a handbag or pocket.",
            "The head toss is a female courtship gesture in which the head is flicked to toss the hair back over the shoulders or away from the face, and even women with short hair may use this gesture.",
            "An interested female will gradually expose the smooth soft skin of her wrists to the potential male partner, because the wrist area has long been considered one of the highly erotic areas of the body, and she also makes her palms visible to the male while she is speaking.",
            "Women who smoke cigarettes find this tantalising wrist and palm exposure quite simple to perform while smoking, and the exposed wrist and head toss gestures are often mimicked by homosexual males who want to take on a feminine appearance.",
            "The open legs signal means the legs are opened wider than they would normally have been if the male had not arrived on the scene, whether the woman is sitting or standing, contrasting with the sexually defensive female who keeps her legs crossed and together at all times.",
            "The hips have an accentuated roll when walking to highlight the pelvic region, and some of the more subtle female courtship gestures have been used for centuries in advertising to sell goods and services.",
            "In the sideways glance the woman holds the man's gaze with partially dropped eyelids just long enough for him to notice, then she quickly looks away, creating the tantalising feeling of peeping and being peeped at that can light the fires of most normal men.",
            "Dr Desmond Morris describes the mouth slightly open with wet lips as 'selfmimicry', as it is intended to symbolise the female genital region, with the lips made to appear wet either by saliva or cosmetics to give the appearance of sexual invitation.",
            "When a woman becomes sexually aroused her lips, breasts and genitals become larger and redder as they fill with blood, and the use of lipstick is a technique thousands of years old intended to mimic the reddened genitals of the sexually aroused female.",
        ],
    ),
    "boss": (
        "Boss Level: The Complete Female Arsenal, From the Shoe Fondle to the Leg Twine",
        "Your mission is to beat the final boss, the complete female arsenal: master the fondled cylindrical object as an unconscious indication of the mind, the sideways glance over the raised shoulder of the cigar advertisement, the three seated leg positions from the knee point to the shoe fondle to the leg twine that Scheflen links to high muscle tone, and the slow crossing and uncrossing of the legs with thigh stroking and the low voice that signals a desire to be touched.",
        "A master-class split screen of the female arsenal: a hand fondling a wine glass stem, a glance over a raised shoulder in a cigar advertisement, three seated diagrams labelled knee point, shoe fondle and leg twine, and a low-voice silhouette of a woman slowly crossing and uncrossing her legs while stroking her thigh.",
        [
            "Fondling cigarettes, the stem of a wine glass, a finger or any long, thin object is an unconscious indication of what may be in the mind.",
            "The sideways glance over a raised shoulder is self-mimicry of the rounded female breasts, and Figure 119 makes use of dilated pupils, the head toss, exposed wrists, a sideways glance, wet lips, head up and fondling a cylindrical object, all intended to generate desire for a particular brand of cigar.",
            "Men often sit with their legs apart in an aggressive crotch display, whereas women use leg crossing as protection for their delicate genital area.",
            "Women use three basic leg positions to communicate a courting attitude.",
            "With the knee point, one leg is tucked under the other and points to the person whom she finds interesting, a very relaxed position that takes the formality out of a conversation and gives the opportunity for a fleeting exposure of the thighs.",
            "The shoe fondle also indicates a relaxed attitude and has the phallic effect of thrusting the foot in and out of the shoe, which can drive some men wild.",
            "Most men agree that the leg twine is the most appealing sitting position a woman can take, and it is a gesture that women consciously use to attract attention.",
            "Dr Scheflen states that in the leg twine one leg is pressed firmly against the other to give the appearance of high muscle tone, the condition that the body takes when a person is ready for sexual performance.",
            "Other signals used by women include crossing and uncrossing the legs slowly in front of the man and gently stroking the thighs with her hand, indicating a desire to be touched.",
            "The slow crossing and uncrossing of the legs and the gentle stroking of the thighs is often accompanied by speaking in a low voice.",
        ],
    ),
}
