# -*- coding: utf-8 -*-
CHAPTER = {
    "num": 9,
    "title": "Eye Signals",
    "authors": "Allan Pease",
    "domain": "Body Language | Eye Behavior",
    "scrub": (
        "Scrub the Tell-Tale Eye: The Pupil Reflex and Its Ancient Track Record",
        "Your mission is to scrub through the history of the eye's influence on behaviour: how everyday phrases like 'shifty eyes' and 'the Evil Eye' secretly refer to pupil size and gaze, Hess's claim in The Tell-Tale Eye that the pupils work independently, the four-fold pupil dilation of excitement versus the snake eyes of anger, the dimly lit dating rooms that cause dilation, babies and children pumping up their pupils to look appealing, and the old profession of pupil watching from belladonna drops and Chinese gem traders to the expert card players who lost games when dark glasses hid the aces.",
        "A time-scrubber playhead sweeps across a candle-lit romantic table where a lover's pupils balloon to four times their size, pans past a 'beady little eyes' snake-eye mask, a baby's huge dilating pupils, an ancient Chinese gem trader leaning over a buyer's eyes, a vial of belladonna, and a poker table where a dark-glassed opponent hides a four-ace hand while the expert folds in frustration.",
        [
            "Throughout history we have been preoccupied with the eye and its effect on human behaviour, as phrases like 'She looked daggers at him', 'He has shifty eyes' and 'He gave me the Evil Eye' unwittingly refer to the size of the person's pupils and to his or her gaze behaviour.",
            "In his book The Tell-Tale Eye, Hess says that the eyes may well give the most revealing and accurate of all human communication signals because they are a focal point on the body and the pupils work independently.",
            "In given light conditions, the pupils will dilate or contract as the person's attitude and mood change from positive to negative and vice versa.",
            "When someone becomes excited, his pupils can dilate up to four times their normal size.",
            "An angry, negative mood causes the pupils to contract to what are commonly known as 'beady little eyes' or 'snake eyes'.",
            "If a woman loves a man, she will dilate her pupils at him and he will decode this signal correctly, without knowing he does so, which is why romantic encounters are often arranged in dimly lit places that cause the pupils to dilate.",
            "Young lovers who look deeply into each other's eyes unknowingly look for pupil dilation, and each becomes excited by the dilation of the other's pupils.",
            "Research has shown that when pornographic films showing men and women in sexual positions are shown to men, their pupils can dilate to almost three times the normal size, and the same films cause even greater dilation in women, which raises some doubt about the statement that women are less stimulated by pornography than men.",
            "Young babies and children have larger pupils than adults and their pupils constantly dilate when adults are present in an attempt to look as appealing as possible and thus receive constant attention.",
            "Tests conducted with expert card players show that fewer games were won by the experts when their opponents wore dark glasses, because an opponent dealt four aces could no longer give his hand away through rapid pupil dilation.",
            "Pupil watching was used by the ancient Chinese gem traders who watched for the pupil dilation of their buyers when negotiating prices, and centuries ago prostitutes put drops of belladonna in their eyes to dilate their pupils and to make themselves appear more desirable.",
            "The old cliché says 'Look a person in the eye when you talk to him', and when communicating or negotiating you should practise 'looking them in the pupil' and let the pupils tell you their real feelings.",
        ],
    ),
    "dialogue": (
        "Dialogue on the Gaze: Eye Contact, Trust, Liking and Cultural Rules",
        "Your mission is to stage a dialogue on how long a gaze should last: argue the one-third versus two-thirds rule, where the dishonest or withholding person meets your eyes less than one-third of the time and a gaze of more than two-thirds signals either interest with dilated pupils or hostility with constricted pupils, bring in Argyle's finding that looking at someone makes them like you back, defend the 60 to 70 per cent rapport gaze, and then widen the table to culture: the nervous timid person who is rarely trusted, the banning of dark tinted glasses in negotiation, the high-frequency gaze of Southern Europeans, and the Japanese who gaze at the neck instead of the face.",
        "A debate stage where one side argues the gaze clocks in at under one-third for the liar while the other side argues over two-thirds for the interested or the hostile, with pupil icons dilating and constricting; on a side screen Argyle's two figures point at each other and smile, a dark-glassed negotiator is crossed out, and a map lights up Southern Europe in one colour and Japan with a neck-gazing silhouette in another.",
        [
            "It is only when you see 'eye to eye' with another person that a real basis for communication can be established.",
            "The feeling that some people make us quite comfortable while others make us ill-at-ease or seem untrustworthy has to do primarily with the length of time that they look at us or hold our gaze as they speak.",
            "When a person is being dishonest or holding back information, his eyes meet ours less than one-third of the time.",
            "When a person's gaze meets yours for more than two-thirds of the time it can mean one of two things: first, he or she finds you very interesting or appealing, in which case the gaze will be associated with dilated pupils, and secondly, he or she is hostile towards you and may be issuing a non-verbal challenge, in which case the pupils will become constricted.",
            "Argyle reported that he found that when person A likes person B, he will look at him a lot, which causes B to think that A likes him, so B will like A in return.",
            "To build a good rapport with another person, your gaze should meet his about 60 to 70 per cent of the time, and this will also make him begin to like you.",
            "It is not surprising that the nervous, timid person who meets your gaze less than one-third of the time is rarely trusted.",
            "In negotiation, dark tinted glasses should be avoided at all times as they make others feel that you are staring at them.",
            "Like most body language and gestures, the length of time that one person gazes at another is culturally determined.",
            "Southern Europeans have a high frequency of gaze that may be offensive to others, and the Japanese gaze at the neck rather than at the face when conversing.",
            "Always be sure to consider cultural circumstances before jumping to conclusions about another person's gaze.",
            "It takes about thirty days of conscious practice before the eye techniques in this chapter can be effectively used to improve your communication skills.",
        ],
    ),
    "audit": (
        "Audit the Gaze Zones: Business, Social and Intimate Triangles",
        "Your mission is to audit the three gaze territories and tick each off against its occasion: check the business gaze with its imaginary triangle on the forehead that creates a serious atmosphere and keeps control of the interaction, the social gaze that drops below eye level to the triangle between the eyes and the mouth, and the intimate gaze that sweeps from the eyes down to the chest or breasts and, at a distance, to the crotch. Then apply the ledger to the manager reprimanding a lazy employee and confirm why only the business gaze carries the right weight.",
        "An audit ledger with three face stamps: the business face wearing a triangle on the forehead labelled serious and in control, the social face with a triangle between eyes and mouth labelled friendly, and the intimate face with a triangle running from eyes to chest labelled interested, alongside a manager's desk where the three gazes are tested on a slouching employee whose reaction changes with each stamp.",
        [
            "When having discussions on a business level, imagine that there is a triangle on the other person's forehead, and by keeping your gaze directed at this area you create a serious atmosphere and the other person senses that you mean business.",
            "Provided that your gaze does not drop below the level of the other person's eyes in a business discussion, you are able to maintain control of the interaction.",
            "When the gaze drops below the other person's eye level, a social atmosphere develops.",
            "Experiments into gazing reveal that during social encounters the gazer's eyes also look in a triangular area on the other person's face, in this case between the eyes and the mouth.",
            "The intimate gaze is across the eyes and below the chin to other parts of the person's body, and in close encounters it is the triangular area between the eyes and the chest or breasts.",
            "For distant gazing, the intimate gaze travels from the eyes to the crotch, and men and women use this gaze to show interest in each other, with those who are interested returning the gaze.",
            "Not only is the length of the gaze significant; just as important is the geographical area of the person's face and body at which you direct your gaze, as this also affects the outcome of a negotiation.",
            "These gaze signals are transmitted and received non-verbally and are accurately interpreted by the receiver.",
            "If you were a manager going to reprimand a lazy employee and you used the social gaze, the employee would take less heed of your words, regardless of how loud or threatening you sounded.",
            "The social gaze would take the sting out of your words, and the intimate gaze would either intimidate or embarrass the employee.",
            "The business gaze is the appropriate one to use when reprimanding an employee, as it has a powerful effect on the receiver and tells him that you are serious.",
            "The area of the other person's body upon which you direct your gaze can have a powerful effect on the outcome of any face-to-face encounter.",
        ],
    ),
    "matrix": (
        "Matrix Match: Side-Glances, Eye Blocks and Reading the Courtship Signals",
        "Your mission is to build a matrix of the eyes' side messages: drop the sideways glance with raised eyebrows or a smile into INTEREST and the same glance with down-turned brows and drooping mouth corners into HOSTILITY, then chart the courtship side of the grid where the 'come-on' look combines the sideways glance with the intimate gaze, playing hard to get is merely dropping the intimate gaze for the social gaze, and the business gaze in courting earns a label of cold. Finish with the eye-block gesture, from the unconscious lid-closing of the bored or superior person to the head-back look known as 'looking down one's nose'.",
        "A wall matrix with four cells: INTEREST holds a raised-brow sideways glance and a smile, HOSTILITY holds a furrowed-brow sideways glance, COURTSHIP holds the come-on look with hearts and the hard-to-get player switching to the social gaze, and BLOCKOUT holds an eye-block face whose eyelids close for a second and a head tilted back in the 'looking down one's nose' pose.",
        [
            "The sideways glance is used to communicate either interest or hostility.",
            "When the sideways glance is combined with slightly raised eyebrows or a smile, it communicates interest and is frequently used as a courtship signal.",
            "When the sideways glance is combined with down-turned eyebrows, a furrowed brow or the corners of the mouth down-turned, it signals a suspicious, hostile or critical attitude.",
            "What men describe as the 'come-on' look that women use relates to a sideways glance and an intimate gaze.",
            "If a man or woman wants to play hard to get, he or she needs only avoid using the intimate gaze and instead use the social gaze.",
            "To use the business gaze during courting would cause a man or woman to be labelled as cold or unfriendly.",
            "When you use the intimate gaze on a potential sex partner, you give the game away.",
            "Women are expert at sending and receiving the intimate gaze, but unfortunately most men are not.",
            "Men are usually obvious when they use the intimate gaze and are generally unaware of having been given an intimate gaze, much to the frustration of the woman who has transmitted it.",
            "The eye-block gesture occurs unconsciously and is an attempt by the person to block you from his sight because he has become bored or uninterested in you or feels that he is superior to you.",
            "Compared to the normal rate of six to eight blinks per minute during conversation, the eyelids close and remain closed for a second or longer as the person momentarily wipes you from his mind, and the ultimate blockout is to fall asleep.",
            "If a person feels superior to you, the eye-block gesture is combined with the head tilted backwards to give you a long look, commonly known as 'looking down one's nose', and seeing an eye block signals that the approach you are using may be causing a negative reaction and that a new tack is needed.",
        ],
    ),
    "boss": (
        "Boss Level: Take Command of the Other Person's Gaze",
        "Your mission is to defeat the final boss, the presenter's oldest enemy, the wandering gaze: survive the statistics that 87 per cent of the information relayed to the brain comes via the eyes and that a visual-aid-bound listener absorbs as little as 9 per cent of an unrelated message or only 25 to 30 per cent of a related one, then master the pen-lift manoeuvre that drags his head up from the visual aid to your eyes for maximum absorption, and finish the fight with your other palm kept visible as you speak.",
        "A boss arena that is a presentation room where a listener's head is locked down on a chart, absorbing only 9 per cent, until the presenter lifts the pen from the visual aid and holds it between their eyes, magnetically raising the listener's head to meet his gaze while a palm stays visible and an intake meter climbs to maximum absorption.",
        [
            "Research shows that of the information relayed to a person's brain, 87 per cent comes via the eyes, 9 per cent via the ears, and 4 per cent via the other senses.",
            "If a person is looking at your visual aid as you are speaking, he will absorb as little as 9 per cent of your message if the message is not directly related to what he sees.",
            "If the message is related to the visual aid, he will absorb only 25 to 30 per cent of your message if he is looking at the visual aid.",
            "To maintain maximum control of his gaze, use a pen or pointer to point to the visual aid and at the same time verbalise what he sees.",
            "Lift the pen from the visual aid and hold it between his eyes and your own eyes, which has the magnetic effect of lifting his head so that he is looking at your eyes, and now he sees and hears what you are saying.",
            "Holding the pen between his eyes and yours achieves maximum absorption of your message, so be sure that the palm of your other hand is visible when you are speaking.",
            "The area of the other person's body upon which you direct your gaze can have a powerful effect on the outcome of any face-to-face encounter.",
            "It takes about thirty days of conscious practice before the eye techniques described in this chapter can be effectively used to improve your communication skills.",
        ],
    ),
}
