# -*- coding: utf-8 -*-
CHAPTER = {
    "num": 1,
    "title": "A Framework for Understanding",
    "authors": "Allan Pease",
    "domain": "Body Language | Foundations",
    "scrub": (
        "Scrub the Origins: From Silent Film and Darwin to the Science of the Non-Verbalist",
        "Your mission is to scrub through the birth of body language study: how a new breed of social scientist called the non-verbalist watches people's cues and signals, why the field only took off in the 1960s and reached the public via Julius Fast in 1970, how Chaplin and the silent actors pioneered gesture communication, and how Darwin's 1872 book spawned the modern field. Then weigh the numbers: the million recorded cues, Mehrabian's 7-38-55 split, and Birdwhistell's finding that over 65 per cent of face-to-face communication is non-verbal.",
        "A time-scrubber playhead glides across a silent film set where Chaplin gestures to the camera, then lands on Darwin's 1872 volume opening onto a modern research lab; a bar chart tilts showing 7 per cent verbal, 38 per cent vocal, 55 per cent non-verbal, while a woman's look to kill leaves a man frozen in place.",
        [
            "Pease introduces the non-verbalist as a new kind of social scientist who delights in watching the non-verbal cues and signals of human beings wherever people interact, just as the birdwatcher delights in watching birds.",
            "The non-verbal aspects of communication have been actively studied on any scale only since the 1960s, and the public became aware of their existence only since Julius Fast published a book about body language in 1970.",
            "Charlie Chaplin and many other silent movie actors were the pioneers of non-verbal communication skills because gestures and other body signals were the only means of communication available on the screen.",
            "Each silent movie actor was classed as good or bad by the extent to which he could use gestures and other body signals to communicate effectively, while those with good verbal skills prevailed once talking films became popular.",
            "The most influential pre-twentieth-century work on body language was Charles Darwin's The Expression of the Emotions in Man and Animals, published in 1872, which spawned the modern studies of facial expressions and body language.",
            "Since Darwin's time researchers have noted and recorded almost one million nonverbal cues and signals.",
            "Albert Mehrabian found that the total impact of a message is about 7 per cent verbal, 38 per cent vocal, and 55 per cent non-verbal.",
            "Professor Birdwhistell estimated that the average person actually speaks words for a total of about ten or eleven minutes a day and that the average sentence takes only about 2.5 seconds.",
            "Birdwhistell found that the verbal component of a face-to-face conversation is less than 35 per cent and that over 65 per cent of communication is done non-verbally.",
            "Most researchers agree that the verbal channel is used primarily for conveying information, while the non-verbal channel is used for negotiating interpersonal attitudes and in some cases as a substitute for verbal messages.",
            "A woman can give a man a look to kill and convey a very clear message to him without opening her mouth.",
            "Birdwhistell maintains that words and movements occur together with such predictability that a well-trained person should be able to tell what movement a man is making by listening to his voice, and he learned to tell what language a person was speaking by watching his gestures.",
        ],
    ),
    "dialogue": (
        "Dialogue on the Signals: Inborn, Genetic, Learned and the Perceptive Mind",
        "Your mission is to stage a dialogue on how signals get made: debate whether gestures are inborn, genetic, learned or cultural, using the evidence from deaf and blind children, five divergent cultures, and our ape relatives, and then walk the universal basics, from smiling and nodding to the shoulder shrug, and the claim that the human animal rarely notices that his body tells one story while his voice tells another. Then defend women's intuition: why perceptiveness is a technical reading of cues, why a hunch is a mismatch of channels, and why mothers become sharp negotiators.",
        "A seminar table where one side argues inborn and the other argues learned while an evidence projector shows Eibl-Eibesfeldt's deaf-blind child smiling, Ekman's five culture masks, and a coat being put on right arm first by a man and left arm first by a woman; a hunch bubble floats over a listener whose arms are crossed and chin is down.",
        [
            "Many people find difficulty in accepting that humans are still biologically animals, yet Homo sapiens is a species of primate, a hairless ape that has learned to walk on two limbs and has a clever, advanced brain.",
            "Like any other species, humans are dominated by biological rules that control their actions, reactions, body language and gestures.",
            "The fascinating thing about the human animal is that he is rarely aware of his postures, movements and gestures that can tell one story while his voice may be telling another.",
            "Whenever we call someone perceptive or intuitive we are referring to his or her ability to read another person's non-verbal cues and to compare these cues with verbal signals.",
            "When we say we have a hunch or gut feeling that someone has told us a lie, we really mean that their body language and their spoken words do not agree.",
            "A perceptive speaker gets a hunch that his delivery is not going across when the audience sits back in their seats with chins down and arms crossed on their chest, and he knows he needs a different approach, while an unperceptive speaker blunders on regardless.",
            "Women are generally more perceptive than men, which has given rise to what is commonly referred to as women's intuition, including an innate ability to pick up and decipher non-verbal signals and an accurate eye for small details.",
            "Because few husbands can lie to their wives and get away with it, while most women can pull the wool over a man's eyes without his realising it, female intuition is particularly evident in women who have brought up young children.",
            "For the first few years a mother relies solely on the non-verbal channel to communicate with the child, and this is believed to be the reason why women often become more perceptive negotiators than men.",
            "Evidence about whether non-verbal signals are inborn, genetic, learned or acquired was collected from blind and deaf people who could not have learned through the auditory or visual channels, from many different cultures, and from our nearest anthropological relatives, the apes and monkeys.",
            "The German scientist Eibl-Eibesfeldt found that the smiling expressions of children born deaf and blind occur independently of learning or copying, which means these must be inborn gestures.",
            "Ekman, Friesen and Sorenson studied the facial expressions of people from five widely different cultures and found each culture used the same basic facial gestures to show emotion, leading them to conclude that these gestures must be inborn.",
        ],
    ),
    "audit": (
        "Audit the Universal and the Local: Gestures Across Cultures, From the OK Ring to the V Sign",
        "Your mission is to audit how a gesture's meaning survives travel: check off the universal basics like smiling, frowning, head nodding and the three-part shoulder shrug, then take the ring gesture, the thumb-up and the V sign through their cultural ledger, ticking off what OK means in France, Japan and the Mediterranean, why the thumb-up puts an Australian hitch-hiker in trouble in Greece, and how Churchill's palm-out victory sign becomes an obscenity when the palm faces in. Close the books with the safest rule for travellers and the exact cultural scope of the discussion.",
        "An audit ledger on a world map: a checklist of universal gestures stamps past, while three exhibit cards, the ring, the thumb-up and the V sign, are stamped with differing labels as they cross borders, and a caption reads When in Rome, do as the Romans do above a clashing flag row.",
        [
            "Most of the basic communication gestures are the same all over the world: when people are happy they smile, and when they are sad or angry they frown or scowl.",
            "Nodding the head is almost universally used to indicate yes or affirmation, appears to be a form of head lowering, and is probably an inborn gesture because it is also used by deaf and blind people.",
            "Shaking the head from side to side to indicate no or negation is also universal and may well be a gesture learned in infancy, when a baby turns his head from side to side to reject his mother's breast and later shakes his head to stop a parent's spoon feeding.",
            "Baring the teeth is derived from the act of attacking and is still used by modern man in the form of a sneer and other hostile gestures, even though he will not attack with his teeth.",
            "Smiling was originally a threat gesture, but today it is done in conjunction with non-threatening gestures to show pleasure.",
            "The shoulder shrug is a universal gesture used to show that a person does not know or understand what you are talking about, and it is a multiple gesture with three main parts: exposed palms, hunched shoulders and raised brow.",
            "Just as verbal language differs from culture to culture, so the non-verbal language may also differ, and a gesture that is common in one culture may be meaningless in another or even have a completely opposite meaning.",
            "The ring or OK gesture was popularised in the USA during the early nineteenth century by newspapers that were starting a craze of using initials to shorten common phrases, and the ring itself seems to represent the letter O in the OK signal.",
            "Theories about the initials OK include the misspelled all correct or oll korrect, the opposite of knock-out or K.O., and Old Kinderhook, the birthplace of a nineteenth century American president who used the initials as a campaign slogan.",
            "In France the OK ring gesture means zero or nothing, in Japan it can mean money, and in some Mediterranean countries it is an orifice signal often used to infer that a man is homosexual.",
            "In Britain, Australia and New Zealand the thumb-up gesture means the hitch-hiker's thumbing a lift, an OK signal, and, when jerked sharply upwards, an insult meaning up yours or sit on this, while in Greece its main meaning is get stuffed.",
            "Churchill popularised the V for victory sign during World War II with the palm facing out, whereas the palm faces towards the speaker in the obscene insult version, which still means victory in most parts of Europe and the number two in many parts of Europe.",
        ],
    ),
    "matrix": (
        "Matrix Match: Clusters, Congruence, Context and the Status Equation",
        "Your mission is to build a four-cell matrix for reading gestures correctly: drop each evidence card into its cell, the scratch of the head with its multiple meanings into CLUSTER, the critical evaluation figure with the finger up the cheek and chin down into SENTENCE, the incongruent politician and Freud's wedding ring patient into CONGRUENCE, the cold man at the bus terminal and the arthritis sufferer's dead fish handshake into CONTEXT, and the vocabulary-versus-gesticulation finding into STATUS. Then place the ageing card showing how the five-year-old's hand slap becomes the adult's nose touch.",
        "A wall matrix with four columns labeled CLUSTER, CONGRUENCE, CONTEXT and STATUS; cards fly into place, a head-scratch man with dandruff and flea icons, a folded-arms politician behind a lectern, Freud's patient slipping her wedding ring, a shivering man at a bus terminal, a dead fish handshake, and a chart plotting vocabulary against gesticulation while an age slider runs from five years old to fifty.",
        [
            "One of the most serious mistakes a novice in body language can make is to interpret a solitary gesture in isolation of other gestures or other circumstances.",
            "Scratching the head can mean dandruff, fleas, sweating, uncertainty, forgetfulness or lying, depending on the other gestures that occur at the same time, so we must always look at gesture clusters for a correct reading.",
            "Like any other language, body language consists of words, sentences and punctuation, with each gesture like a single word that may have several different meanings, and it is only when the word is put into a sentence with other words that its meaning is fully understood.",
            "Gestures come in sentences and invariably tell the truth about a person's feelings or attitudes, and the perceptive person is one who can read the non-verbal sentences and accurately match them against the person's verbal sentences.",
            "The critical evaluation gesture cluster in Figure 5 shows the hand-to-face gesture with the index finger pointing up the cheek, another finger covering the mouth and the thumb supporting the chin, plus tightly crossed legs, an arm crossing the body, and head and chin down, saying something like I don't like what you are saying and I disagree with you.",
            "If a listener's words and gestures match or are consistent they are congruent, but if he claims to be enjoying what you say while his gestures show disagreement, he would be lying because his words and gestures would be incongruent.",
            "Research shows that non-verbal signals carry about five times as much impact as the verbal channel and that, when the two are incongruent, people rely on the non-verbal message and the verbal content may be disregarded.",
            "A high ranking politician may stand behind a lectern with his arms tightly folded across his chest and chin down while telling his audience how receptive and open he is to the ideas of young people.",
            "Sigmund Freud once noted that while a patient was verbally expressing happiness with her marriage, she was unconsciously slipping her wedding ring on and off her finger, and he was not surprised when marriage problems began to surface.",
            "Observation of gesture clusters and congruence of the verbal and non-verbal channels are the keys to accurate interpretation of body language.",
            "All gestures should be considered in the context in which they occur: arms and legs tightly crossed with chin down at a bus terminal on a chilly winter's day most likely means the person is cold, but the same gestures across a table during a sale can be correctly interpreted as negative or defensive.",
            "Linguistics research shows a direct relationship between the amount of status, power or prestige a person commands and his range of vocabulary, and non-verbal research reveals that status, power or prestige is also directly related to the number of gestures or body movements he uses, so the higher a person is on the socio-economic scale, the less gesticulation and body movement he uses.",
        ],
    ),
    "boss": (
        "Boss Level: Faking It, Lying and Learning to Read the Body",
        "Your mission is to defeat the final boss, the question of whether body language can be faked: hold the faker's open palms up to the light and catch the microgestures, contract his pupils, lift his eyebrow and twitch the corner of his mouth, then walk the fail-safe tilt mechanism, the Miss World charm school, the politician's charisma and Freud's failings. Then stage the lying gauntlet: the subconscious nervous energy, the refined gestures of politicians, lawyers and actors, the split-second microgestures seen on slow motion cameras, the police interrogation room, and the best way to lie over the telephone. Finish with the training ground: fifteen minutes a day, the airport spectrum, and turning the television sound down.",
        "A boss arena that is a police interrogation room with a suspect under lights in full view, while a slow motion camera freezes a microgesture mid-frame; on one wall the faker's open palms flash honesty while his eyebrow lifts, and on the other an airport concourse fills with travellers showing eagerness, anger, sorrow and happiness while a television silently plays captioned scenes.",
        [
            "The general answer to whether you can fake your own body language is no, because of the lack of congruence that is likely to occur in the use of the main gestures, the body's microsignals and the spoken words.",
            "Open palms are associated with honesty, but when the faker holds his palms out and smiles at you as he tells a lie, his microgestures give him away as his pupils contract, one eyebrow lifts or the corner of his mouth twitches, so the receiver tends not to believe what he hears.",
            "The human mind seems to possess a fail-safe mechanism that registers tilt when it receives a series of incongruent non-verbal messages.",
            "In a Miss World or Miss Universe contest each contestant uses studiously learned body movements to give the impression of warmth and sincerity, yet even the experts can only fake body language for a short period of time and eventually the body emits signals independent of conscious actions.",
            "Many politicians are experts in faking body language in order to get the voters to believe what they are saying, and the politician who can successfully do this is said to have charisma.",
            "The face is used more often than any other part of the body to cover up lies, as we use smiles, nods and winks in an attempt to cover up, but our body signals tell the truth and there is a lack of congruence between our body gestures and facial signals.",
            "The difficulty with lying is that the subconscious mind acts automatically and independently of our verbal lie, so our body language gives us away, and people who rarely tell lies are easily caught regardless of how convincing they may sound.",
            "During the lie the subconscious mind sends out nervous energy that appears as a gesture that can contradict what the person said, and people whose jobs involve lying, such as politicians, lawyers, actors and television announcers, have refined their body gestures to the point where it is difficult to see the lie.",
            "If you tell a deliberate lie to an acquaintance and make a conscious effort to suppress all body gestures while your body is in full view, numerous microgestures will still be transmitted, including facial muscular twitching, expansion and contraction of pupils, sweating at the brow, flushing of the cheeks and increased rate of eye blinking.",
            "Research using slow motion cameras shows that these microgestures can occur within a split second, and only people such as professional interviewers, sales people and those we call perceptive can consciously see them during a conversation or negotiation.",
            "Police interrogation involves placing the suspect on a chair in the open or under lights with his body in full view of the interrogators because his lies are much easier to see under those circumstances, while telling lies is easier behind a desk, a fence or a closed door, and the best way to lie is over the telephone.",
            "To learn body language, set aside at least fifteen minutes a day to study and read the gestures of other people, as well as acquiring a conscious awareness of your own gestures, and use television by turning down the sound and checking your reading every five minutes until you can watch an entire program without sound, just as deaf people do.",
        ],
    ),
}
