# -*- coding: utf-8 -*-
"""Phase 2 chapter data for Predictably Irrational (Dan Ariely), chapters 11-15.
Each chapter: num, title, pages, domain, and 5 slots (scrub/dialogue/audit/matrix/boss),
each slot a 4-tuple (topic, player_mission, visual_frame_description, key_concepts[10-12]).
"""

D = "Behavioral Economics | Metacognition"

CHAPTERS = [
    {
        "num": 11,
        "title": "Chapter 11: The Power of Price",
        "pages": "183-201",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Price Tag Placebo Lab",
            "Scan 12 everyday scenes where a price tag looms over a product or a pill, and identify where the price is silently changing the experience. Name the price-driven placebo effect at work, trace it to the Veladone or SoBe data, and decide whether the buyer's belief amplified or sabotaged the outcome.",
            "A white laboratory corridor lined with floating price tags, each glowing tag dripping into a glass pill capsule while test subjects in electrode gear report pain levels on wall-mounted touch screens.",
            [
                "In the Veladone-Rx experiment the capsule was just vitamin C, yet almost all participants reported pain relief when they believed they had taken an opioid painkiller",
                "When the Veladone price was cut from $2.50 to 10 cents, only half of the participants experienced pain relief instead of almost all of them",
                "The link between price and placebo effect was strongest for people with more recent experience of pain, who depended more on pain medications",
                "In the Iowa cold-medicine study, the 13 students who paid list price reported significantly better medical outcomes than the 16 who bought discount drugs",
                "SoBe drinkers who paid the full price reported less fatigue after exercise than those who bought the same drink for about one-third of the price",
                "Price made a difference of about 28 percent in performance: full-price SoBe drinkers and non-drinkers averaged about nine of 15 anagrams, while discounted-drinkers averaged 6.5",
                "When the quiz cover claimed that more than 50 scientific studies supported SoBe, the discounted group gained 0.6 extra answers while the full-price group gained 3.3",
                "Consumers who stopped to reflect on the relationship between price and quality were far less likely to assume that a discounted drink was less effective",
                "The effect of discounts on perceived quality is largely an unconscious reaction to lower prices",
                "Beliefs and expectations affect not only how we perceive sights and tastes but also our subjective and even objective experiences, sometimes profoundly",
            ],
        ),
        "dialogue": (
            "Dialogue: The Veladone Clinic Interview",
            "Play both the Vel Pharmaceuticals representative greeting participants in a crisp business suit and the participant hooked to the electrical shock generator. Run the brochure pitch, the shock calibration, and the pain ratings, then switch sides and decide whether a discounted Veladone still earns its pain relief.",
            "A staged MIT Media Lab medical office with stale magazines, a cup of Veladone-logo pens, and a shock machine whose green-gel electrodes pulse as a visual pain analog line fills the wall screen.",
            [
                "Veladone-Rx was presented as an exciting new medication in the opioid family, with brochures claiming that over 92 percent of patients in double-blind studies reported significant pain relief within 10 minutes",
                "The brochure priced a single dose of Veladone at $2.50",
                "Participants rated pain on a visual pain analog ranging from 'no pain at all' to 'the worst pain imaginable'",
                "Taya Leary, a young woman with a hint of a Russian accent, was presented as a representative of Vel Pharmaceuticals",
                "The experiment involved about 100 adult Bostonians at the MIT Media Lab",
                "The shock generator delivered painful electrical shocks through electrodes that encircled the wrists, greased with a green electrode gel",
                "Participants were told it would take about 15 minutes for the drug to reach its maximal effect",
                "Rebecca Waber, wearing the white coat of a lab technician with a stethoscope, asked about medical history and listened to the heart before the shocks began",
                "Placebo comes from the Latin for 'I shall please' and was used in the fourteenth century for sham mourners hired to wail at funerals",
                "The two mechanisms that make placebos work are belief, or confidence in the drug, procedure, or caregiver, and conditioning, like Pavlov's dogs",
                "Expectation of pain relief can unleash hormones and neurotransmitters such as endorphins and opiates that block agony and trigger the same receptors as morphine",
                "Lying in the burn ward, Ariely's brain began secreting pain-dulling opioids as soon as he saw the nurse approaching with a needle",
            ],
        ),
        "audit": (
            "Audit: The Price-Efficacy Field Log",
            "Spend an afternoon auditing medical procedures, cold remedies, and pricey brand purchases for placebo contamination, and log each one as belief-driven or chemically driven. For every entry, record the study that tests it and classify whether the evidence supports real efficacy or a placebo effect.",
            "A hospital ward floating in data overlays where surgery tables split into real and sham halves, and a field notebook stamps each procedure with a 'placebo' or 'real effect' seal.",
            [
                "In 1955 cardiologist Leonard Cobb performed real internal mammary artery ligation on half his patients and fake surgery on the other half, and both groups reported immediate relief lasting about three months",
                "Electrocardiograms showed no difference between patients who had their mammary arteries constricted and those who got the placebo operation",
                "Dr. Moseley's arthroscopic knee surgery study with 180 patients found that the placebo group got the same relief from pain and improvements in walking as the groups that had the actual operations",
                "The Moseley study appeared as the lead article in the New England Journal of Medicine on July 11, 2002, and its authors questioned whether the $1 billion spent on the procedures might be put to better use",
                "When researchers tested the six leading antidepressants, they noted that 75 percent of the effect was duplicated in placebo controls",
                "When physicians drilled holes in the skulls of patients without performing the full brain surgery for Parkinson's disease, the sham-surgery patients had the same outcome as those who got the full procedure",
                "Encainide, flecainide, and mexiletine were widely prescribed off-label for irregular heartbeat and were later found to cause cardiac arrest",
                "Placebos run on the power of suggestion and are effective because people believe in them",
                "Branding, packaging, and the reassurance of the caregiver can make us feel better, and a doctor's enthusiasm for a treatment may predispose us toward a positive outcome",
                "Surgeons cut remnants of scar tissue out of the abdomen for chronic pain until controlled studies faked the procedure and patients reported equal relief",
                "A study done in 2003 found that more than one-third of patients who received antibiotics for a sore throat were later found to have viral infections",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Real Cure vs Placebo Ritual",
            "Sort a wall of historical and modern remedies into two bins: chemically active medicine or placebo ritual. For each cure, name the belief that carried it and predict whether a controlled trial would reveal real efficacy.",
            "A museum of medicine with glass jars labeled 'eye of toad,' 'mummy powder,' and 'worm secretions' sliding along conveyor belts toward two sorting chutes marked REAL and RITUAL.",
            [
                "In 1794 the Italian physician Gerbi rubbed the secretions of a certain type of worm on aching teeth, and 68 percent of his patients reported that their pain went away for a year",
                "Egyptian mummy ground to powder was believed to remedy epilepsy, abscesses, rashes, fractures, paralysis, migraine, and ulcers, and could still be ordered through the E. Merck catalog as late as 1908",
                "A seventeenth-century 'cure all' recipe called for the fresh corpse of a red-haired, uninjured, unblemished 24-year-old man killed no more than one day before",
                "The royal touch of medieval kings was said to have cured thousands of people of scrofula, and Charles II was said to have touched some 100,000 people during his reign",
                "The royal touch continued until the 1820s, by which time monarchs were no longer considered heaven-sent",
                "Airborne was invented by Victoria Knight-McDowell, a second-grade teacher from California, and its maker agreed to pay $23.3 million in a settlement for false advertising",
                "After the settlement, the former 'miracle cold buster' was demoted to a simple dietary supplement made from 17 vitamins, minerals, and herbs",
                "Learning the truth about Airborne destroyed Ariely's placebo benefit, because he could no longer believe in the fizzy miracle",
                "Before recent times almost all medicines were placebos, including eye of toad, wing of bat, dried fox lungs, mercury, mineral water, and an electric current",
                "When Lincoln lay dying, his physician applied ground Egyptian mummy, called 'mummy paint,' to the wounds",
            ],
        ),
        "boss": (
            "Boss Battle: The Jobst Suit Trial",
            "Lead a review board deciding whether expensive treatments and placebo procedures should be tested, while a burn patient's story hangs in the balance. Weigh the ethics of sham surgery against the cost of untested treatments, then approve or reject each procedure with a written rationale.",
            "A hospital boardroom where a transparent Jobst suit rises from a patient bed, and each decision stamp glows green or red while a gallery of past placebo trials watches from the walls.",
            [
                "Ariely's Jobst pressure suit, hyped as a healing garment for burns, provided him months of itching, aching, and torn new skin with no real benefits",
                "The Jobst suit was skinlike and meant to press against the skin so that the redness and hypergrowth of the scars would decrease",
                "The areas of his body that were better covered by the suit looked and felt no different from the areas that were not as well covered",
                "Ariely argues that his wasted suffering, and the suffering of other patients like him, is the real cost of not doing placebo experiments",
                "There was an outcry against Cobb's sham operations, raising the ethical question of sacrificing some individuals to learn whether a procedure should be used on others",
                "Without enough placebo experiments, hundreds or thousands of people undergo useless but risky operations",
                "Very few surgical procedures in the United States are tested scientifically",
                "Physicians provide placebos all the time, and America spends more of its GDP per person on health care than any other Western nation",
                "The perception of value, in medicine, soft drinks, drugstore cosmetics, or cars, can become real value",
                "We cannot and should not always do placebo tests, but Ariely feels that we are not doing nearly as many of them as we should",
                "Doctors may hand out antibiotics for viral colds because most patients expect to walk out with a prescription",
                "The trade-offs of not carrying out placebo experiments can result in thousands of people undergoing useless operations",
            ],
        ),
    },
    {
        "num": 12,
        "title": "Chapter 12: The Cycle of Distrust",
        "pages": "201-215",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Fine-Print Catch Finder",
            "Scan 12 marketing offers and find the catch in each one: the seven-point font, the fake degree, the wonder pill, and the free month of cable. Name the trust-eroding tactic and predict how each scam ripples distrust through the industry.",
            "A city street where each billboard entices passersby and then cracks open to reveal its fine print, while a ripple meter shows distrust spreading from each ad to the whole market.",
            [
                "Ariely's local cable company promised one month of free digital cable that actually cost $60, with the terms explained in the seven-point font at the bottom of the ad",
                "Ariely was offered another Ph.D. that would not require five years of hard labor, but the organization dropped him from its list after he contacted them",
                "Marian Friestad and Peter Wright suggested that people are starting to understand that companies' offers are in their best interest and not ours, making us more distrustful of everyone",
                "Wonder-pill salespeople erode trust not only for themselves but make it more difficult to believe those who truly deserve to be trusted",
                "In the film Little Big Man, the snake-oil salesman Merriweather sold a miracle drug that was really a brew concocted from rattlesnake heads, and people got sick after swallowing it",
                "Rexall Americanitis Elixir in 1903 was 'especially recommended for nervous disorders, exhaustion, and all troubles arising from Americanitis'",
                "People are willing to forgive a bit of lying, and many corporations get away with lying in their advertisements at least temporarily",
                "When marketers persist in pulling bait-and-switch tactics, mistrust bites back and sinks its sharp teeth not only into the perpetrator but also into others",
                "The cable company that betrayed Ariely's trust hurt its whole industry by causing consumers like him to mistrust telecommunications companies in general",
                "Distrust spreads like a pebble dropped into a still pond, creating tiny waves that end up affecting business and society as a whole",
            ],
        ),
        "dialogue": (
            "Dialogue: The Free Money Booth",
            "Play both the wary passerby and the smiling undergraduate staffing a 'Free Money' booth in a Cambridge commercial center. Run the exchange, choose whether to take the bill, and then switch sides and measure how deep your own suspicion runs.",
            "A sunny Cambridge plaza booth draped with a large 'Free Money' sign, piles of bills on the table, and wary pedestrians walking slow circles around it while a trust-meter ticks below 20 percent.",
            [
                "When the booth offered $1, only 1 percent of those who passed stopped to check it out",
                "Even when the sign said $50, only 19 percent of passersby stopped and took a bill",
                "Wary passersby asked 'Is this a trick?', 'Is there something I have to sign?', and 'There must be a catch' before taking a bill",
                "People who chose to ignore the booth said they believed the offer was some kind of scheme",
                "Economists claim that there are no $100 bills lying on the sidewalk, because if there were, someone would have already picked them up",
                "People might have expected to do something in return, like answer a short survey, yet the vast majority believed the offer was not even worth asking about",
                "The researchers chose to measure distrust through behavior rather than a self-report scale because people often have wrong intuitions about their own behavior",
                "The free money experiment was run by undergraduate students at a big commercial center in Cambridge, Massachusetts",
                "Reassured passersby would take a bill, hold it up for a second as if waiting for something to happen, then walk away slowly before picking up their pace",
                "The booth's front sign indicated how much money would be given away, showing $1, $5, $10, $20, or $50 at different times",
            ],
        ),
        "audit": (
            "Audit: The Trust Erosion Field Log",
            "Spend a day logging every broken promise, inflated claim, and defected deal you witness, and classify each as an act of defection. For every entry, record how the loss of trust raises the cost of the next transaction.",
            "A fishing village on a depleted salmon river where a field notebook logs each defector's over-catch while a commons pasture fades to bare dirt.",
            [
                "The phrase 'tragedy of the commons' traces back to Oxford professor William Forster Lloyd, who described the phenomenon in his 1833 book on population",
                "In medieval England, parishes had common land on which each member could graze a limited number of cattle, and farmers who added animals left the grass dwindling and all livestock malnourished",
                "If a few individuals get greedy and use more than their share of a common resource, the system becomes unsustainable and in the long term everybody loses",
                "Social scientists refer to those who betray social contracts as 'defectors'",
                "Wild salmon populations are depleted because it is more profitable for an individual fisherman to overfish in a given year, so salmon fishermen are now constrained by law to a limited number",
                "In the Public Goods Game, if all four players contributed their $10, the pot would double and each would take away $20, but a defector like Bernie keeps his $10 and takes $25 while contributors get $15",
                "After experiencing a defection, players contribute less, and when nobody trusts anybody, each player ends each round with just the $10 he started with",
                "Distrust is infectious: when we see people defect by lying in their advertisements, we start acting similarly and trust deteriorates",
                "Trust is a public good like clean air and water, and higher trust makes financial transitions smoother and contracts simpler",
                "In online dating, men cared mostly about women's weight and women cared mostly about men's height and income, so both men and women cheat just a little when describing themselves",
                "An honest 5'9\" man earning $60,000 is penalized because women reading his profile assume his real height is 5'8\" or 5'7\", lowering his market value",
                "Résumé inflation spreads because students believe everyone exaggerates a bit, so a two-month internship in Paris becomes 'fluent in French'",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Source vs Substance",
            "Sort statements and product reviews by whether their credibility comes from the source or the substance. Decide whether the truth survives when a brand's name, a party's label, or a company's brochure gets attached to it.",
            "A courtroom where 'the sun is yellow' and 'a camel is bigger than a dog' float as exhibits while logos stamp across them, and a trust gauge shows truth wobbling under each stamp.",
            [
                "One hundred percent of participants agreed that 'the sun is yellow' and 'a camel is bigger than a dog' were completely unambiguous true statements",
                "When the same statements were attributed to Proctor & Gamble, the Democratic Party, or the Republican Party, participants hedged their bets and questioned them",
                "Participants rationalized doubts by imagining red spots on the sun's surface or a bull mastiff versus a newborn camel",
                "The level of distrust, owing to the origin of a statement, was so high that it influenced participants' ability to identify obviously correct statements",
                "Students liked a Cambridge Audio stereo much more when the brochure they read supposedly came from Consumer Reports than when it came from the manufacturer",
                "Participants said they would pay, on average, about $407 for the stereo after reading the Consumer Reports brochure versus $282 after the Cambridge Audio brochure",
                "Mistrust in marketing information runs so deeply that it colors our entire perception even in the face of firsthand, direct experience",
                "When shown the 'free digital cable' ad, the vast majority of people expected the free offer to really cost them somewhere between $10 and $70",
                "People who had prior experience with the cable provider estimated the real cost of the offer much higher than those who had never done business with it",
                "Those who had been burned before revised their trust in anything that originated from that company",
            ],
        ),
        "boss": (
            "Boss Battle: The Tylenol Crisis Command",
            "Take command of a corporation in crisis and decide how to restore public trust after a product disaster. Choose between transparency, sacrifice, and silence, and see whether your market share and share price recover.",
            "A war-room board showing a cyanide-laced capsule, a recalled product line, and a triple-sealed package rising while a stock chart climbs back toward 30 percent.",
            [
                "In September 1982, seven people in the Chicago area died after ingesting Extra Strength Tylenol capsules that a pharma-terrorist had adulterated with cyanide",
                "Johnson & Johnson quickly and voluntarily halted Tylenol production, withdrew all Tylenol capsule products from the market, and urged the return of all previously purchased capsules",
                "The company ultimately destroyed millions of bottles of Tylenol at a cost of more than $100 million",
                "Tylenol's market share, previously more than a third of U.S. painkiller sales, dropped dramatically and many experts predicted the demise of the brand",
                "Tylenol was reintroduced in a tamper-resistant triple safety-sealed container and its market share recovered to 30 percent one year later",
                "Johnson & Johnson's share price recovered within two months, and the Tylenol case remains the overly cited paradigm of effective crisis management",
                "Comcast's director of digital care Frank Eliason searched the internet for the word 'Comcast' to locate unhappy customers and contacted them about their problems before they became formal complaints",
                "Transparency acts as a commitment device that forces companies to behave in trustworthy ways, since flagrant misbehavior is harder to get away with in a publicly exposed world",
                "Timberland CEO Jeff Swartz said he had not found an economic return for his environmental actions but wanted his company to follow the moral principles he wanted his kids to live by",
                "Aesop's 'The Boy Who Cried Wolf' teaches that when market defectors spread false claims, more of us increase our distrust and cast even obvious truths into doubt",
                "The banking crisis of 2008 left the U.S. economy in tears, and the multiple bailouts and new regulations that followed did little to heal the broken trust",
                "Trust, once eroded, is very hard to restore, and repairing the public trust will take a very long time",
            ],
        ),
    },
    {
        "num": 13,
        "title": "Chapter 13: The Context of Our Character, Part I",
        "pages": "215-233",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Honesty Baseline Lab",
            "Scan 12 test-room scenes and spot where cheating is happening: the transferred answers, the shredded worksheets, and the hands dipping into the money jar. Name each condition, compare its claimed score to the 32.6 baseline, and say whether the risk of being caught mattered.",
            "A university exam hall where bubble sheets glow with pre-marked gray answers, a shredder chews worksheets, and a coin jar shines at the front while a scoreboard ticks claimed answers.",
            [
                "The control group at the Harvard Business School, with no opportunity to cheat, solved on average 32.6 of the 50 questions",
                "Students who transferred answers to a bubble sheet with the correct answers pre-marked in gray claimed to have solved on average 36.2 questions, catching them in a bit of cheating by about 3.6 questions",
                "Students who were also asked to shred their worksheets claimed on average 35.9 correct answers, about the same as the group that did not shred",
                "Students who shredded both sheets and withdrew their earnings from a money jar claimed on average 36.1 answers, and none took more money than they claimed",
                "When given the opportunity, the majority of people cheated, and they cheated just a little bit",
                "The probability of being caught did not have much influence on dishonesty: shredding the evidence completely did not push cheating farther",
                "Similar honesty experiments were conducted at MIT, Princeton, UCLA, and Yale with similar results",
                "The money jar contained about $100, and every student could have claimed a perfect test score, but none of them did",
                "In a recent survey of nearly 36,000 high school students in the United States, 98 percent said it was important to be honest",
                "The test consisted of 50 multiple-choice questions similar to standardized tests, like 'Who wrote Moby-Dick?'",
                "In the control condition, students handed both the worksheet and the bubble sheet to a proctor at the front of the room and were paid 10 cents per correct answer",
            ],
        ),
        "dialogue": (
            "Dialogue: The Bubble Sheet Interrogation",
            "Play both the proctor who pays 10 cents a question and the Harvard student who just saw the gray-marked correct answers on the bubble sheet. Run the transfer, watch the cheat, and then switch sides and decide how many answers you claim as you walk to the money jar.",
            "A colonial Harvard exam room where gray bubbles highlight correct answers on every sheet, and a proctor counts claimed scores as a shredder hums in the corner.",
            [
                "The Harvard test had 50 multiple-choice questions, 15 minutes to answer them, and 10 cents paid for every correct answer",
                "The bubble sheet had the correct answers pre-marked, with the bubble indicating the correct answer colored gray for each question",
                "In the final condition, students were instructed to destroy the worksheet and the pre-marked bubble sheet, then walk to a jar full of coins, withdraw their earnings, and leave",
                "Students in the second condition could decide to lie and mark the correct answer on the bubble sheet even if they had chosen wrong on their worksheet",
                "Adam Smith held that nature endowed man with 'an original desire to please, and an original aversion to offend his brethren'",
                "Freud said that as we grow up in society we internalize the social virtues, leading to the development of the superego",
                "Returning a lost wallet to its owner stimulates the reward centers of the brain, the nucleus accumbens and the caudate nucleus",
                "The internal honesty monitor is active only when we contemplate big transgressions, while for little ones like taking a single pen the superego stays asleep",
                "The cost-benefit analysis, and the probability of getting caught in particular, does not seem to have much influence on dishonesty",
                "One type of dishonesty belongs to crooks circling a gas station weighing the money in the till and the punishment if caught, while a second type is committed by people who generally consider themselves honest",
            ],
        ),
        "audit": (
            "Audit: The Workplace Dishonesty Ledger",
            "Audit a year of corporate and white-collar dishonesty: workplace theft, padded insurance claims, the tax gap, and returned-clothes fraud. For each figure, compare it against the $525 million robbery total and decide which crime is the real drain.",
            "A skyscraper ledger where columns of dollars cascade: $600 billion from employees, $24 billion in bogus claims, and a $350 billion tax gap, while a mugger's haul shrinks to pocket change beside them.",
            [
                "In 2004 the total cost of all robberies in the United States was $525 million, with an average loss from a single robbery of about $1,300",
                "Employees' theft and fraud at the workplace are estimated at about $600 billion every year",
                "Individuals add a bogus $24 billion to their property-loss claims each year, and the IRS estimates a loss of $350 billion a year in the tax gap",
                "The retail industry loses $16 billion a year to customers who buy clothes, wear them with the tags tucked in, and return them for a full refund",
                "Property crime including robbery, burglary, larceny-theft, and automobile theft totaled about $16 billion in 2004",
                "The Enron scandal of 2001 revealed that an 'America's Most Innovative Company' for six consecutive years owed much of its success to innovations in accounting",
                "The Sarbanes-Oxley Act of 2002 requires the chief executives of public companies to vouch for the firms' audits and accounts",
                "The 'toothpick rule' lets lobbyists serve legislators food they can eat standing up with a toothpick, and the seafood lobby responded by dropping pasta and serving raw oysters",
                "Critics call Sarbanes-Oxley ambiguous, inconsistent, inefficient, and outrageously expensive, and William A. Niskanen said it only forced companies to jump through hoops",
                "White-collar crooks can inflict more financial damage between their ten o'clock latte and lunch than a standard-issue burglar might in a lifetime",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Moral Benchmark vs Temptation",
            "Sort 20 temptation scenarios by whether a moral benchmark is present at the moment of temptation. Decide which groups cheated and which stayed at the 3.1 baseline, then classify each benchmark as effective or inert.",
            "A UCLA lab where half the desks bear parchment lists of the Ten Commandments and half bear book titles, while a scoreboard ticks 4.1 for books and 3.0 for commandments.",
            [
                "In the UCLA matrix test, participants had five minutes to solve 20 problems requiring them to find two numbers that added up to 10, with $10 per correct problem if they won a lottery",
                "When cheating was not possible, participants solved on average 3.1 of the matrix problems",
                "The group that first recalled 10 books they read in high school achieved an average of 4.1 problems solved, or 33 percent more than those who could not cheat",
                "The group asked to recall the Ten Commandments had not cheated at all, averaging three correct answers",
                "Almost none of the participants could recall all ten Commandments, yet the exercise evoked the idea of honesty among them",
                "Students who could remember only one or two Commandments were as affected by them as students who remembered nearly all ten",
                "It was not the Commandments themselves that encouraged honesty, but the mere contemplation of a moral benchmark of some kind",
                "When participants signed the statement 'I understand that this study falls under the MIT honor system,' they claimed exactly three problems, the same as the control group",
                "MIT does not even have an honor code, making the effect of the signed statement particularly amazing",
                "Without the honor statement, participants who pocketed their answer sheets claimed on average 5.5 problems",
                "When we are removed from any benchmarks of ethical thought, we tend to stray into dishonesty, but if we are reminded of morality at the moment we are tempted, we are much more likely to be honest",
                "Oaths and rules must be recalled at, or just before, the moment of temptation to curb dishonesty",
            ],
        ),
        "boss": (
            "Boss Battle: The Honor Code Redesign",
            "Redesign a society's honesty infrastructure: revive professional oaths, place moral reminders at moments of temptation, and roll out a bathroom-note policy. Defend your choices against the erosion of professionalism and see whether the nation's integrity ranking climbs.",
            "A civic design studio where an integrity scoreboard shows the United States sliding from 14th to 20th while engineers pin honor-code posters and notes onto bathrooms, courtrooms, and boardrooms.",
            [
                "The word profession comes from the Latin professus, meaning 'affirmed publicly'",
                "In the 1960s a strong movement to deregulate professions replaced strict professionalism with flexibility, individual judgment, the laws of commerce, and the urge for wealth",
                "A 1990s study by the state bar of California found that two-thirds of attorneys said lawyers compromise their professionalism as a result of economic pressure, and nearly 80 percent said the bar fails to adequately punish unethical attorneys",
                "The Florida bar reported in 2003 that a substantial minority of lawyers were 'money-grabbing, too clever, tricky, sneaky, and not trustworthy'",
                "Rhonda, a reader living in a house near the UC Berkeley campus, stopped toilet-paper hoarding by posting a note in the upstairs bathroom, and fresh rolls reappeared only where the note was placed",
                "In 2002 the United States ranked twentieth in the world in terms of integrity, down from fourteenth in 2000 before the wave of corporate scandals",
                "Denmark, Finland, and New Zealand ranked first in integrity, while Haiti, Iraq, Myanmar, and Somalia ranked last at number 163",
                "The United States holds economic power partly because it is, or is perceived to be, one of the world's most honest nations in terms of corporate governance standards",
                "An Iranian student at MIT told Ariely that business in Iran lacks a platform of trust, so no one pays in advance, no one offers credit, and people must hire within their families",
                "When personal financial benefit stands in opposition to our moral standards, we are able to bend reality and see the world in terms compatible with our selfish interest",
                "We can avoid temptation from the outset by prohibiting physicians from ordering tests that benefit them financially and barring members of Congress from setting their own salaries",
            ],
        ),
    },
    {
        "num": 14,
        "title": "Chapter 14: The Context of Our Character, Part II",
        "pages": "233-244",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Refrigerator Audit",
            "Walk the dorm halls of MIT and audit the communal refrigerators: six Cokes vanish in 72 hours while six one-dollar bills lie untouched. Spot where the line between object and cash runs, and name the rationalization that makes each theft feel innocent.",
            "An MIT dorm corridor lined with open refrigerators where Coke cans dissolve into the void in time-lapse while dollar bills on plates remain frozen in place for exactly 72 hours.",
            [
                "All six cans of Coke that Ariely slipped into MIT communal refrigerators vanished within 72 hours",
                "Plates containing six one-dollar bills, left in other refrigerators, remained untouched for 72 hours until Ariely removed them",
                "People rationalize taking a can of Coke from a communal refrigerator by thinking that we've all had cans of Coke taken from us",
                "Taking a red pencil from work for a daughter feels relatively easy, while taking 10 cents from an open petty cash box feels very hard",
                "Much of the dishonesty in the world involves cheating that is one step removed from cash, such as accounting practices, backdated stock options, and lobbyist-funded parties",
                "Ariely doubts that Enron's Lay, Skilling, and Fastow would have hit a woman with a blackjack and pulled cash from her fingers, though they took millions in pension monies",
                "Cheating is a lot easier when it is a step removed from money",
                "In taking a pencil, we might reason that office supplies are part of our overall compensation, or that lifting a pencil or two is what everyone does",
                "Ariely kept a diary detailing how many of his Coke cans remained in each refrigerator over the following days",
                "The students at MIT also felt differently about taking cash, and the plates of dollar bills remained untouched until Ariely removed them",
            ],
        ),
        "dialogue": (
            "Dialogue: The Token Exchange Room",
            "Play both the MIT cafeteria experimenter who pays in tokens and the student who just tore up the worksheet. Run the 20-math-problem test, hand over the tokens, and then switch sides and watch how many problems you claim when paid in tokens instead of cash.",
            "An MIT cafeteria where students tear up worksheets and walk twelve feet across the room to exchange tokens for 50 cents each, while a cheat-o-meter jumps from 2.7 to 5.9.",
            [
                "Participants who tore up their worksheets and claimed a cash score claimed an average of 6.2 of the 20 problems, 2.7 more than the 3.5 control baseline",
                "Participants paid in tokens claimed an average of 9.4 problems solved, 5.9 more than the control group",
                "When given the same chance to cheat with nonmonetary currency, cheating more than doubled in magnitude",
                "Students walked 12 feet across the room to another experimenter who exchanged each token for 50 cents",
                "Of the 2,000 participants in the studies of honesty, only four ever claimed to have solved all the problems",
                "In the token condition, 24 of the study's 150 participants cheated 'all the way,' equivalent to about 320 per 2,000 participants",
                "All 24 extreme cheaters were in the condition with tokens, not the condition with money",
                "Tokens released people from some of their moral constraints, and for quite a few the release was so complete that they cheated as much as was possible",
                "When asked to predict, students said the amount of cheating would be the same for tokens and cash because the tokens represented real money exchanged within seconds",
                "People did not see how fast we can rationalize our dishonesty when it is one step away from cash",
                "The experiment used 20 simple math problems of finding two numbers that added up to 10, with 50 cents paid per correct answer",
            ],
        ),
        "audit": (
            "Audit: The One-Step-From-Cash Ledger",
            "Audit a year of everyday nonmonetary dishonesty: stretched insurance claims, wardrobing, padded expense reports, blacked-out frequent-flyer miles, and two-cycle billing. For each entry, count the steps between the act and the cash and predict how easily it gets rationalized.",
            "A forensic accounting table where a 27-inch television inflates to 32 inches, a mug becomes an $8 bar drink, and a frequent-flyer card's blackout dates spread like ink through a ledger.",
            [
                "Consumers stretch their home and car insurance loss claims by about 10 percent, so the loss of a 27-inch television is reported as the loss of a 32-inch set",
                "Wardrobing, buying an item of clothing, wearing it, and returning it in a state the store cannot resell, costs the clothing industry about $16 billion a year",
                "Buying a $5 mug for an attractive stranger was clearly out of bounds on an expense account, but buying the same stranger an $8 drink in a bar was very easy to justify",
                "When people give receipts to their administrative assistants to submit, they are one additional step removed from the dishonest act and more likely to slip in questionable receipts",
                "Businesspeople who live in New York are more likely to consider a gift for their kid a business expense if they bought it at the San Francisco airport than at the New York airport",
                "An airline told Ariely's friend that his saved 25,000 frequent-flyer miles could not be used on any of the dates he wanted, but seats were available everywhere if he used 50,000 miles",
                "The airline stole from Ariely's friend the value of about $450 in the form of requiring 25,000 additional miles rather than taking cash",
                "Two-cycle billing means that the moment you do not pay your bill in full, the credit issuer charges interest on new purchases and also reaches into the past to charge interest on past purchases",
                "An Ohio man who charged $3,200 to his card soon found his debt to be $10,700 because of penalties, fees, and interest",
                "The biggest and most reputable banks, whose advertising makes you believe you are family, would not steal your wallet but apparently would steal with a transaction somewhat removed from cash",
                "When the medium of exchange is nonmonetary, our ability to rationalize increases by leaps and bounds",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Cash vs Nonmonetary Currency",
            "Sort 20 dishonest acts into two bins: direct cash theft or nonmonetary cheating. For each act, weigh the moral distance from the dollar and predict whether the perpetrator feels like a thief.",
            "A sorting line where dollar bills march into a narrow honest chute while tokens, Cokes, pencils, stock options, and Skype minutes funnel into a wide rationalization chute labeled 'one step away.'",
            [
                "The dollar bill seems designed to conjure up a contract, with 'THE UNITED STATES OF AMERICA' in prominent type, George Washington, 'IN GOD WE TRUST,' a pyramid, and an unblinking eye looking right at us",
                "Money is a clear unit of exchange: it is hard to say that a dime is not a dime, or that a buck is not a buck",
                "With nonmonetary exchanges there is always a convenient rationale, and we can be dishonest without thinking of ourselves as dishonest",
                "Upton Sinclair noted, 'It is difficult to get a man to understand something when his salary depends upon his not understanding it'",
                "Someone hacked into Ariely's Skype account and charged his PayPal account a few hundred dollars for calling time",
                "The Skype thief stole calling time rather than money, gained nothing tangible, stole from Skype rather than directly from Ariely, and may have imagined Skype would cover the cost",
                "Electronic transactions with no physical exchange of money might make it easier for people to be dishonest without questioning the immorality of their actions",
                "The dishonesty observed in the experiments was probably the lower boundary of human dishonesty, practiced by individuals who want to be ethical and see themselves as ethical",
                "Even good people are not immune to being partially blinded by their own minds on the road to financial rewards",
                "A Gordon Gekko character who declares that 'greed is good' and uses nonmonetary means to encourage dishonesty can lead astray people who in principle want to be honest",
            ],
        ),
        "boss": (
            "Boss Battle: The Cashless Future Simulator",
            "Design an economy where cash is disappearing and decide how to keep people honest with tokens, points, and stock options. Label every nonmonetary instrument with its cash value and defend your policies as the electronic transaction wave hits.",
            "A futuristic exchange floor where dollar bills vaporize into glowing points, and policy levers labeled 'price tags,' 'monetary wording,' and 'honor priming' control a global cheat gauge.",
            [
                "Credit card profits in the United States rose from $9 billion in 1996 to a record $27 billion in 2004",
                "Banking analysts said that by 2010 there would be $50 billion in new electronic transactions, nearly twice the number processed under the Visa and MasterCard brands in 2004",
                "Cash is a drag on the profits of banks, and they want to get rid of it",
                "The days of cash are coming to a close, and our tendency to cheat is brought to our senses only by the sight of cash",
                "One fix is to label each item in the supply cabinet with a price and to explain stocks and stock options clearly in terms of their monetary value",
                "We need to recognize that once cash is a step away, we will cheat by a factor bigger than we could ever imagine",
                "Willie Sutton allegedly robbed banks because that was where the money was, and by that logic he might be writing the fine print for a credit card company today",
                "The level of deception observed in the experiments is probably an underestimation of what would be found across a variety of circumstances and individuals",
                "If the tokens had not been immediately convertible into money, or the participants had cared less about their honesty, dishonesty would most likely have been even higher",
                "Motivation can play tricks on us whether or not we are good, moral people",
            ],
        ),
    },
    {
        "num": 15,
        "title": "Chapter 15: Beer and Free Lunches",
        "pages": "244-254",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Beer Table Order Watch",
            "Stand at the Carolina Brewery and watch 12 tables order beer aloud and in sequence, spotting each nonconforming choice and each sacrificed favorite. Name the need for uniqueness driving the pick and predict which drinker regrets the choice.",
            "A brick-walled brewery where four glowing beer samples hover over a table, and a halo crowns the first drinker while a frown-meter tracks the later orderers' regret.",
            [
                "The Carolina Brewery is a hip bar on Franklin Street, the main street outside the University of North Carolina at Chapel Hill",
                "When people ordered out loud in sequence, they chose more types of beer per table, in essence opting for variety",
                "The Summer Wheat Ale was not very attractive to most people, but when the other beers were taken, participants felt they had to choose something different to show they had a mind of their own",
                "Those who made their choices out loud were not as happy with their selections as those who made their choices privately",
                "The first person to order in the sequential group was the happiest of the group and just as happy as those who chose their beers in private",
                "None of the double-dating couples took a sip of anyone else's beer sample",
                "The four beers offered were the Copperline Amber Ale, Franklin Street Lager, India Pale Ale, and Summer Wheat Ale",
                "In a later Duke study with wine samples and MBA students, the tendency to select a different beverage correlated with the personality trait 'need for uniqueness'",
                "People may sacrifice the pleasure of a particular consumption experience in order to project a certain image to others",
                "Participants who ordered out loud often ended up with a beer they did not really want or like",
            ],
        ),
        "dialogue": (
            "Dialogue: The Carolina Brewery Waitstaff",
            "Play both the waiter in the brewery apron reading the beer menu aloud and the table of patrons ordering in turn. Run the public orders, then the private written orders, and then switch sides and discover whether a familiar face breaks your poker face.",
            "A brewery table where a waiter with a notepad recites beer descriptions while a menu with checkboxes passes to each patron, and a split screen shows the same table ordering in silence.",
            [
                "Ariely approached the tables and took their sample orders within one minute of their sitting down, as the brewery manager required",
                "For the first 50 tables, participants said their beer choice out loud; for the next 50 tables, they wrote their preferred beer on a small menu",
                "Writing down the order transformed ordering from a public event into a private one, so each participant would not hear what the others ordered",
                "The MIT accountants needed convincing that a $1,400 bill for beer was a legitimate research expense",
                "Ariely recognized Rich, a computer science graduate student he had worked with years before, but had to put on a poker face and describe the beers matter-of-factly",
                "Rich kept trying to chat and told Ariely he had recently read one of his papers and liked it, apparently trying to make him feel better about his job as a beer server",
                "In Hong Kong, individuals who selected food in public chose items they did not like as much but were more likely to select the same item as the people ordering before them",
                "In cultures where the need for uniqueness is not considered a positive trait, people who order aloud try to portray a sense of belonging and express more conformity",
                "People who order food and drinks seem to have two goals: to order what they will enjoy most and to portray themselves in a positive light in the eyes of their friends",
                "Jonathan Levav, a professor at Columbia, collaborated with Ariely on the beer experiment at the Carolina Brewery",
            ],
        ),
        "audit": (
            "Audit: The Decision Illusion Field Log",
            "Spend a day logging every decision you make at a menu, a store, or a pricing screen, and classify each as rational or predictably irrational. For every entry, record the invisible force - relativity, emotion, context - that steered it and note how you could have resisted.",
            "A restaurant menu suspended in a brain-scan chamber where each dish glows with hidden influences, and a field notebook auto-classifies orders while a driver's-seat illusion flickers on a wall screen.",
            [
                "The main lesson of the book is that we are pawns in a game whose forces we largely fail to comprehend",
                "We usually think of ourselves as sitting in the driver's seat with ultimate control over our decisions, but this perception has more to do with our desires than with reality",
                "We fall for the decision illusions our minds show us, just as we cannot help being fooled by visual illusions",
                "By the time we comprehend and digest information, it is not necessarily a true reflection of reality but our representation of reality",
                "Our natural tendency is to vastly underestimate or completely ignore the power of influences such as emotions, relativity, and social norms",
                "These influences affect experts as well as novices in systematic and predictable ways",
                "Although irrationality is commonplace, it does not necessarily mean that we are helpless",
                "Once we understand when and where we may make erroneous decisions, we can be more vigilant, force ourselves to think differently, or use technology to overcome our shortcomings",
                "We are limited to the tools nature has given us, and the natural way in which we make decisions is limited by the quality and accuracy of those tools",
                "The resulting mistakes are simply how we go about our lives, how we do business; they are a part of us",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Rational vs Predictably Irrational",
            "Sort 20 decisions into two bins: the behavior standard economics predicts and the behavior behavioral economics observes. For each entry, state the rational assumption and name the systematic mistake people actually make.",
            "A courtroom debate where a chalkboard of rational-assumption equations faces a wall of real-world data streams, and each decision card is stamped by either 'maximizer' or 'human.'",
            [
                "Standard economics assumes that we are rational, know all the pertinent information about our decisions, can calculate the value of the different options, and are cognitively unhindered in weighing each potential choice",
                "The standard economics perspective suggests that even if we make a wrong decision, we will quickly learn from our mistakes on our own or with the help of market forces",
                "Behavioral economics is based on how people actually behave instead of how they should behave",
                "Our irrational behaviors are neither random nor senseless; they are systematic and predictable",
                "We all make the same types of mistakes over and over because of the basic wiring of our brains",
                "Standard economics asserts that there are no free lunches, because if there were any, someone would have already found them and extracted all their value",
                "Behavioral economists believe people are susceptible to irrelevant influences from their immediate environment, irrelevant emotions, shortsightedness, and other forms of irrationality",
                "From the standard economic perspective, people who are not saving enough for retirement are saving exactly the amount they want to save",
                "Behavioral research shows that people procrastinate, have a hard time understanding the real cost of not saving, and find consumption habits easy to create and hard to give up",
                "The behavioral economics view, which acknowledges human deficiencies, is more depressing, but the silver lining is that making mistakes also means there are opportunities for free lunches",
            ],
        ),
        "boss": (
            "Boss Battle: The Free Lunch Architect",
            "Design interventions that give everyone net benefits: a save-more-tomorrow retirement plan, an order-first dining protocol, and a self-control credit card. Deploy your free lunches, watch the saving rate climb from 3.5 percent to 13.5 percent, and defend them to the rationalists.",
            "A policy design studio where a retirement chart climbs from 3.5 to 13.5 percent as employees sign future-raise pledges, and a restaurant switches to anonymous order cards.",
            [
                "'Save more tomorrow,' proposed and tested by Dick Thaler and Shlomo Benartzi, asks new employees what percentage of their future salary raises they would be willing to invest in the retirement plan",
                "In Thaler and Benartzi's test, employee saving rates increased from about 3.5 percent to around 13.5 percent over the next few years",
                "It is difficult to sacrifice consumption today for saving in the distant future, but psychologically easier to sacrifice future consumption or a share of a raise one does not yet have",
                "Free lunches are mechanisms that provide net benefits to all parties involved, even when implementing them involves a cost",
                "The new and innovative credit card described in Chapter 7, on self-control, could help people exercise more self-control within the domain of spending",
                "Restaurant owners should ask their customers to write out orders privately so that no customer will be influenced by the orders of his or her companions",
                "When you go to a restaurant, it is a good idea to plan your order before the waiter approaches you and stick to it",
                "If you are afraid you might be swayed by others, a useful strategy is to announce your order to the table before the waiter comes",
                "The best option is to order first, since the first orderer is unencumbered by other people's choices",
                "Businesses and policy makers could revise their thinking and design their policies and products so as to provide free lunches",
                "As the Nobel laureate Murray Gell-Mann once said, 'Think how hard physics would be if particles could think'",
            ],
        ),
    },
]
