# -*- coding: utf-8 -*-
"""Phase 2 chapter data for Predictably Irrational (Dan Ariely), chapters 6-10.
Each chapter: num, title, pages, domain, and 5 slots (scrub/dialogue/audit/matrix/boss),
each slot a 4-tuple (topic, player_mission, visual_frame_description, key_concepts[10-12]).
"""

D = "Behavioral Economics | Metacognition"

CHAPTERS = [
    {
        "num": 6,
        "title": "Chapter 6: The Influence of Arousal",
        "pages": "104-121",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Hot-Cold Prediction Switch",
            "Move through the nineteen sexual-preference questions, five immorality questions, and five safe-sex questions, tagging each answer as cold-state or hot-state. Spot which numbers balloon under arousal - sexual preferences up 72 percent, immoral intent up 136 percent, condom skipping up 25 percent - and judge whether any cold-state forecast survives contact with the red zone of the arousal meter.",
            "A darkened Berkeley dorm room where a Saran-wrapped laptop glows on a bed; an arousal meter swings toward the red high zone while two answer columns, cold predictions and hot predictions, split apart on the wall.",
            [
                "In 2001 Ariely and George Loewenstein studied how rational, intelligent people predict their attitudes when in an impassioned state, using 25 male Berkeley students",
                "Participants answered questions in a cold, rational state and later while aroused by erotic pictures and masturbation, using a Saran-wrapped laptop and a 12-key keypad",
                "Across 19 questions about sexual preferences, aroused participants predicted their desire to engage in odd sexual activities would be 72 percent higher than they predicted when cold",
                "On five questions about immoral behaviors like date rape, aroused participants predicted their propensity more than twice as high - 136 percent higher - than in the cold state",
                "Despite years of warnings about condoms, participants were 25 percent more likely in the aroused state to predict they would forego condoms",
                "The idea of sexual contact with an animal was more than twice as appealing when aroused (16) as when cold (6), a 167 percent difference",
                "The willingness to slip a woman a drug to increase the chance of sex rose from 5 percent cold to 26 percent aroused, a 420 percent difference",
                "Keeping trying to have sex after a date said no rose from 20 percent cold to 45 percent aroused, a 125 percent difference",
                "Prevention, protection, conservatism, and morality disappeared completely from the radar screen when participants were aroused",
                "The participants revealed in their unaroused state that they themselves did not know what they were like once aroused",
                "Our inability to understand ourselves in a different emotional state does not seem to improve with experience, even for a familiar emotion like sexual arousal",
                "A teenager driving alone is 40 percent more likely to get into an accident than an adult; with one other teenager the rate doubles, and with a third teenager it doubles again",
            ],
        ),
        "dialogue": (
            "Dialogue: The Dr. Jekyll Test",
            "Interrogate Roy, the affable straight-A biology major who plays Chopin etudes, about his decisions in both states: first the cold, superego-driven answers, then the hot answers given while the arousal meter sits in the red zone. Catch the moment his self-understanding collapses, and press him on whether 'Just say no' can possibly hold when passion takes over.",
            "A split-screen dorm room: on the left a calm Roy doing homework under lamplight, on the right a flushed Roy clicking the arousal meter to its bright red high zone as a question pops up on the Saran-wrapped screen.",
            [
                "Roy was typical of the 25 participants: accomplished, intelligent, and kind, with straight A's, the volleyball team captaincy, and a steady girlfriend",
                "In the cold state the participants respected women, were not attracted to odd sexual activities, took the moral high ground, and expected to always use a condom",
                "In the aroused state, prevention, protection, conservatism, and morality vanished from the participants' decisions",
                "Robert Louis Stevenson wrote Dr. Jekyll and Mr. Hyde in 1885 after a nightmare, capturing the Victorian fascination with repressive propriety versus uncontrollable passion",
                "The experiment revealed not just the old story that we are all like Jekyll and Hyde, but that every one of us, regardless of how good we are, underpredicts the effect of passion on behavior",
                "MIT's Sloan School stymied the project with a committee consisting mostly of women; Walter Bender, head of the Media Lab, approved it",
                "The ads posted around Sproul Plaza sought male heterosexual participants 18 and over, offered $10 per session, and warned the experiments could involve sexually arousing material",
                "The committee worried about participants uncovering repressed memories of sexual abuse or discovering they were sex addicts, even though any student with a computer could find graphic pornography",
                "'Just say no' assumes we can turn off passion at will, an assumption the study showed to be false",
                "Avoiding temptation altogether is easier than overcoming it once it has started to lure us in",
                "Sex education should focus less on the physiology and biology of the reproductive system and more on strategies to deal with the emotions that accompany sexual arousal",
                "Before the birth of their first child, Sumi plunged her hands into a bucket of ice for two minutes and afterward clearly understood the appeal of an epidural",
            ],
        ),
        "audit": (
            "Audit: The Emotional-State Field Log",
            "Audit ten real-world decisions from the chapter - condom carrying, teenage speeding, epidurals, angry e-mails, sports-car contracts - and classify each as a cold-state plan or a hot-state outcome. Log the gap between predicted and actual behavior for each, then propose a precautionary device that could be configured in a cold state to foil the hot state.",
            "A city street at dusk where each decision scene floats in a bubble tagged cold-plan or hot-outcome; a giant ledger column records the gap while a Jekyll-and-Hyde mask rotates overhead.",
            [
                "To make informed decisions we need to somehow experience and understand the emotional state we will be in at the other side of the experience",
                "When the boss criticizes us publicly, we might be tempted to send a vehement e-mail, but we would be better off putting the reply in the draft folder for a few days",
                "After test-driving a sports car, we should take a break and discuss the spouse's plan to buy a minivan before signing a contract",
                "We promise to save for retirement but spend the money on a vacation; we vow to diet but surrender to the dessert cart",
                "Giving up on long-term goals for immediate gratification is procrastination",
                "Precautionary devices configured in a cold state, like a modified OnStar system, could impose consequences for speeding or make the radio switch from 2Pac to Schumann's Second Symphony",
                "We invest surprisingly little in learning about both sides of ourselves, though failure to understand the gap can bring repeated failures in many aspects of our lives",
                "Many women who are pregnant for the first time tell their doctors before labor that they will refuse painkillers, a decision made when they cannot imagine the pain of childbirth",
                "Modern cars are already full of computers controlling fuel injection, climate, and sound systems, so automatically calling Mom is feasible",
                "Learning how to bridge the hot-cold gap is essential to making some of the important decisions of our lives",
                "It may be that our models of human behavior need rethinking because we may be an agglomeration of multiple selves rather than fully integrated human beings",
                "Perhaps just being aware that we are prone to wrong decisions when gripped by intense emotion may help us apply knowledge of our Hyde selves to daily activities",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: The 19-Question Arousal Grid",
            "Sort the appendix's questions into three rows - sexual preferences, immoral behaviors, and birth control - and match each with its cold score, hot score, and percentage difference. Flag the biggest gaps: contact with animals at 167 percent, date-rape persistence at 125 percent, and the drug question at 420 percent, then rate whether each answer would survive the hot state.",
            "A glowing spreadsheet wall at Sproul Plaza where each question cell splits into cold-blue and hot-red numbers, and the largest percentage gaps flare into pulsing warnings.",
            [
                "Each question was presented on a visual-analog scale stretching from no on the left (zero) to possibly in the middle (50) to yes on the right (100)",
                "Can you imagine being attracted to a 12-year-old girl rose from 23 nonaroused to 46 aroused, a 100 percent difference",
                "Can you imagine having sex with a 60-year-old woman rose from 7 to 23, a 229 percent difference",
                "Could you enjoy having sex with someone you hated rose from 53 to 77, a 45 percent difference",
                "Would you find it exciting to have anal sex rose from 46 to 77, a 67 percent difference",
                "Excitement from contact with an animal rose from 6 to 16, a 167 percent difference",
                "Would you slip a woman a drug to increase the chance that she would have sex with you rose from 5 to 26, a 420 percent difference",
                "Would you tell a woman you loved her to increase the chance of sex rose from 30 to 51, a 70 percent difference",
                "Would you keep trying to have sex after your date says no rose from 20 to 45, a 125 percent difference",
                "Would you always use a condom if you didn't know the sexual history of a new partner fell from 88 nonaroused to 69 aroused, a 22 percent difference",
                "Would you use a condom even if a woman might change her mind while you went to get it fell from 86 to 60, a 30 percent difference",
                "The conclusions were consistent and clear - overwhelmingly clear, frighteningly clear - across all participants and question sets",
            ],
        ),
        "boss": (
            "Boss Battle: The Mr. Hyde Showdown",
            "Face the final challenge: predict the size of the hot-cold gap before the reveal, then defend a cold-state decision - condom availability, a speeding car, or an epidural choice - as the arousal meter climbs into the red. Beat Hyde by choosing which real-world safeguard survives the heat of passion.",
            "A nightmarish mirror where Dr. Jekyll's calm face is reflected as a sweating, reptilian-eyed Mr. Hyde; between them floats a giant arousal meter and a stack of decision cards marked condom, OnStar, and draft folder.",
            [
                "No matter how we looked at the numbers, the magnitude of underprediction by the participants was substantial",
                "Even the most brilliant and rational person, in the heat of passion, seems to be absolutely and completely divorced from the person he thought he was",
                "When the reptilian brain takes over during arousal, emotions may blur the boundary between what is right and what is wrong",
                "In the heat of passion we are all in danger of switching from 'Just say no' to 'Yes!' in a heartbeat",
                "Widespread availability of condoms is essential because we should not decide in a cool state whether to bring them; they must be there just in case",
                "A better strategy to guarantee teenagers avoid sex is to teach them to walk away from the fire of passion before they are close enough to be drawn in",
                "It is easier to fight temptation before it arises than after it has started to lure us in",
                "Roy is smart, decent, reasonable, and trustworthy most of the time, but unrecognizable to himself when sexually aroused",
                "The study suggested that participants' predictions were not just wrong but wrong by a large margin",
                "He may risk sexually transmitted diseases and unwanted pregnancies in order to achieve sexual gratification",
                "If we don't teach young people how to deal with sex when they are half out of their minds, we are not only fooling them; we're fooling ourselves as well",
                "Sumi's ice bucket test showed that cold-state predictions about pain and childbirth decisions do not match hot-state reality",
            ],
        ),
    },
    {
        "num": 7,
        "title": "Chapter 7: The Problem of Procrastination and Self-Control",
        "pages": "121-142",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Deadline Decoder",
            "Review the three MIT consumer-behavior classes - self-imposed deadlines, no deadlines, and dictated deadlines - and tag each student's deadline pattern as rational, procrastinating, or precommitted. Spot the students who spaced their papers across the semester and the few who set everything for the last day, then predict the grade ranking of each class.",
            "A twelve-week semester timeline stretched across three blackboards, each class drawn as a row of paper deadlines; a red penalty stamp falls one percent per day onto late papers while grade curves settle over the rows.",
            [
                "By 2006 the American personal savings rate had fallen below zero, to negative one percent, with Americans spending more than they earned",
                "Europeans save an average of 20 percent of income, Japan 25 percent, and China 50 percent",
                "The average American family now has six credit cards, and in 2005 alone Americans received 6 billion direct-mail solicitations for credit cards",
                "Average family debt on credit cards is about $9,000, and seven in 10 households borrow on credit cards to cover basic living expenses",
                "Procrastination comes from the Latin pro, meaning for, and cras, meaning tomorrow",
                "In Ariely's consumer behavior class, three papers over the 12-week semester were penalized at one percent off the grade for each day late",
                "A perfectly rational student would set all deadlines for the last day of class, since papers could always be submitted earlier without penalty",
                "Gaurav's class used the scheduling tool to space their deadlines across the whole semester, suggesting students realize their problems with procrastination",
                "The class with dictated deadlines at weeks 4, 8, and 12 got the best grades; the class with no deadlines at all got the worst; the self-deadline class finished in the middle",
                "Simply offering the students a tool by which they could precommit to deadlines helped them achieve better grades",
                "Students who did not space their deadlines sufficiently pulled the class average down with rushed, poorly written final papers",
                "Those who recognize and admit their procrastination weakness are in a better position to utilize precommitment tools to overcome it",
            ],
        ),
        "dialogue": (
            "Dialogue: The Bank of Self-Control Pitch",
            "Play both sides of the pitch meeting: the enthusiastic professor selling the self-control credit card to half a dozen high-powered bankers overlooking Manhattan, and the bankers weighing $17 billion in yearly interest against a revolutionary product. Negotiate the card's features - category limits, self-selected penalties, cooling-off periods - and decide whether the bank ever calls back.",
            "A plate-glass Manhattan conference room high above rainy yellow cabs, where a mock credit card glows on the table showing limits for coffee, clothing, and chocolate while the executives exchange uneasy glances.",
            [
                "The self-control credit card would let users decide in advance how much to spend in each category, store, and time frame, such as limiting coffee to $20 every week",
                "Cardholders who surpassed a limit could select their penalties, from having the card rejected to taxing themselves and transferring the tax to Habitat for Humanity",
                "The system could automatically trigger an e-mail to a spouse or friend, such as one noting that Dan Ariely exceeded his $50 monthly chocolate limit by $73.25",
                "The 'ice glass' method puts the credit card in a glass of water in the freezer, so an impulse purchase must wait for the ice to thaw, by which time the compulsion subsides",
                "Tricia, 29, owed $22,302 on her credit cards with a net worth of negative $38,691, and blogged the intimate details of her financial life online",
                "Debt blogging sites such as bloggingawaydebt.com and poorerthanyou.com grew as consumers asked others to help them develop self-control",
                "The bankers were stunned because credit card companies made $17 billion a year in interest from these cards",
                "Ariely argued that one company could step out of the pack by identifying itself as an advocate for the credit-crunched consumer",
                "The executives shook his hand warmly and assured him they would be talking again soon, but they never called him back",
                "The failure may have been due to the $17 billion in interest charges, or maybe it was just good old procrastination",
                "From 1992 to 2004, the rate of debt of Americans age 55 and over rose faster than that of any other group",
                "Smart Cards, thin palm-size cards with impressive computational powers, could be customized to each individual's credit needs",
            ],
        ),
        "audit": (
            "Audit: The Procrastination Prescription Log",
            "Walk through the chapter's real-world fixes - automatic paycheck deduction, exercise appointments with friends, refundable health-test deposits, and Ford's bundled maintenance intervals - and log the procrastination problem each one solves. For each fix, classify it as dictation, precommitment, or simplification, and rate its expected effect on behavior.",
            "A clinic waiting room where a wall board like Honda's service menu lists checkup intervals while a freezer holds a credit card in a glass of ice and a $100 refundable deposit form floats toward the nurse's desk.",
            [
                "Without precommitments, we keep on falling for temptation and failing to reach our long-term goals",
                "If we can't save from our paycheck, we can take advantage of the employer's automatic deduction option",
                "If we don't have the will to exercise regularly alone, we can make an appointment to exercise in the company of friends",
                "A doctor charging an up-front $100 deposit, refundable only if you show up promptly, would make you more likely to appear for a cholesterol test",
                "For a colonoscopy, a $200 deposit refundable only for arriving on time would replicate the self-imposed deadline condition offered to Gaurav's class",
                "Preventive medicine is generally more cost-effective than the remedial approach, but colonoscopies and mammograms are ordeals people put off",
                "Honda lumped its roughly 18,000 maintenance options into three engineering intervals: every 6 months or 5,000 miles, every year or 10,000 miles, and every two years or 25,000 miles",
                "Ford's service bay was 40 percent vacant until it adopted Honda-style bundling, and in just three years Ford matched Honda's success",
                "The winning argument at Ford was that it is better to have consumers service their vehicles at somewhat compromised intervals than not to service them at all",
                "Bundling medical tests so that people remember to do them is far smarter than adhering to an erratic series of health commands people are unwilling to follow",
                "Thoreau wrote 'Simplify! Simplify!' and simplification is one mark of real genius",
                "Self-imposed deadlines with penalties attached offer a middle ground between authoritarianism and complete freedom to fail",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: The Reinforcement Schedule Lab",
            "Sort Skinner's schedules - fixed-ratio versus variable-ratio - and match each to its human counterpart: used-car bonuses, slot machines, e-mail checking, and pellet-pressing rats. Predict which schedule keeps the rat pressing longest after rewards cease, then classify your own e-mail habit and prescribe a fix from the chapter.",
            "A Skinner box on one side and an inbox on the other: a lever-pressing rat works under a flashing pellet counter while a human thumb scrolls an endless feed; both timelines split into fixed green and variable red reward dots.",
            [
                "Skinner distinguished fixed-ratio schedules, with reward after a fixed number of presses, from variable-ratio schedules with a random number of presses",
                "Under a fixed schedule a rat received food after a fixed number of presses, comparable to a used-car dealer earning $1,000 for every 10 cars sold",
                "Under a variable schedule the rat earned the pellet after a random number of presses, sometimes 10 and sometimes 200",
                "Skinner found variable schedules more motivating: when rewards ceased, fixed-schedule rats stopped almost immediately while variable-schedule rats kept working for a very long time",
                "The variable schedule of reinforcement is the dark magic underlying gambling and the lottery, whose joy comes from unpredictable rewards",
                "E-mail is like gambling: most of it is junk, but the occasional valuable message acts as an unexpected pellet that keeps us pressing the lever",
                "An Australian report found workers spent an average of 14.5 hours a week checking, reading, arranging, deleting, and responding to e-mail",
                "Businesspeople recognize the addictive properties of these devices, which is why they call their BlackBerries 'CrackBerries'",
                "Turning off the automatic e-mail-checking feature reduces the frequency with which the computer notifies us of new mail",
                "Ariely assigns every cc'd e-mail the color gray and sends it to a folder labeled 'Later' to reduce the randomness of the reward",
                "Assigning a cheerful sound to urgent messages made the schedule of reinforcement more fixed and ultimately improved his life",
                "In the movie Seven Pounds, Will Smith's character checks e-mail while driving and veers head-on into a van, killing his wife and six other people",
            ],
        ),
        "boss": (
            "Boss Battle: The Interferon Regimen",
            "Survive the six-month self-control gauntlet: self-inject interferon three times a week and withstand the fever, nausea, and vomiting while everyone else in the protocol skips doses. Deploy your secret weapon - no movies until after the injection - and time the Play button perfectly to beat the side effects and finish the treatment.",
            "A loft apartment with a hammock facing a television, a syringe, a refrigerator, and a bucket within reach; a calendar counts down injections as a stack of rental movies grows beside the hammock.",
            [
                "Ariely acquired hepatitis from a blood transfusion while hospitalized for burns; in 1993 doctors identified it as hepatitis C",
                "The initial protocol called for self-injections of interferon three times a week for six months, each followed by about 16 hours of fever, nausea, headaches, and vomiting",
                "At the end of the six-month trial, Ariely was the only patient in the protocol who had followed the regimen in the way the doctors designed it",
                "Ariely's trick was to not watch any movies until after injecting himself, then watch as many as he wanted until he fell asleep",
                "Starting the movie immediately after the injection associated the injection with the rewarding experience rather than with the fever and chills",
                "If a desired behavior results in an immediate negative outcome, it will be very difficult to promote even if the ultimate outcome is highly desirable",
                "The second treatment lasted a year and combined interferon with a drug called ribavirin, and it eliminated the hepatitis from his liver",
                "During job interviews he carried his injections in a little icebox and invented excuses to skip dinner so he could inject himself in hotel rooms",
                "The general lesson is to look for tricks that match immediate, powerful, and positive reinforcements with the unpleasant steps toward long-term objectives",
                "Lack of medical compliance is a very pervasive problem",
                "Ralph Keeney estimates that about half of us will make a lifestyle decision that will ultimately lead us to an early grave",
                "Oscar Wilde said, 'I never put off till tomorrow what I can do the day after'",
            ],
        ),
    },
    {
        "num": 8,
        "title": "Chapter 8: The High Price of Ownership",
        "pages": "142-154",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Krzyzewskiville Ticket Tell",
            "Call a hundred Duke students the night after the lottery and classify each as ticket owner or non-owner from their price alone. Spot the emotional chasm: buyers anchored near $175 by alternative uses for the money, sellers anchored near $2,400 by memories, and flag the moment when no trade can possibly happen.",
            "A tent city outside a small stadium under floodlights; each tent glows either seller-red with a $2,400 price or buyer-blue with a $175 offer, and a giant gap splits the two sides of the screen.",
            [
                "Duke students pitch tents in Krzyzewskiville for basketball tickets, with random air-horn occupancy checks that can bump a whole tent to the end of the line",
                "For the most important games, students at the front of the line still did not get a ticket; they received lottery numbers instead",
                "Ariely and Ziv Carmon telephoned ticket winners and non-winners after the lottery in the spring of 1994, becoming ticket scalpers",
                "William, a non-winner, was willing to pay about $175, a price tempered by alternatives like a sports bar, beer, food, CDs, and shoes",
                "Joseph, a winner, demanded about $2,400, justifying the price with the importance of the experience and the lifelong memories it would create",
                "The average selling price of about $2,400 was separated by a factor of about 14 from the average buyer's offer of about $175",
                "Not a single person was willing to sell a ticket at a price that someone else was willing to pay",
                "In an instant after the lottery drawing, students were divided into owners and non-owners, forming an emotional chasm between imagined glory and imagined purchases",
                "From a rational perspective, both groups should have thought of the game in exactly the same way, since enjoyment should not depend on winning a lottery",
                "The predictions were based on the endowment effect research of Jack Knetsch, Dick Thaler, and Daniel Kahneman",
                "The question was whether winners valued tickets more than non-winners even though all the students worked equally hard to obtain them",
            ],
        ),
        "dialogue": (
            "Dialogue: The Seller's and Buyer's Mirror",
            "Play both sides of a VW bus sale and a house sale: the seller reliving mountain trips and sunlight-filtering kitchen windows, and the buyer noticing the puff of smoke shifting from first to second gear and the black mold in the corner. Run both negotiations and decide when each perspective mismatch leads to an inflated price or a lost sale.",
            "A driveway split in two: on one side a VW bus glows with golden vacation memories; on the other the buyer squints at a puff of exhaust and a corner of mold while a FOR SALE sign swings overhead.",
            [
                "The first quirk of ownership is that we fall in love with what we already have, recalling warm trips and memories even before the FOR SALE sign goes up",
                "The Chinese adoption story: the director randomly presented each of 12 couples a daughter, yet all felt the matches were perfect",
                "What made each match seem perfect was not the director's talent but nature's ability to make us instantly attached to what we have",
                "The second quirk is that we focus on what we may lose rather than what we may gain when pricing a possession",
                "Our aversion to loss is a strong emotion that sometimes causes us to make bad decisions",
                "As soon as we begin thinking about giving up our valued possessions, we are already mourning the loss",
                "The third quirk is that we assume other people will see the transaction from the same perspective as we do",
                "The buyer of the VW is more likely to notice the puff of smoke when you shift from first into second than your memories",
                "The buyer of your house is more likely to notice the strip of black mold in the corner than the sunlight through the kitchen windows",
                "The friend who sold a whole box of records for $25 at a garage sale saw the buyer sell them for ten times that the next day",
                "If we always overvalued what we had, there would be no such thing as Antiques Roadshow",
                "Ownership also applies to points of view, and once we prize an idea too much we are left with a rigid, unyielding ideology",
            ],
        ),
        "audit": (
            "Audit: The Ownership Audit Trail",
            "Audit five ownership traps from the chapter - the online auction spiral, the digital gold trial package, the 30-day money-back sofa, the remodeled Cambridge house, and the VW sale - and log how each one triggers the three irrational quirks. Note the moment virtual ownership took over in each and the price ultimately paid.",
            "A cluttered living room where each trap appears as a glowing exhibit: an auction countdown, a cable bill marked digital gold, a sofa with a money-back tag, and a blueprint of a wall being torn down and later rebuilt.",
            [
                "The more work you put into something, the more ownership you begin to feel for it, a phenomenon Mike Norton and Ariely call the 'Ikea effect'",
                "Pride of ownership is inversely proportional to the ease with which one assembles the furniture",
                "In online auctions, the participant who is the highest bidder for the longest period ends up with the strongest feelings of virtual ownership",
                "James Heyman, Yesim Orhun, and Ariely found that once bidders thought of themselves as owners, they were compelled to bid higher and higher to prevent losing their position",
                "Virtual ownership is one mainspring of the advertising industry, from BMW convertibles to Patagonia fleece",
                "Cable trial promotions like digital gold at $59 instead of $89 hook customers because once we have the package, downgrading becomes a loss we cannot bear",
                "The 30-day money-back guarantee pushes us to take the sofa home, where returning it starts to feel like a loss",
                "In the second quarter of 2008, 92 percent of home owners said there had been foreclosures in their local real estate market and were concerned about home values",
                "Two out of three home owners (62 percent) believed the value of their own home had increased or stayed the same while the market collapsed",
                "Ariely and Sumi tore down walls for an open feel in their Cambridge house and converted the carriage house, yet no buyer made an offer",
                "Their real estate agent said they would have to rebuild some walls and reverse their changes; a few weeks after they did, the house was sold",
                "In the end, the buyers didn't want their home; they wanted theirs, an expensive lesson in overvaluing our modifications",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: The Value Gap Grid",
            "Sort every price in the chapter into buyer values and seller values - $175 versus $2,400 tickets, the garage-sale album box, Zillow's home values, and the Cambridge house - and compute each gap. Flag the emotional driver on each side, from memories to sports bars, and mark which gaps rational analysis simply cannot close.",
            "A wall of glowing price tags in a stadium concourse, each buyer-seller pair separated by a red chasm while a factor-of-14 ruler hovers above the basketball ticket pair.",
            [
                "William's buyer price of $175 was tempered by what the money could alternatively buy: the sports bar, beer and food, CDs, or shoes",
                "Joseph's seller price of $2,400 rested on the game being a defining memory of his time at Duke, an experience to pass on to his children and grandchildren",
                "The average selling price of about $2,400 exceeded the average buyer's offer of about $175 by a factor of about 14",
                "The positivity bias, called the Lake Wobegon Effect, holds that all the women are strong, all the men are good-looking, and all the children are above average",
                "We feel we are better-than-average drivers, more likely to be able to afford retirement, and less likely to get a parking ticket for overstaying a meter",
                "Zillow found that two out of three home owners believed the value of their own home had increased or stayed the same as the housing market collapsed",
                "About half of home owners (56 percent) planned to invest in home improvements even as they watched the housing market collapse",
                "After each set of prospective buyers left the Cambridge house, the couple said to each other that the people were dull and unimaginative and had no taste",
                "The house sold only after a contractor re-erected walls, an expensive lesson about the effect of modifications on potential buyers",
                "From a rational perspective, the anticipated atmosphere at the game and its enjoyment should not depend on winning a lottery",
                "There is no known cure for the ills of ownership, which Adam Smith said is woven into our lives",
                "Downgrading to a smaller home is experienced as a loss that is psychologically painful, even if the monthly mortgage sinks our ship",
            ],
        ),
        "boss": (
            "Boss Battle: The Endowment Gauntlet",
            "Defend the final asset - your cherished opinion - against the three ownership quirks: the love of what you have, the fear of loss, and the assumption that others see it your way. Price your possession as a nonowner, accept the agent's verdict on your rebuilt walls, and break the Lake Wobegon spell before the market collapses around you.",
            "A courtroom of ownership where your childhood house, your VW bus, and your cherished opinion sit on the witness stand; each quirk rises as a gavel-smashing hologram while a Zillow-style market line crashes behind the judge.",
            [
                "Ownership fundamentally changes our perspective, and suddenly moving backward to our pre-ownership state is a loss we cannot abide",
                "Once we take ownership of an idea, we love it perhaps more than we should, prize it more than it is worth, and have trouble letting go",
                "We overvalue everything that we own, whether basketball tickets or domiciles, the same way we think our own kids are more wonderful than our friends' children",
                "Home ownership is more complex than a coffee mug because we invest so much in our houses, from granite countertops to koi ponds",
                "The owner of the beautifully remodeled house understands why the other homes languished on the market: 'they simply are not as nice as mine'",
                "The Cambridge house cost double mortgages, double heating bills, and double taxes while the housing market continued to slow down",
                "Being aware of ownership biases might help us listen more carefully to the advice and feedback we get from others",
                "The Lake Wobegon Effect reflects a more general tendency to fall in love with, and be overly optimistic about, anything that has to do with ourselves",
                "We may not become more accurate and objective about our children and houses, but we can realize that we have such biases",
                "The buyers didn't want the remodeled home; they wanted theirs, no matter how convinced the sellers were of their superior taste",
                "We are willing to make all kinds of sacrifices to avoid the psychologically painful loss of downgrading",
                "Ariely tries to view all transactions, particularly large ones, as if he were a nonowner, attempting to be as Zen as he can about material things",
            ],
        ),
    },
    {
        "num": 9,
        "title": "Chapter 9: Keeping Doors Open",
        "pages": "154-165",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Door-Game Dilemma",
            "Watch Sam race through the disappearing-doors version of the game and tag each of his clicks as exploration, exploitation, or panic-rescue. Count the clicks wasted on keeping doors alive, then compare his earnings with Albert's, who sampled every room, returned to the best one, and stayed there.",
            "A dark MIT East Campus hallway where a laptop screen shows three doors shrinking as Sam's cursor darts between them; beside him a scoreboard compares his frantic clicks with Albert's calm, profitable strategy.",
            [
                "In 210 BC, Xiang Yu burned his ships and crushed his cooking pots after crossing the Yangtze, leaving his troops no choice but to fight, and they won nine consecutive battles",
                "Xiang Yu's story is completely antithetical to normal human behavior, since normally we cannot stand the idea of closing the doors on our alternatives",
                "We buy expandable computer systems, TV insurance policies, and luxury SUVs just in case, giving up time and money for worthless options",
                "In the door game, three colored doors led to rooms that paid between one cent and 10 cents per click, with a total of 100 clicks available",
                "Each move from one room to another cost one click, so running from door to door burned up earnings",
                "Albert sampled all three rooms, went back to the best one, and spent the remainder of his 100 clicks there, earning one of the best scores so far",
                "In the disappearing condition, any door left unvisited for 12 clicks would disappear forever",
                "Sam frenziedly raced from door to door, clicking each one to restore it to full size before it vanished",
                "Participants in the frenzy to keep doors from shutting made substantially less money, about 15 percent less, than those who didn't have to deal with closing doors",
                "They could have made more money by picking a room, any room, and merely staying there for the whole experiment",
                "Charging three cents per door opening, revealing exact monetary outcomes, and allowing hundreds of practice trials all failed to change the behavior",
                "Even a door that could be brought back to life with a single click was still defended, because participants couldn't tolerate the idea of the loss",
            ],
        ),
        "dialogue": (
            "Dialogue: The Two-Major Crossroads",
            "Counsel Joe at the MIT crossroads between architecture and computer science, then counsel Dana between two boyfriends, playing both voices in each conversation. Push them to name what they lose by keeping both doors open, and decide which door each should close before the semester swallows them.",
            "A cavernous MIT atrium split into two mirrored lecture halls - one filled with drafting tables and blueprints, the other with server racks - while two students stand at the intersection holding course lists that refuse to overlap.",
            [
                "Joe, an incoming junior, had a passion for architecture and a liking for computer science, and the required courses for the two majors were incompatible",
                "If Joe signed up for classes in both disciplines, he would most likely end up without a degree in either field and would need another year, paid for by his parents",
                "Joe eventually graduated with a degree in computer science and found the perfect blend in his first job designing nuclear subs for the Navy",
                "Dana could not let go of a previous relationship that was dying while her new boyfriend grew restless",
                "Ariely asked Dana if she would risk losing the boy she loved for the remote possibility that she might love her former boyfriend more",
                "We give up the chance that our children could become really good at one activity by spreading them across gymnastics, piano, French, and tae kwon do",
                "In running back and forth among the things that might be important, we forget to spend enough time on what really is important",
                "Erich Fromm's 1941 book Escape from Freedom described people beset not by a lack of opportunity but by a dizzying abundance of it",
                "We must develop ourselves in every way possible and taste every aspect of life, spreading ourselves too thin",
                "We chase after doors of little worth, like nourishing a wilting relationship or buying on sale just because the price will never come again",
                "Some doors close too slowly for us to see them vanishing, such as the childhood of our sons and daughters slipping away while we work",
                "A friend's single best year of marriage came when he and his wife lived apart and met only on weekends, making their shared time limited with a clear end",
            ],
        ),
        "audit": (
            "Audit: The Open-Door Cost Ledger",
            "Audit every open door in the chapter - the expandable computer, the TV warranty, the SUV clearance, Joe's double major, Dana's two boyfriends, and the sale-shopping habit - and bill each one its true cost in clicks, time, money, and attention. Close the doors whose upkeep exceeds their option value.",
            "A cluttered family garage where each possession sprouts a glowing price tag of hidden costs - insurance, upgrades, lessons, tuition - while a ledger column labeled cost of keeping open grows taller than the door.",
            [
                "We end up with a computer that has more functions than we need and a stereo with an unnecessarily expensive warranty",
                "Keeping children in every activity gives up their time and ours, and the chance that they could become really good at one activity",
                "We buy things on sale not because we really need them but because once the sale ends we could never have them at that price again",
                "Ariely's own MIT versus Stanford decision consumed weeks of comparing schools, neighborhoods, and jobs while his research productivity began to suffer",
                "Ironically, as he searched for the best place to do his work, his research was being neglected",
                "Congress frequently gridlocks itself over the details of legislation, stuck in the middle like the donkey between two haystacks",
                "A friend spent three months selecting a digital camera from two nearly identical models, missing months of family photo opportunities",
                "The donkey in the story stood between two haystacks of identical size and eventually died of starvation because it couldn't decide",
                "The donkey, Congress, and the friend all failed to take into account the consequences of not deciding",
                "They also failed to consider the relatively minor differences that would have come with either one of the decisions",
                "The friend would have been equally happy with either camera, and the donkey could have eaten either bale of hay",
                "They should have considered the decision an easy one and gotten on with their lives, but we don't act that way because we can't close those doors",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: The Option-Value Grid",
            "Rate every door in the game and in life on two axes - true payoff versus cost of keeping open - and sort them into keep, close, and never-open columns. Score the disappearing-door runs, the three-cent door tax, the revealed-payout condition, and the reincarnating door, and decide which fixation is pure loss aversion.",
            "A two-axis scatter plot floating above a game screen, with doors plotted by payoff and upkeep cost; the keep-open zone shrinks as loss-aversion red spreads across the grid.",
            [
                "When each click opening a door cost three cents, participants showed no difference in response and still had the same irrational excitement about keeping options open",
                "When told the exact monetary outcomes they could expect from each room, participants still could not stand to see a door close",
                "Even with hundreds of practice trials, MIT students could not stay focused once they saw their options shrinking",
                "In the reincarnating condition, a single click could bring a vanished door back to life, yet participants still wasted clicks on it",
                "The reincarnating door's disappearance had no real consequences and could always be easily reversed, but the loss was still intolerable",
                "Pecking like barnyard hens at every door, participants sought to make more money and ended up making far less",
                "Running from pillar to post was not only stressful but uneconomical",
                "Jiwoong Shin of Yale and Ariely devised the door game to capture the dilemma represented by Joe and Dana",
                "The experiment location was MIT's East Campus dormitory, home to hackers, hardware enthusiasts, oddballs, and general misfits",
                "Getting the most money out of the experiment involved finding the room with the biggest payoff and clicking in it as many times as possible",
                "Switching from one room to another could be a good strategy for finding the biggest payout, but it burned clicks that could have made money",
                "The frenzy to keep doors from closing cost participants about 15 percent less in earnings than those with no closing doors",
            ],
        ),
        "boss": (
            "Boss Battle: The Closing-Door Finale",
            "Stand where Rhett Butler stood and close your doors deliberately: drop the committee, cut the sport, end the stale relationship, and make the MIT-or-Stanford call. Survive the two-option paralysis of donkey, Congress, and camera alike, and walk away with one door open, chosen, and committed.",
            "A plantation staircase at dusk where Scarlett begs 'Where shall I go?' and Rhett turns away; behind him a row of doors - committee, golf, ex, Stanford - slam one by one while a single door glows at the end of a hallway.",
            [
                "Rhett Butler's 'Frankly, my dear, I don't give a damn' was voted the most memorable line in cinematographic history, and its appeal comes from the emphatic closing of a door",
                "What we need is to consciously start closing some of our doors, and small doors are rather easy to close, like striking names off holiday card lists",
                "Bigger doors tied to new careers, better jobs, dreams, and relationships are harder to close even when they seem to be going nowhere",
                "We ought to shut doors because they draw energy and commitment away from the doors that should be left open, and because they drive us crazy",
                "Choosing between two things that are similarly attractive is one of the most difficult decisions we can make",
                "The donkey, Congress, and the friend all failed to consider the consequences of not deciding",
                "The relatively minor differences between similar options mean the decision should have been an easy one, even flippable with a coin",
                "Ariely chose MIT over Stanford in the end, having wound up like the donkey trying to discriminate between two very similar bales of hay",
                "With all his foreknowledge of the difficulty in decision making, Ariely was just as predictably irrational as everyone else",
                "A built-in alarm to warn us when the doors are closing on our most important options would be nice",
                "We have an irrational compulsion to keep doors open; it's just the way we're wired, but that doesn't mean we shouldn't try to close them",
                "When the couple knew they had only the weekends together, they dedicated them to enjoying each other rather than doing their work",
            ],
        ),
    },
    {
        "num": 10,
        "title": "Chapter 10: The Effect of Expectations",
        "pages": "165-183",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Beer Expectations Lab",
            "Watch patrons of the Muddy Charles sample MIT Brew - Budweiser plus two drops of balsamic vinegar per ounce - and tag each reaction as blind preference, forewarned disgust, or after-the-fact acceptance. Spot the exact moment knowledge flips the nose-wrinkle, then sort who asked for the standard beer.",
            "A pub under towering Greek columns where two pitchers labeled A and B pour glowing streams; drinkers split into three haloed groups - blind, warned, and informed-later - as their taste ratings arc across the wooden bar.",
            [
                "At the Muddy Charles pub, Leonard Lee, Shane Frederick, and Ariely tested whether expectations influence views of subsequent events, using glasses of beer",
                "MIT Brew was basically Budweiser plus two drops of balsamic vinegar for each ounce of beer; later studies used Sam Adams after students objected to calling Budweiser beer",
                "Without foreknowledge about the vinegar, most of the participants chose the vinegary MIT Brew over the standard beer",
                "When participants knew in advance that the MIT Brew was laced with balsamic vinegar, they wrinkled their noses and requested the standard beer instead",
                "If you tell people up front that something might be distasteful, the odds are good that they will end up agreeing with you - because of their expectations",
                "Students who found out about the vinegar after drinking the beer liked it much better than those who were told up front",
                "Those told afterward about the vinegar liked the beer just as much as those who were never aware there was vinegar in it at all",
                "Knowledge that comes after an experience is too late to affect sensory perceptions, suggesting expectations reshape the experience itself",
                "Telling participants about the vinegar after rather than before they tasted the beer doubled the number who decided to add vinegar to their beer",
                "In the extreme version, participants were given unadulterated beer, vinegar, a dropper, and the recipe: two drops of balsamic vinegar per ounce",
                "The beer studies imply Aunt Darcy would be better off keeping a painting's origin under wraps until after visitors finish admiring it",
            ],
        ),
        "dialogue": (
            "Dialogue: The Caterer's Menu Pitch",
            "Play the caterer and the bride's parents across two menus: Josephine's plain ginger chicken versus Culinary Sensations' merlot demi-glace and herbed Israeli couscous tasting notes. Sell the descriptions, then confess which dish wins in a blind taste test, and decide how much the wineglasses and plating will sway the guests.",
            "A wedding tent where two menus hang side by side - one plain typewritten card, one embossed calligraphy promising chèvre and raspberry vinaigrette - while the guests' pleasure meters rise with the font size.",
            [
                "A deep description like 'succulent organic breast of chicken roasted to perfection and drizzled with a merlot demi-glace' can lead us to expect greater things even if the food is no better",
                "Small things that sound exotic and fashionable, like chipotle-mango sauces, might not improve a dish in a blind taste test but can effectively influence taste through expectations",
                "Omitting that a cake is made from a commercial mix or that Jell-O comes from cow hooves can improve how a meal is received",
                "Learning to present food artfully on the plate is as important in culinary school as learning to grill and fry",
                "Removing Styrofoam packaging and placing take-out on nice dishes with garnish can make all the difference when you have company",
                "If you want to enhance the experience of your guests, invest in a nice set of wineglasses",
                "Controlled studies find that the shape of a wineglass makes no difference at all in an objective blind taste test",
                "People perceive a significant difference when they are handed the 'correct' glass for burgundy, chardonnay, or champagne",
                "Even if you forget that the glass shape has no real effect, you yourself may better enjoy wine consumed in appropriately shaped fancy glasses",
                "Mentioning that a movie got great reviews can increase friends' enjoyment of it",
                "Marketing is about providing information that will heighten someone's anticipated and real pleasure",
                "The identical foie gras au torchon would be enjoyed less at a truck stop on Interstate 95 than in Manhattan because ambience and expectations add to our enjoyment",
            ],
        ),
        "audit": (
            "Audit: The Expectation Field Notes",
            "Audit four field experiments - the beer tastings, the coffee condiments shop, the Joshua Bell Metro concert, and the Coke-Pepsi fMRI - and log the expectation manipulation, the measure, and the outcome of each. Note which results changed perception, which changed behavior, and which changed brain activation.",
            "A clipboard floating over L'Enfant Plaza at rush hour where a violinist plays beside a coin case; on the other side a coffee table with silver trays and Styrofoam cups splits patrons into upscale-tasters and ordinary-tasters.",
            [
                "In the coffee experiment with Elie Ofek and Marco Bertini, none of the odd condiments - cloves, nutmeg, orange peel, anise, sweet paprika, cardamom - were ever used",
                "When the same odd condiments were displayed in beautiful glass-and-metal containers with silver spoons and printed labels, coffee drinkers were much more likely to say they liked the coffee a lot",
                "The fancy containers made drinkers willing to pay well for the coffee and recommend serving the new blend in the cafeteria",
                "When the coffee ambience looked upscale, the coffee tasted upscale as well",
                "Joshua Bell posed as a street performer at L'Enfant Plaza Metro station during morning rush hour for the Washington Post",
                "Only 27 out of 1,097 people (2.5 percent) put money into Bell's open Stradivarius case, and only 7 (0.5 percent) stopped to listen for more than a minute",
                "Bell played for a little less than an hour and made about $32, humbling for a man used to making far more for one minute of playing",
                "Passersby said the music sounded like a slightly better than average street performer, because no one expected a world-class musician in a Metro station",
                "Bell said that if a mediocre player performed in Carnegie Hall with the Berlin Philharmonic, the expectations would triumph over the experience",
                "At Monterey, Ariely imagined Bell was a mediocre fifteen-year-old and could suddenly hear off-key patches and squeaks of the strings",
                "Expectations enable us to make sense of a conversation in a noisy room and to read text messages even when some words are scrambled",
                "In Jerome K. Jerome's Three Men in a Boat, the audience laughed at a German tragedy because two young men set the cues for when to laugh",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: The Coke-Pepsi Brain Grid",
            "Sort the fMRI results into hedonic versus brand-driven activations: tag which brain regions lit up for the sugar squirt alone and which fired for the red trademark. Then place every drinker on the grid - blind, known-Coke, known-Pepsi - and explain why the marketplace advantage belongs to the brand rather than the beverage.",
            "A brain scan split-screen: one hemisphere lights up at the sweet squirt, the other fires in the dorsolateral prefrontal cortex only when the known brand's name appears, while a cola aisle fades in behind the fMRI.",
            [
                "Sam McClure, Jian Li, and colleagues conducted blind and non-blind taste tests of Coke and Pepsi inside a functional magnetic resonance imaging (fMRI) machine",
                "Whenever a person received a squirt of Coke or Pepsi, the ventromedial prefrontal cortex (VMPFC), associated with strong feelings of emotional connection, was stimulated",
                "When participants knew they were going to get a squirt of Coke, the dorsolateral aspect of the prefrontal cortex (DLPFC) was also activated",
                "The DLPFC is an area involved in higher human brain functions like working memory, associations, and higher-order cognitions and ideas",
                "The reaction of the brain to the basic hedonic value of the drinks, essentially sugar, turned out to be similar for Coke and Pepsi",
                "The advantage of Coke over Pepsi was due to Coke's brand, which activated the higher-order brain mechanisms",
                "The brand-related response was stronger in people who had a stronger preference for Coke",
                "There is a dopamine link by which the front part of the brain projects and activates the pleasure centers",
                "The brand associations were more powerful, allowing the part of the brain representing them to enhance activity in the brain's pleasure center",
                "Pepsi ran its challenge using blind tasting and standard plastic cups marked M and Q, while Coke's market research was based on sighted preference with the famous red trademark",
                "The two companies' contradictory ads were both based on real but differently conducted evaluations",
                "The bright red can, swirling script, and years of messages are as much responsible for our love of Coke as the brown bubbly stuff itself",
            ],
        ),
        "boss": (
            "Boss Battle: The Stereotype Priming Siege",
            "Survive the priming gauntlet: take the math exam as an Asian-American woman primed by gender or by race, wait at the interrupted experimenter's door, and walk the hallway after the elderly-word scramble. Predict each priming outcome, then decide whether to settle a conflict blind or with a neutral third party.",
            "A research hallway where scrambled words float in the air - rude, polite, Florida, bingo - and two clocks measure the wait at a lab door while a third times the slow walk to the exit.",
            [
                "Margaret Shih, Todd Pittinsky, and Nalini Ambady asked Asian-American women to take a math exam after priming one group with gender questions and the other with race questions",
                "The women primed with gender-related questions performed worse than those primed with race-related questions, matching the stereotypes of both women and Asian-Americans",
                "The results show that even our own behavior can be influenced by our stereotypes, and that activation can depend on our current state of mind",
                "In John Bargh, Mark Chen, and Lara Burrows' study, participants completed scrambled-sentence tasks based on words like rude and aggressive or polite and considerate",
                "Participants primed with polite words patiently waited about 9.3 minutes before interrupting, while those primed with rude words waited only about 5.5 minutes",
                "Participants primed with elderly words like Florida, bingo, and ancient walked down the hallway considerably slower than the control group",
                "The primed participants were not elderly people but undergraduate students at NYU",
                "Stereotypes are not intrinsically malevolent; they provide shortcuts in our never-ending attempt to make sense of complicated surroundings",
                "Because a stereotype provides specific expectations about group members, it can unfavorably influence both our perceptions and our behavior",
                "In conflicts like Israeli-Palestinian or American-Iraqi, both sides read similar history books and are taught the same facts, yet rarely agree about who started the conflict",
                "Our investment in our beliefs is much stronger than any affiliation to sports teams, so the likelihood of agreement about the facts shrinks as personal investment grows",
                "Presenting the perspective of each side without the affiliation - revealing the facts but not which party took which actions - might help us better recognize the truth",
            ],
        ),
    },
]
