# -*- coding: utf-8 -*-
"""Phase 2 chapter data for Predictably Irrational (Dan Ariely), Introduction + chapters 1-5.
Each chapter: num, title, pages, domain, and 5 slots (scrub/dialogue/audit/matrix/boss),
each slot a 4-tuple (topic, player_mission, visual_frame_description, key_concepts[10-12]).
"""

D = "Behavioral Economics | Metacognition"

CHAPTERS = [
    {
        "num": 0,
        "title": "Introduction",
        "pages": "9-18",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Bandage-Dilemma Autopsy",
            "Walk through the burn ward's daily bath procedure and autopsy every decision the nurses made: the quick-pull tactic, the pain-spike theory, the start-at-the-worst-part plan. For each choice, identify the bias that produced it and redesign the procedure using the evidence the nurses never had.",
            "A hospital ward frozen mid-procedure: a nurse's hand hovers over a bandage while red tags pop over each assumption - 'sharp spike is kinder,' 'order doesn't matter' - and a pain-meter line graphs the patient's true agony against the nurses' theory.",
            [
                "An explosion of a large magnesium flare left 70 percent of Ariely's body covered with third-degree burns when he was an eighteen-year-old Israeli",
                "The next three years found Ariely wrapped in bandages in a hospital, emerging in a tight synthetic suit and mask that made him look like a crooked version of Spider-Man",
                "The nurses routinely grabbed a bandage and ripped it off as fast as possible, theorizing that a sharp spike of pain was preferable to a slow pull that would extend the treatment",
                "Ariely's experiments showed people feel less pain if treatments such as bandage removal are carried out with lower intensity and longer duration than with high intensity and a shorter duration",
                "Etty, Ariely's favorite nurse, pointed out that pulling bandages quickly might shorten the nurses' own torment when their patients screamed in agony",
                "Even with their vast experience, the nurses were victims of inherent biases in their perceptions of the patients' pain - biases that experience apparently did not alter",
                "A class on the physiology of the brain taught by Professor Hanan Frenk showed Ariely that science is an empirical endeavor in which anyone can propose alternative theories as long as they find empirical ways to test them",
                "Ariely probed pain with heat, cold water, pressure, loud sounds, and even the psychological pain of losing money in the stock market",
                "Behavioral economics, also called judgment and decision making (JDM), draws on aspects of both psychology and economics",
                "For social scientists, experiments are like microscopes or strobe lights: they slow human behavior down, isolate individual forces, and let us test directly what makes us tick",
                "Our irrational behaviors are neither random nor senseless - they are systematic, and since we repeat them again and again, predictable",
            ],
        ),
        "dialogue": (
            "Dialogue: The Burn Ward Roundtable",
            "Play the nurses, then switch and play young Ariely as he presents his slow-pull findings to the ward. Argue the quick-pull case from the nurses' own torment and the fear of anticipating pain, then counter with the data on intensity, duration, and the pain of the patients - and decide whether the ward changes its methods.",
            "A hospital conference room where two screens face off: on one side the nurses defend the fast rip while a scream-o-meter spikes, on the other Ariely's line graphs show lower total pain for slow removal.",
            [
                "The nurses had theorized that a vigorous tug at the bandages, causing a sharp spike of pain, was preferable to a slow pulling that would extend the treatment",
                "Ariely concluded that people feel less pain if treatments are carried out with lower intensity and longer duration than with high intensity and a shorter duration",
                "The nurses' theories gave no consideration to the fear the patient felt anticipating the treatment, the fluctuations of pain over time, or the benefit of knowing the pain would be reduced over time",
                "Etty admitted their understanding had been lacking and said the methods should change, but noted the psychological pain the nurses experienced when patients screamed in agony",
                "In the end the procedures were changed, and some of the nurses followed Ariely's recommendations",
                "The episode impressed on Ariely that if experienced nurses misunderstood reality for patients they cared about, other people likely misunderstand the consequences of their behaviors too",
                "Behavioral economics is a relatively new field that draws on aspects of both psychology and economics",
                "The rational economic model is the basic assumption that most economists and many of us hold: that we are capable of making the right decisions for ourselves",
                "Traditional economics holds that if we make a mistake, market forces will sweep down on us and set us back on the path of rationality",
                "Ariely's irrational behaviors are neither random nor senseless but systematic, and since we repeat them again and again, predictable",
                "Each chapter of the book is based on experiments that illustrate a general principle, providing insight into how we think in many contexts of life",
            ],
        ),
        "audit": (
            "Audit: The Predictable-Pattern Field Log",
            "Spend a day logging your own decisions and tag each one with the irrational pattern behind it: the diet promise lost to the dessert cart, the aspirin priced at 50 cents, the impulse purchase. For every entry, note the systematic mistake and design one countermeasure you could actually use.",
            "A personal dashboard feeds a scrolling ledger: every logged decision gets stamped with its bias - dessert-cart amnesia, price placebo, impulse buy - while a counter-tactic shelf lights up with options.",
            [
                "Ariely asks why we so often promise ourselves to diet, only to have the thought vanish when the dessert cart rolls by",
                "A one-cent aspirin does not cure a headache the way the same aspirin at 50 cents does, showing price itself changes the experienced effect",
                "People who have been asked to recall the Ten Commandments tend to be more honest, at least immediately afterward, than those who haven't",
                "Honor codes actually do reduce dishonesty in the workplace",
                "The nurses' quick-pull method was not due to maliciousness, stupidity, or neglect but to inherent biases in their perceptions of patients' pain",
                "Ariely's research showed that people feel less pain if treatments are carried out with lower intensity and longer duration",
                "The three years Ariely spent observing daily activities as an outsider taught him to reflect on the goals of behaviors, his own and those of others",
                "Understanding the impact of the Ten Commandments in curbing dishonesty might help prevent the next Enron-like fraud",
                "Understanding the dynamics of impulsive eating has implications for every other impulsive decision, including why it's so hard to save money for a rainy day",
                "The value of an experiment lies in extrapolation: the lessons apply not only in the experiment's environment but in many contexts of life",
                "Ariely suggests pausing at the end of each chapter to consider whether the principles revealed might make your life better or worse",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Rationality x Irrationality x Predictability",
            "Sort a grid of 12 everyday episodes - the dessert cart, the 50-cent aspirin, the honor code, the failed bandage theory - by whether they fit the rational economic model or systematic irrationality, and by whether the outcome is predictable. Mark each cell with the evidence and name the force that drives it.",
            "A courtroom-style grid where episode cards slide into cells; the rational column glows faintly while the predictable-irrational column blazes, each card pinned with its experimental evidence.",
            [
                "In conventional economics, the assumption that we are all rational implies that we compute the value of all options and follow the best possible path of action",
                "Traditional economics holds that market forces will sweep down on irrational decision makers and swiftly set them back on the path of rationality",
                "Ariely argues we are really far less rational than standard economic theory assumes",
                "Our irrational behaviors are systematic, and since we repeat them again and again, predictable",
                "Behavioral economics draws on aspects of both psychology and economics and is also called judgment and decision making (JDM)",
                "Experiments are like microscopes or strobe lights, slowing human behavior to a frame-by-frame narration so individual forces can be examined",
                "The nurses' mistaken theory showed that even experts with vast experience can hold wrong beliefs that were never scientifically tested",
                "Ariely's finding that slow bandage removal hurts less overall contradicts the nurses' quick-pull belief",
                "The 50-cent aspirin cures a headache that a one-cent aspirin cannot, illustrating that price shapes perceived effectiveness",
                "Honor codes reduce dishonesty in the workplace, and recalling the Ten Commandments makes people more honest",
                "Each chapter's experiment illustrates a general principle that applies by extrapolation to many contexts of life",
                "Recognizing where we depart from the ideal of perfect reasoning promises many practical benefits for everyday decisions",
            ],
        ),
        "boss": (
            "Boss Battle: The Rational-Economist Showdown",
            "Face a defender of the rational economic model who claims market forces will always correct our mistakes. Fire your empirical counter-evidence from the burn ward, the Ten Commandments, and the price of aspirin, and land the knockout point: irrationality is systematic, repeated, and predictable.",
            "An economics lecture hall turned arena: the rational model stands on a gilded platform that cracks with each experiment you cite, while a banner overhead slowly rewrites itself from 'rational actor' to 'predictably irrational.'",
            [
                "The rational economic model is the simple and compelling idea that we are capable of making the right decisions for ourselves",
                "Generations of economists since Adam Smith have built far-reaching conclusions on the assumption of rationality",
                "Traditional economics answers mistakes with market forces that will sweep down and set us back on the path of rationality",
                "Ariely's research shows we are far less rational than standard economic theory assumes",
                "Our irrational behaviors are systematic and, since we repeat them again and again, predictable",
                "The nurses in the burn unit had vast experience yet held a theory about pain that was never scientifically tested and was wrong",
                "Ariely found that lower-intensity, longer-duration treatments hurt less overall than the nurses' quick-pull method",
                "A 50-cent aspirin cures a headache that a one-cent aspirin leaves in place",
                "Recalling the Ten Commandments makes people more honest, and honor codes reduce dishonesty in the workplace",
                "Behavioral economics draws on psychology and economics and aims to move economics away from naive psychology toward empirical scrutiny",
                "Experiments allow social scientists to isolate individual forces and test unambiguously what makes us tick",
                "Understanding how we are predictably irrational provides a starting point for improving decision making and changing the way we live for the better",
            ],
        ),
    },
    {
        "num": 1,
        "title": "Chapter 1: The Truth about Relativity",
        "pages": "18-36",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Decoy Detection Lab",
            "Scan 12 product and price displays and spot the decoy in each: the print-only subscription, the colonial needing a roof, the overpriced bread machine, the distorted face. Name what the decoy makes look good, and explain how it changes the choice even though nobody picks it.",
            "A marketplace diorama where each display freezes and the decoy glows in a pulsing red ring while an arrow shows which option it inflates - the Economist trio, the television row, and the menu all at once.",
            [
                "The Economist offered an Internet-only subscription for $59, a print-only subscription for $125, and a print-and-Internet subscription for $125",
                "Humans rarely choose things in absolute terms - we don't have an internal value meter, so we focus on the relative advantage of one thing over another",
                "Among 100 students at MIT's Sloan School, 16 chose the Internet-only subscription, zero chose print-only, and 84 chose the print-and-Internet combination",
                "Without the print-only decoy, 68 students chose the Internet-only option for $59 and only 32 chose the combination - the mere presence of the decoy had shifted the choices",
                "Sam the television salesman prices the set he most wants to sell as the middle option because, given three choices, most people will take the middle choice",
                "Restaurant consultant Gregg Rapp found that high-priced entrees boost revenue even if no one buys them, because people order the second most expensive dish",
                "A decoy option that is clearly worse than one alternative but similar to it makes that alternative look better, not just relative to the decoy but overall",
                "In the dating experiment, participants chose the regular, similar-but-superior person over the other undistorted person 75 percent of the time",
                "Williams-Sonoma's $275 bread machine sold poorly until a larger model priced about 50 percent higher was added; then sales of the smaller machine began to rise",
                "When choosing among three houses, buyers pick the colonial with the good roof over the contemporary because the roof-needing colonial makes the comparison easy",
                "Envy and jealousy spring from comparing our lot with others, which is why the Ten Commandments warned against coveting a neighbor's possessions",
                "Most people will walk 15 minutes to save $7 on a $25 pen but not to save $7 on a $455 suit, even though $7 is $7 in both cases",
            ],
        ),
        "dialogue": (
            "Dialogue: The Economist Subscription Interrogation",
            "Sit in the Economist's London office and interrogate the marketers about the three subscription offers, then switch sides and play the MIT students choosing between them. Run the decoy experiment yourself: show the set with and without the print-only option and watch the 84/16 split become 32/68.",
            "A British office with a chalkboard showing the two price ladders; each time the decoy is erased, a crowd of student avatars visibly migrates from the $125 bundle to the $59 web deal.",
            [
                "The Economist's marketing wizards knew that humans rarely choose things in absolute terms but focus on the relative advantage of one thing over another",
                "The print-and-Internet option at $125 was clearly better than the print-only option at $125, making the combination a no-brainer",
                "Given the three options, 84 of 100 MIT Sloan students chose the print-and-Internet combination and 16 the Internet-only option",
                "Removing the print-only decoy changed the result to 68 for the Internet-only option and 32 for the combination",
                "The mere presence of the decoy, even though no one selected it, was enough to change the students' choices - a predictably irrational result",
                "Sam the salesman knows that given three choices, most people will take the middle choice, so he prices the television he wants to sell in the middle",
                "Gregg Rapp found that an expensive dish lures customers into ordering the second most expensive choice, which can be engineered for higher profit",
                "Adding an option like -Rome (Rome without free breakfast) makes Rome with free breakfast look better than the difficult-to-compare Paris option",
                "In the photo experiment, the slightly distorted version of a face pushed participants to prefer the similar but undistorted face 75 percent of the time",
                "The bread machine's larger, 50 percent more expensive sibling model gave consumers something to compare, and the smaller machine began to sell",
                "A decoy friend with your basic physical characteristics but slightly less attractive (-you) makes you look better at a singles event",
                "When a similar but better-looking friend of the same sex asks you out for a night, you might wonder whether you're being used as a decoy",
            ],
        ),
        "audit": (
            "Audit: The Relative-Value Field Log",
            "Walk through a week of choices - the restaurant menu, the electronics display, the open-house circuit - and log every relative judgment you catch yourself making. For each, name the comparison standard, spot any decoy, and record whether the choice was truly about value or about contrast.",
            "A city street overlaid with floating comparison brackets linking every product to its neighbor, while a field notebook stamps each observation with its decoy and its target.",
            [
                "Most people don't know what they want unless they see it in context - we don't know what kind of speaker system we like until we hear one that sounds better than the previous one",
                "We always compare jobs with jobs, vacations with vacations, lovers with lovers, and wines with wines",
                "We tend to compare things that are easily comparable and avoid comparing things that cannot be compared easily",
                "A $7 saving on a $25 pen seems worth a 15-minute trip, while the same $7 on a $455 suit does not - yet $7 is $7 no matter how you count it",
                "It is easy to add $200 to a $5,000 catering bill but hard to spend $3,000 on a new leather sofa, even though we spend more time on the sofa than in the car",
                "The more we have, the more we want - James Hong sold his Porsche Boxster and bought a Toyota Prius to shrink his circles of comparison",
                "When CEO pay was made public in 1993, comparisons pushed salaries to skyrocket rather than fall, with the average CEO now making about 369 times the average worker",
                "A young man making almost $300,000 complained about his salary because two coworkers at adjacent desks were making $310,000",
                "Mencken observed that a man's satisfaction with his salary depends on whether he makes more than his wife's sister's husband",
                "We can sometimes control the circles around us - skipping open houses above our means or walking away from the boastful big spender at a reunion",
                "Relativity is everywhere, and we view everything through its lens - the enchantment of meeting a fellow traveler abroad may be limited to the circumstances",
                "A doctor who dreamed of a Nobel Prize for cancer research moved to Wall Street because colleagues' yachts and vacation homes made him feel poor",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Decoy x Target x Choice Shift",
            "Complete a grid for 12 decoy scenarios - the Economist trio, the three houses, the distorted faces, the bread machines - by naming the target option each decoy inflates and the measured shift in choices. Mark whether the decoy was ever selected and still moved the market.",
            "A laboratory grid where decoy cards insert into each row and the target column pulses; a readout beside each row shows the before-and-after choice percentages.",
            [
                "The print-only subscription for $125 was the decoy that made the print-and-Internet subscription for $125 look clearly superior",
                "With the decoy present, 84 of 100 MIT students chose the combination; with it removed, only 32 did",
                "The decoy option was chosen by zero of the 100 students, yet its mere presence determined their choices",
                "Adding a clearly inferior option (-A) similar to (A) makes (A) look better overall, not just relative to the decoy",
                "The colonial needing a new roof is the decoy that steers buyers to the colonial with the good roof instead of the contemporary",
                "In the dating experiment, the slightly distorted decoy face made participants prefer the similar but undistorted face 75 percent of the time",
                "The larger, 50 percent more expensive bread machine was never the best seller, but it made the smaller machine start flying off the shelves",
                "Gregg Rapp's expensive menu entrees are decoys that push diners to the second most expensive dish",
                "Sam the salesman places the television he wants to sell in the middle of three options because most customers take the middle choice",
                "The decoy effect helps decide whom to date and marry, and even applies to the honeymoon choice between Rome and Paris",
                "The Economist's marketers assumed the Web reader would otherwise pick the Internet-only option, so they built a decoy to push him to the bundle",
                "Bring a slightly less attractive friend (-you) to a singles event and you will look better in comparison with everyone around",
            ],
        ),
        "boss": (
            "Boss Battle: The Runway-Lights Gauntlet",
            "Pilot your decision-making past the decoys of a full day's shopping while the relativity of the circle illusion shifts around you. Resist the middle-television trap, the $125 combo lure, and the $310,000 desk envy - and land your choices on the runway lights you chose, not the ones the marketers placed.",
            "A dark landing strip at night: every product on sale glows as a runway light, but decoys flicker red and the circle illusion shrinks and swells on the horizon as you approach.",
            [
                "Like an airplane pilot landing in the dark, we want runway lights on either side of us to guide our choices",
                "The middle circle appears to shrink among larger circles and grow among smaller ones, though it stays the same size - mirroring how the mind compares everything around us",
                "The Economist's print-only decoy sent 84 of 100 MIT students to the $125 combination; without it, 68 chose the $59 Internet-only option",
                "The decoy effect works even though no one ever selects the decoy itself",
                "Sam the television salesman prices the set he wants to sell in the middle because most customers take the middle choice",
                "In the photo experiment, participants preferred the similar-but-superior face 75 percent of the time when the distorted decoy was present",
                "The Williams-Sonoma bread machine began selling only after a larger, 50 percent more expensive model gave consumers a comparison",
                "A young man making almost $300,000 was unhappy because his coworkers made $310,000 - envy is relativity at work",
                "Publicizing CEO pay in 1993 made salaries skyrocket instead of fall, with the average CEO now making about 369 times the average worker",
                "Most people would walk 15 minutes to save $7 on a $25 pen but not to save $7 on a $455 suit, even though $7 is $7",
                "The only cure for the cycle of relativity is to break it - James Hong sold his Boxster and bought a Prius to make his circles of comparison smaller",
                "We can choose smaller circles: skip open houses above our means, and step away from the boastful big spender at the class reunion",
            ],
        ),
    },
    {
        "num": 2,
        "title": "Chapter 2: The Fallacy of Supply and Demand",
        "pages": "36-58",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Anchor Hunt",
            "Hunt for anchors across 12 buying scenarios - the social security digits, the Cotes du Rhone auction, the LCD television, the new-city housing market. Name the anchor in each, say whether it is arbitrary or earned, and predict how it will bend the next bid.",
            "A bungee-cord visualization: each product price glows as a peg in the ground while a cord stretches from it to every future price, showing how far the anchor can pull.",
            [
                "Konrad Lorenz showed goslings imprint on the first moving object they see and stick with that decision - and humans similarly accept the first price they encounter as an anchor",
                "In the MIT auction, students wrote down the last two digits of their social security numbers before bidding, and those digits anchored their willingness to pay",
                "Any question could have created the anchor - the researchers could have asked for the current temperature or the manufacturer's suggested retail price instead",
                "Price tags by themselves are not anchors; they become anchors when we contemplate buying a product or service at that particular price",
                "People who move to a new city generally remain anchored to the prices they paid for housing in their former city",
                "In the annoying-sounds experiment, the group first offered 10 cents demanded an average of 33 cents to hear the sound again, while the 90-cents group demanded 73 cents",
                "The first anchor predominated across all phases of the sound experiment, even when new anchors of 50 cents and flipped 90/10 cents were suggested",
                "Self-herding happens when we believe something is good on the basis of our own previous behavior - each Starbucks visit lines us up behind ourselves",
                "Once the first decision is made, later decisions follow in what seems a logical and coherent manner - the die is cast and the anchor set",
                "The poetical reading auction showed anchors can even flip the sign: students anchored to paying offered about a dollar or two, while those anchored to being paid demanded $1.30 to $4.80",
                "In the real world, anchoring comes from MSRPs, advertised prices, promotions, and product introductions - all supply-side variables",
                "Our sensitivity to price changes might be largely a result of our memory for past prices and our desire for coherence with past decisions",
            ],
        ),
        "dialogue": (
            "Dialogue: The Gosling Imprinting Trial",
            "Re-enact the wine auction with the MIT marketing class: hand out the forms, have the students write their social security digits, collect the yes-no answers and the real bids, then switch sides and watch the 216-to-346-percent spread appear. Interrogate the students about whether their digits influenced them.",
            "A lecture hall where the last two digits of each student's social security number float above their heads and their bids rise in price bars that sort themselves by digit size.",
            [
                "Students with social security numbers ending in the upper 20 percent placed bids 216 to 346 percent higher than those ending in the lowest 20 percent",
                "The top 20 percent bid an average of $56 for the cordless keyboard while the bottom 20 percent bid an average of $16",
                "When asked, the students quickly dismissed the suggestion that writing their social security digits had influenced their final bids",
                "Social security numbers were the anchor only because the researchers requested them - any question would have created the anchor",
                "The bids showed coherent logic within categories: everyone was willing to pay more for the keyboard than the trackball and more for the 1996 Hermitage than the 1998 Cotes du Rhone",
                "Arbitrary coherence means initial prices are largely arbitrary, but once established they shape present and future prices for related products",
                "Price tags become anchors only when we contemplate buying a product at that price - the imprint is set at the moment of consideration",
                "In the sounds experiment, the 10-cent group demanded an average of 33 cents while the 90-cent group demanded 73 cents for the same annoying experience",
                "Even after new anchors were suggested, participants stuck with their first anchor across all three phases of the experiment",
                "The poetry auction anchored half the students to paying and half to being paid, producing bids versus demands for the same ambiguous experience",
                "Like Tom Sawyer's whitewashing, an ambiguous experience can be made arbitrarily pleasurable or painful by the anchor set before it",
                "The first decision in a long stream of decisions can have such a long-lasting effect that it percolates into future decisions for years to come",
            ],
        ),
        "audit": (
            "Audit: The First-Decision Ledger",
            "Inventory the first decisions that shaped your life - the first Starbucks coffee, the first DVD player, the first apartment rent - and record how each became an anchor for everything that followed. Ask whether the original decision was wise, and note which habits are just self-herding.",
            "A ledger book that fills itself with first-purchase entries, each one growing a chain of later decisions until the page shows a Starbucks queue of your own past selves.",
            [
                "Once we buy a new product at a particular price, we become anchored to that price from then on",
                "The first Starbucks visit starts a self-herding process in which each repeat visit lines you up behind your own previous behavior until the coffee becomes a habit",
                "People who move from inexpensive to moderately priced cities spend similar amounts on housing, even if it means squeezing into smaller homes",
                "Renting for about a year in a new location lets you adjust to the new market before making a purchase that aligns with it",
                "The first anchor influences not only the immediate buying decision but many others that follow, like the pull of a bungee cord",
                "Assael anchored his black pearls to the finest gems in the world, and the high prices followed forever after",
                "Howard Schultz designed Starbucks as a continental coffeehouse so that Dunkin' Donuts prices would not serve as the anchor",
                "Starbucks made lateral moves to Caffe Americano, Macchiato, and Frappuccino seem logical once the price bracket was accepted",
                "Descartes said 'I think, therefore I am,' but we might be nothing more than the sum of our first, naive, random behaviors",
                "Train yourself to question repeated behaviors: how did the habit begin, how much pleasure does it deliver, and could the money be better spent",
                "Pay particular attention to the first decision in a long stream of decisions about clothing, food, and other choices",
                "Socrates said the unexamined life is not worth living - it may be time to inventory the imprints and anchors in your own life",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Anchor Source x Product x Bid Outcome",
            "Fill a 12-cell grid matching anchor sources - social security digits, offered prices, MSRP, prior city rent - to products and the resulting bids. Mark which anchors were arbitrary, which held across later offers, and which flipped the direction of willingness to pay.",
            "A trading floor display where anchor cards connect to product rows and the final bid lights up green when the anchor held and red when it broke.",
            [
                "The social security digits served as anchors: upper-20 percent endings produced bids 216 to 346 percent higher than the lowest 20 percent",
                "In the sounds experiment, the 10-cent anchor produced 33-cent average demands while the 90-cent anchor produced 73-cent demands for the same sound",
                "The first anchor held through two later phases even when new anchors (50 cents, then flipped 90/10 cents) were introduced",
                "Arbitrary coherence means initial prices are largely arbitrary but shape present and future prices for the item and related products",
                "Price tags become anchors only when we contemplate buying at that price - otherwise they are just numbers",
                "Housing anchors follow people across cities: Lubbock-to-Pittsburgh transplants spend what they spent before, as do Los Angeles transplants",
                "The poetry auction flipped the sign of the exchange: one group bid to pay, the other demanded payment, for the same recitation",
                "The students' relative bids were coherent - everyone paid more for the keyboard than the trackball and more for the better wine",
                "Supply and demand are not independent forces: market prices such as MSRPs and promotions influence consumers' willingness to pay",
                "If people had amnesia for past prices, price changes such as doubling the price of milk would have a trivial effect on demand",
                "In the long run, a doubled gasoline tax would have much less effect on demand than short-term reactions suggest, as new anchors form",
                "Free-market trading assumes we know the value of what we trade, but arbitrary anchors mean trades may not reflect true pleasure",
            ],
        ),
        "boss": (
            "Boss Battle: The Pearl King's Showcase",
            "Take the role of Salvador Assael and build the launch that turns unsellable black pearls into luxury icons - or take the role of the buyer who must resist. Set the anchor, pair the pearls with diamonds, rubies, and emeralds, price them outrageously in Harry Winston's Fifth Avenue window, and see how much value you can manufacture from nothing.",
            "A Fifth Avenue jewelry window glowing at night: a string of black pearls floats among diamonds and rubies while a price tag rises higher and higher, and a crowd of well-dressed admirers multiplies outside.",
            [
                "Assael's first attempts to sell Tahitian black pearls failed - they were gunmetal gray, about the size of musket balls, and he returned from his trip without a single sale",
                "Assael waited a year for better specimens, then had Harry Winston place them in his Fifth Avenue window with an outrageously high price tag",
                "A full-page advertisement set a string of black pearls among diamonds, rubies, and emeralds in the glossiest of magazines",
                "The pearls that once hung on a rope in the Polynesian sea were soon parading through Manhattan on the necks of the city's most prosperous divas",
                "Mark Twain noted that to make a man covet a thing, it is only necessary to make the thing difficult to attain",
                "Assael anchored his pearls to the finest gems in the world, and the prices followed forever after",
                "Arbitrary coherence: initial prices are largely arbitrary, but once established they shape present and future prices",
                "In the sounds experiment, the first anchor held even when new anchors were suggested - first impressions resonate over long sequences of decisions",
                "The poetry auction showed the same ambiguous experience becomes pleasurable or painful depending on the anchor set beforehand",
                "Starbucks separated itself from Dunkin' Donuts through ambience so that old prices would not be the anchor",
                "Self-herding makes each repeat Starbucks visit feel like acting on genuine preferences until the habit is fixed",
                "Because anchors rather than preferences may determine behavior, free-market trading may not maximize the happiness we derive from goods",
            ],
        ),
    },
    {
        "num": 3,
        "title": "Chapter 3: The Cost of Zero Cost",
        "pages": "58-72",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Free! Hazard Sweep",
            "Sweep 12 offers - free shipping thresholds, buy-two-get-one-free, the free $10 certificate, the free oil change - and flag the FREE! hazard in each. Name what you would really be giving up, compute the true cost, and decide whether to grab or walk.",
            "A supermarket aisle where every free offer radiates a red glow; a scanner badge over each one reveals the hidden price - the $13 forgone, the 0.5 percent oil-change value, the unwanted DVD player.",
            [
                "Zero is not just another price - it is an emotional hot button and a source of irrational excitement",
                "When the Lindt truffle cost 15 cents and the Kiss one cent, 73 percent chose the truffle; with both cut by one cent and the Kiss free, 69 percent chose the free Kiss",
                "The real allure of FREE! is tied to humans' intrinsic fear of loss - choosing a free item carries no visible possibility of a poor decision",
                "In the Halloween experiment, about 70 percent of children chose a free small Snickers bar over the better deal of trading one Kiss for the large bar",
                "Most people at a Boston mall chose a free $10 Amazon gift certificate over a $20 certificate for seven dollars - forgoing a $13 profit",
                "Amazon's French division priced shipping at one franc (about 20 cents) and saw no increase in sales; free shipping produced the same dramatic jump as elsewhere",
                "Ariely bought an Audi partly for free oil changes for three years - about $150 of value, roughly 0.5 percent of the purchase price",
                "Most people would choose a free credit card with a 12 percent APR over a 9 percent APR card with a $100 annual fee, paying much more if they carry a balance",
                "A 'zero calories' label or a calorie-free beer makes people feel they are doing the right thing healthwise, even compared with a three-calorie option",
                "Free items can make perfect sense - a bin of free athletic socks has no downside - but trouble arises when FREE! competes with a better alternative",
                "The difference between two cents and one cent is small, but the difference between one cent and zero is huge",
                "When something is FREE! we forget the downside, because FREE! gives us such an emotional charge that we perceive the offer as immensely more valuable than it is",
            ],
        ),
        "dialogue": (
            "Dialogue: The Halloween Candy Trade",
            "Play Joey the Spider-Man and then Zoe the princess as Ariely works the porch: the two-Snickers trade where both bars have a cost, then the free small bar versus the trade for the large one. Feel the 70 percent gravity of FREE! and argue both sides of the deal to yourself.",
            "A front porch on Halloween night: two candy bars float in front of a giant trick-or-treater, and the free small bar pulses with a warm glow that outshines the objectively better trade.",
            [
                "Joey easily traded two of his three Hershey's Kisses for the two-ounce Snickers bar, getting more than six times the return on investment in net chocolate weight",
                "All but one of the kids offered both bars at a cost traded in two Kisses for the bigger candy bar",
                "Zoe was offered a choice between the large Snickers for one Kiss or the small Snickers for free, and the rational calculation clearly favored the trade",
                "About 70 percent of the children in Zoe's condition gave up the better deal and took the worse deal just because it was free",
                "The experiment was repeated with students at the MIT student center and replicated the pattern seen on Halloween",
                "The draw of zero cost is not limited to monetary transactions - whether it's products or money, we can't resist the gravitational pull of FREE!",
                "In the chocolate table experiment, 73 percent chose the truffle at 15 cents versus one cent for the Kiss; when the Kiss became free, 69 percent chose the Kiss",
                "Standard economic theory predicts no change from an equal one-cent discount on both chocolates, but the zero price changed everything",
                "The zero price effect persisted in a cafeteria where chocolates were added to purchases at the cashier line, ruling out a lack of change as the explanation",
                "Because humans are intrinsically afraid of loss, choosing a free item seems risk-free while choosing the paid item risks a poor decision",
                "A $20 gift certificate for seven dollars delivers a $13 profit, yet most mall shoppers jumped for the free $10 certificate",
                "The one-franc shipping bargain in France was virtually ignored, while free shipping caused an enthusiastic response - zero is a different place",
            ],
        ),
        "audit": (
            "Audit: The Zero-Price Audit Trail",
            "Audit a month of your own purchases and mark every choice touched by zero: the free checking account, the coupon run, the free museum day, the free gift with purchase. For each entry, compute what free actually cost you in money, time, or unwanted goods.",
            "A receipt tape unspooling across a desk, each free item glowing and a cost-counter beside it ticking up the real price of zero.",
            [
                "A free checking account with no benefits may cost more than a five-dollar account that includes free traveler's checks and online billing",
                "A mortgage with no closing costs but off-the-wall interest rates and fees shows how free can hide the real price",
                "Ariely drove about 7,000 miles a year with oil changes needed every 10,000 miles at about $75 each - the free oil was worth about $150 over three years",
                "The free-oil offer's influence on the Audi purchase was, from a rational perspective, unjustifiably large - about 0.5 percent of the purchase price",
                "Zero also applies to time: 45 minutes waiting for a free taste of ice cream is time taken from something else",
                "On free-entrance day the museum is overcrowded with long lines, yet Ariely knows it is a mistake and goes anyway",
                "The pain of paying is relatively insensitive to the amount paid - every additional dollar on a bill pains us less (diminishing sensitivity)",
                "Because the pain of paying is insensitive to amount, one person should pay the whole restaurant bill and friends should take turns paying over time",
                "A $100 bill split four ways costs the table about 40 units of pain, while one person paying the whole bill costs about 26 units",
                "Recalling the Ten Commandments example aside, most people overemphasize the yearly fee and pick the free credit card that costs more in the long run",
                "In the land of pricing, zero is not just another discount - the difference between one cent and zero is huge",
                "Want people to do the right thing? Don't just lower co-pays for colonoscopies and mammograms - make these critical procedures free",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Price Point x Emotion x Choice",
            "Complete the grid for 12 zero-price cases - chocolates at 15/1 and 14/0 cents, the Amazon franc, AOL's flat rate, the gift certificates - by rating the emotional charge and the choice outcome in each. Mark which cases match standard cost-benefit analysis and which break it.",
            "A laboratory matrix where each price row lights an emotion gauge and a choice column; the zero-price rows all blaze red while the economist's predicted column stays cold and empty.",
            [
                "Standard cost-benefit analysis predicts no change in chocolate choice from an equal one-cent discount, yet the free Kiss took 69 percent of customers",
                "When the Kiss was priced at two cents, one cent, and zero with the truffle at 27, 26, and 25 cents, only the drop to zero produced a dramatic reaction",
                "The zero price effect survived in a cafeteria setting where chocolates were paid for at the cashier, so a lack of change cannot explain it",
                "One franc of shipping (about 20 cents) was a real bargain that French shoppers virtually ignored, while free shipping started a stampede",
                "AOL's flat $19.95 monthly plan produced an overnight jump from 140,000 to 236,000 customers and a doubling of average time online",
                "AOL's customers hit busy phone lines, forcing AOL to lease services from other providers at premium prices",
                "The allure of FREE! is tied to the fear of loss - a free item has no visible possibility of a poor decision",
                "A free $10 gift certificate beat a $20 certificate for seven dollars in most mall shoppers' minds, even though the paid one earns $13",
                "Discounting from two cents to one cent changed nothing; the drop to zero changed everything - zero is in a category all its own",
                "The free-oil offer's worth ($150, about 0.5 percent of the car's price) had an unjustifiably large influence on Ariely's Audi purchase",
                "A zero-calorie beer increases the feeling that you're doing the right thing healthwise, even versus a three-calorie beer",
                "Most people overemphasize a credit card's yearly fee and choose the free 12 percent APR card over the 9 percent card with a $100 annual fee",
            ],
        ),
        "boss": (
            "Boss Battle: The Free-Chocolate Stampede",
            "Stand at the chocolate table as the crowd surges toward the free Kisses: manage the either-or rule, track the 73/27 split flipping to 31/69, and hold the line against the economist who insists nothing changed. Keep the experiment clean to the last customer.",
            "A public building atrium where a crowd of shoppers presses toward a table with a 'One chocolate per customer' sign; the free Kiss tray glows while a whiteboard charts the 73/27 split flipping to 31/69.",
            [
                "With the truffle at 15 cents and the Kiss at one cent, 73 percent chose the truffle and 27 percent a Kiss",
                "With the truffle at 14 cents and the Kiss free, only 31 percent chose the truffle while 69 percent chose the free Kiss",
                "Both chocolates were discounted by the same amount, so the relative difference and expected pleasure were unchanged - yet behavior reversed",
                "A passing economist following standard cost-benefit theory would say the customers should have chosen the truffles by the same margin",
                "The shoppers were not making a reasoned cost-benefit analysis - they were simply responding to the fact that the Kisses were free",
                "When the Kiss was priced at two, one, and zero cents (with the truffle at 27, 26, and 25 cents), only the drop to zero mattered",
                "Running the promotion at an MIT cafeteria cashier line reproduced the same overwhelming preference for the free option",
                "Most transactions have an upside and a downside, but when something is FREE! we forget the downside",
                "The zero price effect is in a category all its own - nothing beats the emotional surge of FREE!",
                "Seven free DVD titles lured buyers toward a high-definition player locked in a losing format war with Blu-Ray",
                "Free! can drive social policy: eliminate registration and inspection fees to push electric cars, and make colonoscopies and mammograms free",
                "Zero is a different place: the difference between one cent and zero is huge, not like the small difference between two cents and one cent",
            ],
        ),
    },
    {
        "num": 4,
        "title": "Chapter 4: The Cost of Social Norms",
        "pages": "72-93",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Norm-Domain Radar",
            "Sweep 12 exchanges - moving a couch, paying rent, the lawyer checking the mail, the $30 hourly offer - and tag each one as social or market on your radar. For each, name what happens if the wrong norm gets introduced: the fine, the price tag on the gift, the tip.",
            "A split-screen scanner: friendly favors appear on the warm side, wages and rents on the cold side, and any mention of money draws a crack across the dividing wall.",
            [
                "We live simultaneously in two worlds: social norms (friendly requests, warm, no instant payback required) and market norms (wages, prices, rents, comparable benefits, prompt payment)",
                "Offering your mother-in-law payment for Thanksgiving dinner puts a damper on the party and violates the social norm",
                "When market norms enter our considerations, the social norms depart - mentioning money converts a favor into underpaid work",
                "AARP lawyers refused $30 an hour for work with needy retirees but overwhelmingly agreed to do the same work for free",
                "Explicitly pricing a gift - calling it a '50-cent Snickers bar' - moves it into the realm of market norms",
                "In the Israeli day care study, a fine for late pickups replaced the social norm with a market norm, and tardiness actually became a choice parents made",
                "Once a social norm is trumped by a market norm, it rarely returns - social relationships are not easy to reestablish",
                "Gifts are financially inefficient but are an important social lubricant that builds long-term relationships",
                "A $1,000 cash bonus is what most employees would choose, but a $1,000 vacation would build more loyalty and enjoyment of work",
                "Stating the prices of benefits on a paycheck stub changes the workplace from a social environment to a transactional relationship",
                "The sensei replied that if he charged his students for martial arts training, they would not be able to afford him",
                "Police officers, firefighters, and soldiers don't risk their lives for their weekly pay - pride in profession and a sense of duty motivate them",
            ],
        ),
        "dialogue": (
            "Dialogue: The Thanksgiving Payment Faux Pas",
            "Replay the Thanksgiving dinner where the guest pulls out his wallet: run the scene first as the offering guest, then as the red-faced mother-in-law, then as the family that watches the silence fall. Rewind and choose the move that keeps the dinner in the social world.",
            "A Norman Rockwell-style dining room that freezes as a wallet appears above the turkey; a wine glass tilts, napkins drop, and a thermometer labeled 'relationship' plunges.",
            [
                "The social norms world is warm and fuzzy, and instant paybacks are not required - you may help move your neighbor's couch without him rushing to move yours",
                "The market norms world is sharp-edged: wages, prices, rents, interest, and costs-and-benefits, where you get what you pay for",
                "Offering direct payment for the Thanksgiving dinner makes the mother-in-law stand up red-faced and ruins the occasion",
                "When social and market norms collide, trouble sets in - as when a dating man starts counting what the romance is costing him",
                "Woody Allen's immortal words: 'The most expensive sex is free sex'",
                "In the circle-dragging experiment, the $5 group dragged 159 circles, the 50-cent group dragged 101, and the unpaid favor group dragged 168",
                "The unpaid participants applied social norms and worked more than the low-paid group and slightly more than the $5 group",
                "When money was mentioned, the 50-cent participants switched to market norms, decided 50 cents wasn't much, and worked halfheartedly",
                "The AARP lawyers refused $30 an hour for needy retirees but overwhelmingly agreed to provide the same services free",
                "Gifts keep exchanges in the social world - small gifts offend no one, and even small gifts keep us away from market norms",
                "Mention what a gift cost you, and you will see the back of people faster than you can say market norms",
                "Recovering a social relationship after introducing market norms is difficult - the mother-in-law will remember the incident for years",
            ],
        ),
        "audit": (
            "Audit: The Social-Market Ledger",
            "Keep a week-long ledger of every favor, gift, payment, and fee in your life, and classify each as social or market exchange. Flag the transitions - the priced gift, the late fee, the mention of cost - and note which relationships took damage.",
            "A double-column ledger book: warm entries fill the social side, sharp entries the market side, and any item that crosses the middle leaves a scorch mark.",
            [
                "Social norms include friendly requests like 'Could you help me move this couch?' with no instant payback required",
                "Market relationships are not necessarily evil - they include self-reliance, inventiveness, and individualism - but they imply comparable benefits and prompt payments",
                "In the circle-dragging experiment, $5 produced 159 circles, 50 cents produced 101, and no money at all produced 168",
                "Replacing cash with gifts kept everyone in the social world: Snickers 162 circles, Godiva 169, and nothing at all 168",
                "Explicitly pricing the gift as a '50-cent Snickers bar' dropped effort to the level of 50 cents in cash",
                "The AARP lawyers refused $30 an hour but accepted the same work free - zero dollars was more attractive than $30",
                "Thinking about money makes people more self-reliant and less helpful, as Vohs, Mead, and Goode's scrambled-sentence experiments showed",
                "The money-primed group waited about five and a half minutes before asking for help on a puzzle, versus about three minutes for the neutral group",
                "Asking a friend to help move a large piece of furniture is fine, but asking him to work beside paid movers is not",
                "Asking your lawyer neighbor to bring in your mail is fine, but asking him to prepare a rental contract free is not",
                "Companies that treat customers like family must maintain the social relationship under all circumstances - one violation sends consumers back to market exchange",
                "Money is very often the most expensive way to motivate people; social norms are not only cheaper but often more effective",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Reward x Norm x Effort",
            "Fill the grid mapping reward types - $5, 50 cents, nothing, a Snickers bar, a priced Snickers bar, Godiva - to the norm each triggers and the circles dragged in the experiment. Mark which rewards kept participants in the social world and which pushed them into the market.",
            "A spreadsheet-style arena where each reward card slides into its column and a circle-counter animates 159, 101, 168, 162, and the collapse back to the 50-cent level.",
            [
                "Five dollars produced 159 circles, 50 cents produced 101, and no money produced 168 - people worked harder under social norms than for 50 cents",
                "A Snickers bar (worth about 50 cents) produced 162 circles and Godiva chocolates (worth about five dollars) produced 169 - gifts kept participants in the social world",
                "Calling the reward a '50-cent Snickers bar' dropped effort to the same level as 50 cents in cash - the priced gift entered the market realm",
                "For market norms to emerge, it is sufficient to mention money, even when no money changes hands",
                "The AARP lawyers said no to $30 an hour but yes to free work - once market norms entered, the social norms departed",
                "The day care fine turned tardiness into a purchasable option, and lateness persisted even after the fine was removed",
                "In the money-priming experiments, participants unscrambling money-related sentences asked for help later, helped less, and chose seats farther away from teammates",
                "The money-primed participants showed the characteristics of the market: more selfish, more self-reliant, and wanting more time alone",
                "The salary group wanted to select tasks requiring individual input rather than teamwork",
                "Gifts are financially inefficient - a $50 bottle of Bordeaux may be worth at most $25 to the recipient - but they build social relationships",
                "Explicitly stating the financial value of benefits on a paycheck stub diminishes enjoyment, motivation, and loyalty",
                "Open-source communities like Linux show how social rewards and reputation strongly motivate behavior without money",
            ],
        ),
        "boss": (
            "Boss Battle: The Day Care Fine Reversal",
            "Run the Israeli day care center: introduce the late-pickup fine, watch the parents turn tardy, then remove it and confront the truth that the social norm never comes back. Decide whether to reintroduce guilt, and manage the wrecked social contract.",
            "A day care yard at dusk: a fine schedule is posted, then torn down, while a clock tower shows late pickups climbing - and a ghostly outline of the old social contract fades from the wall.",
            [
                "Before the fine, the teachers and parents had a social contract, and parents who were late felt guilty and became more prompt",
                "Once the fine was imposed, the day care had inadvertently replaced social norms with market norms - parents could decide whether to be late and often chose to be late",
                "The fine did not work well as a deterrent and had long-term negative effects",
                "When the fine was removed, parents' behavior didn't change - they continued to pick up their kids late, with a slight increase in tardy pickups",
                "When a social norm collides with a market norm, the social norm goes away for a long time",
                "Social relationships are not easy to reestablish - once the bloom is off the rose, it will rarely return",
                "In the circle-dragging experiment, unpaid participants working as a favor dragged more circles (168) than the 50-cent group (101)",
                "AARP lawyers refused $30 an hour for needy retirees but overwhelmingly accepted the same work for free",
                "A gift, even a small one, is sufficient to get people to help - but mention what the gift cost and they walk away",
                "Companies can't have it both ways: they can't treat customers like family one moment and impersonally the next",
                "Cutting benefits like medical coverage converts the employer-employee social relationship into a market relationship, and 'corporate loyalty' becomes an oxymoron",
                "Money is very often the most expensive way to motivate people - social norms are not only cheaper, but often more effective",
            ],
        ),
    },
    {
        "num": 5,
        "title": "Chapter 5: The Power of a Free Cookie",
        "pages": "93-104",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Selfishness Thermometer",
            "Scan 12 sharing scenarios - the free cookie box, the communal sushi plate, the one-cent Starbursts, the free truffle tray - and read the selfishness level in each. Name the norm at work and predict how many units each person takes.",
            "A candy booth where every offer lights a selfishness thermometer: the penny trays run hot, the free trays glow cool, and the communal sushi plate sits untouched with one piece left.",
            [
                "At Filene's Basement's 'Running of the Brides,' about a thousand brides-to-be trampled one another in a mass grab for discount wedding dresses, showing rampant selfishness",
                "When money is added to a situation governed by social norms, the added payment can reduce motivation - '$3 for your help?' turns a favor into underpaid work",
                "In the Susan-the-baker thought experiment, free cookies make you think about social justice and coworkers' welfare, while nickel cookies let you take as many as you want",
                "At the Starburst booth, about 58 students per hour bought candy at a cent each, while 207 per hour took candy when it was free - nearly three times as many",
                "Average candies per customer fell from 3.5 at one cent to 1.1 when free - almost all students politely took exactly one Starburst",
                "When price is not part of the exchange, we become less selfish maximizers and start caring more about the welfare of others",
                "The communal plate transforms food into a shared resource and leads us into the realm of social norms and sharing rules",
                "The sushi waitress said she finds one extra piece left almost every time - more common than people finishing all their sushi",
                "In the effort experiment, the monetary group took an average of 30 truffles, the free group 1.5, and the effort group 8.6",
                "When prices are zero and social norms are part of the equation, people look at the world as a communal good",
                "A $3 offer for a tire change changes your perspective: you look at the situation as work and conclude it is not worth your time",
                "Effort falls somewhere in the middle of the spectrum between market and social norms, keeping a large part of the social norms intact",
            ],
        ),
        "dialogue": (
            "Dialogue: The Susan Cookie Stand",
            "Play Susan the baker walking the office with a hundred cookies, then play the coworker she visits: first the free offer where you weigh hunger, waistline, and coworkers, then the nickel-apiece offer where you stock up without compunction. Feel the norm switch and narrate it out loud.",
            "An office corridor where the free cookie box glows warmly and each taker politely lifts one, while the nickel version of the same box turns the taker into a hoarder with a full basket.",
            [
                "With free cookies, you consider your hunger, your waistline, your love of chocolate-chip-oatmeal cookies, and how coworkers would feel if the cookies ran out",
                "When Susan asks a nickel apiece, you take a bunch to eat and take home without compunction, not thinking about depriving your coworkers",
                "By asking for money, Susan introduced market norms into the equation, chasing away the social norms that governed the free cookies",
                "Once money is introduced into the exchange, you stop thinking about what's socially right and wrong and simply maximize your cookie intake",
                "In economic exchanges, we are perfectly selfish and unfair, and we think following our wallets is the right thing to do",
                "When the price is not part of an exchange, we start caring about the welfare of others and limit consumption",
                "At the Starburst booth, the free condition drew 207 students per hour versus 58 in the monetary condition - but each took far fewer candies",
                "Average Starbursts per customer dropped from 3.5 at one cent to 1.1 when free, with almost all students taking exactly one",
                "Students collectively took fewer Starbursts as the price decreased from one cent to free - the opposite of the second law of demand",
                "We are caring social animals, but when the rules of the game involve money, this tendency is muted",
                "In the truffle experiment, the monetary group took an average of 30 truffles while the free group took a polite 1.5",
                "Not mentioning prices ushers in social norms, and with those social norms, we start caring more about others",
            ],
        ),
        "audit": (
            "Audit: The Communal-Resource Field Log",
            "Log a week of communal resources - the office snack shelf, the shared birthday cake, the last olive, the sushi plate - and record how many units you took and the rule you used. For each entry, note whether price was part of the exchange and how that changed your ethics.",
            "A kitchen counter diary: each shared dish logs its takers' counts in floating numbers - 1, 1, 1 on the free shelf, 3.5, 3.5, 3.5 next to the penny jar.",
            [
                "Taking the last olive when dining out with friends feels like such a big deal because the shared food becomes a social good",
                "At a party, you balance your desire for the Red Velvet cake against the desires of your friends and end up with only a medium-sized slice",
                "When sushi is served on a large plate in the middle of the table, taking the last piece feels 'a bit declassé'",
                "The waitress reported finding one extra piece of sushi left almost every time - more common than people finishing all their sushi",
                "When dining alone or with a personal portion, Ariely always manages to finish everything on the plate",
                "The communal plate transforms food into a shared resource that leads into the realm of social norms and rules for sharing",
                "When Starbursts were free, students limited themselves to an average of 1.1 candies and almost all took exactly one",
                "In the effort experiment, participants took an average of 8.6 truffles in exchange for finding pairs of s's - between the free 1.5 and the monetary 30",
                "Effort keeps a large part of the social norms, though not all of them - it sits on the spectrum between market and social norms",
                "Investing effort rather than cash in recycling, neighborhood watch, kids' schools, and soup kitchens keeps us in the domain of social norms",
                "The more people who stopped for free Starbursts took fewer candies each, so total demand actually decreased as the price went to zero",
                "As social animals we care about others, but when money is part of the game this tendency is muted",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Price x Social Norm x Demand",
            "Fill the 12-cell grid of the truffle and Starburst experiments: price points from 10 cents to free, the people who stopped, the units per person, and total demand. Mark where the first law of demand holds, where the second law fails, and the backward sloping zone.",
            "A demand-curve auditorium: the curve climbs steeply from 10 to 5 to 1 cent, then snaps backward at zero while two laws of demand duel on a scoreboard.",
            [
                "Dropping chocolate prices from 10 cents to 5 cents increased total demand by about 240 percent, verifying both laws of demand",
                "Dropping prices from 5 cents to 1 cent increased total demand by about 400 percent, verifying both laws of demand",
                "Dropping the price from 1 cent to free verified the first law (more people stopped) but disconfirmed the second (each took less), cutting total demand about 50 percent",
                "The theory of demand is solid except when we're dealing with the price of zero - when price is not part of the exchange, social norms become entangled",
                "At the Starburst booth, 58 students per hour bought at one cent while 207 per hour took when free - nearly three times as many people",
                "Average candies per customer fell from 3.5 at one cent to 1.1 when free, the opposite of the second law of demand",
                "Because more people took fewer candies, students collectively took fewer Starbursts as the price decreased from one cent to free",
                "Economists call the decrease in demand as price falls a 'backward sloping demand curve'",
                "The first law of demand says more women buy Vera Wang gowns at $249 than at $10,000; the second says buyers take multiple units at low prices",
                "Wedding gowns are a case where the second law is less relevant, yet multiple women have been sighted leaving Filene's with more than one gown",
                "In the effort condition, people took an average of 8.6 truffles - between the monetary 30 and the free 1.5 - showing effort keeps part of the social norms",
                "Cap and Trade puts a price on pollution, and once companies pay for the right to pollute, morality and concern for the environment become nonissues",
            ],
        ),
        "boss": (
            "Boss Battle: The Running of the Brides Melee",
            "Survive and manage the Running of the Brides: keep the gowns on the racks, hold the line at $249 to $699, and test whether any social norm can survive a thousand brides at peak arousal. Hold the event together and file your verdict on what emotion does to other-regarding behavior.",
            "A department store at dawn: brides in bright uniforms surge toward stripped racks, dresses flying like chum, while a slow-motion readout overhead shows selfishness maxing out as emotional intensity peaks.",
            [
                "At Filene's Basement's annual Running of the Brides, gowns originally priced at thousands of dollars are offered for a pittance, from $249 to $699",
                "The minute the doors open, the brides turn into a frantic, screaming, pushing mob, tearing as many dresses as they can carry off the racks",
                "Ariely witnessed rampant selfishness and terrible language, though not much violence, at the event",
                "At $249 instead of $10,000, a Vera Wang gown dramatically increases demand - more women can afford it, and some buy multiple units",
                "In economic exchanges, we are perfectly selfish and unfair, and we think following our wallets is the right thing to do",
                "When you're focused, mind and body, on one highly emotional objective - grabbing that wedding dress - it's hard to factor in others' well-being",
                "For social norms to operate, people cannot be at their most emotionally piqued state - when emotions run high, social norms get trampled",
                "Ariely gave up on fixing the event because getting a bride to concentrate on 'other people' versus a discounted gown seemed nearly impossible",
                "The Starburst experiment showed the flip side: when the price dropped to zero, customers restrained themselves and took far fewer units",
                "Average Starbursts per customer fell from 3.5 at one cent to 1.1 when free, and total demand fell about 50 percent when truffles went from 1 cent to free",
                "In the effort experiment, people took 30 truffles for money, 1.5 when free, and 8.6 for effort - effort keeps a large part of social norms",
                "When price is not part of the exchange, we become less selfish maximizers and start caring more about the welfare of others",
            ],
        ),
    },
]
