# -*- coding: utf-8 -*-
"""Phase 2 chapter data for The Power of Body Language (Reiman), chapters 3-4.
Each chapter: num, title, pages, domain, and 5 slots (scrub/dialogue/audit/matrix/boss),
each slot a 4-tuple (topic, player_mission, visual_frame_description, key_concepts[8-12]).
"""

D = "Body Language | Nonverbal Communication"

CHAPTERS = [
    {
        "num": 3,
        "title": "The Language of the Body",
        "pages": "107-156",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Head and Hand-to-Head Signals",
            "Work through 14 video clips of isolated gestures and tag each one by body region (head, hand-to-head, torso, arm) and meaning: head nod, head shake, head tilt, hair toss, once-over, hands to mouth, hand on nose, hand on ear, hand on chin, head/neck scratch, and head/neck rub. Lock your tag before the clip loops, and flag every signal that belongs to the 'see no evil / speak no evil / hear no evil' deception triad.",
            "A split-screen video player with frame-stepping controls; a glowing body-diagram hotspot map on the right highlights the gesture's region as each clip plays, and a tag drop-down snaps your verdict into a running evidence log with a green/red accuracy meter.",
            [
                "The head nod, movement of the top of the head down toward your partner, is an (almost) universal signal for acknowledgment and approval",
                "Some experts trace the nod to the submissive bow; others to our reptilian ancestors' head bob",
                "Excessive nodding makes a person a human bobble-head doll, signaling meek compliance - 'Yes, absolutely, you bet, you're right'",
                "The head shake is a hardwired, universal negation, seen in babies twisting away from a spoon of strained peas",
                "The head tilt exposes the neck on the opposite side - animals do it to appear submissive, and it can increase trust",
                "Hair toss is a preening attention-getter: 'I am here and I feel good about myself,' like peacocks fanning feathers or lions shaking manes",
                "Hands to mouth can signal sensuality, surprise, nervousness, shame, embarrassment, anticipation - or deception; context decides",
                "The 'Pinocchio effect': anxiety raises blood pressure, swelling the soft tissue in the nose so the skin tingles and we touch or scratch it - a nervous system response, not a direct lie signal",
                "Hand on ear says 'I don't want to listen to this anymore. You're hurting my ear' - the 'hear no evil' signal of the deception triad",
                "Hand on chin with index finger pointing up toward the ear and thumb on the chin signals evaluation and assessment",
                "The skeptical neck scratch: head tilted, index finger of the dominant hand scratching just below the earlobe - 'Really? Are you sure about that?'",
                "George Washington reportedly practiced the maxim 'When in Company, put not your Hands to any Part of the Body'",
            ],
        ),
        "dialogue": (
            "Dialogue: The Congruence Check",
            "Sit in on six conversations where words and body fight each other - a politician swearing agreement while shaking his head, a coworker shrugging through a firm denial - and choose the accurate read from three interpretations. Then pick the reply that keeps rapport alive, deciding whether a nod means 'keep talking' or 'wrap it up, my turn.'",
            "A split-screen conversation scene with two NPCs; each speaker carries a congruence meter that dips when words and gestures disagree. Your reply options float as thought-bubbles, and the right read restores the meters and brightens the room's lighting.",
            [
                "When body language and spoken words match - are 'congruent' - you send signals of trustworthiness; mismatch reads as dissonance, unease, and deception",
                "Both speech and gesture are controlled in the Broca's area of the brain, very close to where mirror neurons are believed to reside",
                "People blind since birth use hand gestures when speaking with other blind people, from toddlers to adults - gestures help the speaker articulate as well as the listener understand",
                "A series of studies found that nodding to yourself reinforces your faith and confidence in your current thought - positive or negative - and that the act of nodding alone can put you in a better mood",
                "The impatient nod: a chronic nodder who purses his lips or puts a finger to his mouth and nods faster is saying 'I get your point. Wrap it up - my turn to talk'",
                "Women nod a lot more than men, as encouragement and a sign of attention; men tend to nod when they actually agree",
                "Politicians emphatically state agreement verbally while unconsciously shaking their heads - leakage that means covering one's backside or interior conflict",
                "One study found that shaking your head actually decreases your self-confidence in your own opinions",
                "Reiman's head-still experiment: keep your head perfectly still while a friend speaks and she will start tilting and nodding to coerce mirroring, then demand 'Come on - what do you think?'",
                "A shoulder shrug during a committed verbal statement - 'I was not in that bar!' with lifted shoulders and exposed palms - tells you the person is lying or deeply uncertain",
                "Many liars know the palms-exposed gesture is powerful and combine it with a shrug and indifference: 'Trust me, I didn't do it'",
                "An analyzed politician said 'It's very important that we do this' with hands close together, then 'It's not that big a deal' as his hands swept out - gesture distance revealed how the issue truly felt",
            ],
        ),
        "audit": (
            "Audit: The Bob Effect - Logging Gesture Tells",
            "Audit a recorded staff meeting the way Reiman audited Bob's lip-picking: replay the tape, timestamp every hand-to-head, torso, and arm signal, and judge which ones were congruent with the words. At the end, predict from your log alone whether the meeting ended well or fell apart, then compare against the recorded outcome.",
            "A nonlinear video editor interface over a boardroom recording; a timeline fills with colored pin-marks for each gesture class as you scrub frames, and a verdict panel asks you to rate the meeting's fate before the outcome stamp drops.",
            [
                "Bob's lip-picking tell: the high-level manager picked his lip at the first sign of trouble, and entire departments used his gesture as a gauge of whether a critical meeting had gone well or fallen apart",
                "Torso signals are all about power - giving yours up or trying to get more - because the torso houses the organs and feels vulnerable to attack",
                "Hunched shoulders telegraph insecurity and a total absence of authority, and denote depression, low self-esteem, and lack of confidence",
                "The backward 'lazy lean' says 'What's being discussed is not important enough for me to have to sit up straight' - a great way to tell people you are arrogant and cocky",
                "If a listener shifts from a forward lean to sitting back suddenly, that is a cue they disapprove of what was just said",
                "The forward lean says 'I'm interested - tell me more' and translates into sincerity and confidence, but never go into anyone's personal space uninvited",
                "Crossed arms are as close as you can come to hugging yourself, but read as defensive, cold, and closed off - even when done innocuously",
                "Five moms on the block standing with arms crossed are mirroring each other and holding rapport with a supposedly hostile gesture - context matters",
                "Arms at sides feels as solid as a tree trunk and telegraphs the solidity and symmetry that make people trust you, calming the dynamic of a group",
                "The figure four: with a backward lean, arm cross, and finger-to-chin pose it is negative and confrontational; with an open countenance it shows an overly confident, casual attitude",
                "Chest thrusts are broadside displays to seem larger - men puff their chests; women thrust theirs to exhibit their goods, and it is way too sexual a signal for business",
                "The ten nervous gestures that turn people off: jiggling car keys, clicking pen caps, tapping a foot, chewing on anything, pacing, swaying, playing with a water bottle cap, picking fingernails, picking your lip, finger drumming",
            ],
        ),
        "matrix": (
            "Matrix: Gesture x Context x Meaning Grid",
            "Score 12 gestures (head tilt, palms up, palms down, palms forward, steeple, chop, politician's point, single and double-barrel point, pen point, thumbs-up, preening) across the contexts of job interview, bar, boardroom, negotiation, and funeral. Mark each cell where the meaning flips - the same tilt that wins a modeling audition sinks an accounting interview - and hit the grid before the timer drains.",
            "A 12x5 data wall glows cell by cell: rows are gestures, columns are contexts, and each cell fills green (rapport-building), red (rapport-breaking), or amber (context-dependent). The tilt row and the palms rows shimmer as the most volatile cells.",
            [
                "People who tilt their heads just eight degrees to the right are judged more trustworthy; women found the left tilt 'flirtier' and left tilts were rated more attractive",
                "Reiman's interview rule: tilt right for accounting, law, or medicine; tilt left if you are trying to become America's next top model",
                "Palms down is a dominant gesture suggesting control - parents use it to tamp down children, so adults receiving it feel patronized",
                "Palms exposed (up) is a universal sign of supplication and openness; primatologists found it in chimpanzees begging for food, and Darwin made it part of the shoulder shrug",
                "Palms forward literally tells people 'Stop' and requests complete attention; pushing palms out toward an approaching person puts up a barrier against touch",
                "The steeple is a 'precision gesture' (David Givens) made possible by the same brain structures that allowed man to create tools, communicating authority, confidence, superiority, and reasoned thinking",
                "Spread fingers wider in the steeple and you take up more space and reflect more dominance; raised hands signal superiority, lowered hands signal openness - either way you create a barrier",
                "The chop mimics the motion of a weapon - 'I [chop] did [chop] not [chop] do [chop] that [chop]!' - and is read as an emphatic strong-arm tactic",
                "Normally the dominant hand sits on top in the chop; Bill Clinton is a lefty, so when he used his right hand to emphasize his innocence on national TV he telegraphed insincerity",
                "The politician's point (thumb and forefinger meeting like the A-OK symbol) lets elected officials appear decisive without appearing aggressive - and was a favorite of Tony Soprano",
                "The pointed index finger is symbolic of a gun; escalating from a single to a double-barrel point marks a very hot topic, as in Bill O'Reilly's on-air clash with Geraldo Rivera",
                "The pen point closes distance and can read as an invasion; at a signing table, pointing to contract clauses with a pen leads the other person's eye 'like a puppy on a leash' while feeling collaborative",
            ],
        ),
        "boss": (
            "Boss: The Master Communicator Gauntlet",
            "Face the timed finale: 20 rapid-fire clips of real-world gestures under a shrinking clock. For each clip, name the signal, spot the incongruence if one exists, and pick the rapport-preserving action - and survive the final round where a single misread of a fig leaf, a preen, or a heart touch ends the run.",
            "A dim broadcast studio, a single hot spotlight, and a towering scoreboard counting down from 60 seconds. Clips slam in edge to edge like a news wall; each correct verdict throws a green pulse across the stage while mistakes snap the lights red.",
            [
                "The body is a much better indicator of true emotions than the face, because most people don't try to mask their body's revealing signals - they don't even realize those signals are happening",
                "Charisma is developed by integrating faith in yourself into trusting your intuitive read of others' body language and responding with confident, steady messages that build rapport",
                "Insecurity and nervousness lead to jerky movements, so confidence and natural gestures go hand in hand",
                "Preening is the conscious or unconscious grooming of yourself for another's attention - a man pulling up socks, a woman fixing her hair - and a confident signature move (hair flip, lip stroke) done well highlights your best assets",
                "The heart touch: a wife with her hand resting on her husband's heart in photos shows deep affection; we clutch our own neck to show vulnerability and clutch a beloved's chest when passionate",
                "The fig leaf (one hand folded over the other at the lower body) protects against pain, physical or emotional - Spanish royals used it at a funeral for six UN soldiers killed in Lebanon - and can also be done with a briefcase or pocketbook",
                "Hands behind the back says 'You're so unthreatening that I can be entirely unguarded in front of you without fear'; clutching your wrist behind the back instead signals frustration and growing anger, as if restraining yourself",
                "University of Chicago study: students who watched a math teacher use sweeping gestures were four times more likely to use the same gestures during a test and got significantly more problems correct - gesture cements learning",
                "Contain your gestures below your shoulders and above your hip line so incongruent slips stay small - a core of the Reiman Rapport Method (chapter 9)",
                "Men's brains are 10 percent bigger than women's, but women have more brain cells in the left brain, the seat of language, and use both sides of the brain for speech; men use only one",
                "The once-over rhyme: 'Eyes in front, I like to hunt / Eyes on the side, I like to hide' - men use hunt-vision in the up-and-down glance while women covertly take in a whole body in one quick glance without moving their heads",
                "Lip enhancers containing capsicum (red pepper) stimulate blood flow to make lips plumper and rosier - plump lips remind men of sexually stimulated tissue, which is why bulbous lips get noticed",
            ],
        ),
    },
    {
        "num": 4,
        "title": "Decoding Space and Touch",
        "pages": "157-204",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Hall's Four Zones",
            "Classify 16 scenario clips - sidewalk, subway car, conference table, cocktail party, wedding hug, concert front row - by where the interaction sits on Edward Hall's proxemics scale: public, social, personal, or intimate zone. Flag every clip where the zone shifts mid-interaction, and tag the moment a stranger's entry triggers an invasion reaction.",
            "A wireframe street scene with concentric colored bubbles around each person; the clip's distance readout glides across a four-zone ruler at the bottom of the frame, and you snap a zone pin onto the timeline before the clip ends.",
            [
                "In 1966 Edward Hall coined the term proxemics for the study of how human beings interact within space, replacing the old amorphous idea of 'elbow room'",
                "The public sphere extends twelve to twenty-five feet or more - the space between a speaker and the audience at a rally, or a concertgoer and the performer",
                "The social sphere affords about four to twelve feet - the 'beach blanket zone,' used with business associates across a conference table",
                "Personal space extends two to four feet - the 'friendship zone' and 'cocktail party zone,' where you shake hands and have your best conversations",
                "Intimate space runs from your body to about two feet - touching space reserved for your absolute closest friends, children, and spouse",
                "Hall's zones are culture-dependent: personal space in the United States can be social or even public space in parts of Latin America",
                "Zone shifts are constant: a quiet residential sidewalk is public space, a city street at rush hour becomes social space, and a packed subway is personal if not intimate",
                "In a seating study, of 1,081 people passing pairs seated twenty-six inches apart, 53.3 percent walked between two females, 29 percent between a male and female, and only 17 percent between two males - women's space is invaded more because they are seen as lower status",
                "Invasion reactions include a threatening stare followed by a gaze turn, increased blinking, leaning away, decreased smiling, stiffening, crossed arms, blushing, piling things between you, and refusal to share personal details",
                "When people feel crowded into their personal space, heart rate and blood pressure rise, skin gets tingly and sensitive, and EEGs show heightened brain activity",
                "Research found that even the mere idea of being crowded made people actively dislike those around them",
                "Smaller people tend to be closer talkers, as do confident extroverts who love to bond, while high-status individuals take up more space with their bodies and gestures",
            ],
        ),
        "dialogue": (
            "Dialogue: The Stephen Protocol - Proximity Role-Play",
            "Play both sides of six encounters: as a real estate agent, a waitress, a networker, and a client whose space is invaded. Read the other person's distance preference, decide when to advance, hold, or retreat, and recover if you breach - exactly the fix that tripled Stephen's real estate sales. One wrong step into the four-foot danger zone and the client is gone.",
            "A warm office scene with two characters circling each other; a live distance meter between them ticks in feet and inches, while the client's comfort bar drains during each wrong advance and refills as you back off and mirror their preferred distance.",
            [
                "Stephen the real estate agent stood about four inches from Reiman's shoes during a seminar break; once he simply gave people their space and stopped going toward them, his sales practically tripled",
                "A waitress who touches a patron while he orders a $10 plate of pasta is thought of as warm and hospitable and earns a much bigger tip",
                "A real estate agent who comes within four feet of a client discussing a $500,000 purchase will be seen as incredibly aggressive and might be 'kissed off forever'",
                "In all settings, higher-status people are afforded a wider berth of space, and people who touch others are considered higher status than those being touched",
                "Break the rules of space and touch during a first impression and you are quickly scanned as 'unsafe' - a fast and definitive 'no'",
                "Women who wanted someone's approval moved in and stayed about fifty-seven inches (four feet, nine inches) away; those not at all interested averaged about ninety-four inches, almost eight feet",
                "Male college students who disliked their teacher said they would hold almost five and a half feet of distance in a one-on-one talk; if they liked him, just over two feet - women moved from almost five feet down to a cozy twenty-two and a half inches",
                "Men prefer to be approached at a 90-degree angle with about thirty-five inches of distance; women like a frontal approach with about thirty-two inches because they seek out more eye contact",
                "Very, very few people will ever tell you that you have overstepped into their personal space - they just gradually withdraw their attention, then flee, and apologizing will not bring them back",
                "Celebrities and extremely attractive people may be granted entry to your personal zone without asking - Bono crossed the stage to find a woman to dance with, and normal proxemics rules did not apply",
                "Your boss may feel entitled to pat you on the back, and you are expected to feel honored - but he would likely be horrified if you returned the favor",
                "Shifting Reiman's cubicle eight feet to the end of a row of three turned a mid-level professional into a message-taking administrative assistant - positions equal power",
            ],
        ),
        "audit": (
            "Audit: The Fourteen Touches Review",
            "Review 16 clips of people touching and identify which of Desmond Morris's fourteen social touches appears - handshake, body guide, pat, arm link, shoulder embrace, full embrace, hand in hand, waist embrace, kiss, hand to head, head to head, caress, mock attack, and the rest of the list. Then judge context: would this touch be welcome or career-ending at the office, and log your verdict before moving on.",
            "A courtroom-style review board: each clip freezes into a still with a numbered touch label, and you drag it into an 'appropriate / risky / forbidden' verdict column while a style guide of acceptable touch zones glows in the corner.",
            [
                "Desmond Morris created a list of fourteen ways humans touch each other in social settings in his book Manwatching: A Field Guide to Human Behavior",
                "The handshake likely came into common use in medieval times, when soldiers gripped each other's forearms to prove no weapons were up their sleeves; business deals are still done 'on a handshake'",
                "The twelve wrong handshakes include the limp, dominant, submissive, fingers-only, overly affectionate ('politician's handshake'), mini-hug, sweaty, cold-hands, over-the-table, forward-lean, and seated varieties",
                "The only right handshake: lean slightly forward, meet the eye, extend your right hand parallel to the ground, offer your full palm, grip as if comfortably holding hands, thumb straight up, elbow slightly bent, pump two to three times, finished in no more than two to three seconds",
                "The body guide takes the other person gently by the elbow - never the upper arm, which feels too authoritative - while you stay slightly behind so it is a gentle prod, not a pull",
                "The pat mirrors the beat of a person's heart - very fast when they are wound up, very slow as they drift off - but with adults it can be dismissive or condescending",
                "Bill Clinton gave Hillary a 'Gee, we're kind of like buddies' hug and patted her three times on the back right after her 2008 presidential announcement - a friendly but not intimate couple signal",
                "The hand is the only part of a stranger's body you are allowed to touch without further information being exchanged",
                "Men can touch each other on the hand, shoulder, forearm, or upper arm - anything else is not received well, and being touched by another man was the touch least welcomed by all men in one survey",
                "Women have more latitude touching other women (hands, forearm, upper arm, knee) and can touch a man almost anywhere, but a man touching an unknown woman should stay strictly chaste - hand or forearm only",
                "Librarian study: patrons whose palms were touched when their library card was returned were more likely to say they enjoyed the experience and would return",
                "If a customer's eyes narrow or they break eye contact, don't touch them - restart the rapport-building process instead, because a touch then looks like manipulation",
            ],
        ),
        "matrix": (
            "Matrix: Zone x Status x Touch Grid",
            "Score 12 interactions across three axes - proxemic zone, status differential, and touch permissibility: the CEO jabbing the mailroom guy, the Gore interview, kangaroo-care preemies, Miami vs. Paris teens, and the man hug. Mark where the chapter's rules bend for celebrities, families, and cultures, and identify the one cell where a touch is medically healing rather than social.",
            "A 3D wireframe grid: the x-axis is zone (public to intimate), the y-axis is status difference, and the z-axis is touch permissibility; each scored interaction drops in as a glowing node, with cultural outliers pulsing violet against the green norm field.",
            [
                "A CEO who jokingly punches the mailroom employee's arm is seen as jovial and 'in touch,' while the mailroom guy who attempts a jab at the CEO might be escorted from the premises",
                "Touch starts in the womb; in 'kangaroo care' for preemies, a mother's breasts automatically heat up as much as two degrees Celsius in five minutes when her baby is cold - with no machines and not a word spoken",
                "Compared with standard NICU treatment, kangaroo-care preemies show a 75 percent greater reduction in apnea, better oxygen saturation, faster weight gain, and earlier hospital release - and their brains fall into a rhythm full-term babies don't reach until four weeks of age",
                "A thirty-minute massage lowered the fundamental frequency and sound pressure of people's voices - they sounded more relaxed and had more appealing body language because they had been touched",
                "School-aged kids who are cuddled more are less aggressive on the playground, and adolescents who receive massage therapy are less depressed and more empathetic",
                "Analyzing a videotaped encounter between a reporter and Al Gore, Reiman caught in slow motion Gore's slight backward shrink when the reporter repeatedly entered his personal space and grasped his arm - an automatic pull-away response",
                "In a packed elevator or a five-deep parade crowd you develop a 'nonperson orientation': you and the stranger silently agree to deny each other's existence and treat each other as objects",
                "Miami vs. Paris McDonald's pilot studies: Parisian teens leaned against, stroked, kissed, and hugged peers, while Miami teens self-touched more and touched others in aggressive mock-attack ways - a suspected cultural touch deficit",
                "Man hug variants: one hand, one hand with a handshake, one hand with a back pat, one hand with a shoulder bump, two hands (bear hug), or two hands with a back pat - most involve only the upper body, and straight men pull back their hips in the bear hug to guarantee no contact",
                "Kissing display rules shift by microculture: double-cheek kisses are now passé in New York but still the norm in London and Paris, and parts of the Netherlands greet acquaintances with three kisses - left, right, left",
                "Desmond Morris's road map to sex: eye to body, eye to eye, voice to voice, hand to hand, arm to shoulder, arm to waist, mouth to mouth, hand to head, hand to body, mouth to breast, hand to genitals, then genitals to genitals",
                "Nancy Henley's Body Politics (1977): others are more likely to touch you when they are giving information, giving an order, or trying to persuade you - and less likely to touch when you are in deep conversation at a party",
            ],
        ),
        "boss": (
            "Boss: Space and Touch Command",
            "Run the finale: a timed networking event where every approach, advance, hold, and retreat scores rapport against a shrinking clock. Spot the boundary-breacher working the room and neutralize the damage while holding your own zone - Reiman-style, without retreating an inch - and end the run by deciding which of three strangers earns the right to enter your intimate space.",
            "A crowded wireframe ballroom swarming with glowing proximity bubbles; NPCs surge and retreat around you as you pick moves from a command wheel. A rapport score climbs in the corner, and the boundary-breacher pulses red as their bubble overlaps yours, daring you to respond.",
            [
                "When someone invades your space, take a quick step back, then fold your arms to put a barrier between you, and if they still don't get it, move closer to them - a martial-arts move that turns their energy back on them",
                "It is critical, especially for women in business, to answer a zone invasion assertively right away, until the person relents - once you are seen in a submissive light, it is hard to reverse that impression",
                "The sole exception to backing off is using a space invasion as a manipulation tactic against someone you recognize as insecure - but it can easily backfire if they get angry instead",
                "When people prefer larger personal zones, they will like you even more if you mirror their preferred distance, because it suggests another similarity between you",
                "A landmark 1998 University of Chicago study found pheromones are responsible for the long-observed synchronization of menstrual cycles among women living in close proximity",
                "The closer women are to ovulating, the more they are attracted to the scent of men with higher testosterone levels - an evolutionary preference that enhances reproductive success",
                "Our individual scents are as distinctive as fingerprints, and six-day-old infants prefer the smell of their mothers' breasts to those of other nursing mothers",
                "Research shows our bodies are actually repulsed by artificial perfumes; women should stick to musky jasmine, vanilla, or amber and men to sandalwood, cedar, and balsam - or skip scents entirely, as in the Princess by Vera Wang interview disaster",
                "Smells and early childhood memories are both processed in the basal ganglia, the reptilian part of the brain - the reason a whiff can bring back twenty-year-old memories",
                "Men and women almost universally prefer that a new acquaintance stand slightly to their right side, aligned with their right eye - the right eye links with the left brain, the seat of rational thought, while the left side may trigger anxious emotions",
                "A study of married couples: the more satisfied the husband was with his marriage, the closer he walked toward his wife before stopping at the ideal conversational distance",
                "In a study of wives under stress, the simple act of their husband offering a hand to hold lessened their brain activity and decreased the release of stress hormones; Ellen Kreidman's Light His Fire recommends couples practice ten-second kisses to deepen connection",
            ],
        ),
    },
]
