# -*- coding: utf-8 -*-
"""Phase 2 chapter data for The Power of Body Language (Reiman), chapters 7-9.
Each chapter: num, title, pages, domain, and 5 slots (scrub/dialogue/audit/matrix/boss),
each slot a 4-tuple (topic, player_mission, visual_frame_description, key_concepts[8-12]).
"""

D = "Body Language | Nonverbal Communication"

CHAPTERS = [
    {
        "num": 7,
        "title": "Reading Their Secret Signals",
        "pages": "260-277",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Deceit Signal Clusters",
            "Screen 15 short clips and flag the common deceit signals from the chapter - dilated pupils, more pauses, speech errors, allness terms, hand-to-mouth covering, nose rub, fake cough, increased swallowing, eye rubbing, higher-pitched voice, shorter answers, and flushing. For each clip, tag the signal, then decide whether it is a norm-level quirk or a true deviation - remember, no single gesture is proof of a lie.",
            "A freeze-frame video console where each clip is overlaid with a blinking body-part heat map; a verdict bar at the bottom snaps between NORM and DEVIATION as you tag cues.",
            [
                "During ten-minute conversations with strangers, 60 percent of us lie at least once",
                "Only half of the people who lie reveal their deceit in microexpressions",
                "No single gesture is directly linked to deceit; clusters of two or three gestures raise certainty",
                "Dilated pupils and increased blinking are arousal-based deceit signals",
                "Liars often show more pauses, more speech errors, and shorter verbal responses",
                "'Allness' terms - all, always, everyone, none, nobody - mark overstated claims",
                "Flushed cheeks, sweating, and increased swallowing can appear when the conversation doesn't warrant it",
                "Hands to mouth, fingernail biting, and fake coughs are classic deceit signals",
                "Liars may show fewer or more body movements depending on their individual norm",
                "The receiver of a lie can tip the liar off with recognition cues, helping the liar to lie",
            ],
        ),
        "dialogue": (
            "Dialogue: The Late-Night Whereabouts",
            "Your spouse comes home late and the story smells. Re-establish the baseline with casual memory questions, then ask where he or she was. Choose follow-ups that drill down into details and double back on earlier answers - 'What was your entre? I thought you said filet' - while watching for pitch rise, overcompensating stares, or anger when whereabouts come up.",
            "A kitchen table at 1 a.m. with two coffee mugs; dialogue choices appear as thought bubbles while a live tell-meter tracks pitch, blinking, and eye shift across the bottom of the frame.",
            [
                "Norm your spouse first - you already hold a baseline for his or her behavior",
                "Pitch rising when answering questions about infidelity is a listed suspicion signal",
                "Body orientation away from you, especially the feet, signals a drifting partner",
                "Shifting eyes when asked whereabouts suggests a cover story",
                "Staring directly into your eyes when asked may be overcompensation by a liar",
                "Getting angered when asked whereabouts is on the infidelity watch list",
                "Microexpression sneering can flash even when love has merely waned",
                "Drill down on details - what did you eat, what time, what did it cost, what did he drink",
                "Double back on earlier answers; most liars don't think out every aspect of the lie",
                "Liars use distancing language, skip names and details, and repeat stock phrases",
                "Gazing into each other's eyes for three minutes at a time, twice a day, can repair a marriage",
                "Prolonged kissing - ten to twenty seconds or longer - twice a day strengthens any romance",
            ],
        ),
        "audit": (
            "Audit: Norm the Target's Baseline",
            "Run the chapter's norming protocol on three recorded targets: ask factual, visual-memory questions - the neighbor's name, the kind of dog - and log each target's eye direction, blink rate, breathing, and skin color before the kill question: 'Where were you last night?' Rate each deviation and identify the target's one true tell.",
            "A split-screen lab view with a polygraph-style strip chart; factual-question answers scroll in green while the kill-question answer scrolls in red for direct comparison.",
            [
                "Norming works on the same principle as a polygraph: factual questions first, then the provocative one",
                "The difference between reactions to factual and provocative questions is the signal",
                "People often look up and to the left when recalling a visual memory from the past",
                "A liar constructing a lie typically shifts his eyes in the opposite direction of his norm",
                "The eye shift happens because the lie is constructed in a different part of the brain",
                "Blink rate can be normed - it increases when we are nervous",
                "Breathing (deep versus shallow) and skin color (pasty versus flushed) can also be normed",
                "Gesture size is normable: big to none, or small to big sweeping movements",
                "Once you have seen the tell, never reveal it or the person will consciously minimize it",
                "Incongruence - words that don't match the body - is the easiest way to detect insincerity",
            ],
        ),
        "matrix": (
            "Matrix: Secret Signal x Scenario x Verdict",
            "Build the scenario matrix for 10 situations - lying, strong-arming, distrust, hiring, firing, attack, her seduction, his seduction, infidelity, and friendship - and assign each of 20 signature cues to the right scenario. Rank each cue from harmless quirk to near-certain signal, then pair it with the chapter's prescribed response for that situation.",
            "A 10x10 grid of body-part icons; cells light up with a cue label - JAW JUT, SHOE DANGLING, PAT DURING HUG - and a confidence bar climbs as each row completes.",
            [
                "Bullying cues include invading personal space, standing over you, jaw jutting, and eye rolling",
                "Distrust shows in a tilted head with squinted eye, crossed arms, neck scratching, and ear rubbing",
                "Interview yes-signs include nodding while you speak, leaning toward you, and walking you to reception",
                "An interviewer who stops nodding is unconsciously discouraging you from speaking",
                "Dismissal signs include occasional glares, head shakes while you speak, and a secretary who stops the small talk",
                "Attack signs include the stalker stare, clenched fist, tongue sticking out, and finger jabbing",
                "Her signals: dangling shoe, rubbing the top of a glass, hair tossing, throat baring, crossed-uncrossed legs",
                "His signals: preening, thumb looped in the front pocket, hands on hips, eyes-to-mouth-to-eyes gaze",
                "True friendship shows in mirroring, head tilting, equal conversation sharing, and joy at your successes",
                "Shoulder pats during hugs and forward-lean hugs with no lower-body contact mark waning love",
                "Trust your golden gut: if time with a friend leaves you depleted, the signals have been incongruent",
            ],
        ),
        "boss": (
            "Boss Battle: The Ambush in the Parking Lot",
            "A woman exits her car in a dim garage and a stranger begins closing in - stalker stare, clenched fist, sarcasm, high-pitched voice. Decide under time pressure: read the victim-profile research on her own walk, then choose between submissive de-escalation, holding ground, or flight before the aggressor crosses the intimate zone.",
            "A first-person view from a garage walkway with a threat gauge pulsing red as the figure closes; cue pop-ups - CLENCHED FIST, MOUTH SMILE ONLY - appear inside one-second decision slots.",
            [
                "The stalker stare and very close proximity in your personal zone are intent-to-attack signals",
                "A smile on the mouth but not in the eyes can precede an attack",
                "Women who lift their feet and walk slowly are judged easier to attack",
                "The least vulnerable have a vigorous walk, long stride, widely swinging arms, and a fast pace",
                "Heavier women are attacked less; weight matters even more for men",
                "Women in bare feet or heels are more likely attacked than those in flat shoes; skirts lose to pants",
                "Once in an attacker's sights, adopt body language similar to or slightly more submissive than his",
                "Keep your voice calm and even-tempered to avoid fueling further rage",
                "Let them take the wallet - acknowledging irrational anger is the way to defuse it",
                "Bullies love a victim: stand your ground, smile right back, and maintain eye contact",
                "When someone invades your space, don't move; even lean toward them to reclaim it",
                "Crossed arms can answer with 'That's not going to happen. No way, no how.'",
            ],
        ),
    },
    {
        "num": 8,
        "title": "Using Your Own Secret Signals",
        "pages": "278-296",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Trustworthiness Transmitter",
            "Screen 15 body-position stills of a speaker delivering a pitch and flag which trustworthiness signals are present - palms up, steady eye contact, uncrossed arms, feet flat on the floor, tall straight posture, feet pointed at the target, nodding on positive points, and the occasional submissive shrug. Then spot the leaks: smirks, nose scratches, and smiles that are too many.",
            "A wireframe figure on a stage with green halo highlights on every signal present; a credibility meter at the top slides as you tag or miss cues.",
            [
                "Top trust signals: palms-up gestures, eye contact, uncrossed arms, feet flat on the floor",
                "Keep posture tall and straight, feet pointed toward the target, smiles - but not too many",
                "Nod when making positive points and shake your head when making negative ones",
                "Occasional submissive shrugs belong on the trustworthiness list",
                "Human beings run a 'truth bias' - we are preprogrammed to expect honesty from others",
                "We detect truth accurately 67 percent of the time but a lie only 44 percent of the time",
                "The most popular middle and high school students are also the best liars",
                "Practice like an actor: repeat lines until they flow with no speech disturbances",
                "Look away at the right moments to indicate regret or remorse",
                "Success shows as smiles, nods, and mirrored body language; smirks and nose scratches mean work harder",
                "Breathe deeply to manage anxiety while you practice your signals",
            ],
        ),
        "dialogue": (
            "Dialogue: The Friday-Night Favor",
            "Get your assistant to stay late on a Friday. Open with her WIIFM, sit in her visitor's chair, put your hands on her desk, lean in, hunch your shoulders, turn your palms up - then ask, stop talking, and hold eye contact. If her posture turns submissive - averted eyes, slumped shoulders, turning away - you've strong-armed her; rebuild rapport before you lose her.",
            "A cubicle at dusk with a warm lamp; dialogue wheels sit on one side and a posture-scan silhouette on the other that shifts from OPEN to SUBMISSIVE as you choose moves.",
            [
                "WIIFM - 'What's in it for me?' - is the question to answer before you ask for anything",
                "Begin with empathy; your mirror system recalls a time you felt like the other person",
                "For an emotional request, line up with the other person's right eye; for an intellectual one, the left eye",
                "For a woman, stand face-to-face on the outer edge of the personal zone, about three feet",
                "For a man, stand at a 90-degree angle, three to four feet away",
                "Persuasion signals: faster speech, varied pitch, open body posture, open palms, steady eye contact",
                "Use smiles that involve the eye crinkle and mirror the other person's body language",
                "After you make the request, stop talking but maintain eye contact",
                "If you've strong-armed someone, their posture turns submissive - averted eyes, slumped shoulders",
                "When motivation works, pupils dilate and the person nods and acts like it was their own idea",
                "A good manager is nothing more than a benevolent manipulator",
            ],
        ),
        "audit": (
            "Audit: The Showroom Negotiation Audit",
            "Audit two recorded showroom encounters. First score the buyer's posture - closed posture, crossed arms, look of indifference, closed lips, body angled away, subtle head shakes - then norm the salesperson on factual questions (list price, mpg, the color's name) and catch the exact moment he deviates from his norm while calling your price 'unlikely.'",
            "A showroom floor view from behind the sales desk; two overlays - YOUR POSTURE AUDIT and HIS PRICING TELLS - with timestamps marking every deviation moment.",
            [
                "As a buyer you have all the leverage, and you give it up by volunteering information about yourself",
                "A fluent salesperson reads your age, sex, walk, clothes, and what your eyes linger on in the first thirty seconds",
                "Retain power with closed posture: crossed arms, closed lips, body angled away, a look of indifference",
                "Disclose neither your degree of interest nor the size of your budget for as long as possible",
                "As the price nears your range, open up gradually - grab your opposite arm instead of crossing",
                "Don't go from scowls to grins; the salesperson may feel played and stop playing",
                "Ask factual questions - list price, standard mpg, the color's name - to norm his pricing behavior",
                "If he deviates from his norm while calling your price unlikely, you're in a comfortable range",
                "Seller tells that you have the deal: covering the mouth, fidgeting, biting the lip, darting eyes, pacing",
                "Flushed skin, perspiring, fast shallow breathing, and nose rubbing mean he's working overtime to soften you",
                "Politely wait him out and you'll eventually get your price or something close to it",
            ],
        ),
        "matrix": (
            "Matrix: Goal x Target x Signal Set",
            "Build the influence matrix for 9 goals - seem trustworthy, motivate, negotiate, close the deal, unite a team, seduce him, seduce her, approach a group, and make friends - and assign each of the chapter's signal sets to its goal. Mark which signals are shared across goals (open palms, eye contact) versus exclusive (right-eye alignment, thumbs in the front pocket).",
            "A nine-column matrix with signal chips that snap into columns; shared signals glow amber across multiple columns while exclusive ones lock in with a click.",
            [
                "The flirt technique: pause at the entranceway, sweep the room, then mill about before approaching",
                "Toss your hair back to expose your neck, then brush past him with a coy 'Oh, excuse me'",
                "Glance over your shoulder to make eye contact once more, then smile, look down, and look back up",
                "From ten to thirty feet away, turn your back, look over your shoulder, and repeat until he notices",
                "Men assume you are flirting if you stand too close - they can't tell friendly from flirty",
                "To seduce her, use signals sparingly; stacking them all at once reads as predatory",
                "Women like to be heard: make eye contact, tilt your head, nod, and show comprehension of their words",
                "Never enter a woman's personal space uninvited",
                "A group is open to entry with three or more people, uncrossed arms, scanning eyes, and open palms",
                "A closed group - feet and bodies pointed at one another - means you're not invited; don't try",
                "One person's feet poking out from the group is your entranceway; let them start the conversation",
                "To make friends, listen twice as much as you speak",
            ],
        ),
        "boss": (
            "Boss Battle: Close the Deal",
            "You've pitched the client and must now read the closing moment in real time. Watch her normed baseline for the no-gestures - folded arms, tapping, hands over the mouth, squinting eyes - that mean don't ask yet, the maybe-signals of a sip, cleaned glasses, or a chin stroke, and the yes-cluster of forward lean, open palms, pupil dilation, and eye twinkle. Fire the closing question only inside the yes window.",
            "A boardroom table with the client's face rendered as a live heat readout; a deal-meter swings between STALL, MAYBE, and CLOSE with every cue you correctly catch.",
            [
                "You must norm the client before you can read the critical closing moment",
                "Whatever signals she sends after your pitch ends indicates her answer",
                "'No' gestures: folded arms, tapping, hands over the mouth, eye squinting - don't end your pitch yet",
                "Once she verbally says no, it's tough to turn it around, so try a different tack first",
                "'Maybe' signals: taking a sip of a drink, cleaning her glasses, or stroking her chin",
                "Keep additional convincing points ready to capitalize on her indecision",
                "'Yes' cluster: a change in overall body language, smile, enhanced eye contact, and nodding",
                "Forward lean, direct body orientation, open palms, and straightened posture all say yes",
                "Pupil dilation, blushing, shallow breathing, and an eye twinkle confirm the sale",
                "Look for deviations from the norm - the transitions as people make up their minds",
                "Detect whether she's thinking 'No way do I want this' or 'Yes, but I want a better price'",
            ],
        ),
    },
    {
        "num": 9,
        "title": "Become a Master Communicator: The Reiman Rapport Method",
        "pages": "297-316",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Ten-Step Spotter",
            "Screen 15 clips of the same interaction and identify which of the ten Reiman Rapport Method steps each clip demonstrates - relaxed face, body symmetry, social smile, handshake, nod-mirror-lead, contained gestures, pitch variation, space respect, anchoring, or plan of action. Also flag the violations: clenched teeth, a snooty chin angle, gum-exposing smiles, gestures above the chin, and bubble-penetrating reaches.",
            "A ten-step ladder runs down the left edge of the screen; each correctly tagged clip lights a glowing rung, and violation clips shake the ladder red.",
            [
                "The Reiman Rapport Method is a ten-point system for congruent, welcoming body language in any situation",
                "Master each step for at least one week - ideally three - before adding the next",
                "Practice several times a day, at least three to five, to make the changes permanent habits",
                "A smooth forehead is one of the main ways your face tells others you are relaxed",
                "The relaxation mantra: 'Scalp, forehead, eyelids, cheeks, mouth, jaw'",
                "People avoid insecure people because mirror systems make their anxiety contagious",
                "The content of spoken words makes up less than 10 percent of the impact of your message",
                "Any two humans using these ten key signals are brought closer and kept 'in sync,' often for life",
                "Before a meeting, take a slow deep breath, release it fully, and relax your scalp down through your jaw",
                "Make sure your teeth aren't clenched and your chin and jaw are relaxed",
            ],
        ),
        "dialogue": (
            "Dialogue: The Rehearsed Interview",
            "Walk the group interview exactly as the Plan of Action prescribes: research names, pronunciations, and backgrounds first, script responses to anticipated questions, then role-play the entry - smile at the door, arms and legs in sync, weight equal on both legs, meet her eyes, say your name as you shake - and finish by buttoning your suit jacket and repeating each person's name at the good-byes.",
            "A split screen: the imagined interview plays on a mental projection screen at left while the physical rehearsal room at right lets you pick each move of the sequence.",
            [
                "A POA is a step-by-step recipe for a positive experience you want to happen in the future",
                "Research first: scope the entrance, call the switchboard for name pronunciations, Google each person's background",
                "Recite the full POA sequence out loud to yourself, picturing the events clearly in your mind",
                "Repeat the sequence four or five times a day during the week leading up to the event",
                "Repeated visualization tricks your brain into believing the event has already happened",
                "Nod two to three times at least every 30 to 45 seconds while the other person is talking",
                "Make it a personal rule to never interrupt - interruption says 'My thoughts are more important'",
                "Mirror with similar but not identical movements; picking up a fork mirrors a glass of water",
                "Mirror speech speed - a slow talker is thrown by a fast talker, and vice versa",
                "To test rapport, lead: make a different movement, like unfolding your arms; if they follow, you're in",
                "Even after hundreds of engagements, Reiman arrives an hour early and shouts 'Hello, everybody!' to own the room",
            ],
        ),
        "audit": (
            "Audit: The Mirror-Image Audit",
            "Audit a recorded handshake and two minutes of posture, gesture, and speech. Check the handshake rules - step in, lean slightly forward, right eye aligned, full palm, thumb straight up, elbow slightly bent, two to three seconds - then audit body symmetry (weight balanced, spine like a stack of dice, chin parallel to the floor, feet pointed at the person) and gesture discipline inside the hipline-to-chin box.",
            "A video desk with freeze-frame audit rings: a green ring clicks around each correct handshake element while a posture grid overlays the standing frame and a gesture-box wireframe tracks the hands.",
            [
                "Approach, lean slightly forward, look him in the eye, extend your right hand horizontally, and introduce yourself",
                "Always shake with the right hand, never the left - shift any carried items to your left hand",
                "Grip like holding hands: easy, comfortable pressure that suggests self-confidence and enthusiasm",
                "Align your right eye with his right eye; a thumb pointing straight up ensures a neutral handshake",
                "A slightly bent elbow means the right distance; shake the entire arm, not just the wrist or fingers",
                "Finish by opening your hand wide; the whole handshake should last no more than two to three seconds",
                "Extend your hand first to be unconsciously seen as the person in control - confident, warm, welcoming",
                "Balance your weight equally on both feet with arms at your sides; see the spine as a stack of dice",
                "Elongate the neck, drop the shoulders, draw in the belly button, keep the chin parallel to the floor",
                "Crossing your arms or legs throws off the symmetry and makes you appear closed off",
                "Feet pointed at the person signal powerful interest and make the other person feel heard and valued",
            ],
        ),
        "matrix": (
            "Matrix: Method Step x Situation x Function",
            "Build the master matrix: all 10 method steps against 6 situations - job interview, sales close, party entry, a parenting crisis, a bully boss, and a first date - and map what each step contributes in each context. Flag the advanced mirroring pair (breathing and blink matching) as expert-only, with blink matching marked as high-risk.",
            "A 10x6 matrix with step tiles that expand into function notes - 'ANCHOR: cements pride at the trophy moment' - while the two advanced-mirroring tiles glow purple with a MASTER-ONLY seal.",
            [
                "Mirror breathing: diagnose a chest breather versus a belly breather, then match the style to sync up",
                "Rapid breathing at the start of an encounter may be nerves - don't mirror that or he'll never calm down",
                "Mirror blinking: gauge his rate over the first minutes, then match it; he'll read it as his own state",
                "Blink matching is very difficult and can easily backfire - only attempt it as a true Master Communicator",
                "The personal bubble extends two to three feet away from your body",
                "Personal zones are larger in North America and Northern Europe than in countries farther south",
                "A 'mush' - a touchy-feely person - won't mind an arm touch; the people who mind will really mind",
                "Wait for the other person's signal - a touch on the arm, an approach - before entering the bubble",
                "Touch the forearm with pointer and middle finger to make a key point stick; withdraw within two or three seconds",
                "In a crisis with a child, drop the parent stance: crossed arms, leaning on one leg, the skeptical eyebrow",
                "Get down to your child's level, look them in the eye, and label the feeling - 'It looks like you're upset'",
                "Never say 'Stop crying' or 'That didn't hurt' - that's how we make kids into nonverbal idiots",
            ],
        ),
        "boss": (
            "Boss Battle: The Master Communicator Certification",
            "Run a full simulated first meeting as a timed certification exam: relax your face at the door, hold symmetric posture, flash your crafted social smile, deliver the perfect handshake, keep the nod-and-mirror rhythm, punctuate with contained gestures, vary your pitch, respect the bubble, then anchor her moment of joy with a well-timed forearm touch - and if she follows your lead, you pass. Violations - gestures above the chin, lingering touch, gum-showing smiles - cost points.",
            "A rehearsal stage with an examiner's panel; a ten-step progress rail fills as you execute each element while a violation buzzer flashes red at every miss.",
            [
                "Craft the social smile in the mirror like a resume: crinkle in the crow's-feet, slight cheek lift, no gums",
                "Smile with your eyes - they close slightly when you get it right - and diminish any nostril flaring",
                "People unconsciously return a smile, touching off a biochemical cascade of pleasurable feelings",
                "Keep hands open with palms exposed, inside an imaginary box from hipline to chin, shoulder to shoulder",
                "Gestures above the chin read as erratic and flamboyant; overgesticulators seem silly and scatterbrained",
                "Contained gestures that match your speech convey energy, original ideas, and fluent thinking",
                "The palm-down gesture says 'I'm the expert on this part'; flipping palms over hands the discussion to them",
                "Low pitch is universally preferred; high pitch signals anxiety because stress contracts the vocal cords",
                "The voice originates in the diaphragm: belly button expands on the inhale, contracts on the exhale",
                "An anchor links a strong emotion to a gesture, word, or sound - like the shower music in Psycho",
                "Touch the forearm or speak louder at the peak of her recollection - 'Wow, that's amazing!'",
                "Anchor pride with a hug, thumbs-up, or forehead kiss when your child wins a trophy",
            ],
        ),
    },
]
