# -*- coding: utf-8 -*-
"""Phase 2 chapter data for The Righteous Mind (Jonathan Haidt),
4 sections: chapters 9-12 of Part III (Morality Binds and Blinds):
Why Are We So Groupish?, The Hive Switch, Religion Is a Team Sport,
Can't We All Disagree More Constructively?.
Each chapter: num, title, pages, domain, and 5 slots (scrub/dialogue/audit/matrix/boss),
each slot a 4-tuple (topic, player_mission, visual_frame_description, key_concepts[10-12]).
"""

D = "Moral Psychology | Intuition vs Reason | Political Division"

CHAPTERS = [
    {
        "num": 9,
        "title": "Chapter 9: Why Are We So Groupish?",
        "pages": "189-220",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Multilevel Scanner",
            "Scan a gallery of evolutionary tableaux frozen at their decisive instant and judge which level of selection is doing the work in each: the deer fleeing the predator, the termite nest, the fox pup nuzzling its breeder, the hens stacked in their cages. Name every scene individual or group, flag the free riders who hang back to survive the fight, and stamp the verdict before the exhibit seals itself.",
            "A dim evidence chamber where each scene is nested inside the next like Russian dolls - genes within chromosomes within cells within organisms within hives - while a gauge labeled Selection Level swings between Individual and Group and a red lamp marks every lurking free rider.",
            [
                "Haidt felt a primitive urge to put an American flag decal on his car after the terrorist attacks of September 11, 2001, and resolved his dilemma by placing an American flag in one corner of his rear windshield and a United Nations flag in the opposite corner",
                "Selfishness means our minds contain mechanisms that promote our own interests in competition with our peers, while groupishness means mechanisms that promote our group's interests in competition with other groups",
                "Group selection was banished as a heresy from scientific circles in the 1970s, but Haidt argues it was falsely convicted and unfairly banished, and presents four exhibits in its defense",
                "In The Descent of Man, Darwin argued that a tribe rich in courageous, sympathetic, and faithful members would succeed and conquer other tribes, but he raised the free rider problem in the very next paragraph",
                "Multilevel selection treats life as a hierarchy of nested levels, like Russian dolls: genes within chromosomes within cells within individual organisms within hives, societies, and other groups",
                "The free rider problem says that within the bravest army, the few cowards who hang back are the most likely of all to survive the fight, go home alive, and become fathers",
                "Darwin's probable steps toward team playing were the social instincts, reciprocity, passionate concern with the praise and blame of our fellow-men, and the capacity to treat duties and principles as sacred",
                "Darwin summarized morality as a highly complex sentiment originating in the social instincts, largely guided by the approbation of our fellow-men, ruled by reason, self-interest, and in later times deep religious feelings, and confirmed by instruction and habit",
                "In Adaptation and Natural Selection (1966), George Williams argued that a fast herd of deer is nothing more than a herd of fast deer - the selection process operated on the level of individuals, not the herd",
                "Williams conceded that only by a theory of between-group selection could we achieve a scientific explanation of group-related adaptations",
                "By the late 1970s there was a strong consensus that anyone who said a behavior occurred for the good of the group was a fool who could be safely ignored",
                "Williams called morality an accidental capability produced, in its boundless stupidity, by a biological process normally opposed to its expression, while Haidt answers that human beings are the giraffes of altruism - one-of-a-kind freaks of nature occasionally as team-spirited as bees",
            ],
        ),
        "dialogue": (
            "Dialogue: The Retrial of Group Selection",
            "Take the stand at the retrial of group selection and play the witnesses in turn: Darwin, who described the tribe that conquers other tribes; George Williams, who set out to purge biology of Panglossian mushiness; Richard Dawkins, who taught generosity because we are born selfish; Michael Tomasello, who never saw two chimps carry a log; and Lesley Newson, who insisted that groups competed to turn resources into offspring rather than to make war. Question each about the free rider problem, then render your verdict on the banished heresy.",
            "A wood-paneled courtroom where an exhibit table holds the rowboat race of life: a lone rower, a two-person boat, a train of three boats crewed by identical septuplets, and a motorboat of twenty-four sisters, all frozen mid-stroke before the bench.",
            [
                "The boat race is a metaphorical history of life on Earth: a lone rower is passed by a boat with two rowers, then by a train of three rowboats tied together, then by an enterprising group of twenty-four sisters who rented a motorboat",
                "Around 2 billion years ago two bacteria somehow joined together inside a single membrane, which is why mitochondria have their own DNA, unrelated to the DNA in the nucleus",
                "The biologists John Maynard Smith and Eors Szathmary count just eight clear major transitions over the last 4 billion years, the last of which is human societies",
                "A superorganism is an organism made out of smaller organisms, and competition among superorganisms is one form of group selection",
                "More than 100 million years ago some wasps developed the trick of a queen who lays all the eggs plus workers who maintain the nest, a trick discovered independently by the ancestors of termites, naked mole rats, shrimp, aphids, beetles, and spiders",
                "The colonial insects represent just 2 percent of all insect species, yet they are now the majority, by weight, of all insects on Earth",
                "Bert Holldobler and E. O. Wilson find that the resource for nonhuman ultrasocials is invariably a nest plus dependable food within foraging range, and beehives have been described as a factory inside a fortress",
                "The three factors that pulled for human ultrasociality were territorial creatures fond of defensible nests, needy offspring requiring enormous care, and threat from neighboring groups - making humans the only ultrasocial primate",
                "Tomasello's sentence that it is inconceivable you would ever see two chimpanzees carrying a log together convinced Haidt that shared intentionality was the Rubicon crossing of moral evolution",
                "Across ten tasks, chimps and two-year-olds solved the physical problems equally well, about 68 percent of the time, but children aced the social challenges 74 percent of the time while chimps solved them just 35 percent of the time",
                "When everyone in a group shared a common understanding of how things were supposed to be done and felt a flash of negativity when anyone violated those expectations, the first moral matrix was born",
                "Tomasello notes that a word is not a relationship between a sound and an object but an agreement among people who share a joint representation of the things in their world and a set of conventions for communicating about them",
            ],
        ),
        "audit": (
            "Audit: The Four Exhibits Dossier",
            "File every piece of evidence into the four exhibits of Haidt's defense: Exhibit A, major transitions producing superorganisms; Exhibit B, shared intentionality generating moral matrices; Exhibit C, genes and cultures coevolving; and Exhibit D, evolution that can be fast. For each artifact - the hand axe, the lactase gene, the tamed fox, the healed chicken - record the selection level that produced it before the timeline closes.",
            "A clerk's office stacked with four brown dossier binders labeled A, B, C, and D; artifacts fly in to be filed while a timeline along the wall runs from the first bacteria to Facebook linking half a billion people, and an alarm box reads: In case of foreign attack, break glass and push button.",
            [
                "Acheulean hand axes are nearly identical everywhere, from Africa to Europe to Asia, for more than a million years, which suggests the knowledge of how to make them may have become innate rather than passed on culturally",
                "Homo heidelbergensis, the ancestor of Neanderthals as well as us, left the first clear evidence of hearths and of spears and is Haidt's best candidate for the Rubicon crosser",
                "Among the first cattle keepers of northern Europe and parts of Africa, any individual whose mutated genes delayed the shutdown of lactase production had an advantage, and groups with the new gene kept larger herds and found more ways to use milk, such as turning it into cheese",
                "Richerson and Boyd's tribal instincts hypothesis holds that gene-culture coevolution moved humanity from the small-group sociability of other primates to the tribal ultrasociality found today in all human societies",
                "Human beings take extraordinary, costly, and sometimes painful steps to make their bodies advertise group membership, from Amazonian tattoos and the male circumcision required of Jews to the tattoos and facial piercings of punks in the United Kingdom",
                "Early humans domesticated themselves by selecting friends and partners who could live within the tribe's moral matrix, and our brains, bodies, and behavior show domesticated signs: smaller teeth, smaller body, reduced aggression, and greater playfulness carried into adulthood",
                "Stephen Jay Gould asserted in a 2000 interview that natural selection has almost become irrelevant in human evolution and that there has been no biological change in humans in 40,000 or 50,000 years",
                "Dmitri Belyaev, demoted in 1948 for his belief in Mendelian genetics, bred foxes for tameness rather than pelt quality, and after nine generations novel traits began to appear - largely the ones that distinguish dogs from wolves",
                "William Muir used group selection on hens kept twelve to a cage: within three generations aggression levels plummeted, by the sixth generation the death rate fell from 67 percent to 8 percent, and eggs per hen jumped from 91 to 237",
                "Data from the Human Genome Project show that genetic evolution greatly accelerated during the last 50,000 years, the curve getting steeper after 20,000 years ago and reaching a crescendo during the Holocene era in Africa as well as Eurasia",
                "Genes for recent traits, such as those that changed the blood of Tibetans so they could live at high altitudes, have already been identified",
                "The climate in Africa fluctuated wildly between 70,000 and 140,000 years ago, and a catastrophic volcanic eruption from the Toba volcano in Indonesia occurred 74,000 years ago",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Chimp or Bee, Self or Team",
            "Sort a wall of behaviors and scenes into the two natures Haidt describes: the chimp-like pursuit of individual advantage and the bee-like promotion of the group. Weigh each case - the lone forager's fig, the warrior's self-sacrifice, the group-selected hen, the reputation hunter - and justify every call by naming the selection level that shaped it before the scenes multiply.",
            "A sorting chamber with twin scales, one stamped with a chimp and one with a bee; between them a glowing banner reads 'We are 90 percent chimp and 10 percent bee,' and each sorted card drops onto its level of the hierarchy of life.",
            [
                "Haidt's thought experiment asks: if 95 percent of the food on Earth disappeared tonight, would the survivors be the biggest, strongest, and most violent individuals, or the people who manage to work together to monopolize, hide, and share the remaining food?",
                "Lesley Newson warned that groups were not necessarily at war: they competed to be the most efficient at turning resources into offspring, and women and children were very important members of these groups",
                "Group selection pulls for cooperation and for the ability to suppress antisocial behavior, but groupishness is generally focused on improving the welfare of the in-group, not on harming an out-group",
                "Darwin wrote that selfish and contentious people will not cohere, and without coherence nothing can be effected",
                "In a real army that sacralizes honor, loyalty, and country, the coward is not the most likely to make it home and father children - he risks being beaten up, left behind, or shot in the back for committing sacrilege, and his reputation will repel women and employers",
                "The term me decade was first applied to the growing individualism of American society, and it described broad changes in the social sciences, where the idea of people as Homo economicus spread far and wide",
                "Equity theory, the leading explanation of fairness in social psychology, rested on the first axiom that individuals will try to maximize their outcomes",
                "Dawkins wrote, let us try to teach generosity and altruism because we are born selfish",
                "People who devote their lives to helping strangers are so rare that we send film crews out to record them for the evening news, yet human ability to work together, divide labor, and function as a team is so all-pervasive we do not even notice it",
                "The 9/11 attacks turned Haidt into a team player and produced what he calls the rally-round-the-flag reflex, exactly the sort of groupish mechanism you would expect if humans were shaped by group selection as Darwin described",
                "By Williams's own criterion, if people in every society readily organize themselves into cooperative groups with a clear division of labor, then this ability is an excellent candidate for being a group-related adaptation",
                "Most of human nature was shaped by natural selection operating at the level of the individual, but not all of it - the groupish overlay makes up a crucial part of our righteous minds",
            ],
        ),
        "boss": (
            "Boss Battle: The Final Verdict on the Tribe",
            "Stand before the tribunal that banished group selection in the 1970s and deliver the closing argument: walk the bench through all four exhibits, from the bacterial merger and the hymenopteran revolution to the moral matrix born of shared intentionality, the lactase gene, the tamed foxes, and the hens' falling death rate. Convince the court that the wholesale dismissal was premature before the gavel falls on human groupishness itself.",
            "A vaulted hall where Darwin's two warring tribes flicker on a screen above the bench; as each exhibit is entered, the chamber fills with the symbols of the transition - the beehive, the hand axe, the hearth, the city-state raising walls and armies.",
            [
                "Exhibit A: major transitions produce superorganisms - when the free rider problem is muted at one level of the biological hierarchy, large and cohesive units become the vehicle for selection at the next level up",
                "Exhibit B: shared intentionality generates moral matrices - the Rubicon crossing was the uniquely human ability to share intentions and other mental representations, the beginning of the moral matrices that govern our social lives today",
                "Exhibit C: genes and cultures coevolve - once our ancestors crossed the Rubicon, evolution became a two-stranded affair, giving us tribal instincts to mark group membership and cooperate preferentially with group members",
                "Exhibit D: evolution can be fast - gene-culture coevolution reached a fever pitch during the last 12,000 years, so we cannot assume that modern-day hunter-gatherers represent universal human nature locked into place 50,000 years ago",
                "Even if group selection played no role in the evolution of any other mammal, human evolution has been so different since shared intentionality and gene-culture coevolution that humans may well be a special case",
                "Bees, ants, and termites are the ultimate team players - one for all, all for one - because in their hives competition within the group has been nearly eliminated and almost all selection is group selection",
                "Natural selection favored increasing levels of Tomasello's group-mindedness: the ability to learn and conform to social norms, feel and share group-related emotions, and create and obey social institutions, including religion",
                "Humans construct moral communities out of shared norms, institutions, and gods that they fight, kill, and die to defend, just as bees construct hives out of wax and wood fibers",
                "Shared intentionality allowed humans to construct nests that were vast and ornate yet weightless and portable",
                "The coevolution of tribal minds and tribal cultures prepared us not just for war but for far more peaceful coexistence within our groups and, in modern times, for cooperation on a vast scale",
                "Haidt concludes that we have a dual nature - selfish primates who long to be a part of something larger and nobler than ourselves: we are 90 percent chimp and 10 percent bee",
                "The wholesale dismissal of group selection in the 1960s and 1970s, based mostly on arguments and examples from other species, was premature",
            ],
        ),
    },
    {
        "num": 10,
        "title": "Chapter 10: The Hive Switch",
        "pages": "221-245",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Switch Flipper",
            "Scan a montage of collective scenes frozen mid-transition - the drill field at morning march, the fire-lit dance, the rave's strobed crowd, the stadium swaying in unison - and judge each one: has the hive switch been flipped, and is this muscular bonding, collective effervescence, or awe? Ring the instant the self shuts down and the gauge hits 'simply a part of a whole.'",
            "A diagnostic arch over a darkened hall where every scene glows with a slider labeled Hive Switch; when the crowd moves as one, a golden current - a sort of electricity generated from their closeness - arcs between the figures.",
            [
                "William McNeill, drafted into the U.S. Army in September 1941, found that prolonged movement in unison during drilling produced a strange sense of personal enlargement, a sort of swelling out, becoming bigger than life",
                "McNeill hypothesized that muscular bonding - moving together in time - evolved long before the beginning of recorded history for shutting down the self and creating a temporary superorganism",
                "McNeill concluded that the key innovation of Greek, Roman, and later European armies was synchronous drilling and marching, and the Macedonian phalanx was the superorganism Alexander the Great used to defeat much larger armies",
                "McNeill studied accounts of men in battle and found that men risk their lives not so much for their country or their ideals as for their comrades-in-arms",
                "One veteran quoted by McNeill said that when their 'I' passes insensibly into a 'we,' self-sacrifice becomes easy, for 'I may fall, but I do not die, for that which is real in me goes forward and lives on in the comrades for whom I gave up my life'",
                "The hive hypothesis states that human beings are conditional hive creatures who have the ability, under special conditions, to transcend self-interest and lose themselves temporarily and ecstatically in something larger than themselves",
                "The hive switch is a group-related adaptation that can only be explained by a theory of between-group selection, as Williams said - it is an adaptation for making groups more cohesive",
                "Barbara Ehrenreich's Dancing in the Streets argues that collective and ecstatic dancing is a nearly universal biotechnology for binding groups together and a form of muscular bonding that fosters love, trust, and equality",
                "Early Christianity was a danced religion until dancing in church was suppressed in the Middle Ages, and Ehrenreich traces Europe's abandonment of ecstatic dancing to the rise of individualism beginning in the sixteenth century",
                "Ehrenreich noted that if homosexual attraction is the love that dares not speak its name, the love that binds people to the collective has no name at all to speak",
                "Durkheim insisted there were social facts - such as the suicide rate or norms about patriotism - that are not reducible to facts about individuals, and he described Homo sapiens as Homo duplex, existing as an individual and as part of the larger society",
                "Durkheim's second set of social sentiments makes the person 'simply a part of a whole, whose actions I follow, and whose influence I am subject to'",
            ],
        ),
        "dialogue": (
            "Dialogue: The Effervescence Witness Stand",
            "Interview the witnesses who crossed into the sacred realm and described it: Ralph Waldo Emerson on the bare ground, Darwin in the Brazilian forest, the Boston divinity student caught up in the vastness of Creation, and Tony Hsieh surrendering his 'I' on the rave floor. Then take the stand yourself and testify whether awe, drugs, or drumbeats flipped your switch - or whether you only ever saw the profane world.",
            "A dim witness room where each speaker's face floats above a scene: a transparent eye-ball dissolving into the sky, a forest of grandeur, a blinding altar light, and a crowd of thousands facing an elevated DJ while wordless electronic beats pulse beneath them all.",
            [
                "Emerson's Transcendentalism rejected the analytic hyperintellectualism of America's top universities and argued that the deepest truths must be known by intuition, not reason",
                "Emerson described standing on the bare ground, head bathed by the blithe air: 'I become a transparent eye-ball; I am nothing; I see all; the currents of the Universal Being circulate through me; I am part or particle of God'",
                "Darwin recorded in his journal that standing in the midst of the grandeur of a Brazilian forest, it was not possible to give an adequate idea of the higher feelings of wonder, admiration, and devotion which fill and elevate the mind",
                "The emotion of awe is most often triggered by situations with two features: vastness, which overwhelms us and makes us feel small, and a need for accommodation, when the experience cannot be assimilated into our existing mental structures",
                "Awe acts like a kind of reset button - it makes people forget themselves and their petty concerns and opens them to new possibilities, values, and directions in life",
                "When Cortes captured Mexico in 1519 he found the Aztecs using mushrooms containing psilocybin called teonanacatl, literally 'God's flesh,' which took people directly from the profane to the sacred realm in about thirty minutes",
                "Religious practices north of the Aztecs focused on peyote, a cactus containing mescaline, while practices to the south used ayahuasca, a brew of vines and leaves containing DMT - drugs that could just as well be called Durkheimogens",
                "Traditional rites for transforming boys into men and girls into women involve fear, pain, symbolism of death and rebirth, and many societies used hallucinogenic drugs to catalyze the transformation of the selfish child into a morally responsible adult",
                "In a controlled experiment in the basement chapel of a Boston church, twenty divinity students took either psilocybin or niacin, and within forty minutes it was clear to all who had taken which",
                "The psilocybin subjects reported statistically significant effects on nine kinds of experiences, including unity with a loss of sense of self, transcendence of time and space, sacredness, and persisting positive changes in attitude and behavior",
                "Twenty-five years later Rick Doblin tracked down nineteen of the twenty original subjects and concluded that the psilocybin experiences were among the most meaningful of their lives",
                "Tony Hsieh of Zappos.com described the rave as one massive, united tribe of thousands with the DJ as tribal leader, where the steady wordless electronic beats were the unifying heartbeats that synchronized the crowd and individual consciousness was replaced by a single unifying group consciousness",
            ],
        ),
        "audit": (
            "Audit: The Neurochemistry Ledger",
            "Audit the biology of the hive switch and file each finding under its building material: oxytocin, the glue of within-group bonding, and the mirror neuron system, the machinery of shared feeling. For every entry, record whether it bonds us to our group or to humanity in general, and flag any study that shows parochial altruism rather than universal love.",
            "A laboratory ledger with two columns, Oxytocin and Mirror Neurons; beside them a warning gauge labeled Parochial Altruism ticks upward with every entry while a banner asks whether putting oxytocin into the world's drinking water would end war and cruelty - and answers: unfortunately, no.",
            [
                "Oxytocin is a hormone and neurotransmitter produced by the hypothalamus that causes uterine contractions and milk letdown, and evolution has often reused it to forge other kinds of bonds, such as between mates and between parents and offspring",
                "The press has dubbed oxytocin the love drug and the cuddle hormone because your brain secretes more of it with intimate contact, even if that contact is just a back rub from a stranger",
                "If the hive switch is a product of group selection, it should show the signature feature of group selection: parochial altruism - bonding us to our partners and groups, not to humanity in general",
                "In studies of Dutch men playing economic games in cubicles, those given a nasal spray of oxytocin made less selfish decisions and cared more about helping their group but showed no concern at all for improving the outcomes of men in the other groups",
                "In one of the Dutch studies, oxytocin made men more willing to hurt other teams in a prisoner's dilemma game because doing so was the best way to protect their own group",
                "In follow-up studies, oxytocin caused Dutch men to like Dutch names more and to value saving Dutch lives more in trolley-type dilemmas, yet researchers failed to find increased out-group hate toward Muslims",
                "Mirror neurons were discovered accidentally in the 1980s when Italian scientists inserting electrodes into the brains of Macaque monkeys heard firing noises at odd times - such as when a still monkey watched the researcher pick something up with his thumb and forefinger",
                "Most mirror neurons fire not when they see a specific physical movement but when they see an action indicating a more general goal or intention - watching a hand lift a cup from a clean table triggers an eating neuron, while the same movement from a messy table triggers a different one",
                "Just seeing someone else smile activates some of the same neurons as when you smile, so the other person is effectively smiling in your brain, which makes you happy and likely to smile back",
                "In Tania Singer's study, subjects' brains responded the same way when a nice player received an electric shock as when they themselves were shocked, but when the selfish player was shocked people showed less empathy and some even showed neural evidence of pleasure",
                "We are conditional hive creatures: we are more likely to mirror and empathize with others when they have conformed to our moral matrix than when they have violated it",
                "Mirror neurons send signals from motor areas first to the insular cortex and from there to the amygdala and other limbic areas, letting people feel each other's pain and joy to a much greater degree than any other primates",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: The Glauconian or the Hivish Firm",
            "Sort each organizational practice into the nature it appeals to: the transactional firm staffed by Homo economicus and monitored with carrots and sticks, versus the hivish organization that builds similarity, synchrony, and team competition. Justify every placement with the research - the bonus pool that destroys morale, the Toyota morning exercises, the All Blacks Haka - before the org chart multiplies.",
            "A corporate boardroom split down the middle: on one side a flowchart of incentives under surveillance cameras, on the other a floor of employees exercising in synchrony; a single clapping hand hovers above both, captioned: leadership is the complement of followership.",
            [
                "The word corporation comes from corpus, Latin for body, and legally a corporation is a collection of many individuals united into one body, having perpetual succession under an artificial form and the capacity of acting, in several respects, as an individual",
                "The corporate legal fiction let people place themselves in a new kind of boat within which they could divide labor, suppress free riding, and take on gigantic tasks, and corporate law helped England pull ahead in the early days of the industrial revolution",
                "It is possible to build a corporation staffed entirely by Homo economicus, but this approach, sometimes called transactional leadership, has its limits because self-interested employees are Glauconians, far more interested in looking good and getting promoted than in helping the company",
                "Hivish employees work harder, have more fun, and are less likely to quit or to sue the company, unlike Homo economicus, who is no team player",
                "Robert Hogan, Robert Kaiser, and Mark van Vugt argue that leadership can only be understood as the complement of followership - focusing on leadership alone is like trying to understand clapping by studying only the left hand",
                "People evolved to live in groups of up to 150 that were relatively egalitarian and wary of alpha males, yet we also evolved to rally around leaders when our group is under threat or competing with other groups",
                "Research shows that strangers will spontaneously organize themselves into leaders and followers when natural disasters strike",
                "A leader must construct a moral matrix based on the Authority foundation, the Liberty foundation, and above all the Loyalty foundation, without activating followers' hypersensitive oppression detectors",
                "To make a human hive, increase similarity, not diversity: people are warmer and more trusting toward those who look like them, dress like them, or even just share their first name or birthday, and there is nothing special about race",
                "Synchrony builds trust - Japanese corporations such as Toyota begin their days with synchronous companywide exercises, groups prepare for battle with chants and ritualized movements, and if you want an impressive rugby example, Google 'All Blacks Haka'",
                "Studies show that intergroup competition increases love of the in-group far more than it increases dislike of the out-group, while pitting individuals against each other for scarce bonuses destroys hivishness, trust, and morale",
                "Kaiser and Hogan summarize the literature: transactional leadership appeals to followers' self-interest, but transformational leadership changes the way followers see themselves - from isolated individuals to members of a larger group - by modeling collective commitment through self-sacrifice and the use of 'we' rather than 'I'",
            ],
        ),
        "boss": (
            "Boss Battle: The Fascism Line and the Hivish Nation",
            "Face the charge that hiving is fascism: hold the two texts in your hands - Kennedy's inaugural address and Mussolini's Doctrine of Fascism - and tell the court where the line falls between the festival that mocks its leaders and the spectacle that worships them. Then govern the thought experiment of two nations, one full of cross-cutting hives and one devoid of them, and argue why the hivish nation is not a promising target for a demagogue.",
            "A grand hall where one banner reads 'Ask not what your country can do for you' and a second, in heavy black type, preaches renunciation of self-interest for a purely spiritual existence; below, two glass nations stand side by side, one swarming with little glowing hives and one flat and dark.",
            [
                "For Americans born before 1950, the words 'Ask not' activate their Durkheimian higher nature through John F. Kennedy's 1961 inaugural address, which called on Americans to bear the burden of a long twilight struggle against the Soviet Union",
                "Mussolini's The Doctrine of Fascism rejects man as a self-centered individual and builds a higher life founded on duty in which the individual, by self-sacrifice and the renunciation of self-interest, achieves a purely spiritual existence - fascism is hive psychology scaled up to grotesque heights",
                "Ehrenreich refutes the fascism charge by noting that ecstatic dancing, festivals, and carnivals invariably erase or invert the hierarchies of everyday life: men dress as women, peasants pretend to be nobles, and leaders can be safely mocked",
                "Fascist rallies were spectacles, not festivals: people stood around passively for hours, applauding soldiers and cheering the leader, and the rallies used awe to strengthen hierarchy and bond people to the godlike figure of the leader",
                "Hiving comes naturally, easily, and joyfully to us, and its normal function is to bond dozens or at most hundreds of people into communities of trust, cooperation, and even love",
                "Creating a nation of multiple competing groups and parties was seen by America's founding fathers as a way of preventing tyranny",
                "Robert Putnam's research on social capital shows that bowling leagues, churches, and other kinds of groups, teams, and clubs are crucial for the health of individuals and of a nation",
                "Haidt changed his mind since The Happiness Hypothesis: happiness comes from between - from getting the right relationships between yourself and others, yourself and your work, and yourself and something larger than yourself",
                "The hive switch is another way of stating Durkheim's idea that we are Homo duplex: we live most of our lives in the ordinary profane world but achieve our greatest joys in brief moments of transit to the sacred world, in which we become simply a part of a whole",
                "The hive switch is made of oxytocin, which bonds people to their groups rather than to all of humanity, and mirror neurons, which help people empathize particularly with those who share their moral matrix",
                "When a single hive is scaled up to the size of a nation and led by a dictator with an army at his disposal, the results are invariably disastrous - but that is no argument for removing or suppressing hives at lower levels",
                "Parochial love - love within groups, amplified by similarity, a sense of shared fate, and the suppression of free riders - may be the most we can accomplish",
            ],
        ),
    },
    {
        "num": 11,
        "title": "Chapter 11: Religion Is a Team Sport",
        "pages": "246-273",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Sacred Things Scanner",
            "Scan the game-day rituals at UVA and detect the sacred machinery inside each gesture: the neckties and pearls, the painted Cavaliers logo, the locked arms swaying to 'Wah-hoo-wah,' the fist-pumping battle chant. Judge each behavior against Durkheim's definition of religion and stamp which ones create a community before the scanner seals the frame.",
            "A stadium transformed into a scanner bay where 50,000 fans glow in a single field; as arms lock and sway, the overlay traces the century-old song and labels each chant 'muscular bonding warming up for coordinated military action.'",
            [
                "Every Saturday in the fall, millions of people pack themselves into stadiums at colleges across the United States to participate in a ritual that can only be described as tribal",
                "At UVA the ritual begins with costumes: men wear dress shirts with UVA neckties, women wear skirts or dresses sometimes with pearl necklaces, and some students paint the logo of the Cavaliers - a V crossed by two swords - on their faces",
                "The students sing the same song UVA students have sung together for over a century, to the tune of 'Auld Lang Syne,' beginning 'That good old song of Wah-hoo-wah'",
                "After locking arms and swaying as a single mass, the students illustrate McNeill's thesis that muscular bonding warms people up for coordinated military action, with aggressive fist-pumping in sync with a nonsensical battle chant",
                "Collective effervescence is guaranteed at the game, along with collective outrage at questionable calls by the referees, collective triumph if the team wins, and collective grief if the team loses",
                "From a Durkheimian perspective the function of the cheering and chanting is not victory but the creation of a community - a college football game is a superb analogy for religion",
                "From a naive perspective college football is an extravagant, costly, wasteful institution that impairs rational thinking, but from a sociologically informed perspective it pulls people up from the profane level to the sacred level and flips the hive switch",
                "The school spirit it augments attracts better students and more alumni donations, which improves the experience for the entire community, including professors with no interest in sports",
                "Durkheim defined a religion as a unified system of beliefs and practices relative to sacred things, things set apart and forbidden, which unite into one single moral community called a Church all those who adhere to them",
                "Religion cannot be studied in lone individuals any more than hivishness can be studied in lone bees - religions are social facts",
                "Many scientists misunderstand religion because they examine only what is most visible - individuals and their supernatural beliefs - and conclude it is an extravagant, costly, wasteful institution that leaves a long trail of victims",
                "The third principle of moral psychology, that morality binds and blinds, must be honored before rendering a fair judgment about religion and its relationship to morality and politics",
            ],
        ),
        "dialogue": (
            "Dialogue: The Four Horsemen Debate",
            "Take the interviewer's seat at a debate among the three men of science - Harris, Dawkins, and Dennett - and the Durkheimian challenger. Ask each what religion is: a set of beliefs that cause harmful deeds, or believing, doing, and belonging woven into a community? Then switch seats and answer as a believer whose gods bind a village together, and defend the model that the beliefs exist to serve.",
            "A panel room where three books float above the table - The End of Faith, The God Delusion, Breaking the Spell - while behind them a football arcs across a stadium, and a caption reads: understanding religion by studying beliefs about God is like understanding football by studying the movements of the ball.",
            [
                "Between 2004 and 2007 so many books attacking religion were published that a movement was born: the New Atheism, whose four authors are known as the four horsemen",
                "The titles were combative: Sam Harris's The End of Faith, Richard Dawkins's The God Delusion, Daniel Dennett's Breaking the Spell, and Christopher Hitchens's God Is Not Great: How Religion Poisons Everything",
                "Haidt sets Hitchens aside because his book made no pretense to be anything other than a polemical diatribe, while Harris was a graduate student in neuroscience, Dawkins is a biologist, and Dennett is a philosopher",
                "For Harris, beliefs are the key to the psychology of religion because believing a falsehood - such as martyrs being rewarded with seventy-two virgins in heaven - makes religious people do harmful things such as suicide bombing",
                "Dawkins defines the God Hypothesis as the proposition that there exists a superhuman, supernatural intelligence who deliberately designed and created the universe and everything in it, including us",
                "Dawkins argues that God, in the sense defined, is a delusion - and, as later chapters will show, a pernicious delusion",
                "Trying to understand the persistence and passion of religion by studying beliefs about God is like trying to understand the persistence and passion of college football by studying the movements of the ball",
                "Believing, doing, and belonging are three complementary yet distinct aspects of religiosity according to many scholars, and looking at all three at once gives a view very different from the New Atheists'",
                "The Durkheimian model holds that the function of those beliefs and practices is ultimately to create a community, and that our beliefs are often post hoc constructions designed to justify what we've just done or support the groups we belong to",
                "The New Atheist model is based on the Platonic rationalist view that reason is the charioteer guiding the passions, the view Haidt rejected in favor of the Humean account in which reason, the rider, is a servant of the intuitions, the elephant",
                "To understand the psychology of religion, the question is whether to focus on the false beliefs and faulty reasoning of individual believers or on the automatic intuitive processes of people embedded in social groups striving to create a moral community",
                "Supernatural agents play a central role in religion, just as the actual football is at the center of the whirl of activity on game day at UVA, but you've got to broaden the inquiry to the ways beliefs work with practices to create a religious community",
            ],
        ),
        "audit": (
            "Audit: The By-Product Debrief",
            "Work the audit trail of the New Atheist story and file each mechanism under its misfire: the hypersensitive agency detector that sees agents in the wind, the gullible learning module that believes whatever grown-ups say, the love circuitry commandeered for God, and the dualist mind that parks immortal souls in temporary bodies. Then close the file on the parasites - the ant at the blade of grass, the virus that makes you sneeze.",
            "A pathology lab where slides of mental machinery are projected, each misfiring into a god-shaped glow; on one bench a parasite-controlled ant climbs a blade of grass while the caption reads 'suicide for the ant, adaptive for the parasite.'",
            [
                "To an evolutionist, religious behaviors stand out like peacocks in a sunlit glade, as Dennett put it, because evolution ruthlessly eliminates costly and wasteful behaviors from an animal's repertoire",
                "Dawkins notes that no known culture lacks some version of the time-consuming, wealth-consuming, hostility-provoking rituals, the anti-factual, counterproductive fantasies of religion",
                "The first step of the New Atheist story - one Haidt does not challenge - is the hypersensitive agency detection device, which makes almost all of its mistakes in one direction: false positives rather than false negatives",
                "Just as we see faces in the clouds but never clouds in faces, the face detector is on a hair trigger, and similarly the agency detector makes thunder and lightning seem as though somebody up in the sky is angry at us",
                "The bridge of the nose is a mundane by-product example: it evolved for other reasons, but we humans reuse it for the entirely new purpose of holding up eyeglasses",
                "Dawkins proposes a gullible learning module: there will be a selective advantage to child brains that possess the rule of thumb to believe, without question, whatever your grown-ups tell you",
                "Dennett suggests that the circuitry for falling in love has been commandeered by some religions to make people fall in love with God",
                "Paul Bloom has shown that our minds were designed for dualism - we think minds and bodies are different but equally real sorts of things - and so we readily believe we have immortal souls housed in our temporary bodies",
                "Dennett opens Breaking the Spell with a tiny parasite that commandeers the brains of ants, making them climb to the tops of blades of grass where grazing animals can eat them - suicide for the ant but adaptive for the parasite",
                "Dawkins describes religions as viruses that spread from host to host, and both he and Dennett treat religions as sets of memes that have undergone Darwinian selection for their own ability to survive and reproduce",
                "Dennett describes the nymphs, fairies, goblins, and demons of mythology as the imaginative offspring of a hyperactive habit of finding agency, with only the souped-up winners of billions of competitions for rehearsal time surviving to be shared",
                "If religion is a virus or parasite that exploits a set of cognitive by-products for its benefit, then scientists, humanists, and the few who have escaped infection must work together to break the spell, lift the delusion, and bring about the end of faith",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: The Sacrifice and Sanctity Sorter",
            "Sort a stream of evidence into the two evolutionary stories: the New Atheists' parasitic memes and Atran and Henrich's cultural group selection. Weigh each artifact - the cheating lab lit dimly, the image of the eye, the jealous gods, the communes' costly sacrifices - and decide what actually binds groups together before the ledger closes.",
            "A sorting machine fed by two columns, Memes and Moralistic Gods; each god arrives thundering against adultery and oath-breaking, while a balance scale weighs costly sacrifices against commune longevity and a graph rises perfectly linearly for the religious communes.",
            [
                "Atran and Henrich tell a two-step story: diverse cognitive modules evolved as adaptations but misfired, producing supernatural beliefs as by-products, followed by cultural evolution in which religions spread to the extent that they make groups more cohesive and cooperative",
                "The gods of hunter-gatherers are often capricious and malevolent, but as groups take up agriculture and grow larger, their gods become far more moralistic, concerned about actions that foment conflict and division such as murder, adultery, false witness, and the breaking of oaths",
                "People cheat more on a test when the lights are dimmed, but they cheat less when a cartoonlike image of an eye is nearby or when the concept of God is activated in memory by unscrambling sentences containing God-related words",
                "Gods who administer collective punishment - bringing drought or pestilence on the whole village for the adultery of two people - make shame more effective as a means of social control and keep villagers gossipy about extramarital liaisons",
                "Richard Sosis compared nineteenth-century communes and found that just 6 percent of secular communes were still functioning twenty years after their founding, compared to 39 percent of the religious communes",
                "The master variable explaining commune longevity was the number of costly sacrifices each commune demanded: giving up alcohol and tobacco, fasting for days at a time, conforming to a dress code or hairstyle, or cutting ties with outsiders",
                "For religious communes the effect was perfectly linear - the more sacrifice a commune demanded, the longer it lasted - but demands for sacrifice did not help secular communes, most of which failed within eight years",
                "Sosis quotes Roy Rappaport: to invest social conventions with sanctity is to hide their arbitrariness in a cloak of seeming necessity",
                "When secular organizations demand sacrifice, every member has a right to ask for a cost-benefit analysis, and many refuse to do things that don't make logical sense",
                "Religions can spread far faster than genes, as in the case of Islam in the seventh and eighth centuries or Mormonism in the nineteenth century, and a successful religion can be adopted by neighboring or vanquished populations",
                "Atran and Henrich argue that moralistic high gods are just too recent to have driven genetic evolution for religiosity, having emerged along with agriculture in the last 10,000 years",
                "Haidt finds it hard to imagine that the genes stood still for more than 50,000 years in the swirling waltz of gene-culture coevolution while the cultural partner began dancing to religious music",
            ],
        ),
        "boss": (
            "Boss Battle: The Water Temple Summit",
            "Take command of Wilson's case: walk the river from the Balinese volcano's Goddess of the Waters down through the subaks and the temple at every fork, and keep the rice flowing without central government, inspectors, or courts. Then rule on the two great questions - do the gods make people good, and can those who forsake the moral exoskeleton escape anomie? - before the maypole weaves its final ribbon.",
            "A mountainside of terraced pools under the immense temple of the Goddess of the Waters, where twenty-four priests file past and a high priest speaks for the goddess; below, a maypole's ribbons weave a tubular cloth while a banner reads 'Religions exist primarily for people to achieve together what they cannot achieve on their own.'",
            [
                "David Sloan Wilson of Binghamton University watched group selection convicted in the 1970s, spent thirty years trying to prove it innocent, and merged the ideas of Darwin and Durkheim in Darwin's Cathedral",
                "Wilson shows how John Calvin developed a strict and demanding form of Christianity in sixteenth-century Geneva that suppressed free riding and facilitated trust and commerce, and how medieval Judaism created cultural fortresses that kept outsiders out and insiders in",
                "On Bali, hundreds of terraced pools are irrigated by aqueducts and tunnels, some running underground for more than a kilometer, overseen by an immense temple to the Goddess of the Waters staffed by twenty-four full-time priests selected in childhood",
                "The lowest level of Balinese organization was the subak, a group of several extended families that made decisions democratically, and a small temple was placed at every fork in the irrigation system to unite all the subaks downstream of it",
                "The temple system minimized the cheating that would flourish in a zero-sum division of water and let thousands of farmers cooperate without central government, inspectors, and courts - so efficiently that the Dutch, expert hydrologists, could find little to improve",
                "In the maypole dance, men and women circle the pole in opposite directions weaving their ribbons into a tubular cloth, symbolically enacting the central miracle of social life: e pluribus unum",
                "The !Kung believe in an omnipotent sky god named //Gauwa and spirits of the dead called //gauwasi who offer no moral guidance but simply cause things to happen - perfect examples of the hypersensitive agency detector in action",
                "Lorna Marshall describes the !Kung healing dances as people binding together to become a unit, singing, clapping, and stamping in an extraordinary unison, with no words dividing them",
                "Nicholas Wade's The Faith Instinct endorses Wilson's theory: people belonging to a religiously cohesive society are more likely to survive and reproduce than those in less cohesive groups, who may be vanquished by their enemies",
                "Gods and religions, in sum, are group-level adaptations for producing cohesiveness and trust, created by the members of the group and then organizing the activity of the group",
                "In the United States, the least religious fifth of the population gives just 1.5 percent of its money to charity, while the most religious fifth - measured by church attendance, not belief - gives 7 percent, mostly to religious organizations",
                "In a German trust game, trusters who learned a trustee was religious transferred more money, and the religious trustees really did transfer back more than the nonreligious trustees - the highest wealth was created when religious people played with other religious people",
            ],
        ),
    },
    {
        "num": 12,
        "title": "Chapter 12: Can't We All Disagree More Constructively?",
        "pages": "274-303",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The First Draft Scanner",
            "Scan the developmental timeline of a life and detect the settings written into the first draft of the brain: threat sensitivity, novelty-seeking, openness to experience. Judge whether each scene - the nursery school report, the strict school, the blast of white noise - pushes a child toward the left or right team, and stamp the heritability verdict before the case file seals itself.",
            "A scanning arch over a crib and then a nursery where teachers rate children curious, verbal, and self-reliant or obedient and neat; a gauge labeled Threat Sensitivity spikes with a sudden blast of white noise while twin strands of DNA glow in the corner.",
            [
                "Haidt defines ideology simply as a set of beliefs about the proper order of society and how it can be achieved",
                "At the French Assembly of 1789, delegates who favored preservation sat on the right side of the chamber while those who favored change sat on the left, and the terms right and left have stood for conservatism and liberalism ever since",
                "Political theorists since Marx assumed people chose ideologies to further their self-interest, but when political scientists looked into it they found that self-interest does a remarkably poor job of predicting political attitudes",
                "Studies of twins in the 1980s showed that identical twins are more similar than fraternal twins on just about everything, and identical twins reared in separate households usually turn out very similar",
                "Genetics explains between a third and a half of the variability among people on their political attitudes, while being raised in a liberal or conservative household accounts for much less",
                "Innate does not mean unmalleable; it means organized in advance of experience, with the genes guiding the construction of the brain in the uterus as a first draft that gets revised by childhood experiences",
                "Genes related to glutamate and serotonin, both involved in the brain's response to threat and fear, fit findings that conservatives react more strongly to signs of danger, including germs, contamination, and sudden blasts of white noise",
                "Genes related to receptors for the neurotransmitter dopamine, tied to sensation-seeking and openness to experience, correlate with liberalism, echoing Montaigne's line that the only things he finds rewarding are variety and the enjoyment of diversity",
                "John Jost's major review found that nearly all the traits distinguishing liberals and conservatives are conceptually related to threat sensitivity - conservatives react more strongly to reminders of death - or to openness to experience",
                "Even though the effects of any single gene are tiny, the genes collectively give some people brains more reactive to threats and less pleased by novelty, and these are the two main personality factors that distinguish the sides",
                "Women who called themselves liberals as adults had been rated by their nursery school teachers as more curious, verbal, and self-reliant, but also more assertive and aggressive, less obedient and neat",
                "Genes contribute to just about every aspect of our personalities: how much you like jazz, spicy foods, and abstract art, your likelihood of divorce, your degree of religiosity, and your political orientation as an adult",
            ],
        ),
        "dialogue": (
            "Dialogue: The Holiday Table Reunion",
            "Play both fraternal twins at the family table they have agreed not to talk politics over: the sister who majors in Latin American studies in New York and advocates for children of illegal immigrants, and the brother who stays close to home, works at the local bank, and hears 'Country First.' Then take the confession of Keith Richards - dumped from his school choir, made to repeat a year, his slow-burning fuse lit - and decide how much of each life was written in advance.",
            "A holiday table divided down the middle: on one side a wall of books about oppression and a poster of Obama's 2008 promise of change; on the other a bank ledger, a church pew, and a campaign button reading 'Country First'; at the head of the table an electric guitar stands unplayed.",
            [
                "The sister's genes gave her a brain lower than average in threat sensitivity and higher in pleasure at novel experiences, and in 2008 she is electrified by Barack Obama's concern for the poor and his promise of change",
                "The brother, with the opposite settings, chooses to stay close to family and friends, attends the local branch of the state university, earns a business degree, works for a local bank, and becomes a pillar of his church and community",
                "The moral matrices surrounding the brother are based on all six foundations, with the most common themes being personal responsibility - based on the Fairness foundation, not being a free rider or a burden on others - and loyalty to the many teams he belongs to",
                "The brother resonates to John McCain's campaign slogan 'Country First,' and the twins' one point of agreement is that they must not talk about politics when the sister comes home for the holidays",
                "On the day they were born the sister was not predestined to vote for Obama, nor was the brother guaranteed to become a Republican - their genes gave them different first drafts that led them down different paths into different moral subcultures",
                "Dan McAdams distinguishes three levels of personality: dispositional traits, characteristic adaptations, and life narratives",
                "Characteristic adaptations emerge as people respond to the specific environments they face, as when a strict, well-ordered school fits the brother but turns the sister angry and socially disengaged",
                "The human mind is a story processor, not a logic processor, and life narratives are simplified, selective reconstructions of the past, often connected to an idealized vision of the future, that still influence behavior, relationships, and mental health",
                "Analyzing narratives from liberal and conservative Christians with Moral Foundations Theory, McAdams found conservatives underscored respect for authority, allegiance to one's group, and purity of the self, while liberals emphasized human suffering and social fairness",
                "Keith Richards, once a marginally well-behaved member of his school choir that won competitions, was dumped by the choir master when the boys' voices changed and was then informed he would have to repeat a full year in school",
                "Richards called it a kick in the guts that made him, Spike, and Terry become terrorists against the country: 'There's them, the authorities. And a slow-burning fuse was lit'",
                "Once Richards understood himself as a crusader against abusive authority, his life narrative fit the stories that all parties on the left tell, and there was no way he was ever going to vote for the British Conservative Party",
            ],
        ),
        "audit": (
            "Audit: The Grand Narrative Files",
            "File each claim under the grand narrative it serves: the liberal progress narrative of heroic liberation from oppression, or the Reagan narrative of defense against the federal bureaucracy. For every entry, record which moral foundations carry the moral force, and audit both sides' ability to understand the other before the empathy-asymmetry study is stamped.",
            "A file room where two narratives unroll like scrolls: one showing crowds storming the Bastille and freeing the prisoners, the other a family reclaiming its home from termites and repairing the joists; a rubber stamp reads 'Morality binds and blinds.'",
            [
                "In Moral, Believing Animals, the sociologist Christian Smith shows how grand narratives identify and reinforce the sacred core of each moral matrix, each with a beginning, a middle in which a threat arises, and an end in which a resolution is achieved",
                "The liberal progress narrative begins once upon a time with the vast majority of humans suffering in unjust, unhealthy, repressive societies, and ends with the struggle to dismantle the powerful vestiges of inequality, exploitation, and repression",
                "The liberal progress narrative is a heroic liberation narrative whose moral force comes primarily from the Care/harm and Liberty foundations, with Authority mentioned only as an evil and no mention of Loyalty or Sanctity",
                "Drew Westen's The Political Brain extracts the Reagan master narrative: once upon a time America was a shining beacon, then liberals erected an enormous federal bureaucracy that handcuffed the invisible hand of the free market",
                "In the Reagan narrative, liberals siphoned money from hardworking Americans and gave it to Cadillac-driving drug addicts and welfare queens, tried to understand criminals instead of punishing them, and preached promiscuity instead of traditional values",
                "The Reagan narrative is a heroism of defense - less like storming the Bastille than like a family reclaiming its home from termites and then repairing the joists",
                "The Reagan narrative relies on at least five of the six moral foundations: a hint of Care for the victims of crime, plus clear Liberty, Fairness as proportionality, Loyalty to soldiers and the flag, Authority, and Sanctity",
                "The obstacles to empathy are not symmetrical: since the left builds its moral matrices on a smaller number of foundations, there is no foundation used by the left that is not also used by the right",
                "In a study with Jesse Graham and Brian Nosek, more than two thousand American visitors to YourMorals.org filled out the Moral Foundations Questionnaire as themselves, as they think a typical liberal would, or as a typical conservative would",
                "Moderates and conservatives were most accurate in predicting the responses of typical partisans, while liberals were the least accurate - especially those who described themselves as very liberal",
                "The biggest errors came when liberals answered the Care and Fairness questions while pretending to be conservatives, assuming conservatives would reject statements such as 'One of the worst things a person could do is hurt a defenseless animal'",
                "The theater critic who wrote that Republicans should be exterminated before they cause more harm showed the inability of a man who enters fantastical imaginary worlds for a living to imagine that Republicans act within a moral matrix different from his own",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: The Sacred Value Sorter",
            "Sort each figure and quote onto the matrix that owns it: liberals with their sacred value of caring for victims of oppression, libertarians with their sacred value of individual liberty, and social conservatives with their sacred value of preserving institutions and traditions. Justify every placement by the foundation weights on the diagram before the third rail electrifies.",
            "Three moral matrix diagrams glow side by side - a two-foundation liberal matrix, a liberty-centered libertarian matrix, and a six-foundation conservative matrix - while figures step onto the scale of their most sacred value, past a warning rail labeled 'the third rail that will get you electrocuted if you touch it.'",
            [
                "For American liberals since the 1960s, the most sacred value is caring for victims of oppression, and anyone who blames such victims for their own problems or merely excuses prejudice against them can expect a vehement tribal response",
                "Garrison Keillor captured the spirit and self-image of the left: 'I am a liberal, and liberalism is the politics of kindness'",
                "The liberal moral matrix rests primarily on the Care and Liberty foundations, with thin but existing lines to Loyalty, Authority, and Sanctity - think of the sanctification of nature",
                "Libertarians are the direct descendants of the eighteenth- and nineteenth-century Enlightenment reformers who fought to free people and markets from the control of kings and clergy, and liberty is their sacred value",
                "In the late nineteenth century liberalism split: the new liberals, or progressives, saw powerful corporations as the chief threats to liberty, while the classical liberals continued to fear government, and progressives like Theodore Roosevelt and Woodrow Wilson broke up monopolies and created regulatory agencies",
                "The libertarian writer Will Wilkinson suggests libertarians are basically liberals who love markets and lack bleeding hearts - a claim our research at YourMorals.org confirms",
                "In a project led by Ravi Iyer and Sena Koleva, analyses of surveys from 12,000 libertarians showed they score higher than conservatives on openness to experience and lower than conservatives on disgust sensitivity and conscientiousness",
                "Libertarians have generally supported the Republican Party since the 1930s because libertarians and Republicans share a common enemy: the liberal welfare society that they believe is destroying America's liberty and moral fiber",
                "Social conservatives have the broadest set of moral concerns, valuing all six foundations relatively equally, and this breadth - especially high settings on Loyalty, Authority, and Sanctity - gives them insights into threats to moral capital that liberals cannot perceive",
                "For social conservatives, preserving the institutions and traditions that provide our moral exoskeletons is the most sacred value, and they fight back ferociously when they believe change will damage institutions such as the family",
                "As one formulation puts it, when the foundations of society are threatened, the conservative ideology reminds men of the necessity of some institutions and the desirability of the existing ones",
                "John Stuart Mill said that a party of order or stability and a party of progress or reform are both necessary elements of a healthy state of political life",
            ],
        ),
        "boss": (
            "Boss Battle: The Yin-Yang Arbitration",
            "Arbitrate the disputes of the age under Durkheimian utilitarianism: rule on the two liberal points - governments should restrain corporate superorganisms, and some problems really can be solved by regulation - and the two counterpoints - markets are miraculous, and you can't help the bees by destroying the hive. Weigh the evidence: the leaded gasoline phaseout, the can of peas, Goldhill's father, the hunkering turtles, and produce a verdict that turns Manichaean war into yin-yang disagreement.",
            "A courtroom where two giant hands, one labeled Care and one labeled Liberty, hold a scale of externalities; exhibits line the bench - a leaded gas pump, a can of peas, a hospital checklist, a beehive with a single dying bee being rescued by a giant hand - while a banner reads 'Morality binds and blinds.'",
            [
                "Haidt argues that corporations are actual superorganisms that will grow ever more powerful as they evolve, and the only force left on Earth that can stand up to the largest of them is national governments",
                "Economists speak of externalities - the costs incurred by third parties who did not agree to the transaction - as when a farmer's new fertilizer increases his yield but causes damaging runoff into nearby rivers",
                "When corporations are given the ring of Gyges - secrecy and public invisibility, and the ability to capture politicians and agencies - we can expect catastrophic results, and efficient markets require government regulation",
                "The chemical industry blocked all efforts to ban lead additives from gasoline for decades, but after the Carter administration began a partial phaseout and a bipartisan group of congressmen stood up against the industry, lead was completely removed from gasoline by the 1990s",
                "The lead phaseout may have been responsible for up to half of the extraordinary and otherwise unexplained drop in crime in the 1990s, as the generation of boys with lead-poisoned brains was replaced by young men with unleaded brains and better impulse control",
                "From a Durkheimian utilitarian perspective, the cheapest and most humane way to fight crime may be to give more money and authority to the Environmental Protection Agency",
                "David Goldhill's father was killed by an infection he caught while in the hospital, and Goldhill learned that the death rate can be cut by two-thirds when hospitals follow a simple checklist of sanitary procedures that most hospitals never adopt",
                "Goldhill's 2009 Atlantic essay 'How American Health Care Killed My Father' argues that using insurance for routine purchases is absurd - we would never file a claim on our car insurance to pay for an oil change",
                "Libertarians sometimes have a quasi-religious faith in free markets because competition rewards every innovation that shaves a penny off cost - a can of peas bought for under a dollar represents farmers, truckers, miners, and metalworkers coordinated by the invisible hand",
                "Edmund Burke said in 1790 that to love the little platoon we belong to in society is the first principle of public affections, the first link in the series by which we proceed towards a love of our country and of mankind",
                "Putnam's paper 'E Pluribus Unum' found that ethnic diversity reduces both bridging capital - trust between groups - and bonding capital - trust within groups - making people in diverse settings hunker down and pull in like a turtle, the exact opposite of hiving",
                "America's political class has become far more Manichaean since the early 1990s, following the third-century Persian prophet Mani's vision of the world as a battleground between absolute good and absolute evil in which compromise is a sin",
            ],
        ),
    },
]
