# -*- coding: utf-8 -*-
CHAPTER = {
    "num": 7,
    "title": "Experimental Design",
    "authors": "Eliot R. Smith",
    "domain": "Research Methods | Experimental Design",
    "scrub": (
        "Statistical Power and Research Design",
        "You are a study designer who must plan a new experiment. Compute how statistical power depends on alpha, sample size, and effect size, and explain why underpowered studies are dangerous. Decide how to allocate a fixed number of participants across conditions so each planned hypothesis test is as powerful as possible.",
        "You stand before a whiteboard covered with power curves and a sample-size calculator. A bar chart shows the median power of social psychological studies dropping below fifty percent, while a warning panel flashes Type M and Type S error labels next to a low-power study's inflated effect estimate.",
        [
            "Statistical power is the probability that a study will attain a statistically significant result for a particular effect, assuming that effect has a specific nonzero size in the population.",
            "Researchers usually aim to achieve power of 80 percent or better for the effects they test.",
            "For a given effect in a design, power depends on the chosen alpha or significance level (conventionally 0.05), the number of participants or other units, and the assumed size of the effect.",
            "An a priori power analysis indicates the required number of participants given an estimated effect size, which may come from a similar study, a meta-analysis, or a domain-wide meta-analysis.",
            "For an already completed study with fixed N, a sensitivity analysis can indicate the smallest effect size the study would have been able to detect.",
            "Best practice today is to conduct a power analysis to select the sample size before running a study, to ensure the study is adequately powered.",
            "As long ago as 1962, Cohen found that published social psychological studies had a median power of only 0.46 to detect a medium-sized effect, meaning researchers had less than an even chance of finding a significant result.",
            "A low-powered study gives imprecise and highly variable estimates of effects, and a significant result from it is very likely to represent a Type M error (overestimating the effect's magnitude) or even a Type S error (getting the wrong sign).",
            "Running several low-powered studies is dangerous because one may pop up as significant by chance alone even when the procedural variations being tested make no real difference.",
            "The way a fixed number of participants is allocated across conditions affects power, and no single allocation is optimal for all hypotheses simultaneously.",
            "Factors other than participant number that affect power include the choice of within-participant versus between-participant designs, covariates or blocking factors, reliable measurement of dependent variables, and fixed versus random treatment of factors.",
        ],
    ),
    "dialogue": (
        "Independent Variables and Factors",
        "You are a researcher designing the independent variables for an experiment on persuasion and person perception. Choose whether each factor is between-participant or within-participant, decide whether its levels are fixed or random, and justify the extremity and number of levels you select for each manipulation.",
        "You sit at a drafting table covered with factor cards labeled between and within, next to a diagram of participants flowing into groups. A scale of manipulation strength runs along the wall, and a panel contrasts one scenario about a fixed set of accident scenarios with a random sample of scenarios drawn from a larger population.",
        [
            "An experimental design always has at least two factors: one corresponding to participants (or other randomly assigned units) and at least one other independent variable.",
            "A between-participant factor means distinct groups of participants are exposed to the different levels of the factor, with participants randomly assigned to those groups.",
            "A within-participant factor means each participant is exposed to more than one level of the factor, and in an experimental design the order of exposure is what is randomly assigned.",
            "Randomization means that differences between groups on the dependent variable cannot readily be attributed to alternative causes like differences in group composition.",
            "With a fixed factor, the levels used in a study are selected for their intrinsic theoretical or practical interest, and conclusions apply only to those levels.",
            "With a random factor, the levels used in the experiment are regarded as a sample from a larger population of levels, and the participants factor in a typical experiment is the obvious example.",
            "As a guideline for deciding between fixed and random treatment, a factor is fixed if one would leave its levels the same when replicating the study, and random if one would sample other similar levels instead.",
            "Reusing the same materials across studies is dangerous, as the risky shift literature showed: the effect was specific to particular decision problems and was later reconceptualized as group polarization.",
            "Ecological design emphasizes constructing manipulations that match treatments found in everyday life, such as sampling accident scenarios from police reports.",
            "Strong manipulations can create larger effect sizes and higher statistical power, but some effects of everyday life, like the death of a close relative, cannot be ethically or practically reproduced as manipulations.",
            "For an ordered continuum, a typical design uses just high and low levels to maximize power for a linear effect, while more levels can reveal nonlinear or U-shaped effects at a cost in power.",
            "Dichotomizing a continuous variable throws away valid variance and reduces power, and Maxwell and Delaney showed it can even make another factor appear significant when it is not.",
        ],
    ),
    "audit": (
        "Relations among Factors: Crossing, Nesting, and Counterbalancing",
        "You are a design auditor reviewing a proposed experiment on memory for expectation-consistent versus inconsistent behaviors. Classify each pair of factors as crossed, nested, or confounded, evaluate the within-participant design for carryover and order effects, and recommend counterbalancing or other corrections before the study is approved.",
        "You review a wall of factor-relation diagrams: crossed grids, nested trees, and a tangle labeled confounded. A timeline of conditions scrolls past, with carryover effects leaking between adjacent cells, while a checkerboard counterbalancing grid shows how stimulus sets can be swapped across participant groups.",
        [
            "Multiple factors in a design can be crossed, nested, or confounded, and crossed factors include each level of one factor in combination with each level of the other.",
            "Nested factors involve multiple levels of a subsidiary factor that occur uniquely within a given level of a more encompassing factor, and confounded factors are conceptually distinct variables whose effects cannot be empirically disentangled.",
            "A between-participant design nests participants within all other factors, while a within-participant design crosses one or more factors with participants, and a mixed design has both kinds of factors.",
            "Power is often greater for within-participant manipulations because differences among participants, the largest source of variance, inflate the error term only for between-participant effects.",
            "Carryover effects occur when a participant's response in a given condition depends on experimental conditions experienced previously, for example because previous stimuli serve as anchors for reactions to the next stimulus.",
            "Participants in a within-participant design see more than one condition and are better able to guess the hypotheses, creating demand characteristics that can bias their responses.",
            "The most important reason for including crossed factors is to test a theoretically predicted interaction, since theories that predict a specific interaction pattern rather than a simple main effect gain more in credibility when confirmed.",
            "A single dissociation shows one manipulation affecting one measure but not another, and a full double-dissociation design manipulates both constructs to rule out alternative explanations like insensitive measures.",
            "Tests of interactions generally have much lower power than tests of main effects: detecting a predicted interaction in a two-by-two design typically requires quadrupling the sample size compared with detecting the original main effect.",
            "When factors entering an interaction are measured rather than manipulated, power is further reduced by few cases with extreme values on both factors and by measurement unreliability.",
            "Mathematical transformations can create or remove ordinal interactions, so claims about the presence or absence of an interaction are weak unless the applicability of transformations can be ruled out on theoretical grounds.",
            "Adding crossed factors that represent theoretically irrelevant sources of variance, termed covariates (if continuous) or blocking factors (if categorical), reduces error variance and increases statistical power.",
        ],
    ),
    "matrix": (
        "Dependent Variables: Pretesting and Item Selection",
        "You are building the dependent measures for an attitude change study. Decide whether to include a pretest, choose how many items to use, and select a strategy for combining them, weighing power and reliability against the risk of pretest sensitization for each measurement choice.",
        "You arrange blocks on a measurement matrix: a single gold-standard item, a stack of Likert items awaiting averaging, and a column of items coded as a within-participants factor. A warning light labeled pretest sensitization flickers next to a timeline that shows where the pretest is placed in the session.",
        [
            "Pretesting participants with a measure identical or related to the dependent variable can increase power when the pretest is used as a covariate or to create blocks of participants with similar pretest scores.",
            "If the covariate's within-groups correlation with the dependent variable is r, the experiment's error variance decreases by approximately a factor of 1 minus r squared in either a randomized-blocks or covariance design.",
            "A covariate with a correlation of 0.70 with the dependent variable would cut error variance roughly in half, doubling the study's power.",
            "Pretests are common in studies using physiological measures with large individual differences, such as measuring blood pressure reactivity while a participant relaxes to collect a baseline.",
            "The main reason pretests are often not used is concern about pretest sensitization, because participants who have completed a pretest may respond differently to a manipulation than unpretested participants.",
            "Pretest sensitization can be made less likely by administering the pretest in a separate session unconnected in participants' minds with the main experiment, such as a mass pretesting session at the start of an academic term.",
            "Using a single item selected from pilot testing minimizes the participant's time and effort but may lead to low reliability, although a single gold-standard measure is appropriate in some areas, such as the cardiac measure of pre-ejection period.",
            "The most common approach is to average or sum several items with the same response scale, which gains power by increasing reliability and increases construct validity by more broadly sampling the content domain.",
            "Treating item as an explicit within-participant factor corresponds to systematically varying a contextual factor and permits confidence about generality if the effect holds across items, but items should then be treated as a random factor requiring a large number of items.",
            "Analyzing multiple dependent variables separately should be avoided if they are parallel measures of the same construct, because conflicting results would be uninterpretable, but separate analyses are reasonable for measures of distinct constructs.",
            "When measures of multiple conceptual variables are included and hypotheses concern their causal and mediational interrelationships, the data can be analyzed in a multiple-group structural equation framework.",
        ],
    ),
    "boss": (
        "Confounds, Artifacts, and Studying Mediation",
        "You are the chief methodologist in charge of a high-stakes online experiment on stereotypes and decision making. Protect the study against demand characteristics, experimenter expectancies, social comparison effects, and differential attrition, and then plan a multi-study strategy that can support a mediation claim about the causal chain.",
        "You command a control room with panels monitoring every study session: a cover-story integrity gauge, an experimenter blindness switch, and an attrition tracker that charts who drops out in each condition in real time. A wall map shows a causal chain X to M to Y, with dashed lines marking the untestable assumptions that a single study cannot verify.",
        [
            "Demand characteristics arise because participants' perceptions of the purpose of the research may influence their responses, and a coherent believable cover story can at least ensure all participants hold the same view of the purpose.",
            "Keeping experimenters or confederates unaware of each participant's condition prevents unconscious biases from causing subtle differential treatment, whereas merely keeping them unaware of the hypotheses offers no real protection.",
            "Participants who see treatments as differentially desirable may react with compensatory rivalry or demoralization, and mood effects from manipulations are a related potential confound that experimenters often assess and statistically check.",
            "Differential treatment-related attrition can falsely produce differences between conditions, and even equal attrition rates across conditions are a problem because the remaining subpopulations may no longer be equivalent.",
            "Zhou and Fishbach recommend inducing less motivated participants to drop out before random assignment and collecting demographics and personality measures before assignment so analyses can show which participants drop out.",
            "Reporting attrition, both overall and per condition, is essential for online studies, where large proportions of participants may drop out or fail minimal data quality checks.",
            "A typical mediation design manipulates X and measures both the dependent variable Y and one or more putative mediators M, and statistical evidence for mediation is traditionally obtained from several separate regression equations.",
            "Experimental manipulation assures that X causally precedes both M and Y, but the design does not establish causal priority between the latter two variables.",
            "Standard mediation analysis requires strong assumptions, including that all unobserved causes of M are uncorrelated with unobserved causes of Y, and these assumptions generally are not empirically testable within a single study.",
            "Mediation cannot generally be demonstrated with a single statistical procedure or a single study, but can be firmly supported only by convergent patterns of results from multiple studies, often from multiple research teams.",
            "In social psychology today the most important unit of research is not the individual study but the research program, a series of conceptually related studies developing a common theoretical theme.",
            "The strategic maxim proposed is that more smaller studies are often better than fewer larger ones, provided they possess adequate power, because a series of small studies is stronger in construct and external validity than a single massive study.",
        ],
    ),
}
