# -*- coding: utf-8 -*-
CHAPTER = {
    "num": 8,
    "title": "Quasi-Experimental Designs",
    "authors": "Leandre R. Fabrigar, Thomas I. Vaughan-Johnston, and Duane T. Wegener",
    "domain": "Research Methods | Quasi-Experimental Design",
    "scrub": (
        "What Is a Quasi-Experiment and the Validity Framework",
        "You are a methods instructor preparing students to distinguish study types. Classify studies as randomized experiments, quasi-experiments, or nonexperimental studies based on how assignment to the independent variable occurs, and apply the four types of validity from Cook and Campbell (1979) to a set of study descriptions. Use the association, direction, and isolation conditions to judge how strong a causal claim each design can support.",
        "You stand before a lecture screen with three study-type cards and arrows showing how assignment to conditions occurs in each one. A validity diamond labeled statistical conclusion, construct, external, and internal validity spins beside a causal-inference meter that moves as you test the association, direction, and isolation conditions.",
        [
            "A quasi-experiment is a type of study that attempts to mimic the objectives and structure of traditional randomized experiments, and like an experiment its goal is to evaluate the causal effect of an independent variable (IV) on a dependent variable (DV) of interest.",
            "The primary distinction between quasi-experiments and experiments is that condition assignment is randomized in experiments whereas it is not randomized in quasi-experiments.",
            "Quasi-experiments are typically used in contexts where it is not possible to randomly assign participants to conditions because of practical constraints or ethical concerns.",
            "Unlike nonexperimental studies, assignment to levels of the IV in a quasi-experiment is usually not solely the result of natural variation but is typically based on some researcher-specified criterion that is at least somewhat under the researcher's control or understood by the researcher.",
            "Even when natural variation has determined assignment in a quasi-experiment, the threshold value for assignment is at minimum known by and often determined by the researcher, and variation above and below the threshold has no implications for assignment.",
            "Quasi-experiments are frequently conducted in field settings, because these settings sometimes make random assignment unfeasible or unethical, and they often address applied research questions.",
            "The Cook and Campbell (1979) framework conceptualizes the validity of a study in terms of statistical conclusion validity, construct validity, external validity, and internal validity.",
            "Statistical conclusion validity is the accuracy of a conclusion regarding a relation between or among variables in a study, and methodologists have typically not assumed a general advantage of any study type on this dimension.",
            "Construct validity is the degree to which operationalizations of IVs and DVs reflect their intended constructs, since no single operationalization is likely to perfectly reflect its intended construct.",
            "External validity is the degree to which the results of a given study can be generalized to other contexts and populations, and it must be judged in the context of the researchers' goals.",
            "Internal validity refers to the inferential strength with which an observed relation among variables can be interpreted as causal in nature.",
            "Bollen (1989) suggested that internal validity is high to the extent that one can build a compelling case for having satisfied three conditions: association, direction, and isolation, where the condition of isolation is achieved by removing the distorting effects of all other causal influences on the DV.",
        ],
    ),
    "dialogue": (
        "Threats to Causal Assumptions in Quasi-Experiments",
        "You are a research consultant reviewing a school-based intervention study in which assignment was not random. Diagnose which internal validity threats, including history, maturation, selection, attrition, testing, and instrumentation effects, could explain the observed outcome changes. Recommend design modifications that would make each identified threat implausible before the study is rerun.",
        "You face a wall of time-lapse panels showing an intervention study across a school year, with ghost arrows labeled history, maturation, and attrition poking at the outcome line. A deck of threat cards sits on your desk, each one marked with how it undermines the condition of isolation.",
        [
            "Each of the threats to causal assumptions in quasi-experiments can be understood as undermining the condition of isolation.",
            "A history threat is any influence that occurs between participants' exposure to an IV and the assessment of the DV that might shape participants' outcome responses.",
            "Maturation effects refer to endogenous changes in participants across time, either immediately, such as participants becoming tired after exposure to an intervention, or in the longer term, such as child participants developing greater cognitive skills as they age.",
            "Selection threats arise when participants' judgments or actions determine their assignment to conditions, something that always occurs when the IV reflects naturally occurring variation on a measure.",
            "Attrition threats arise when participants drop out of a study at systematically different rates, or for systematically different reasons, in a way associated with their standing on the IV.",
            "Testing effects capture shifts in participants' understanding, interpretation, or subjective view of measures, whereas instrumentation effects refer to shifts in the measurement instrument itself, such as a gradual loss of sensitivity in a physical measurement tool.",
            "Random assignment makes history and maturational effects unlikely because control and intervention participants should be equally susceptible to external events and endogenous changes.",
            "A key advantage of the experiment is that random assignment mitigates the risk that selection can occur at different rates or for different reasons depending on condition.",
            "Attrition can be an issue even in experiments, because if dropout rates are substantial but at comparable levels across conditions, attrition could still threaten isolation if the psychological factors producing attrition in the two conditions are different and exert a causal impact on the DV.",
            "If quasi-experimental condition assignment is based on properties of the participants that influence attrition, those properties might exert influences on the DV that may be incorrectly attributed to the IV.",
            "If the criterion that determines condition assignment is associated with the direction or magnitude of testing or instrumentation effects, internal validity can be threatened in quasi-experimental and nonexperimental studies.",
        ],
    ),
    "audit": (
        "Nonequivalent Comparison Group Designs and Statistical Control",
        "You are a design auditor evaluating a district's new academic skills program tested with an intervention group and a control group of schools. Inspect the covariate set and the propensity score analysis for the assumption of strong ignorability, decide whether a pretest of the DV was included, and judge how the hierarchical structure of the data was handled. Recommend propensity score stratification or a switching replication design where the evidence is weak.",
        "You sit before a balance scale with an intervention school on one side and a control school on the other, labeled not equivalent. A covariate tree grows beside it with propensity scores glowing as matched pairs light up, and a data grid shows classrooms nested inside schools to flag nonindependent observations.",
        [
            "Nonequivalent comparison group design is a family of quasi-experimental designs in which researchers acknowledge that a control group and an intervention group are not equivalent because of some nonrandom assignment of participants to conditions.",
            "A crucial limitation of the nonequivalent comparison group design is the assumption of strong ignorability, the idea that all possible variables that might make the control and intervention groups non-equivalent have somehow been captured and addressed.",
            "The simplest approach to debiasing the causal estimate is to include covariates that might be associated with the IV, by measuring the alternative causal variables and including them in statistical analyses.",
            "Research suggests that it is often better to include relatively diverse domains of covariates, more domains of covariates, and more covariates within each domain, for example child cognitive skills, child demographics, child social skills, teacher demographics, and home environment.",
            "Propensity scores are composite variables calculated from several other measured variables that are intended to capture variance that could conceivably be confounded with membership in conditions.",
            "A propensity score represents the probability that a person will be in one condition rather than another given that person's observed scores on a set of covariates selected to predict the person's condition.",
            "Detected differences in propensity score distributions by condition can be adjusted in numerous ways, such as stratifying the sample by propensity score quintiles.",
            "Propensity scores can only reduce biases insofar as the measures used to calculate them are internally reliable, and to a degree the sheer volume of measures can help counteract the deleterious effect of unreliable measures.",
            "The most basic design is the posttest-only nonequivalent-groups design, in which the control and intervention groups' scores on the DV are compared without measuring the DV at any other timepoint, and selection and attrition factors could prompt artificial differences between the groups.",
            "Designs that employ a pretest of the DV are termed pretest-posttest comparison group designs, and selection biases are less likely to drive results in these designs because control-versus-intervention selection differences that affect the DV are accounted for by the pretest measure, although history effects remain possible.",
            "In switching replication with treatment removal designs, treatment assignment is reversed over time so that a causal effect can be triangulated, making it increasingly implausible that maturity or history effects would account for the shifting patterns on the DV.",
            "When data are hierarchical, such as observations nested within schools, neighborhoods, or wards, statistical conclusion validity is undermined if this nonindependence is not modeled with multilevel modeling, and statistical power is also influenced by the degree of nonindependence.",
        ],
    ),
    "matrix": (
        "Regression Discontinuity Designs",
        "You are an evaluator for a scholarship program that awards certificates of merit to students scoring at or above a cutoff on an aptitude measure. Estimate the intervention's causal effect from the discontinuity at the cutoff, check whether the functional form of the selection-outcome relation is correctly modeled, and judge whether the design has adequate statistical power. Consider adding a pretest or an exclusively control sample to strengthen the estimates.",
        "You gaze at a scatterplot of aptitude scores against scholarship rates with a vertical cutoff line and a substantial jump in the regression line at the boundary. A model-fitting panel lets you toggle linear and curvilinear functional forms, while a power meter warns that the design needs roughly three to four times as many participants as an experiment.",
        [
            "Researchers can estimate the causal effect of the IV using a regression discontinuity design in cases where interventions are allocated strictly based on a cutoff point on a known variable, as when psychiatric patients are assigned therapy given a particular level of depression.",
            "The regression discontinuity design capitalizes on the fact that although condition assignment is not random, the basis of assignment is known: participants' level on a quantitative assignment variable.",
            "The relation between the selection variable and the DV is assumed to show a consistent, though not necessarily linear, pattern across levels of the selection variable, which is called the functional form.",
            "Any discontinuity in the relation between the selection variable and the DV that occurs at the cutoff point determining inclusion in the experimental versus control groups is assumed to represent the causal impact of the intervention.",
            "The first published regression discontinuity study was by Thistlewaite and Campbell (1960), in which 5,126 students received certificates of merit and another 2,848 did not, and their outcomes were tracked six months later.",
            "In the basic linear implementation, the causal effect of the intervention is estimated through a regression equation in which an indicator variable is scored 0 if the participant is in the control group and 1 if the participant is in the experimental group.",
            "The regression discontinuity design can demonstrate the causal impact of the IV even in the presence of nonlinearity in the relation between the selection variable and the DV, so long as the relation is correctly modeled.",
            "A widely discussed limitation of the design is the loss of statistical power relative to experiments, with common estimates that regression discontinuity studies need about 2.75 or three to four times more participants to reach a comparable level of statistical power.",
            "Regression discontinuity designs technically only provide evidence of an average causal effect at the level of the selection variable that forms the cutoff point, and thus are limited in their ability to generalize across levels of the selection variable.",
            "The regression discontinuity with control group design adds a second sample that is exclusively a control group, which helps to determine the functional form between the selection and outcome variables in the absence of the intervention and increases statistical power.",
            "Supplementing the regression discontinuity design with a pretest of the DV has been demonstrated to improve researchers' ability to extrapolate causal effect estimates beyond the cutoff point.",
            "Methodologists have often proposed regression discontinuity as the gold standard for quasi-experiments, and when optimal designs have been compared against randomized experiments they often produce very similar results, suggesting an almost complete elimination of bias.",
        ],
    ),
    "boss": (
        "Interrupted Time Series Designs",
        "You are the lead analyst for a hospital policy change that took effect on a known date, with weekly outcome measurements collected before and after. Conduct a segmented regression analysis, model autocorrelation with ARIMA, and identify whether the intervention's effect takes step, pulse, or ramp form. Strengthen the design by adding a control series, an A-B-A phase, or multiple baselines before delivering the causal verdict.",
        "You stand before a long timeline chart of weekly outcome data with a vertical intervention marker and a slope that visibly shifts at the break point. Side panels show an ARIMA parameter console, an A-B-A toggle that withdraws the intervention, and a second grey control-group line tracking flat beside the experimental line.",
        [
            "Interrupted time series designs use multiple measurements of a DV assessed on a regular basis, and researchers assess whether there is a disruption in the relation between time and the DV at the timepoint when an intervention occurs.",
            "In the most basic version of this design there is no true control group, because observations collected when the intervention is not occurring are the control condition being compared against observations collected during the intervention.",
            "The classic tool for analyzing interrupted time series data is segmented regression analysis, and at its most basic level this form of analysis matches the equations used for regression discontinuity analysis.",
            "Autocorrelation refers to the idea that observations closer to one another in time will not be entirely independent of one another, and it can take the form of negative autocorrelation or the more common positive autocorrelation.",
            "Autocorrelation can be modeled with varying levels of sophistication using ARIMA (autoregressive integrated moving average) models, whose three basic parameters are p, d, and q, each of which can be as low as zero.",
            "An intervention's effect can be understood as having a step form, representing a sudden sustained change in the outcome variable, a pulse form, representing a sudden but temporary change that reverts back to baseline, or a ramp form, representing a change in the slope that gradually takes place across time.",
            "The most basic interrupted time series design is called an A-B design, and toggling the intervention on and off produces the A-B-A design, in which alternative explanations like history effects are increasingly implausible because an external event would have to begin and end exactly with the intervention.",
            "History and maturation explanations become decreasingly plausible as the number of pre-intervention measures increases, because the pattern of change in the outcome measure prior to the intervention is explicitly modeled.",
            "Adding an intervention-irrelevant DV, such as attitudes toward school cafeteria food when studying attitudes toward science, helps show that an intervention did not simply capitalize on a general shift in circumstances on that date.",
            "The comparative interrupted time series (CITS) design measures a control group whose observations are collected across the same time period as the intervention group but which does not receive the intervention, and there is wide consensus that CITS methods are superior to simple ITS designs.",
            "In a multiple-baseline design, multiple groups eligible to receive an intervention are allocated different dates to receive it, and the mere effect of time is ruled out by showing that whichever group is not receiving the intervention does not demonstrate any pronounced increases.",
            "Collecting many pre-intervention measurements of the DV is important, with at least fifty recommended by Glass et al. (1975), though some have questioned the evidentiary basis for this assertion.",
        ],
    ),
}
