# -*- coding: utf-8 -*-
CHAPTER = {
    "num": 16,
    "title": "Behavioral Observation and Coding",
    "authors": "Katherine R. Thorson and Tessa West",
    "domain": "Research Methods | Behavioral Coding",
    "scrub": (
        "Observing and Coding: What It Is and Why It Matters",
        "Define behavioral observation and behavioral coding, then contrast manual coding with automated coding done by computer programs. Build a checklist of the method's strengths (direct measurement, low interference, temporal frequency, portability) and its three main challenges (measurement difficulties, labor intensity, time intensity).",
        "A research lab whiteboard is split into two columns: one labeled behavioral observation, listing a researcher watching and hearing actions in real time, and one labeled behavioral coding, showing assistants turning those actions into numbers in a spreadsheet. Icons of a handheld video camera, a clipboard, and a computer with NLP gear float nearby, with a balance scale weighing strengths against challenges.",
        [
            "Behavioral observation is the process that occurs when a researcher sees or hears the actions of a person or multiple persons.",
            "Behavioral coding is the process that occurs when other people systematically document those actions in quantitative form.",
            "Manual coding stands in contrast to automated coding, which uses tools from computer science such as natural-language processing rather than people to quantify behaviors.",
            "The chapter focuses on observation of direct behaviors and actions of a person, rather than the products or outcomes of a person's behaviors.",
            "The primary strength of behavioral observation and coding is that it explicitly measures the variables of interest to researchers.",
            "Self-reports about behavior are subject to numerous biases and do not show a one-to-one correspondence with real behavior.",
            "Behavioral observation requires relatively low levels of interference, reducing social desirability biases and experimenter effects.",
            "Behavior can be assessed with a high degree of temporal frequency, often continuously throughout a study or at multiple timepoints.",
            "Behavioral data can be recorded in a wide range of settings, including outside the lab, often with a simple handheld video camera.",
            "Behavioral coding is not immune to measurement difficulties, including whether a code is reliable and whether it is a true measure of the behavior.",
            "Behavioral observation and coding are labor-intensive because multiple research assistants must be hired, trained, and supervised throughout the coding process.",
            "The first guiding principle is to lead with your conceptual question and not build a research question around behaviors that are easy to record.",
        ],
    ),
    "dialogue": (
        "Designing Observation: Settings, Recording, and Code Types",
        "Walk through the continuum of observation approaches, from naturalistic to quasi-naturalistic to analog to experimental manipulation with confederates. Then decide between topographical and dimensional codes and between macro and micro systems, judging which code types fit the behavior's observability and variability.",
        "A settings dial rotates from a city park (naturalistic), to a living room with a no-devices rule (quasi-naturalistic), to a lab with couples discussing conflicts (analog), to a participant talking with a confederate (experimental). Beside it, two code ladders stand side by side: one with presence-absence checkboxes and one with a 1-to-7 intensity scale, plus two clocks labeled macro (one summary rating) and micro (every five seconds).",
        [
            "Observation and coding can occur live in real time or later from documentation such as videotape, audio recording, or a text transcript.",
            "Recordings afford flexibility because they can be viewed repeatedly, slowed down for temporal precision, and used for secondary data analysis.",
            "Behavioral observation occurs in environments ranging from tightly controlled settings to completely naturalistic contexts.",
            "With naturalistic observation, researchers exert no influence over participants or the setting, giving the approach ecological validity and relevance.",
            "Quasi-naturalistic observation preserves ecological validity while placing some constraints, such as telling families no devices or no leaving home during a two-hour observation window.",
            "With analog observation, researchers use more control to construct in the lab situations of the kind in which the behaviors of interest occur.",
            "In experimental manipulation designs, researchers may control the interaction partner through a confederate or even a virtual confederate.",
            "Behaviors and constructs vary in observability, and in general more overt behaviors are easier to code and to achieve reliable estimates for.",
            "Topographical codes judge whether a behavior is present or absent and are useful when there is a clear, meaningful distinction between presence and absence.",
            "Dimensional codes capture the intensity of a behavior on a scale, such as rating negative affect on a scale of 1 to 7 during a conflict conversation.",
            "With both code types, variability in measurements is important because low variability can impair inter-rater reliability estimates.",
            "Macro coding systems involve global or overall codes made over longer lengths of time, while micro systems involve more frequent and fine-grained coding.",
        ],
    ),
    "audit": (
        "Building and Managing the Coding Team",
        "Select coders who are conscientious and blind to the hypotheses, decide how many coders you need and how much they should overlap, and choose what study information coders may see. Then run the five-step coder training process and lead the team with weekly meetings that minimize coder drift.",
        "A personnel chart shows junior research assistants clustered around a lead coder, with a 25 percent overlap badge on a pie chart of the coding workload. A five-step staircase labeled scheme, self-test, teach, practice, and independent coding rises behind them, while a drifting arrow warns that ratings can change over time, and a wall sign reads: randomize, don't binge-code, ask questions.",
        [
            "Coders should not have extensive knowledge of the study hypotheses and research objectives, and they are often junior members of the research team such as undergraduate research assistants.",
            "Coders should be conscientious, organized, and detail-oriented, and they must follow coding instructions closely without applying their own interpretations of behavior.",
            "Researchers generally worry most about generalizability when codes involve more subjectivity, and in those instances they try to have a larger number of coders.",
            "You must have some overlap among coders in order to assess inter-rater reliability, and often people recommend 25 percent overlap.",
            "The more your coders overlap and the less you rely on any one single coder, the better.",
            "Researchers should think about coder overlap at the level of coding units or time intervals rather than participants, dyads, or groups, so reliability estimates are not based on agreement on only a subset of participants.",
            "Generally, the less information coders have about the specific study hypotheses, the fewer chances there are for their judgments to inadvertently conform to or refute those hypotheses.",
            "When outcomes are at the level of the dyad or group, coders need access to all interactants' behavior, but with individual-level outcomes coders' judgments of one person can be affected by information about that person's interaction partners.",
            "In the first step of training, researchers develop an initial coding scheme that describes all the behaviors they want documented and how they want them documented.",
            "Lead researchers test the coding scheme themselves and develop a coding manual that includes answers to likely questions and specifics about how borderline or questionable cases should be coded.",
            "Coders first practice on example observations in small groups and then independently code new example participants, and researchers only proceed once coders have reached an acceptable level of inter-rater reliability.",
            "Coding teams should meet weekly to minimize coder drift, and although disagreements are discussed, ratings are not updated or resolved because that would destroy their independence.",
        ],
    ),
    "matrix": (
        "Coding Logistics and Reliability Statistics",
        "Set up your recording and coding workflow: test your recording system before launching, decide how much of the observation to code, use coding passes, and document codes in spreadsheets or specialized software. Then select and compute the right reliability statistic, weighing Cohen's kappa against intraclass correlation coefficients.",
        "A video editor timeline shows multiple camera angles, color-coded coding passes for questions, smiles, and emotional tenor, and visual cue markers at segment boundaries. A calculator splits into two branches: one counting nominal codes through Cohen's kappa with Landis-Koch benchmarks, and one feeding ordinal ratings into ICC formulas, with a checklist reading remove mistakes, match the statistic to your final analysis measure, and report the variant used.",
        [
            "Researchers should fully test out a recording system and coding scheme before officially collecting data, and have their team code pilot recordings before launching the study.",
            "When recording, researchers should consider multiple camera angles, high-quality video with proper zoom and lighting, separate audio recording devices, and visual cues to mark the beginnings and ends of tasks.",
            "With longer tasks, researchers often select shorter intervals to code under the assumption that those segments are representative of longer periods of time, an approach known as thin-slicing.",
            "Coding passes are separate instances of processing a recording for particular codes, such as marking task start and stop times on one pass and questions on another.",
            "When structuring coding passes, the goal is to get as much information from coders as you can with as little effort as possible, and coding related variables together in one pass is often efficient.",
            "Spreadsheet programs are cost-effective, require minimal training, and have easily manipulable data, while specialized software like Datavyu or Noldus Observer keeps all information about a recording in one place.",
            "When two or more people code behavioral observations, researchers must assess inter-rater reliability, the degree to which those coders agree in their ratings.",
            "Inter-rater reliability is important because many behavioral codes have some degree of subjectivity, and it matters for statistical power and validity since unreliable measurements are poor representations of theoretical constructs.",
            "Cohen's kappa is appropriate when the final analyzed behavioral outcome is measured on a nominal scale, and it assesses agreement while adjusting for agreement expected due to chance.",
            "Cohen's kappa values range from -1 (complete disagreement) to 1 (complete agreement), with values from 0.6 to 0.8 considered substantial and 0.8 to 1 almost perfect agreement.",
            "The intraclass correlation coefficient (ICC) is used for variables measured on ordinal, interval, or ratio scales and is rooted in generalizability theory, which decomposes variance into sources such as participant, coder, and their interaction.",
            "When calculating ICCs, researchers must decide whether coders are random or fixed effects, whether the same or different coders coded each participant, whether absolute agreement or consistency is needed, and whether the unit of analysis is average or single measures.",
        ],
    ),
    "boss": (
        "Analyzing Coded Data and Open-Science Practices",
        "Tackle the three major analytic issues in behavioral data: inter-rater reliability, aggregation of coded responses, and nonindependence of measurements. Then navigate the modern toolkit of automated coding, text analysis, preregistration, transparency, and open data, deciding how each applies to your coding project.",
        "A final analysis dashboard shows three gauges labeled reliability, aggregation, and nonindependence, with pipelines feeding averages across coders, summed frequencies across codes, and sums across time. Around it float a robot arm coding video frames, a transcript with dictionary keywords highlighted, and an open-science shelf holding a preregistration form, a transparency report card, and a Databrary repository box.",
        [
            "There are three major analytic issues relevant to behavioral data: inter-rater agreement and reliability, aggregated coded responses, and potential nonindependence of measurements.",
            "Reliability is the extent to which a measurement can be reproduced, and unreliable measurements make it harder to detect true relationships among variables.",
            "If all coders coded all participants, averaging across coders can allow you to incorporate the number of coders into your reliability calculation, which can boost reliability estimates.",
            "Researchers can aggregate responses across codes, for example summing frequencies of fussing, crying, and gaze aversion to create a more general measure of infant negative engagement.",
            "When aggregating across codes, you should make sure the behavioral codes hang well together by assessing internal consistency, for example with a variance decomposition approach.",
            "Aggregating responses across time, such as summing the number of times people smiled over an entire conversation, can lead to more reliable estimates and a more parsimonious analysis.",
            "Nonindependence exists when outcomes cannot be considered fully independent of one another, as with repeated measures over time within a person or measures from people linked in a dyad, family, or team.",
            "Traditional statistical approaches like ANOVA and linear regression assume independent observations, so they often cannot be used when analyzing coded behavioral data.",
            "Automated coding trains computer models to recognize behaviors of interest based on a subset of information, and one example uses computer vision and machine learning to code facial affect intensity.",
            "One drawback of automated approaches is that they generally require substantial expertise in computer science, and it can be challenging to code macro behaviors in ways congruent with human perceptions.",
            "Because behavioral observation and coding are iterative, researchers who want to preregister should outline the general stages of their process and how they will make decisions during each stage, since preregistration is not all-or-nothing.",
            "Behavioral coding often receives just a few sentences in methods sections, and the authors encourage transparency about decisions such as how coders were trained and how coder drift was handled, even if only in a supplement.",
        ],
    ),
}
