# -*- coding: utf-8 -*-
CHAPTER = {
    "num": 4,
    "title": "Realizing the Promise of Diverse and Interdisciplinary Team Science",
    "authors": "Stephanie J. Tepper and Neil A. Lewis Jr.",
    "domain": "Research Methods | Team Science",
    "scrub": (
        "The Benefits of a Team Science Approach",
        "Audit the four benefits of team science described in section 4.1: the opportunity to diversify the field, expanded questions and methodologies, and the people power for more ambitious projects. For each benefit, identify the factual claims and named examples the authors cite, then rank which benefit makes the strongest case for building diverse interdisciplinary teams.",
        "A split-screen scene: on the left, a laboratory full of similar-looking researchers clustered around one whiteboard; on the right, a wide round table where researchers of varied backgrounds, fields, and nations exchange methods and questions. Floating between the two panels, a ticking gauge labeled 'collective toolkit' rises as the diverse team speaks.",
        [
            "Psychology is a team science in that people from many walks of life come together to explore the inner workings of the mind and how those internal dynamics are affected by external forces.",
            "Many areas of psychology benefit from channeling the 'wisdom of crowds' that comes from working together in teams (Larrick et al., 2012).",
            "In a diverse and inclusive team science model, people can use their unique experiences and training to advance the research process more efficiently and expand the collective toolkit of methods and approaches available for tackling important psychological questions.",
            "Research teams continue to be overwhelmingly white and wealthy, as are the participants recruited into research studies to examine psychological processes (Dupree & Kraus, 2022; Roberts et al., 2020).",
            "In a sample of research articles about race published in top social psychology journals, 92 percent of papers were edited by white editors in chief, 72 percent were written by white authors, and 66 percent of participants were white (Roberts et al., 2020).",
            "A team science approach has the potential to address the lack of diversity by creating new opportunities for expanding access to research and for creating more roles on teams that increase the representation of people who have been traditionally excluded from knowledge production processes in the field.",
            "Because 'homophily' is a strong force, it is actually quite easy to build teams that lack diversity (McPherson et al., 2001).",
            "Faculty tend to admit graduate students who share their background characteristics, collaborate with people who are already in their homogeneous networks, and cite researchers who are similar to them (Posselt, 2016; Newman, 2001; Greenwald & Schuh, 1994).",
            "There is a 'bonus' that comes from diversity: new ways of thinking, new questions, and new ideas that can advance knowledge (Page, 2019).",
            "The Psychological Science Accelerator is 'a distributed network of laboratories designed to enable and support crowdsourced research projects' (Moshontz et al., 2018).",
            "In its first project, the Psychological Science Accelerator tested the generalizability of the valence-dominance model of face perception by collecting data from over 11,000 participants in forty-one countries through a large-scale collaboration with over 200 researchers (Jones et al., 2021).",
            "Even small teams can benefit from the ethos of team science, because as long as team members possess different skills and backgrounds, they can work together in a way that capitalizes on those unique strengths and improves the efficiency and outcomes of their collaboration.",
        ],
    ),
    "dialogue": (
        "Four Models of Team Science",
        "Host a debate among four lab directors, each defending one of the four models of team science: lab teams, cross-lab teams, cross-discipline teams, and cross-sector teams. For each model, present its composition, scale, benefits, and characteristic challenges, and press the panel on when one model should be chosen over another.",
        "A round-table talk show: four chairs labeled 'Lab,' 'Cross-lab,' 'Cross-discipline,' and 'Cross-sector,' each occupied by a researcher silhouette, with a table in the middle listing Table 4.1's four principles of team science. A moderator projects each model's reach as a network diagram behind the speakers.",
        [
            "The chapter discusses four common models of team science: lab teams, cross-lab teams, cross-discipline teams, and cross-sector teams.",
            "Lab teams are groups of students, postdocs, and faculty working on common issues and topics, and they are small-scale collaborations.",
            "Lab teams may not live up to their full potential under the traditional model of academic research in which principal investigators or lab directors set the research agenda, select their own preferred methods, and train their students to follow in their academic footsteps.",
            "Thinking of labs as teams can help us recognize the contributions of members whose work may not always be acknowledged, such as research assistants, administrators, or interns (Allen et al., 2019).",
            "Cross-lab teams are often made up of researchers from different universities, typically within the same or related fields, who come together to conduct research on a shared interest.",
            "Cross-lab teams include large-scale collaborations that often produce replication studies or more rigorous tests of ideas in the field, such as the Psychological Science Accelerator and the Many Labs replication projects (Klein et al., 2018).",
            "Cross-lab teams allow researchers to test a question across several different contexts (e.g., regions, countries, languages), creating opportunities to assess generalizability and cultural variation.",
            "Conducting cross-lab research at a larger scale often requires a great deal of organization given challenges such as agreeing on research methods, navigating multi-institutional review board protocols, and finding times for team members to meet across time zones.",
            "Cross-discipline teams involve researchers from various fields or disciplines who likely have different academic backgrounds and methodological skills from one another.",
            "Cross-discipline teams are typically broader in terms of the skills and goals of the team members, so it is often important for them to be aligned in their goals for a given project, as there may be different standards across fields to adhere to.",
            "Cross-sector teams typically involve academics working in partnership with companies, schools, nonprofits, technology firms, government agencies, or other organizations to answer questions of mutual interest to all parties (Yudkin et al., 2021).",
            "Cross-sector partnerships can provide researchers with access to real-world data that are otherwise difficult to obtain, but cross-sector teams consist of people who might have drastically different goals.",
        ],
    ),
    "audit": (
        "Forming and Growing Teams",
        "Act as a team-building consultant running the three assessment questions from section 4.3.1: What are your team's goals? What skills do your team members have (or need)? What voices are represented on the team? Produce a concrete expansion plan that closes skill gaps, runs a project premortem, and recruits underrepresented collaborators through the routes the authors list.",
        "A whiteboard covered in three sticky-note clusters labeled 'Goals,' 'Skills,' and 'Voices,' with a facilitator drawing a dotted line from an empty skill slot to a door marked 'Collaboration Zone.' Off to one side, a clock ticks through a premortem imaginary failure scenario, and a checklist shows paid positions and SPSP networking platforms.",
        [
            "To engage in team science, we first need to form teams or expand and improve our current teams.",
            "The chapter offers three questions that researchers should discuss with one another early on and often: (1) What are your team's goals? (2) What skills do your team members have (or need)? (3) What voices are represented on the team?",
            "Researchers' goals might vary depending on their background, personal interests, skills, career stage, and long-term career goals, with some researchers more drawn to basic research and others interested in applications.",
            "Researchers should take time to reflect on their personal goals regularly throughout their careers, because personal reflection can help them decide whether a given project is a good investment of time and resources before beginning to work on it.",
            "Team members should meet to discuss their goals for the project and what they each hope to get out of it, including what they hope to learn and what the concrete outputs will be (e.g., papers, conference presentations, or other forms of dissemination).",
            "When collaborating in diverse teams, especially in terms of career stage and field, it is important to consider that not all outputs are valued equally across different contexts; for example, for early-career researchers in psychology departments, publications in 'top' journals are typically valued more highly than publications in other outlets.",
            "While authorship conversations can be difficult at times, the authors recommend having them early in order to set expectations for all members of the team (Eggert, 2011).",
            "To divide tasks efficiently, the team should have an understanding of each person's capacities and how they would like to use them in a particular project, and teams can start by creating a list of the skills needed for the project at hand.",
            "To generate a skills list, teams might broadly map out each phase of a project, such as idea generation, sample selection, research design, data collection, data analysis, and dissemination, and then fill in each phase with the required skills.",
            "Teams might assess where there may be gaps in their collective skill set by performing a study 'premortem,' imagining a scenario in which their project fails to meet its intended aims (Klein, 2007).",
            "As a matter of ethical concern, teams should strive to represent a diversity of experiences and identities as much as possible, because academic psychology has systematically excluded people of color, low-income people, and other marginalized groups.",
            "Researchers can expand teams by creating paid positions specifically focused on recruiting people from underrepresented groups, for example by writing funding into existing grants or working with programs like SPSP's Social-Personality Undergraduate Research (SPUR) Program or the NSF's Research Experiences for Undergraduates.",
        ],
    ),
    "matrix": (
        "The Logistics of Working in Teams",
        "Take charge of the operational handbook for a large, newly formed research team. Establish roles and a leadership structure, set communication norms, adapt the research process for a community partner organization, and write a conflict-resolution protocol that handles authorship disputes and power dynamics fairly.",
        "A control-room dashboard with four panels: 'Roles & Leadership' showing an org chart, 'Communication' showing email and Slack threads with an agreed cadence, 'Research Process' showing a community partnership flowchart, and 'Conflict' showing a mediation staircase ending at a university ombudsperson's office door.",
        [
            "Each person on the team should have a clear set of tasks that they will be responsible for, and it can be useful to establish specific roles, especially regarding leadership.",
            "The larger the team, the more critical it is to have people who are in charge of high-level co-ordination of the project, such as assigning responsibilities, assessing the progress of team members, setting up meetings, and establishing a timeline.",
            "Regardless of the scope of the project or the size of the team, it is critical to have a clear leadership structure and to make sure that all team members are aware of and in agreement on that structure.",
            "Although teams may require a few members to take on leadership roles, all team members should ideally feel comfortable asking questions and contributing ideas.",
            "In a team science model, leaders should instead seek out opportunities to include others in the decision-making process and provide rationale for any major decisions.",
            "Team members should all agree on a mode or modes of communication and set expectations about when and how often to communicate, for example whether to meet monthly over Zoom and whether progress updates should go to leaders or the whole team.",
            "In many cases of collaboration, the steps of the research process closely resemble those of a more traditional, small-scale project, with teams assembling already having a specified research question and hypothesis.",
            "Partner organizations have an intimate knowledge of their processes and of the communities they serve that they can contribute to the collaboration, so partners (and participants) may feel excluded from the research process if academics approach them with a preset agenda that has no room for their goals.",
            "Whereas many researchers are interested in answering theoretical questions, organizations are typically far more driven by practical questions, which may result in a misalignment of goals on the team.",
            "Conflict can arise at any stage of the process, from deciding on authorship order to interpreting findings, and these conflicts often stem from poor communication, unclear expectations, or misalignment of goals.",
            "When conflict arises, the best course of action is often to facilitate an open discussion, which authors can do by approaching one another one-on-one, calling for a group discussion, or trying to bring in a neutral party to aid in the conversation.",
            "More junior members of the team may not feel as comfortable advocating for themselves, so more senior team members should be acutely aware of power dynamics and, when necessary, create anonymous ways for team members to share their concerns, such as involving a university ombudsperson.",
        ],
    ),
    "boss": (
        "The Promise of Team Science",
        "Deliver the closing keynote: synthesize why diverse, interdisciplinary team science matters and what it requires beyond adding more people. Lay out the core principles from Table 4.1 and the field-level norm changes (hiring, promotion, credit) needed for team science models to become more commonplace, ending with the impact case.",
        "A stadium stage with the African proverb 'If you want to go fast, go alone; if you want to go far, go together' projected behind the speaker. As the talk progresses, a wall of solo publication counts collapses and is rebuilt as a mosaic of shared contributions, labeled 'access, inclusion, communication, roles, cooperative decisions.'",
        [
            "Team science models can be implemented in social and personality psychology in a number of ways, from lab teams to cross-sector teams.",
            "Regardless of the size or scope of the collaboration, we can benefit from expanding our teams to include people from different backgrounds, disciplines, and perspectives.",
            "Working in teams provides us with a larger toolkit and greater capacity to address bigger and more impactful questions.",
            "Conducting team science is not just about working with a larger number of people, but also about implementing certain principles in our work, including promoting access and inclusion as we build our teams, creating open and honest channels of communication, and establishing clear roles and expectations for team members.",
            "By engaging in this type of science, we maximize our potential for learning by tackling more ambitious research questions and by engaging with team members who think differently about scientific and social issues.",
            "In order for team science models to become more commonplace in social and personality psychology, we must also push to change the norms in our field to place greater value on collaborative work instead of primarily focusing on individual accomplishments.",
            "Changing field norms requires assessing people's contributions to science in a more holistic way, for example by changing our hiring and promotion practices to value different types of contribution to projects rather than counting first-author publications.",
            "Most researchers in social and personality psychology seek to have an impact in their careers, whether on the field itself or in the world more broadly.",
            "Diverse team science can bring us closer to this goal by helping us add nuance to our questions, expand our methods and theories, and improve the validity and generalizability of our research.",
            "The benefits of a team science approach are not automatic; creating larger teams does not mean that those teams will necessarily be better or more diverse, and increasing diversity requires deliberate efforts.",
            "Team science approaches create new opportunities for expanding access to research, and these collaborations can help us increase our toolkit to include methods like field studies that many of us may not be exposed to in our traditional training (Paluck & Cialdini, 2013).",
            "Engaging in interdisciplinary collaborations can also be mutually beneficial, because just as psychologists can learn new methods from other researchers, researchers from other fields can also expand their toolkits through partnership with psychologists.",
        ],
    ),
}
