# -*- coding: utf-8 -*-
CHAPTER = {
    "num": 0,
    "title": "Introduction",
    "authors": "Tessa West, Harry T. Reis, and Charles M. Judd",
    "domain": "Research Methods | Science of Methods",
    "scrub": (
        "The Third Edition of the Handbook",
        "Your mission is to introduce a newcomer to the Handbook of Research Methods in Social and Personality Psychology by explaining why a third edition exists, what it promises, and how it differs from the earlier editions. Walk through the book's purpose, the decision process behind topic selection, and what readers can expect from the current chapters.",
        "You stand at a bookshelf in a campus office, holding the thick third edition while the faded 2000 and 2014 volumes sit open on the desk. A browser on the desk screen shows the Cambridge University Press website listing freely available chapters from the second edition.",
        [
            "The Handbook of Research Methods in Social and Personality Psychology is now in its third edition.",
            "The first two editions of the handbook were published in 2000 and 2014.",
            "The first two editions of the handbook played an important role in widening access to and utilization of cutting-edge methods in the field.",
            "The science of personality and social psychology never sleeps when it comes to developing new and improved research methods.",
            "The third edition was designed to capture some of the most influential and promising new methodological advances in the field.",
            "The third edition covers both traditional methodological topics that have seen advances in recent years and novel approaches of recent vintage.",
            "The editors chose content they believed would be most relevant to the largest proportion of new scholars in the field.",
            "Topics omitted from the third edition are not necessarily less important than the ones included.",
            "With the help of Cambridge University Press and the consent of the authors, several still-timely chapters from the second edition were made freely available on the publisher's website.",
            "The freely available chapters from the second edition should be considered essential elements in a survey of the field's methodological state of the art.",
            "The freely available chapters from the second edition might well be incorporated into a methods-course syllabus.",
        ],
    ),
    "dialogue": (
        "Methods and Theory: Two Sides of the Same Coin",
        "Your mission is to explain how methods and theory feed each other, using Greenwald's observations about Nobel awards and Lewin's famous dictum as anchors. Show how new methods open doors to questions and how a good theoretical question should lead the researcher, not a trendy method.",
        "You sit across a table from a skeptical senior scholar, a shiny coin resting between you with 'method' on one face and 'theory' on the other. Over your shoulder, a chalkboard carries Lewin's dictum and a chart of relationship research timelines marked by multilevel modeling breakthroughs.",
        [
            "Methods are the bread and butter of science: more than just defining what is possible, they suggest what can be learned.",
            "Much of what appears in journals today asks questions that could not have been imagined, much less investigated, by earlier researchers.",
            "Tony Greenwald's 2012 observation that there is a much greater frequency of Nobel science awards for contributions to method than for contributions to theory still rings true.",
            "Methods open the door to questions, and questions make it possible to advance theory.",
            "The methods in the handbook are not intended to replace theories, but rather to provide a guide to optimally test them.",
            "Most chapters in the handbook toggle between theory and method, presenting them as two sides of the same coin.",
            "The history of psychology is full of examples of theories advancing with the advent of new methods, and vice versa.",
            "Relationships scientists were able to develop and test complex theories of how partners influence one another over time once advancements were made in multilevel modeling generally, and dyadic analysis more specifically.",
            "Those advances in multilevel modeling and dyadic analysis happened out of necessity, once scholars realized the importance of handling issues such as nonindependence of data properly.",
            "Without properly handling nonindependence of data, it was easy to make mistakes in drawing conclusions from the data.",
            "Leading with a good theoretical question, especially one that may lead to useful applications, is good practice.",
            "Methodological approaches change all of the time, but, to quote Lewin's well-known dictum, there is nothing so practical as a good theory.",
        ],
    ),
    "audit": (
        "Taking Measurement Into the Field",
        "Your mission is to audit how psychophysiologic measurement has moved out of the laboratory and into everyday settings. Catalogue what new tools enable researchers to measure, where the measurements now happen, and what big questions the age of massive data has made testable.",
        "You sit in a sunlit park café, auditing a researcher's field kit: a smartwatch recording cardiovascular data, a phone app with dashboards, and a tablet streaming live heart-rate traces from a participant jogging past the fountain. A map pins study sites from the classroom to the operating room.",
        [
            "Advances in psychophysiologic measurement have enabled researchers to move beyond the lab to the field to collect cardiovascular data using watches and phone apps.",
            "Questions such as how basic stressors impact people's health across multiple social contexts and in multiple countries can now be studied in a more ecologically valid manner.",
            "With psychophysiologic tools being widely available, more and more researchers can now think even bigger about the contexts in which they can study physiological processes, from the classroom to the operating room.",
            "Since the prior edition of the handbook, the age of massive data began, a point made clearly in Kosinski's chapter in this handbook.",
            "Scholars can now test big questions with huge multinational samples, such as how emotions spread throughout social networks.",
            "Massive data now allow scholars to test questions such as who we are attracted to and what gives rise to misinformation contagion.",
            "Parts I and II of the handbook introduce readers to basic issues in the science and design of research.",
            "Parts I and II of the handbook might be considered what you need to know before starting research.",
            "Parts III and IV of the handbook introduce the reader to new methodological and statistical procedures while considering the role of theory development in their application.",
            "The handbook urges readers to ask whether a proposed method will be the best available to test their question.",
            "The handbook urges readers to ask whether an analysis strategy will allow them to ask what they need to ask to advance their theory.",
        ],
    ),
    "matrix": (
        "Navigating the Handbook's Architecture",
        "Your mission is to map the four parts of the handbook onto the stages of a researcher's journey, from first-year graduate student to data analyst. Explain what each part covers, in what order it should be read, and why the later parts are organized by breadth rather than sequence.",
        "You stand before a large four-column wall chart, each column a part of the handbook color-coded to a stage of a researcher's journey, from a student's first lecture hall to a laboratory bench where data analysis is underway. Arrows show Parts I and II as a fixed path and Parts III and IV as modular detours.",
        [
            "When deciding how to organize the handbook, the editors adopted the perspective of a new researcher with little experience conducting or running studies.",
            "The handbook is designed to guide the reader from the earliest stages of thinking about research, when foundational issues of ethics and replication are top of mind, through the design, implementation, and analysis stages.",
            "The handbook deliberately starts out broad, addressing big-picture issues relevant to all new scholars interested in the study of personality and social psychology, regardless of topic.",
            "The first part of the handbook, foundational issues in psychological science, covers basic issues around ethics in conducting research, replication, how to conduct team science, and how to conduct research that captures multicultural and multinational samples.",
            "The editors recommend reading the first part of the handbook first, and it requires no prior knowledge or expertise in conducting experimental research.",
            "The second part of the book, basic methodological considerations, covers the basics of design and validity, beginning with essential concepts of validity and experimentation.",
            "The second part of the book moves on to quasi-experimental design and field methods, which take the researcher out of the lab and into uncharted real-world territory.",
            "The third part of the handbook assumes a basic knowledge of experimental method and design, along with consideration of ethics and replication.",
            "In Part III, the authors provide a deep dive into several popular methodological approaches at the forefront of cutting-edge research.",
            "Part III chapters need not be read in order, but rather can be turned to as the researcher begins to think through different methodological options.",
            "The fourth and final part is aimed at the reader who has designed a study and collected the data, and is now ready for data analysis.",
        ],
    ),
    "boss": (
        "Keeping Up in an Era of Rapid Change",
        "Your mission is to advise a novice researcher on how to stay afloat as methodological and statistical advances accelerate. Weigh the promise of generative AI, machine learning, and data-driven approaches against the risk of running code without understanding it, and defend why the classic building blocks still anchor the field.",
        "You sit at a curved control desk in a dim data center, wall screens streaming live feeds of AI-generated survey items, R and Python code windows, and neural-net training curves. A junior researcher in the chair beside you watches a chatbot draft a results section, looking both awed and adrift.",
        [
            "One challenge all researchers face is that methodological and statistical advances are happening at a rapid, and perhaps expanding, pace.",
            "The three editors struggled to create a handbook that is both cutting-edge in the approaches covered and likely to stand the test of time.",
            "The editors' goal is to expose the reader to as many methods as possible while also covering the tried and true principles of methodological skill building.",
            "As the handbook was being finalized, the advent of generative AI happened.",
            "AI tools will shape not only the types of question scientists can ask, but also how they go about developing materials, collecting and analyzing data, and even writing up scientific findings.",
            "Issues of ethics will surely come up as generative AI tools develop.",
            "Machine learning and computational modeling, topics covered in Part IV, allow scholars to examine dynamic processes that unfold naturally over time.",
            "Using data-driven statistical approaches can help circumvent some of the ethical issues around questionable research practices that have entered the zeitgeist since the prior edition of the handbook.",
            "Most analyses these days are conducted using packages in R, Python, MPlus, and SPSS, many of which can be run with little knowledge of what is going on under the hood.",
            "It can be all too easy to run code without knowing what it does, and fighting this temptation is essential as you develop your methodological and analytical skills.",
            "The classic issues of psychometrics and study design, such as principles of construct validity and scale construction, are essential to learn during this time of constant change.",
            "Classic knowledge of psychometrics and design will anchor your understanding of methodological developments and give you a more critical eye when encountering something new.",
        ],
    ),
}
