# -*- coding: utf-8 -*-
CHAPTER = {
    "num": 11,
    "title": "An Office and a Gentleman",
    "authors": "Sam Gosling",
    "domain": "Snoop | Workplaces",
    "scrub": (
        "Scrub the Office: Charles Gibson's Books, Desk and the Really-Must-Get-Around-To-It Personality",
        "Your mission is to scrub through the playhead of Charles Gibson's office: rewind past the bookshelves where the spines are not lined up neatly and the books sit in no obvious order, glide over the desk with the rubber bands outside their container, the desk calendar not updated for twenty days, the pens only partly in the jar, the half-closed filing drawer and the Post-it notes out of reach, then rest on the inbox holding a green baseball hat and the row of grocery boxes full of files and papers. End the scrub on the emerging picture of an I-really-must-get-around-to-that personality whose actions typically lag behind his good intentions.",
        "A playhead glides over a wide office scene: a bookcase with spines at odd angles, a desk with a calendar showing yesterday's date and a pen jar half empty, an ajar filing drawer, Post-it notes beyond arm's reach, an inbox cradling a green baseball hat, and a row of cardboard grocery boxes stuffed with papers.",
        [
            "The apparent variety of books on Charles Gibson's shelf caused Gosling to raise his estimate of Gibson's level of openness, making him probably a little less conventional than some of the books might suggest.",
            "Gibson's books appeared to be on the shelves in no particular order, not arranged by topic, author's name, or jacket color, which suggested to Gosling that he followed the most-recent-ones-on-the-top rule.",
            "Because the spines of Gibson's books were not lined up neatly and most of the books were simply in the bookcase, Gosling set his initial estimate of Gibson's organization to medium-low.",
            "Gibson's desk showed evidence of his organizational style: the rubber bands were not in the rubber-band container, the daily desk calendar hadn't been updated for twenty days, and only some of the pens were in the pen jar.",
            "The filing drawer in Gibson's desk was not closed fully, and Gosling reasoned that a true neat freak would be unable to focus on what he's doing with a half-closed drawer in his peripheral vision.",
            "Gibson had the trappings of organization, such as a desk organizer with a rubber-band section, a calendar, and a pen jar, so Gosling concluded that he cares about order but just didn't execute it in the way intrinsically organized people do.",
            "The Post-it notes on Gibson's desk were out of reach, which suggested that at heart he does have organizational aspirations and does see the value of being organized.",
            "Gosling suspected Gibson is a sporadic organizer, someone who lets things get out of hand and embarks on a major clean-up when the mess is no longer tolerable.",
            "The inbox on Gibson's desk contained a green baseball hat and was otherwise empty, and on the basis of the hat-holding function of the box, along with the other evidence, Gosling guessed the inbox goes unused.",
            "Gibson's character configuration seemed to be an I-really-must-get-around-to-that personality, in which his actions typically lag behind his good intentions.",
            "The row of grocery boxes full of files and papers along Gibson's wall might have meant he was in the midst of getting organized, but a deeply organized person would find a permanent place for things and might even use special organizing boxes with color-coded tabs.",
            "The two paintings in Gibson's office, a blown-up detail of a painting he has at home and a framed painting of a building at Princeton University, were neither of them hung up, and for Gibson, like many of us, that was good enough.",
        ],
    ),
    "dialogue": (
        "Dialogue with the Office Snooper: Mike Barz, the Sediment of Sentiment and Social Snacking",
        "Your mission is to stage a dialogue with the Snooper-in-Chief: ask how Mike Barz's sparse, functional office with its scrunched-up wires and empty bookcase compares with Gibson's, how the framed family photos on the windowsill face the visitor rather than Barz himself, how the dozen pictures of his children pinned in a narrow vertical column on the bulletin board suggest a man who hungers not for food but for connection, and how Wendi Gardner's experiments with photos of friends versus celebrities prove that social snacks soften the pain of social isolation and that as many as 85 percent of adults keep photos or mementos of loved ones on their desks.",
        "A talk-show set with two chairs: one holds a psychologist with office floor plans, the other a curious host, while a wall screen flashes a sparse office with scrunched-up lamp wires, family photos arranged on a windowsill, a bulletin board with a vertical column of children's pictures, and a lab scene showing a friend photo and a celebrity photo beside a mood chart.",
        [
            "When Gosling compared photos of Gibson's office with those of Mike Barz's, he was struck first by how sparse Barz's office is, which suggests someone whose perspective is more functional than aesthetic.",
            "The unsightly but highly efficient scrunched-up wires at the foot of Barz's lamp showed few attempts to make the space pleasing to the eye, and his empty bookcase suggested that Barz is a more concrete, conventional person than Gibson.",
            "Barz's office was adorned with pictures of him, his kids, and his wife, while Gibson's office had not one family photo, which suggested that Barz maintains less separation between his work self and his home self than Gibson does.",
            "The nicely framed family photos on Barz's windowsill, in which everyone was beaming beautifully at the camera, were placed so that a visitor sitting across from Barz would see him flanked by the photos of his wife and kids in the background, making them classic other-directed identity claims.",
            "On the bulletin board to his left, Barz displayed about a dozen pictures of his children pinned in a narrow vertical column running down the right rim, an unbalanced display that Gosling realized was arranged so Barz could see the photos as he works.",
            "Gosling concluded that Barz is a snacker, but he doesn't hunger for food, he hungers for connection with his family, and the photos are social snacks that tide him over until he can reconnect with his loved ones in person.",
            "Wendi Gardner, a professor at Northwestern University, has studied social snacking and has provided compelling evidence that psychological snacks such as photos in wallets and letters from lovers soften the pain of social isolation.",
            "In Gardner's clever set of studies, participants who recalled an experience of being rejected while looking at a photo of a friend did not experience the drop in mood that occurred for the people who had a picture of a favorite celebrity in front of them.",
            "The buffering effect of social snacks was specific to feelings about being separated from others, because when Gardner had participants recall a failure instead of a rejection, all the participants felt equally bad regardless of whether they had photos of celebrities or friends in front of them.",
            "According to Gardner, as many as 85 percent of adults have photographs or mementos of loved ones on their desks at work or in their wallets.",
            "Loneliness has been linked to a host of serious health problems, from poor sleep and cardiovascular disease to compromised immune systems and increased blood pressure.",
            "Reminders such as photos, wedding rings, or e-mails from intimate others can fend off isolation and enhance well-being and productivity.",
        ],
    ),
    "audit": (
        "Audit the Aspirations: Good Intentions Gone Bad and the Aspired Self",
        "Your mission is to audit the ledger of failed resolutions: check off the unopened package of swimming goggles collecting dust behind the desk, the out-of-date schedule for water aerobics classes, the recently expired gym membership card, and the impressive but unused haul of stuff from Staples, then audit the University of Texas moving study where the new offices still held color-coded files arranged willy-nilly and Post-it notes still in their packets. Close the ledger on the aspired self, the distinction between those disorganized people who wish they weren't and those who don't care, and the rule that real change only shows up clearly at times of major life change.",
        "An audit ledger stamped over an office: checkmarks land on a package of swimming goggles behind a desk, a faded water aerobics schedule, an expired gym card and a bag from Staples, while a card shows an old office and a new office with identical willy-nilly color-coded files, and a mirror card reflects an aspired self.",
        [
            "Good intentions gone awry are all those things we say we ought to do but, given our personalities, we don't, such as get in shape, get organized, or take time to relax.",
            "A good snooper would unearth evidence of these failed resolutions in the unopened package of swimming goggles collecting dust behind the desk, the out-of-date schedule for water aerobics classes, and the recently expired gym membership card.",
            "Optimistic but unrealistic office organizers give themselves away with an impressive but unused haul of stuff from Staples, because accumulating evidence for these aspirations is easy but carrying them out is hard.",
            "When the psychology department at the University of Texas moved into a new building, Gosling conducted a small study to see whether people would really be true to their aspirations, examining the old offices before the move and the new offices afterwards.",
            "In the new offices the evidence was all there that the chasm was too great between people's aspirations and the lifestyle dictated by their personalities, with color-coded files arranged willy-nilly, Post-it notes still in their packets, and business cards stuffed randomly into a box.",
            "The personality impressions of observers who saw only the old offices correlated strongly with the impressions of observers who saw only the new offices.",
            "Most people did show a bit of progress in organizing their new offices, starting out by making logical use of the folders and labels and boxes, but after a while things began to break down.",
            "An unrealized relaxer might have stocked up on scented candles, foot massage cream, bath oil, and an iPod playlist titled Soothing Sounds, but you'll find the jar of cream still nearly full, the candles hardly used, and the gentle songs missing from the most-played list.",
            "Real change is possible, but it's hard to achieve because you have to contend with your underlying biological predisposition as well as the pressures and daily obligations you have built into your routines.",
            "Personality change is most clearly seen at times of major life change, and conscientiousness tends to increase when parenthood and professional duties demand that you ramp up the responsibility levels.",
            "The concept of an aspired self helps distinguish those who are disorganized but wish they weren't from those disorganized folks who are not bothered by it.",
            "Knowing whether a disorganized person appreciates organization can guide everyday interactions, such as whether to clean up your office when hosting a meeting or to run a loosely structured meeting that goes with the flow for someone who couldn't care less.",
        ],
    ),
    "matrix": (
        "Matrix Match: Maps, Absences and the On-the-Fly Yardstick",
        "Your mission is to build a matrix mapping office clues to their meanings: drop the map pinned next to the printer into the OPEN-MINDEDNESS cell and then flag it as dampened because the map depicted Afghanistan and Gibson needed it for business reasons, drop the reproduction paintings into the slightly-elevated OPENNESS cell, and drop the burned-down candle with bath salts and exfoliating gloves into the VALUES RELAXATION cell. Then place the absence cards: the empty wall, the bare windowsill, and the mantelpiece with no photos, and finish with the yardstick card showing an office whose four postcards would have been among the most decorated in a retail bank but looked anemic inside the advertising agency.",
        "A wall matrix of cells: OPEN-MINDEDNESS, OPENNESS, ABSENCE and YARDSTICK; cards fly into place, a map of Afghanistan beside a printer with a dimmed light, a reproduction painting, a burned-down candle with bath salts and an eye mask, an empty wall with a dashed outline, and a postcard-covered wall shown twice, vibrant next to a bank logo and pale next to an ad agency logo.",
        [
            "Gosling's research shows that maps tend to be kept by people with diverse interests and are a clue to open-mindedness.",
            "The map in Gibson's office depicted Afghanistan, and because it was pinned right next to the printer where it could easily be referred to rather than in a spot that favored getting lost in reverie, it seemed to be there for business reasons, which would dampen the clue's diagnosticity for open-mindedness.",
            "Gibson's paintings were a bit unusual but they were reproductions, not originals, which suggests an interest in the arts and signifies someone only slightly elevated on the trait of openness.",
            "It is as important to pay attention to what is absent in a room, such as an empty wall, a bare windowsill, or a mantelpiece with no photos on it, as it is to note what is there.",
            "When weighing the significance of a blank wall or a clear surface on top of a filing cabinet, a snooper should look around at other similar spaces that can act as an on-the-fly yardstick.",
            "An office with four postcards on the wall along with some stickers and a couple of posters would have been among the most decorated retail-banking offices, but in the building housing the advertising agency its decor appeared positively anemic next to the extensive decoration in the neighboring offices.",
            "A good snooper must be sure about the provenance of objects before drawing conclusions, so the Princeton painting could have meant Princeton was Gibson's alma mater or that his daughter was a student there or that a guest on the show had given the picture to Gibson.",
            "Gibson referred to his time at Princeton twice when he appeared on the show, and it was clear that his memories of that experience continue to be integrated into his sense of who he is.",
            "In the offices the researchers studied there were plenty of symbolic ties to moments, places, and groups from the past, including a small Hungarian flag pinned to the wall above a desk and a crystal glass sphere with three Greek symbols announcing an ongoing allegiance to a sorority.",
            "A burned-down candle on a bathroom shelf accompanied by other candles in a similar state, a jar of bath salts, an eye mask, well-worn exfoliating gloves, and residue of wax around the bathroom is a good sign that the person values taking time to relax and actually does it.",
            "Candles alone are not enough to signify their owner likes to relax, because as Quirk 2 taught us, cues derive part of their meaning from other cues.",
            "If Gibson's books proved unread, he might be an unrealistically optimistic planner who is busy but should calibrate his book acquisitions accordingly, or he might have a collection of unread books on a bookshelf to create a good impression.",
        ],
    ),
    "boss": (
        "Boss Level: Read the Office, Read the Need to Belong",
        "Your mission is to defeat the final boss, the reading of sociability from office decor: first score Barz's office where every photo and poster depicts a person, the comfortable chair and sofa with cushions, and the family photos arranged for himself to see, then face the science of the need to belong, the need to affiliate, and Mark Leary's findings that people with a strong drive to belong form bonds easily and are reluctant to break them. Finish with the handshake test: Barz looked, Gibson looked away, and the door to the next chapter, where spaces are designed from scratch to match the occupant's personality.",
        "A boss arena shaped like a two-man office face-off: on one side a desk with a chair and sofa, photos of faces on every wall and a bulletin board column of children's pictures, on the other an empty wall with a map and a propped painting, while a banner unfurls listing need to belong, need to affiliate, hello and good-bye rituals, and a handshake freeze-frame where one man meets the eyes and the other looks away.",
        [
            "In Barz's office, every photo and poster depicted a person, which suggested he is extraverted, while introverts tend to display fewer depictions of people and go for a quiet landscape or a still life.",
            "If introverts do display portraits they are often of calm, restful people, and an introverted graduate student of Gosling's adorned her walls with pictures of doors.",
            "Extraverts are so drawn to other people that they are more likely than introverts to prefer music with vocals, and Barz's comfortable chair and sofa with cushions further supported his extraversion.",
            "As was seen in chapter 8, an inviting office layout is implicitly designed to encourage people to come in and linger, even though it is not a conscious strategy.",
            "The photos in Barz's office and their arrangement suggest that he is especially concerned with social connectedness, and people vary in how much they have this need to belong, though we all have it to some extent.",
            "In our evolutionary past we needed a mechanism that ensured individuals stayed near one another, because without group cohesion people might wander off, diminishing the integrity of the group and leaving its members unprotected.",
            "The need to affiliate is associated with extraversion, and people high on this trait tend to be sociable, enjoy interacting with others, and have more close friends and a more active social life than people low on this need.",
            "People high in the need to affiliate also tend to be higher on the trait of agreeableness and disclose more about themselves, a difference Gosling noticed between Barz and Gibson even during his brief encounter.",
            "Crucially, people high in the need for affiliation are unhappier when they are alone than people low on this need, and they are more dependent on others.",
            "According to David Winter's analysis of his inaugural address, George W. Bush is unusually high on the need for affiliation.",
            "Mark Leary at Duke University found that people with a strong drive to belong form social bonds easily, are reluctant to break bonds even if those bonds are no longer needed or cause them pain, and become more distressed than others when relationships end.",
            "People with a strong need to belong engage in hello and good-bye rituals, like to interact just for the sake of it, spend lots of time thinking about their relationships, and are particularly attentive to social cues.",
        ],
    ),
}
