# -*- coding: utf-8 -*-
CHAPTER = {
    "num": 12,
    "title": "Bringing It Home",
    "authors": "Sam Gosling",
    "domain": "Snoop | Home and Self",
    "scrub": (
        "Scrub the Refrigerator: The Regimented Beverages, the Backup Hoard and the Mystery That Confounded the Snooper",
        "Your mission is to scrub through Gosling's own private mystery box: rewind to the visitors who find his refrigerator amusing enough to whip out their camera phones, the shelves of perfectly regimented beverages, the beers and sodas stretching in perfect rows, the mixers on the next shelf, the bottled water, Red Bull, fancy lemonade and Guinness up top, the door compartments full of wine, champagne, cider and backup beers, and the tall cupboard of backup hoard standing by for replenishment emergencies. End the scrub on the oddity that his OCD tendencies stop at the refrigerator door, his desk in disarray and his bathroom cupboard organized by the order items were chucked in, a mystery not even his snooping research could solve until he met a man named Chris Travis.",
        "A playhead glides over a kitchen scene: a refrigerator door swings open to reveal shelf after shelf of perfectly regimented drink bottles, a tall cupboard of backup beverages stands nearby, a guest heads for the bathroom while the owner darts to the cupboard to restore balance, and a desk in disarray with a messy bathroom cupboard fades in behind, with a question mark hovering over the fridge.",
        [
            "On more than one occasion visitors to Gosling's apartment have been sufficiently amused by what they found inside his refrigerator to whip out their camera phones.",
            "There are no gory body parts or rare wines in Gosling's fridge; it is the arrangement of items that grabs visitors' attention.",
            "When you open Gosling's refrigerator door, you face shelves and shelves of perfectly regimented beverages, with the bottom shelf holding several different kinds of beers and sodas stretching in perfect rows all the way to the back.",
            "On the next shelf of Gosling's fridge are the mixers, small bottles of tonic, soda, ginger ale, tomato juice, V8, and orange juice.",
            "The top shelf of Gosling's refrigerator holds the bottled water, Red Bull, fancy lemonade, and Guinness, and the row leaves at least half a shelf for all the other things people ordinarily store in refrigerators.",
            "The door compartments of Gosling's refrigerator are full of wine, champagne, cider, larger bottles of water, and backup beers.",
            "The drinks in Gosling's refrigerator are not for show, because his guests and he do consume them, but the shelves are rarely less than fully stocked.",
            "Right next to Gosling's refrigerator is a tall cupboard that contains his backup hoard, always on standby for replenishment emergencies.",
            "Gosling will casually offer someone a drink and affect a calm demeanor, apparently unfazed that the ginger ale row is now one bottle short, but as soon as the guest takes a bathroom break he heads straight to the storage cupboard and restores balance to his beverages.",
            "What makes Gosling's arrangement particularly odd is that his OCD tendencies stop at the refrigerator door, because his desk is typically in disarray and the organization of items in his bathroom cupboard is determined by the order in which they were chucked in there.",
            "Even the snooping Gosling did while researching and writing this book did not shed light on his strange beverage behavior, and the fridge has always puzzled him.",
            "It was not until Gosling met a man named Chris Travis that he began to solve the mystery of his chilly little universe, learning that the unique needs we seek to satisfy with our physical spaces are rooted deeply in our past experiences.",
        ],
    ),
    "dialogue": (
        "Dialogue with the Truehome Builder: Chris Travis, the Round Top Epiphany and the Three Levels of Personality",
        "Your mission is to stage a dialogue with Chris Travis: ask the builder and designer who heads up an architecture firm how he recognized the connections between his work and Gosling's snooping studies, how over the last twelve years he developed the Truehome workshop to integrate emotional and psychological associations into house design, and how he takes identity claims, self-regulators, and behavioral residue to the extreme by considering personalities so early in the design process that the house fits the occupants. Then press him on the winter of 1992 in Round Top, Texas, bankrupt and strumming his guitar in a rocking chair, overcome by warmth, wellness, and tranquility, remembering his great-grandfather's house and the old man's knee, and how that epiphany revealed that our emotional well-being depends on how well our surroundings match our ingrained psychological needs.",
        "A talk-show set: one chair holds a psychologist, the other a builder and designer, while a wall screen flashes a guitar and a rocking chair on a Texas balcony, a restored old house, a boy on his great-grandfather's knee, and a diagram of Dan McAdams's three-tiered system with Level 1 traits, Level 2 personal concerns, and Level 3 identities.",
        [
            "Chris Travis is a builder and designer who also heads up an architecture firm, and he contacted Gosling when he heard about the snooping studies because he recognized the connections between his work and the research.",
            "Gosling is interested in how people's personalities leave their imprint on the spaces in which they live, and Travis is interested in creating homes perfectly matched to his clients' personalities.",
            "Over the last twelve years Travis has been developing an innovative system, which he calls the Truehome workshop, to help people identify their emotional and psychological associations to places and to integrate those associations into the design of their houses.",
            "In a sense, Travis is focusing on the processes Gosling has been studying, identity claims, self-regulators, and behavioral residue, and taking them to the extreme.",
            "Travis does not wait until people move to a new place and then use posters and music and magazines to shoehorn their personalities into it, because he considers people's personalities so early in the design process that he can make the house fit the occupants, not the other way around.",
            "In the winter of 1992, after some disastrous entrepreneurial ventures left him bankrupt, Travis decided to return to what he knew best, renovating old houses, and chose as his base a tiny central Texas town called Round Top.",
            "One evening as Travis strummed his guitar in a rocking chair on the balcony of a house he was restoring, he was surprised to find himself overcome by a sense of warmth, wellness, and tranquility.",
            "Travis recalled sitting on his great-grandfather's knee as the old man rocked back and forth humming a song, and more than three decades later, rocking on the balcony in Round Top, he felt connected to that earlier time when he had felt loved and appreciated.",
            "Travis's realization about the connection between his present feelings and those from a happy childhood memory precipitated an epiphany: that we all develop emotional associations with places that affect how we later respond to our surroundings.",
            "Travis concluded that our long-term emotional well-being can be profoundly affected by how well our surroundings match our ingrained psychological needs.",
            "The Truehome system goes much deeper than conventional question-and-answer exercises and would find out why a client likes trees, whether for seclusion, the sound of wind through the leaves, or childhood memories, because each reason suggests a different architectural solution.",
            "The Truehome method focuses on Dan McAdams's three-tiered system of describing personality, touching Level 2 constructs such as roles, goals, and values, and even delving deeper to matters of identity at Level 3.",
        ],
    ),
    "audit": (
        "Audit the Feeling Plans: Warmth and Companionship, the Claustrophobic Client and the Rift in a Marriage",
        "Your mission is to audit how Travis's psychological perspective gets translated into design: check off the plan where the kitchen is labeled warmth and companionship, the dining area friendship, the pantry abundance, the master bath rejuvenation, the gun room safety and adventure, and the master bedroom privacy, passion, and reflection, then audit the second plan with its different labels, and the clients Jenni and Sanjay, arguing constantly because Sanjay wanted a basement and Jenni had an irrational negative reaction, until the My Family exercise revealed the closets of her childhood trauma and her claustrophobia, which neither spouse had recognized. Close the ledger on the solution of shallow ample closets, windows galore, special furnishings, and the back porch that recalled Sanjay's mother.",
        "An audit ledger stamped over a house plan: checkmarks land on a kitchen labeled warmth and companionship, a pantry labeled abundance and a master bedroom labeled privacy, passion, and reflection, a red flag lands on a basement, a file card reads claustrophobia traced to childhood closets, and a drawing shows shallow closets, windows galore and a large back porch.",
        [
            "When Gosling visited Travis and looked at some of the plans he had created for his clients' houses, he quickly saw how his understanding of the functions of a living space differs from that of a conventional architect.",
            "Whereas a conventional architect might use labels such as family room, back porch, and master bedroom, Travis's labels denote the feelings each space must evoke for the home's owners.",
            "On one plan Travis's kitchen was labeled warmth and companionship, the dining area friendship, the pantry abundance, the master bath rejuvenation, and the master bedroom privacy, passion, and reflection.",
            "Travis's designations are customized for each client, as another plan labeled the kitchen central and functional, the rear porch invitation to beautiful vistas, and the master bedroom tranquility heaven.",
            "Travis does not view homes simply as places in which to eat and sleep and work; rather, he looks at how they can help provide feelings of safety, social stature, and comfort.",
            "When Travis first met his clients Jenni and Sanjay, they had been arguing constantly about the design of their new home, because Sanjay wanted a basement and Jenni had what seemed an irrational negative reaction to it.",
            "As Travis explored their associations with the basement, it became apparent that Jenni was claustrophobic, and oddly, neither she nor Sanjay realized this even though she literally had to hold her breath when she needed to enter a walk-in closet.",
            "When the couple did Truehome's My Family exercise, it emerged that closets had figured in traumatic experiences that Jenni had suffered when she was a young child.",
            "Jenni took her husband's desire for a basement as evidence that he did not care about her or appreciate her needs, as if he were trying to force her to live through that trauma again, and the impasse was creating a major rift in their marriage.",
            "Once Jenni and Sanjay were able to see the psychological roots of their conflict, finding an architectural solution was possible, so Travis included plenty of shallow but ample closets and fitted the house with windows galore.",
            "Travis designed the space so Jenni could surround herself with her own special furnishings to feel safe and secure, and Sanjay's need for a personal place to hang out and tinker was met by a large back porch that reminded him of loving times with his mother.",
        ],
    ),
    "matrix": (
        "Matrix Match: Shared Spaces, Whose Stuff Is It and the Mixer Wellspring in Gosling's Own Home",
        "Your mission is to build a matrix mapping the challenge of reading homes: drop the card that even couples who have spent many years together may lose sight of each other's likes and dislikes into the SHARED SPACE cell, the card that it's so hard to know who is responsible for what, whether the ghastly living room picture reflects his tastes or hers or an unhappy compromise, into the WHOSE STUFF cell, and the card that snoopers look for a place primarily the province of one person, such as a study or a basement, into the ONE-PERSON DOMAIN cell. Finish with Gosling's own matrix: his grandmother's drinks cabinet, the tonic water and bitter lemon, the rationing of wartime England, the father who added milk to the ketchup, and his adult re-creation of a bottomless mixer wellspring, with the lesson that implicit connections find ways to express themselves in the spaces you create.",
        "A wall matrix of four cells: SHARED SPACE, WHOSE STUFF, ONE-PERSON DOMAIN and IMPLICIT LINKS; cards fly into place, a couple arguing in front of a ghastly living room picture, a study and a basement labeled province of one person, a grandmother's drinks cabinet beside a wartime ration book, and a glass-fronted fridge full of mixer bottles with a question mark over the rows.",
        [
            "In the everyday give-and-take of a relationship, even couples who have spent many years together may lose sight of each other's likes and dislikes.",
            "In Gosling's snooping work, interpreting shared spaces is one of the greatest challenges because it's so hard to know who is responsible for what.",
            "When snooping in a shared home, Gosling wonders whether a ghastly picture in the living room reflects his tastes or hers, or perhaps is just the result of an unhappy compromise suiting neither person well.",
            "When Gosling and his colleagues are snooping, they look for a place, such as a study or a basement, that is primarily the province of one person.",
            "As Gosling reflected on how Travis and his clients resonated with memories of their parents' or grandparents' homes, his mind wandered back to his own experiences at his grandmother's house.",
            "Gosling recalled summers playing in the garden with his brother, dashing into the living room to grab a bottle of tonic water or bitter lemon from the drinks cabinet, because the great tonic fount never seemed to run dry.",
            "Gosling's parents grew up in England during the severe rationing of World War II, when excessive consumption was discouraged, and his father famously added milk to the ketchup when it got low so the family could extract every last dreg.",
            "Now as an adult, without quite realizing it, Gosling has re-created his own bottomless mixer wellspring in the perfectly stocked refrigerator that so amuses his visitors.",
            "Gosling doubts he would think of mentioning his deep-rooted need for abundance to a conventional architect, but he is sure it would have emerged with Travis's expert probing.",
            "Not everyone can have a house custom designed for them, but many of these implicit connections will find ways to express themselves in the spaces you create, even if you're not quite sure what it is that's driving your preferences.",
            "When one of Travis's clients fondly recalled sitting in an adult chair where her feet couldn't touch the ground, he responded by building in a kitchen counter for high stools so she could swing her legs as she did when she was a child.",
            "Being aware of the principles that Travis employs will direct you, as it did Gosling in the case of his refrigerator, to ask the right questions about the psychological functions that spaces serve.",
        ],
    ),
    "boss": (
        "Boss Level: Snoop Dreams, the Leaking Personality and the Frontier of Human Behavior",
        "Your mission is to defeat the final boss, the closing lessons of snoopology: first master the idea that we have come full circle, from leaving personality footprints on spaces to learning how spaces can be crafted to realize our personality potential, then face the power of snooping to uncover truths about friendliness, flexibility, orderliness and originality that are hard to detect any other way, and the fundamental need to size people up as mates, job candidates, or closet-dwellers. Then tour the closing banner: personalities inextricably linked to the places that surround us, the clues we leave with every poster, coffee cup and album download, the true personality that inevitably leaks out, the tools that turn an ordinary observer into a savvy snooper, and the new frontier of wallets, purses, suitcases, Facebook wall posts, pets, tattoos, cocktails, and vacation spots.",
        "A boss arena that is a hallway of mirrors with a banner reading Snoop Dreams: one side shows a poster hung on a wall, a coffee cup tossed in the trash and an album downloaded from iTunes, the other shows a sharp-eyed sleuth reading a person, while a frontier map unfurls listing wallets, purses, suitcases, Facebook wall posts, pets, tattoos, cocktails and vacation spots.",
        [
            "Gosling says we have come full circle, from discovering how we leave personality footprints on the spaces we inhabit to learning how spaces can be crafted to realize our personality potential.",
            "When it comes to the most essential pieces of our personalities, from friendliness and flexibility to orderliness and originality, snooping has the power to uncover truths about us that are hard to detect in any other way.",
            "So much of living life successfully involves getting to know what people are like, which is why we have been endowed with a fundamental need to figure others out.",
            "We size people up as prospective mates, decide whether they've got the goods for a particular job, or even deduce what kind of closets would suit them best.",
            "Our personalities are inextricably linked to the places that surround us, and every time we hang a poster on a wall, toss a coffee cup in the trash, or download another album from iTunes, we leave clues about who we are.",
            "We broadcast our traits and values, our goals and identities for people to see and perhaps to judge, and although we may attempt to arrange our stuff to outfox others, our true personalities inevitably leak out, especially under the scrutiny of sharp-eyed sleuths.",
            "A core goal of the book has been to provide the tools that will turn you from an ordinary observer into a savvy snooper.",
            "Snooping gives all of us unique insights into ourselves and sharpens our perceptions of others, something that has been overlooked by a century's worth of psychological research.",
            "Your enriched knowledge of how people relate to their spaces, deliberately and inadvertently, will help you investigate domains of expression that have yet to be studied scientifically, from the contents of wallets, purses, suitcases, or Facebook wall posts, to preferences for pets, tattoos, cocktails, and vacation spots.",
            "Gosling hopes that the next time you poke around a friend's medicine cabinet or surreptitiously review the stuff stuck on his refrigerator door, you will revel in the realization that you are poised at the edge of a new frontier in the understanding of human behavior.",
        ],
    ),
}
