# -*- coding: utf-8 -*-
"""Phase 2 chapter data for Social Intelligence: The New Science of Human
Relationships (Daniel Goleman), Part 5 (Healthy Connections), chapters 15-19:
The Biology of Compassion, Stress Is Social, Biological Allies,
A People Prescription, The Sweet Spot for Achievement.
Each chapter: num, title, pages, domain, and 5 slots (scrub/dialogue/audit/matrix/boss),
each slot a 4-tuple (topic, player_mission, visual_frame_description, key_concepts[10-12]).
"""

D = "Social Neuroscience | Relationships | Emotional Connection"

CHAPTERS = [
    {
        "num": 15,
        "title": "Chapter 15: The Biology of Compassion",
        "pages": "223-237",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Caregiving Circuit Scanner",
            "Scan a grid of couple and family scenes frozen at their critical moment and name the tell in each: a secure base offered, a safe haven granted, an intrusion that violates the cardinal rule, or an anxious partner's clingy hold. Ring the scene when caregiving flows fully from a stable foundation, and flag the moments when oxytocin, the molecule of motherly love, floods the frame.",
            "A high-tech scanner arch over a living room where each couple glows with a readout of Secure Base, Safe Haven, or Intrusion while gauges labeled Oxytocin and Empathy Distress swing as the low-road circuitry of the social brain flickers beneath the floorboards.",
            [
                "John Bowlby proposed that the same innate caregiving system springs into action whenever we have the urge to respond to a call for help, whether it is our lover, our child, our friend, or a stranger in distress",
                "Bowlby put it that 'all of us, from the cradle to the grave, are happiest when life offers us a series of excursions, long or short, from a secure base'",
                "Caregiving between romantic partners comes in two main forms: providing a secure base where a partner can feel protected and offering a safe haven from which that partner can take on the world",
                "The propositions about secure base and exploration were tested with 116 couples who had been romantically involved for at least four years: the more a person felt his or her partner to be a dependable 'home base,' the more willing they were to pursue life's opportunities with confidence",
                "In videotapes of couples discussing each other's goals, a partner who was sensitive, warm, and positive left the recipient more confident by the end of the discussion, often raising the bar on their goals",
                "If a partner was intrusive and controlling, the other became more downbeat and insecure about the goal, often cutting back on aspirations; controlling partners were perceived as rude and critical, and their advice was generally rejected",
                "The cardinal rule for providing a secure base: intervene only when asked to or when it is absolutely necessary",
                "Anxious people may have trouble relaxing enough to allow space for a partner's explorations, while avoidant people are poor at offering a secure base of comfort and virtually never come to their partner's emotional rescue",
                "Jaak Panksepp argues that empathy has its roots in the low-road neural system for maternal nurturance, one we share with a wide range of other species, and that empathy appears to be a primary response of this system",
                "Lab studies show that a mother's physiological arousal is distinctly stronger when she hears her own baby crying than when she hears another baby's wails",
                "When it comes to a prospective mate, both men and women rate kindness as the number-one trait they seek",
                "Freud noted a striking similarity in the physical intimacy between lovers and that between a mother and her baby: both spend much time gazing into each other's eyes, cuddling, nuzzling, suckling, and kissing, with ample skin-to-skin contact",
            ],
        ),
        "dialogue": (
            "Dialogue: Poor Liat's Ordeal",
            "Play Liat, the university student who screams 'I can't go on!' after facing gory pictures, a rat, ice water, and a live tarantula - then switch seats and play the fellow student deciding whether to volunteer to take her place. Let your attachment style rule your choice, then face the soup-kitchen mother's questions: would you donate food once a month, search the want ads, or go so far as to accompany her to a job interview?",
            "A bare laboratory room where a young woman recoils from a glass terrarium holding a tarantula; on a screen behind her a hideously burned man glares, while an ice bath steams at her side and a row of volunteers watches through a one-way mirror.",
            [
                "Liat, a university student who was in fact an experimental confederate, had to look at gory pictures of a burned man and an injured face, hold and stroke a rat, keep her arm in ice water, and reach into a terrarium to pet a live tarantula before she screamed, 'I can't go on!'",
                "Mario Mikulincer, an Israeli colleague of Phillip Shaver in the research on attachment styles, argues that the innate altruistic impulse that follows from empathy can become muddled, suppressed, or overridden when people feel the anxiety of insecure attachment",
                "The secure people were the most compassionate, both in feeling Liat's distress and in volunteering to take her place in the ordeal",
                "Anxious people were swallowed up by their own distressing reactions and could not bring themselves to come to Liat's rescue",
                "For anxious people, feeling another's pain can intensify into 'empathy distress,' a level of anxiety so strong that they become overwhelmed, making them most vulnerable to compassion fatigue",
                "Avoidant people protect themselves against painful emotions by suppressing them, closing themselves off to emotional contagion, and because they empathize poorly they rarely help - except when they might benefit personally, giving their compassion a 'what's in it for me' flavoring",
                "Caregiving flows most fully when we are feeling secure, possessed of a stable foundation that allows us to feel empathy without being overwhelmed",
                "Volunteers in one of Mikulincer's studies were asked whether they would donate food monthly to a woman with three hungry children, help her search the want ads for a job, or even accompany her to a job interview",
                "Before the questions, the volunteers received a one-fiftieth of a second, unconscious exposure to the names of people who made them feel secure, and were asked to deliberately visualize the faces of these caring figures",
                "Strikingly, even this temporary boost of security allowed anxious people to overcome their empathy distress and usual reluctance to help, reacting like secure people and showing more compassion",
                "A heightened sense of security seems to free up an abundant supply of attention and energy for the needs of others, but avoidant people still failed to empathize and suppressed their altruistic impulse",
                "Of the three attachment styles, the secure people were still the most willing among the volunteers to lend a hand, with their compassion directly proportional to the need they perceive: the greater the pain, the more they help",
            ],
        ),
        "audit": (
            "Audit: The Secure Base Field Ledger",
            "File every couple scene you witness under the correct column of the ledger: a secure base offered, a safe haven granted, or an intrusion that violates the rule of intervening only when asked. Record the social allergies that bloom with repeated exposure, and log every chemical marker - the oxytocin floods of nursing and affectionate contact, and the vasopressin-testosterone crossfire of long-term love.",
            "A counselor's office turned ledger with two columns, Secure Base and Safe Haven, linked by a reciprocity meter; exhibits float in to be filed - wet towels on the floor, a toilet-paper roll left on the empty cardboard tube, a nursing mother glowing - each dissolving into its column.",
            [
                "Ideally both partners should be able to switch fluidly from one role to the other, providing solace or haven - or receiving it - as needed, and such reciprocity marks a healthy relationship",
                "We provide a secure base whenever we come to our partner's emotional rescue, helping them solve a vexing problem, soothing them, or simply being present and listening",
                "A 'social allergy' is a strong aversion toward a romantic partner's habits that, like a physical allergen, at first contact causes no reaction - and would not in most other people - but becomes increasingly sensitized with each exposure",
                "Social allergies typically emerge when a dating couple spend more time together, getting to know each other 'warts and all,' as the inoculating power of romantic idealization wanes",
                "In research among American college students, most social allergies in women developed in reaction to their boyfriends' uncouth or thoughtless behavior, while men became vexed when their girlfriends seemed self-absorbed or too bossy",
                "Social allergies have consequence only to the extent that they prime anger and distress: the more upset they make a partner, the more likely it is that the couple will break up",
                "Psychoanalysts remind us that the desire for the 'perfect' person who will meet every expectation and fulfill our every need is a primal fantasy impossible to achieve",
                "Oxytocin, which the human body releases in women during childbirth and nursing as well as during orgasm, induces a flow of milk, dilates the blood vessels in the skin around the mammary gland, and lowers the mother's blood pressure as she feels more relaxed",
                "Kerstin Uvnas-Moberg, a Swedish neuroendocrinologist, contends that the oxytocin flood occurs whenever we engage in affectionate contact with someone we care for, so that merely being in a loved one's presence - or even thinking about them - may trigger a pleasant dose",
                "In one study oxytocin bonded members of one species of prairie vole in lifelong monogamous matches, while voles of another variety who lack this release have sex promiscuously and never bond to a partner",
                "In experiments where the hormone was blocked, monogamous voles that had already mated suddenly lost interest in each other; when the hormone was released in the promiscuous voles that lacked it, they started bonding with each other",
                "In one interaction vasopressin, oxytocin's close cousin, drives down levels of testosterone; in another, testosterone suppresses oxytocin, though testosterone can sometimes enhance oxytocin, suggesting passion need not fade with commitment",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: The Three Attachment Styles",
            "Sort a wall of faces who witness another's distress - the burnt man's image, the baby's cry - into the three attachment styles and the compassion signature of each: the secure who help in proportion to need, the anxious who drown in empathy distress, the avoidant who seal themselves off. Justify every call with the evidence on the card before the empathy-distress gauge redlines.",
            "A sorting chamber where three chutes open beneath a giant baby's wailing face: Secure glows golden, Anxious churns orange like a storm, Avoidant is sealed in grey; each scene card spirals down into the chute that owns its style of empathy.",
            [
                "Just as attachment styles can skew sexuality, they also lend their distinctive twist to empathy",
                "The secure people were the most compassionate, both in feeling Liat's distress and in volunteering to take her place",
                "Anxious people attune with an oversensitivity that can make them all the more upset at another person's suffering, swamped by emotional contagion",
                "Anxious people seem most vulnerable to compassion fatigue, burning out from their own anguish when faced with a relentless parade of others' suffering",
                "Avoidant people protect themselves against painful emotions by suppressing them, and in self-defense they close themselves off to emotional contagion from others who are suffering",
                "Because avoidant people empathize poorly, they rarely help - the one exception being when they might benefit personally, giving their compassion a 'what's in it for me' flavoring",
                "Mikulincer suggests the cynical view that compassionate acts always contain a bit of self-interest has a grain of truth - but mainly for people who are avoidant and so do not empathize well in the first place",
                "Of the three attachment styles, the secure people were still the most willing among the volunteers to lend a hand",
                "The secure people's compassion appears to be directly proportional to the need they perceive: the greater the pain, the more they help",
                "Feeling cared for frees us to care for others - and when we don't feel cared for, we can't care nearly so well",
                "An infant's cries triggering on-target caregiving is a phenomenon seen not just in mammals but even in birds, suggesting a universal template in Nature with obvious benefits for survival",
                "Compassion, a grand term, in its everyday guise can show as availability, sensitivity, or responsiveness - all signs of good parenting or friendship",
            ],
        ),
        "boss": (
            "Boss Battle: The Five-to-One Emotional Bank Account",
            "Stand in John Gottman's marriage laboratory and rule on each couple that files past: count their toxic and nourishing moments, catch the contemptuous insult delivered as though to someone on a lesser plane, and predict which unions will die within three years - you have the 90 percent accuracy standard to meet. Then fight the indifference that one divorce lawyer called the worst cruelty in a marriage, and hold the ratio at five to one.",
            "A marriage laboratory with two chairs facing a wall of video screens replaying arguments in fast-forward; an enormous scale weighs toxic moments against nourishing ones while a meter labeled Contempt glows red and a counter tallies good feelings shared between the partners.",
            [
                "John Gottman, a psychologist at the University of Washington, once came up with a way to predict with more than 90 percent accuracy whether a couple would separate within the following three years",
                "In a study of dating couples on the verge of marriage, the less satisfied couples tended to match their emotions the most closely during hostile arguments, and the more negative they became in that early disagreement, the less stable their match turned out to be",
                "Particularly damaging were expressions of disgust or contempt, which escalate negativity beyond mere criticism, often taking the form of an outright insult delivered as though to someone on a lesser plane",
                "With a partner's contempt comes the message that the other is unworthy of empathy, let alone love",
                "As one seasoned divorce lawyer put it, 'Indifference - not caring about, or even paying attention to, your mate - is one of the worst forms of cruelty in a marriage'",
                "A pattern where one disgruntlement triggered another, with defiant challenges and partners interrupting each other before the other could finish, most strongly predicted the couple would break up, most within a year and a half after their first session",
                "Gottman: 'In dating couples, the most important predictor of whether the relationship will last is how many good feelings the couple shares. In marriages, it's how well the couple can handle their conflicts.'",
                "Couples who live together for decades come to resemble each other because their continual rapport sculpts their facial muscles as they evoke the same emotions over the years",
                "In the photo study, couples' faces had grown more alike over twenty-five years, and the greater the facial similarity, the happier they reported being in their marriage",
                "The quiet push of partners toward each other's ideal version of who they should be has been called the Michelangelo Phenomenon",
                "The ratio of toxic to nourishing moments a couple has together has remarkable predictive power: a five-to-one ratio of positive to negative moments indicates a sound emotional bank account and a robust relationship almost certain to thrive long term",
                "As husbands and wives in their sixties discuss something they enjoy, measures of their physiology show that they both become progressively more cheerful as the conversation continues, reaching more peaks of resonance than couples in their forties",
            ],
        ),
    },
    {
        "num": 16,
        "title": "Chapter 16: Stress Is Social",
        "pages": "238-249",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Allostatic Load Gauge",
            "Scan a street of frozen social scenes and read the biological signature in each: the soothing conversation that drops blood pressure, the ambivalent companion who spikes it hardest, the insult swallowed in silence, the judgment that keeps cortisol high an hour longer. Stamp each dyad Toxic, Nourishing, or Ambivalent before the gauge labeled Allostatic Load ticks upward.",
            "A city street overlaid with diagnostic readouts where each passing pair is ringed - blue for soothing, red for toxic, amber for ambivalent - while a towering gauge labeled Allostatic Load climbs and a cortisol clock records how long each encounter's chemistry lingers.",
            [
                "The Tolstoys' forty-eight-year marriage began when Sonya, just seventeen, read Leo's diary of a profuse and conflicted sexual history and resolved to withdraw from him and poison his life; the battle was punctuated by truces while she bore thirteen children and recopied twenty-one thousand manuscript pages",
                "Sonya Tolstoy wrote that the daily blows to her heart 'shorten my life,' yet Leo lived to be eighty-two and Sonya lived nine years after him, to seventy-four - a remarkable exception like the centenarian who credits whipped cream and a pack of cigarettes a day",
                "It is not the quantity but the quality of social ties that counts: far more telling for our health than the absolute number of relationships may be the emotional tone of those we have",
                "In a study of elderly people hospitalized for congestive heart failure, those who had no one to rely on for emotional support were three times more likely to have another episode requiring a return to the hospital than those with warm relationships",
                "Among men getting angiography as part of treatment for coronary heart disease, those whose loved ones were reportedly least supportive had about 40 percent more blockage than those who reported the warmest connections",
                "Data from large epidemiological studies suggest that toxic relationships are as major a risk factor for disease and death as are smoking, high blood pressure or cholesterol, obesity, and physical inactivity",
                "'Hobbes,' a macho male baboon who invaded a troop in the jungles of Kenya, was named for the philosopher who wrote that life is 'nasty, brutish, and short'; his raw aggression rippled through the endocrine systems of the entire group, measured by cortisol samples from the males' blood",
                "Under stress the adrenal glands release cortisol, a hormone that acts as biological 'fuel' for metabolism and helps regulate the immune system, but chronically high levels are at play in cardiovascular disease, impaired immune function, diabetes, hypertension, and even the destruction of neurons in the hippocampus",
                "Even as cortisol shuts down the hippocampus, it stokes the amygdala, stimulating the growth of dendrites in that site for fear, and blunts the ability of key areas in the prefrontal cortex to regulate the fear signals coming from the amygdala",
                "The key biological systems linking stress to health are the sympathetic nervous system (SNS) and the hypothalamic-pituitary-adrenal (HPA) axis, which prepare us for emergencies by borrowing resources from the immune and endocrine systems",
                "The physiological changes from random ups and downs of relationships do not matter that much, but when downs continue over many years they create levels of biological stress technically known as an 'allostatic load' that can speed the onset of disease",
                "The more frail our condition - after onset of a serious disease, while recovering from a heart attack, in old age - the more powerful the health impact of our relationships",
            ],
        ),
        "dialogue": (
            "Dialogue: The Hostile Interviewer",
            "Play the German job-practice stress test: keep a stony, unsmiling expression, make cool notes on your clipboard, and belittle the applicant's skills while you ask her to subtract 17 from 1,242 aloud as fast as she can - then switch seats and be the applicant watching her cortisol spike. Now face Margaret Kemeny's principle: threats are most stressful when you have an audience and feel you are being judged.",
            "A spare interview room where an interviewer with a stone face notes on a clipboard while an applicant's voice trembles; behind a one-way mirror a cortisol readout spikes to record laboratory heights as a gauge compares this ordeal to math-under-noise stress tests.",
            [
                "Elysa Yanowitz, a regional sales manager, was ordered to fire one of her best-performing salespeople because a top executive did not think the woman was 'hot' enough; she refused, and over months of mistreatment developed high blood pressure before the company replaced her",
                "In a British study of health care workers who had two supervisors, their average blood pressure jumped 13 points systolic and 6 diastolic - from 113/75 to 126/81 - on the days the dreaded boss worked",
                "Studies in Sweden and the United Kingdom show that people in lower positions in an organization are four times more likely to develop cardiovascular disease than those in the top rungs",
                "Workers who feel unfairly criticized, or whose boss will not listen to their problems, have a rate of coronary heart disease 30 percent higher than those who feel treated fairly",
                "An analysis of 208 studies involving 6,153 individuals who were subjected to stressors found that the worst stress by far was being the target of harsh criticism while helpless to do anything about it",
                "Margaret Kemeny, an expert in behavioral medicine at the University of California Medical School in San Francisco, says threats are most stressful 'when you have an audience and feel you are being judged'",
                "The largest cortisol spikes occurred when the source of stress was interpersonal - for example, when someone sat in judgment on a volunteer who had to subtract the number 17 from 1,242 aloud and continue subtracting as rapidly as possible",
                "When a person performed an onerous task while being judged on how they did, the effect on cortisol was about three times greater than when the stress was comparable but impersonal",
                "Dickerson and Kemeny argue that being evaluated threatens the 'social self,' the ways we see ourselves through others' eyes, and that such threats are almost as powerful biologically as threats to our very survival",
                "An interviewer's unnerving, hostile reaction reliably triggers the HPA axis to produce some of the highest levels of cortisol of any laboratory stress simulation ever tested",
                "A virtual audience can affect the HPA system as powerfully as a live one, Kemeny explains, because 'the moment you think of something, you create an internal representation, which in turn acts on the brain' much as would the reality it represents",
                "When a threat persists no matter what efforts we might make, the cortisol rise magnifies, paralleling the predicament of someone who finds himself the target of vicious prejudice",
            ],
        ),
        "audit": (
            "Audit: The Social Stressor File",
            "File every stressor you encounter under its true category - interpersonal or impersonal, controllable or helpless - and grade each by its cortisol recovery time: forty minutes for the auto alarm, an hour or more for the negative social judgment. Then audit Sheldon Cohen's cold laboratory: sort the factors that multiply susceptibility, from smoking at three times to lonely relationships at 4.2 times.",
            "A records office where dossiers labeled Conflict, Insult, Ambivalence, Loneliness, and Judgment are stamped with cortisol-recovery clocks, while a wall chart ranks smoking, vitamin C deficiency, and poor sleep against rocky relationships as causes of the common cold.",
            [
                "In a study of a hundred men and women wearing blood-pressure devices, readings fell when they were with family or enjoyable friends - these interactions were pleasant and soothing - and rose when they were with someone troublesome",
                "The biggest blood-pressure jump came while people were with those they felt ambivalent about: an overbearing parent, a volatile romantic partner, a competitive friend",
                "Ambivalent relationships put an emotional demand on us: each interaction is unpredictable, perhaps potentially explosive, and so requires heightened vigilance and effort",
                "In a stress experiment, volunteers had to defend themselves against a false accusation that they had shoplifted; their immune systems secreted T lymphocytes while the walls of their blood vessels emitted a substance that binds to those cells, setting in motion artery-clogging plaque on the endothelium",
                "Sheldon Cohen of Carnegie Mellon University has intentionally given colds to hundreds of volunteers, quarantining them for twenty-four hours before exposure and housing them for five days at least three feet apart while testing nasal secretions and blood for antibodies",
                "Those with an ongoing personal conflict were 2.5 times as likely as others to get a cold, putting rocky relationships in the same causal range as vitamin C deficiency and poor sleep",
                "Smoking, the most damaging unhealthy habit, made people three times more likely to succumb to the cold virus",
                "Compared to those with a rich web of social connections, those with the fewest close relationships were 4.2 times more likely to come down with the cold, making loneliness riskier than smoking",
                "Conflicts that lasted a month or longer boosted susceptibility to colds, but an occasional argument presented no health hazard",
                "Vibrant social connections boost our good moods and limit our negative ones, suppressing cortisol and enhancing immune function under stress",
                "For impersonal stress, like an obnoxious auto alarm we are helpless to stop, the body got over its inevitable jump in cortisol within about forty minutes",
                "If the cause was a negative social judgment, cortisol stayed high 50 percent longer, taking an hour or more to return to normal",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: The Class of '57 Sorting Room",
            "Sort the Wisconsin graduates into the two columns of Richard Davidson's study: the high-risk physical profiles with unfavorable relationship histories versus the resilient ones, then match each to the ratio of left to right prefrontal activity that predicts their recovery from distress. Defend every placement with the cumulative emotional tone of the relationship record before the allostatic-load meter reads your own score.",
            "A sorting room built from a high school reunion: class portraits glow on twin racks, one labeled High-Risk Profile and one Labeled Resilient, while an EEG-style meter shows left-prefrontal activity weighing against right and a card flips between Jane's nine symptoms and Jill's three.",
            [
                "The Class of 1957 study began when researchers from the University of Wisconsin started studying about ten thousand graduating high school seniors, nearly a third of those in the entire state, reinterviewing them at age forty and again in their mid-fifties",
                "Near sixty-five, a group of the graduates was brought to the W. M. Keck Laboratory for Functional Brain Imaging and Behavior, where Richard Davidson correlated their social history, brain activity, and immune function",
                "The graduates were assessed on blood pressure, cholesterol, and levels of cortisol and other stress hormones; a very high total score predicts an earlier death",
                "The researchers found a strong association between having a high-risk physical profile and an unfavorable cumulative emotional tone in the graduates' most important life relationships",
                "Jane, whose parents were alcoholics and who was divorced with a scant social life, had nine out of twenty-two common medical symptoms in the medical survey",
                "Jane had the highest activity in her right prefrontal area relative to the left of anyone studied in her class, a pattern suggesting she more often reacted to life with intense distress and recovered slowly from setbacks",
                "Jill, whose father died when she was nine but whose mother she felt was extremely caring, was close to her husband and four sons, had many close friends, and reported problems with only three of the twenty-two symptoms",
                "Jill was the member of the Class of '57 with the greatest activity in her left prefrontal cortex relative to the right, a pattern suggesting her days were filled with mostly pleasant moods",
                "The left prefrontal area regulates a cascade of circuitry in lower brain areas that determines our recovery time from distress - that is, our resilience",
                "The more left prefrontal activity relative to the right, the better we are at developing cognitive strategies for emotional regulation and the faster our emotional recovery, which in turn determines how quickly cortisol returns to normal",
                "Davidson's group found that activity in the same left prefrontal area correlated with the immune system's response to a flu shot: those with the highest activation mobilized three times more flu antibodies than others",
                "Wisconsin graduates who endured relentless stress in childhood now as adults had poor stress recovery abilities, staying overwhelmed longer once upset, while those exposed to manageable stress in childhood were most likely to have the better prefrontal ratio - with a caring adult who provides a secure base seeming essential",
            ],
        ),
        "boss": (
            "Boss Battle: The Toxic Boss Endgame",
            "Survive the months of Yanowitz's ordeal - the refused order, the souring bosses, the hypertension - and then face the caretaker's siege: Laura Hillenbrand's husband Borden sobbing alone in the foyer, the Alzheimer's caregivers with immune genes expressed 50 percent less, telomeres shrinking ten years of biology. Counter every assault with collective social intelligence until thirty-five neighbors rally around Philip Simmons's wheelchair and you have built FOPAK.",
            "A night-lit office where a sales manager refuses a monstrous order as her blood pressure climbs on a monitor; dissolve to a bedroom where a caretaker sobs in the foyer while a DNA helix visibly shortens, and then to a brilliant fall yard where a crowd of neighbors surrounds a wheelchair in a golden web of coordination.",
            [
                "When someone was the target of harsh criticism and helpless to do anything about it, the stress was the worst of all kinds - and people who respond to insults with silence experience significant hikes in blood pressure",
                "Laura Hillenbrand, the author of Seabiscuit, suffered from chronic fatigue syndrome; her devoted husband Borden, even while struggling with his own graduate work, nursed her, helped her eat, drink, and walk, and read to her - and one night she heard him 'pacing the foyer and sobbing,' his anguish hidden by the next morning's 'cheerful and steady' mask",
                "The most powerful data on caregiver stress comes from the interdisciplinary research group at Ohio State University led by psychologist Janice Kiecolt-Glaser and her husband, immunologist Ronald Glaser",
                "The Ohio State group studied ten women in their sixties caring for a husband with Alzheimer's disease, on duty twenty-four hours a day and feeling terribly isolated and uncared for themselves",
                "A gene that regulates a range of crucial immune mechanisms - GHmRNA, which enhances the production of lymphocytes and boosts the activity of natural killer cells and macrophages - was expressed 50 percent less in the caretakers than in other women their age",
                "An earlier finding showed that women under such stress were virtually unable to benefit from flu shots, and that stressed women took nine days longer to heal a small puncture wound than women in a nonstressed comparison group",
                "ACTH, a precursor to cortisol and one of the hormones secreted when the HPA axis runs amok, blocks the production of the crucial immune agent interferon and diminishes the responsiveness of lymphocytes",
                "The continual stress of tireless caregiving in social isolation impairs the brain's control of the HPA axis, which in turn weakens the ability of immune system genes like GHmRNA to do their job fighting disease",
                "The toll of relentless stress strikes the very DNA of caretakers: mothers caring for a chronically ill child were, on average, ten years older biologically than others of the same chronological age, as measured by the length of the telomeres on their white blood cells",
                "Telomeres are pieces of DNA at the end of a cell's chromosome that shrink each time the cell divides; somewhere after ten to fifty divisions the telomere becomes too short to replicate and the cell 'retires'",
                "Among the exceptions were women who, despite feeling overwhelmed in their lives, felt well supported by others - they had younger cells even if they were caring for a disabled loved one",
                "In Sandwich, New Hampshire, thirty-five neighbors rallied around Philip Simmons, a college English teacher with Lou Gehrig's disease, coordinating largely by phone and e-mail as cooks, drivers, babysitters, home aides, and yard workers until he died at age forty-five; the group, FOPAK (Friends of Phil and Kathryn), gave his wife the sense of being loved by their community - and most volunteers agreed they were the ones receiving the gift",
            ],
        ),
    },
    {
        "num": 17,
        "title": "Chapter 17: Biological Allies",
        "pages": "250-266",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Emotional Rescue Radar",
            "Scan a ward, a living room, and an MRI suite for the signatures of emotional rescue: a hand held, a lullaby sung, skin-on-skin touch, a reassuring presence at a bedside. Ring each moment oxytocin primes its chemistry - blood pressure falling, cortisol plummeting, pain threshold rising - and flag the scenes where the HPA axis still roars unchecked.",
            "A radar sweep across a hospital ward, a living room, and an MRI bore; each comforting touch leaves a golden trail of oxytocin molecules while red HPA activity subsides, and a counter shows blood pressure falling, wounds healing faster, and the pain threshold rising.",
            [
                "Goleman's mother, a retired sociology professor, offered a free room to graduate students from her university, preferring those from East Asian cultures where older people are appreciated; a baby born when she was almost ninety roamed the house giving hugs, and she seemed for a few years to get younger, physically and mentally",
                "Older people tend to cut back their social networks selectively, preserving positive relationships - a strategy that makes good biological sense as health becomes more fragile with age",
                "A landmark study of elderly Americans who were aging successfully found that the more emotionally supportive their relationships, the lower their indicators of biological stress like cortisol",
                "One study found that when elderly people had an engaging, supportive social life, they displayed better cognitive abilities seven years later than did those who were more isolated",
                "Paradoxically, loneliness has little or nothing to do with how much time people actually spend by themselves, nor how many social contacts they have in a given day - it is the paucity of intimate, friendly contacts that leads to loneliness",
                "The sense of loneliness, rather than the sheer number of acquaintances a person has, correlates most directly with health: the lonelier a person feels, the poorer immune and cardiovascular function tends to be",
                "Neurogenesis, the brain's daily manufacture of new neurons, continues into old age though at a slower rate, and some neuroscientists suggest the slowdown is a side effect of monotony rather than an inevitability",
                "Adding complexity to a person's social environment primes new learning and enhances the rate at which the brain adds new cells, which is why some neuroscientists work with architects to design homes for the elderly where occupants must interact more with others in their daily routines",
                "Skin-on-skin touch is particularly soothing because it primes oxytocin, as do warmth and vibration - which may explain much of the stress relief that comes from massage or a cozy cuddle",
                "When oxytocin releases, blood pressure lowers as we slide into the relaxed mode of parasympathetic activity, cortisol levels plummet, our pain threshold rises, and even wounds heal faster",
                "Oxytocin has a short half-life in the brain - it is gone in just a matter of minutes - but close, positive long-term relationships may offer a relatively steady source of release through every hug and affectionate moment",
                "The very substance that draws us closer to the people we love converts those warm connections into biological well-being",
            ],
        ),
        "dialogue": (
            "Dialogue: The ICU Lullaby",
            "Play John F. Kennedy, Jr., still in his tuxedo, taking his dying cousin Anthony Radziwill's hand and singing 'The Teddy Bears' Picnic' - the lullaby Jackie Onassis sang to them both - and carry Anthony's voice joining in softly. Then switch seats into the MRI: face the mild shock alone, with a stranger's hand, and with your husband's hand, and feel which clasp pacifies the HPA axis.",
            "An ICU room in dim blue light where a man in a tuxedo holds the hand of a dying cousin and sings softly while the monitors flatten toward calm; the scene dissolves into the vast bore of an MRI machine where a woman's hand lies cupped in another hand as a shock warning flickers on a screen above.",
            [
                "Anthony Radziwill lay dying in the intensive care unit of a New York hospital from fibrosarcoma, a deadly cancer, when his cousin John F. Kennedy, Jr. - who was himself to die months later off Martha's Vineyard - arrived still in a tuxedo and learned the doctors had given his cousin just hours to live",
                "Taking hold of his cousin's hand, John quietly sang 'The Teddy Bears' Picnic,' the song his own mother, Jackie Onassis, had sung to them both as a lullaby when they were small, and Anthony, near death, joined in softly",
                "John, as Carole Radziwill recounts, 'had taken him to the safest place he can find'",
                "Physiologists have shown that as people become emotionally interdependent, they play an active role in the regulation of each other's very physiology - a biological entrainment in which the cues each partner receives drive their own body for better or worse",
                "In Richard Davidson's laboratory, eight women volunteered to face a mild shock while lying in an MRI; sometimes they were alone, sometimes a stranger held their hand, and sometimes they felt the reassuring touch of their husband's hand",
                "When a woman held her husband's hand, she felt far less anxiety than when she faced the shock alone; holding a stranger's hand helped a bit, though not nearly so much",
                "It was impossible to conduct the study so that the women were 'blind' to whose hand they were holding - on a trial run, wives always guessed correctly whether the hand was their husband's or a stranger's",
                "When the wives faced the shock alone, fMRI analysis showed activity in regions of the brain that drive the HPA axis into its emergency response, pumping stress hormones through the body",
                "That volatile circuitry was pacified strikingly with the calming clasp of a husband's hand - a snapshot of the brain undergoing emotional rescue",
                "The more highly satisfied a wife felt with her marriage, the greater the biological benefit from holding hands, clinching the answer to why some marriages challenge women's health while others protect it",
                "Oxytocin acts as a stress hormone 'down-regulator,' reducing the very HPA and SNS activity that, when sustained, puts our health at risk",
                "Under stress, a woman's brain secretes more oxytocin than a man's, with a calming effect that moves women to seek out others - and androgens suppress the calming benefits of oxytocin while estrogen enhances them, so women tend and befriend while men go it alone",
            ],
        ),
        "audit": (
            "Audit: The Marital Battleground Dossier",
            "Audit the conflict sessions in the lab: file each couple's fight by the number of adrenal hormones that changed, the immune dips that lingered for hours, and the rancor that made the shifts worse. Then record the gender ledger - wives whose cholesterol tracks marital stress, husbands whose endocrine systems do not budge - and reconcile every entry with the thirteen-year study of five hundred married women in their fifties.",
            "A laboratory observation room behind a one-way mirror onto a confrontation room; case files float in with hormone readouts - ACTH, cortisol, blood pressure - while a chart plots wives' cholesterol against marital stress and a satisfaction dial spins on the thirteen-year study.",
            [
                "Newlyweds, all considering themselves 'very happy' in their marriages, volunteered to be studied during a thirty-minute confrontation about a disagreement, and during the tiff five of six adrenal hormones tested changed levels, including increases in ACTH that indicate a mobilized HPA axis",
                "During the newlyweds' argument, blood pressure shot up and indices of immune function were lowered for several hours, with long-term shifts for the worse in the immune system's ability to mount a defense against invaders",
                "The more bitterly hostile the argument, the stronger the shifts - the endocrine system, the researchers conclude, 'serves as one important gateway between personal relationships and health'",
                "Couples in their sixties, married an average forty-two years, showed negative biological changes even stronger than the newlyweds during the marital battle - but only for the wives",
                "The newlywed wives who showed the greatest decline in immune measures during and after the fight were the most dissatisfied with their marriages a year later",
                "For women, when husbands withdrew in anger during disagreements, stress hormones zoomed upward; when husbands displayed kindness and empathy, wives reflected their relief in lower levels of the same hormones",
                "For husbands, whether the talk was harsh or pleasant, their endocrine systems did not budge - the sole exception being at the extreme, among those who reported the most abrasive arguments at home",
                "Data from multiple sources suggest that wives are more vulnerable to suffer the health costs of a rocky marriage than their husbands, yet women do not seem to be more biologically reactive than men in general",
                "Women put a greater emotional premium on their closest ties, take more personal responsibility for the fate of those they care about, and are more attuned to the ups and downs of their relationships",
                "Wives spend far more time than husbands ruminating about upsetting encounters, reviewing them in more vivid detail - and because simply recalling a conflict can trigger the biological shifts that accompanied it, the tendency to mull over one's troubles takes a physical toll",
                "In the Wisconsin Study, women's cholesterol levels were directly linked to the amount of stress in their marriages, far more so than for men in the Class of '57",
                "Women are more likely to have a heart attack when they experience emotional stress from a severe relationship crisis like divorce or death, while for men the trigger is more likely physical exertion; older women are also more vulnerable to life-threatening stress-hormone rises in response to a sudden emotional shock like the unexpected death of a loved one, a condition doctors call the 'broken heart syndrome'",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Tend-and-Befriend or Fight-or-Flight",
            "Sort each response to a threat into its hormonal owner: the woman's brain secreting extra oxytocin and seeking out others, the man's androgen-suppressed calm sought through sheer distraction. Then sort relationships into the two registers that decide a marriage's biology - the women in the thirteen-year study whose satisfaction set their blood pressure, glucose, and cholesterol, versus the embattled couples whose immune systems weakened day to day.",
            "Two silhouettes stand under a threat gauge: one turns toward a gathering of friends beneath a golden oxytocin cloud, the other stands alone before a red adrenal storm, while a dial reads the HPA and SNS toll of each and a scale weighs satisfied wives against embattled couples.",
            [
                "Shelley Taylor at UCLA discovered that while women tend or befriend, their bodies release additional oxytocin, which calms them even more",
                "Androgens, male sex hormones, suppress the calming benefits of oxytocin, while estrogen, the female sex hormone, enhances it",
                "When told they would receive an electric shock, women chose to wait for it with other participants, while men preferred being by themselves",
                "Men seem better able to calm their distress through sheer distraction; TV and a beer may suffice",
                "The more close friends women have, the less likely they are to develop physical impairments as they age, and the more likely they are to lead a joyful life in their later years",
                "The impact is so strong that friendlessness has been found to be as detrimental to a woman's health as smoking or obesity",
                "Even after an enormous blow like the death of a spouse, women with a close friend and confidante are more likely to escape new physical impairments or loss of vitality",
                "Psychology has an infelicitous term for the coalescing of two into one: a 'mutually regulating psychobiological unit,' a radical relaxing of the usual psychological and physiological line separating I and You, self and other",
                "The fluidity of boundaries between people who feel close allows a two-way coregulation, influencing each other's biology: 'Your hostility bumps up my blood pressure; your nurturing love lowers it'",
                "If we have a life partner, a close friend, or a warm relative on whom we can rely as a secure base, we have a biological ally - and patients with severe or chronic disease may well benefit from tuning up their emotional connections",
                "In a nourishing relationship, partners help each other manage their distressing feelings, rethinking what causes the distress and short-circuiting the negative neuroendocrine cascade",
                "In the thirteen-year study of close to five hundred married women in their fifties, the more pleased a woman was with her marriage, the better her health: levels of blood pressure, glucose, and bad cholesterol were lower for the satisfied women than for those unhappy in their marriages",
            ],
        ),
        "boss": (
            "Boss Battle: The Caretaker's Long Night",
            "Endure the twenty-four-hour siege of caregiving - Borden's hidden anguish, the Alzheimer's caregivers' flu-shot failure, the immune genes dimming to 50 percent, telomeres shriveling - and fight back with collective social intelligence. Mobilize the FOPAK model, heed Sheldon Cohen's advice to graft new people onto your network, and end at the bedside where a loving presence reaches even a minimally conscious patient.",
            "A house at night where one light burns in a caretaker's room while a DNA helix visibly shortens on a monitor; then a circle of neighbors with phone receivers forms a golden web around a hospital bed, and a whispering visitor's words light up a scan of a brain that cannot answer.",
            [
                "Anyone who has to nurse a loved one day and night endures extraordinary, unabated stress that takes an inevitable toll on the health and well-being of even the most devoted caretaker",
                "An earlier study of women under similar stress had discovered that they were virtually unable to benefit from flu shots; their immune systems could not manufacture the antibodies the shot ordinarily stimulates",
                "The continual stress of tireless caregiving in social isolation impairs the brain's control of the HPA axis, which in turn weakens the ability of immune system genes like GHmRNA to fight disease",
                "The toll of relentless stress strikes the very DNA of the caretakers, speeding the rate at which cells age and adding years to their biological age",
                "The longer mothers had been burdened caring for a chronically ill child, the more they had aged at the cellular level, the rate measured by the length of the telomeres on their white blood cells",
                "Collective social intelligence can offer an alternative to the overwhelming toll of caregiving, as the thirty-five Sandwich, New Hampshire neighbors who formed FOPAK demonstrated for Philip Simmons and his wife",
                "Sheldon Cohen recommends that hospital patients deliberately seek out biological allies, arguing that it can pay to 'graft new people on to your social network, especially people you can open up to'",
                "Cohen: 'The most striking finding on relationships and physical health is that socially integrated people - those who are married, have close family and friends, belong to social and religious groups, and participate widely in these networks - recover more quickly from disease and live longer. Roughly eighteen studies show a strong connection between social connectivity and mortality'",
                "Cohen also urges patients to reduce the number of emotionally toxic interactions in their day while increasing the nourishing ones, and suggests hospitals should enlist the personal networks of patients, educating those who care most to become allies in making lifestyle changes",
                "Awkwardness and anxiety often make friends and families step back from a patient: 'Most of the people around me stepped backward,' recalls Laura Hillenbrand, who stopped hearing from friends after one or two get-well cards",
                "Even patients in a vegetative state who seem utterly unaware - in what medical jargon labels a 'minimally conscious state' - activate the same brain circuitry as people with intact brains when someone emotionally close reminisces about past events or touches them lightly",
                "Love is more than just a way to improve the emotional tone of a patient's life - it is a biologically active ingredient in medical care, and Mark Pettus, a physician, urges us to act on the 'invitations to enter' that take the form of 'a tear, a laugh, a look, or even silence'; with his own young son in the hospital, he says, 'Love was our language'",
            ],
        ),
    },
    {
        "num": 18,
        "title": "Chapter 18: A People Prescription",
        "pages": "267-284",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The I-It Detection Lab",
            "Scan a hospital ward of frozen moments and name the stance in each: the resident's extra ten minutes with the frightened woman, the nurse reprimanded for holding a dying patient's hand, the surgeon's golf joke, the throat doctor's 'Busy day! Busy day!' Flag every scene where the person is treated as a numbered unit and every scene where simple recognition of the human being breaks through.",
            "A hospital corridor turned diagnostic board where each interaction glows cold grey (I-It) or warm gold (I-You); a clock ticks the fifteen-minute-per-patient budget while a gauge weighs caring against cost-effectiveness and a file folder labelled 4D floats past.",
            [
                "A medical resident in a spine clinic stayed ten extra minutes with a woman in great pain from severe disk degeneration until she agreed to the facet joint injection, only to be told by the attending physician that he could not afford 'the luxury of that kind of prolonged conversation' - the clinic was scheduled for fifteen minutes per patient, including dictation time",
                "The attending physician walked the resident through the mathematics: if a doctor billed $300,000 each year to patients, he would be left with about $70,000 for his salary, so the only way to make more money was to cram in more patients in less time",
                "A European neurologist lamented that his national health plan computes how much time to spend with each patient 'but they don't include any time to talk to patients, to relate, to explain, to make them feel better'",
                "Surveys find signs of at least some degree of burnout in 80 to 90 percent of practicing physicians - a quiet epidemic with symptoms of exhaustion, intense dissatisfaction, and a depersonalized I-It attitude",
                "The patient in 4D, admitted for multidrug resistant pneumonia with no visitors and no one to notify, was befriended by a night nurse who spent his spare moments holding her hand in her last moments of life - and was reprimanded by his supervisor for wasting time, with a complaint registered in his personnel file",
                "'Our institutions are organized lovelessness,' as Aldous Huxley put it in The Perennial Philosophy",
                "When people are treated as numbered units, interchangeable parts of no interest or value in themselves, empathy is sacrificed in the name of efficiency and cost-effectiveness",
                "Inpatients scheduled for an X-ray are last in line because the hospital makes more money from outpatient X-rays, while inpatient tests are paid for as part of a 'bundled' payment, making the inpatient X-ray a potential money-loser; patients may wait five hours, and for some tests must fast from midnight, missing breakfast and lunch",
                "'Revenue guides how services are handled,' one hospital executive admitted; 'We don't consider how we would feel if it were us waiting'",
                "A heart surgeon told a patient who had jumped from a fifth-floor window in a suicide attempt that if he wanted to punish himself, he would have done better to take up golf, while his medical-resident students laughed and the patient's face revealed his anguish",
                "A throat surgeon told a patient he had a growth on his vocal cords needing biopsy and tests, then muttered 'Busy day! Busy day!' as she left - a tale told by the late Peter Frost, a professor of management who campaigned for medical compassion after his own experience in a cancer ward",
                "The key element lacking in such scenarios is the simple recognition of the human being, the person struggling for dignity, even for life; insensitivity can cause needless 'iatrogenic suffering,' anguish added when medical personnel leave their hearts at home",
            ],
        ),
        "dialogue": (
            "Dialogue: The Presurgery Interview",
            "Play the brusque nurse who softens the moment Kenneth Schwartz says 'lung cancer,' takes his hand, and ends wiping tears from her eyes - then play Schwartz himself, telling her about two-year-old Ben. Switch seats into the spine clinic and win the frightened woman's trust in ten minutes, then into Dr. Robin Youngson's ward, where you must find the human being behind the 'physiological preparation.'",
            "A crowded presurgery waiting area where a nurse and patient sit face to face, a single warm light isolating them; across the room a clock counts down while a tear rolls down the nurse's cheek, and a sign on the wall reads 'Compassion: right to be treated with it.'",
            [
                "Kenneth Schwartz, a successful Boston lawyer, was forty when he was diagnosed with lung cancer, the day before his surgery sitting in a mobbed presurgery waiting area while harried nurses scurried about",
                "During the presurgery interview, a nurse who at first seemed brusque took Schwartz's hand and asked how he was doing when he told her he had lung cancer; he told her about his two-year-old son Ben, and she said her nephew was named Ben, too",
                "By the end of their conversation the nurse was wiping tears from her eyes, and though she ordinarily did not go to the surgical floor, she came the next day to take his hand and wish him luck",
                "Schwartz described such acts of kindness by medical staff, 'quiet acts of humanity,' as having 'made the unbearable bearable'",
                "Shortly before his death, just months later, Schwartz founded the Kenneth B. Schwartz Center at the Massachusetts General Hospital to 'support and advance compassionate health care' that offers hope to patients and support to caregivers",
                "The Schwartz Center bestows an annual Compassionate Caregiver Award to honor medical staff who have shown extraordinary kindness in caring for patients and can serve as role models",
                "Instead of standard medical grand rounds updating staff on new developments, 'Schwartz Center Rounds' give hospital staff a chance to share their concerns and fears, on the premise that insight into their own responses lets caregivers make a personal connection with patients",
                "At the first Schwartz Center Round at Mount Auburn Hospital in Cambridge, Massachusetts, around 160 medical staff showed up though no more than sixty or seventy were expected - 'these rounds really speak to a need for us to talk honestly with one another about what it's like to do our work,' said Dr. Beth Lown",
                "Dr. Lown: 'The motive to connect with people that draws so many into medicine gets slowly supplanted by the hospital culture - a biomedical orientation, technology-driven... The question is not whether empathy can be taught, but what are we doing that drives it out of medical students?'",
                "Medical school interview guidelines emphasize the human dimension: let a patient complete his first statement rather than commandeering the conversation, elicit all of a patient's concerns, and understand how the patient perceives the illness and treatment",
                "Empathy and rapport, Dr. Lown says, 'can be taught and learned, but they must be practiced and cultivated like any other clinical skill,' making physicians more efficient and patients more adherent and satisfied",
                "Schwartz, writing just months before he died: 'Quiet acts of humanity have felt more healing than the high-dose radiation and chemotherapy that hold the hope of cure... it certainly made a huge difference to me'",
            ],
        ),
        "audit": (
            "Audit: The Caregiving Flowchart",
            "Audit the social service agency with William Kahn's three years of observations: draw the arrows of care from desk to desk, find who gives and who receives, and expose the reverse caregiving that runs uphill. Balance every account - the board president's secure base, the fund-raiser's mutual support society, the fourteen quits from six positions - and stamp each entry with its emotional debit.",
            "A flowchart wall of an agency office where golden arrows connect desks: a thick warm loop between director and fund-raiser, an upward flow from supervisor to director, empty grey channels down to the social workers, and a counter that tallies the resignations month by month.",
            [
                "William Kahn cast an anthropological eye over the small daily exchanges among the staff of a social service agency whose mandate was to provide homeless children with an adult volunteer as companion, mentor, and role model",
                "Caring interactions are nothing special, Kahn discovered; they are embedded in the daily life of any workplace",
                "When a new social worker presented a difficult case, a more seasoned worker listened attentively to his frustrations, asked probing questions, held back her most negative judgments, and said how impressed she was with his sensitivity - a natural display of multiple modes of caregiving",
                "In a meeting where the supervisor was supposed to discuss the workers' most problematic cases, she launched into a monologue on administrative issues, stared down at her notes avoiding eye contact, left little opportunity for questions, expressed no empathy for the overwhelming caseloads, and could not produce the crucial scheduling information - caregiving score: zero",
                "The executive director was fortunate in having a board president who was a model secure base, listening sympathetically to his predicaments and offering reassurances that the board would not abandon him while giving him autonomy",
                "The executive director provided none of that caring to the overburdened social workers: he never asked how they felt, never encouraged them, and his relationship with them was emotionally barren, resulting only in disconnection",
                "The director and his fund-raiser formed a mutual support society, listening to each other's troubles and offering counsel and consolation - but neither of them gave a bit to anyone else at the agency",
                "The social work supervisor gave far more support to her boss than he did to her - a reverse caregiving that is surprisingly common and resembles dysfunctional families where a parent abdicates responsibility and seeks care from the children",
                "The social workers told Kahn that when they felt cared about themselves, they were more willing and able to be active caregivers: 'When I'm feeling like I'm worthwhile around here, I throw myself into the supervision' of the children in their charge",
                "The social workers had a swelling emotional debit, giving far more than they received; month by month they withdrew emotionally from their work, burned out, and eventually left",
                "Over two and a half years, fourteen people quit the six social work positions - lacking emotional refills, caregivers run on empty",
                "Staff caregiving is an adult version of offering a secure base, from simply being available and lending a sympathetic ear to stopping to listen to a complaint, and people in the helping professions who get little sense of a secure base become more susceptible to 'compassion fatigue'",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Empathy or Efficiency",
            "Sort each doctor-patient scene onto the ledger of the 1997 JAMA malpractice study: the rapport-builders who sat down, used small talk, and laughed versus the I-It machines who ran on the clock. Judge which physician gets sued, which patients recall instructions, which 25 percent quit their health plan, and which institution keeps its staff - then justify every call with the evidence card.",
            "A courtroom-style sorting desk where two physicians sit across from each other: one with a chair pulled up and a warm tone, the other with a hand already on the doorknob; a ledger tallies malpractice suits, patient recall, and the exit interviews of those who leave their health plan.",
            [
                "A much-discussed study of how doctors talk to patients, featured in 1997 in the Journal of the American Medical Association, found that impaired communication - rather than the actual number of mishaps - largely predicted that a given physician would be sued for malpractice",
                "Doctors whose patients felt more rapport sued them less; they told patients what to expect from their visit or treatment, engaged in small talk, touched them reassuringly, sat down with them, and laughed with them - humor builds rapport quickly and powerfully",
                "The office visits of the doctors less likely to be sued ran about three and a half minutes longer, and the shorter the visit, the more likely a malpractice claim",
                "A review of studies found patients' satisfaction was highest when they felt a doctor was empathic and gave useful information",
                "A tone of voice that showed concern and emotional engagement made a doctor's words seem more helpful, and the more satisfied the patients, the better they could recall the physician's instructions and the greater their compliance",
                "'Exit interviews' with patients who have decided to quit their health plan reveal that 25 percent leave because 'I didn't like the way my physician communicated with me'",
                "The first principle of the Code of Medical Ethics of the American Medical Association admonishes physicians to provide competent medical care with compassion",
                "Only in the last few years did the U.S. licensing exam for medicine begin to include an assessment of a doctor's ability to establish rapport and communicate with patients",
                "The movement toward 'patient-centered' or 'relationship-centered' medicine enlarges the focus of medical attention beyond mere diagnosis to include the person being treated",
                "Robin Youngson, an anesthesiologist in Auckland, New Zealand, campaigns to add the right to be treated with compassion to his country's legal code of patients' rights after his five-year-old daughter lay tied to a bed for ninety days with a broken neck",
                "Youngson confesses that for much of his career he reduced the human being in front of him to a 'physiological preparation,' and now blames 'dysfunctional styles of thinking and belief of physicians: linear, reductionistic, overly critical and pessimistic, intolerant of ambiguity. We think that 'clinical detachment' is the key to clear perception. Wrong' - 'We have utterly lost compassion'",
                "The word 'heal' comes from the Old English hal, 'to make whole, or mend,' implying helping a person regain a sense of wholeness and emotional wellness - and compassion heals in ways that no medicine or technology can",
            ],
        ),
        "boss": (
            "Boss Battle: The Accountant's Mentality",
            "Break the machine: rebalance the hospital's time math, defend the night nurse's holding of a dying hand, heal the burnout epidemic that touches 80 to 90 percent of physicians, and keep the nurses who catch distress from running on empty. Build a secure base for the front line, institute the Schwartz Center Rounds, and end by being the presence that makes the unbearable bearable.",
            "A hospital ward rendered as a spreadsheet where each patient is a row of dollars and minutes; the player must paint the cells gold with care until the grid dissolves into a ward of faces, where a nurse at the end of a long night holds a patient's hand as the sun rises.",
            [
                "The prescription for physician burnout is written during the notoriously grinding hours of medical school and residency, combined with medical economics that demand more and more from physicians",
                "In a study of the 'emotional work' done by health care workers, mostly nurses, those whose work made them more upset lost track of their sense of mission, had poorer physical health, and most strongly wanted to leave their job",
                "The researchers concluded that the nurses' problems stemmed from 'catching' distress from the despair, anger, or anxiety of those they dealt with - negativity that threatened to spill over into their interactions with patients",
                "Nurses whose work allowed get-togethers and emotional connections had better physical health, a sense of a meaningful mission, and were far less likely to want to leave their jobs",
                "The more a nurse makes patients and their families feel good, the better she feels; the ratio of positive-to-negative emotional interactions is, to a great degree, in the nurse's own hands",
                "Continually listening to someone's worries often leads to 'compassion fatigue,' where a helper becomes overwhelmed by the anguish of those she tries to help - the solution is not to stop listening but to find emotional support",
                "In a compassionate medical setting, front-line people like nurses need help to 'metabolize' the inevitable suffering, and institutions must make sure staff have enough support themselves to be empathic without burning out",
                "Just as people whose work makes them vulnerable to repetitive stress injuries take stretch time-outs, those who do stressful emotional work can benefit from time-outs to calm down before re-entering the fray - but such breaks will never become routine until administrators value the emotional work as an essential part of the task",
                "Studies comparing superb leaders with mediocre ones find that the competencies distinguishing the best in human services have little or nothing to do with medical knowledge and everything to do with social and emotional intelligence - empathy, conflict resolution, and people development",
                "Joan Strauss, senior project manager for service improvement at Massachusetts General, notes that managers promoted on medical expertise rather than people skills sometimes need coaching to hold people accountable respectfully 'without being a patsy on the one hand or Attila the Hun on the other'",
                "Nancy Abernathy, teaching a seminar for first-year medical students when her husband died of a heart attack while cross-country skiing, found her room already partly full - her students from the year before had come simply to lend their presence and offer their support",
                "'This is compassion,' Abernathy testified, 'a simple human connection between the one who suffers and one who would heal' - and compassionate medicine needs caring leaders who can give medical staff the sense of a safe emotional base to work from",
            ],
        ),
    },
    {
        "num": 19,
        "title": "Chapter 19: The Sweet Spot for Achievement",
        "pages": "285-297",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Frazzle Detector",
            "Scan scenes of the classroom and the office for the frazzle signature: the ambulance moment that disorganizes your planning, the meeting where vacant eyes betray inner absence, the fear that freezes a workplace. Rate each brain's state - amygdala ascendant or prefrontal in command - before the cognitive-dysfunction alarm sounds.",
            "A neural dashboard over a classroom and an office: each person's brain shows the amygdala flaring red while the prefrontal hub dims, and a glowing upside-down U curve spans the wall with a needle reading Cognitive Efficiency at each scene.",
            [
                "'The Biology of Being Frazzled,' an article from the academic journal Science, opens with a driver who, after an ambulance screams up behind him, finds his thoughts disorganized and loses concentration - and berates himself for forgetting the cleaners",
                "'Frazzle' is a neural state in which emotional upsurges hamper the workings of the executive center; while frazzled we cannot concentrate or think clearly",
                "'Banish fear' was a slogan of the late quality-control guru W. Edwards Deming, who saw that fear froze a workplace - workers reluctant to speak up, share new ideas, or coordinate well",
                "Under stress the HPA axis roars into action and the amygdala commandeers the prefrontal cortex, the brain's executive center, favoring automatic knee-jerk responses as the high road moves too slowly",
                "The ascendant amygdala handicaps learning, holding information in working memory, reacting flexibly and creatively, focusing attention at will, and planning - plunging us into what neuroscientists call 'cognitive dysfunction'",
                "The neural highway for dysphoria runs from the amygdala to the right side of the prefrontal cortex, and as it activates our thoughts fixate on what triggered the distress",
                "When we are sad, activity levels in the prefrontal cortex drop and we generate fewer thoughts",
                "Boredom fogs the brain with its own brand of inefficiency: as minds wander, they lose focus and motivation vanishes",
                "The greater the anxiety we feel, the more impaired is the brain's cognitive efficiency, and because high anxiety shrinks the space available to attention, near-panic is the enemy of learning and creativity",
                "A friend described the worst period at work - the company restructuring with people 'disappeared' daily: 'No one could focus while that fear was in the air. No real work got done'",
                "Because high anxiety shrinks the space available to our attention, it undermines our very capacity to take in new information, let alone generate fresh ideas",
                "In any meeting that has gone on too long, the vacant eyes of those trapped at the table betray this inner absence, like students absently staring out the window on days of ennui",
            ],
        ),
        "dialogue": (
            "Dialogue: The Spanish Crossword Class",
            "Play the teacher guiding the crossword-puzzle game where partners give Spanish clues for the missing words, and feel the bell ring unheard at the end of class. Then switch seats and play a student pair swept into absorption, and finally the girl in the English class who slips the clothing catalog from her bag - and decide which state you will carry into the next day's essays.",
            "A sunny classroom where pairs lean over identical crossword grids, one copy glowing with filled words while partners gesture and laugh; the bell on the wall rings silently as no one moves, and across the hall a girl's hand reaches into her bag for a clothing catalog.",
            [
                "In a Spanish class game, partners had the same crossword puzzle - one copy with words filled in, the other with blanks - and had to help each other guess the missing words by giving clues in Spanish",
                "The students got so swept up in the game they were completely oblivious to the bell ringing at the end of class, and the next day their essays in Spanish showed excellent comprehension of the new vocabulary",
                "Sam Intrator, an educator, spent a year observing high school classrooms; whenever he witnessed an absorbing moment he canvassed the students, rating the moment 'inspired' if most reported a state of total involvement",
                "The inspired moments of learning shared the same active ingredients: a potent combination of full attention, enthusiastic interest, and positive emotional intensity",
                "University of Southern California neuroscientist Antonio Damasio says such joyous moments signify 'optimal physiological coordination and smooth running of the operations of life'",
                "Damasio argues that upbeat states allow a 'greater ease in the capacity to act,' a greater harmony in our functioning that enhances our power and freedom in whatever we do",
                "Cognitive scientists dub such conditions 'maximal harmonious states,' in which ease, efficiency, rapidity, and power are at a maximum and which we experience with a quiet thrill",
                "Imaging studies show that while people are in such exhilarating, upbeat states, the area of the brain that displays most activity is the prefrontal cortex, the hub of the high road",
                "Heightened prefrontal activity enhances mental abilities like creative thinking, cognitive flexibility, and the processing of information",
                "Radiologists work with greater speed and accuracy after getting a small mood-boosting gift, and their diagnostic notes include more helpful suggestions for further treatment",
                "Even physicians, those paragons of rationality, think more clearly when they are in good moods",
                "In the English class on commas, a student bored and distracted slipped her hand into her bag and discreetly pulled out a catalog for a clothing store - as though she had left one store in a mall for another",
            ],
        ),
        "audit": (
            "Audit: The Inverted-U Chartroom",
            "File every performance scene onto the upside-down U: the drowsy student on the boredom leg, the panicked chemist on the anxiety leg, the jubilant radiologist at the crest. Record the cortisol and norepinephrine traces for each, mark the tipping point where challenge melts into overwhelm, and note each person's set point where the U tips.",
            "A vast wall chart of the inverted U where scenes fly in like pins: a drowsy student near the left leg, a panicked student at a blackboard near the right, a jubilant radiologist at the crest; two colored traces mark cortisol and norepinephrine as they climb with stress.",
            [
                "Plotting the relationship between mental adeptness and the spectrum of moods creates what looks like an upside-down U with its legs spread a bit: joy, cognitive efficiency, and outstanding performance occur at the peak, with boredom along the downside of one leg and anxiety along the other",
                "The height of cognitive performance occurs where motivation and focus peak, at the intersection of a task's difficulty and our ability to match its demand",
                "At a tipping point just past the optimal state, challenge melts into overwhelm, the low road becomes increasingly active, and the brain hands the reins to the low road - the neural shift that accounts for the shape of the upside-down U",
                "Healthy levels of cortisol energize us for engagement, and positive moods elicit the mild-to-moderate range of cortisol associated with better learning",
                "If stress continues to climb after the optimal point, a second neural system kicks in to secrete norepinephrine at the high levels found when we feel outright fear, and the more stress escalates, the worse our mental efficiency becomes",
                "When these stress hormones reach a critical level, they enhance amygdala function but debilitate the prefrontal areas, which lose their ability to contain amygdala-driven impulses",
                "A modicum of pressure enhances motivation and focuses attention: up to a point, selective attention increases as pressure ratchets upward, and paying fuller attention means working memory operates with more cognitive efficiency",
                "Students with math anxiety have less attention available when they tackle a math problem, because their anxious worrying occupies the attentional space they need",
                "While we are distressed we don't think clearly, and we tend to lose interest in pursuing even goals that are important to us; when students are neither attentive nor happy in class, they absorb only a fraction of the information being presented",
                "Foul feelings weaken empathy and concern: managers in bad moods give more negative performance appraisals, focusing only on the downside, and are more disapproving in their opinions",
                "People differ in their set points for where the U tips: students who can take the most stress without disabling their cognition are unflappable at the blackboard and, as adults, would likely thrive as Wall Street traders",
                "We do best at moderate to challenging levels of stress, while the mind frazzles under extreme pressure",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: The Achievement Ledger",
            "Sort the students of the national math test into achievers and strugglers by the chemistry of their study sessions - focused pleasure about 40 percent of the time versus great anxiety 55 percent - and grade each teacher by the 910-first-grader study's four winning behaviors. Justify every call with the inverted-U reading on the card before the hippocampus's cortisol count decides the learning outcome.",
            "A sorting chamber where study-session gauges flash between focused pleasure and anxiety, a teacher's scorecard shows Tuned In, Upbeat, Positive Regard, and Flexible Rules, and a hippocampus hologram shrinks and swells with each cortisol reading.",
            [
                "A group of sixteen-year-olds scored in the top 5 percent on a national test of potential in math, yet some did poorly in their math class despite their aptitude",
                "The high-achieving students experienced focused pleasure about 40 percent of the time they were immersed in their studies - more often than they felt anxious (about 30 percent)",
                "While studying math, the low achievers experienced such optimal states only 16 percent of the time and great anxiety 55 percent of the time",
                "College students taking math exams scored 10 percent better when they were told the test was a practice than when they thought their score could win a cash prize for a team - and under social stress the deficit in working memory was greatest for the smartest students",
                "Almost half a century before, in 1960, Richard Alpert, then at Stanford, showed experimentally what every student already knew: high anxiety cripples test-taking ability",
                "The hippocampus, near the amygdala in the midbrain, is our central organ for learning, converting the contents of working memory held briefly in the prefrontal cortex into long-term storage",
                "The vast majority of neurogenesis - the brain's production of new neurons and laying down of connections - takes place in the hippocampus",
                "Under prolonged stress, cortisol attacks the neurons of the hippocampus; the actual killing off of hippocampal neurons occurs during sustained cortisol floods from severe depression or intense trauma, though with recovery the hippocampus regains neurons and enlarges again",
                "In a simulation, college students who got injections raising their cortisol remembered what they had studied when tested two days later in the mild to moderate range, but at extreme levels the cortisol impaired their recall by inhibiting the hippocampus",
                "New cells take a month to mature and four more to fully link to other neurons, and during this window the environment determines in part the final shape and function of the cell - the more conducive the atmosphere for learning, the better the encoding",
                "The type of stress that most activates the stress hormones lurks in the classroom, in the form of social threats like fears of a teacher's judgment or of seeming 'stupid' in the eyes of other students - and in a chemistry class where a teacher calls students to the board to calculate difficult interactions on the spot, it is a moment of pride for the bright kids and shame for the rest",
                "In a study of 910 first-graders from a national sample, trained observers found the best results when teachers tuned in to the child and responded to his needs, created an upbeat classroom climate, showed warmth and 'positive regard,' and had good classroom management with clear but flexible expectations - while the worst outcomes came from teachers who took an I-It stance and imposed their own agenda; at-risk students with a warm, responsive teacher flourished, learning as well as the other kids, and sixth-graders who had such a teacher earned better grades not only that year but the next as well",
            ],
        ),
        "boss": (
            "Boss Battle: The Leadership Contagion Chamber",
            "Command the fifty-six simulated teams: calibrate your displeasure to herd your people up the inverted U, never past the tipping point into the zone where panicked efforts produce bad decisions. Then become the secure base - the buffer, the listener, the best friend at work - and finally walk into Pamela's classroom and become Maeva's secure base before the semester's report card is stamped.",
            "A boardroom where the leader's mood radiates as colored waves washing over rows of seated people, a meter measuring how far each wave moves the team up or past the peak of the inverted U; the door to the toxic boss's office glows red while a report card waits on a desk at the far end.",
            [
                "Displays of a leader's displeasure make use of emotional contagion: if artfully calibrated, even a burst of pique can stir followers enough to capture their attention and motivate them, and well-titrated doses of irritation - like compliments - can energize",
                "A power dynamic operates in emotional contagion: emotions flow with special strength from the more socially dominant person to the less, because people naturally pay more attention to what the most powerful person says and does",
                "'When my mind is full of anger, other people catch it like the flu,' the head of a small organization told Goleman ruefully",
                "When a manager delivered a piece of bad news with a warm demeanor, people nevertheless rated the interaction positively; when good news was delivered with a sullen expression, the interaction paradoxically left people feeling bad",
                "In a study where fifty-six heads of simulated work teams were moved into good or bad moods, teams with upbeat leaders coordinated their work better and got more done with less effort, while teams with grumpy bosses were thrown out of synch and their panicked efforts to please the leader led to bad decisions and poorly chosen strategies",
                "While a boss's artfully couched displeasure can be an effective goad, fuming is self-defeating as a leadership tactic: relentlessly foul moods corrode the emotional climate, sabotaging the brain's ability to work at its best",
                "People recall negative interactions with a boss with more intensity, in more detail, and more often than they do positive ones - so the ease with which demotivation can be spread makes it imperative for a boss to leave uplifting emotions behind",
                "George Kohlrieser, a psychologist and professor of leadership at the International Institute for Management Development in Switzerland, observes that having a secure base at work is crucial for high performance: feeling secure lets a person focus, achieve goals, and see obstacles as challenges, not threats",
                "Anxious employees readily become preoccupied with the specter of failure, fearing that doing poorly will mean rejection or abandonment, and so they play it safe - while people who feel their boss provides a secure base are freer to explore, take risks, innovate, and take on new challenges",
                "A midlevel executive praised his boss as 'a superb buffer' who absorbed the financial performance pressures from headquarters rather than passing them down, unlike the head of a sister division who subjected employees to quarterly profit-and-loss evaluations for products that take two to three years to come to market",
                "In surveys of more than five million people working in close to five hundred organizations, one of the best predictors of how happy someone felt on their job was agreement with the statement, 'I have a best friend at work'",
                "In a survey of employees at seven hundred companies, the majority said that a caring boss was more important to them than how much they earned, and employees' liking for their boss was a prime driver of both productivity and how long they stayed - while in a New York City middle school, Pamela became Maeva's secure base: she discovered the thirteen-year-old's reading level was that of a kindergartner, and within four months Maeva had passed every class, and students who feel connected to school have lower rates of violence, bullying, vandalism, anxiety, depression, drug use, suicide, truancy, and dropping out",
            ],
        ),
    },
]
