# -*- coding: utf-8 -*-
"""Phase 2 chapter data for The Social Animal (Aronson & Aronson, 12th ed), chapters 5-9.
Each chapter: num, title, pages, domain, and 5 slots (scrub/dialogue/audit/matrix/boss),
each slot a 4-tuple (topic, player_mission, visual_frame_description, key_concepts[10-12]).
"""

D = "Social Psychology | Situational vs Dispositional"

CHAPTERS = [
    {
        "num": 5,
        "title": "Chapter 5: Mass Communication, Propaganda, and Persuasion",
        "pages": "171-219",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Who-Says-What-to-Whom Sweep",
            "Scan twelve persuasion scenes and tag each one by the three factors that make a communication effective: the source (who says it), the nature of the communication (how it is said), and the characteristics of the audience (to whom it is said). For each scene, name the factor doing the work and say whether the target is being moved through an opinion or a deeply held attitude.",
            "A news studio frozen mid-broadcast; the communicator's face, the words of the message, and the faces of the audience are each ringed in a different colored scanner light while a paradigm meter tallies which factor is driving the shift.",
            [
                "Persuasion occurs when communication from one person changes the opinions, attitudes, or behavior of another person",
                "An opinion is what a person believes to be true and is primarily cognitive and transient, while an attitude is an opinion that includes an emotional and evaluative component and is extremely difficult to change",
                "The three key factors in any persuasive attempt are the source of the communication, the nature of the communication, and the characteristics and mindset of the audience",
                "The news media influence opinions simply by selecting which events get exposure and how much exposure they get, based largely on entertainment value, so 'if it bleeds, it leads'",
                "A Gallup poll found 60 percent of Americans believed crime was on the rise even though crimes of all kinds had been steadily declining for 25 years, a distortion fed by violent media coverage",
                "Selective emphasis puts the media in a position not only of reporting events but of determining subsequent ones, as when heavy news coverage of suicides increased teen suicides (David Phillips's studies)",
                "More than 90 percent of preschool children asked for toys or food they saw advertised on television, and by the tenth grade only 4 percent of children believed ads told the truth most of the time",
                "Robert Zajonc showed that, all other things being equal, the more familiar an item is, the more attractive it is, even a silly nonsense word",
                "Northwestern Mutual jumped from thirty-fourth to third in name familiarity after two weeks of $1 million worth of advertising, and A&W Root Beer's market share rose from 15 to 50 percent after six months of TV ads",
                "The Willie Horton ads of the 1988 Bush-Dukakis campaign showed that when people are scared and angry, facts alone (like Dukakis's furlough statistics) are neither reassuring nor convincing",
                "Eli Pariser calls the personalized universe of information created by algorithms and social networks the filter bubble, which reinforces our beliefs invisibly so we think we are seeing reality",
                "The more educated and skeptical viewers believe they are immune to persuasion, but our sense of immunity can make us more susceptible to persuasion of all kinds",
            ],
        ),
        "dialogue": (
            "Dialogue: The Central Versus Peripheral Cross-Examination",
            "Play two jurors at once: one who weighs arguments systematically about reducing prison recidivism and one who gets scared and angry by a mug shot. For each pitch, decide whether it persuades by strong logic (central route) or by simple, irrelevant cues like a rhymed slogan or a familiar face, and then argue both sides of why the phrase 'If it doesn't fit, you must acquit' swayed a jury.",
            "A courtroom splits down the middle: the left half shows scales weighing argument strength while the right half flashes peripheral cues - a glowing glove, a rhymed slogan, a celebrity smile - and a cursor labeled 'which route?' hovers between them.",
            [
                "Richard Petty and John Cacioppo argued there are two ways people are persuaded: the central route, weighing arguments and considering relevant facts systematically, and the peripheral route, responding to simple, often irrelevant cues",
                "People who consider the strength of arguments about reducing prison recidivism are taking the central route; those who get scared and angry by the image of Willie Horton are taking the peripheral route",
                "Johnnie Cochran's rhyme 'If it doesn't fit, you must acquit' was persuasive not because of its logic but because people judging an argument can be influenced by the way it is phrased",
                "Matthew McGlone found college students were more persuaded by unfamiliar aphorisms that rhyme ('woes unite foes') than by the same ideas in nonrhyming form ('woes unite enemies')",
                "Frank Luntz's research showed people could be turned against an estate tax if politicians called it a 'death tax', which conjures the image of being unfairly penalized for dying",
                "Far more Americans approved of the Affordable Care Act than of Obamacare, although it was the same program",
                "ABC News's renaming of a USDA-approved meat additive as 'pink slime' cost producers their customers, showing words conjure powerful images that can overwhelm consideration of the facts",
                "If your aim is to persuade, you need strong, logical arguments for audiences that are knowledgeable and motivated, and high-quality peripheral cues for audiences that do not care or cannot comprehend",
                "Persuasion that gets people to process arguments systematically is much more likely to endure than persuasion based solely on peripheral cues",
                "Harold Hartmann's early study of voting preferences showed that individuals who received a primarily emotional message voted for the endorsed candidate more often than those who received a primarily logical message",
                "In the fluoridation referendum, opponents used an emotional leaflet picturing an ugly rat saying 'Don't let them put rat poison in your drinking water' and soundly defeated the logical pro-fluoridation campaign",
            ],
        ),
        "audit": (
            "Audit: The Source Credibility Field Log",
            "Spend an hour rating communicators on trustworthiness and expertise: a Nobel physicist, a communist party newspaper, a prize-winning engineer, a dishwasher, a mobster arguing for stricter courts, and a beautiful woman pitching an opinion. For each entry, note whether the person argues against their own self-interest or seems unaware they are being overheard, and log the credibility verdict.",
            "A broadcast studio with a walk of fame: each communicator steps onto a pedestal as a credibility meter swings between expert, trustworthy, self-interested, and persuasive, while a ledger auto-fills with audience impact scores.",
            [
                "Carl Hovland and Walter Weiss found that almost everyone who believed a claim about nuclear submarines came from J. Robert Oppenheimer changed their opinions, while very few shifted when the identical claim was attributed to Pravda",
                "A communicator is credible when he or she is both expert and trustworthy, the concept Hovland and Weiss substituted for Aristotle's 'good men'",
                "In the Aronson and Golden experiment, sixth-graders heard a speech on arithmetic from a prize-winning engineer or a dishwasher; prejudiced children were less influenced by the black engineer and unprejudiced children were more influenced by him than by the identical white engineer",
                "Joe 'The Shoulder' Napolitano, a fictional mobster and hit man, was totally ineffective arguing for lenient courts but extremely effective arguing for stricter, more powerful courts - as effective as a respected public official",
                "When people argue against their own self-interest, we infer that the truth of the issue is so compelling that they sincerely believe what they are saying",
                "Patrick Reynolds, heir to the R. J. Reynolds Tobacco fortune, took a strong public stand against smoking, and no one disputed his sincerity",
                "Elaine Walster and Leon Festinger found participants' opinions changed significantly more when they believed graduate students were unaware of their presence in the next room and were not trying to influence them",
                "Judson Mills and Aronson showed a beautiful woman could have a major impact on an audience's opinions on a topic wholly irrelevant to her beauty, and her impact was greatest when she openly told the audience she wanted to influence them",
                "Alice Eagly and Shelly Chaiken replicated the finding that more likable communicators are more persuasive and showed that we expect beautiful people to think the way we do",
                "People trust the confident speaker rather than one who hems and haws, but extreme confidence can rouse our suspicions if we suspect flimflam or an ulterior motive",
                "The same communicator may be regarded by some people as possessing high credibility and by others as possessing low credibility",
                "Celebrities and athletes can influence our cereal choices and opinions on trivial issues, but are unlikely to influence us on issues where we strongly disagree, such as gun control or abortion",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Fear, Forewarning, and Inoculation Trials",
            "Run a matrix of persuasion defenses: sort appeals by fear level (low, moderate, high), audience self-esteem, and the presence of specific instructions, then choose whether to inoculate the audience with a mild attack or warn them it is coming. Track which cells yield attitude change and which yield resistance.",
            "A laboratory grid glows with three axes - fear dosage, audience self-esteem, and instruction specificity - as needle gauges for compliance swing; a weakened-virus vial labeled 'inoculation' sits beside a megaphone labeled 'forewarning'.",
            [
                "The overwhelming weight of experimental data suggests that, all other things being equal, the more frightened a person is by a communication, the more likely he or she is to take preventive action",
                "Howard Leventhal's smoking and chest X-ray studies showed those who were most frightened were also most eager to stop smoking and most likely to get X-rays",
                "People with high self-esteem are most likely to take immediate action when frightened, while people with low self-esteem act if there is a delay and they know they can take action later",
                "Fear-arousing messages containing specific instructions about how, when, and where to take action are much more effective than generalized alarms with no recommendations",
                "In the tetanus shot campaign, 28 percent of students who were frightened and given specific instructions got the shots, while only 3 percent of those without instructions or high fear did",
                "Daniel Gilbert argues our brains evolved to be frightened by clear and present dangers, not gradual ones, so people are more afraid of terrorism and identity theft than of global warming",
                "Matthew McGlone's swine flu pamphlets showed people who read 'Swine flu may kill thousands of people this year' were significantly more likely to see the flu as frightening and to schedule a flu shot than those who read that people contract the flu",
                "William McGuire's inoculation effect: people who receive a brief communication they can refute are 'immunized' against a subsequent full-blown presentation of the same argument",
                "Inoculating people with the facts about 9/11 increased their resistance to subsequent conspiracy theory propaganda about that tragedy",
                "Jack Brehm's theory of reactance: when our sense of freedom is threatened, we attempt to restore it, so blatant or coercive messages trigger resistance",
                "Jonathan Freedman and David Sears found teenagers who were forewarned 10 minutes before a talk on why teenagers should not drive were less convinced than those who got no forewarning",
                "Madeline Heilman found the more intense the attempts to prevent people from signing a petition, the more likely they were to sign it",
            ],
        ),
        "boss": (
            "Boss Battle: The Propaganda Siege of the Media Citadel",
            "Defend a city of citizens against a 24/7 propaganda siege: fake news and filter bubbles on one front, emotional contagion on another, and identity appeals and moral outrage on the last. For each wave, deploy the correct countermeasure - inoculation, two-sided refutation, reactance triggers, or free inquiry - before the citizens vote on a war they never wanted.",
            "A walled city where citizens scroll glowing feeds; hostile banners - 'fake news', 'death panels', 'America Under Attack' - batter the gates while defenders arm a broadcast tower with inoculation speeches and a 'more speech, not enforced silence' banner unfurls.",
            [
                "Propaganda is defined as 'the systematic propagation of a given doctrine' and education as 'the act of imparting knowledge or skill', yet whether a message counts as one or the other depends largely on the viewer's moral values and ideology",
                "Fake news demonstrates that because it comes from so many unknown sources and is easy to package as real news, people rely on their existing ideas and social networks to decide what to believe",
                "Emotional contagion occurs when one person's emotional behavior triggers similar emotions and behaviors in observers, as with the 1982 Tylenol poisonings, where false alarms outnumbered verified cases of product tampering by seven to one",
                "The more coverage major television networks devoted to suicide, the greater the subsequent increase in suicides among teenagers, and suicides spike especially when a celebrity commits suicide",
                "Tweets containing words associated with moral emotions, such as outrageous or disgusting, tend to be re-tweeted more often than tweets with non-moral emotion words",
                "Moral elevation - witnessing virtue in others, such as in videos of real-life kindness - makes people many times more likely to say yes to a request for help or money",
                "Adam Grant nearly tripled donations from volunteer callers by arranging a five-minute meeting between them and a past recipient of the fellowship they were soliciting for",
                "Aronson's energy conservation study found auditors who used vivid language, like comparing cracks to a basketball-sized hole in the living room wall, increased homeowner improvements from 15 to 61 percent",
                "Christopher Bryan showed people are much more likely to vote if asked 'How important is it for you to be a voter?' than 'How important is it for you to vote?', and children help more when asked 'Who wants to be a helper?'",
                "The Texas 'Don't Mess With Texas' slogan, tapping into frontier pride and identity, cut litter on Texas highways roughly 72 percent between 1986 and 1990",
                "Well-informed audiences are more persuaded by a two-sided argument that refutes the opposition, while uninformed audiences are persuaded by whichever one side they hear",
                "John Stuart Mill argued in 'On Liberty' that we must allow the expression of ideas we dislike, and Justice Brandeis wrote that the remedy for fallacies and falsehoods is 'more speech, not enforced silence'",
            ],
        ),
    },
    {
        "num": 6,
        "title": "Chapter 6: Human Aggression",
        "pages": "219-269",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Intentional Harm Detector",
            "Scan twelve violent scenes and decide for each one whether it is aggression: check the actor's intention, whether harm is physical or verbal, and whether the act succeeded or missed. Then classify the source - instinct, culture of honor, frustration, or learned model - and flag any scene where the target is actually being dehumanized.",
            "A street frozen mid-action with each punch, insult, and gunshot trailed by a red intention-tag that glows only for deliberate harm; a biology chart of chimps and bonobos hangs in the background while an instinct-versus-learning meter wavers.",
            [
                "Aronson defines aggression as an intentional action aimed at doing harm or causing physical or psychological pain, so an angry friend throwing a beer bottle that misses is still aggression but a drunk driver's accident is not",
                "Thomas Hobbes in Leviathan argued humans are brutes in their natural state, while Rousseau's noble savage held that a restrictive society forces gentle creatures to become hostile",
                "Freud theorized human beings are born with an instinctual drive toward life (eros) and an instinctual drive toward death (thanatos) leading to aggressive actions",
                "Zing Yang Kuo raised a kitten in the same cage with a rat and found the cat refused to attack its buddy or any other rats, showing aggressive instincts can be curbed by early experience",
                "Rats raised in isolation still attack a fellow rat introduced into the cage using the same pattern of threat and attack as experienced rats, so in some species aggression needn't be learned",
                "Our closest genetic relatives are the aggressive chimpanzee and the peaceful bonobo, the 'make love not war' ape that defuses conflict with communal sex",
                "The Iroquois lived in peace for hundreds of years but became ferocious warriors when trade with Europeans brought competition with the Hurons over furs, showing aggression is an optional strategy shaped by circumstances",
                "Richard Nisbett showed homicide rates for white Southern males are substantially higher than for white Northern males, but only for honor-related killings and only in areas with a herding economy",
                "In the culture of honor experiments by Dov Cohen and Richard Nisbett, Southern white males responded to an insult with more aggression, spiking cortisol and testosterone, while Northerners tended to shrug it off",
                "Cultures of honor have rates of honor-related homicide five times higher than other regions, more than twice as many school shootings per capita, and higher rates of domestic violence",
                "The number one predictor of violence is gender: boys engage in more rough-and-tumble play, and in a cross-cultural study by Dane Archer and Patricia McDaniel, young men in all 11 countries showed a greater tendency to end conflict stories with violence",
                "James Dabbs found naturally occurring testosterone levels are significantly higher among prisoners convicted of violent crimes, but Robert Sapolsky argues testosterone does not cause aggression since aggression continues even after castration",
            ],
        ),
        "dialogue": (
            "Dialogue: The Thwarted-Goal Interrogation",
            "Interrogate the frustration-aggression connection by playing the experimenter in the roomful of toys: frustrate one group of children behind a wire screen while letting another play freely, then watch how each group handles the toys. Then switch sides and run the line-cutting field study, the charity phone call, and the capuchin monkey grape exchange to pin down when goals within reach, high expectations, and unfairness turn frustration into rage.",
            "A playroom bisected by a wire screen: on one side children press against the mesh watching the toys, on the other children play freely; a rage thermometer rises only on the frustrated side while a monkey hurls a cucumber at a researcher in the corner.",
            [
                "Roger Barker, Tamara Dembo, and Kurt Lewin frustrated young children by showing them a roomful of appealing toys kept out of reach behind a wire screen; when finally allowed to play, the frustrated group smashed and threw the toys while the non-frustrated group played joyfully",
                "Mary Harris's field study found people standing behind a student who cut into the second place in line became much more aggressive than those behind an intruder who cut in front of the twelfth person, since frustration is high when a goal is within reach",
                "James Kulik and Roger Brown found charity phone callers with high expectations spoke more harshly and hung up more forcefully when refused, and callers became more aggressive when refusals sounded arbitrary and illegitimate rather than affordable",
                "Sarah Brosnan and Frans de Waal found capuchin monkeys rewarded with cucumber slices became angry and even threw the cucumber when a nearby monkey received a grape for the same token, showing the perceived unfairness effect is so fundamental it appears in monkeys",
                "Frustration is most pronounced when the goal is within reach, when expectations are high, when the rule of fairness has been violated, and when the goal is blocked without a compelling reason",
                "Frustration is often the result of relative deprivation, the deprivation we feel when we see others enjoying a better situation or when we are deprived relative to our expectations",
                "Katherine DeCelles and Michael Norton found the presence of a first-class cabin produced four times as many aggressive 'air rage' incidents among economy passengers, especially when they had to walk through first class to board",
                "Most social revolutions are started not by the most oppressed but by people who have recently lifted their faces out of the mud and noticed others doing better, as Tocqueville observed about evils that become intolerable once escape seems possible",
                "The most intense African American riots of the 1960s took place not in the areas of greatest poverty but in Los Angeles (Watts) and Detroit, where conditions were better but the gap relative to whites was visible",
                "Shabaz Mallick and Boyd McCandless found frustrated third-graders directed much less aggression at a thwarting child when told he had been 'sleepy and upset'",
                "Hopeless people are apathetic people: Ugandans under Idi Amin and South African blacks under apartheid did not revolt while they were prevented from hoping for anything better",
                "The pain we receive always feels more intense than the pain we inflict: English neurologists found participants could not retaliate exactly in kind and always escalated pressure, making escalation 'a natural by-product of neural processing'",
            ],
        ),
        "audit": (
            "Audit: The Situational Trigger Field Log",
            "Walk through a heatwave city and log every situational trigger of aggression you find: a 90-degree testing room, a voodoo doll stabbed at low blood sugar, a rifle left lying on a table, a full bar fight, and a driver honking in traffic. For each entry, identify the trigger category - heat, pain, hunger, alcohol, weapons, rejection - and record the experimental evidence that proves it.",
            "A summer city street where every aggressive act is traced back to a glowing cause: thermometers over rooftops, a glowing rifle on a desk, cocktail glasses in a bar, and a voodoo doll bristling with pins in a kitchen window.",
            [
                "Leonard Berkowitz showed students who underwent the pain of having their hand immersed in excruciatingly cold water showed a sharp increase in committing aggressive acts against other students",
                "Brad Bushman's voodoo doll study of 107 married couples found spouses with the lowest blood sugar stuck more than twice as many pins in the doll and were more likely to blast their spouse with awful noises, the toxic combination of anger and hunger - being 'hangry'",
                "In the 'long, hot summer of 1967', 159 race riots erupted, and Merrill Carlsmith and Craig Anderson found riots were far more likely on hot days than cold days, while heat did not increase burglary or property crimes",
                "William Griffitt and Roberta Veitch found students who took a test in a 90 degree F room reported feeling more aggressive and expressed more hostility toward a stranger than students in a normal-temperature room",
                "In major league baseball, significantly more batters are hit by pitched balls when the temperature is above 90 degrees, and Phoenix drivers without air-conditioning honk more in traffic jams",
                "Alcohol serves as a disinhibitor that makes drinkers less cautious and impulsive, and it disrupts information processing so drunk people respond to the earliest, most obvious aspects of a situation and miss subtleties",
                "In the 'think-drink' effect study of 116 men, the actual quantity of alcohol the men drank was related less to their aggressive behavior than their expectations: the more alcohol they believed they were drinking, the more aggressively they behaved",
                "The weapons effect: college students angered in a room where a rifle was left lying around administered more electric shocks than those angered in a room with a badminton racket, and people drive more aggressively with a gun on the passenger seat",
                "Mark Leary's analysis of over 15 school shootings found acute or chronic rejection - ostracism, bullying, or romantic rejection - was present in all but two of the incidents",
                "Jean Twenge and Roy Baumeister found college students led to believe nobody wanted to work with them expressed far more intense hostility, even against neutral individuals, than students who had not been excluded",
                "Philip Zimbardo showed female students made anonymous with robes and hoods administered longer and more severe shocks, and Brian Mullen found the larger the mob in 60 lynchings between 1899 and 1946, the more heinous the atrocities",
                "Deborah Davis and Elizabeth Loftus found men who are drunk are less likely to interpret nonconsent messages accurately and women who are drunk convey less emphatic signs of refusal",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Media Violence and Catharsis Sorting Grid",
            "Sort a wall of evidence into five columns: catharsis studies, imitation studies, desensitization effects, hostile attribution bias, and the fear-of-crime magnifier. Decide for each card whether the finding supports venting anger or shows that venting backfires, and place the Bobo doll, the punching bag, the voodoo finger-pressure game, and the lambs-versus-lemmings game in their correct cells.",
            "A courtroom evidence wall covered with cards and video stills: a child punching a Bobo doll, a man slugging a punching bag, a gory boxing match, and a violent video game screen; a verdict banner asks 'Does venting reduce or increase hostility?' while the pointer swings to increase.",
            [
                "The belief in catharsis comes from Freud's hydraulic analogy that aggressive energy must be drained off lest it build up and explode, but abundant evidence indicates the 'hit a pillow' solution simply does not work",
                "Brad Bushman found participants who slugged a punching bag while thinking about the student who insulted them felt the most angry afterward, and later blasted their tormentor with the loudest, longest noise, while those who sat still felt least angry",
                "Arthur Patterson measured football players' hostility before, during, and after the season and found a significant increase in hostility over the course of the season, contradicting the idea that intense physical activity drains aggression",
                "Russell Geen found participants who had previously shocked a confederate delivered more frequent and more intense shocks the second time around, contrary to the catharsis hypothesis",
                "Laid-off technicians who were allowed to verbalize their hostility against their ex-bosses were much nastier in their subsequent descriptions of them than those who had not vented",
                "The more people ventilate anger by behaving aggressively, the angrier they remain and the more aggressive they become, and people who believe in catharsis act out more aggressively because they expect it to make them feel better",
                "Michael Kahn found students who vented hostility about a derogatory technician to his employer subsequently disliked him more and expressed greater hostility toward him than those not given the opportunity to vent",
                "In Albert Bandura's Bobo doll experiments, children who watched an adult knock around a plastic doll imitated the aggression hit for hit and kick for kick and invented their own new aggressive behaviors",
                "A meta-analysis of 98 studies with nearly 37,000 participants found both violent video games and prosocial video games have direct effects on their players",
                "Bushman and Anderson found participants who played a violent video game took five times longer to respond to a victim groaning in the next room, and people who had just seen a violent movie took longer to help a woman struggling with her crutches",
                "A longitudinal study of 430 elementary school children found that consumption of media violence early in the school year predicted higher rates of verbal, relational, and physical aggression and less prosocial behavior later in the year",
                "Gentile and Gentile found children who played many different violent games were more likely to develop a hostile attribution bias, interpreting the ambiguous behavior of others in a hostile manner",
            ],
        ),
        "boss": (
            "Boss Battle: The Violence Reduction Summit",
            "Take charge of a violence prevention summit and deploy each proven intervention: mild threats of punishment that produce internalization, rewarding nonaggressive alternatives, providing nonaggressive models, empathy training, and mindfulness. A crisis counselor will test you with the paradox cases - the smacking mother, the graffiti wall, the horn-honking drivers, and the bullying school - and you must choose the strategy the research actually supports.",
            "A school auditorium summit table surrounded by glowing strategy cards - punishment severity dials, empathy training videos, mindfulness bells, and cooperative game designs - while a city skyline beyond the windows dims as each intervention succeeds.",
            [
                "States that have the harshest punishment - the death penalty for murder - have higher murder rates than states without it, and a natural experiment from the Gideon v. Wainwright ruling found prisoners who served their full terms were twice as likely to return to prison as those released early",
                "Severe punishment, if administered promptly, frequently results in compliance but rarely produces internalization, and it teaches children 'so that's what I should do when I'm mad at someone: yell at them or hit them'",
                "Threats of mild punishment are far more effective than threats of severe punishment: with minimal external justification, the child internalizes a counteraggressive value and convinces himself that hitting someone is neither desirable nor fun",
                "Dan Olweus curtailed bullying in Norwegian schools by as much as 50 percent by training teachers to be vigilant and to take swift but moderate punitive action",
                "Seeing an aggressive model punished neither increases nor decreases a child's aggressive behavior, while seeing an aggressor rewarded increases it, so it is just as effective not to expose children to aggressive models at all",
                "Paul Brown and Rogers Elliot found nursery school teachers who ignored aggressive acts but were attentive when children shared and cooperated produced a noticeable decline in aggressive behavior",
                "Joel Davitz found children trained to behave constructively played far more constructively and less aggressively after frustration than children rewarded for aggressive, competitive behavior",
                "Robert Baron and Richard Kepner found participants who witnessed a person delivering intense shocks to their tormentor delivered more intense shocks, and those who saw mild shocks delivered milder shocks, showing aggression is a form of conformity",
                "In the horn-honking experiment, almost 90 percent of second-car drivers honked aggressively when the light turned green, but the percentage dropped dramatically when the pedestrian crossing was on crutches and evoked empathy",
                "Norma and Seymour Feshbach demonstrated a negative correlation between empathy and aggression in children, and Norma Feshbach's 30-hour empathy-training program made children more empathic, higher in self-esteem, more generous, and less aggressive",
                "Kenichi Obuchi found Japanese students administered much milder shocks to victims who first disclosed something personal about themselves, opening the door to empathy",
                "Lara Aknin's three-method research pinned down that behaving altruistically produces greater feelings of happiness, and even brief mindfulness training reduces mind-wandering and aggressive responses to provocation",
            ],
        ),
    },
    {
        "num": 7,
        "title": "Chapter 7: Prejudice",
        "pages": "269-319",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Three-Component Prejudice Detector",
            "Scan twelve scenes and split each one into its three components: the cognitive stereotype (the little picture in the head), the emotional gut feeling, and the behavioral discrimination. For each scene, name the category used - race, gender, weight, sexual orientation - and decide whether the stereotype is accurate, misleading, or a rationalization for hatred.",
            "A mindscape gallery where each person's head is split into three panels: one panel fills with a sketchy 'little picture' of the group, one glows red with gut feeling, and one shows an action of unfair treatment; an accuracy meter grades each stereotype.",
            [
                "Aronson defines prejudice as a negative attitude toward all members of a distinguishable group, based solely on their membership in the group, and it is partly cognitive, partly emotional, and partly behavioral",
                "Categorization, the grouping of people by key characteristics, is fundamental to cognition and can be the first step toward prejudice, and the fundamental category for social animals is us or them",
                "Newborns show no preference for faces of one race or another, but by three months of age babies in a mono-racial setting prefer faces of their own race, showing we are predisposed to like people like us and be wary of people who are different",
                "Walter Lippmann, the first to use the term stereotype, described the difference between reality - the 'world out there' - and the 'little pictures in our heads'",
                "Contrary to conventional wisdom, stereotypes are often accurate and can be an adaptive, shorthand way of dealing with complexity; Lee Jussim showed stereotype accuracy is among the strongest and most reliable findings in social psychology",
                "A stereotype that is accurate as a group average can be woefully incomplete and misleading when applied to an individual, as with the 'model minority' myth that torments a Chinese male who hates math",
                "Jeff Stone's experiment: students who believed basketball player 'Mark Flick' was African American rated him as having more natural athletic ability and playing a better game, while those who thought he was white rated him as having greater hustle and basketball smarts",
                "Birt Duncan showed people interpreted the same shove differently depending on who did it - aggression if a black man shoved a white man, playful if a white man shoved a black man - even when the interpreters were themselves black",
                "James Pennebaker wired up men and women with voice recorders and found both sexes used about 16,000 words per day, so the girls-talk-more stereotype is simply false",
                "Peter Glick and Susan Fiske found sexism worldwide takes two forms - hostile sexism, holding negative stereotypes of women, and benevolent sexism, holding positive but patronizing stereotypes that idealize women as needing protection",
                "In the hurricane naming study, raters thought male-named hurricanes were more intense than female-named ones and said they'd be more likely to evacuate for Hurricane Christopher than for identically described Hurricane Christina",
                "Oliver Wendell Holmes Jr. compared the mind of a bigot to the pupil of an eye: 'The more light you pour on it, the more it contracts', and as Allport put it, 'Defeated intellectually, prejudice lingers emotionally'",
            ],
        ),
        "dialogue": (
            "Dialogue: The Us-Them Interrogation",
            "Interrogate four causes of prejudice in turn: economic and political competition, displaced aggression and scapegoating, maintenance of status and self-image, and conformity to social norms. Play the experimenter in the Robbers Cave camp, the demagogue studying the 1949 speech analysis, the low-status sorority member, and the West Virginia coal miner to decide which cause each case actually demonstrates.",
            "A camp at Robbers Cave splits into the Eagles and the Rattlers squaring off over tug-of-war rope while a scapegoat runs through the woods; beside it a coal mine splits into an integrated shaft and a segregated town, and a demagogue's checklist floats over a rally stage.",
            [
                "Prejudice often results from economic and political competition: John Dollard documented that prejudice against newly arrived Germans in a small industrial town increased as jobs became scarce",
                "Attitudes toward Chinese immigrants in nineteenth-century America fluctuated with economic competition - 'depraved and vicious' while competing for gold, 'sober, industrious, and law-abiding' while building the railroad, and criminal and conniving again once jobs grew scarce",
                "In a 1970s survey, most anti-black prejudice was found in groups just one rung above black people socioeconomically, especially where whites and blacks competed closely for jobs",
                "In Sherif's Robbers Cave experiment, healthy, well-adjusted 12-year-old boys randomly assigned to the Eagles or the Rattlers became hostile and riotous after a series of competitions with prizes, and simply stopping the competition did not eliminate the hostility",
                "Scapegoating describes blaming innocent and powerless others for our troubles, tracing back to the ancient Hebrew ritual of placing the sins of the people on a goat that was sent into the wilderness",
                "Laboratory experiments suggest frustrated individuals displace aggression onto groups that are disliked, visible, and relatively powerless, but the form the mistreatment takes depends on what the ingroup approves of",
                "An analysis of demagogues' speeches throughout history found striking regularities: 'You've been cheated', 'there is a widespread conspiracy', 'our enemies are low animals', and 'behold, I am your leader'",
                "Self-justification preserves the self-image but intensifies hostility: if we can convince ourselves a group is subhuman or stupid, we feel free to enslave or aggress against it without questioning our own morality",
                "Jennifer Crocker found college women in low-status sororities expressed more prejudice and disparagement of other sororities than members of higher-status sororities, and low or declining social status predicts prejudice",
                "Steven Fein and Stephen Spencer found anti-Semitic students became especially biased against a woman they thought was Jewish if they received a low score on a supposed intelligence test, showing threats to self-esteem increase prejudice",
                "Thomas Pettigrew concluded the West Virginia coal miners' pattern - complete integration underground and complete segregation above ground - demonstrates that prejudice is often simply conformity to the prevailing norms of one's community",
                "Jeanne Watson found people who moved to a large city and came into contact with anti-Semitic people became more anti-Semitic themselves, while Pettigrew found Southerners entering the army became less prejudiced against blacks",
            ],
        ),
        "audit": (
            "Audit: The Hidden Bias Field Log",
            "Go undercover and log discrimination that hides in plain sight: resumes with black names versus white names, identical science-lab resumes with male versus female names, blind orchestra auditions, teachers watching children at play, and salespeople facing a fat-suit shopper with a diet soda or a milkshake. For each entry, identify the bias mechanism and judge whether the IAT would or would not have predicted it.",
            "A job market diorama: identical resumes float onto desks and get shuffled into a yes pile or a no pile, an orchestra auditions behind a screen, a woman in a fat suit drinks a milkshake in a department store, and an eye-tracking heat map shows teachers staring at a black boy at play.",
            [
                "African Americans are much more likely than whites to be arrested, convicted, and incarcerated for the same crime, and possession of crack cocaine carries more severe penalties than powder cocaine even though both are the same chemical",
                "Field experiments show applicants with black names like DeShawn or Queenisha are less likely to get called for interviews than applicants with names like Emily or Greg despite identical resumes",
                "Devah Pager sent matched pairs of well-groomed college graduates to 350 Milwaukee employers and found whites with a clean record were called back three times as often as black applicants with a clean record, and employers even preferred white convicts over black applicants with a clean record",
                "When science professors at leading universities evaluated resumes with randomly assigned male or female names, both male and female professors judged the male applicant as more capable, more worthy of hiring, and more deserving of a higher salary",
                "In 2014 the typical American woman earned about 77 cents for every dollar earned by a man, with African American women earning 64 cents and Latina women earning 56 cents, and the gap remains even after factoring in education and experience",
                "When symphony orchestras began blind auditions using a screen, the number of women hired shot up, and most orchestras are now evenly divided between male and female musicians",
                "The Implicit Association Test (IAT), developed by Mahzarin Banaji and Anthony Greenwald, measures the speed of people's positive and negative associations to a target group, and more than 15 million people have taken versions of it",
                "Banaji herself 'failed' the racial IAT, revealing antiblack associations she consciously repudiates, and writer Malcolm Gladwell was shocked by his own results, though the test's originators disagree about what it measures",
                "The evidence linking IAT scores with overt behavior is weak, and Adam Hahn found people were 'surprisingly accurate' in predicting their own responses, casting doubt on the claim that IAT results reflect unconscious attitudes",
                "When white students were told they would shock a black 'learner', they initially gave lower intensity shocks, but after overhearing the learner insult them they administered higher levels of shock than did students working with a white learner",
                "Christian Crandall and Amy Eshleman suggest people are attracted to justifications that let them express prejudice without feeling like bigots, avoiding the dissonance of being a fair person who dislikes a group",
                "In Eden King's fat suit study, salespeople treated an obese woman just as nicely as a thin one when she drank a diet soda, but smiled less, made less eye contact, and spoke more abruptly when she drank a milkshake",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Stereotype Threat and Attribution Grid",
            "Run a grid of stigma experiments: black students told a hard verbal test measures intelligence versus 'testing the test', women taking a math test after affirming a value, white male engineers told about Asian math superiority, and minority students writing self-affirmation essays. Place each in the correct cell of threat versus buffer and predict the performance outcome.",
            "A testing hall where identical exams float under different banners - 'measuring your intellectual ability' versus 'testing the test' - while anxiety meters rise and fall; beneath them, essays about personal values glow green as buffers against the threat.",
            [
                "Attributional ambiguity is the extra layer of complexity that makes members of minority groups unsure whether feedback about their work reflects their performance or the evaluator's prejudice",
                "Kent Harber found white evaluators gave overly positive feedback on poorly written essays when they believed the writer was black, being so eager to appear unprejudiced that they withheld the honest feedback students need to improve",
                "Marlene Turner and Anthony Pratkanis found women told they were selected for a job because the company needed more women later denigrated their own abilities and stopped trying as hard as women selected on the basis of merit",
                "Claude Steele and Joshua Aronson's stereotype threat research: black students who believed a difficult GRE verbal test measured their intellectual ability performed about half as well as black students who believed the investigators were merely testing the test",
                "White students performed equally well regardless of whether they believed the test measured intelligence, showing the evaluative framing itself activated stereotype threat for black students",
                "Stereotype threat also afflicts women working on math problems, Latinos on verbal ability tests, and elderly people on memory tests, and even white male engineering majors with near-perfect math SATs performed worse when told the test explored why Asians excel at math",
                "Matthew McGlone and Joshua Aronson found that reminding women about to take a spatial ability test that they were students at a highly selective university completely eliminated the male-female gap",
                "Exposing black test-takers to images of successful African American role models like W.E.B. Du Bois and Neil deGrasse Tyson eases their performance anxiety, and women who affirmed a personally important value scored as well as men under stereotype threat",
                "Geoffrey Cohen's school interventions found minority students improved their grades after a few writing assignments explaining why certain values were important to them",
                "Melvin Lerner showed people attribute personal responsibility for inequitable outcomes: if two people work equally hard and a coin flip gives one a reward, observers rate the unlucky person as having worked less hard",
                "Blaming the victim - 'If the Jews have been victimized, they must have been doing something wrong' - is motivated by the desire to see the world as fair and just, and negative attitudes toward the poor are more prevalent among those who believe most strongly the world is just",
                "Janet Swim and Lawrence Sanna analyzed more than 50 experiments and found a man's success is attributed to natural ability while a woman's is attributed to hard work, and a man's failure to bad luck while a woman's failure to not having what it takes",
            ],
        ),
        "boss": (
            "Boss Battle: The Desegregation Campaign",
            "Command a desegregated school under siege by hostility and self-segregated lunchtime clusters. Deploy the contact hypothesis, equal-status contact, superordinate goals, and the jigsaw classroom: divide the class into diverse six-person groups where each child holds one-sixth of Joseph Pulitzer's biography, and defuse the taunting of Carlos before the exam. Defeat the final wave by showing how cooperation changes 'those people' into 'us people'.",
            "A schoolyard where the lunchtime clusters of black, Latino, and white students slowly dissolve into mixed groups holding puzzle-piece cards; in a classroom, a nervous Mexican American boy recites his paragraph while other children learn to ask gentle, probing questions.",
            [
                "The contact hypothesis predicted that bringing black and white children into direct contact would replace stereotypes with real human beings, and Morton Deutsch and Mary Ellen Collins found white residents of integrated housing projects reported greater positive attitude change than residents of segregated projects",
                "Mere contact did not work in desegregated schools: schoolyards showed almost no integration, tension and turmoil rose, and Walter Stephan found no studies showing significant increases in self-esteem among black children while 25 percent showed significant drops",
                "For contact to reduce prejudice it must take place with equal status, since throughout history most white contact with blacks occurred in menial roles as porters, dishwashers, and domestic workers that perpetuated stereotyping",
                "Sherif reduced the Eagles-Rattlers hostility at Robbers Cave not by removing competition but by creating superordinate goals: the boys had to cooperate to repair the water-supply system and to pull the broken camp truck up a steep hill",
                "The key factor in reducing hostility is interdependence in reaching mutual goals - a situation in which individuals need one another to succeed",
                "Aronson invented the jigsaw classroom in 1971 to defuse the crisis of Austin, Texas, desegregation: each child in a diverse six-person group held one-sixth of a biography and needed the others to learn the material for the exam",
                "In the jigsaw classroom, when Mary ridiculed Carlos's accent the assistant told her that taunting would not help her learn about Joseph Pulitzer's young adulthood with the exam in less than an hour, shifting the reinforcement contingencies",
                "Children in jigsaw classrooms performed better on objective exams, liked each other better, developed greater liking for school and self-esteem, and formed friendships across ethnic and racial barriers, with absenteeism dropping",
                "Diane Bridgeman found 10-year-olds from jigsaw classes could take the perspective of the letter carrier who did not know why a boy cried over a toy airplane, while traditional-classroom children assumed everyone knew what they knew",
                "The jigsaw method works partly because cooperation breaks down ingroup-outgroup perceptions and creates a sense of 'oneness', and Leippe and Eisenstadt showed people who benefit others come to feel more favorable toward them - 'If I'm helping them, it must be because they deserve it'",
                "Jay Van Bavel and William Cunningham found white participants assigned to a mixed-race team showed more positive automatic evaluations of black ingroup members than white outgroup members, driven by ingroup bias more than outgroup denigration",
                "John McConahay called cooperative learning the single most effective practice for improving race relations in desegregated schools, yet educational systems resist change and the competitive classroom remains the norm",
            ],
        ),
    },
    {
        "num": 8,
        "title": "Chapter 8: Liking, Loving, and Connecting",
        "pages": "319-367",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Attraction Factor Detector",
            "Scan twelve couples at a party and tag what drew each pair together: proximity, attitude similarity, competence with a pratfall, physical attractiveness, being liked, or the paradox of choice. For each scene, name the factor, predict whether the pair will stick, and flag any couple where a gain or loss of esteem is doing the work.",
            "A party where every pair of guests is linked by a glowing thread labeled with its factor - 'same dorm hall', 'both love birdwatching', 'she spilled coffee', 'he complimented her' - while a matchmaker's ledger tracks which threads hold and which fray.",
            [
                "John Thibaut and Harold Kelley argued attraction is partly determined by our comparison level for alternatives - we calculate a person's value by comparing what they bring to us with what we might get from others",
                "College students randomly assigned to dorm rooms named their next-door neighbors about half the time when asked who they liked best, showing proximity fuels friendship",
                "James Brossard analyzed Philadelphia marriage records from the 1930s and found one in three marriages involved people who lived within five blocks, one in six on the same block, and only about one in five involved partners from different cities",
                "The more similar a person seems in attitudes, opinions, and interests, the more you like them: 'Opposites may attract, but they don't stick'",
                "We like people whose attitudes are similar to ours, and if we like someone for an irrelevant reason we assume they share our attitudes about politics, religion, and movies - causality runs in both directions",
                "Hunter Gelbach found that making teachers and students aware of five similarities they shared increased mutual liking and respect, especially among minority students",
                "In problem-solving groups, the participants considered most competent and having the best ideas tend not to be the ones best liked, because people who are too competent may seem unapproachable and make us look bad by comparison",
                "The pratfall effect, demonstrated by Aronson, Willerman, and Floyd: the superior quiz-show candidate who clumsily spilled coffee was rated most attractive, while the average candidate who spilled it was rated least attractive",
                "Abraham Tesser found we bask in the reflected glory of highly competent friends and relatives, but their attractiveness is diminished if their competence in areas that matter to us makes us feel inadequate by comparison",
                "A 1966 analysis of more than 29,000 people found physical attractiveness matters equally to both sexes, contradicting the belief that looks matter more to men",
                "Elaine Walster randomly matched incoming University of Minnesota students for a blind date and found the one determinant of whether they liked each other and repeated the date was physical attractiveness, not intelligence or personality scores",
                "Gregory White found that among young UCLA couples, it was the similarity of the partners' physical attractiveness that determined whether they stayed together over many months",
            ],
        ),
        "dialogue": (
            "Dialogue: The Beauty-and-Blunder Interrogation",
            "Interrogate the power of looks by running the classic studies yourself: pair blind-date students at random and ask which trait predicted a second date, show photos and predict future happiness ratings, grade classroom misbehavior reports with photos attached, and tape the intercom conversation where the man believes his unseen partner is beautiful. Then switch sides and decide whether the beautiful woman who criticizes you is liked or loathed.",
            "A dating lab with a wall of headshots; a misbehaved-child report slides in with an attractive face and gets excused while the same report with a plain face gets condemned; behind glass, an intercom hums as a woman's voice warms up for a man who believes she is gorgeous.",
            [
                "Karen Dion showed college students photos of attractive, average, and unattractive people and found the attractive were assigned the most desirable traits on all 27 ratings and given the greatest prognosis for future happiness",
                "Karen Dion also found women evaluating classroom disturbance reports blamed less attractive children more, inferring the incident was typical of their everyday behavior, while attractive children's misbehavior was excused as a situational aberration",
                "In the Aronson and Sigall experiment, a woman made to appear unattractive was liked about the same whether she gave favorable or unfavorable evaluations, but when beautiful she was liked a lot for favorable evaluations and disliked more than in any other condition when she criticized the men",
                "Mark Snyder, Elizabeth Decker Tanke, and Ellen Berscheid found that when men believed their unseen phone partner was beautiful, independent observers rated the woman's side of the conversation as more attractive, confident, animated, and warm - a self-fulfilling prophecy that treating someone as attractive brings out desirable qualities",
                "Attractive workers are often paid better and promoted more often, and the 'pro-beauty bias' begins at a very young age",
                "Female high school students who watched 15 beauty commercials ranked beauty-oriented attributes as more important than did a control group that watched unrelated commercials",
                "In sensitivity-training groups where people got acquainted by touch and voice with eyes closed, participants reported their prior stereotypes had been shattered by discovering that the 'funny-looking guy' was the warm, gentle person who had impressed them",
                "Evolutionary arguments that beauty preferences are hardwired are controversial because the round face and plump body that are gorgeous in Tonga may be unattractive in Tallahassee",
                "What is beautiful is good - but what is good becomes beautiful: people we dislike come to look less beautiful to us as we get to know them",
                "Jon Freeman points out that we bring tremendous psychological baggage to face perception, so evaluating mates mainly with our eyes on Tinder may make us miss wonderful people whose beauty requires more than a quick glance",
                "Half of all marriages end in divorce after about eight years, the question that opens the chapter's exploration of why some couples stay together till death like Annie Oakley and Frank Butler",
                "The Harvard study of 75 years of Boston men concluded 'Good relationships keep us happier and healthier. Period.', and the happiest men were those who had prioritized their relationships, not the most accomplished or wealthy",
            ],
        ),
        "audit": (
            "Audit: The Liking Ledger Field Log",
            "Keep a ledger of liking experiments: log what happens when someone is told you like them, when praise arrives with an ulterior motive, when an insecure student rates her admirer, when a coffee shop confederate is plain or pretty, and when a favor is done for you versus done by you. For each entry, enter the gain or loss on the scale and note whether the Dale Carnegie playbook actually worked.",
            "A bookkeeper's office where every interaction posts to a ledger with two columns - rewards given and costs paid - while a Franklin-style library book floats overhead and a speed-dating table glows with selectivity meters.",
            [
                "Rebecca Curtis and Kim Miller found people led to believe another person liked them disclosed more, disagreed less, and behaved more warmly, and were in fact subsequently liked, while those told they were disliked were disliked - another self-fulfilling prophecy",
                "Elaine Walster found female students who received negative personality test feedback liked the smooth young man who had made a date with them more than students who received positive feedback: the more insecure we feel, the more we like someone who likes us",
                "Sara Kiesler and Roberta Baral found male students led to feel insecure after a poor test performance showed more romantic interest toward a plain confederate, while secure students showed more interest toward an attractive one",
                "Paul Eastwick and Eli Finkel's speed-dating study found people who seemed likely to say yes to everyone were perceived as less desirable and having less chemistry, while those perceived as selective were more readily reciprocated",
                "Teresa Amabile found college students considered a negative novel reviewer considerably more intelligent, competent, and expert than a positive reviewer - but less likable",
                "Jason Lawrence found black female students who were praised with 'Great job!' on a test rated the white evaluator as significantly less polite, suspecting the praise revealed surprise about their performance",
                "Edward Jones found liking dropped sharply when an evaluator's praise came with a possible ulterior motive: 'flattery will get you somewhere - but not everywhere'",
                "Favors are rewards, but not if they come with strings attached that threaten the freedom of the receiver, as when a borderline student presents an expensive gift just before grading",
                "Benjamin Franklin won over a political enemy by asking to borrow a scarce, curious book from his library, and Jon Jecker and David Landy's experiment confirmed it 230 years later: students cajoled into returning their winnings as a special favor liked the experimenter best",
                "Tolstoy wrote in War and Peace, 'We do not love people so much for the good they have done us, as for the good we have done them'",
                "Aronson's gain-loss theory predicts we like someone whose liking for us increases over time more than someone who has always liked us, and dislike someone whose esteem decreases more than someone who always disliked us",
                "In the Aronson and Linder experiment, women in the gain condition (negative evaluations that became positive) liked the confederate significantly better than those in the all-positive condition, and a true gain requires an integrated, gradual change of heart",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: The Choice and Exchange Sorting Grid",
            "Sort dating profiles and relationships into a matrix: jam tables with 24 versus 6 varieties, Derek dismissing a beautiful Red Sox fan, exchange relationships keeping score, communal relationships responding to needs, and prenuptial agreements. For each card decide whether it belongs to the paradox of choice column or the exchange versus communal column, and predict whether the shopper buys, the couple sticks, and the friend pays the bill.",
            "A supermarket aisle where one table overflows with 24 gleaming jam jars and another holds six; beside it a relationship split-screen shows one couple splitting the dinner check to the penny while another partner watches a light panel to see if her loved one needs help.",
            [
                "Barry Schwartz's paradox of choice: people always say they want more options, but too many choices can impede us from making any decision at all and leave us less happy with the choices we finally make",
                "Sheena Iyengar's jam study: 60 percent of passersby stopped for the 24-jam display versus only 20 percent for the six-jam display, but only 3 percent of those with the wide array bought jam while 30 percent of those with the narrow array did",
                "Online dating turns every searcher into 'Derek', who deleted a beautiful, witty woman with a great job because she liked the Red Sox - an impossibility for the Derek of 1993, showing choice breeds pickiness and paralysis",
                "As Barry Schwartz concluded, unlimited choice leaves us comparing our current choice to a fantasy, 'and nobody can compete with a fantasy'",
                "Margaret Clark and Judson Mills distinguished exchange relationships, where people are concerned about reciprocity and equity, from communal relationships, where neither partner is keeping score and each gives in response to the other's need",
                "In the Clark and Mills light-monitoring experiment, participants paired with a stranger watched the lights more when a signal meant a possible reward, while participants paired with a close friend watched more when the signal meant the friend might need help",
                "Clark and Mills suggested prenuptial agreements are more likely to undermine than enhance the intensity of feelings, and someone who counts every penny at dinner is telling the other person they want an exchange rather than a communal relationship",
                "In an exchange relationship with a major imbalance, the person getting less feels angry or depressed while the person getting more feels guilty",
                "Partners in communal relationships are not totally unconcerned with equity but are relaxed about it, having faith that over the long haul things will even out",
                "The lonely widower's story and the Harvard study's George Vaillant capture the chapter's thesis: 'Connection is the whole shooting match'",
                "Lonely people have been found to have less efficient sleep patterns and higher blood pressure, and when wounded they heal more slowly than people who are not lonely",
                "Living single is perfectly healthy; half of American adults choose to live alone, and what causes problems is feeling alone and being isolated, not being single",
            ],
        ),
        "boss": (
            "Boss Battle: The Companionate Love Keep",
            "Defend a relationship through the two danger points: the passionate peak when couples dive in headfirst, and the fade when the dopamine high wears off after a year to 18 months. Deploy the right weapons at each wave - implicit theories of love, secure attachment, straight talk against Gottman's four horsemen, authentic disclosure, and the porcupine's dilemma balance - before the final boss: the Dotings' plateau of stagnant compliments.",
            "A relationship ark sailing past two whirlpools labeled 'dive in too fast' and 'the high wears off'; the deck holds cards for destiny versus growth beliefs, secure-attachment anchors, a four-horsemen armor set, and two porcupines huddling at a tolerable distance in the snow.",
            [
                "Love researchers distinguish passionate love, characterized by strong emotions, unquenchable sexual desire, and intense preoccupation with the beloved, from companionate love, a milder, more stable experience marked by mutual trust, dependability, and warmth",
                "Passionate love floods the brain with dopamine, the same neurotransmitter released by cocaine, and the high wears off after about a year to 18 months, when companionate love must arise to take its place",
                "Jonathan Haidt identifies two danger points: moving in or marrying too quickly at the peak of passion, and giving up when the initial phase fades, as couples who believe only obsessive love is real become repeatedly disappointed",
                "Spike W. S. Lee and Norbert Schwarz found that recalling conflicts made people with a 'soul mate' unity frame of love feel less satisfied with their relationship, but people who framed love as a journey were unaffected",
                "C. Raymond Knee's longitudinal study found 'destiny' believers' satisfaction depended on meeting ideal standards and they used avoidance coping, while growth believers remained more satisfied and worked to repair fraying seams",
                "Phillip Shaver, Cindy Hazan, and Mario Mikulincer describe adult attachment styles: securely attached lovers are rarely jealous, anxious lovers are clingy and fear abandonment, and avoidant lovers distrust intimacy and keep partners at a distance",
                "Attachment theory holds that children form internal working models of relationships from their parents' care, and the Minnesota Longitudinal Study found poorly attached children become the less-committed partners in adult relationships, creating a self-fulfilling prophecy of rejection",
                "Insecurely attached adults can be helped by a securely attached partner, and Eli Finkel's research with Ximena Arriaga found that the ability to trust the partner predicts a reduction in avoidant tendencies over time",
                "The porcupine's dilemma, from Schopenhauer's parable, is the desire to achieve deep intimacy while remaining invulnerable to hurt, and people who fear rejection place self-protection over self-revelation, losing the warmth of connection",
                "John Gottman identified four destructive forms of communication that predict marriage failure: hostile criticism, defensiveness, contempt (the most devastating sign), and stonewalling",
                "Fincham and Bradbury studied 130 newly married couples and found those who made dispositional attributions about their spouses became increasingly unhappy, while those who used straight talk and made situational attributions became increasingly happy",
                "Shelley Gable found people who received enthusiastic responses from partners when describing a triumph were happier with their relationship months later than those who received flat responses",
            ],
        ),
    },
    {
        "num": 9,
        "title": "Chapter 9: Social Psychology as a Science",
        "pages": "367-484",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Scientific Method Workbench",
            "Scan twelve claims about the social world and process each through the four steps of the scientific method: observe the phenomenon, make a guess about the lawful relationship, frame a testable hypothesis, and design an experiment that can confirm or disconfirm it. For each claim, decide whether it can be tested experimentally or whether, like Kennedy's Bay of Pigs popularity spike, you must experiment on the underlying phenomenon instead.",
            "A laboratory workbench where a wagon with a rolling rubber ball and a smiling waiter's tip jar are fed through four glowing stations - observe, guess, hypothesize, experiment - while a gauge stamped with Feynman's quote rejects beautiful guesses that fail the test.",
            [
                "The scientific method is the best way we humans have of uncovering lawful relationships among things, whether chemicals, planets, or the antecedents of human prejudice or love",
                "The steps of the scientific process are observation, a guess about why it happens, framing the guess as a testable hypothesis, and designing an experiment that will confirm or disconfirm the hypothesis",
                "As Richard Feynman put it, 'It doesn't matter how beautiful the guess is or how smart the guesser is, or how famous the guesser is; if the experiment disagrees with the guess, then the guess is wrong'",
                "There are no sacred truths in science - if a series of well-designed experiments fails to confirm a hypothesis, we give it up",
                "Social psychologists perform experiments because people are often unaware of why they act in certain ways, so simply asking people to explain their behavior usually will not yield reliable results",
                "When Kennedy's popularity rose after the Bay of Pigs fiasco, Aronson could not experiment on Kennedy himself but designed an experiment on the underlying phenomenon, testing whether a blunder makes a nearly perfect person more attractive",
                "In social psychology we are not studying chemicals in a beaker but adults who have lived in a social world their entire lives, bringing their own ideas and theories about what causes behavior",
                "Pavel Semonov distinguished science and art: as scientists we organize the unknown, as artists we reorganize the known to create something new, and a good social psychology experiment requires skills from both domains",
                "The prison college program case shows scientific skepticism: the prisoners who volunteered for the program may have differed from nonvolunteers in motivation and ability, so the lower recidivism rate proves nothing about the program's effects",
                "The New York State study found male inmates who completed college in prison had a recidivism rate 20 percent lower than average, but the comparison stacked the deck because the groups were not equivalent at the outset",
                "As scientists we must face our biases and preferences, but the scientific method lets us separate the wheat from the chaff to determine which programs are worthy of our time, effort, and money",
                "The science part of an experiment is easier to replicate than the art part, just as a chef's souffle recipe rarely survives the transfer to another kitchen",
            ],
        ),
        "dialogue": (
            "Dialogue: The Aronson-Mills Initiation Trial",
            "Play the experimenter behind the group-discussion screen: randomly assign sixty-three college women to a severe initiation, a mild initiation, or no initiation, let each eavesdrop on the same excruciatingly dull tape-recorded discussion of secondary sex characteristics, and collect their ratings. Then argue the case for why random assignment - not the fraternity survey - is the only way to know that severity of initiation causes liking.",
            "A theater of the absurd: women recite 12 obscene words behind a curtain, then listen through headphones to a recorded discussion of spider mating dances while a rating scale collects their verdicts; a judge's gavel hovers over 'the dependent variable'.",
            [
                "In the Aronson-Mills experiment, sixty-three college women who volunteered for discussions on the psychology of sex were randomly assigned to a severe initiation (reciting obscene words and explicit passages), a mild initiation, or no initiation at all",
                "The severity of initiation was the independent variable - the cause the experimenter manipulates - and the women's ratings of how interesting and worthwhile the discussion was constituted the dependent variable",
                "All participants heard the same incredibly dull tape-recorded discussion of the secondary sex characteristics of lower animals, yet women who suffered a severe initiation rated it as really exciting while mild- and no-initiation women rated it as dull",
                "The greatest advantage of the laboratory experiment is not control but random assignment: each participant has an equal chance of being in any condition, so uncontrolled variables are distributed randomly and cannot systematically affect results",
                "The hypothetical intelligent-wife study shows why correlation is not causation: happy men may attract intelligent women, or a third factor like wealth may cause both happiness and marrying an intelligent woman",
                "From survey data alone we cannot conclude severe initiations cause liking, because an elite group might require severe initiations, or a third variable like sadomasochistic tendencies could cause both severity and mutual liking",
                "The random assignment of children to watch a violent video or an athletic event neutralized personality differences across conditions, strongly suggesting watching violence can lead to violence",
                "To evaluate the prison college program properly, researchers should randomly select half of twice as many volunteers for the program and place the other half in the control condition",
                "The experimental method eliminates third-variable explanations in one fell swoop: sadomasochists have just as much chance of being assigned to the no-initiation condition as to the severe-initiation condition",
                "A survey showing severe-initiation fraternity members like each other more provides evidence of a positive correlation, but says nothing about cause and effect",
                "An experiment must have impact on participants as well as control, and the difficulty is that these two crucial factors often work in opposite directions - as one increases the other tends to decrease",
                "Merrill Carlsmith and Aronson distinguished experimental realism, whether the experiment has impact and forces participants to take it seriously, from mundane realism, whether the laboratory situation resembles everyday life",
            ],
        ),
        "audit": (
            "Audit: The Correlation-Versus-Causation Field Log",
            "Walk through a field of natural observations - TV violence and childhood aggression, prison education and recidivism, smart wives and happy husbands, newborn imitation - and audit each one for confounds. For every entry, propose the hidden third variable and then redesign the study with random assignment so the causal arrow can finally be trusted.",
            "A countryside of observations: a living room where violent TV hours and playground punches rise together, a prison classroom with a recidivism chart, a nursery where babies mirror tongues, and a wedding where happiness and intelligence swirl in a fog of possible causes.",
            [
                "The correlation between children's TV violence watching and their aggressive problem-solving does not prove causation, because aggressive children may simply like to watch aggression",
                "The experiment that randomly assigned children to a violent video or an athletic event found those who watched violence behaved more aggressively afterward, showing the causal link",
                "Replication, in which the original study is repeated by other investigators in other labs, clarifies for whom and under what conditions a finding applies and whether it is robust or a fluke",
                "If scientists are unable to duplicate original results, either they did not replicate accurately or the original investigators' conclusions were limited or wrong",
                "A well-done 1970s study seemed to show newborn infants imitate adults' facial expressions, but a much better-controlled recent experiment found this imitation skill is learned, beginning at about six months of age",
                "The minority-student values essay intervention did not replicate everywhere - it works only in schools where minority students feel a great deal of prejudice against them",
                "Several viral findings failed replication: age-related words making young people walk slowly, hand-washing reducing guilt, watching eyes increasing honesty, oxytocin increasing empathy, and warm coffee making people feel more loved",
                "The alleged 'power pose' that went viral through a TED talk failed most replications, and Joseph Simmons and Uri Simonsohn's statistical analysis of 33 studies concluded the evidence was too weak to advocate power posing",
                "Pop social psychology findings that fail replication do not mean the basic methods of experimentation are at fault - science is moving along as it should, correcting its mistakes",
                "The public should be wary of sensational, improbable, or simplistic findings and ask, 'But have they been replicated?'",
                "A failed replication sometimes catches a mistake in the original experimenters' procedures or analysis, and sometimes reveals a missing ingredient that was crucial to the original research",
                "Milgram's obedience experiment was low in mundane realism - we are rarely asked to deliver shocks in everyday life - but high in experimental realism, as his twitching, stuttering participants demonstrated",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: The Deception and Realism Sorting Grid",
            "Sort every study on the board by realism type and deception status: Milgram's shock lab, the Asch line judgment, the Aronson-Mills embarrassment test, the eavesdropping discussion, and the staged intercom conversations. For each card, check the cover story cell, the participant-knows-the-truth cell, and the 'looking good' cell, then decide where the deception was ethically required for valid data.",
            "A film director's storyboard wall where each experiment is a scene with its cover story on a clapperboard; a sign flashes 'Do not tell the actor what the play is about' while a monitoring room shows participants straining to look good.",
            [
                "Deception is frequently necessary because participants, who are always amateur social psychologists, will behave in ways consistent with their own hypotheses if they know the true purpose of the study",
                "Cover stories like the Aronson-Mills 'test for embarrassment' increase experimental realism by letting participants act naturally without knowing which behavior is being studied",
                "Participants who know an experiment's purpose either try to perform in a way that puts themselves in a good light or try to help the experimenter make the study come out as they think it should - both outcomes are disastrous",
                "When told a particular outcome indicated a good personality trait, participants worked to produce that outcome far more often than when told it reflected a negative trait",
                "The Asch conformity experiment used deception because almost no one would conform if told in advance they were being tested for conformity, since conformity is considered a weak and unattractive act",
                "In Milgram's obedience experiments around 65 percent of average citizens administered intense shocks, yet only about 1 percent of students predict they would obey - evidence that people, given half a chance, will try to look good",
                "Without deception we would get a picture of how people would like to be rather than a picture of how people are",
                "Deception presents three ethical problems: it is simply unethical to lie to people, it frequently leads to an invasion of privacy when participants cannot give informed consent, and procedures often entail pain, boredom, anxiety, or embarrassment",
                "Robyn Dawes, Jeanne McTavish, and Harriet Shaklee's social dilemma experiments seemed innocuous with no deception, yet one man telephoned 24 hours later to return his $190 winnings because he felt miserable about defecting, showing no code of ethics can anticipate all problems",
                "Social psychologists work on an ethical dilemma between two values they subscribe to: free scientific inquiry and the dignity of humans with their right to privacy",
                "Aronson advocates a cost-benefit analysis: compare the benefits to science and society against the costs to the participants before deciding whether a procedure is ethical",
                "Leonard Bickman and Matthew Zarantonello found that people who read that a high proportion of Milgram's participants had been fully obedient rated the procedure as more harmful and less ethical than those told hardly anyone had obeyed",
            ],
        ),
        "boss": (
            "Boss Battle: The Ethics of the Science Council",
            "Stand before the ethics council defending five experiments - Milgram's obedience lab, the Asch line study, the initiation embarrassment test, the Dawes social dilemmas, and Aronson's cheating at cards - against charges of lying, invasion of privacy, and discomfort. Win each round by applying Aronson's five guidelines: avoid intense pain, offer the real option to quit, seek alternatives to deception, debrief thoroughly to restore dignity, and never run a study 'just for the hell of it'.",
            "A marble hearing chamber where a projector plays clips of twitching, stuttering participants and a defector returning his winnings; five golden guidelines engraved on the wall glow one by one as each case is acquitted, and a scientist's oath against misuse of findings scrolls beneath the bench.",
            [
                "Aronson's five guidelines: avoid procedures that cause intense pain or discomfort, provide participants the real option to quit, be alert to alternative procedures to deception, debrief participants carefully to protect their dignity and leave them feeling good, and never undertake an experiment relying on deception or discomfort just for the hell of it",
                "During debriefing, experimenters should carefully explain the true purpose of the experiment and the reasons for the deception, going out of their way to avoid making participants feel stupid or gullible for having fallen for it",
                "Milgram worked hard after the experiment to make the experience useful and exciting for participants: several weeks later 84 percent were glad they had taken part, 15 percent felt neutral, and only 1 percent were sorry",
                "A university psychiatrist who interviewed a random sample of Milgram's participants a year later found no evidence of injurious effects, with the typical response being that participation was instructive and enriching",
                "Milgram confided that he believed much of the ethical criticism was fueled by the results he obtained rather than by the actual procedure he employed",
                "The ethics of any experiment seem less problematic when the results tell us something pleasant or flattering about human nature than when they tell us something we would rather not know",
                "Milgram's obedience experiment taught us a great deal about human behavior, and Aronson concludes he is glad Milgram went ahead with it despite the controversy",
                "A social psychologist's decision to run an experiment depends on an assessment of its potential costs and benefits, even though we can never be absolutely certain of either in advance",
                "Many participants have argued that self-discovery, such as Asch's participants learning they would conform, has therapeutic or educational benefit, but this does not in itself justify the procedures",
                "The knowledge described in this book rests on the cooperation of tens of thousands of individuals who allowed their behavior to be studied, and our understanding rests on techniques that are well controlled and influential without violating the essential dignity of participants",
                "The mechanisms of self-persuasion are powerful because the persuaded never know what hit them, and they can be used to get people to floss their teeth or to vote for particular candidates",
                "Aronson names his own responsibilities: to educate the public about how social-psychological knowledge might be used for the greater good, to remain vigilant against its abuse, and to promote good research aimed at furthering our understanding of us social animals",
            ],
        ),
    },
]
