# -*- coding: utf-8 -*-
"""Phase 2 chapter data for Social Intelligence: The New Science of Human
Relationships (Daniel Goleman), Part III (Nurturing Nature) and Part IV
(Love's Varieties): Chapter 10 (Genes Are Not Destiny), Chapter 11
(A Secure Base), Chapter 12 (The Set Point for Happiness), Chapter 13
(Webs of Attachment), Chapter 14 (Desire: His and Hers). Each chapter:
num, title, pages, domain, and 5 slots (scrub/dialogue/audit/matrix/boss),
each slot a 4-tuple (topic, player_mission, visual_frame_description,
key_concepts[10-12]).
"""

D = "Social Neuroscience | Relationships | Emotional Connection"

CHAPTERS = [
    {
        "num": 10,
        "title": "Chapter 10: Genes Are Not Destiny",
        "pages": "162-172",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Inhibition Detector",
            "Scan a parade of four-month-olds facing a stream of novel toys and ring the tell in each: the baby who loves the onslaught of novelty versus the one who cries so hard he shakes in protest. Then switch to Crabbe's mouse laboratories and judge whether each mouse's behavior is the same in Portland and Albany, stamping every scene with its verdict on gene expression before the case file seals itself.",
            "A baby laboratory turned diagnostic theater: infants in baby seats face a carousel of novel toys while a scanner ring paints each child's amygdala in red-hot overreaction, and an interlab map of Portland, Albany, and a third city flickers with the same mouse strain behaving differently in each.",
            [
                "Four-month-olds shown a toy they've never seen, then another twenty seconds later and another after that: some babies love this onslaught of novelty, while others hate it, crying so hard they shake in protest",
                "Babies who hate novelty grow into toddlers wary of strange people and places—'inhibited' in Kagan's term—whose inhibition shows up as shyness once they reach school",
                "Kagan speculates the shyness is due to an inherited neurotransmitter pattern that makes the amygdala more excitable, hyperarousing these kids at startling things and novel events",
                "Crabbe's alcohol-loving mouse strain C57BL/6J, one of a hundred or so inbred strains useful for medical research, chose the 'rodent martini' far more often than did other mouse strains",
                "Every mouse in a given inbred strain is, in effect, a clone of every other such mouse—they share their genes like identical twins",
                "In Crabbe's three-laboratory test at the identical point (April 20, 1998, between 8:30 and 9:00 A.M., with identical Purina feed, age, shipping history, and apparatus), strain BALB/cByJ was very anxious in Portland but quite adventurous in Albany",
                "'If genes were all, you'd expect to find no differences whatever,' Crabbe noted of the lab-to-lab anxiety differences",
                "Crabbe bets that mice can 'read' the emotional state of the person handling them—one research assistant, allergic to mice, wore a respirator while holding them",
                "In gene expression, essentially, a bit of DNA makes RNA, which in turn creates a protein that makes something happen in our biology",
                "Of the thirty thousand or so genes in the human body, some are expressed only during embryonic development then shut off forever, while others turn on and off constantly; some express themselves only in the liver, others only in the brain",
                "The methyl molecule, one of the mechanisms of epigenetics, not only turns genes on or off but also tones down or speeds up their activity, and helps determine where in the brain the more than 100 billion neurons end up",
                "Crabbe's finding stands as a landmark in 'epigenetics,' the study of ways the experiences we undergo change how our genes operate—without altering our DNA sequence an iota",
            ],
        ),
        "dialogue": (
            "Dialogue: The Kagan Babies Interview",
            "Take the role of the boy identified as inhibited in infancy who learned to feel his fear and act anyway, and walk him through his small victories—the dentist who won his trust, the pool his sister jumped into, the bad dream he learned to calm alone. Then switch seats and interview Kagan on the top floor of William James Hall: does the amygdala still overreact even when the behavior has changed, and what exactly did the fMRI show in those twenty-two kids?",
            "The top floor of William James Hall, the tallest tower on the Harvard campus: Kagan's old office overlooks Boston while a grown 'Kagan baby' sits across the desk, his fMRI scan glowing on the wall with a still-overreactive amygdala and a colliculus readout spiking at a picture of a baby's head on a giraffe's body.",
            [
                "Kagan has studied the inhibited babies' trait for close to three decades and, by now semiretired, still follows some of the 'Kagan babies' into their early adult years",
                "In an fMRI study of twenty-two Kagan babies, identified as inhibited as children and now in their twenties, their amygdalas still overreacted to anything out of the ordinary just as they had done before",
                "One neurological indicator of the timidity profile appears to be higher activity in the colliculus, a part of the sensory cortex that is activated when the amygdala detects something anomalous and possibly threatening",
                "The colliculus circuitry triggers whenever we perceive a discrepancy, like a picture of a baby's head on a giraffe body—the images need not be outright threats, anything strange-looking or 'crazy' will do the trick",
                "Kids who have low reactivity in these circuits tend to be outgoing and sociable, while highly reactive youngsters shy away from anything unusual; the novel frightens them",
                "Kagan discovered that when parents encourage these timid kids to spend time with peers they might otherwise avoid (sometimes parents have to be forceful), the children can often overcome the genetic predisposition to shyness",
                "After decades of research, among children identified shortly after birth as 'inhibited,' only one-third still showed timid behavior as they entered early adulthood",
                "'Seventy percent grow toward health. Temperament may constrain what can be, but it does not determine it,' Kagan said of the inhibited children",
                "One formerly inhibited boy overcame his fear of shots by finally finding a dentist who won his trust, learned to swim after seeing his sister jump into the pool, and eventually calmed himself after bad dreams—writing, 'Because I now understand my predisposition towards anxiety, I can talk myself out of simple fears'",
                "Kagan's granddaughter, very shy at six, told him: 'Make believe I don't know you—I have to practice not being shy'",
                "Neuroscientists use the term 'neural scaffolding' for how a laid-out brain circuit's connections strengthen with repeated use, explaining why an established behavioral pattern requires effort to change—though new opportunities or effort and awareness can lay down a new track",
                "Kagan's books, with titles like Galen's Prophecy, suggest his fluency with philosophical as well as scientific issues, and his late-1970s claim that inhibition had biological causes ran against an ethos that traced every childhood problem to an error in parenting",
            ],
        ),
        "audit": (
            "Audit: The Gene Expression Ledger",
            "File every experimental finding under the right entry in the ledger of gene expression: which results demonstrate that possessing a gene is not the same as expressing it, and which show the environment turning genomic on-off switches. For each entry, note the mechanism—methyl, diet, handling, or the mother's licking and grooming—and flag every case that strikes another blow against the naive view of genetic determinism.",
            "A genomics ledger bound in lab-coat white where every entry splits into DNA, RNA, and protein columns; a methyl-molecule cursor toggles switches across a wall of gene lights while a balance scale weighs the nurturing mother's lick-and-groom count against the neglectful one's.",
            [
                "Crabbe's now-famous, simple experiment, featured in the prestigious journal Science, showed that minor differences from one laboratory to another—such as how the mice were handled—created disparities in behavior, which implied a difference in how the identical genes acted",
                "Epigenetics shows how our environment, translated into the immediate chemical surround of a given cell, programs our genes in ways that determine just how active they will be",
                "The food we eat contains hundreds of substances that regulate a host of genes, turning them on and off like flickering Christmas tree lights",
                "A bite of broccoli offers a dose of vitamin B6, which spurs the tryptophan hydroxylase gene to produce the amino acid L-tryptophan, which helps synthesize dopamine, a neurotransmitter that stabilizes mood",
                "It is biologically impossible for a gene to operate independently of its environment: genes are designed to be regulated by hormones from the endocrine system and neurotransmitters in the brain, some of which are profoundly influenced by our social interactions",
                "'Social epigenetics is part of the next frontier in genomics,' says Crabbe—'another blow against the naive view of genetic determinism: that our experiences don't matter—that genes are all'",
                "In an adoption natural experiment, children born into families with a history of aggressive, belligerent violence adopted by peaceable families showed just 13 percent displaying antisocial traits as they grew up, versus 45 percent of those adopted into 'bad homes' where aggression had free rein",
                "Michael Meaney of McGill University identified a singular window in development—the first twelve hours after a rodent's birth—during which a crucial methyl process occurs, and how much a mother rat licks and grooms her pups in that window determines how the brain chemicals that respond to stress will be made for the rest of the pup's life",
                "Pups born to the most devoted mothers, who licked and groomed the most, grew up with denser connections between their brain cells, particularly in the hippocampus, the seat of memory and learning, and were especially clever at finding their way around a physical layout",
                "The offspring of less nurturing and inattentive mothers ended up with less dense connections between neurons and scored poorly on solving mazes—the 'IQ test' equivalent for mice",
                "Rat pups completely separated from their mothers while still quite young suffer a crisis that flips off protective genes, leaving them vulnerable to a biochemical chain reaction that floods the brain with toxic stress-triggered molecules, and they grow up easily frightened and startled",
                "The human equivalents of licking and grooming seem to be empathy, attunement, and touch—and how we treat our children will, in turn, set levels of activity in their genes",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: Nature or Nurture",
            "Sort a stream of evidence—adoption statistics, twin-study percentages, family scenes, and gene-expression patterns—onto the two pans of the nature-nurture scale, then decide when the old distinction itself dissolves. Justify every placement by quoting the finding behind it, and reject any case built on the fallacy that genes and environment are independent of each other.",
            "A twin dial scale in a stepfamily living room: nature weighs one pan and nurture the other while 720 pairs of teenagers stream past to be sorted—identical twins, fraternal twins, and every variety of stepsibling—and above them glows the rectangle analogy of the two entangled causes.",
            [
                "The century-old debate on nature versus nurture turns out to be pointless, based on the fallacy that our genes and our environment are independent of each other—'it's like arguing over which contributes more to the area of a rectangle, the length or the width'",
                "In the 1980s Plomin startled the scientific world with adopted-twin data asserting a teenager's scholastic ability is about 60 percent due to genes, the sense of self-worth only about 30 percent genetic, and morality but 25 percent",
                "Plomin and others using his method came under scientific fire because they typically assessed impacts only in a limited range of families, mainly twins raised by biological parents compared with those raised by stepparents",
                "The Reiss group at George Washington University—with Mavis Hetherington, an expert on stepfamilies, and Robert Plomin—demanded 720 pairs of teenagers spanning the entire range of genetic closeness in six specific family configurations, with stepparents married at least five years",
                "The Reiss group research found that every child experiences the very same family in sharply idiosyncratic ways—blowing to bits the 'one-family-one-environment school of thought'",
                "Children vie to be unique, which results in their being treated differently, and these unique-to-one-child aspects of family life turned out to have great power in determining a child's temperament above and beyond any genetic influences—making them epigenetic wild cards",
                "A teenager's sense of overall self-worth depends much on how the child has been treated and almost not at all on genetics—and once formed, it shapes her behavior quite apart from the ministrations of parents, the pressures of peers, or any genetic given",
                "A child's genetic givens in turn shape how everyone treats him: parents naturally cuddle with babies who flirt and hug back, while testy or indifferent babies get less cuddling",
                "When a child's genetics lead him to be irritable, aggressive, and difficult, parents tend to respond with harsh discipline, tough talk, and criticism, worsening his difficult side in a vicious spiral that evokes more parental negativity",
                "James Watson—Nobel laureate for the double-helix discovery with Francis Crick—admits to a hair-trigger temper but says he gets over his anger quickly, standing toward the better end of the spectrum of how the anger-inhibiting gene can operate",
                "In the weaker pattern of that aggression gene, the person expresses extra-small amounts of the enzyme that controls aggression, angers easily, stays much angrier, is more prone to violence, and can readily end up in prison",
                "The warmth of parents, how limits are set, or myriad other ways a family operates help set the expression of many genes, but a bossy sibling or screwy buddy both have their impact—the old, clear distinction between genetics and the social world blurs substantially",
            ],
        ),
        "boss": (
            "Boss Battle: Use It or Lose It",
            "Stand at the crossroads of the sculpting brain and rule on every circuit that streams past: which connections get strengthened, which get pruned like twigs, and which newborn neurons get to wire themselves into the social brain. Forge the neural trail through the snow of experience—attuned peekaboo against the clicking tongue—and decide what gets imprinted before the optimal windows close.",
            "A snow-covered Nevada schoolyard at dawn where young Milton Erickson's circuitous first track through the snow hardens by day's end into the one fixed route everyone follows; beneath the snow, a cross-section of a growing brain shows circuits pruned like twigs while newborn neurons migrate, each about to make its ten thousand connections.",
            [
                "Milton Erickson's tale of the first track through the snow, and the repeated traversing that followed it, offers an apt model for how neural pathways are laid down in the brain: the first connections become strengthened each time the sequence is followed until they become the automatic route",
                "The adage 'use it or lose it' refers to this ruthless neural Darwinism, where brain circuits vie with one another to survive; the neurons lost are 'pruned,' disappearing like twigs cut from a tree",
                "Over the course of childhood and the teen years, the brain selectively loses half those overabundant neurons, keeping the ones that are used and dropping those that are neglected, as the child's life experiences—including relationships—sculpt its brain",
                "The brain and spinal cord contain stem cells that turn into new neurons at the rate of thousands a day; the pace of neuron creation peaks during childhood but continues into old age",
                "A new neuron migrates to its position and over the course of a month develops to make about ten thousand connections, then refines them over the next four months until the pathways are locked in—'cells that fire together wire together'",
                "During that five-or-six-month period, personal experience dictates which neurons the newborn cell will connect with, and Meaney has found that in mice repetitive learning speeds the rate at which new neurons integrate into circuits",
                "Each brain system has an optimal period during which experience maximally shapes its circuitry: sensory systems are largely shaped during early childhood, and language systems mature next",
                "The hippocampus—in humans as in rats, the seat for learning and memory—continues to be strongly shaped by experience throughout life",
                "In humans, the longest window for shaping occurs with the prefrontal cortex, molded anatomically into early adulthood, so the people in a child's life have a decades-long opportunity to imprint that child's executive neural circuitry",
                "Spindle cells—the superrapid connectors of the social brain—migrate largely to the orbitofrontal cortex and anterior cingulate cortex at around four months and extend connections to thousands of other cells; just where and how richly they connect depends on influences like family stress (for the worse) or a warm and loving atmosphere (for the better)",
                "Richard Davidson: 'There is a lot more plasticity early in life than later... once a circuit is shaped by the environment in childhood, it then becomes quite stable'",
                "In the attuned peekaboo game, the baby at peak excitement abruptly turns away, sucks his thumb, and dully stares into space—a time-out he needs to calm down—while in the unattuned version the mother clicks her tongue and leans into his line of vision, setting him off fussing and grimacing until he turns farther away, sucking feverishly on his thumb",
            ],
        ),
    },
    {
        "num": 11,
        "title": "Chapter 11: A Secure Base",
        "pages": "173-188",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Still-Face Scanner",
            "Watch mother-infant pairs through the one-way glass and name the tell in each scene: the synchrony of a protoconversation, the broken loop of a still face, the intrusive mother, the blank, uninvolved one. Judge whether the baby is looping, making repair attempts, or giving up to suck his thumb, and stamp each case before the emotional intercom goes dark.",
            "A nursery observation room behind one-way glass: mother and infant face each other in an infrared synchrony loop that glows warm when in synch and ice-blue when out; a still-face alarm rings the instant the mother's expression goes blank, and the baby's repair attempts flash across a ticker.",
            [
                "In the still-face scenario, invented by psychologist Edward Tronick, the mother's face goes blank and unresponsive and her baby panics a bit, a look of anguish sweeping over his face, then starts to whimper",
                "Even after the still-face mother returns to her well-connected manner, babies continue to show distress for a while—how quickly they recover indicates how well they have mastered the rudiments of emotional self-management",
                "During the course of the first year or two of life, that basic skill builds as babies practice over and over going from upset to calm, from out of synch to looping",
                "A blank-faced mother invariably provokes the baby to make repair attempts, signaling her in every way they know, from flirting to crying; some eventually give up, looking away and sucking their thumb to try to soothe themselves",
                "In Tronick's view, the more successfully infants solicit 'repairs' of that broken loop, the better at it they become—and they come to see human interactions as reparable",
                "Babies who master repairs grow up seeing themselves as effective, able to have positive interactions and to repair them if they go off track, and they assume other people will be trustworthy and reliable partners",
                "Six-month-old babies have already started developing a typical style of interacting with other people and a habitual way of thinking about themselves and others",
                "Mother-infant synchrony operates from a child's first day of life; the more synchrony, the warmer and happier their overall interactions—but being out of synch makes newborns angry, frustrated, or bored",
                "Virtually from birth babies are not passive lumps but active communicators seeking urgent goals, managing their caretakers through an elaborate built-in system of eyes contacted and avoided, smiles, and cries—lacking that social intercom, babies can remain miserable or even die from neglect",
                "In a protoconversation the partners switch taking the lead: as the baby smiles or cries the mother reacts accordingly, so the emotions of the infant direct what the mother does as much as the mother directs the infant",
                "The wordless protoconversation of the first year of life builds the mental scaffolding for actual conversations at age two, and mastering the habit of talking primes that private inner conversation we call thinking",
                "Looping activates two pleasure-inducing neurotransmitters: oxytocin generates a sense of satisfying relaxation, while endorphins mimic the addictive pleasure of heroin in the brain (though not nearly so intensely)",
            ],
        ),
        "dialogue": (
            "Dialogue: The Reparative Experience",
            "Sit opposite Bowlby's suicidal patient and let him tell the story of the night he lay awake moaning with appendicitis, then switch seats and hear the husband whose father's narrowed eyes meant 'get out of the room.' Now play the therapist—and the assiduously attuned wife—offering each of them the I-You treatment: available where a father was distant, accepting where a mother was hypercritical.",
            "A dim consulting room where a young man tells of being left alone to cry until his parents' indifference taught him to hide his yearning; beside him a husband confesses 'Whenever I saw my father's eyes narrow, we kids knew it was time to get out of the room,' while his wife's hand stays on his, anchored in the reparative here-and-now.",
            [
                "Bowlby's suicidal patient was a twenty-three-year-old who had just graduated from a well-known university; his childhood was one ongoing misery of violent quarrels, a father often away for work, and a mother who would lock herself in her bedroom for hours, even days, at a time",
                "The patient's parents believed that a child's crying was just an attempt 'to be spoilt' by their attention, and he was left alone to cry for long periods; his signature memory was the night he developed appendicitis and lay awake until dawn, moaning and alone",
                "His first day of school was the most miserable of his life—being deposited there seemed like the final rejection by his mother, and he cried the whole day",
                "During therapy he was terrified that if he let his feelings into the open and cried, his therapist would see him as an attention-seeking nuisance and—he fantasized—lock himself away in another room until he left",
                "Bowlby, though trained in the classic patient-on-the-couch mode of psychoanalysis, did something revolutionary from the 1950s on: he observed mothers and infants directly rather than depending solely on the unverifiable memories of patients, and followed up with those children to see how early interactions shaped their interpersonal habits",
                "Bowlby identified a healthy attachment to parents as the crucial ingredient in a child's well-being, built by consistent empathy and sensitivity; well-attuned parents offer a child a 'secure base,' people they can count on when they are upset and need attention, love, and comfort",
                "Every child, Bowlby argued, needs a preponderance of I-You connections in childhood to thrive throughout life",
                "The husband whose father was prone to violent rages—especially when drunk—recalled, 'Whenever I saw my father's eyes narrow, we kids knew it was time to get out of the room'",
                "The husband's wife learned her own lesson: 'I realize my husband wasn't paid attention to as a child. So even when I'm hearing the same old story over and over, I remind myself, Stay here'; he is hypersensitive to the moments when she starts to tune out, knowing the instant she goes away inside",
                "Anyone who in childhood was treated by caretakers as an It rather than as a You is likely to bear such sensitivities and emotional wounds, but in adulthood close relationships can offer a healing scenario: the person, instead of being ignored or worse, is treated as a You",
                "Schore holds that the therapist serves as a projection screen for reliving early relationships: where a father was distant, the therapist can be available; where a mother was hypercritical, the therapist can be accepting—a reparative experience yearned for but never achieved",
                "One mark of effective psychotherapy is the opening up of a freer emotional flow: the best therapists create a secure emotional atmosphere, a safe container, and the very act of looping with the therapist helps the client learn to handle those same emotions on her own",
            ],
        ),
        "audit": (
            "Audit: The Attachment Style File",
            "File every parent-infant scene under the attachment outcome it produces: secure, anxious, avoidant, or the mixed tangle of the stiff-upper-lip pretense. Record for each dossier the maternal behavior behind it—intrusive, uninvolved, aloof, or anxious and self-preoccupied—and flag every file where a surrogate parent could still shift the pattern toward secure.",
            "A filing cabinet of childhoods: each dossier's attachment style is stamped SECURE, ANXIOUS, or AVOIDANT while a prediction dial reads off the parent's style with about 70 percent accuracy, and surrogate parents—older siblings, teachers, relatives—line up to offer a rescue route.",
            [
                "Mothers whose children will grow up to be secure are more attentive and responsive to their baby's cries, more affectionate and tender, and more comfortable in close contact like cuddling, repeatedly looping with their baby",
                "If a mother habitually intrudes, the infant copes by shutting down, actively trying to avoid interactions",
                "When the mother seems uninvolved, the baby reacts with a helpless passivity at being unable to connect—the very pattern brought into his adult life by Bowlby's suicidal patient",
                "Mothers who create emotional distance with their child, even keeping a physical gap and talking to or touching the child relatively little, produce children with a 'stiff-upper-lip' pretense of not caring, though their bodies reveal signs of heightened anxiety",
                "Mothers who are anxious and self-preoccupied tend to be out of tune with their child's needs, and some infants react by feeling fearful and clingy, becoming absorbed in their own anxieties and less able to attune well",
                "Happy, attuned interactions are as much a basic need for an infant as is feeding or burping: well-empathized children tend to become secure, anxious parenting produces anxious children, and aloof parents produce avoidant children who withdraw from emotion and from people",
                "Twin studies find that if a secure child gets adopted by an anxious parent, the child will most likely end up sharing that anxious pattern",
                "The attachment style of a parent predicts the child's style with about 70 percent accuracy",
                "If an anxious child can find a secure 'surrogate parent'—an older sibling, a teacher, or another relative who does much of the caregiving—her emotional pattern can shift toward the secure",
                "The parent-child loop offers the central passageway for parents to help children learn the ground rules for relationships: how to attend to another person, pace an interaction, engage in conversation, tune in to the other person's feelings, and manage your own feelings while engaged with someone else",
                "Injury to the brain areas with the most oxytocin receptors severely impairs maternal nurturing, and the wiring seems largely the same in infants as in their mothers—providing some of the neural cement for the loving bond they form",
                "Children who are well nurtured have the sense of a secure base in part because these brain chemicals evoke the inner sense that 'everything is all right'—possibly the biochemical basis for what Erik Erikson saw as an infant's basic sense of trust in the world",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: The Broken Loop",
            "Sort a stream of mother-infant interactions onto the right diagnostic screen: the joyful allegro of a well-synchronized duet, the flat largo of a depressed loop, the still-face rupture, and the warped empathy of the neglected or abused child. For each scene, name the tell—the missing Motherese, the anger seen in a neutral face—before the case files itself into the family's emotional weather.",
            "A split-screen observation suite: on one side an Italian mother sings a clapping ditty in a lilting allegro while baby Fabiana coos on the beat; on the other, a depressed mother sings the same tune in a slow, flat largo while her baby's stress-hormone gauge climbs; a third screen reads two Johnny vignettes to preschoolers and scores their answers half wrong.",
            [
                "An Italian mother sings a happy ditty to baby Fabiana—'Clap, clap, your little hands / Daddy will be here soon'—in a joyful tone, an upbeat allegro, and Fabiana delightedly joins in on the beat with coos",
                "When another mother, suffering from clinical depression, sings the same ditty in a monotonous, low-pitched largo, her baby responds with signs of distress, not delight",
                "Depressed mothers find it difficult to engage their babies in happy protoconversation and lack the energy for the lilting tones of Motherese; in interactions they tend to be poorly timed and 'off,' or intrusive, angry, or sad",
                "A depressed mother's failure to synchronize disables looping, while her negative emotions send the message that the baby has done something wrong and needs to change—upsetting a baby who can neither get his mother to help calm him down nor effectively do so himself",
                "As Michael Meaney points out, children born with a parent prone to bouts of depression inherit not only that parent's genes but also the depressed parent, who may well act in ways that foster that gene's expression",
                "Depressed mothers tend to look away from their babies more than others, become angry more often, are more intrusive when their babies need a recovery time-out, and are less warm",
                "Babies mirror the mother's pattern: if the mother tends toward anger, the baby becomes angry too; if she tends to be passively withdrawn, so becomes her baby",
                "Babies of depressed mothers have higher levels of stress hormones and lower levels of dopamine and serotonin—a chemical profile linked to depression",
                "Parents who are somewhat depressed but can manage to show good cheer in the face of difficulty seem to minimize the social transmission of depression, and having additional caretakers who are not depressed offers a reliably secure base",
                "Some children of depressed mothers become exquisite readers of their mother's shifting emotions, and as adults are artful at handling their interactions to keep them as pleasant (or minimally upsetting) as possible—a hard-earned social intelligence",
                "When two vignettes about Johnny—one about a lost ball and one about a friend who moved away—were read to preschoolers who were severely neglected by their parents, their answers were wrong half the time, a far poorer rate of emotion recognition than for well-nurtured preschoolers",
                "Abused preschoolers saw anger in faces that were neutral, ambiguous, or even sad, an overperception suggesting a hypersensitized amygdala that is selective for anger—their brains respond normally to faces showing joy or fear",
            ],
        ),
        "boss": (
            "Boss Battle: The Orbitofrontal Forge",
            "Take up the hammer in the forge of the orbitofrontal cortex and decide the fate of each set of neural scripts: which interactions shape the OFC's brake on anger, terror, and shame, and which leave it awry. Then fight the last battle of the broken loop—the family crisis, the war zone, the raging father—by keeping the emotional cocoon intact and looping until the It becomes a You.",
            "A forge lit by the glow of the orbitofrontal cortex: each attuned exchange hammers the OFC's emotional regulator into shape, while beneath it a war-zone family huddles in a stable, reassuring cocoon and a therapist's office offers the safe container where a child who learned to expect rejection can finish the job of childhood.",
            [
                "Allan Schore's theory holds that the neural site for emotional malfunction is primarily in the orbitofrontal cortex (OFC), that keystone in the brain's relationship pathways",
                "The very growth of the OFC depends on a child's experience: attunement and a secure base let it flourish, while unresponsive or abusive parenting makes its development go awry, limiting the ability to regulate the length, intensity, or frequency of distressing emotions like anger, terror, or shame",
                "Through neuroplasticity—the way repeated experiences sculpt the shape, size, and number of neurons and their synaptic connections—being chronically hurt and angered, or emotionally nourished, by someone we spend time with daily over the course of years can refashion the circuitry of our brain",
                "Schore argues that nurturing relationships later in life can to some extent rewrite the neural scripts that were encrypted in the brain during childhood",
                "In psychotherapy the active ingredients in this emotional repair work include rapport and trust, with patient and therapist looping well",
                "Psychologists use the still-face intentionally to explore the foundations of resilience, the ability to recover from distress",
                "A baby given a constant diet of dis-synchrony and solitary misery will learn to rely on whatever strategy for calming down he has stumbled upon—and in the adult version, countless people when feeling down turn to solitary consolations like overeating, drinking, or compulsive channel surfing",
                "Schoolyard bullies, who typically have a history of physical abuse, overinterpret anger and read antagonism into faces that are neutral—their attacks on other children are often due to their misperceiving hostile intent where there is none",
                "When a parent manages her own anger, neither pushing it away nor indulging in it, while staying looped, she offers the child a safe container for learning to handle his own irritations; the family surround creates a young child's emotional reality",
                "Children living in a war zone will skirt later trauma symptoms or heightened anxiety if their parents manage to create a stable, reassuring environment from day to day",
                "Stanford University psychiatrist David Spiegel on families after 9/11: 'The emotional cocoon works not when parents pretend nothing has happened but when they let children know we're dealing with how upset we are as a family, together'",
                "Abused children scan for anger more than other kids do, 'see' it when it is in fact not there, and keep looking at such signs longer—protective radar where real danger exists at home, but trouble when the child brings that heightened sensitivity into the world outside",
            ],
        ),
    },
    {
        "num": 12,
        "title": "Chapter 12: The Set Point for Happiness",
        "pages": "189-197",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Set Point Gauge",
            "Scan a stream of lives for the tell of their emotional set point: the lottery winner a year out, the paralyzed accident victim, the resilient late-fifties adult whose childhood warmth shows in his prefrontal ratio. Read the right-versus-left prefrontal gauge on every face and judge whether the pattern is dour or joyous before the scan seals its verdict.",
            "A mood laboratory where Davidson's imaging rig paints two prefrontal hemispheres—the right flaring red in distress, the left glowing gold in cheer—while a set-point needle traces the year-long return of lottery winners and accident victims to their baseline moods, and a mother's OFC lights up as she gazes at a picture of her newborn.",
            [
                "Richard Davidson's lab discovered that the more the orbitofrontal cortex activates as a mother gazes at a picture of her newborn, the stronger her feelings of love and warmth",
                "Davidson's research has mapped the neural centers that give each of us a unique emotional set point—the neural pivot point that fixes the range our emotions typically swing through during any given day",
                "The elation people feel after winning a huge amount of money in a lottery settles back in about a year to the range of mood they felt before winning",
                "People who become paralyzed in an accident return, a year or so after the initial agony, to nearly the same daily moods they had before the accident",
                "When people are in the grip of distressing emotion, the two brain areas most active are the amygdala and the right prefrontal cortex; when we're feeling cheery, those areas are quiet while part of the left prefrontal cortex lights up",
                "Even when we are in a neutral mood, the ratio of background activity in the right and left prefrontal areas is a remarkably accurate gauge of the range of emotions we typically experience",
                "People with more right-side prefrontal activity are particularly prone to down or upsetting moments, while those with more activity on the left generally have happier days",
                "The emotional thermostat does not seem to be fixed at birth: each of us has an innate temperament, but even given that baseline, research links the kind of care we get as children to our brain's capacity for joy in adulthood",
                "'A great deal of animal data shows that nurturing parents—a rodent mother who grooms and licks, for example—promote happiness and resilience under stress in their young,' says Davidson",
                "Animals who had more nurturing in their upbringing will view a strange place as an opportunity, exploring it more freely and being more outgoing—novelty can be appraised as a threat or as an opportunity",
                "In studies of adults in their late fifties, assessed every few years since their high school graduation, those with the most resilience and the best daily moods showed a revealing pattern of brain activity when Davidson's group measured their happiness set point",
                "'The amount of joy in a toddler's relationships appears critical to setting the brain pathways for happiness,' Davidson told Goleman",
            ],
        ),
        "dialogue": (
            "Dialogue: The I-Love-You Repair",
            "Play the uncle facing the ornery three-year-old and improvise the repair—from 'I hate you' to 'I still love you' to the melting hug—while the out-of-synch waveform above you threatens to spiral into disrepair. Then switch seats and be the child witnessing a marital disagreement: will you imitate the contemptuous withdrawal or the warm, playful resolution, and how fast will your own recovery be?",
            "A living room in miniature: a three-year-old and her visiting uncle face off over an I-hate-you/I-love-you volley while a waveform above them goes out of phase, then snaps into synchronized repair as he sweeps her up in his arms; a second screen shows two couples arguing, one pair contemptuous and withdrawing, the other warm and playful.",
            [
                "A three-year-old in an ornery mood tells her visiting uncle 'I hate you,' and he replies 'Well, I love you'—the volley escalates through 'I hate you!' yelled with dramatic gusto until he sweeps her up and she concedes softly, 'I love you,' melting into his hug",
                "Developmental psychologists view the I-hate-you/I-love-you disconnect as an 'interaction error,' and getting back on the same emotional wavelength as 'repair' of that error",
                "A successful repair, like the final rapport achieved between the three-year-old and her uncle, makes both partners feel good; continued disrepair has the opposite effect, and a child's ability to repair such a disconnection is one key to lifelong happiness",
                "The secret lies not in avoiding life's inevitable frustrations and upsets but in learning to recover from them: the faster the recovery, the greater the child's capacity for joyfulness",
                "During the first year of life, babies stay well coordinated with their caregiver only about 30 percent of the time or less, with a natural cycle of going from in synch to out of synch",
                "Being out of synch makes babies unhappy—they protest via signs of frustration, in effect asking for help getting back in synch, in their first attempts at interaction repair",
                "This learning goes on implicitly, no doubt via mirror neurons, as a child witnesses how an older sibling, a playmate, or a parent manages an emotional storm, and the OFC's regulatory circuits for calming the amygdala 'rehearse' whatever strategy the child witnesses",
                "By age four or five, children are able to shift from simply trying to control their upsetting emotions to having a greater understanding of what causes their distress and what to do to relieve it—a sign of high-road maturation",
                "Parental coaching in the first four years of life, some psychologists suspect, may be particularly potent in shaping a child's later abilities to manage her emotions well and to handle rocky encounters smoothly",
                "In one study, parents of preschoolers observed during a marital disagreement who were antagonistic and disjointed—neither party listening, both angry and contemptuous, often withdrawing as hostility grew—had children who imitated the pattern with their playmates, being demanding and angry, bullying and hostile",
                "Couples who displayed more warmth, empathy, and mutual understanding during their disagreements also approached parenting together with greater harmony, even playfulness, and their children in turn got along better with playmates and could work disagreements out more productively",
                "How couples work out their disagreements predicts their children's conduct, even years later, and with all going well the result is a child who is resilient in the face of stress and able to attune effectively—the 'positive affective core' of a happy child, which takes a socially intelligent family",
            ],
        ),
        "audit": (
            "Audit: The Four Ways to Say No",
            "Audit four replays of the same scene—a fourteen-month-old climbing toward a lamp on a table—and file each parental response under its discipline style: redirect, ignore, or the angry-guilty-disappointed swing. For every file, record the orbitofrontal outcome it forges: a strengthened emotional brake, a frustrated, skittish child, or the ambivalent adult who yearns for affection while fearing abandonment.",
            "A nursery classroom with a lamp perched precariously on a table and a fourteen-month-old climbing toward it: the same scene plays four times side by side, each branching into a different orbitofrontal outcome—brake, neglect, or the ambivalent swing of rage, guilt, and disappointment—while a growth spurt chart at age five to seven rises toward the schoolroom.",
            [
                "Daniel Siegel, the UCLA child psychiatrist who offers the scenarios, argues that each type of parental reaction to the table-climbing fourteen-month-old shapes centers in the social brain in unique ways",
                "The parent who gives a firm 'No!' then tells the boy climbing is for outdoors and takes him there optimally affects his orbitofrontal cortex, strengthening the OFC's emotional 'brake' that tones down the youngster's initial excitement and helps him manage his impulsivity",
                "What the redirected boy learns, in essence, comes down to: 'My parents don't always like what I do, but if I stop and find something better, everything will be okay'",
                "Setting a boundary and then finding a better outlet for the child's energy typifies the discipline style that results in secure attachment—securely attached children experience attunement from their parents even when they've been naughty",
                "The 'terrible twos,' when babies start to defy their parents by shouting 'No!' when told to do something, signals a major milestone in brain development: the brain is beginning to be able to inhibit impulse—to say no to urges",
                "Apes and very young children alike have great trouble with this aspect of social life for the same neural reason: the array of neurons in their OFC that can stop an impulse from being enacted is underdeveloped",
                "A neural growth spurt in the OFC starts at around age five and continues apace to around age seven, greatly boosting the child's self-control and making second-grade classrooms far less rambunctious than kindergarten; the anatomical process continues into the mid-twenties",
                "The parent who ignored the climbing boy typifies a relationship where attunement occurs rarely, and the absence of looping—and hence shared moments of pleasure or joy—increases the odds that a child will grow up with a diminished capacity for positive emotions",
                "Children of such avoidant parents grow up skittish; as adults their expression of emotions is inhibited, particularly the emotions that would help them bond with a partner, and they avoid not just expressing feelings but emotionally intimate relationships",
                "Siegel fittingly describes the parent who first becomes angry, then guilty, then disappointed as 'ambivalent,' sending signals of disapproval or rejection—facial expressions of disgust or contempt, averting gaze, body language signifying anger or disconnection—that leave the child repeatedly feeling hurt and humiliated",
                "Children often respond to such ambivalent parenting with uncontrollable emotional swings, their impulses unchecked or running amok like the classic 'bad boy,' and they come to regard themselves as basically flawed",
                "In adulthood, such children tend to bring to their close relationships the same ambivalent combination of yearning for affection with an intense fear that they will not get it—and an even deeper fear of being abandoned altogether",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: The Stress Sine Wave",
            "Classify each stress signature as it writes itself across a school year: the helpful first-week jitters of the socially adept preschooler, the stuck-in-high-gear arousal of the isolated child, the inoculation curve of the squirrel monkeys, or the too-overwhelming fear that rehearses failure. Route every case to mastery or to misery before the sine wave for resilience etches itself for life.",
            "A schoolyard laboratory across a school year: a stress-hormone sine wave draws itself across the calendar, rising with first-week jitters and smoothing for the socially adept while the isolated child's line stays stuck high; beside it, a cage of squirrel monkeys charts the inoculation curve of just-scary-enough exposure and a screen plays Chicken Run to a rapt two-year-old.",
            [
                "In the beginning weeks of the school year, preschoolers who are most outgoing, socially competent, and well liked show high activity in the brain circuit that triggers stress hormones—their physiological effort to meet the challenge of entering a new social group",
                "For these socially adept preschoolers, stress hormone levels decline as the year goes on as they find a comfortable niche in their small community, while preschoolers who remain unhappy and socially isolated maintain high stress hormone levels or even increase them",
                "The 'first week jitters' rise in stress hormone activity is a helpful metabolic response, mobilizing the body to handle a dicey situation, and the biological cycle of arousal and return to normal as a challenge becomes mastered etches the sine wave for resilience",
                "Children who are slow to develop distress mastery show a very different pattern—their biology seems inflexible, their arousal levels 'stuck' in too high a gear",
                "The wealthy New York couple's four-year-old has a castlelike dollhouse, jungle gym, and rooms packed with playthings but has never had a friend over to play, because her parents are afraid another child might do something that would upset her",
                "Such overprotection is in fact a form of deprivation: the goal for parenting should not be achieving a brittle 'positive' psychology of perpetual joy but teaching a child how to return on her own to a state of contentment, whatever may happen",
                "Parents who can 'reframe' an upsetting moment—the wisdom in the old saying 'No use crying over spilt milk'—teach their children a universal method for undoing distressing emotions, ingrained at the neural level in the OFC circuitry for managing distress",
                "Learning to build inner resources for a happier life demands that we endure the hard knocks of the playground—boot camp for the inevitable upsets of everyday relationships",
                "In the squirrel monkey study, monkeys taken at seventeen weeks from their cozy cage once a week for ten weeks to a cage with adult monkeys they did not know proved, after weaning, far braver and more curious than others their age who had never left their mothers' side, exploring new cages freely and treating themselves to the snacks there",
                "The independent squirrel monkeys showed no biological signs of fear arousal—the regular visits to a scary place acted as an inoculation against stress",
                "As Richard Davidson explains, 'We can learn to be resilient by being exposed to a threat or stress at a level that allows us to manage it': if we are exposed to too little stress, nothing will be learned; too much, and the wrong lesson might become embedded in the neural circuitry for fear",
                "One sign that a scary movie is too overwhelming for a child is how slowly he recovers physiologically—if his brain stays stuck in the fear-arousal mode for a distressingly prolonged period, what's being rehearsed is not resilience but the failure to recover",
            ],
        ),
        "boss": (
            "Boss Battle: The Positive Affective Core",
            "Build the happy child: defend the safe haven so a child dares to go out and play, then hold the line against the ancient suppressors—anxiety, anger, and sadness—that stamp out playfulness. Master the primal circuitry of joy, from the belly laugh to the fifty-kilohertz chirp, and channel the urge to romp into the grown-up pleasures before the prefrontal cortex demands that everyone get serious.",
            "A playroom built inside the ancient brain: brain-stem circuitry glows with the joy of play while tickle receptors trace the tickle zone from the back of the neck around the rib cage; a delighted rat pup's fifty-kilohertz chirp rises unheard as a tickled three-year-old dissolves into gales of belly laughter, and an ADHD classroom waits on Panksepp's morning recess proposal.",
            [
                "Mary Ainsworth, Bowlby's chief American disciple, proposed that children also need a 'safe haven'—an emotionally secure place, like their room or home, to return to after going out and exploring the wider world; a simple sign that a child feels he has one is going out to play",
                "Poet Emily Fox Gordon vividly remembers being 'wildly, uncontrollably' happy as a young girl: 'The elms stood guard, the local dogs greeted us, and even the telephone operators knew us by name'",
                "Through years of hard play children acquire a range of social expertise—how to negotiate power struggles, cooperate and form alliances, concede with grace—all in a relaxed sense of safety where even a mistake can trigger giggles",
                "The brain circuitry that primes play also arouses joy, and identical circuitry for playfulness can be found in all mammals, hiding in the most ancient neural zones down in the brain stem, a pocket near the spine that governs reflexes and our most primordial responses",
                "Jaak Panksepp of Bowling Green State University, author of Affective Neuroscience, sees playfulness as the brain's source of joy; the primal subcortical circuitry that prompts the young of all mammals to romp in rough-and-tumble play seems to have a vital role in a child's neural growth",
                "In research with rodents, Panksepp's group discovered that play 'fertilizes' the growth of circuitry in the amygdala and frontal cortex, and identified a specific compound generated during play that drives genetic transcription in these fast-developing areas",
                "All mammals have 'tickle skin' peppered with specialized receptors that transmit the brain messages for a playful mood, and tickling triggers the belly laugh, which has circuitry distinct from that for smiling",
                "Panksepp discovered that like human toddlers, baby rats are drawn to adults who will tickle them, uttering a chirp of delight at about 50 kilohertz, out of the range of the human ear—an evolutionary cousin of the rapturous laugh of a tickled three-year-old",
                "The reason we can't tickle ourselves is that the neurons for tickling are tuned to react to unpredictability—which is why wiggling a finger at a youngster along with a threatening 'coochi-coochi-coo' will set off wild laughter, the primal joke",
                "Panksepp notes that the psychostimulant medications given to children for ADHD all reduce the activity of the brain's play modules when given to animals, and makes the radical, untested proposal of an early-morning free-play, rough-and-tumble recess so children can more easily pay attention once their urge to play is sated",
                "Playfulness throws off a kind of charisma: adults, children, and even lab rats are drawn to spend more time with those who have had abundant practice playing",
                "The play circuitry defers to bad feelings—anxiety, anger, and sadness all suppress playfulness, in all mammals—and as the regulatory circuits of the prefrontal cortex develop in late childhood and the early teen years, children are more able to meet the social demands to 'get serious,' slowly channeling play's energies into more grown-up modes of pleasure",
            ],
        ),
    },
    {
        "num": 13,
        "title": "Chapter 13: Webs of Attachment",
        "pages": "198-210",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Flirt Radar",
            "Scan the Friday-night singles event and ring every move in the courtship sequence: the tossed hair and swaying hips, the eye contact held just long enough, the coy look away. Judge each gesture against the mammalian approach-withdrawal template and the dopamine reward circuit it triggers, and flag the moment the wide net of broadcasting gives way to the Talk.",
            "A crowded Upper East Side singles bar at Friday night: a woman parades past the bar tossing her hair and swaying her hips, meets a man's eyes for just a moment, and quickly looks away, while an overlay traces the approach-withdrawal sequence, the flirter's smile among Ekman's eighteen varieties, and a dopamine circuit lighting in the watching man's brain.",
            [
                "The woman at the Upper East Side singles event parades past the bar heading for the powder room, tossing her hair and swaying her hips, letting her eyes meet the man's for just a moment, then quickly looking away as she sees him start to return her gaze—her unstated message: Notice me",
                "That inviting look followed by coyness imitates an approach-withdrawal sequence found in most mammalian species where survival of newborns requires a father's help: the female needs to test a male's willingness to pursue and commit",
                "The flirtatious move is so universal that ethologists have observed it even in rats: a female will repeatedly run toward and away from a male, or dart past him wiggling her head, all the while emitting the same high-pitched squeal that rat pups make while playing",
                "The flirtatious smile is catalogued among Paul Ekman's eighteen varieties: the flirter smiles while facing elsewhere, then gazes directly at the target of ardor just long enough to be noticed, before quickly looking away",
                "A team of neuroscientists in London discovered that when a man receives the direct gaze of a woman he finds attractive, his brain activates a dopamine circuit that delivers a dollop of pleasure",
                "Simply looking at beautiful women, or making eye contact with someone not perceived as attractive, fails to stir that dopamine circuitry",
                "Whether or not men find a given woman appealing, flirting itself pays off: men most frequently approach those women who flirt a lot, rather than more attractive women who don't flirt",
                "Flirting goes on among people in cultures around the world—one researcher documented it from Samoa to Paris with a camera that takes pictures from its side",
                "The first strategic gambit of courtship involves casting a wide net by reckless broadcasting of one's readiness to engage; very young infants do the same, promiscuously signaling their interest in interacting with just about any friendly person who happens by",
                "The parallel in adult flirting includes not just the flirtatious smile but making eye contact and talking animatedly in a high-pitched voice with exaggerated gestures—much like an infant on the prowl for friendly interaction",
                "Many pathways for love travel the low road, and love's reasons have always been subcortical, though love's execution may require careful plotting: loving well requires a full social intelligence, the low road married to the high",
                "When all three of the love systems—attachment, caregiving, and sexuality—are operating, they feed romance at its richest: a relaxed, affectionate, and sensual connection where rapport blossoms",
            ],
        ),
        "dialogue": (
            "Dialogue: The Coffee Talk",
            "Sit across the coffee table from a prospective partner and conduct the Talk—the subtext-laden conversation that determines whether this person would be worth becoming attached to. Gauge warmth, responsiveness, and reciprocity like a suspicious parent checking out a teenager's date, then switch seats and answer as the one being sized up: do you pass the test of the secure base, or do you regress into the stormy tantrum of courtship?",
            "A coffee shop after last night's tryst: two people talk in a bubble of subtext while an overlay weighs considerateness, understanding, responsiveness, and competence on the scales of prospective parenthood, and a miniature pair of infants at three months look on, already selective about who they will engage.",
            [
                "At least in American culture, the Talk—an essential step in a budding courtship—has an almost mythic quality: a conversation with the subtext of determining whether the prospective partner actually would be worth becoming attached to",
                "The Talk gives the high road a central role in what has hitherto been largely a low-road process, something like a suspicious parent checking out a teenager's date",
                "A prolonged courtship lets partners take the full measure of each other on what counts most to both: that a romantic partner be considerate and understanding, responsive and competent—that is, worthy of a more intense attachment",
                "The stages of courtship are paced to give prospective partners a chance to guess whether the other person might be a good companion, a positive indicator that perhaps one day they would also be a good parent",
                "During early conversations partners gauge each other's warmth, responsiveness, and reciprocity and make a tentative choice; similarly, infants at around three months become more selective in whom they seek to engage, focusing on the people with whom they feel most secure",
                "Once a partner passes that test, synchrony marks the transition from attraction to feeling romantic longings, and the increased ease of getting in synch shows up in fond gazes, cuddling, and nuzzling",
                "At this stage lovers regress to outright babyishness, using baby talk or cute private names, soothing whispers, and gentle caressing",
                "This utter physical ease with each other marks the point where each has become a secure base for the other—still another echo of infancy",
                "Courtship can be as stormy as a toddler in a tantrum, and the general template morphs to contain all the ways risk and anxiety can bring couples together—from wartime romances and illicit affairs, to women who fall for 'dangerous' men",
                "Neuroscientist Jaak Panksepp theorizes that as a couple fall in love, they literally become addicted to each other, finding a neural corollary between the dynamics of opiate addiction and our dependence on the people for whom we feel our strongest attachments",
                "The OFC and ACC activate in addicts while they are craving, intoxicated, and bingeing, and deactivate during withdrawal—a system that accounts for the addict's overvaluing his favored drug, and perhaps also for the object of ardor during the pangs of falling in love",
                "Even animals prefer to spend time with those in whose presence they have secreted oxytocin and natural opioids, which induce a relaxed serenity—suggesting these brain chemicals cement our family ties and friendships as well as our love relationships",
            ],
        ),
        "audit": (
            "Audit: The Attachment Styles Ledger",
            "File every adult under his or her attachment style—secure, anxious, or avoidant—and justify each call with the evidence on the card: the ease of getting close, the fretful clinging, the stiff suppression of feelings. For each entry, record the distress strategy—reaching out to people or standing stridently alone—and flag the couples destined for flare-ups before the demand-withdraw pattern locks in.",
            "A filing cabinet of adult relationships: each dossier is stamped SECURE, ANXIOUS, or AVOIDANT while a ledger tallies the percentages—55, 20, 25—and a split screen plays the Brenda-and-Bob exchange over the beach photos, she crying and he turning the page of his newspaper.",
            [
                "In the exchange over the beach photos, Brenda comes in holding photographs, her eyes red from crying, and tells Bob she's found photos from a day they took their dead baby to the beach; Bob, not even looking up, mutters 'Yeah' and 'Hmmm,' refuses to see the pictures, and finally storms out growling, 'Of course I miss her! I just don't want to talk about it'",
                "The Brenda-Bob exchange illustrates the 'demand-withdraw' pattern long commented on by marital therapists—she sees him as cold and uncaring, he sees her as intrusive and demanding—and new findings suggest this classic discrepancy has a brain basis: neither way is 'best,' both tendencies reflect underlying neural patterns",
                "Bob embodies the avoidant type, who finds intense emotions unpleasant and so tries to minimize them; Brenda is the anxious type, whose feelings bubble up irrepressibly and who needs to talk over her preoccupations; the secure type is comfortable with emotions but not preoccupied by them",
                "Once formed in childhood, the way we attach ourselves stays remarkably constant, and these distinct attachment styles emerge to some degree in every close relationship—nowhere so strongly as in our romantic ties",
                "Phillip Shaver, the psychologist at the University of California, has led much of the research on attachment and relationships, carrying the mantle from Bowlby to Ainsworth, whose pioneering studies of how nine-month-olds reacted to a brief separation from their mothers first identified some infants as secure in their attachment",
                "Shaver's group finds that 55 percent of Americans fall into the 'secure' category, easily getting close to others and being comfortable depending on them, expecting a partner to be emotionally available and attuned",
                "Securely attached people see themselves as worthy of concern, care, and affection, and others as accessible, reliable, and having good intentions toward them—so their relationships tend to be intimate and trusting",
                "About 20 percent of adults are 'anxious' in their love relationships, prone to fret that their partner does not really love them or won't stay with them, and their apprehensive clinging and need for reassurance can inadvertently drive a partner away",
                "Anxious types are prone to all the signs of 'love addiction'—obsessive preoccupation, self-conscious anxiety, and emotional dependence—and are hypervigilant and jealous about imagined dalliances, often bringing the same overconcern to their friendships",
                "Around 25 percent of adults are 'avoidant,' uncomfortable being emotionally close, finding it hard to trust a partner or share feelings, and getting nervous when their partner seeks to get more emotionally intimate; they tend to suppress their own emotions, and especially to stifle their distressing feelings",
                "The underlying difficulty with the anxious and avoidant types comes down to rigidity—strategies that actually make sense in a specific situation but are adhered to even where they fail; when distressed, anxious people turn to other people, while avoidant people remain stridently independent, preferring to manage their upsets on their own",
                "A secure romantic partner seems able to buffer the perturbations of an anxious partner, and if one partner in a couple has the secure pattern they have relatively few conflicts and crises—but when both partners are anxious they are prone to flare-ups and tiffs and demand constant high maintenance: apprehension, resentment, and distress are contagious",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: The Three Love Systems",
            "Sort a stream of loving moments onto the three interlocking branches of the love web: attachment that clings, caregiving that provides, and sex that begins the job. For each case, name which system is ascendant—the couple's warm togetherness, the cuddle over the baby, the tryst—and rule on what happens to romance when one of the three goes missing.",
            "A kinetic mobile by Alexander Calder hangs overhead: three branches labeled Attachment, Caregiving, and Sex, each with its own chemical sparkle, and motion in any branch reverberating through the others; beneath it, scenes of romance, parenting, and lovemaking slide into their slots as the whole web trembles.",
            [
                "Neuroscience distinguishes between three independent but interrelated brain systems for love—attachment, caregiving, and sex—each fueled by a differing set of brain chemicals and hormones, and each running through a disparate neuronal circuit",
                "Attachment determines who we turn to for succor; these are the people we miss the most when they are absent, while caregiving gives us the urge to nurture the people for whom we feel most concern: when we are attached we cling, when we are caregiving we provide",
                "Sex alone merely begins the job of continuing the species: attachment provides the glue that keeps not just a couple but a family together, and caregiving adds the impulse to look after offspring so our children can grow up to have their own",
                "When attachment entwines with caring and sexual attraction, we can savor full-blown romance—but when any of these three goes missing, romantic love stumbles",
                "Many pathways for love travel the low road, and someone who fit the narrow definition of social intelligence as based on cognition alone would be clueless here: love's reasons have always been subcortical, though love's execution may require careful plotting",
                "The attachment system begins its operation in earliest infancy, guiding an infant to seek care and protection from others, most particularly from its mother or other caregivers—and there are fascinating parallels between how we form our first attachments and how we form our initial connection to a romantic partner",
                "The neural systems for attachment, sex, and caregiving can be thought of as parts of one of Alexander Calder's kinetic mobiles, where motion in any branch reverberates to the others—for example, attachment styles mold a person's sexuality",
                "Avoidant types have more sexual partners and 'one-night stands' than do anxious or secure people, and true to their preference for emotional distance, they are content with sex without caring or intimacy",
                "Avoidants who end up in an ongoing relationship tend to oscillate between distance and coercion, and so are understandably more likely to divorce or break up—and then, oddly, to try to return to that same partner",
                "The same circuits may be at work to one extent or another in larger realms, like spiritual longing or an affinity for open skies and empty beaches",
                "At a given moment any of the three systems can be ascendant—say, as a couple feels a warm togetherness, or when they cuddle their baby, or while they make love—and the first step in forming a union involves the attachment system in its scouting mode",
                "When the three love systems align, love grows robust, but when they are at odds love can flounder: attachment pitched in the direction of anxiety inhibits the operation of the others, and such gnawing apprehension can wither the sexual urge and snuff out affectionate caring",
            ],
        ),
        "boss": (
            "Boss Battle: The UC Davis Scanner",
            "Take the fMRI seat in Shaver's scanner lab and rule on each brain as it works through a distressing reverie about a relationship: can she shut down the ATP's sadness when the breakup fears flare, can he flip off the cingulate's suppression when asked to stop thinking about something sad? Map each woman to her attachment style—then fight the final battle against the jammed neural brake that leaves avoidants grieving nothing.",
            "A brain scanner suite at the University of California at Davis: on the screens, low-road zones light up in anxious women—anterior temporal pole, anterior cingulate, hippocampus—in a circuit that will not shut down, while in secure women the OFC's switch for calming distress from the ATP snaps cleanly on, and in avoidant women the cingulate's suppression brake stays jammed.",
            [
                "Shaver's research with neuroscientists at the University of California at Davis reveals that each of the three attachment styles reflects a specific variation in the wiring of the brain's attachment system, with differences surfacing most boldly in disturbing moments—an argument, fearful ruminations about a tiff, or obsessing about breaking up with a romantic partner",
                "The fMRI study of the three attachment styles used only women, and presumably the same conclusions apply to men—only future studies will tell",
                "In anxious women, the propensity to overworry, as when one fears losing a partner, lit up low-road zones including the anterior temporal pole (ATP), which activates during sadness; the anterior cingulate, where emotions flare; and the hippocampus, a key site for memory",
                "The anxious women could not shut down this circuit for relationship disquiet even when they were specifically trying to—their obsessive worries overpowered their brain's ability to turn them off",
                "This neural activity was specific to anxiety about relationships rather than fears in general: the anxious women's anxiety-calming circuits worked perfectly well for shutting off other kinds of worries",
                "The secure women had no trouble shutting off fears about breaking up—their sadness-generating ATP quieted down as soon as they turned their attention to other thoughts",
                "The key difference: the secure women readily activated the OFC's neural switch for calming distress from the ATP",
                "The anxious women could bring to mind some particular worry-provoking moment from their romantic relationship far more easily than could the other women—a readiness for preoccupation that, Shaver suggests, could well interfere with their ability to figure out what would be most constructive to do",
                "In avoidant women, the crucial action hinged on an area in the cingulate that activates during suppression of upsetting thoughts, and this neural brake on emotion seems jammed: just as the anxious women were unable to stop their worry, the avoidant women were unable to stop their suppression of worry, even when they were asked to",
                "The other women had no trouble flipping on and off the cingulate when they were asked to think about something sad and then to stop thinking about it",
                "The nonstop-suppression pattern explains why those with the avoidant style tend to be emotionally distant and uninvolved with life: when a relationship breaks up or someone dies, they do little grieving, and they feel emotionally unengaged during social interactions",
                "Shaver found it hardest to recruit avoidant women for this study, because one of the requirements was involvement in a serious, long-term romantic relationship—and so few were; these styles are largely shaped in childhood and so do not seem genetic givens, which means they should be modifiable by the right experience, whether in psychotherapy or in a reparative relationship",
            ],
        ),
    },
    {
        "num": 14,
        "title": "Chapter 14: Desire: His and Hers",
        "pages": "211-222",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Attraction Scan",
            "Scan the couples in love and name the gender signature in each gaze: the man whose visual-processing and arousal centers light up at his lover's photo, the woman whose memory and attention circuits engage. Then run the low-road sweep for Nature's tricks—the hourglass ratio, the scent of a man's perspiration, the husband's pillowcase—and stamp each attraction cue with its sensory channel before the scan closes.",
            "A brain-imaging theater where couples gaze at photos of their beloveds: men's scans flare in visual processing and sexual arousal, women's in the cognitive centers of memory and attention; beside them, a row of line drawings of women with varying waist-to-hip ratios waits to be rated, and a vial of four-week underarm scent sits under a lab lamp labeled floor-wax study.",
            [
                "When couples in love gazed at photos of their partners, for men in love—but not for women—the centers for visual processing and sexual arousal lit up, showing how his lover's looks trigger a man's passion",
                "Anthropologist Helen Fisher notes that men worldwide seek out visual pornography, while women tend to draw feelings of self-worth from their appearance and put so much energy into their looks, all the better to 'advertise their assets visually'",
                "For women in love, looking at their beloved activates very different centers in the brain's social circuitry: cognitive centers for memory and attention, suggesting women more thoughtfully weigh their feelings and assess a man as a prospective mate and provider",
                "Women entering a romance notoriously tend to be more pragmatic than men, and so of necessity they fall in love more slowly; 'Casual sex' for women, Fisher comments, 'is often not as casual as it is for men'",
                "Men plunge down the low road while they are falling in love; women cruise down the low too, but they also circle back along the high",
                "The cynical view has it that 'men look for sex objects, and women for success objects,' but although women tend to find allure in signs of a man's power and wealth, and men in a woman's physical attractiveness, these are not the prime draws for either sex—just the ones they most differ on: for men and women alike, kindness tops the list",
                "The male brain contains seemingly hardwired signal detectors for key aspects of the female body, particularly the 'hourglass' ratio of breast-to-waist-to-hips, a signal of youthful beauty that in itself can trigger sexual arousal in men",
                "When men around the world rated the attractiveness of line drawings of women with varying ratios, most chose women with a waist circumference about 70 percent of her hips",
                "The route taken in some of the very first stirrings of sexual attraction is low road—sensory rather than a formulated thought: for women that initial subliminal intrigue can stem from an olfactory impression, for men a visual one",
                "A woman writer, independent and enterprising, always traveled with a pillowcase her husband had slept on, slipping it onto the hotel pillow wherever she went—his scent with her made it easier to fall asleep in a strange bed, a clue about one of Nature's tricks in its drive to continue the species",
                "Scientists found that the scent of a man's perspiration can have remarkable effects on women's emotions, brightening their moods, relaxing them, and raising their levels of the luteinizing reproductive hormones that bring on ovulation",
                "In the clinical study of that scent, samples from the underarms of men who had not used deodorant for four weeks were blended into a concoction dabbed on the upper lip of young women who volunteered for what they thought was a study of the scent of products like floor wax, and the women felt more relaxed and happy",
            ],
        ),
        "dialogue": (
            "Dialogue: The Ounce of Space",
            "Play the young lawyer coming home to the hovering writer fiancé, and deliver the line—'Just give me an ounce of space to love you from'—that sends him toward the couch. Then switch seats and be the fiancé whose single-pointed fixation is akin to a nursing infant's ruthless desire, and find with Mark Epstein the alternative: slow down, attune emotionally, and create the psychological space where her desire can stay alive.",
            "A bedroom at nightfall: the writer fiancé drops his work to hover, then pulls the lawyer to him before she can get under the sheets, while above them an overlay shows the three love systems misaligning—attachment tipped into anxiety, withering the sexual urge—and a voice asks Freud's question, 'What does woman want?'",
            [
                "The beautiful and independent young lawyer's fiancé, a writer who worked at home, would drop whatever he was doing and hover around her whenever she came home; one evening as she was coming to bed, he eagerly pulled her to him even before she had a chance to get under the sheets",
                "'Just give me an ounce of space to love you from,' she said to him—a comment that hurt his feelings so much that he threatened to go sleep on the couch",
                "Her comment bespeaks the underside of looping too tightly: it can be suffocating, and the goal of attunement is not simply continual meshing with an utter entrainment of every thought and feeling, but also giving each other space to be alone as needed",
                "As one family therapist put it, 'The more a couple can be apart, the more they can be together'",
                "The mismatch between attachment and sex occurs, for example, when one partner feels insecure or, even worse, nurses outright jealousy or harbors fears of abandonment—and from the neural perspective, the system for attachment, when pitched in the direction of anxiety, inhibits the operation of the others",
                "Such gnawing apprehension can easily wither the sexual urge and snuff out affectionate caring—at least for a time",
                "The fiancé's single-pointed fixation on the lawyer as a sexual object is akin to the ruthless desire of a nursing infant, who knows nothing of his mother's own feelings and needs",
                "The childhood roots of intimacy resurface in the use of childlike, high-pitched voices or baby names between lovers—cues that, as ethologists argue, trigger in lovers' brains parental responses of caregiving and tenderness",
                "The difference between infant desire and adult desire lies in the adult capacity for empathy, so that passion melds with compassion or at least caring",
                "Mark Epstein, the lawyer's psychiatrist, suggested an alternative for the fiancé: slow down enough to attune emotionally and thereby create the psychological space that would let her stay in touch with her own desire",
                "That mutuality of desire—and maintenance of the loop between them—offered a way to bring back the passion she was losing",
                "This harkens back to Freud's famous question, 'What does woman want?'—as Epstein answers, 'She wants a partner who cares what she wants'",
            ],
        ),
        "audit": (
            "Audit: The Fantasy File",
            "Audit a shelf of sexual fantasies—Anne Rice's auction blocks in ancient Greece, the survey's most frequent themes, the diary tallies of college students—and file each under the rules of the consensual. For every entry, record whether it is a font of healthy stimulation, a convergent game played with a willing partner, or a script being imposed on an It, and strike the ledger when the fantasy crosses the line from thought to action.",
            "A filing room of erotic daydreams: cards slide into bins labeled Common Fantasy, Healthy Stimulation, Consensual Play, and Imposed Script, while a Kinsey-era projector shows a 1950s poll revealing that 89 percent of men and 64 percent of women fantasized during masturbation, and a wag in the corner counts four people in every couple's bed.",
            [
                "Anne Rice, author of a best-selling series of vampire novels and of erotica under a nom de plume, remembers having vivid sadomasochistic fantasies as far back as childhood, one of her earliest centering on elaborate scenarios of young men in ancient Greece being auctioned as sexual slaves",
                "The flamboyant sexual scenes Rice has elaborated in detail are not 'deviant' in a normative sense; rather, they are among the fantasy themes commonly reported by men and women alike in study after study",
                "One survey found that the most frequent sex fantasies include reliving an exciting sexual encounter, imagining having sex with one's partner or with someone else, having oral sex, making love in a romantic location, being irresistible—and being forced into sexual submission",
                "A wide variety of sex fantasies can reflect a healthy sexuality, offering a font of stimulation that enhances arousal and pleasure, and when both parties consent, this goes even for more bizarre fantasies like Rice's",
                "We've come a long way since Freud's proclamation a century ago that 'a happy person never fantasizes, only an unsatisfied one,' and as Rice pointedly mentions, she has never acted on her fantasies, despite being presented with opportunities",
                "Alfred Kinsey's original studies (which in retrospect represented a skewed sample) showed that 89 percent of men and 64 percent of women admitted to having sex fantasies during masturbation—a shocking finding in the sedate 1950s, but rather ho-hum today",
                "Sex researchers routinely assume that any statistics based on people's own reports of their sexual behavior underrepresent actual numbers",
                "When college men and women recorded in a diary every sexual fantasy or sexy thought over the course of a day, men reported about seven daily and women between four and five—but in recall questionnaires the men estimated just one per day and the women one per week",
                "Fantasizing during intercourse seems to level the playing field: up to 94 percent of women and 92 percent of men say that they have done so, though some reports range as low as 47 percent for men and 34 percent for women",
                "One study found that having sex with one's current lover is a popular daydream while one is not engaged in lovemaking, but imagining sex with someone else is a more popular fantasy during intercourse—leading one wag to observe that when romantic partners make love, there are in effect four people involved: the two actual ones, and the two that exist in their minds",
                "Consenting to enter, share, and act out a sex fantasy in vivo is an act of convergence: 'playing' the script with a willing partner, rather than imposing the fantasy and so making the other an It, makes all the difference, and even a seeming I-It scenario can create a closer sense of intimacy if mutually consensual",
                "'A good sexual relationship is like a good sexual fantasy'—exciting but safe: when partners have complementary emotional needs, the resulting chemistry, like fantasies that mesh, can breed an excitement that counters the usual downward drift in sexual interest among couples who have been together for many years",
            ],
        ),
        "matrix": (
            "Discrimination Matrix: The Chemical Recipe",
            "Sort the molecules of desire onto the correct shelves of his-and-hers biology: testosterone that soars with arousal, dopamine that rockets in both sexes, oxytocin that permeates a woman's brain and floods a man's afterglow, and AVP that builds toward ejaculation and imprints a partner's image in memory. For each entry, name who carries more of it and when it peaks, then file the culture that tried to put high-road brakes on the whole recipe.",
            "A chemistry lab of lust: color-coded molecular racks run down the wall—testosterone, dopamine, oxytocin, AVP—with male and female concentration gauges above each one, while a hippocampus readout imprints a lover's image and a historical timeline shows European upper classes marrying for property with adultery always waiting in the wings.",
            [
                "Men generally have higher levels of the chemicals that drive lust and lower levels of those that fuel attachment than do women—biological mismatches that create many of the classic tensions between men and women in the arena of passion",
                "For men, both sexuality and aggressiveness are lifted by the sex hormone testosterone acting in connected areas of the brain, and men's testosterone levels soar when they become sexually aroused; it fuels a sexual itch in women as well, albeit not so strongly as in men",
                "Dopamine—the chemical that injects intense pleasure in activities as diverse as gambling and drug addictions—rockets during sexual encounters for men and women alike, rising not just during sexual arousal but with the frequency of intercourse and the intensity of a person's sex drive",
                "Oxytocin, a chemical source of caregiving, permeates women's brains more than men's, and so it has more impact on women's sexual bonding",
                "Vasopressin, a hormone closely related to oxytocin, can also play a role in bonding, and receptors for vasopressin are abundant in spindle cells—the superfast connectors of the social brain involved when we make very rapid, intuitive judgments about someone we are meeting for the first time",
                "In the run-up to lovemaking, oxytocin levels soar in a man's brain, as does the hormonal hunger driven by arginine and vasopressin (known together as AVP); the male brain has more AVP receptors than the female, most of them concentrated in the sexual circuitry",
                "AVP becomes abundant at puberty, seems to fuel a man's sexual hankering, builds up as ejaculation nears, and rapidly declines at the moment of orgasm",
                "In both men and women, oxytocin fuels many of the loving and delectable feelings of sexual contact: ample doses release during orgasm, after which a flood of the chemical seems to stimulate the afterglow of warm affection—and put men and women on the same tenderly loving hormonal wavelength for the time being",
                "Oxytocin secretions remain strong after climax, particularly during 'afterplay,' the cuddling that follows intercourse, and the chemical wells up in particular strength in men during the 'refractory' period after orgasm, when they typically cannot get an erection",
                "At least in rodents (and possibly in humans), abundant sexual gratification in males spikes a threefold rise in oxytocin levels—a brain change that apparently brings male brain chemistry closer to that of females for the time being",
                "The hippocampus, the key structure in memory storage, holds neurons rich in receptors for AVP and oxytocin alike: AVP, particularly in a man, seems to imprint in memory with special strength the enticing image of his partner in passion, and the oxytocin produced by orgasm also boosts memory of a lover's fond figure",
                "Circuits within the high road, whether through elevated sentiments or puritanical mores, resolutely strive to contain the red-hot subterranean currents of lust: for centuries marriages in European upper classes were simply a matter of landed families ensuring their property remained in a particular lineage, and only around the Industrial Revolution and the rise of the middle class did romantic love become a popular enough ideal that simply falling in love was a respectable reason to marry",
            ],
        ),
        "boss": (
            "Boss Battle: The High Road Barrier",
            "Stand at the barrier between thought and action and rule on each case that breaches it: the narcissist who feels entitled to sex despite a clear no, the date rapist who ignores the protests, the high-testosterone husband at war with his own impulses. Hold the high road against the low—empathy as your shield—and decide which explosive combination of fantasies, hostility, and loneliness is the danger signal that almost ensures trouble.",
            "A courtroom built from brain anatomy: the low road surges beneath the floorboards while the prefrontal systems sit in the judge's seat, and a parade of case files streams past—the Christmas narcissist, the date rapists, the 4,462 high-testosterone men, the serial murderer's fantasies—each one asking whether the barrier between thought and action holds.",
            [
                "The case report of a twenty-five-year-old pathological narcissist: he easily becomes infatuated with women and is obsessed by powerful fantasies about each one in turn, but after a series of sexual trysts he always feels disappointed in her, suddenly finding her too dumb, or clinging, or physically repugnant—and when his girlfriend of a few weeks refused to stay in town with him over Christmas instead of visiting her family, he attacked her as self-centered and, enraged, decided never to see her again",
                "The narcissist's sense of entitlement endows him with the feeling that ordinary rules and boundaries do not apply to him: he feels entitled to sex if a woman encourages and arouses him—even if she clearly says she wants to stop—and he will go ahead anyway, even if he has to use force",
                "Narcissistic men endorse attitudes that favor sexual coercion, such as the idea that victims of rape are 'asking for it,' that when a woman says no to sex she really means yes, and that a girl who engages in necking or petting and lets things get out of hand has only her own fault to blame if her partner forces sex on her",
                "In the United States, around 20 percent of women claim to have been forced into unwanted sexual activity despite their resistance—most often by a spouse or partner or someone with whom they were in love at the time",
                "Ten times as many women are forced into sex by someone they love as by a stranger",
                "A study of self-confessed date rapists found that every instance of such coercion followed mutually consensual sex play; the rapist simply ignored the woman's protests about going further",
                "Unlike the majority of men, narcissists actually enjoy and find sexually arousing films in which a couple are petting, the woman wants to stop, and the man then forces sex on her despite her evident pain and disgust—tuning out of the woman's suffering and focusing only on the self-gratification of the aggressor, though they did not enjoy a sequence showing the rape alone without the foreplay and refusal",
                "The more empathic a man, the less likely he is to act as a sexual predator or even imagine doing so",
                "A study of testosterone levels among 4,462 American men found an alarming pattern among those with the very highest readings: they were more aggressive overall, more likely to have been arrested and been in fights, and were bad risks as husbands—prone to hitting or throwing things at their wives, to having extramarital sex, and, understandably, to having divorced",
                "Many high-testosterone men are happily married—what makes the difference, the authors propose, is the extent to which the men have learned to control their wilder testosterone-driven impulses, for the prefrontal systems hold the keys to managing impulse of all kinds, sexual and aggressive alike",
                "An FBI profiler who specialized in the psychological analysis of serial murderers told Goleman that such murderers are almost invariably acting out perversely cruel sex fantasies, in which even the pleas of victims become fodder for arousal; a significant number of convicted rapists later report that during the rape they felt nothing for their victim, and almost half convinced themselves she 'enjoyed it'",
                "Men imprisoned for rape could be effective at understanding other people in most situations, with one notable exception: they were inept at perceiving negative expressions in women, though not positive ones—and for repeated sex crimes the danger signal is a man who lacks empathy for his victims, believes the victims 'enjoy it,' feels hostility toward his victims, and is emotionally lonely, an explosive combination that almost ensures trouble",
            ],
        ),
    },
]
