# -*- coding: utf-8 -*-
"""Phase 2 chapter data for What Every BODY Is Saying (Navarro & Karlins), chapters 7-9.
Each chapter: num, title, pages, domain, and 5 slots (scrub/dialogue/audit/matrix/boss),
each slot a 4-tuple (topic, player_mission, visual_frame_description, key_concepts[8-12]).
"""

D = "Body Language | Nonverbal Communication"

CHAPTERS = [
    {
        "num": 7,
        "title": "The Mind's Canvas: Nonverbals of the Face",
        "pages": "214-268",
        "domain": D,
        "scrub": (
            "Cue Scrubber: The Face's Tension and Comfort Tells",
            "Screen 15 freeze-frames of faces and flag each tell before the timer clears: jaw tightening, nasal wing dilation, squinting, quivering mouth, lip occlusion, furrowed forehead, head tilt, widened eye area, full versus compressed lips, and the eye block. Sort each flag as tension or comfort, then judge whether the cue could be faked or is a limbic leak that context must confirm.",
            "A portrait gallery where each face is dissected into glowing zone overlays - jaw, nose, eyes, mouth, forehead - that light up as their tension cues fire. A comfort/tension gauge pivots under every face while a counter tracks how many microgestures you caught before they vanished.",
            [
                "Humans are capable of more than ten thousand different facial expressions (Ekman, 2003)",
                "Happiness, sadness, anger, fear, surprise, disgust, joy, rage, shame, anguish, and interest are universally recognized facial expressions",
                "Negative emotions show as a tension constellation: tightening of jaw muscles, flaring of nose wings, squinting of the eyes, quivering of the mouth, and lip occlusion in which lips seemingly disappear",
                "We are taught from an early age to fake smiles and mask our facial displays, so the best evidence of true sentiment comes from clusters of behavior",
                "Jaw tightening is an indication of tension: an executive's tight jaw during a proposal (Box 45) hid his real upset over his children's jobs",
                "Positive emotions loosen the furrowed lines of the forehead, relax the muscles around the mouth, restore full lips, and widen the eye area",
                "Head tilt to the side exposes the neck - a high-comfort display nearly impossible to mimic when tense, as the elevator experiment (Box 47) proves",
                "Happy feet corroborate a suppressed smile: the Baltimore passenger bounced his feet like a child while hiding his first-class upgrade joy (Box 46)",
                "Facial cues can be fleeting microgestures, easily missed because we are taught not to stare and concentrate on what is said rather than how it is said",
                "The face and its mantle, the neck, function as one canvas - our public face - and should be read as a unit",
                "Actors are trained to make expressions easy to read, while real-world tells are subtle, intentionally obfuscated, or overlooked (Figure 59)",
                "Assess facial behaviors in context and compare them to other nonverbal behaviors before trusting what the brain is processing",
            ],
        ),
        "dialogue": (
            "Dialogue: Squint, Blink, and Brow in Conversation",
            "Play both sides of a negotiation scene: as the observer, watch for the squint at the contract line, the eye block after your offer, the eyelid flutter at a sensitive topic, and the brow raise that stops mid-story - then choose whether to press on, restate, or change tack; as the speaker, leak the tells and see how quickly they are caught. Replay until every tell is caught before the scene ends.",
            "A split-screen office: on the left the negotiator's script with flagged trigger lines, on the right the counterpart's face rendered as a live map where squints flash red, flutters strobe, and brow raises dim when commitment dies. A tactic bar offers PRESS, RESTATE, and PIVOT choices as the tells fire.",
            [
                "Squinting is a form of eye blocking when we see something objectionable - my daughter's seven-year-old dislike of a classmate leaked through a brief squint at a low wave",
                "Customers who suddenly squint while reading a contract are struggling with the wording, discomfort and doubt registering immediately in their eyes",
                "Arched eyebrows are a gravity-defying sign of high confidence; lowered eyebrows signal low confidence, weakness, and insecurity (Box 49)",
                "Prisoners report looking for lowered-eyebrow, troubled behavior in new inmates to find who is weak and insecure (Box 49)",
                "Pupils dilate when we like what we see and constrict when we do not; the 1989 FBI spy case (Box 48) used 32 name cards and caught two co-conspirators by pupil constriction and a slight squint",
                "Eye blocking is a limbic survival mechanism to protect the brain from undesirable images; even children born blind cover their eyes on hearing bad news (Knapp & Hall)",
                "Eyelid flutter indicates an inner struggle - an onset of flutter mid-conversation marks a topic that has become controversial and a change of subject is in order (Box 51)",
                "Blink rate increases under stress: Nixon's blink rate rose during his 'I am not a crook' speech, and Clinton's blink rate increased fivefold during his deposition - yet stress alone should never label anyone a liar",
                "Looking askance says 'I am listening to you but I am not buying what you're saying - at least not yet'",
                "Gazing away during conversation is a comfort display that enhances clarity of thought, not rudeness or deception (Vrij)",
                "Dominants have more freedom in eye-gaze behavior; subordinates are restricted in where and when they can look - the king looks where he wants, all subjects face the king",
            ],
        ),
        "audit": (
            "Audit: The Smile and Mouth Tell Log",
            "Log five conversations this week and classify every mouth display: full lips, compressed lips, disappearing lips, upside-down U corners, lip pursing, sneers, lip licking, and tongue jutting. Score each as comfort or discomfort, note which question or statement triggered it, and practice the classroom experiment of forcing the corners of your mouth down to learn why the upside-down U cannot be faked.",
            "A timeline journal where each conversation draws a mouth-state strip: full lips as a green band, compression as red dips, and the upside-down U as a deep red spike. Each event is tagged with the exact spoken trigger, and a practice window lets you attempt the forced frown while a difficulty meter laughs at you.",
            [
                "A real smile comes from the zygomaticus major drawing the mouth corners up plus the orbicularis oculi crinkling the eyes into crow's feet",
                "A fake or polite smile uses the risorius to pull the lip corners sideways toward the ears, with little emotion in the eyes",
                "Babies several weeks old reserve the full zygomatic smile for their mothers and use the risorius smile for everyone else",
                "Disappearing lips are a universal stress response - nothing is more common than lip occlusion when testifying before Congress",
                "Lip compression is a clear sign a person is troubled by a specific negative stimulus; ask 'Are you hiding something from me?' and watch whether the lips compress exactly as the question lands (Box 53)",
                "The upside-down U mouth is a limbic response that is hard to mimic unless truly distressed or grieving - most people can only compress into a straight line",
                "Lip pursing means disagreement or consideration of an alternative: seen during closing arguments, sidebar conferences, contract reviews, and when a suspect is confronted with wrong information",
                "The sneer is a universal act of contempt, produced by the buccinator muscles; researcher John Gottman at the University of Washington found sneering couples a potent predictor of breakup (Box 54)",
                "Tongue jutting between the teeth without touching the lips appears when people feel they got away with something or were caught - seen at flea markets, poker tables in Las Vegas, and FBI interviews",
                "Lip licking is a pacifying behavior that soothes and calms, as seen in class just before a test",
                "Nail-biting is an indication of stress, insecurity, or discomfort - we bite not primarily for trimming but because it pacifies us",
                "The smile barometer: watch a business partner greet a liked and a disliked guest (Box 52) and you will learn to tell the real from the fake smile in no time",
            ],
        ),
        "matrix": (
            "Matrix: Facial Zone x Emotion x Context Grid",
            "Fill the cross-reference grid mapping facial zones (forehead, nose, eyes, mouth, chin) against emotions (stress, disgust, contempt, arousal, disapproval) and score each cell by the context that changes its meaning: the furrowed forehead of the cashier squaring her register versus the arrest mug shot, the nose flare of lovers versus the fighter. Lock every cell before the mug-shot timer expires.",
            "A wall-sized matrix on three axes; populating a cell summons a labeled case snapshot - the cashier's frown, the arrested man led past reporters, the French politician's haughty nose raise on television. Cells that hold across contexts pulse gold, revealing which signs are reliable.",
            [
                "A furrowed forehead appears when a person is anxious, sad, concentrating, concerned, bewildered, or angry - the cashier squaring her register and the arrest mug shot share the same frown",
                "A furrowed brow is so ancient that even dogs recognize it and can exhibit it themselves when anxious, sad, or concentrating",
                "Furrows deepen into permanent wrinkles with age: a wrinkled brow likely reflects a challenging life of frequent frowning",
                "Nasal wing dilation signals arousal and is an intention cue - oxygenation before physical action, from climbing steep stairs to moving a bookcase",
                "Lovers hover with subtly flaring nostrils as they absorb each other's pheromones (Givens)",
                "A person looking down, feet in the ready or pugilistic position, with nose flaring is preparing to argue, run, or fight",
                "Blushing is a true limbic response: my classroom space-violation demo makes students blush, as do teenagers when a secret crush draws near",
                "Blanching (turning pale) occurs in the sustained limbic reaction of shock - one man was so surprised at his arrest that he blanched and suffered a fatal heart attack",
                "Disgust registers primarily on the face because this anatomy evolved over millions of years to reject spoiled food - 'I don't like this, get it away from me'",
                "The microgesture of disgust - nose and one corner of the mouth lifting upward - revealed the gym saleswoman's displeasure at my Olympic-pool counter (Box 55), and a fiancée's same microgesture at the word 'marriage' predicted the wedding was off (Box 56)",
                "Rolling of the eyes is a sign of disrespect that must not be tolerated, especially from subordinates, staff, or children",
                "The rule of mixed signals: when verbal and facial messages conflict, side with the negative emotion - the first emotion observed is the most accurate",
            ],
        ),
        "boss": (
            "Boss Battle: The Face's Final Verdict",
            "You are the behavioral analyst at a witness table: 12 close-up video clips of declarative statements play one after another, and you must stamp each face TRUTH, STRESS, or DECEPTION CUE before the frame freezes. Name the exact zone - eye block, squint, lip compression, upside-down U, sneer, or brow loss - that drove your call, and hit 10 of 12 verdicts to clear the chapter.",
            "A dark evidence room where each clip slams into a decision booth; a freeze-frame fuse burns down while four zone badges - EYES, MOUTH, BROW, CHIN - light up as their tells fire. Your verdict stamp slams onto the glass with the zone name glowing beneath it.",
            [
                "Squinting, furrowing of the forehead, and facial contortions are indicative of distress or discomfort (Figure 59)",
                "A brief touch of the eyes during conversation may clue a person's negative perception of what is being discussed (Figure 65)",
                "A delay in opening the eyelids upon hearing information, or a lengthy closure, is indicative of negative emotions or displeasure (Figure 66)",
                "Lids that compress tightly signal the person trying to block out totally some negative news or event (Figure 67)",
                "If an eye block occurs right after you make a specific offer, something is amiss and the individual is troubled - rethink how you proceed",
                "Head tilt says powerfully 'I am comfortable, I am receptive, I am friendly' and is very difficult to do around people we don't like (Figure 60)",
                "The eyebrow raise or eye flash should occur when someone excitedly emphasizes a story; a sudden absence of brow raises alerts you that something has changed",
                "When you see eye shrinkage - squinting, dropping eyebrows, constricting pupils - you may want to rethink and change your behavioral tactics",
                "Pupil dilation and constriction can be caused by lighting, medical conditions, and certain drugs - consider these factors or you could be misled",
                "A low-hand wave done out of social convention paired with an honest, betraying eye squint exposed seven years of dislike",
                "If you are confused by a facial expression, reenact it and sense how it makes you feel - the trick can decipher what you just observed",
                "The face can reveal a great deal but it can also mislead: look for clusters of behaviors, evaluate in context, and note whether the face agrees with or contrasts against the rest of the body",
            ],
        ),
    },
    {
        "num": 8,
        "title": "Detecting Deception: Proceed with Caution!",
        "pages": "269-299",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Discomfort Signals in the Interview Room",
            "Screen 15 staged interview clips and flag each discomfort signal before the clip loops: barrier building, leaning away, foot withdrawal, jiggling feet, rubbing the forehead or neck, stroking the back of the head, preening, eye blocking, eyelid flutter, hard swallows, and throat clearing. Judge each flag as stress or deception - and remember the case of the Central Park jogger before you convict anyone.",
            "A video wall of interrogation clips where each suspect's body renders with distance tracks - lean-away arrows, foot-slide vectors, and barrier-growth bars - while a running caption reminds you that stress is not proof of deceit. Your flags land as colored pins on a body map.",
            [
                "Most people - both laypersons and professionals - are no better than chance, fifty-fifty, at detecting deception (Ekman & O'Sullivan, 1991)",
                "Even those truly gifted at detecting deception, probably less than 1 percent of the population, are seldom right more than 60 percent of the time",
                "The behaviors most often mistaken for dishonesty are primarily manifestations of stress, not deception (Ekman)",
                "The vaunted polygraph is accurate only 60 to 80 percent of the time, depending on the operator (Ford)",
                "In the New York Central Park jogger case, officers mistook nonverbals of stress for deception and pressured the innocent into confessions (Kassin)",
                "There is no single behavior that is indicative of deception - not one (Ekman)",
                "Navarro's Four-Domain Model of Detecting Deception (FBI Law Enforcement Bulletin, 2003) rests on limbic arousal and the comfort/discomfort domain",
                "Liars carry 'guilty knowledge' that places a distressing cognitive load on them as they fabricate answers (DePaulo et al., 1985)",
                "Discomfort shows first in physiology: heart rate quickens, hairs stand on end, perspiration increases, breathing quickens",
                "When scared, nervous, or uncomfortable we jiggle our feet, fidget, twist at the hips, or drum our fingers (de Becker)",
                "A desk or table blocks nearly 80 percent of the body surfaces you should observe, hiding the honest lower limbs - interview in an open space with no objects between you",
                "One FBI subject gradually built a barrier of soda cans, pencil holders, documents, and finally a backpack between himself and the interviewers (Box 57)",
            ],
        ),
        "dialogue": (
            "Dialogue: The Comfort-Zone Interrogation",
            "Play both sides of a workplace theft interview: as the interviewer, establish rapport, keep your tone neutral, ask clarifying follow-ups with pregnant pauses, and decide when a topic spike in pacifying behavior warrants pursuit; as the interviewee, leak discomfort through distancing, touch-withdrawal, and delayed head shakes while trying to appear relaxed. Earn rapport points by keeping the session synchronized, then catch the asynchrony that gives the lie away.",
            "A two-panel interview room: the interviewer's question cards on the left, the subject's live body map on the right where comfort shows as synchronized breathing waves and isopraxis mirror lines - and where discomfort fires red: lean-away, eye block, flutter, touch-loss. A rapport meter climbs or collapses with every choice you make.",
            [
                "How you behave affects the suspected liar: accusatory questions, sitting too close, and suspicious looks disrupt the comfort you need (Ekman, 1991)",
                "The moment you become suspicious - by word or look - you change how the person responds to you (Vrij)",
                "The best way to proceed is to ask for ever-more clarifying details: 'I don't understand' or 'Can you explain how that happened again?'",
                "Comfort shows when people move objects aside so nothing blocks the view, draw closer, and display the torso and insides of arms and legs - ventral access or fronting",
                "Isopraxism: two comfortable people mirror each other's leaning, posture, breathing rhythm, and tone - 'I am comfortable with you'",
                "Asynchrony is a barrier to communication: when harmony is missing, expressions are at odds and the interview fails",
                "A person who is flash frozen - tense, lacking movement while you are relaxed - signals no comfort even if things look all right (Knapp & Hall; Schafer & Navarro)",
                "Liars will rarely touch you; any diminution of touching during critical questions is more likely than not indicative of deception (Lieberman, 1998)",
                "A smile held for what seems an eternity after being caught is a discomfort display, not comfort",
                "If the head shakes as the person speaks, the statement can be relied upon; if the head movement is delayed until after the speech, the statement is most likely contrived",
                "Incongruity: someone says 'I didn't do it' while his head is slightly nodding in the affirmative",
                "Predators and habitual liars lock eyes with you: Machiavellian people actually increase eye contact during deception (Ekman)",
            ],
        ),
        "audit": (
            "Audit: The Pacifier Spike Log",
            "Run the twelve-point FBI pacifier protocol across three real or recorded conversations: clear view, expect pacifiers, allow initial nervousness, relax the subject first, establish the baseline, then log every spike in neck touching, nose stroking, lip licking, or collar ventilation and tag the exact question or information that triggered it. Flag the stress-in/stress-out sequence - distancing first, pacifying after - and decide which topics deserve pursuit.",
            "A scrolling interview timeline with a pacifier baseline drawn as a flat line and each spike as a red mountain labeled with the trigger question. A two-phase overlay shows the distancing moment in blue and the pacifying aftermath in red for every hard question.",
            [
                "Get a clear view: nothing should block your total view of the person, including a desk - human resource personnel should interview in a physically open space",
                "Expect some pacifying behaviors: people self-soothe throughout the day, like Navarro's daughter curling her hair strands to fall asleep",
                "Expect initial nervousness: a father asking about homework is not as stressful as asking why a son was expelled",
                "Get the person relaxed first: a good interviewer lets people calm down before exploring stressful topics",
                "Establish a baseline: once pacifying behaviors decrease and stabilize, use that level to assess future behavior",
                "Look for increased use of pacifiers: a spike in response to a specific question marks a troubled topic - a candidate ventilating his collar at one question identifies the issue to pursue",
                "Ask, pause, and observe: do not machine-gun questions; build in pregnant pauses and craft specific questions that elicit precise nonverbals",
                "Sustained staccato-like questioning produces false confessions - innocent people confess, even in writing, to terminate a stressful interview (Kassin, 2006)",
                "Keep the person focused: pointed questions elicit behavioral manifestations; free storytelling yields fewer useful nonverbals",
                "Chatter is not truth: the Macon, Georgia woman gave pages of plausible lies for three days that cost a year of investigation (Box 58)",
                "Stress comes in and goes out: a guilty person first shows distancing - foot withdrawal, leaning away, jaw and lip tightening - then pacifies with neck touching, nose stroking, or neck massaging",
                "Isolate the cause: nose touching relieves tension regardless of source - for everyone who touches the nose while lying, you will find a hundred who do it out of habit to relieve stress",
            ],
        ),
        "matrix": (
            "Matrix: Comfort x Synchrony x Emphasis Grid",
            "Build the three-axis paradigm grid Navarro proposes for sorting fact from fiction: each behavior you witness gets scored on comfort/discomfort, synchrony (verbal against nonverbal, emotion against event, time against place), and emphasis (the limbic brain's backing). Populate cells with case evidence - the kidnapped-infant parents, the delayed drowning report, the nodding denial - and lock the verdict before the corroboration timer expires.",
            "A courtroom evidence wall with three glowing axes; each case snapshot you place casts a shadow across the grid that either lines up with truth or bends out of line. Cells where all three axes agree pulse green; skewed shadows render in jagged red.",
            [
                "Those who are truthful and comfortable display more emphatic behaviors; the model shows how comfort and truthfulness go together",
                "Synchrony of speech and head movement: an affirmative answer should have congruent head movement that immediately supports what is said - not delayed",
                "Asynchrony is demonstrated when a woman states 'I did not do it' while her head nods affirmatively, or a man nods slightly while answering 'No' to 'Would you lie about this?'",
                "There should be synchrony between events and emotions: parents reporting a kidnapping should be distraught, clamoring for help, eager to retell every detail - not placid and self-concerned",
                "There should be synchrony of time and place: delaying the report of a drowning or traveling to another jurisdiction to report it rightfully comes under suspicion",
                "Emphasis is the limbic brain's contribution to communication, a way to let others know how potently we feel - and emphasis is universal when people are genuine",
                "For the most part, liars do not emphasize (Lieberman): they engage the cognitive brain in what to say, rarely in how to present it",
                "Nonverbal emphasis includes hand gestures, pounding a desk, raising the knee staccato-like, and rising up on the balls of the feet",
                "Gravity-defying gestures are emblematic of emphasis and true sentiment, something liars rarely display",
                "De-emphasis shows as speaking behind the hands, limited facial expression, and movement restriction - withdrawal when not committed to one's own words",
                "Deceptive people show deliberative, pensive displays - fingers to the chin, stroking of cheeks - as though still thinking about what to say",
                "Any sudden change in movement reflects brain activity: when arms shift from animated to still, there must be a reason, be it dejection or possibly deception (Vrij)",
            ],
        ),
        "boss": (
            "Boss Battle: The Palm-Down Verdict",
            "You are the behavioral consultant at a criminal deposition: 10 declarative statements play back-to-back and you must stamp each one TRUTH or SUSPECT under time pressure, reading only the posture and hand logic - the palms-up rogatory position, the white-knuckled ejector-seat grip, the abridged shrug, the turtle-effect slump, the fetal fold. Land 8 of 10 verdicts, then explain why even you remain only a blink away from chance.",
            "A dim deposition room where each statement arrives as a hologram: palm orientation renders as glowing shields - up shields flicker gold, down shields sit solid - while posture renders as body wireframes that sink, fold, or lock. A 90-second fuse burns as your verdict stamp swings toward the evidence glass.",
            [
                "The rogatory or 'prayerful' display - outstretched arms with palms up - indicates the person wants to be believed or accepted; it is not a dominant, confident display",
                "A passionate assertion like 'You have to believe me, I did not kill her' should come with hands palm down; made palms up, the statement is highly suspect",
                "The truthful don't have to plead to be believed; they make a statement and it stands",
                "When confident and comfortable we spread out; when less secure we take up less space, and in extreme distress people fold arms and legs into an almost fetal position",
                "Uncomfortable conversations evoke withdrawn postures: arms intertwined like a pretzel and ankles locked, sometimes to the point of being almost painful to observe",
                "People being deceitful stoop or sink into the furniture as if escaping what is being said - the 'turtle effect' of hiding in the open",
                "The liar's shrug is abnormal, abridged and customized: only one shoulder rises, or the shoulders rise nearly to the ears and the head seems to disappear",
                "Navarro has never heard a person lying yell affirmatively 'I didn't do it' while pounding a fist on the table - false declarative statements come with weak, nonemphatic gestures",
                "As with the fake smile, false statements come with weak or passive nonverbals: the limbic brain simply will not be committed to the ruse",
                "The sentiments of the limbic brain are hard to override - try to smile fully at someone you dislike and feel how difficult it is",
                "There is no 'Pinocchio effect' when it comes to deception (Dr. Mark G. Frank): comfort/discomfort, synchrony, and emphasis are a guide or paradigm, and that is all",
                "Be careful not to label someone a liar with limited information or one observation - even the best experts are only a blink away from chance, fifty-fifty at best",
            ],
        ),
    },
    {
        "num": 9,
        "title": "Some Final Thoughts",
        "pages": "300-350",
        "domain": D,
        "scrub": (
            "Cue Scrubber: Ground-Level Signs - The Two Languages of the Body",
            "Screen 15 everyday clips and sort each cue into its sign system before the clip loops: the verbal sign on the pole - the words, tone, and pitch we are trained to hear - versus the nonverbal sign on the ground - the body display that has always been there. Flag which system each cue belongs to and replay the Coral Gables lesson: once you know where to look, the signs become obvious and unmistakable.",
            "A strange street at dusk where glowing street signs hang on poles while six-inch stone blocks sit at ground level, half-hidden by grass; every clip drops a human figure between them and you pin each behavior to the pole or the pavement. Finding a ground sign makes it flare bright and unmistakable.",
            [
                "A friend driving from Tampa to Coral Gables drove twenty minutes through unmarked intersections before a gas station proprietor revealed the secret: 'When you reach the intersection, you need to look down, not up'",
                "Coral Gables street signs are six-inch weathered stone blocks with painted names placed on the ground just off the pavement",
                "'Once I knew what to look for and where to look, the signs were obvious and unmistakable. I had no trouble finding my way.'",
                "This book is about signs, too: when it comes to human behavior there are basically two kinds of signs, verbal and nonverbal",
                "All of us have been taught to look for and identify the verbal signs - by analogy, the ones located on poles, clearly visible as we drive down the streets of a strange city",
                "The nonverbal signs have always been there, but many of us have not learned to spot them because we have not been trained to look for signs located at ground level",
                "Once we learn to attend to and read nonverbal signs, our reactions mirror the friend's: what was hidden becomes obvious and unmistakable",
                "Understanding nonverbal behavior yields a deeper, more meaningful view of the world around you",
                "The spoken and silent languages combine to present the full, rich tapestry of human experience in all of its delightful complexity",
                "You now possess knowledge that will enrich your interpersonal relationships for the rest of your life",
            ],
        ),
        "dialogue": (
            "Dialogue: The Street-Corner Orientation",
            "Play the gas station proprietor giving the orientation: a traveler has driven twenty minutes without seeing a single sign, and you must decide where the signal system actually lives - on the poles or at ground level - then guide her through a real conversation scene, pointing out the ground-level body cues she was never trained to see: the eye block after an offer, the lip purse at a contract line, the pacifier spike at a hard question. Earn the traveler's trust and she will find her destination in minutes.",
            "A gas station counter by day and the same corner by night: the traveler's car idles while a dialogue tree hangs like a menu board; on the street, pole signs glow high while stone-block signs wait in the grass. Every answer you give lights another ground-level cue in the conversation scene beside the car.",
            [
                "When you reach the intersection, you need to look down, not up - the advice that solved the Coral Gables search",
                "Verbal signs sit on poles: we are all trained to see and hear the words, tone, and pitch of what people say",
                "Nonverbal signs sit at ground level: the feet, legs, torso, and hands have always been there but untrained eyes pass them by",
                "The failure was not effort but location - the driver looked six feet or more above the ground for signs six inches off it",
                "Once the searcher knows what to look for and where to look, the signs become obvious and unmistakable",
                "In any interaction, ask where the signs are before reading them: context tells you which sign system carries the message",
                "The same body display changes meaning by setting - the sign on the pole and the sign on the ground must be read together",
                "Comfort displays such as head tilt and fronting, and discomfort displays such as eye blocking and distancing, all live at ground level",
                "Every successful read in this book was a ground-level sign found by a trained search",
                "The two languages - spoken and silent - combine to present the full, rich tapestry of human experience",
            ],
        ),
        "audit": (
            "Audit: The Observer's Sign-System Inventory",
            "Conduct a week-long audit of your own observation habits: for each of ten interactions, log which signs you attended to (verbal content, tone) and which ground-level signs you captured (eye blocks, lip compression, pacifiers, head-tilt exposure, foot position), then score the gap. Replay the Coral Gables test: after logging the ground-level inventory, re-watch the same interaction and count how many signs that were 'not there' before are now obvious and unmistakable.",
            "A split-screen journal: the left track logs spoken content as pole-signs, the right track renders the same conversation as ground-level body pins that multiply on the re-watch pass. A 'before and after knowing where to look' counter flips from single digits to a full constellation.",
            [
                "Keep a baseline first: a person's normal ground-level display before the topic shifts is the map for the search",
                "Clusters of behavior validate a reading; a single cue can mislead, so confirm every sign with corroborating displays",
                "Context governs interpretation - the same shrug, glance, or crossed arm means different things by setting and culture",
                "The comfort/discomfort equation is the organizing principle of the ground-level sign system",
                "The limbic brain is the honest part of the brain; the neocortex fabricates - trust the displays the limbic brain compels",
                "Delayed or incongruent signals, like a head nodding while denying, are contradictions between the two sign systems",
                "The face can mislead; compare it against the nonverbals of the rest of the body before validating any emotion",
                "If a facial expression confuses you, reenact it and sense how it makes you feel",
                "Eye blocking occurs in real time as soon as something negative is heard - one of the best signals that something spoken did not sit well",
                "Pacifiers spike precisely when a topic troubles the speaker; the spike, not the pacifier, is the clue",
                "Gravity-defying behaviors - head tilt, raised brow, risen chin - mark comfort and true sentiment wherever they appear",
                "When verbal and nonverbal signs conflict, side with the negative emotion as the more honest of the two",
            ],
        ),
        "matrix": (
            "Matrix: Sign Type x Location x Setting Grid",
            "Build the final cross-reference grid of the book: map every behavior family (face, eyes, mouth, hands, torso, feet) against its sign location (pole-level or ground-level) and its home setting (interview, courtship, negotiation, family), then lock in the interpretation each cell deserves. Complete the grid and compare it against the Coral Gables map: same signs, but only the trained eye sees them at ground level.",
            "A library wall where the grid renders like a city map: pole signs stand tall above each setting while ground-level signs nestle at pavement height, glowing only after you place them. Completed cells stitch into a street map of the whole book's territory.",
            [
                "Feet and legs are the most honest part of the body: they escape training and betray true sentiment while the face is being managed",
                "Eye blocking protects the brain from undesirable images and appears the instant negative information arrives",
                "Lip compression and disappearing lips mark the exact moment a difficult question lands as a negative stimulus",
                "Head tilt to the side and neck exposure are high-comfort displays nearly impossible to mimic when tense",
                "Pacifiers such as neck touching and nose stroking spike when a topic troubles the speaker, whatever the reason",
                "Each setting - interview, courtship, negotiation, family - changes the meaning of the same sign, so context always precedes interpretation",
                "The limbic brain compels these behaviors regardless of conscious intent; that is precisely why they are reliable",
                "Facial expressions such as happiness, sadness, anger, fear, surprise, and disgust are the universal language - our human crosscultural lingua franca",
                "The rule of mixed signals: when the face sends happiness alongside anxiety, always side with the negative emotion as the more accurate",
                "The comfort/discomfort, synchrony, and emphasis paradigm is the road map that turns the matrix into a usable street map",
                "There is no single behavior indicative of deception - only clusters, context, and corroboration can assure veracity",
                "The Coral Gables principle: the sign system has always been there; the matrix teaches you where to look so the signs become obvious and unmistakable",
            ],
        ),
        "boss": (
            "Boss Battle: The Coral Gables Final Exam",
            "The final timed examination: 12 interaction clips from every chapter of the book, and for each you must stamp the verdict - COMFORT or DISCOMFORT, SYNCHRONOUS or ASYNCHRONOUS, EMPHATIC or FLAT - before the street-map timer burns out. Nail 10 of 12 and the map of Coral Gables resolves on screen: you found the street signs at ground level because you finally knew where to look.",
            "A night city of unmarked intersections: each clip drops a glowing figure at a corner and a compass of verdicts spins around it; correct calls light the six-inch stone blocks under the figure's feet, one by one, until the whole street map of the book's knowledge glows at ground level.",
            [
                "Each encounter resolves through the paradigm: comfort or discomfort, synchrony or asynchrony, emphasis or its absence",
                "No single cue decides a verdict - only clusters of behavior solidify your observations",
                "Context is the map: the same sign changes meaning from street to street, from setting to setting",
                "When signals conflict, side with the negative emotion - our most immediate reaction is usually the most accurate",
                "A delayed head movement after a denial marks the statement as contrived rather than part of the natural flow",
                "The palms-up rogatory position asks to be believed; the truthful make a statement and it stands",
                "Discomfort distances: barriers, leaning away, and feet toward the exit accompany unease and possible deceit",
                "Emphasis is the limbic brain's backing of true sentiment; its absence marks a lack of commitment to the words",
                "Even the best experts are only a blink away from chance - stay humble, keep asking, and corroborate",
                "You now possess two languages, spoken and silent, that combine to present the full, rich tapestry of human experience",
                "Look down, not up: the reliable signs are the ones you were never trained to see, and they have always been there",
                "Enjoy knowing what every body is saying - to that end Navarro dedicated himself and this book",
            ],
        ),
    },
]
